src/lib/edje_script_only.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_script_only.c File Reference
Data Structures
struct _Oid
struct _Sinfo
Macros
#define ADDJ(type, func) si->job.type = ecore_job_add(func, ed);
#define CLFN(func) IFFN(func) {_call_fn(ed, #func, si->fn.func);}
#define DELJ(type) if (si->job.type) ecore_job_del(si->job.type);
#define EXPF(func) embryo_program_native_call_add(ed->collection->script, #func, _exp_##func)
#define GTFN(func) si->fn.func = embryo_program_function_find(ed->collection->script, #func)
#define IFFN(func) if (si->fn.func != EMBRYO_FUNCTION_NONE)
#define IFNJ(type) if (!si->job.type)
#define IFNO(func) if (si->fn.func == EMBRYO_FUNCTION_NONE)
#define PINT(val) embryo_parameter_cell_push(ed->collection->script, (Embryo_Cell)(val))
#define PSTR(val) embryo_parameter_string_push(ed->collection->script, val)
#define SI Sinfo *si; si = ed->script_only_data; if (!si) return
#define SI_RETURN(ret) Sinfo *si; si = ed->script_only_data; if (!si) return (ret)
#define ZERJ(type) si->job.type = NULL;
Typedefs
typedef struct _Oid Oid
typedef struct _Sinfo Sinfo
Functions
Eina_Bool _edje_script_only (Edje *ed)
void _edje_script_only_hide (Edje *ed)
void _edje_script_only_init (Edje *ed)
void _edje_script_only_message (Edje *ed, Edje_Message *em)
void _edje_script_only_move (Edje *ed)
void _edje_script_only_resize (Edje *ed)
void _edje_script_only_show (Edje *ed)
void _edje_script_only_shutdown (Edje *ed)
Macro Definition Documentation
ADDJ
#define ADDJ (type, func) si->job.type = ecore_job_add(func, ed);
CLFN
#define CLFN (func) IFFN(func) {_call_fn(ed, #func, si->fn.func);}
DELJ
#define DELJ (type) if (si->job.type) ecore_job_del(si->job.type);
EXPF
#define EXPF (func) embryo_program_native_call_add(ed->collection->script, #func, _exp_##func)
GTFN
#define GTFN (func) si->fn.func = embryo_program_function_find(ed->collection->script, #func)
IFFN
#define IFFN (func) if (si->fn.func != EMBRYO_FUNCTION_NONE)
IFNJ
#define IFNJ (type) if (!si->job.type)
IFNO
#define IFNO (func) if (si->fn.func == EMBRYO_FUNCTION_NONE)
PINT
#define PINT (val) embryo_parameter_cell_push(ed->collection->script, (Embryo_Cell)(val))
PSTR
#define PSTR (val) embryo_parameter_string_push(ed->collection->script, val)
SI
#define SI Sinfo *si; si = ed->script_only_data; if (!si) return
SI_RETURN
#define SI_RETURN (ret) Sinfo *si; si = ed->script_only_data; if (!si) return (ret)
ZERJ
#define ZERJ (type) si->job.type = NULL;
Typedef Documentation
Oid
typedef struct _Oid Oid
Sinfo
typedef struct _Sinfo Sinfo
Function Documentation
_edje_script_only()
Eina_Bool _edje_script_only (Edje * ed)
References _Edje::collection, _Edje_Part_Collection::script, and _Edje_Part_Collection::script_only.
Referenced by _edje_message_process().
_edje_script_only_hide()
void _edje_script_only_hide (Edje * ed)
References ADDJ, DELJ, IFFN, IFNJ, and SI.
_edje_script_only_init()
void _edje_script_only_init (Edje * ed)
References _edje_script_only_move(), CLFN, _Edje::collection, EXPF, GTFN, _Edje_Part_Collection::script, and _Edje::script_only_data.
_edje_script_only_message()
void _edje_script_only_message (Edje * ed, Edje_Message * em)
References _edje_message_parameters_push(), CLFN, IFNO, and SI.
Referenced by _edje_message_process().
_edje_script_only_move()
void _edje_script_only_move (Edje * ed)
References ADDJ, DELJ, and SI.
Referenced by _edje_script_only_init().
_edje_script_only_resize()
void _edje_script_only_resize (Edje * ed)
References ADDJ, DELJ, IFFN, and SI.
_edje_script_only_show()
void _edje_script_only_show (Edje * ed)
References ADDJ, DELJ, IFFN, IFNJ, and SI.
_edje_script_only_shutdown()
void _edje_script_only_shutdown (Edje * ed)
References CLFN, DELJ, and SI.
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59