src/lib/edje_var.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_var.c File Reference
Functions
int _edje_var_anim_add (Edje *ed, double len, const char *fname, int val)
void _edje_var_anim_del (Edje *ed, int id)
double _edje_var_float_get (Edje *ed, int id)
void _edje_var_float_set (Edje *ed, int id, double v)
void _edje_var_free (Edje_Var *var)
void _edje_var_init (Edje *ed)
int _edje_var_int_get (Edje *ed, int id)
void _edje_var_int_set (Edje *ed, int id, int v)
int _edje_var_list_count_get (Edje *ed, int id)
void _edje_var_list_float_append (Edje *ed, int id, double v)
void _edje_var_list_float_insert (Edje *ed, int id, int n, double v)
void _edje_var_list_float_prepend (Edje *ed, int id, double v)
void _edje_var_list_int_append (Edje *ed, int id, int v)
void _edje_var_list_int_insert (Edje *ed, int id, int n, int v)
void _edje_var_list_int_prepend (Edje *ed, int id, int v)
Edje_Var * _edje_var_list_nth (Edje *ed, int id, int n)
double _edje_var_list_nth_float_get (Edje *ed, int id, int n)
void _edje_var_list_nth_float_set (Edje *ed, int id, int n, double v)
int _edje_var_list_nth_int_get (Edje *ed, int id, int n)
void _edje_var_list_nth_int_set (Edje *ed, int id, int n, int v)
const char * _edje_var_list_nth_str_get (Edje *ed, int id, int n)
void _edje_var_list_nth_str_set (Edje *ed, int id, int n, const char *v)
void _edje_var_list_remove_nth (Edje *ed, int id, int n)
void _edje_var_list_str_append (Edje *ed, int id, const char *v)
void _edje_var_list_str_insert (Edje *ed, int id, int n, const char *v)
void _edje_var_list_str_prepend (Edje *ed, int id, const char *v)
void _edje_var_list_var_append (Edje *ed, int id, Edje_Var *var)
void _edje_var_list_var_append_relative (Edje *ed, int id, Edje_Var *var, Edje_Var *relative)
void _edje_var_list_var_prepend (Edje *ed, int id, Edje_Var *var)
void _edje_var_list_var_prepend_relative (Edje *ed, int id, Edje_Var *var, Edje_Var *relative)
Edje_Var * _edje_var_new (void)
void _edje_var_shutdown (Edje *ed)
const char * _edje_var_str_get (Edje *ed, int id)
void _edje_var_str_set (Edje *ed, int id, const char *str)
int _edje_var_string_id_get (Edje *ed, const char *string)
int _edje_var_timer_add (Edje *ed, double in, const char *fname, int val)
void _edje_var_timer_del (Edje *ed, int id)
double _edje_var_var_float_get (Edje *ed __UNUSED__, Edje_Var *var)
void _edje_var_var_float_set (Edje *ed __UNUSED__, Edje_Var *var, double v)
int _edje_var_var_int_get (Edje *ed __UNUSED__, Edje_Var *var)
void _edje_var_var_int_set (Edje *ed __UNUSED__, Edje_Var *var, int v)
const char * _edje_var_var_str_get (Edje *ed __UNUSED__, Edje_Var *var)
void _edje_var_var_str_set (Edje *ed __UNUSED__, Edje_Var *var, const char *str)
Function Documentation
_edje_var_anim_add()
int _edje_var_anim_add (Edje * ed, double len, const char * fname, int val)
References _Edje_Var_Pool::animators, _Edje::collection, _Edje_Var_Animator::edje, _Edje_Var_Animator::func, _Edje_Var_Animator::id, _Edje_Var_Pool::id_count, _Edje_Var_Animator::len, _Edje_Part_Collection::script, _Edje_Var_Animator::start, _Edje_Var_Animator::val, and _Edje::var_pool.
_edje_var_anim_del()
void _edje_var_anim_del (Edje * ed, int id)
_edje_var_float_get()
double _edje_var_float_get (Edje * ed, int id)
References _edje_var_var_float_get(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_float_set()
void _edje_var_float_set (Edje * ed, int id, double v)
References _edje_var_var_float_set(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_free()
void _edje_var_free (Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_STRING, _Edje_Var::s, _Edje_Var::type, and _Edje_Var_String::v.
Referenced by _edje_var_list_remove_nth(), and _edje_var_shutdown().
_edje_var_init()
void _edje_var_init (Edje * ed)
References _Edje::collection, _Edje_Part_Collection::script, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_int_get()
int _edje_var_int_get (Edje * ed, int id)
References _edje_var_var_int_get(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_int_set()
void _edje_var_int_set (Edje * ed, int id, int v)
References _edje_var_var_int_set(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_count_get()
int _edje_var_list_count_get (Edje * ed, int id)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_float_append()
void _edje_var_list_float_append (Edje * ed, int id, double v)
References _edje_var_list_var_append(), _edje_var_new(), _edje_var_var_float_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_float_insert()
void _edje_var_list_float_insert (Edje * ed, int id, int n, double v)
References _edje_var_list_nth(), _edje_var_list_var_append(), _edje_var_list_var_prepend_relative(), _edje_var_new(), _edje_var_var_float_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_float_prepend()
void _edje_var_list_float_prepend (Edje * ed, int id, double v)
References _edje_var_list_var_prepend(), _edje_var_new(), _edje_var_var_float_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_int_append()
void _edje_var_list_int_append (Edje * ed, int id, int v)
References _edje_var_list_var_append(), _edje_var_new(), _edje_var_var_int_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_int_insert()
void _edje_var_list_int_insert (Edje * ed, int id, int n, int v)
References _edje_var_list_nth(), _edje_var_list_var_append(), _edje_var_list_var_prepend_relative(), _edje_var_new(), _edje_var_var_int_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_int_prepend()
void _edje_var_list_int_prepend (Edje * ed, int id, int v)
References _edje_var_list_var_prepend(), _edje_var_new(), _edje_var_var_int_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth()
Edje_Var* _edje_var_list_nth (Edje * ed, int id, int n)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_var_list_float_insert(), _edje_var_list_int_insert(), _edje_var_list_nth_float_get(), _edje_var_list_nth_float_set(), _edje_var_list_nth_int_get(), _edje_var_list_nth_int_set(), _edje_var_list_nth_str_get(), _edje_var_list_nth_str_set(), and _edje_var_list_str_insert().
_edje_var_list_nth_float_get()
double _edje_var_list_nth_float_get (Edje * ed, int id, int n)
References _edje_var_list_nth(), _edje_var_var_float_get(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_float_set()
void _edje_var_list_nth_float_set (Edje * ed, int id, int n, double v)
References _edje_var_list_nth(), _edje_var_var_float_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_int_get()
int _edje_var_list_nth_int_get (Edje * ed, int id, int n)
References _edje_var_list_nth(), _edje_var_var_int_get(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_int_set()
void _edje_var_list_nth_int_set (Edje * ed, int id, int n, int v)
References _edje_var_list_nth(), _edje_var_var_int_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_str_get()
const char* _edje_var_list_nth_str_get (Edje * ed, int id, int n)
References _edje_var_list_nth(), _edje_var_var_str_get(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_str_set()
void _edje_var_list_nth_str_set (Edje * ed, int id, int n, const char * v)
References _edje_var_list_nth(), _edje_var_var_str_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_remove_nth()
void _edje_var_list_remove_nth (Edje * ed, int id, int n)
References _edje_var_free(), _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_str_append()
void _edje_var_list_str_append (Edje * ed, int id, const char * v)
References _edje_var_list_var_append(), _edje_var_new(), _edje_var_var_str_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_str_insert()
void _edje_var_list_str_insert (Edje * ed, int id, int n, const char * v)
References _edje_var_list_nth(), _edje_var_list_var_append(), _edje_var_list_var_prepend_relative(), _edje_var_new(), _edje_var_var_str_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_str_prepend()
void _edje_var_list_str_prepend (Edje * ed, int id, const char * v)
References _edje_var_list_var_prepend(), _edje_var_new(), _edje_var_var_str_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_var_append()
void _edje_var_list_var_append (Edje * ed, int id, Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_var_list_float_append(), _edje_var_list_float_insert(), _edje_var_list_int_append(), _edje_var_list_int_insert(), _edje_var_list_str_append(), and _edje_var_list_str_insert().
_edje_var_list_var_append_relative()
void _edje_var_list_var_append_relative (Edje * ed, int id, Edje_Var * var, Edje_Var * relative)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_var_prepend()
void _edje_var_list_var_prepend (Edje * ed, int id, Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_var_list_float_prepend(), _edje_var_list_int_prepend(), and _edje_var_list_str_prepend().
_edje_var_list_var_prepend_relative()
void _edje_var_list_var_prepend_relative (Edje * ed, int id, Edje_Var * var, Edje_Var * relative)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_var_list_float_insert(), _edje_var_list_int_insert(), and _edje_var_list_str_insert().
_edje_var_new()
Edje_Var* _edje_var_new (void)
Referenced by _edje_var_list_float_append(), _edje_var_list_float_insert(), _edje_var_list_float_prepend(), _edje_var_list_int_append(), _edje_var_list_int_insert(), _edje_var_list_int_prepend(), _edje_var_list_str_append(), _edje_var_list_str_insert(), and _edje_var_list_str_prepend().
_edje_var_shutdown()
void _edje_var_shutdown (Edje * ed)
References _edje_var_free(), _Edje_Var_Pool::animators, _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_STRING, _Edje_Var::l, _Edje_Var::s, _Edje_Var_Pool::size, _Edje_Var_Timer::timer, _Edje_Var_Pool::timers, _Edje_Var::type, _Edje_Var_String::v, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_file_del().
_edje_var_str_get()
const char* _edje_var_str_get (Edje * ed, int id)
References _edje_var_var_str_get(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_str_set()
void _edje_var_str_set (Edje * ed, int id, const char * str)
References _edje_var_var_str_set(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_string_id_get()
int _edje_var_string_id_get (Edje * ed, const char * string)
References _Edje::collection, and _Edje_Part_Collection::script.
_edje_var_timer_add()
int _edje_var_timer_add (Edje * ed, double in, const char * fname, int val)
References _Edje::collection, _Edje_Var_Timer::edje, _Edje_Var_Timer::func, _Edje_Var_Timer::id, _Edje_Var_Pool::id_count, _Edje_Part_Collection::script, _Edje_Var_Timer::timer, _Edje_Var_Timer::val, and _Edje::var_pool.
_edje_var_timer_del()
void _edje_var_timer_del (Edje * ed, int id)
_edje_var_var_float_get()
double _edje_var_var_float_get (Edje *ed __UNUSED__, Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_FLOAT, EDJE_VAR_HASH, EDJE_VAR_INT, EDJE_VAR_LIST, EDJE_VAR_NONE, EDJE_VAR_STRING, _Edje_Var::f, _Edje_Var::i, _Edje_Var::s, _Edje_Var::type, _Edje_Var_Int::v, _Edje_Var_Float::v, and _Edje_Var_String::v.
Referenced by _edje_var_float_get(), and _edje_var_list_nth_float_get().
_edje_var_var_float_set()
void _edje_var_var_float_set (Edje *ed __UNUSED__, Edje_Var * var, double v)
References _Edje_Var::data, EDJE_VAR_FLOAT, EDJE_VAR_HASH, EDJE_VAR_INT, EDJE_VAR_LIST, EDJE_VAR_NONE, EDJE_VAR_STRING, _Edje_Var::f, _Edje_Var::s, _Edje_Var::type, _Edje_Var_Float::v, and _Edje_Var_String::v.
Referenced by _edje_var_float_set(), _edje_var_list_float_append(), _edje_var_list_float_insert(), _edje_var_list_float_prepend(), and _edje_var_list_nth_float_set().
_edje_var_var_int_get()
int _edje_var_var_int_get (Edje *ed __UNUSED__, Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_FLOAT, EDJE_VAR_HASH, EDJE_VAR_INT, EDJE_VAR_LIST, EDJE_VAR_NONE, EDJE_VAR_STRING, _Edje_Var::f, _Edje_Var::i, _Edje_Var::s, _Edje_Var::type, _Edje_Var_Int::v, _Edje_Var_Float::v, and _Edje_Var_String::v.
Referenced by _edje_var_int_get(), and _edje_var_list_nth_int_get().
_edje_var_var_int_set()
void _edje_var_var_int_set (Edje *ed __UNUSED__, Edje_Var * var, int v)
References _Edje_Var::data, EDJE_VAR_FLOAT, EDJE_VAR_HASH, EDJE_VAR_INT, EDJE_VAR_LIST, EDJE_VAR_NONE, EDJE_VAR_STRING, _Edje_Var::i, _Edje_Var::s, _Edje_Var::type, _Edje_Var_Int::v, and _Edje_Var_String::v.
Referenced by _edje_var_int_set(), _edje_var_list_int_append(), _edje_var_list_int_insert(), _edje_var_list_int_prepend(), and _edje_var_list_nth_int_set().
_edje_var_var_str_get()
const char* _edje_var_var_str_get (Edje *ed __UNUSED__, Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_FLOAT, EDJE_VAR_HASH, EDJE_VAR_INT, EDJE_VAR_LIST, EDJE_VAR_NONE, EDJE_VAR_STRING, _Edje_Var::f, _Edje_Var::i, _Edje_Var::s, _Edje_Var::type, _Edje_Var_Int::v, _Edje_Var_Float::v, and _Edje_Var_String::v.
Referenced by _edje_var_list_nth_str_get(), and _edje_var_str_get().
_edje_var_var_str_set()
void _edje_var_var_str_set (Edje *ed __UNUSED__, Edje_Var * var, const char * str)
References _Edje_Var::data, EDJE_VAR_FLOAT, EDJE_VAR_HASH, EDJE_VAR_INT, EDJE_VAR_LIST, EDJE_VAR_NONE, EDJE_VAR_STRING, _Edje_Var::s, _Edje_Var::type, and _Edje_Var_String::v.
Referenced by _edje_var_list_nth_str_set(), _edje_var_list_str_append(), _edje_var_list_str_insert(), _edje_var_list_str_prepend(), and _edje_var_str_set().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59