src/lib/edje_main.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_main.c File Reference
Functions
void _edje_clean_objects (Edje *ed)
void _edje_del (Edje *ed)
void _edje_lib_ref (void)
void _edje_lib_unref (void)
void _edje_ref (Edje *ed)
void _edje_unref (Edje *ed)
EAPI int edje_init (void)
Initialize the Edje library.
EAPI int edje_shutdown (void)
Shutdown the Edje library.
Variables
int _edje_default_log_dom = -1
Eina_Mempool * _edje_real_part_mp = NULL
Eina_Mempool * _edje_real_part_state_mp = NULL
EAPI Edje_Version * edje_version = &_version
Function Documentation
_edje_clean_objects()
void _edje_clean_objects (Edje * ed)
References _Edje::base, and _Edje::obj.
_edje_del()
void _edje_del (Edje * ed)
References _edje_animators, _edje_callbacks_patterns_clean(), _edje_file_del(), _edje_message_del(), _Edje::actions, _Edje::callbacks, _Edje::color_classes, _Edje::delete_me, _Edje_Text_Class::font, _Edje::group, _Edje::markup_filter_callbacks, _Edje_Text_Class::name, _Edje::parent, _Edje_Text_Insert_Filter_Callback::part, _Edje::path, _Edje::pending_actions, _Edje::processing_messages, _Edje_Signal_Callback::signal, _Edje_Signal_Callback::source, _Edje::text_classes, and _Edje::text_insert_filter_callbacks.
Referenced by _edje_unref().
_edje_lib_ref()
void _edje_lib_ref (void)
Referenced by edje_object_add().
_edje_lib_unref()
void _edje_lib_unref (void)
_edje_ref()
void _edje_ref (Edje * ed)
References _Edje::references.
Referenced by _edje_block(), _edje_emit_handle(), _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), and _edje_timer_cb().
_edje_unref()
void _edje_unref (Edje * ed)
References _edje_del(), and _Edje::references.
Referenced by _edje_file_del(), _edje_program_end(), _edje_program_run_iterate(), _edje_timer_cb(), and _edje_unblock().
edje_init()
EAPI int edje_init (void)
Initialize the Edje library.
Returns
The new init count. The initial value is zero.
This function initializes the Ejde library, making the proper calls to internal initialization functions. It will also initialize its dependencies, making calls to eina_init(), ecore_init(), embryo_init() and eet_init(). So, there is no need to call those functions again, in your code. To shutdown Edje there is the function edje_shutdown().
See also
edje_shutdown()
eina_init()
ecore_init()
embryo_init()
eet_init()
edje_shutdown()
EAPI int edje_shutdown (void)
Shutdown the Edje library.
Returns
The number of times the library has been initialised without being shutdown.
This function shuts down the Edje library. It will also call the shutdown functions of its dependencies, which are eina_shutdown(), ecore_shutdown(), embryo_shutdown() and eet_shutdown(), so there is no need to call these functions again, in your code.
See also
edje_init()
eina_shutdown()
ecore_shutdown()
embryo_shutdown()
eet_shutdown()
Variable Documentation
_edje_default_log_dom
int _edje_default_log_dom = -1
Referenced by _edje_lua2_error_full().
_edje_real_part_mp
Eina_Mempool* _edje_real_part_mp = NULL
Referenced by _edje_file_del().
_edje_real_part_state_mp
Eina_Mempool* _edje_real_part_state_mp = NULL
Referenced by _edje_file_del(), and _edje_part_description_apply().
edje_version
EAPI Edje_Version* edje_version = &_version
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59