src/lib/edje_util.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_util.c File Reference
Data Structures
struct _Edje_Box_Layout
struct _Edje_List_Foreach_Data
struct _Edje_List_Refcount
struct edje_box_layout_builtin
Macros
#define EDJE_PRELOAD_EMISSION "preload,done"
#define EDJE_PRELOAD_SOURCE NULL
#define FASTFREEZE 1
#define S(_r, _g, _b, _a) X(_r); X(_g); X(_b); X(_a)
#define S(_r, _g, _b, _a) X(_r); X(_g); X(_b); X(_a)
#define S(_r, _g, _b, _a) X(_r); X(_g); X(_b); X(_a)
#define S(_r, _g, _b, _a) X(_r); X(_g); X(_b); X(_a)
#define X(C)
#define X(C)
#define X(C)
#define X(C)
Typedefs
typedef struct _Edje_Box_Layout Edje_Box_Layout
typedef struct _Edje_List_Foreach_Data Edje_List_Foreach_Data
typedef struct _Edje_List_Refcount Edje_List_Refcount
Functions
int _edje_block (Edje *ed)
int _edje_block_break (Edje *ed)
void _edje_block_violate (Edje *ed)
void _edje_box_init (void)
Eina_Bool _edje_box_layout_find (const char *name, Evas_Object_Box_Layout *cb, void **data, void(**free_data)(void *data))
void _edje_box_shutdown (void)
Evas_Object * _edje_children_get (Edje_Real_Part *rp, const char *partid)
Edje_Color_Class * _edje_color_class_find (Edje *ed, const char *color_class)
void _edje_color_class_hash_free (void)
void _edje_color_class_member_add (Edje *ed, const char *color_class)
void _edje_color_class_member_del (Edje *ed, const char *color_class)
void _edje_color_class_member_direct_del (const char *color_class, void *l)
void _edje_color_class_members_free (void)
void _edje_color_class_on_del (Edje *ed, Edje_Part *ep)
Edje * _edje_fetch (const Evas_Object *obj)
int _edje_freeze (Edje *ed)
char * _edje_merge_path (const char *alias, char *const *path)
void _edje_object_orientation_inform (Evas_Object *obj)
void _edje_object_part_swallow_changed_hints_cb (void *data, __UNUSED__ Evas *e, __UNUSED__ Evas_Object *obj, __UNUSED__ void *event_info)
void _edje_object_part_swallow_free_cb (void *data, Evas *e __UNUSED__, Evas_Object *obj __UNUSED__, void *event_info __UNUSED__)
Eina_Bool _edje_object_part_text_raw_append (Evas_Object *obj, Edje_Real_Part *rp, const char *part, const char *text)
Eina_Bool _edje_object_part_text_raw_set (Evas_Object *obj, Edje_Real_Part *rp, const char *part, const char *text)
EAPI void _edje_program_insert (Edje_Part_Collection *edc, Edje_Program *p)
EAPI void _edje_program_remove (Edje_Part_Collection *edc, Edje_Program *p)
Eina_Bool _edje_real_part_box_append (Edje_Real_Part *rp, Evas_Object *child_obj)
Eina_Bool _edje_real_part_box_insert_at (Edje_Real_Part *rp, Evas_Object *child_obj, unsigned int pos)
Eina_Bool _edje_real_part_box_insert_before (Edje_Real_Part *rp, Evas_Object *child_obj, const Evas_Object *ref)
Eina_Bool _edje_real_part_box_prepend (Edje_Real_Part *rp, Evas_Object *child_obj)
Evas_Object * _edje_real_part_box_remove (Edje_Real_Part *rp, Evas_Object *child_obj)
Eina_Bool _edje_real_part_box_remove_all (Edje_Real_Part *rp, Eina_Bool clear)
Evas_Object * _edje_real_part_box_remove_at (Edje_Real_Part *rp, unsigned int pos)
Edje_Real_Part * _edje_real_part_get (const Edje *ed, const char *part)
Edje_Real_Part * _edje_real_part_recursive_get (const Edje *ed, const char *part)
Edje_Real_Part * _edje_real_part_recursive_get_helper (const Edje *ed, char **path)
void _edje_real_part_swallow (Edje_Real_Part *rp, Evas_Object *obj_swallow, Eina_Bool hints_update)
void _edje_real_part_swallow_clear (Edje_Real_Part *rp)
void _edje_real_part_table_clear (Edje_Real_Part *rp, Eina_Bool clear)
Eina_Bool _edje_real_part_table_pack (Edje_Real_Part *rp, Evas_Object *child_obj, unsigned short col, unsigned short row, unsigned short colspan, unsigned short rowspan)
Eina_Bool _edje_real_part_table_unpack (Edje_Real_Part *rp, Evas_Object *child_obj)
void _edje_subobj_register (Edje *ed, Evas_Object *ob)
void _edje_subobj_unregister (Edje *ed, Evas_Object *obj)
Edje_Text_Class * _edje_text_class_find (Edje *ed, const char *text_class)
void _edje_text_class_hash_free (void)
void _edje_text_class_member_add (Edje *ed, const char *text_class)
void _edje_text_class_member_del (Edje *ed, const char *text_class)
void _edje_text_class_member_direct_del (const char *text_class, void *l)
void _edje_text_class_members_free (void)
char * _edje_text_escape (const char *text)
char * _edje_text_unescape (const char *text)
int _edje_thaw (Edje *ed)
int _edje_unblock (Edje *ed)
void _edje_user_definition_free (Edje_User_Defined *eud)
void _edje_user_definition_remove (Edje_User_Defined *eud, Evas_Object *child)
EAPI void edje_box_layout_register (const char *name, Evas_Object_Box_Layout func, void *(*layout_data_get)(void *), void(*layout_data_free)(void *), void(*free_data)(void *), void *data)
Registers a custom layout to be used in edje boxes.
void edje_color_class_del (const char *color_class)
Delete edje color class.
EAPI Eina_Bool edje_color_class_get (const char *color_class, int *r, int *g, int *b, int *a, int *r2, int *g2, int *b2, int *a2, int *r3, int *g3, int *b3, int *a3)
Get Edje color class.
Eina_List * edje_color_class_list (void)
Lists color classes.
EAPI Eina_Bool edje_color_class_set (const char *color_class, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Set Edje color class.
EAPI const Edje_Perspective * edje_evas_global_perspective_get (const Evas *e)
Get the global perspective object set for this canvas.
EAPI void edje_extern_object_aspect_set (Evas_Object *obj, Edje_Aspect_Control aspect, Evas_Coord aw, Evas_Coord ah)
Set the object aspect size.
EAPI void edje_extern_object_max_size_set (Evas_Object *obj, Evas_Coord maxw, Evas_Coord maxh)
Set the object maximum size.
EAPI void edje_extern_object_min_size_set (Evas_Object *obj, Evas_Coord minw, Evas_Coord minh)
Set the object minimum size.
EAPI const char * edje_fontset_append_get (void)
Get the edje append fontset.
EAPI void edje_fontset_append_set (const char *fonts)
Set the edje append fontset.
EAPI void edje_freeze (void)
Freeze Edje objects.
EAPI Eina_List * edje_object_access_part_list_get (const Evas_Object *obj)
Retrieve a list all accessibility part names.
EAPI void edje_object_calc_force (Evas_Object *obj)
Force a Size/Geometry calculation.
void edje_object_color_class_del (Evas_Object *obj, const char *color_class)
Delete the object color class.
EAPI Eina_Bool edje_object_color_class_get (const Evas_Object *obj, const char *color_class, int *r, int *g, int *b, int *a, int *r2, int *g2, int *b2, int *a2, int *r3, int *g3, int *b3, int *a3)
Gets the object color class.
EAPI Eina_Bool edje_object_color_class_set (Evas_Object *obj, const char *color_class, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Sets the object color class.
EAPI const char * edje_object_data_get (const Evas_Object *obj, const char *key)
Retrive an EDC data field's value from a given Edje object's group.
EAPI int edje_object_freeze (Evas_Object *obj)
Freezes the Edje object.
EAPI void edje_object_item_provider_set (Evas_Object *obj, Edje_Item_Provider_Cb func, void *data)
Set the function that provides item objects for named items in an edje entry text.
EAPI Eina_Bool edje_object_mirrored_get (const Evas_Object *obj)
Get the RTL orientation for this object.
EAPI void edje_object_mirrored_set (Evas_Object *obj, Eina_Bool rtl)
Set the RTL orientation for this object.
EAPI Eina_Bool edje_object_part_box_append (Evas_Object *obj, const char *part, Evas_Object *child)
Appends an object to the box.
EAPI Eina_Bool edje_object_part_box_insert_at (Evas_Object *obj, const char *part, Evas_Object *child, unsigned int pos)
Inserts an object to the box.
EAPI Eina_Bool edje_object_part_box_insert_before (Evas_Object *obj, const char *part, Evas_Object *child, const Evas_Object *reference)
Adds an object to the box.
EAPI Eina_Bool edje_object_part_box_prepend (Evas_Object *obj, const char *part, Evas_Object *child)
Prepends an object to the box.
EAPI Evas_Object * edje_object_part_box_remove (Evas_Object *obj, const char *part, Evas_Object *child)
Removes an object from the box.
EAPI Eina_Bool edje_object_part_box_remove_all (Evas_Object *obj, const char *part, Eina_Bool clear)
Removes all elements from the box.
EAPI Evas_Object * edje_object_part_box_remove_at (Evas_Object *obj, const char *part, unsigned int pos)
Removes an object from the box.
EAPI Edje_Drag_Dir edje_object_part_drag_dir_get (const Evas_Object *obj, const char *part)
Determine dragable directions.
EAPI Eina_Bool edje_object_part_drag_page (Evas_Object *obj, const char *part, double dx, double dy)
Pages x,y steps.
EAPI Eina_Bool edje_object_part_drag_page_get (const Evas_Object *obj, const char *part, double *dx, double *dy)
Gets the page step increments.
EAPI Eina_Bool edje_object_part_drag_page_set (Evas_Object *obj, const char *part, double dx, double dy)
Sets the page step increments.
EAPI Eina_Bool edje_object_part_drag_size_get (const Evas_Object *obj, const char *part, double *dw, double *dh)
Get the dragable object size.
EAPI Eina_Bool edje_object_part_drag_size_set (Evas_Object *obj, const char *part, double dw, double dh)
Set the dragable object size.
EAPI Eina_Bool edje_object_part_drag_step (Evas_Object *obj, const char *part, double dx, double dy)
Steps the dragable x,y steps.
EAPI Eina_Bool edje_object_part_drag_step_get (const Evas_Object *obj, const char *part, double *dx, double *dy)
Gets the drag step increment values.
EAPI Eina_Bool edje_object_part_drag_step_set (Evas_Object *obj, const char *part, double dx, double dy)
Sets the drag step increment.
EAPI Eina_Bool edje_object_part_drag_value_get (const Evas_Object *obj, const char *part, double *dx, double *dy)
Get the dragable object location.
EAPI Eina_Bool edje_object_part_drag_value_set (Evas_Object *obj, const char *part, double dx, double dy)
Set the dragable object location.
EAPI Eina_Bool edje_object_part_exists (const Evas_Object *obj, const char *part)
Check if an Edje part exists in a given Edje object's group definition.
EAPI Eina_Bool edje_object_part_geometry_get (const Evas_Object *obj, const char *part, Evas_Coord *x, Evas_Coord *y, Evas_Coord *w, Evas_Coord *h)
Retrieve the geometry of a given Edje part, in a given Edje object's group definition, relative to the object's area
EAPI const Evas_Object * edje_object_part_object_get (const Evas_Object *obj, const char *part)
Get a handle to the Evas object implementing a given Edje part, in an Edje object.
EAPI const char * edje_object_part_state_get (const Evas_Object *obj, const char *part, double *val_ret)
Returns the state of the Edje part.
EAPI Eina_Bool edje_object_part_swallow (Evas_Object *obj, const char *part, Evas_Object *obj_swallow)
"Swallows" an object into one of the Edje object SWALLOW parts.
EAPI Evas_Object * edje_object_part_swallow_get (const Evas_Object *obj, const char *part)
Get the object currently swallowed by a part.
EAPI Evas_Object * edje_object_part_table_child_get (const Evas_Object *obj, const char *part, unsigned int col, unsigned int row)
Retrieve a child from a table.
EAPI Eina_Bool edje_object_part_table_clear (Evas_Object *obj, const char *part, Eina_Bool clear)
Removes all object from the table.
EAPI Eina_Bool edje_object_part_table_col_row_size_get (const Evas_Object *obj, const char *part, int *cols, int *rows)
Gets the number of columns and rows the table has.
EAPI Eina_Bool edje_object_part_table_pack (Evas_Object *obj, const char *part, Evas_Object *child_obj, unsigned short col, unsigned short row, unsigned short colspan, unsigned short rowspan)
Packs an object into the table.
EAPI Eina_Bool edje_object_part_table_unpack (Evas_Object *obj, const char *part, Evas_Object *child_obj)
Removes an object from the table.
EAPI const Eina_List * edje_object_part_text_anchor_geometry_get (const Evas_Object *obj, const char *part, const char *anchor)
Return a list of Evas_Textblock_Rectangle anchor rectangles.
EAPI const Eina_List * edje_object_part_text_anchor_list_get (const Evas_Object *obj, const char *part)
Return a list of char anchor names.
EAPI void edje_object_part_text_append (Evas_Object *obj, const char *part, const char *text)
Insert text for an object part.
EAPI Edje_Text_Autocapital_Type edje_object_part_text_autocapital_type_get (const Evas_Object *obj, const char *part)
Retrieves the autocapitalization type.
EAPI void edje_object_part_text_autocapital_type_set (Evas_Object *obj, const char *part, Edje_Text_Autocapital_Type autocapital_type)
Set the autocapitalization type on the immodule.
EAPI void edje_object_part_text_cursor_begin_set (Evas_Object *obj, const char *part, Edje_Cursor cur)
Moves the cursor to the beginning of the text part.
EAPI char * edje_object_part_text_cursor_content_get (const Evas_Object *obj, const char *part, Edje_Cursor cur)
Returns the content (char) at the cursor position.
EAPI Eina_Bool edje_object_part_text_cursor_coord_set (Evas_Object *obj, const char *part, Edje_Cursor cur, Evas_Coord x, Evas_Coord y)
Position the given cursor to a X,Y position.
EAPI void edje_object_part_text_cursor_copy (Evas_Object *obj, const char *part, Edje_Cursor src, Edje_Cursor dst)
Copy the cursor to another cursor.
EAPI Eina_Bool edje_object_part_text_cursor_down (Evas_Object *obj, const char *part, Edje_Cursor cur)
Moves the cursor to the char below the current cursor position.
EAPI void edje_object_part_text_cursor_end_set (Evas_Object *obj, const char *part, Edje_Cursor cur)
Moves the cursor to the end of the text part.
EAPI void edje_object_part_text_cursor_geometry_get (const Evas_Object *obj, const char *part, Evas_Coord *x, Evas_Coord *y, Evas_Coord *w, Evas_Coord *h)
Returns the cursor geometry of the part relative to the edje object.
EAPI Eina_Bool edje_object_part_text_cursor_is_format_get (const Evas_Object *obj, const char *part, Edje_Cursor cur)
Returns whether the cursor points to a format.
EAPI Eina_Bool edje_object_part_text_cursor_is_visible_format_get (const Evas_Object *obj, const char *part, Edje_Cursor cur)
Return true if the cursor points to a visible format For example \t, \n, item and etc.
EAPI void edje_object_part_text_cursor_line_begin_set (Evas_Object *obj, const char *part, Edje_Cursor cur)
Move the cursor to the beginning of the line.
EAPI void edje_object_part_text_cursor_line_end_set (Evas_Object *obj, const char *part, Edje_Cursor cur)
Move the cursor to the end of the line.
EAPI Eina_Bool edje_object_part_text_cursor_next (Evas_Object *obj, const char *part, Edje_Cursor cur)
Advances the cursor to the next cursor position.
EAPI int edje_object_part_text_cursor_pos_get (const Evas_Object *obj, const char *part, Edje_Cursor cur)
Retrieves the current position of the cursor.
EAPI void edje_object_part_text_cursor_pos_set (Evas_Object *obj, const char *part, Edje_Cursor cur, int pos)
Sets the cursor position to the given value.
EAPI Eina_Bool edje_object_part_text_cursor_prev (Evas_Object *obj, const char *part, Edje_Cursor cur)
Moves the cursor to the previous char.
EAPI Eina_Bool edje_object_part_text_cursor_up (Evas_Object *obj, const char *part, Edje_Cursor cur)
Move the cursor to the char above the current cursor position.
EAPI Eina_Bool edje_object_part_text_escaped_set (Evas_Object *obj, const char *part, const char *text)
Sets the text for an object part, but converts HTML escapes to UTF8.
EAPI const char * edje_object_part_text_get (const Evas_Object *obj, const char *part)
Return the text of the object part.
EAPI void * edje_object_part_text_imf_context_get (const Evas_Object *obj, const char *part)
Get the input method context in entry.
EAPI void edje_object_part_text_imf_context_reset (const Evas_Object *obj, const char *part)
Reset the input method context if needed.
EAPI Eina_Bool edje_object_part_text_input_panel_enabled_get (const Evas_Object *obj, const char *part)
Retrieve the attribute to show the input panel automatically.
EAPI void edje_object_part_text_input_panel_enabled_set (Evas_Object *obj, const char *part, Eina_Bool enabled)
Sets the attribute to show the input panel automatically.
EAPI void edje_object_part_text_input_panel_hide (const Evas_Object *obj, const char *part)
Hide the input panel (virtual keyboard).
EAPI void edje_object_part_text_input_panel_imdata_get (const Evas_Object *obj, const char *part, void *data, int *len)
Get the specific data of the current active input panel.
EAPI void edje_object_part_text_input_panel_imdata_set (Evas_Object *obj, const char *part, const void *data, int len)
Set the input panel-specific data to deliver to the input panel.
EAPI Edje_Input_Panel_Lang edje_object_part_text_input_panel_language_get (const Evas_Object *obj, const char *part)
Get the language mode of the input panel.
EAPI void edje_object_part_text_input_panel_language_set (Evas_Object *obj, const char *part, Edje_Input_Panel_Lang lang)
Set the language mode of the input panel.
EAPI Edje_Input_Panel_Layout edje_object_part_text_input_panel_layout_get (const Evas_Object *obj, const char *part)
Get the layout of the input panel.
EAPI void edje_object_part_text_input_panel_layout_set (Evas_Object *obj, const char *part, Edje_Input_Panel_Layout layout)
Set the layout of the input panel.
EAPI Eina_Bool edje_object_part_text_input_panel_return_key_disabled_get (const Evas_Object *obj, const char *part)
Get whether the return key on the input panel should be disabled or not.
EAPI void edje_object_part_text_input_panel_return_key_disabled_set (Evas_Object *obj, const char *part, Eina_Bool disabled)
Set the return key on the input panel to be disabled.
EAPI Edje_Input_Panel_Return_Key_Type edje_object_part_text_input_panel_return_key_type_get (const Evas_Object *obj, const char *part)
Get the "return" key type.
EAPI void edje_object_part_text_input_panel_return_key_type_set (Evas_Object *obj, const char *part, Edje_Input_Panel_Return_Key_Type return_key_type)
Set the "return" key type.
EAPI void edje_object_part_text_input_panel_show (const Evas_Object *obj, const char *part)
Show the input panel (virtual keyboard) based on the input panel property such as layout, autocapital types, and so on.
EAPI void edje_object_part_text_insert (Evas_Object *obj, const char *part, const char *text)
Insert text for an object part.
EAPI Eina_Bool edje_object_part_text_item_geometry_get (const Evas_Object *obj, const char *part, const char *item, Evas_Coord *cx, Evas_Coord *cy, Evas_Coord *cw, Evas_Coord *ch)
Return item geometry.
EAPI const Eina_List * edje_object_part_text_item_list_get (const Evas_Object *obj, const char *part)
Return a list of char item names.
EAPI Eina_Bool edje_object_part_text_prediction_allow_get (const Evas_Object *obj, const char *part)
Get whether the prediction is allowed or not.
EAPI void edje_object_part_text_prediction_allow_set (Evas_Object *obj, const char *part, Eina_Bool prediction)
Set whether the prediction is allowed or not.
EAPI void edje_object_part_text_select_abort (const Evas_Object *obj, const char *part)
Aborts any selection action on a part.
EAPI void edje_object_part_text_select_all (const Evas_Object *obj, const char *part)
Set the selection to be everything.
EAPI void edje_object_part_text_select_allow_set (const Evas_Object *obj, const char *part, Eina_Bool allow)
Enables selection if the entry is an EXPLICIT selection mode type.
EAPI void edje_object_part_text_select_begin (const Evas_Object *obj, const char *part)
Starts selecting at current cursor position.
EAPI void edje_object_part_text_select_extend (const Evas_Object *obj, const char *part)
Extends the current selection to the current cursor position.
EAPI void edje_object_part_text_select_none (const Evas_Object *obj, const char *part)
Set the selection to be none.
EAPI const char * edje_object_part_text_selection_get (const Evas_Object *obj, const char *part)
Return the selection text of the object part.
EAPI Eina_Bool edje_object_part_text_set (Evas_Object *obj, const char *part, const char *text)
Sets the text for an object part.
EAPI const char * edje_object_part_text_style_user_peek (const Evas_Object *obj, const char *part)
Return the text of the object part.
EAPI void edje_object_part_text_style_user_pop (Evas_Object *obj, const char *part)
Delete the top style form the user style stack.
EAPI void edje_object_part_text_style_user_push (Evas_Object *obj, const char *part, const char *style)
Set the style of the.
EAPI char * edje_object_part_text_unescaped_get (const Evas_Object *obj, const char *part)
Returns the text of the object part, without escaping.
EAPI Eina_Bool edje_object_part_text_unescaped_set (Evas_Object *obj, const char *part, const char *text_to_escape)
Sets the raw (non escaped) text for an object part.
EAPI void edje_object_part_text_user_insert (const Evas_Object *obj, const char *part, const char *text)
Deletes the selection and emits a change event.
EAPI void edje_object_part_unswallow (Evas_Object *obj, Evas_Object *obj_swallow)
Unswallow an object.
EAPI Eina_Bool edje_object_parts_extends_calc (Evas_Object *obj, Evas_Coord *x, Evas_Coord *y, Evas_Coord *w, Evas_Coord *h)
Calculate the geometry of the region, relative to a given Edje object's area, occupied by all parts in the object
EAPI const Edje_Perspective * edje_object_perspective_get (const Evas_Object *obj)
Get the current perspective used on this Edje object.
EAPI void edje_object_perspective_set (Evas_Object *obj, Edje_Perspective *ps)
Set the given perspective object on this Edje object.
EAPI Eina_Bool edje_object_preload (Evas_Object *obj, Eina_Bool cancel)
Preload the images on the Edje Object in the background.
EAPI double edje_object_scale_get (const Evas_Object *obj)
Get a given Edje object's scaling factor.
EAPI Eina_Bool edje_object_scale_set (Evas_Object *obj, double scale)
Set the scaling factor for a given Edje object.
EAPI void edje_object_size_max_get (const Evas_Object *obj, Evas_Coord *maxw, Evas_Coord *maxh)
Get the maximum size specified – as an EDC property – for a given Edje object.
EAPI void edje_object_size_min_calc (Evas_Object *obj, Evas_Coord *minw, Evas_Coord *minh)
Calculate the minimum required size for a given Edje object.
EAPI void edje_object_size_min_get (const Evas_Object *obj, Evas_Coord *minw, Evas_Coord *minh)
Get the minimum size specified – as an EDC property – for a given Edje object.
EAPI void edje_object_size_min_restricted_calc (Evas_Object *obj, Evas_Coord *minw, Evas_Coord *minh, Evas_Coord restrictedw, Evas_Coord restrictedh)
Calculate the minimum required size for a given Edje object.
EAPI void edje_object_text_change_cb_set (Evas_Object *obj, Edje_Text_Change_Cb func, void *data)
Set the object text callback.
EAPI Eina_Bool edje_object_text_class_set (Evas_Object *obj, const char *text_class, const char *font, Evas_Font_Size size)
Sets Edje text class.
EAPI void edje_object_text_insert_filter_callback_add (Evas_Object *obj, const char *part, Edje_Text_Filter_Cb func, void *data)
Add a filter function for newly inserted text.
EAPI void * edje_object_text_insert_filter_callback_del (Evas_Object *obj, const char *part, Edje_Text_Filter_Cb func)
Delete a function from the filter list.
EAPI void * edje_object_text_insert_filter_callback_del_full (Evas_Object *obj, const char *part, Edje_Text_Filter_Cb func, void *data)
Delete a function and matching user data from the filter list.
EAPI void edje_object_text_markup_filter_callback_add (Evas_Object *obj, const char *part, Edje_Markup_Filter_Cb func, void *data)
Add a markup filter function for newly inserted text.
EAPI void * edje_object_text_markup_filter_callback_del (Evas_Object *obj, const char *part, Edje_Markup_Filter_Cb func)
Delete a function from the markup filter list.
EAPI void * edje_object_text_markup_filter_callback_del_full (Evas_Object *obj, const char *part, Edje_Markup_Filter_Cb func, void *data)
Delete a function and matching user data from the markup filter list.
EAPI int edje_object_thaw (Evas_Object *obj)
Thaws the Edje object.
EAPI Eina_Bool edje_object_update_hints_get (Evas_Object *obj)
Wether or not Edje will update size hints on itself.
EAPI void edje_object_update_hints_set (Evas_Object *obj, Eina_Bool update)
Edje will automatically update the size hints on itself.
EAPI void edje_password_show_last_set (Eina_Bool password_show_last)
Show last character in password mode.
EAPI void edje_password_show_last_timeout_set (double password_show_last_timeout)
Set's the timeout value in last show password mode.
EAPI void edje_perspective_free (Edje_Perspective *ps)
Delete the given perspective object.
EAPI Eina_Bool edje_perspective_global_get (const Edje_Perspective *ps)
Get whether the given perspective object is global or not.
EAPI void edje_perspective_global_set (Edje_Perspective *ps, Eina_Bool global)
Make this perspective object be global for its canvas.
EAPI Edje_Perspective * edje_perspective_new (Evas *e)
Creates a new perspective in the given canvas.
EAPI void edje_perspective_set (Edje_Perspective *ps, Evas_Coord px, Evas_Coord py, Evas_Coord z0, Evas_Coord foc)
Setup the transform for this perspective object.
EAPI double edje_scale_get (void)
Retrieve Edje's global scaling factor.
EAPI void edje_scale_set (double scale)
Set Edje's global scaling factor.
const char * edje_string_get (const Edje_String *es)
const char * edje_string_id_get (const Edje_String *es)
void edje_text_class_del (const char *text_class)
Delete the text class.
Eina_List * edje_text_class_list (void)
List text classes.
EAPI Eina_Bool edje_text_class_set (const char *text_class, const char *font, Evas_Font_Size size)
Set the Edje text class.
EAPI void edje_thaw (void)
Thaw Edje objects.
Variables
char * _edje_fontset_append = NULL
int _edje_freeze_calc_count = 0
Eina_List * _edje_freeze_calc_list = NULL
int _edje_freeze_val = 0
Eina_Bool _edje_password_show_last = EINA_FALSE
FLOAT_T _edje_password_show_last_timeout = ZERO
FLOAT_T _edje_scale = ZERO
Macro Definition Documentation
EDJE_PRELOAD_EMISSION
#define EDJE_PRELOAD_EMISSION "preload,done"
EDJE_PRELOAD_SOURCE
#define EDJE_PRELOAD_SOURCE NULL
FASTFREEZE
#define FASTFREEZE 1
S [1/4]
#define S (_r, _g, _b, _a) X(_r); X(_g); X(_b); X(_a)
S [2/4]
#define S (_r, _g, _b, _a) X(_r); X(_g); X(_b); X(_a)
S [3/4]
#define S (_r, _g, _b, _a) X(_r); X(_g); X(_b); X(_a)
S [4/4]
#define S (_r, _g, _b, _a) X(_r); X(_g); X(_b); X(_a)
X [1/4]
#define X (C)
Value:
    if (C) \
    *C = cc->C
X [2/4]
#define X (C)
Value:
    if (C) \
    *C = 0
X [3/4]
#define X (C)
Value:
    if (C) \
    *C = cc->C
X [4/4]
#define X (C)
Value:
    if (C) \
    *C = 0
Typedef Documentation
Edje_Box_Layout
typedef struct _Edje_Box_Layout Edje_Box_Layout
Edje_List_Foreach_Data
typedef struct _Edje_List_Foreach_Data Edje_List_Foreach_Data
Edje_List_Refcount
typedef struct _Edje_List_Refcount Edje_List_Refcount
Function Documentation
_edje_block()
int _edje_block (Edje * ed)
References _edje_ref(), and _Edje::block.
Referenced by _edje_emit_handle(), _edje_program_run(), _edje_program_run_iterate(), _edje_timer_cb(), and edje_object_animation_set().
_edje_block_break()
int _edje_block_break (Edje * ed)
References _Edje::block_break.
Referenced by _edje_emit_handle(), _edje_program_run(), _edje_program_run_iterate(), _edje_timer_cb(), and edje_object_animation_set().
_edje_block_violate()
void _edje_block_violate (Edje * ed)
References _Edje::block, and _Edje::block_break.
Referenced by _edje_file_del().
_edje_box_init()
void _edje_box_init (void)
_edje_box_layout_find()
Eina_Bool _edje_box_layout_find (const char * name, Evas_Object_Box_Layout * cb, void ** data, void(**)(void *data) free_data)
References edje_box_layout_builtin::cb, and name.
_edje_box_shutdown()
void _edje_box_shutdown (void)
_edje_children_get()
Evas_Object* _edje_children_get (Edje_Real_Part * rp, const char * partid)
References _edje_external_content_get(), EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_TABLE, name, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, and _Edje_Part::type.
Referenced by _edje_emit_full(), and _edje_real_part_recursive_get_helper().
_edje_color_class_find()
Edje_Color_Class* _edje_color_class_find (Edje * ed, const char * color_class)
References _Edje::color_classes.
Referenced by edje_object_color_class_get().
_edje_color_class_hash_free()
void _edje_color_class_hash_free (void)
_edje_color_class_member_add()
void _edje_color_class_member_add (Edje * ed, const char * color_class)
_edje_color_class_member_del()
void _edje_color_class_member_del (Edje * ed, const char * color_class)
Referenced by _edje_color_class_on_del().
_edje_color_class_member_direct_del()
void _edje_color_class_member_direct_del (const char * color_class, void * l)
_edje_color_class_members_free()
void _edje_color_class_members_free (void)
_edje_color_class_on_del()
void _edje_color_class_on_del (Edje * ed, Edje_Part * ep)
References _edje_color_class_member_del(), _Edje_Part_Description_Common::color_class, _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, and _Edje_Part::other.
Referenced by _edje_file_del().
_edje_fetch()
Edje* _edje_fetch (const Evas_Object * obj)
References _Edje::delete_me.
Referenced by _edje_emit_full(), _edje_message_cb_set(), _edje_object_file_set_internal(), _edje_part_recalc(), _edje_real_part_recursive_get_helper(), edje_object_access_part_list_get(), edje_object_animation_get(), edje_object_animation_set(), edje_object_calc_force(), edje_object_color_class_del(), edje_object_color_class_get(), edje_object_color_class_set(), edje_object_data_get(), edje_object_file_get(), edje_object_file_set(), edje_object_freeze(), edje_object_item_provider_set(), edje_object_load_error_get(), edje_object_message_handler_set(), edje_object_message_signal_process(), edje_object_mirrored_get(), edje_object_mirrored_set(), edje_object_part_box_append(), edje_object_part_box_insert_at(), edje_object_part_box_insert_before(), edje_object_part_box_prepend(), edje_object_part_box_remove(), edje_object_part_box_remove_all(), edje_object_part_box_remove_at(), edje_object_part_drag_dir_get(), edje_object_part_drag_page(), edje_object_part_drag_page_get(), edje_object_part_drag_page_set(), edje_object_part_drag_size_get(), edje_object_part_drag_size_set(), edje_object_part_drag_step(), edje_object_part_drag_step_get(), edje_object_part_drag_step_set(), edje_object_part_drag_value_get(), edje_object_part_drag_value_set(), edje_object_part_exists(), edje_object_part_external_content_get(), edje_object_part_external_object_get(), edje_object_part_external_param_get(), edje_object_part_external_param_set(), edje_object_part_external_param_type_get(), edje_object_part_geometry_get(), edje_object_part_object_get(), edje_object_part_state_get(), edje_object_part_swallow(), edje_object_part_swallow_get(), edje_object_part_table_child_get(), edje_object_part_table_clear(), edje_object_part_table_col_row_size_get(), edje_object_part_table_pack(), edje_object_part_table_unpack(), edje_object_part_text_anchor_geometry_get(), edje_object_part_text_anchor_list_get(), edje_object_part_text_append(), edje_object_part_text_autocapital_type_get(), edje_object_part_text_autocapital_type_set(), edje_object_part_text_cursor_begin_set(), edje_object_part_text_cursor_content_get(), edje_object_part_text_cursor_coord_set(), edje_object_part_text_cursor_copy(), edje_object_part_text_cursor_down(), edje_object_part_text_cursor_end_set(), edje_object_part_text_cursor_geometry_get(), edje_object_part_text_cursor_is_format_get(), edje_object_part_text_cursor_is_visible_format_get(), edje_object_part_text_cursor_line_begin_set(), edje_object_part_text_cursor_line_end_set(), edje_object_part_text_cursor_next(), edje_object_part_text_cursor_pos_get(), edje_object_part_text_cursor_pos_set(), edje_object_part_text_cursor_prev(), edje_object_part_text_cursor_up(), edje_object_part_text_escaped_set(), edje_object_part_text_get(), edje_object_part_text_imf_context_get(), edje_object_part_text_imf_context_reset(), edje_object_part_text_input_panel_enabled_get(), edje_object_part_text_input_panel_enabled_set(), edje_object_part_text_input_panel_hide(), edje_object_part_text_input_panel_imdata_get(), edje_object_part_text_input_panel_imdata_set(), edje_object_part_text_input_panel_language_get(), edje_object_part_text_input_panel_language_set(), edje_object_part_text_input_panel_layout_get(), edje_object_part_text_input_panel_layout_set(), edje_object_part_text_input_panel_return_key_disabled_get(), edje_object_part_text_input_panel_return_key_disabled_set(), edje_object_part_text_input_panel_return_key_type_get(), edje_object_part_text_input_panel_return_key_type_set(), edje_object_part_text_input_panel_show(), edje_object_part_text_insert(), edje_object_part_text_item_geometry_get(), edje_object_part_text_item_list_get(), edje_object_part_text_prediction_allow_get(), edje_object_part_text_prediction_allow_set(), edje_object_part_text_select_abort(), edje_object_part_text_select_all(), edje_object_part_text_select_allow_set(), edje_object_part_text_select_begin(), edje_object_part_text_select_extend(), edje_object_part_text_select_none(), edje_object_part_text_selection_get(), edje_object_part_text_set(), edje_object_part_text_style_user_peek(), edje_object_part_text_style_user_pop(), edje_object_part_text_style_user_push(), edje_object_part_text_unescaped_get(), edje_object_part_text_unescaped_set(), edje_object_part_text_user_insert(), edje_object_part_unswallow(), edje_object_parts_extends_calc(), edje_object_play_get(), edje_object_play_set(), edje_object_preload(), edje_object_propagate_callback_add(), edje_object_scale_get(), edje_object_scale_set(), edje_object_signal_callback_add(), edje_object_signal_callback_del(), edje_object_signal_callback_del_full(), edje_object_signal_emit(), edje_object_size_max_get(), edje_object_size_min_get(), edje_object_size_min_restricted_calc(), edje_object_text_change_cb_set(), edje_object_text_class_set(), edje_object_text_insert_filter_callback_add(), edje_object_text_insert_filter_callback_del(), edje_object_text_insert_filter_callback_del_full(), edje_object_text_markup_filter_callback_add(), edje_object_text_markup_filter_callback_del(), edje_object_text_markup_filter_callback_del_full(), edje_object_thaw(), edje_object_update_hints_get(), and edje_object_update_hints_set().
_edje_freeze()
int _edje_freeze (Edje * ed)
References _Edje::freeze.
Referenced by _edje_emit_handle(), _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), _edje_timer_cb(), edje_object_animation_set(), and edje_object_freeze().
_edje_merge_path()
char* _edje_merge_path (const char * alias, char *const * path)
References EDJE_PART_PATH_SEPARATOR_STRING.
Referenced by _edje_real_part_recursive_get_helper().
_edje_object_orientation_inform()
void _edje_object_orientation_inform (Evas_Object * obj)
References edje_object_mirrored_get(), and edje_object_signal_emit().
Referenced by edje_object_file_set(), and edje_object_mirrored_set().
_edje_object_part_swallow_changed_hints_cb()
void _edje_object_part_swallow_changed_hints_cb (void * data, __UNUSED__ Evas * e, __UNUSED__ Evas_Object * obj, __UNUSED__ void * event_info)
Referenced by _edje_real_part_swallow_clear().
_edje_object_part_swallow_free_cb()
void _edje_object_part_swallow_free_cb (void * data, Evas *e __UNUSED__, Evas_Object *obj __UNUSED__, void *event_info __UNUSED__)
References _edje_user_definition_free(), _Edje_Real_Part::edje, EDJE_USER_SWALLOW, _Edje_User_Defined::swallow, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
Referenced by _edje_real_part_swallow_clear().
_edje_object_part_text_raw_append()
Eina_Bool _edje_object_part_text_raw_append (Evas_Object * obj, Edje_Real_Part * rp, const char * part, const char * text)
References _edje_entry_text_markup_append(), _edje_recalc(), _Edje::data, _Edje::dirty, _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, _Edje::func, _Edje_Real_Part::part, _Edje::recalc_call, _Edje_Real_Part::text, and _Edje::text_change.
Referenced by edje_object_part_text_append().
_edje_object_part_text_raw_set()
Eina_Bool _edje_object_part_text_raw_set (Evas_Object * obj, Edje_Real_Part * rp, const char * part, const char * text)
References _edje_entry_text_markup_set(), _edje_recalc(), _Edje::data, _Edje::dirty, _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, _Edje::func, _Edje_Real_Part::part, _Edje::recalc_call, _Edje::recalc_hints, _Edje_Real_Part::text, and _Edje::text_change.
Referenced by edje_object_part_text_escaped_set(), edje_object_part_text_set(), and edje_object_part_text_unescaped_set().
_edje_program_insert()
EAPI void _edje_program_insert (Edje_Part_Collection * edc, Edje_Program * p)
References _Edje_Part_Collection::nocmp, _Edje_Part_Collection::nocmp_count, _Edje_Part_Collection::programs, _Edje_Program::signal, _Edje_Program::source, _Edje_Part_Collection::strcmp, and _Edje_Part_Collection::strcmp_count.
_edje_program_remove()
EAPI void _edje_program_remove (Edje_Part_Collection * edc, Edje_Program * p)
References _Edje_Part_Collection::nocmp, _Edje_Part_Collection::nocmp_count, _Edje_Part_Collection::programs, _Edje_Program::signal, _Edje_Program::source, _Edje_Part_Collection::strcmp, and _Edje_Part_Collection::strcmp_count.
Referenced by edje_edit_program_del(), edje_edit_program_signal_set(), and edje_edit_program_source_set().
_edje_real_part_box_append()
Eina_Bool _edje_real_part_box_append (Edje_Real_Part * rp, Evas_Object * child_obj)
References _edje_box_layout_add_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_append().
_edje_real_part_box_insert_at()
Eina_Bool _edje_real_part_box_insert_at (Edje_Real_Part * rp, Evas_Object * child_obj, unsigned int pos)
References _edje_box_layout_add_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_insert_at().
_edje_real_part_box_insert_before()
Eina_Bool _edje_real_part_box_insert_before (Edje_Real_Part * rp, Evas_Object * child_obj, const Evas_Object * ref)
References _edje_box_layout_add_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_insert_before().
_edje_real_part_box_prepend()
Eina_Bool _edje_real_part_box_prepend (Edje_Real_Part * rp, Evas_Object * child_obj)
References _edje_box_layout_add_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_prepend().
_edje_real_part_box_remove()
Evas_Object* _edje_real_part_box_remove (Edje_Real_Part * rp, Evas_Object * child_obj)
References _edje_box_layout_remove_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_remove().
_edje_real_part_box_remove_all()
Eina_Bool _edje_real_part_box_remove_all (Edje_Real_Part * rp, Eina_Bool clear)
References _edje_box_layout_remove_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_remove_all().
_edje_real_part_box_remove_at()
Evas_Object* _edje_real_part_box_remove_at (Edje_Real_Part * rp, unsigned int pos)
References _edje_box_layout_remove_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_remove_at().
_edje_real_part_get()
Edje_Real_Part* _edje_real_part_get (const Edje * ed, const char * part)
References _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
Referenced by _edje_emit_full(), _edje_emit_handle(), _edje_real_part_recursive_get_helper(), edje_edit_part_clip_to_set(), edje_edit_part_name_set(), edje_edit_program_target_add(), and edje_edit_program_target_del().
_edje_real_part_recursive_get()
Edje_Real_Part* _edje_real_part_recursive_get (const Edje * ed, const char * part)
References _edje_real_part_recursive_get_helper(), and EDJE_PART_PATH_SEPARATOR_STRING.
Referenced by _edje_real_part_recursive_get_helper(), _edje_user_definition_free(), edje_object_part_box_append(), edje_object_part_box_insert_at(), edje_object_part_box_insert_before(), edje_object_part_box_prepend(), edje_object_part_box_remove(), edje_object_part_box_remove_all(), edje_object_part_box_remove_at(), edje_object_part_drag_dir_get(), edje_object_part_drag_page(), edje_object_part_drag_page_get(), edje_object_part_drag_page_set(), edje_object_part_drag_size_get(), edje_object_part_drag_size_set(), edje_object_part_drag_step(), edje_object_part_drag_step_get(), edje_object_part_drag_step_set(), edje_object_part_drag_value_get(), edje_object_part_drag_value_set(), edje_object_part_exists(), edje_object_part_external_content_get(), edje_object_part_external_object_get(), edje_object_part_external_param_get(), edje_object_part_external_param_set(), edje_object_part_external_param_type_get(), edje_object_part_geometry_get(), edje_object_part_object_get(), edje_object_part_state_get(), edje_object_part_swallow(), edje_object_part_swallow_get(), edje_object_part_table_child_get(), edje_object_part_table_clear(), edje_object_part_table_col_row_size_get(), edje_object_part_table_pack(), edje_object_part_table_unpack(), edje_object_part_text_anchor_geometry_get(), edje_object_part_text_anchor_list_get(), edje_object_part_text_append(), edje_object_part_text_autocapital_type_get(), edje_object_part_text_autocapital_type_set(), edje_object_part_text_cursor_begin_set(), edje_object_part_text_cursor_content_get(), edje_object_part_text_cursor_coord_set(), edje_object_part_text_cursor_copy(), edje_object_part_text_cursor_down(), edje_object_part_text_cursor_end_set(), edje_object_part_text_cursor_geometry_get(), edje_object_part_text_cursor_is_format_get(), edje_object_part_text_cursor_is_visible_format_get(), edje_object_part_text_cursor_line_begin_set(), edje_object_part_text_cursor_line_end_set(), edje_object_part_text_cursor_next(), edje_object_part_text_cursor_pos_get(), edje_object_part_text_cursor_pos_set(), edje_object_part_text_cursor_prev(), edje_object_part_text_cursor_up(), edje_object_part_text_escaped_set(), edje_object_part_text_get(), edje_object_part_text_imf_context_get(), edje_object_part_text_imf_context_reset(), edje_object_part_text_input_panel_enabled_get(), edje_object_part_text_input_panel_enabled_set(), edje_object_part_text_input_panel_hide(), edje_object_part_text_input_panel_imdata_get(), edje_object_part_text_input_panel_imdata_set(), edje_object_part_text_input_panel_language_get(), edje_object_part_text_input_panel_language_set(), edje_object_part_text_input_panel_layout_get(), edje_object_part_text_input_panel_layout_set(), edje_object_part_text_input_panel_return_key_disabled_get(), edje_object_part_text_input_panel_return_key_disabled_set(), edje_object_part_text_input_panel_return_key_type_get(), edje_object_part_text_input_panel_return_key_type_set(), edje_object_part_text_input_panel_show(), edje_object_part_text_insert(), edje_object_part_text_item_geometry_get(), edje_object_part_text_item_list_get(), edje_object_part_text_prediction_allow_get(), edje_object_part_text_prediction_allow_set(), edje_object_part_text_select_abort(), edje_object_part_text_select_all(), edje_object_part_text_select_allow_set(), edje_object_part_text_select_begin(), edje_object_part_text_select_extend(), edje_object_part_text_select_none(), edje_object_part_text_selection_get(), edje_object_part_text_set(), edje_object_part_text_style_user_peek(), edje_object_part_text_style_user_pop(), edje_object_part_text_style_user_push(), edje_object_part_text_unescaped_get(), edje_object_part_text_unescaped_set(), and edje_object_part_text_user_insert().
_edje_real_part_recursive_get_helper()
Edje_Real_Part * _edje_real_part_recursive_get_helper (const Edje * ed, char ** path)
References _edje_children_get(), _edje_fetch(), _edje_merge_path(), _edje_real_part_get(), _edje_real_part_recursive_get(), _Edje_Part_Collection::alias, _Edje::collection, EDJE_PART_PATH_SEPARATOR_INDEXL, EDJE_PART_PATH_SEPARATOR_INDEXR, EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_GROUP, EDJE_PART_TYPE_TABLE, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, and _Edje_Part::type.
Referenced by _edje_real_part_recursive_get().
_edje_real_part_swallow()
void _edje_real_part_swallow (Edje_Real_Part * rp, Evas_Object * obj_swallow, Eina_Bool hints_update)
References _Edje_Real_Part::edje, edje_object_part_unswallow(), _Edje::obj, and _Edje_Real_Part::swallowed_object.
Referenced by edje_object_part_swallow().
_edje_real_part_swallow_clear()
void _edje_real_part_swallow_clear (Edje_Real_Part * rp)
References _edje_callbacks_del(), _edje_callbacks_focus_del(), _edje_object_part_swallow_changed_hints_cb(), _edje_object_part_swallow_free_cb(), _Edje_Real_Part::edje, _Edje_Part::mouse_events, _Edje_Real_Part::part, and _Edje_Real_Part::swallowed_object.
Referenced by _edje_file_del(), _edje_user_definition_free(), and edje_object_part_unswallow().
_edje_real_part_table_clear()
void _edje_real_part_table_clear (Edje_Real_Part * rp, Eina_Bool clear)
References _Edje_Real_Part::object.
Referenced by edje_object_part_table_clear().
_edje_real_part_table_pack()
Eina_Bool _edje_real_part_table_pack (Edje_Real_Part * rp, Evas_Object * child_obj, unsigned short col, unsigned short row, unsigned short colspan, unsigned short rowspan)
References _Edje_Real_Part::object.
Referenced by edje_object_part_table_pack().
_edje_real_part_table_unpack()
Eina_Bool _edje_real_part_table_unpack (Edje_Real_Part * rp, Evas_Object * child_obj)
References _Edje_Real_Part::object.
Referenced by edje_object_part_table_unpack().
_edje_subobj_register()
void _edje_subobj_register (Edje * ed, Evas_Object * ob)
References _Edje::subobjs.
_edje_subobj_unregister()
void _edje_subobj_unregister (Edje * ed, Evas_Object * obj)
References _Edje::subobjs.
Referenced by _edje_file_del().
_edje_text_class_find()
Edje_Text_Class* _edje_text_class_find (Edje * ed, const char * text_class)
References _Edje_Text_Class::name, and _Edje::text_classes.
Referenced by _edje_text_class_font_get(), and _edje_textblock_style_all_update().
_edje_text_class_hash_free()
void _edje_text_class_hash_free (void)
_edje_text_class_member_add()
void _edje_text_class_member_add (Edje * ed, const char * text_class)
Referenced by _edje_text_part_on_add(), and _edje_textblock_styles_add().
_edje_text_class_member_del()
void _edje_text_class_member_del (Edje * ed, const char * text_class)
Referenced by _edje_text_part_on_del(), and _edje_textblock_styles_del().
_edje_text_class_member_direct_del()
void _edje_text_class_member_direct_del (const char * text_class, void * l)
_edje_text_class_members_free()
void _edje_text_class_members_free (void)
_edje_text_escape()
char* _edje_text_escape (const char * text)
Referenced by edje_object_part_text_unescaped_set().
_edje_text_unescape()
char* _edje_text_unescape (const char * text)
Referenced by edje_object_part_text_unescaped_get().
_edje_thaw()
int _edje_thaw (Edje * ed)
References _edje_recalc(), _Edje::freeze, and _Edje::recalc.
Referenced by _edje_program_end(), _edje_program_run_iterate(), _edje_timer_cb(), edje_object_animation_set(), and edje_object_thaw().
_edje_unblock()
int _edje_unblock (Edje * ed)
References _edje_unref(), _Edje::block, and _Edje::block_break.
Referenced by _edje_program_run_iterate(), _edje_timer_cb(), and edje_object_animation_set().
_edje_user_definition_free()
void _edje_user_definition_free (Edje_User_Defined * eud)
References _edje_real_part_recursive_get(), _edje_real_part_swallow_clear(), _edje_recalc_do(), _Edje_User_Defined::box, _Edje::dirty, _Edje_User_Defined::ed, _Edje_Real_Part::edje, EDJE_USER_BOX_PACK, EDJE_USER_SWALLOW, _Edje_Size::h, _Edje_Real_Part::max, _Edje_Real_Part::min, _Edje_User_Defined::part, _Edje::recalc_call, _Edje_User_Defined::swallow, _Edje_Real_Part::swallow_params, _Edje_Real_Part::swallowed_object, _Edje_User_Defined::type, _Edje_User_Defined::u, _Edje::user_defined, and _Edje_Size::w.
Referenced by _edje_file_del(), _edje_object_part_swallow_free_cb(), edje_object_part_box_remove(), edje_object_part_box_remove_all(), edje_object_part_box_remove_at(), edje_object_part_table_unpack(), and edje_object_part_unswallow().
_edje_user_definition_remove()
void _edje_user_definition_remove (Edje_User_Defined * eud, Evas_Object * child)
References _Edje_User_Defined::ed, and _Edje::user_defined.
edje_box_layout_register()
EAPI void edje_box_layout_register (const char * name, Evas_Object_Box_Layout func, void *(*)(void *) layout_data_get, void(*)(void *) layout_data_free, void(*)(void *) free_data, void * data)
Registers a custom layout to be used in edje boxes.
Parameters
name The name of the layout
func The function defining the layout
layout_data_get This function gets the custom data pointer for func
layout_data_free Passed to func to free its private data when needed
free_data Frees data
data Private pointer passed to layout_data_get
This function registers custom layouts that can be referred from themes by the registered name. The Evas_Object_Box_Layout functions receive two pointers for internal use, one being private data, and the other the function to free that data when it's not longer needed. From Edje, this private data will be retrieved by calling layout_data_get, and layout_data_free will be the free function passed to func. layout_data_get will be called with data as its parameter, and this one will be freed by free_data whenever the layout is unregistered from Edje.
References name.
edje_color_class_del()
void edje_color_class_del (const char * color_class)
Delete edje color class.
Parameters
color_class This function deletes any values at the process level for the specified color class.
Note
Deleting the color class will revert it to the values defined in the theme file.
Deleting the color class will emit the signal "color_class,del" to all the Edje objects in the running program.
edje_color_class_get()
EAPI Eina_Bool edje_color_class_get (const char * color_class, int * r, int * g, int * b, int * a, int * r2, int * g2, int * b2, int * a2, int * r3, int * g3, int * b3, int * a3)
Get Edje color class.
Parameters
color_class
r Object Red value
g Object Green value
b Object Blue value
a Object Alpha value
r2 Outline Red value
g2 Outline Green value
b2 Outline Blue value
a2 Outline Alpha value
r3 Shadow Red value
g3 Shadow Green value
b3 Shadow Blue value
a3 Shadow Alpha value
Returns
EINA_TRUE if found or EINA_FALSE if not found and all values are zeroed.
This function gets the color values for a process level color class. This value is the globally set and not per-object, that is, the value that would be used by objects if they did not override with edje_object_color_class_set().
The first color is the object, the second is the text outline, and the third is the text shadow. (Note that the second two only apply to text parts).
See also
edje_color_class_set().
Note
unlike Evas, Edje colors are not pre-multiplied. That is, half-transparent white is 255 255 255 128.
edje_color_class_list()
Eina_List* edje_color_class_list (void)
Lists color classes.
Returns
A list of color class names (strings). These strings and the list must be free()'d by the caller.
This function lists all color classes known about by the current process.
edje_color_class_set()
EAPI Eina_Bool edje_color_class_set (const char * color_class, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Set Edje color class.
Parameters
color_class
r Object Red value
g Object Green value
b Object Blue value
a Object Alpha value
r2 Outline Red value
g2 Outline Green value
b2 Outline Blue value
a2 Outline Alpha value
r3 Shadow Red value
g3 Shadow Green value
b3 Shadow Blue value
a3 Shadow Alpha value
This function sets the color values for a process level color class. This will cause all edje parts in the current process that have the specified color class to have their colors multiplied by these values. (Object level color classes set by edje_object_color_class_set() will override the values set by this function).
The first color is the object, the second is the text outline, and the third is the text shadow. (Note that the second two only apply to text parts).
Setting color emits a signal "color_class,set" with source being the given color class in all objects.
See also
edje_color_class_set().
Note
unlike Evas, Edje colors are not pre-multiplied. That is, half-transparent white is 255 255 255 128.
edje_evas_global_perspective_get()
EAPI const Edje_Perspective* edje_evas_global_perspective_get (const Evas * e)
Get the global perspective object set for this canvas.
Parameters
e The given canvas (Evas).
Returns
The perspective object set as global for this canvas. Or NULL if there is no global perspective set and on errors.
This function will return the perspective object that was set as global with edje_perspective_global_set().
See also
edje_perspective_global_set()
edje_perspective_global_get()
edje_extern_object_aspect_set()
EAPI void edje_extern_object_aspect_set (Evas_Object * obj, Edje_Aspect_Control aspect, Evas_Coord aw, Evas_Coord ah)
Set the object aspect size.
Parameters
obj A valid Evas_Object handle
aspect The aspect control axes
aw The aspect radio width
ah The aspect ratio height
This sets the desired aspect ratio to keep an object that will be swallowed by Edje. The width and height define a preferred size ASPECT and the object may be scaled to be larger or smaller, but retaining the relative scale of both aspect width and height.
References _Edje_Real_Part::aspect, EDJE_ASPECT_CONTROL_BOTH, EDJE_ASPECT_CONTROL_HORIZONTAL, EDJE_ASPECT_CONTROL_NEITHER, EDJE_ASPECT_CONTROL_NONE, EDJE_ASPECT_CONTROL_VERTICAL, _Edje_Aspect::h, _Edje_Aspect::mode, _Edje_Real_Part::swallow_params, and _Edje_Aspect::w.
edje_extern_object_max_size_set()
EAPI void edje_extern_object_max_size_set (Evas_Object * obj, Evas_Coord maxw, Evas_Coord maxh)
Set the object maximum size.
Parameters
obj A valid Evas_Object handle
maxw The maximum width
maxh The maximum height
This sets the maximum size restriction for the object.
References _Edje_Size::h, _Edje_Real_Part::max, _Edje_Real_Part::swallow_params, and _Edje_Size::w.
edje_extern_object_min_size_set()
EAPI void edje_extern_object_min_size_set (Evas_Object * obj, Evas_Coord minw, Evas_Coord minh)
Set the object minimum size.
Parameters
obj A valid Evas_Object handle
minw The minimum width
minh The minimum height
This sets the minimum size restriction for the object.
References _Edje_Size::h, _Edje_Real_Part::min, _Edje_Real_Part::swallow_params, and _Edje_Size::w.
edje_fontset_append_get()
EAPI const char* edje_fontset_append_get (void)
Get the edje append fontset.
Returns
The edje append fontset.
This function returns the edje append fontset set by edje_fontset_append_set() function.
See also
edje_fontset_append_set().
References _edje_fontset_append.
edje_fontset_append_set()
EAPI void edje_fontset_append_set (const char * fonts)
Set the edje append fontset.
Parameters
fonts The fontset to append.
This function sets the edje append fontset.
References _edje_fontset_append.
edje_freeze()
EAPI void edje_freeze (void)
Freeze Edje objects.
This function freezes all Edje animations in the current process.
Note
: for freeze a specific object
See also
edje_object_freeze().
edje_thaw()
References _edje_edjes, _edje_freeze_val, and edje_object_freeze().
edje_object_access_part_list_get()
EAPI Eina_List* edje_object_access_part_list_get (const Evas_Object * obj)
Retrieve a list all accessibility part names.
Parameters
obj A valid Evas_Object handle
Returns
A list all accessibility part names on obj
Since
1.7.0
References _edje_fetch(), _Edje_Part::access, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_object_calc_force()
EAPI void edje_object_calc_force (Evas_Object * obj)
Force a Size/Geometry calculation.
Parameters
obj A valid Evas_Object handle
Forces the object obj to recalculation layout regardless of freeze/thaw.
References _edje_fetch(), _edje_freeze_val, _edje_recalc_do(), _Edje::dirty, and _Edje::freeze.
Referenced by edje_edit_part_clip_to_set(), edje_edit_part_effect_set(), edje_edit_part_scale_set(), edje_edit_state_color3_set(), edje_edit_state_image_border_fill_set(), edje_edit_state_image_border_set(), edje_edit_state_text_size_set(), edje_edit_state_visible_set(), edje_object_scale_set(), and edje_scale_set().
edje_object_color_class_del()
void edje_object_color_class_del (Evas_Object * obj, const char * color_class)
Delete the object color class.
Parameters
obj The edje object's reference.
color_class The color class to be deleted.
This function deletes any values at the object level for the specified object and color class.
Note
Deleting the color class will revert it to the values defined by edje_color_class_set() or the color class defined in the theme file.
Deleting the color class will emit the signal "color_class,del" for the given Edje object.
References _edje_emit(), _edje_fetch(), _edje_recalc(), _Edje::color_classes, _Edje::dirty, edje_object_color_class_del(), EDJE_PART_TYPE_GROUP, _Edje_Real_Part::part, _Edje::recalc_call, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_object_color_class_del().
edje_object_color_class_get()
EAPI Eina_Bool edje_object_color_class_get (const Evas_Object * o, const char * color_class, int * r, int * g, int * b, int * a, int * r2, int * g2, int * b2, int * a2, int * r3, int * g3, int * b3, int * a3)
Gets the object color class.
Parameters
o A valid Evas_Object handle
color_class
r Object Red value
g Object Green value
b Object Blue value
a Object Alpha value
r2 Outline Red value
g2 Outline Green value
b2 Outline Blue value
a2 Outline Alpha value
r3 Shadow Red value
g3 Shadow Green value
b3 Shadow Blue value
a3 Shadow Alpha value
Returns
EINA_TRUE if found or EINA_FALSE if not found and all values are zeroed.
This function gets the color values for an object level color class. If no explicit object color is set, then global values will be used.
The first color is the object, the second is the text outline, and the third is the text shadow. (Note that the second two only apply to text parts).
Note
unlike Evas, Edje colors are not pre-multiplied. That is, half-transparent white is 255 255 255 128.
References _edje_color_class_find(), _edje_fetch(), and S.
edje_object_color_class_set()
EAPI Eina_Bool edje_object_color_class_set (Evas_Object * obj, const char * color_class, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Sets the object color class.
Parameters
obj A valid Evas_Object handle
color_class
r Object Red value
g Object Green value
b Object Blue value
a Object Alpha value
r2 Outline Red value
g2 Outline Green value
b2 Outline Blue value
a2 Outline Alpha value
r3 Shadow Red value
g3 Shadow Green value
b3 Shadow Blue value
a3 Shadow Alpha value
This function sets the color values for an object level color class. This will cause all edje parts in the specified object that have the specified color class to have their colors multiplied by these values.
The first color is the object, the second is the text outline, and the third is the text shadow. (Note that the second two only apply to text parts).
Setting color emits a signal "color_class,set" with source being the given color.
Note
unlike Evas, Edje colors are not pre-multiplied. That is, half-transparent white is 255 255 255 128.
References _edje_emit(), _edje_fetch(), _edje_recalc(), _Edje_Color_Class::a, _Edje_Color_Class::a2, _Edje_Color_Class::a3, _Edje_Color_Class::b, _Edje_Color_Class::b2, _Edje_Color_Class::b3, _Edje::color_classes, _Edje::dirty, edje_object_color_class_set(), EDJE_PART_TYPE_GROUP, _Edje_Color_Class::g, _Edje_Color_Class::g2, _Edje_Color_Class::g3, _Edje_Color_Class::name, _Edje_Real_Part::part, _Edje_Color_Class::r, _Edje_Color_Class::r2, _Edje_Color_Class::r3, _Edje::recalc_call, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_object_color_class_set().
edje_object_data_get()
EAPI const char* edje_object_data_get (const Evas_Object * obj, const char * key)
Retrive an EDC data field's value from a given Edje object's group.
Parameters
obj A handle to an Edje object
key The data field's key string
Returns
The data's value string. Must not be freed.
This function fetches an EDC data field's value, which is declared on the objects building EDC file, under its group. EDC data blocks are most commonly used to pass arbitrary parameters from an application's theme to its code.
They look like the following:
collections {
  group {
    name: "a_group";
    data {
  item: "key1" "value1";
  item: "key2" "value2";
    }
  }
}
EDC data fields always hold strings as values, hence the return type of this function. Check the complete syntax reference for EDC files.
Warning
Do not confuse this call with edje_file_data_get(), which queries for a global EDC data field on an EDC declaration file.
See also
edje_object_file_set()
References _edje_fetch(), _Edje::collection, _Edje_Part_Collection::data, and edje_string_get().
edje_object_freeze()
EAPI int edje_object_freeze (Evas_Object * obj)
Freezes the Edje object.
Parameters
obj A handle to an Edje object.
Returns
The frozen state or 0 on Error
This function puts all changes on hold. Successive freezes will nest, requiring an equal number of thaws.
See also
edje_object_thaw()
References _edje_fetch(), _edje_freeze(), edje_object_freeze(), EDJE_PART_TYPE_GROUP, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_freeze(), and edje_object_freeze().
edje_object_item_provider_set()
EAPI void edje_object_item_provider_set (Evas_Object * obj, Edje_Item_Provider_Cb func, void * data)
Set the function that provides item objects for named items in an edje entry text.
Parameters
obj A valid Evas Object handle
func The function to call (or NULL to disable) to get item objects
data The data pointer to pass to the func callback
Item objects may be deleted any time by Edje, and will be deleted when the Edje object is deleted (or file is set to a new file).
References _edje_fetch(), _Edje::data, _Edje::func, and _Edje::item_provider.
edje_object_mirrored_get()
EAPI Eina_Bool edje_object_mirrored_get (const Evas_Object * obj)
Get the RTL orientation for this object.
You can RTL orientation explicitly with edje_object_mirrored_set.
Parameters
obj A handle to an Edje object.
Returns
EINA_TRUE if the flag is set or EINA_FALSE if not.
Since
1.1.0
References _edje_fetch(), and _Edje::is_rtl.
Referenced by _edje_object_orientation_inform(), and _edje_part_description_find().
edje_object_mirrored_set()
EAPI void edje_object_mirrored_set (Evas_Object * obj, Eina_Bool rtl)
Set the RTL orientation for this object.
Parameters
obj A handle to an Edje object.
rtl new value of flag EINA_TRUE/EINA_FALSE
Since
1.1.0
References _edje_fetch(), _edje_object_orientation_inform(), _edje_part_description_apply(), _edje_recalc_do(), _Edje_Real_Part::chosen_description, _Edje_Real_Part_State::description, _Edje::is_rtl, _Edje_Part_Description_Common::name, _Edje_Real_Part::param1, _Edje_Part_Description_Common::state, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part_Description_Common::value.
edje_object_part_box_append()
EAPI Eina_Bool edje_object_part_box_append (Evas_Object * obj, const char * part, Evas_Object * child)
Appends an object to the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to append
Returns
EINA_TRUE: Successfully added.
EINA_FALSE: An error occurred.
Appends child to the box indicated by part.
See also
edje_object_part_box_prepend()
edje_object_part_box_insert_before()
edje_object_part_box_insert_at()
References _edje_fetch(), _edje_real_part_box_append(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_BOX, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_box_insert_at()
EAPI Eina_Bool edje_object_part_box_insert_at (Evas_Object * obj, const char * part, Evas_Object * child, unsigned int pos)
Inserts an object to the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to insert
pos The position where to insert child
Returns
EINA_TRUE: Successfully added.
EINA_FALSE: An error occurred.
Adds child to the box indicated by part, in the position given by pos.
See also
edje_object_part_box_append()
edje_object_part_box_prepend()
edje_object_part_box_insert_before()
References _edje_fetch(), _edje_real_part_box_insert_at(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_BOX, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_box_insert_before()
EAPI Eina_Bool edje_object_part_box_insert_before (Evas_Object * obj, const char * part, Evas_Object * child, const Evas_Object * reference)
Adds an object to the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to insert
reference The object to be used as reference
Returns
EINA_TRUE: Successfully added.
EINA_FALSE: An error occurred.
Inserts child in the box given by part, in the position marked by reference.
See also
edje_object_part_box_append()
edje_object_part_box_prepend()
edje_object_part_box_insert_at()
References _edje_fetch(), _edje_real_part_box_insert_before(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_BOX, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_box_prepend()
EAPI Eina_Bool edje_object_part_box_prepend (Evas_Object * obj, const char * part, Evas_Object * child)
Prepends an object to the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to prepend
Returns
EINA_TRUE: Successfully added.
EINA_FALSE: An error occurred.
Prepends child to the box indicated by part.
See also
edje_object_part_box_append()
edje_object_part_box_insert_before()
edje_object_part_box_insert_at()
References _edje_fetch(), _edje_real_part_box_prepend(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_BOX, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_box_remove()
EAPI Evas_Object* edje_object_part_box_remove (Evas_Object * obj, const char * part, Evas_Object * child)
Removes an object from the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to remove
Returns
Pointer to the object removed, or NULL.
Removes child from the box indicated by part.
See also
edje_object_part_box_remove_at()
edje_object_part_box_remove_all()
References _edje_fetch(), _edje_real_part_box_remove(), _edje_real_part_recursive_get(), _edje_user_definition_free(), _Edje_User_Defined::box, EDJE_PART_TYPE_BOX, EDJE_USER_BOX_PACK, _Edje_Real_Part::part, _Edje_User_Defined::part, _Edje_Part::type, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_box_remove_all()
EAPI Eina_Bool edje_object_part_box_remove_all (Evas_Object * obj, const char * part, Eina_Bool clear)
Removes all elements from the box.
Parameters
obj A valid Evas_Object handle
part The part name
clear Delete objects on removal
Returns
1: Successfully cleared.
0: An error occurred.
Removes all the external objects from the box indicated by part. Elements created from the theme will not be removed.
See also
edje_object_part_box_remove()
edje_object_part_box_remove_at()
References _edje_fetch(), _edje_real_part_box_remove_all(), _edje_real_part_recursive_get(), _edje_user_definition_free(), EDJE_PART_TYPE_BOX, EDJE_USER_BOX_PACK, _Edje_Real_Part::part, _Edje_User_Defined::part, _Edje_Part::type, _Edje_User_Defined::type, and _Edje::user_defined.
edje_object_part_box_remove_at()
EAPI Evas_Object* edje_object_part_box_remove_at (Evas_Object * obj, const char * part, unsigned int pos)
Removes an object from the box.
Parameters
obj A valid Evas_Object handle
part The part name
pos The position index of the object (starts counting from 0)
Returns
Pointer to the object removed, or NULL.
Removes from the box indicated by part, the object in the position pos.
See also
edje_object_part_box_remove()
edje_object_part_box_remove_all()
References _edje_fetch(), _edje_real_part_box_remove_at(), _edje_real_part_recursive_get(), _edje_user_definition_free(), _Edje_User_Defined::box, EDJE_PART_TYPE_BOX, EDJE_USER_BOX_PACK, _Edje_Real_Part::part, _Edje_User_Defined::part, _Edje_Part::type, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_dir_get()
EAPI Edje_Drag_Dir edje_object_part_drag_dir_get (const Evas_Object * obj, const char * part)
Determine dragable directions.
Parameters
obj A valid Evas_Object handle
part The part name
The dragable directions are defined in the EDC file, inside the dragable section, by the attributes x and y. See the Edje Data Collection reference for more information.
Returns
EDJE_DRAG_DIR_NONE: Not dragable
EDJE_DRAG_DIR_X: Dragable in X direction
EDJE_DRAG_DIR_Y: Dragable in Y direction
EDJE_DRAG_DIR_XY: Dragable in X & Y directions
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Part::dragable, EDJE_DRAG_DIR_NONE, EDJE_DRAG_DIR_X, EDJE_DRAG_DIR_XY, EDJE_DRAG_DIR_Y, _Edje_Real_Part::part, _Edje_Part_Dragable::x, and _Edje_Part_Dragable::y.
edje_object_part_drag_page()
EAPI Eina_Bool edje_object_part_drag_page (Evas_Object * obj, const char * part, double dx, double dy)
Pages x,y steps.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x step
dy The y step
Pages x,y where the increment is defined by edje_object_part_drag_page_set.
Values for dx and dy are real numbers that range from 0 to 1.
Warning
Paging is bugged!
See also
edje_object_part_drag_step()
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part_Drag::count, _Edje_Real_Part_Drag::down, _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_PAGE, FLOAT_T, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_page_get()
EAPI Eina_Bool edje_object_part_drag_page_get (const Evas_Object * obj, const char * part, double * dx, double * dy)
Gets the page step increments.
Parameters
obj A valid Evas_Object handle
part The part name
dx The dx page increment pointer
dy The dy page increment pointer
Gets the x,y page step increments for the dragable object.
See also
edje_object_part_drag_page_set()
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::drag, _Edje_Real_Part_Drag::page, TO_DOUBLE, _Edje_Position_Scale::x, and _Edje_Position_Scale::y.
edje_object_part_drag_page_set()
EAPI Eina_Bool edje_object_part_drag_page_set (Evas_Object * obj, const char * part, double dx, double dy)
Sets the page step increments.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x page step increment
dy The y page step increment
Sets the x,y page step increment values.
Values for dx and dy are real numbers that range from 0 to 1, representing the relative size of the dragable area on that axis by which the part will be moved.
See also
edje_object_part_drag_page_get()
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_PAGE, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_size_get()
EAPI Eina_Bool edje_object_part_drag_size_get (const Evas_Object * obj, const char * part, double * dw, double * dh)
Get the dragable object size.
Parameters
obj A valid Evas_Object handle
part The part name
dw The drag width pointer
dh The drag height pointer
Gets the dragable object size.
See also
edje_object_part_drag_size_set()
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::drag, _Edje_Real_Part_Drag::size, TO_DOUBLE, _Edje_Position_Scale::x, and _Edje_Position_Scale::y.
edje_object_part_drag_size_set()
EAPI Eina_Bool edje_object_part_drag_size_set (Evas_Object * obj, const char * part, double dw, double dh)
Set the dragable object size.
Parameters
obj A valid Evas_Object handle
part The part name
dw The drag width
dh The drag height
Values for dw and dh are real numbers that range from 0 to 1, representing the relative size of the dragable area on that axis.
Sets the size of the dragable object.
See also
edje_object_part_drag_size_get()
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part::drag, _Edje_User_Defined::drag_size, EDJE_USER_DRAG_SIZE, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_step()
EAPI Eina_Bool edje_object_part_drag_step (Evas_Object * obj, const char * part, double dx, double dy)
Steps the dragable x,y steps.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x step
dy The y step
Steps x,y where the step increment is the amount set by edje_object_part_drag_step_set.
Values for dx and dy are real numbers that range from 0 to 1.
See also
edje_object_part_drag_page()
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part_Drag::count, _Edje_Real_Part_Drag::down, _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_STEP, FLOAT_T, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_step_get()
EAPI Eina_Bool edje_object_part_drag_step_get (const Evas_Object * obj, const char * part, double * dx, double * dy)
Gets the drag step increment values.
Parameters
obj A valid Evas_Object handle
part The part
dx The x step increment pointer
dy The y step increment pointer
Gets the x and y step increments for the dragable object.
See also
edje_object_part_drag_step_set()
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::drag, _Edje_Real_Part_Drag::step, TO_DOUBLE, _Edje_Position_Scale::x, and _Edje_Position_Scale::y.
edje_object_part_drag_step_set()
EAPI Eina_Bool edje_object_part_drag_step_set (Evas_Object * obj, const char * part, double dx, double dy)
Sets the drag step increment.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x step amount
dy The y step amount
Sets the x,y step increments for a dragable object.
Values for dx and dy are real numbers that range from 0 to 1, representing the relative size of the dragable area on that axis by which the part will be moved.
See also
edje_object_part_drag_step_get()
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_STEP, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_value_get()
EAPI Eina_Bool edje_object_part_drag_value_get (const Evas_Object * obj, const char * part, double * dx, double * dy)
Get the dragable object location.
Parameters
obj A valid Evas_Object handle
part The part name
dx The X value pointer
dy The Y value pointer
Values for dx and dy are real numbers that range from 0 to 1, representing the relative position to the dragable area on that axis.
See also
edje_object_part_drag_value_set()
Gets the drag location values.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::drag, _Edje_Part::dragable, _Edje_Real_Part::part, TO_DOUBLE, _Edje_Real_Part_Drag::val, _Edje_Position_Scale::x, _Edje_Part_Dragable::x, _Edje_Position_Scale::y, and _Edje_Part_Dragable::y.
edje_object_part_drag_value_set()
EAPI Eina_Bool edje_object_part_drag_value_set (Evas_Object * obj, const char * part, double dx, double dy)
Set the dragable object location.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x value
dy The y value
Places the dragable object at the given location.
Values for dx and dy are real numbers that range from 0 to 1, representing the relative position to the dragable area on that axis.
This value means, for the vertical axis, that 0.0 will be at the top if the first parameter of y in the dragable part theme is 1, and at bottom if it is -1.
For the horizontal axis, 0.0 means left if the first parameter of x in the dragable part theme is 1, and right if it is -1.
See also
edje_object_part_drag_value_get()
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part_Drag::count, _Edje_Real_Part_Drag::down, _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_VALUE, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_exists()
EAPI Eina_Bool edje_object_part_exists (const Evas_Object * obj, const char * part)
Check if an Edje part exists in a given Edje object's group definition.
Parameters
obj A handle to an Edje object
part The part's name to check for existence in obj's group
Returns
EINA_TRUE, if the Edje part exists in obj's group or EINA_FALSE, otherwise (and on errors)
This function returns if a given part exists in the Edje group bound to object obj (with edje_object_file_set()).
This call is useful, for example, when one could expect or not a given GUI element, depending on the theme applied to obj.
References _edje_fetch(), and _edje_real_part_recursive_get().
edje_object_part_geometry_get()
EAPI Eina_Bool edje_object_part_geometry_get (const Evas_Object * obj, const char * part, Evas_Coord * x, Evas_Coord * y, Evas_Coord * w, Evas_Coord * h)
Retrieve the geometry of a given Edje part, in a given Edje object's group definition, relative to the object's area
Parameters
obj A handle to an Edje object
part The Edje part's name
x A pointer to a variable where to store the part's x coordinate
y A pointer to a variable where to store the part's y coordinate
w A pointer to a variable where to store the part's width
h A pointer to a variable where to store the part's height
This function gets the geometry of an Edje part within its group. The x and y coordinates are relative to the top left corner of the whole obj object's area.
Note
Use NULL pointers on the geometry components you're not interested in: they'll be ignored by the function.
On failure, this function will make all non-NULL geometry pointers' pointed variables be set to zero.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::h, _Edje_Real_Part::w, _Edje_Real_Part::x, and _Edje_Real_Part::y.
edje_object_part_object_get()
EAPI const Evas_Object* edje_object_part_object_get (const Evas_Object * obj, const char * part)
Get a handle to the Evas object implementing a given Edje part, in an Edje object.
Parameters
obj A handle to an Edje object
part The Edje part's name
Returns
A pointer to the Evas object implementing the given part, or NULL on failure (e.g. the given part doesn't exist)
This function gets a pointer of the Evas object corresponding to a given part in the obj object's group.
You should never modify the state of the returned object (with evas_object_move() or evas_object_hide() for example), because it's meant to be managed by Edje, solely. You are safe to query information about its current state (with evas_object_visible_get() or evas_object_color_get() for example), though.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), and _Edje_Real_Part::object.
edje_object_part_state_get()
EAPI const char* edje_object_part_state_get (const Evas_Object * obj, const char * part, double * val_ret)
Returns the state of the Edje part.
Parameters
obj A valid Evas_Object handle
part The part name
val_ret
Returns
The part state:
"default" for the default state
"" for other states
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::chosen_description, _Edje_Real_Part_State::description, INF, _Edje_Part_Description_Common::name, _Edje_Real_Part::param1, _Edje_Part_Description_Common::state, and _Edje_Part_Description_Common::value.
edje_object_part_swallow()
EAPI Eina_Bool edje_object_part_swallow (Evas_Object * obj, const char * part, Evas_Object * obj_swallow)
"Swallows" an object into one of the Edje object SWALLOW parts.
Parameters
obj A valid Edje object handle
part The swallow part's name
obj_swallow The object to occupy that part
Swallowing an object into an Edje object is, for a given part of type SWALLOW in the EDC group which gave life to obj, to set an external object to be controlled by obj, being displayed exactly over that part's region inside the whole Edje object's viewport.
From this point on, obj will have total control over obj_swallow's geometry and visibility. For instance, if obj is visible, as in evas_object_show(), the swallowed object will be visible too – if the given SWALLOW part it's in is also visible. Other actions on obj will also reflect on the swallowed object as well (e.g. resizing, moving, raising/lowering, etc.).
Finally, all internal changes to part, specifically, will reflect on the displaying of obj_swallow, for example state changes leading to different visibility states, geometries, positions, etc.
If an object has already been swallowed into this part, then it will first be unswallowed (as in edje_object_part_unswallow()) before the new object is swallowed.
Note
obj won't delete the swallowed object once it is deleted – obj_swallow will get to an unparented state again.
For more details on EDC SWALLOW parts, see syntaxreference".
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_real_part_swallow(), _edje_recalc_do(), DBG, _Edje_Real_Part::edje, edje_object_part_unswallow(), EDJE_PART_TYPE_SWALLOW, ERR, _Edje_Part::name, _Edje::obj, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, and _Edje_Part::type.
edje_object_part_swallow_get()
EAPI Evas_Object* edje_object_part_swallow_get (const Evas_Object * obj, const char * part)
Get the object currently swallowed by a part.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The swallowed object, or NULL if there is none.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), and _Edje_Real_Part::swallowed_object.
edje_object_part_table_child_get()
EAPI Evas_Object* edje_object_part_table_child_get (const Evas_Object * obj, const char * part, unsigned int col, unsigned int row)
Retrieve a child from a table.
Parameters
obj A valid Evas_Object handle
part The part name
col The column of the child to get
row The row of the child to get
Returns
The child Evas_Object
References _edje_fetch(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TABLE, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_table_clear()
EAPI Eina_Bool edje_object_part_table_clear (Evas_Object * obj, const char * part, Eina_Bool clear)
Removes all object from the table.
Parameters
obj A valid Evas_Object handle
part The part name
clear If set, will delete subobjs on remove
Returns
EINA_TRUE clear the table, EINA_FALSE on failure
Removes all object from the table indicated by part, except the internal ones set from the theme.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_real_part_table_clear(), EDJE_PART_TYPE_TABLE, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_table_col_row_size_get()
EAPI Eina_Bool edje_object_part_table_col_row_size_get (const Evas_Object * obj, const char * part, int * cols, int * rows)
Gets the number of columns and rows the table has.
Parameters
obj A valid Evas_Object handle
part The part name
cols Pointer where to store number of columns (can be NULL)
rows Pointer where to store number of rows (can be NULL)
Returns
EINA_TRUE get some data, EINA_FALSE on failure
Retrieves the size of the table in number of columns and rows.
References _edje_fetch(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TABLE, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_table_pack()
EAPI Eina_Bool edje_object_part_table_pack (Evas_Object * obj, const char * part, Evas_Object * child_obj, unsigned short col, unsigned short row, unsigned short colspan, unsigned short rowspan)
Packs an object into the table.
Parameters
obj A valid Evas_Object handle
part The part name
child_obj The object to pack in
col The column to place it in
row The row to place it in
colspan Columns the child will take
rowspan Rows the child will take
Returns
EINA_TRUE object was added, EINA_FALSE on failure
Packs an object into the table indicated by part.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_real_part_table_pack(), EDJE_PART_TYPE_TABLE, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_table_unpack()
EAPI Eina_Bool edje_object_part_table_unpack (Evas_Object * obj, const char * part, Evas_Object * child_obj)
Removes an object from the table.
Parameters
obj A valid Evas_Object handle
part The part name
child_obj The object to pack in
Returns
EINA_TRUE object removed, EINA_FALSE on failure
Removes an object from the table indicated by part.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_real_part_table_unpack(), _edje_user_definition_free(), EDJE_PART_TYPE_TABLE, EDJE_USER_TABLE_PACK, _Edje_Real_Part::part, _Edje_User_Defined::part, _Edje_User_Defined::table, _Edje_Part::type, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_text_anchor_geometry_get()
EAPI const Eina_List* edje_object_part_text_anchor_geometry_get (const Evas_Object * obj, const char * part, const char * anchor)
Return a list of Evas_Textblock_Rectangle anchor rectangles.
Parameters
obj A valid Evas_Object handle
part The part name
anchor The anchor name
Returns
The list of anchor rects (const Evas_Textblock_Rectangle *), do not modify! Geometry is relative to entry part.
This function return a list of Evas_Textblock_Rectangle anchor rectangles.
References _edje_entry_anchor_geometry_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_anchor_list_get()
EAPI const Eina_List* edje_object_part_text_anchor_list_get (const Evas_Object * obj, const char * part)
Return a list of char anchor names.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The list of anchors (const char *), do not modify!
This function returns a list of char anchor names.
References _edje_entry_anchors_list(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_append()
EAPI void edje_object_part_text_append (Evas_Object * obj, const char * part, const char * text)
Insert text for an object part.
Parameters
obj A valid Evas Object handle
part The part name
text The text string
This function inserts the text for an object part at the end; It does not move the cursor.
Since
1.1
References _edje_fetch(), _edje_object_part_text_raw_append(), _edje_real_part_recursive_get(), _edje_recalc(), _Edje::data, _Edje::dirty, _Edje_Real_Part::edje, EDJE_PART_TYPE_TEXTBLOCK, _Edje::func, _Edje_Real_Part::part, _Edje::recalc_call, _Edje::recalc_hints, _Edje::text_change, and _Edje_Part::type.
edje_object_part_text_autocapital_type_get()
EAPI Edje_Text_Autocapital_Type edje_object_part_text_autocapital_type_get (const Evas_Object * obj, const char * part)
Retrieves the autocapitalization type.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The autocapitalization type
Since
1.1.0
References _edje_entry_autocapital_type_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_TEXT_AUTOCAPITAL_TYPE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_autocapital_type_set()
EAPI void edje_object_part_text_autocapital_type_set (Evas_Object * obj, const char * part, Edje_Text_Autocapital_Type autocapital_type)
Set the autocapitalization type on the immodule.
Parameters
obj A valid Evas_Object handle
part The part name
autocapital_type The type of autocapitalization
Since
1.1.0
References _edje_entry_autocapital_type_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_begin_set()
EAPI void edje_object_part_text_cursor_begin_set (Evas_Object * obj, const char * part, Edje_Cursor cur)
Moves the cursor to the beginning of the text part.
See also
evas_textblock_cursor_paragraph_first
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_begin(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_content_get()
EAPI char* edje_object_part_text_cursor_content_get (const Evas_Object * obj, const char * part, Edje_Cursor cur)
Returns the content (char) at the cursor position.
See also
evas_textblock_cursor_content_get
You must free the return (if not NULL) after you are done with it.
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to use
Returns
The character string pointed to (may be a multi-byte utf8 sequence) terminated by a nul byte.
References _edje_entry_cursor_content_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_coord_set()
EAPI Eina_Bool edje_object_part_text_cursor_coord_set (Evas_Object * obj, const char * part, Edje_Cursor cur, Evas_Coord x, Evas_Coord y)
Position the given cursor to a X,Y position.
This is frequently used with the user cursor.
Parameters
obj An Edje object.
part The part containing the object.
cur The cursor to adjust.
x X Coordinate.
y Y Coordinate.
Returns
True on success, false on error.
References _edje_entry_cursor_coord_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_copy()
EAPI void edje_object_part_text_cursor_copy (Evas_Object * obj, const char * part, Edje_Cursor src, Edje_Cursor dst)
Copy the cursor to another cursor.
Parameters
obj A valid Evas_Object handle
part The part name
src the cursor to copy from
dst the cursor to copy to
References _edje_entry_cursor_copy(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_down()
EAPI Eina_Bool edje_object_part_text_cursor_down (Evas_Object * obj, const char * part, Edje_Cursor cur)
Moves the cursor to the char below the current cursor position.
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_down(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_end_set()
EAPI void edje_object_part_text_cursor_end_set (Evas_Object * obj, const char * part, Edje_Cursor cur)
Moves the cursor to the end of the text part.
See also
evas_textblock_cursor_paragraph_last
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_end(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_geometry_get()
EAPI void edje_object_part_text_cursor_geometry_get (const Evas_Object * obj, const char * part, Evas_Coord * x, Evas_Coord * y, Evas_Coord * w, Evas_Coord * h)
Returns the cursor geometry of the part relative to the edje object.
Parameters
obj A valid Evas_Object handle
part The part name
x Cursor X position
y Cursor Y position
w Cursor width
h Cursor height
References _edje_entry_cursor_geometry_get(), _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, _Edje_Real_Part::part, _Edje::x, and _Edje::y.
edje_object_part_text_cursor_is_format_get()
EAPI Eina_Bool edje_object_part_text_cursor_is_format_get (const Evas_Object * obj, const char * part, Edje_Cursor cur)
Returns whether the cursor points to a format.
See also
evas_textblock_cursor_is_format
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to adjust.
Returns
EINA_TRUE if it's true, EINA_FALSE otherwise.
References _edje_entry_cursor_is_format_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_is_visible_format_get()
EAPI Eina_Bool edje_object_part_text_cursor_is_visible_format_get (const Evas_Object * obj, const char * part, Edje_Cursor cur)
Return true if the cursor points to a visible format For example \t, \n, item and etc.
See also
evas_textblock_cursor_format_is_visible_get
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to adjust.
References _edje_entry_cursor_is_visible_format_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_line_begin_set()
EAPI void edje_object_part_text_cursor_line_begin_set (Evas_Object * obj, const char * part, Edje_Cursor cur)
Move the cursor to the beginning of the line.
See also
evas_textblock_cursor_line_char_first
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_line_begin(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_line_end_set()
EAPI void edje_object_part_text_cursor_line_end_set (Evas_Object * obj, const char * part, Edje_Cursor cur)
Move the cursor to the end of the line.
See also
evas_textblock_cursor_line_char_last
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_line_end(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_next()
EAPI Eina_Bool edje_object_part_text_cursor_next (Evas_Object * obj, const char * part, Edje_Cursor cur)
Advances the cursor to the next cursor position.
See also
evas_textblock_cursor_char_next
Parameters
obj A valid Evas_Object handle
part The part name
cur The edje cursor to advance
References _edje_entry_cursor_next(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_pos_get()
EAPI int edje_object_part_text_cursor_pos_get (const Evas_Object * obj, const char * part, Edje_Cursor cur)
Retrieves the current position of the cursor.
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to get the position
Returns
The cursor position
Since
1.1.0
References _edje_entry_cursor_pos_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_pos_set()
EAPI void edje_object_part_text_cursor_pos_set (Evas_Object * obj, const char * part, Edje_Cursor cur, int pos)
Sets the cursor position to the given value.
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to move
pos the position of the cursor
Since
1.1.0
References _edje_entry_cursor_pos_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_prev()
EAPI Eina_Bool edje_object_part_text_cursor_prev (Evas_Object * obj, const char * part, Edje_Cursor cur)
Moves the cursor to the previous char.
See also
evas_textblock_cursor_char_prev
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_prev(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_up()
EAPI Eina_Bool edje_object_part_text_cursor_up (Evas_Object * obj, const char * part, Edje_Cursor cur)
Move the cursor to the char above the current cursor position.
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_up(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_escaped_set()
EAPI Eina_Bool edje_object_part_text_escaped_set (Evas_Object * obj, const char * part, const char * text)
Sets the text for an object part, but converts HTML escapes to UTF8.
This converts the given string text to UTF8 assuming it contains HTML style escapes like "&amp;" and "&copy;" etc. IF the part is of type TEXT, as opposed to TEXTBLOCK.
Parameters
obj A valid Evas Object handle
part The part name
text The text string
Returns
EINA_BOOL on success, EINA_FALSE otherwise
Since
1.2
References _edje_fetch(), _edje_object_part_text_raw_set(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TEXT, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_text_get()
EAPI const char* edje_object_part_text_get (const Evas_Object * obj, const char * part)
Return the text of the object part.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The text string
This function returns the text associated to the object part.
See also
edje_object_part_text_set().
References _edje_entry_text_get(), _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part::entry_mode, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje_Real_Part::text, and _Edje_Part::type.
Referenced by _edje_external_param_get().
edje_object_part_text_imf_context_get()
EAPI void* edje_object_part_text_imf_context_get (const Evas_Object * obj, const char * part)
Get the input method context in entry.
If ecore_imf was not available when edje was compiled, this function returns NULL otherwise, the returned pointer is an Ecore_IMF *
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The input method context (Ecore_IMF_Context *) in entry
Since
1.2.0
References _edje_entry_imf_context_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_imf_context_reset()
EAPI void edje_object_part_text_imf_context_reset (const Evas_Object * obj, const char * part)
Reset the input method context if needed.
This can be necessary in the case where modifying the buffer would confuse on-going input method behavior
Parameters
obj A valid Evas_Object handle
part The part name
Since
1.2.0
References _edje_entry_imf_context_reset(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_enabled_get()
EAPI Eina_Bool edje_object_part_text_input_panel_enabled_get (const Evas_Object * obj, const char * part)
Retrieve the attribute to show the input panel automatically.
See also
edje_object_part_text_input_panel_enabled_set
Parameters
obj A valid Evas_Object handle
part The part name
Returns
EINA_TRUE if it supports or EINA_FALSE otherwise
Since
1.1.0
References _edje_entry_input_panel_enabled_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_enabled_set()
EAPI void edje_object_part_text_input_panel_enabled_set (Evas_Object * obj, const char * part, Eina_Bool enabled)
Sets the attribute to show the input panel automatically.
Parameters
obj A valid Evas_Object handle
part The part name
enabled If true, the input panel is appeared when entry is clicked or has a focus
Since
1.1.0
References _edje_entry_input_panel_enabled_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_hide()
EAPI void edje_object_part_text_input_panel_hide (const Evas_Object * obj, const char * part)
Hide the input panel (virtual keyboard).
See also
edje_object_part_text_input_panel_show
Note that input panel is shown or hidden automatically according to the focus state. This API can be used in the case of manually controlling by using edje_object_part_text_input_panel_enabled_set.
Parameters
obj A valid Evas_Object handle
part The part name
Since
1.2.0
References _edje_entry_input_panel_hide(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_imdata_get()
EAPI void edje_object_part_text_input_panel_imdata_get (const Evas_Object * obj, const char * part, void * data, int * len)
Get the specific data of the current active input panel.
Parameters
obj A valid Evas_Object handle
part The part name
data The specific data to be got from the input panel
len The length of data
Since
1.2.0
References _edje_entry_input_panel_imdata_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_imdata_set()
EAPI void edje_object_part_text_input_panel_imdata_set (Evas_Object * obj, const char * part, const void * data, int len)
Set the input panel-specific data to deliver to the input panel.
This API is used by applications to deliver specific data to the input panel. The data format MUST be negotiated by both application and the input panel. The size and format of data are defined by the input panel.
Parameters
obj A valid Evas_Object handle
part The part name
data The specific data to be set to the input panel.
len the length of data, in bytes, to send to the input panel
Since
1.2.0
References _edje_entry_input_panel_imdata_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_language_get()
EAPI Edje_Input_Panel_Lang edje_object_part_text_input_panel_language_get (const Evas_Object * obj, const char * part)
Get the language mode of the input panel.
See edje_object_part_text_input_panel_language_set for more details.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
input panel language type
Since
1.2.0
References _edje_entry_input_panel_language_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_INPUT_PANEL_LANG_AUTOMATIC, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_language_set()
EAPI void edje_object_part_text_input_panel_language_set (Evas_Object * obj, const char * part, Edje_Input_Panel_Lang lang)
Set the language mode of the input panel.
This API can be used if you want to show the Alphabet keyboard.
Parameters
obj A valid Evas_Object handle
part The part name
lang the language to be set to the input panel.
Since
1.2.0
References _edje_entry_input_panel_language_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_layout_get()
EAPI Edje_Input_Panel_Layout edje_object_part_text_input_panel_layout_get (const Evas_Object * obj, const char * part)
Get the layout of the input panel.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
Layout type of the input panel
See also
edje_object_part_text_input_panel_layout_set
Since
1.1
References _edje_entry_input_panel_layout_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_INPUT_PANEL_LAYOUT_INVALID, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_layout_set()
EAPI void edje_object_part_text_input_panel_layout_set (Evas_Object * obj, const char * part, Edje_Input_Panel_Layout layout)
Set the layout of the input panel.
The layout of the input panel or virtual keyboard can make it easier or harder to enter content. This allows you to hint what kind of input you are expecting to enter and thus have the input panel automatically come up with the right mode.
Parameters
obj A valid Evas_Object handle
part The part name
layout layout type
Since
1.1
References _edje_entry_input_panel_layout_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_return_key_disabled_get()
EAPI Eina_Bool edje_object_part_text_input_panel_return_key_disabled_get (const Evas_Object * obj, const char * part)
Get whether the return key on the input panel should be disabled or not.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
EINA_TRUE if it should be disabled
Since
1.2.0
References _edje_entry_input_panel_return_key_disabled_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_return_key_disabled_set()
EAPI void edje_object_part_text_input_panel_return_key_disabled_set (Evas_Object * obj, const char * part, Eina_Bool disabled)
Set the return key on the input panel to be disabled.
Parameters
obj A valid Evas_Object handle
part The part name
disabled The state
Since
1.2.0
References _edje_entry_input_panel_return_key_disabled_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_return_key_type_get()
EAPI Edje_Input_Panel_Return_Key_Type edje_object_part_text_input_panel_return_key_type_get (const Evas_Object * obj, const char * part)
Get the "return" key type.
See also
edje_object_part_text_input_panel_return_key_type_set() for more details
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The type of "return" key on the input panel
Since
1.2.0
References _edje_entry_input_panel_return_key_type_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DEFAULT, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_return_key_type_set()
EAPI void edje_object_part_text_input_panel_return_key_type_set (Evas_Object * obj, const char * part, Edje_Input_Panel_Return_Key_Type return_key_type)
Set the "return" key type.
This type is used to set string or icon on the "return" key of the input panel.
An input panel displays the string or icon associated with this type
Parameters
obj A valid Evas_Object handle
part The part name
return_key_type The type of "return" key on the input panel
Since
1.2.0
References _edje_entry_input_panel_return_key_type_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_show()
EAPI void edje_object_part_text_input_panel_show (const Evas_Object * obj, const char * part)
Show the input panel (virtual keyboard) based on the input panel property such as layout, autocapital types, and so on.
Note that input panel is shown or hidden automatically according to the focus state. This API can be used in the case of manually controlling by using edje_object_part_text_input_panel_enabled_set.
Parameters
obj A valid Evas_Object handle
part The part name
Since
1.2.0
References _edje_entry_input_panel_show(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_insert()
EAPI void edje_object_part_text_insert (Evas_Object * obj, const char * part, const char * text)
Insert text for an object part.
Parameters
obj A valid Evas Object handle
part The part name
text The text string
This function inserts the text for an object part just before the cursor position.
References _edje_entry_text_markup_insert(), _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc(), _Edje::data, _Edje::dirty, _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part::entry_mode, _Edje::func, _Edje_Real_Part::part, _Edje::recalc_call, _Edje::recalc_hints, _Edje::text_change, and _Edje_Part::type.
edje_object_part_text_item_geometry_get()
EAPI Eina_Bool edje_object_part_text_item_geometry_get (const Evas_Object * obj, const char * part, const char * item, Evas_Coord * cx, Evas_Coord * cy, Evas_Coord * cw, Evas_Coord * ch)
Return item geometry.
Parameters
obj A valid Evas_Object handle
part The part name
item The item name
cx Item x return (relative to entry part)
cy Item y return (relative to entry part)
cw Item width return
ch Item height return
Returns
1 if item exists, 0 if not
This function return a list of Evas_Textblock_Rectangle item rectangles.
References _edje_entry_item_geometry_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_item_list_get()
EAPI const Eina_List* edje_object_part_text_item_list_get (const Evas_Object * obj, const char * part)
Return a list of char item names.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The list of items (const char *), do not modify!
This function returns a list of char item names.
References _edje_entry_items_list(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_prediction_allow_get()
EAPI Eina_Bool edje_object_part_text_prediction_allow_get (const Evas_Object * obj, const char * part)
Get whether the prediction is allowed or not.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
EINA_TRUE if prediction feature is allowed.
Since
1.2.0
References _edje_entry_prediction_allow_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_prediction_allow_set()
EAPI void edje_object_part_text_prediction_allow_set (Evas_Object * obj, const char * part, Eina_Bool prediction)
Set whether the prediction is allowed or not.
Parameters
obj A valid Evas_Object handle
part The part name
prediction If true, the prediction feature is allowed.
Since
1.2.0
References _edje_entry_prediction_allow_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_abort()
EAPI void edje_object_part_text_select_abort (const Evas_Object * obj, const char * part)
Aborts any selection action on a part.
Parameters
obj A valid Evas_Object handle
part The part name
References _edje_entry_select_abort(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_all()
EAPI void edje_object_part_text_select_all (const Evas_Object * obj, const char * part)
Set the selection to be everything.
Parameters
obj A valid Evas_Object handle
part The part name
This function selects all text of the object of the part.
References _edje_entry_select_all(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_allow_set()
EAPI void edje_object_part_text_select_allow_set (const Evas_Object * obj, const char * part, Eina_Bool allow)
Enables selection if the entry is an EXPLICIT selection mode type.
Parameters
obj A valid Evas_Object handle
part The part name
allow EINA_TRUE to enable, EINA_FALSE otherwise
The default is to not allow selection. This function only affects user selection, functions such as edje_object_part_text_select_all() and edje_object_part_text_select_none() are not affected.
References _edje_entry_select_allow_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_begin()
EAPI void edje_object_part_text_select_begin (const Evas_Object * obj, const char * part)
Starts selecting at current cursor position.
Parameters
obj A valid Evas_Object handle
part The part name
References _edje_entry_select_begin(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_extend()
EAPI void edje_object_part_text_select_extend (const Evas_Object * obj, const char * part)
Extends the current selection to the current cursor position.
Parameters
obj A valid Evas_Object handle
part The part name
References _edje_entry_select_extend(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_none()
EAPI void edje_object_part_text_select_none (const Evas_Object * obj, const char * part)
Set the selection to be none.
Parameters
obj A valid Evas_Object handle
part The part name
This function sets the selection text to be none.
References _edje_entry_select_none(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_selection_get()
EAPI const char* edje_object_part_text_selection_get (const Evas_Object * obj, const char * part)
Return the selection text of the object part.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The text string
This function returns selection text of the object part.
See also
edje_object_part_text_select_all()
edje_object_part_text_select_none()
References _edje_entry_selection_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_set()
EAPI Eina_Bool edje_object_part_text_set (Evas_Object * obj, const char * part, const char * text)
Sets the text for an object part.
Parameters
obj A valid Evas Object handle
part The part name
text The text string
Returns
EINA_BOOL on success, EINA_FALSE otherwise
References _edje_fetch(), _edje_object_part_text_raw_set(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::part, and _Edje_Part::type.
Referenced by _edje_external_param_set().
edje_object_part_text_style_user_peek()
EAPI const char* edje_object_part_text_style_user_peek (const Evas_Object * obj, const char * part)
Return the text of the object part.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The text string
This function returns the style associated with the textblock part.
Since
1.2.0
References _edje_fetch(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_text_style_user_pop()
EAPI void edje_object_part_text_style_user_pop (Evas_Object * obj, const char * part)
Delete the top style form the user style stack.
Parameters
obj A valid Evas_Object handle
part The part name
Since
1.2.0
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc(), EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::recalc_hints, and _Edje_Part::type.
edje_object_part_text_style_user_push()
EAPI void edje_object_part_text_style_user_push (Evas_Object * obj, const char * part, const char * style)
Set the style of the.
Parameters
obj A valid Evas_Object handle
part The part name
style The style to set (textblock conventions).
This function sets the style associated with the textblock part.
Since
1.2.0
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc(), EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::recalc_hints, and _Edje_Part::type.
edje_object_part_text_unescaped_get()
EAPI char* edje_object_part_text_unescaped_get (const Evas_Object * obj, const char * part)
Returns the text of the object part, without escaping.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The allocated text string without escaping, or NULL on problems.
This function is the counterpart of edje_object_part_text_unescaped_set(). Please notice that the result is newly allocated memory and should be released with free() when done.
See also
edje_object_part_text_unescaped_set().
References _edje_entry_text_get(), _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _edje_text_unescape(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part::entry_mode, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje_Real_Part::text, and _Edje_Part::type.
edje_object_part_text_unescaped_set()
EAPI Eina_Bool edje_object_part_text_unescaped_set (Evas_Object * obj, const char * part, const char * text_to_escape)
Sets the raw (non escaped) text for an object part.
Parameters
obj A valid Evas Object handle
part The part name
text_to_escape The text string
This funciton will not do escape for you if it is a TEXTBLOCK part, that is, if text contain tags, these tags will not be interpreted/parsed by TEXTBLOCK.
See also
edje_object_part_text_unescaped_get().
References _edje_fetch(), _edje_object_part_text_raw_set(), _edje_real_part_recursive_get(), _edje_text_escape(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_text_user_insert()
EAPI void edje_object_part_text_user_insert (const Evas_Object * obj, const char * part, const char * text)
Deletes the selection and emits a change event.
Parameters
obj A valid Evas_Object handle
part The part name
text The text string
Since
1.2.0
References _edje_entry_user_insert(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_unswallow()
EAPI void edje_object_part_unswallow (Evas_Object * obj, Evas_Object * obj_swallow)
Unswallow an object.
Parameters
obj A valid Evas_Object handle
obj_swallow The swallowed object
Causes the edje to regurgitate a previously swallowed object. :)
Note
obj_swallow will not be deleted or hidden.
obj_swallow may appear shown on the evas depending on its state when it got unswallowed. Make sure you delete it or hide it if you do not want it to.
References _edje_fetch(), _edje_real_part_swallow_clear(), _edje_recalc_do(), _edje_user_definition_free(), _Edje::dirty, _Edje_Real_Part::edje, EDJE_PART_TYPE_SWALLOW, EDJE_USER_SWALLOW, ERR, _Edje_Size::h, _Edje_Real_Part::max, _Edje_Real_Part::min, _Edje_Part::name, _Edje_Real_Part::part, _Edje::recalc_call, _Edje_User_Defined::swallow, _Edje_Real_Part::swallow_params, _Edje_Real_Part::swallowed_object, _Edje_Part::type, _Edje_User_Defined::type, _Edje_User_Defined::u, _Edje::user_defined, and _Edje_Size::w.
Referenced by _edje_real_part_swallow(), and edje_object_part_swallow().
edje_object_parts_extends_calc()
EAPI Eina_Bool edje_object_parts_extends_calc (Evas_Object * obj, Evas_Coord * x, Evas_Coord * y, Evas_Coord * w, Evas_Coord * h)
Calculate the geometry of the region, relative to a given Edje object's area, occupied by all parts in the object
Parameters
obj A handle to an Edje object
x A pointer to a variable where to store the parts region's x coordinate
y A pointer to a variable where to store the parts region's y coordinate
w A pointer to a variable where to store the parts region's width
h A pointer to a variable where to store the parts region's height
This function gets the geometry of the rectangle equal to the area required to group all parts in obj's group/collection. The x and y coordinates are relative to the top left corner of the whole obj object's area. Parts placed out of the group's boundaries will also be taken in account, so that x and y may be negative.
Note
Use NULL pointers on the geometry components you're not interested in: they'll be ignored by the function.
On failure, this function will make all non-NULL geometry pointers' pointed variables be set to zero.
References _edje_fetch(), _edje_recalc_do(), _Edje::calc_only, _Edje::dirty, _Edje_Real_Part::h, _Edje::table_parts, _Edje::table_parts_size, _Edje_Real_Part::w, _Edje_Real_Part::x, and _Edje_Real_Part::y.
edje_object_perspective_get()
EAPI const Edje_Perspective* edje_object_perspective_get (const Evas_Object * obj)
Get the current perspective used on this Edje object.
Parameters
obj the given Edje object.
Returns
The perspective object being used on this Edje object. Or NULL if there was none, and on errors.
See also
edje_object_perspective_set()
References _Edje::persp.
edje_object_perspective_set()
EAPI void edje_object_perspective_set (Evas_Object * obj, Edje_Perspective * ps)
Set the given perspective object on this Edje object.
Parameters
obj The Edje object on the perspective will be set.
ps The perspective object that will be used.
Make the given perspective object be the default perspective for this Edje object.
There can be only one perspective object per Edje object, and if a previous one was set, it will be removed and the new perspective object will be used.
An Edje perspective will only affect a part if it doesn't point to another part to be used as perspective.
See also
edje_object_perspective_new()
edje_object_perspective_get()
edje_perspective_set()
References _edje_recalc_do(), _Edje::dirty, _Edje::persp, _Edje::recalc_call, and _Edje_Perspective::users.
edje_object_preload()
EAPI Eina_Bool edje_object_preload (Evas_Object * obj, Eina_Bool cancel)
Preload the images on the Edje Object in the background.
Parameters
obj A handle to an Edje object
cancel EINA_FALSE will add it the preloading work queue, EINA_TRUE will remove it (if it was issued before).
Returns
EINA_FASLE if obj was not a valid Edje object otherwise EINA_TRUE
This function requests the preload of all data images (on the given object) in the background. The work is queued before being processed (because there might be other pending requests of this type). It emits a signal "preload,done" when finished.
Note
Use EINA_TRUE on scenarios where you don't need the image data preloaded anymore.
References _edje_fetch(), _edje_recalc_do(), EDJE_PART_TYPE_GROUP, EDJE_PART_TYPE_IMAGE, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::preload_count, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
edje_object_scale_get()
EAPI double edje_object_scale_get (const Evas_Object * obj)
Get a given Edje object's scaling factor.
Parameters
obj A handle to an Edje object
This function returns the individual scaling factor set on the obj Edje object.
See also
edje_object_scale_set() for more details
References _edje_fetch(), _Edje::scale, and TO_DOUBLE.
edje_object_scale_set()
EAPI Eina_Bool edje_object_scale_set (Evas_Object * obj, double scale)
Set the scaling factor for a given Edje object.
Parameters
obj A handle to an Edje object
scale The scaling factor (the default value is 0.0, meaning individual scaling not set)
This function sets an individual scaling factor on the obj Edje object. This property (or Edje's global scaling factor, when applicable), will affect this object's part sizes. If scale is not zero, than the individual scaling will override any global scaling set, for the object obj's parts. Put it back to zero to get the effects of the global scaling again.
Warning
Only parts which, at EDC level, had the "scale" property set to 1, will be affected by this function. Check the complete syntax reference for EDC files.
See also
edje_object_scale_get()
edje_scale_get() for more details
References _edje_fetch(), edje_object_calc_force(), edje_object_scale_set(), EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, FROM_DOUBLE, _Edje::groups, _Edje_Real_Part::items, _Edje::obj, _Edje_Real_Part::part, _Edje::scale, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by _edje_part_recalc(), and edje_object_scale_set().
edje_object_size_max_get()
EAPI void edje_object_size_max_get (const Evas_Object * obj, Evas_Coord * maxw, Evas_Coord * maxh)
Get the maximum size specified – as an EDC property – for a given Edje object.
Parameters
obj A handle to an Edje object
maxw Pointer to a variable where to store the maximum width
maxh Pointer to a variable where to store the maximum height
This function retrieves the obj object's maximum size values, as declared in its EDC group definition. Maximum size of groups have the following syntax
collections {
  group {
    name: "a_group";
    max: 100 100;
  }
}
where one declares a maximum size of 100 pixels both for width and height. Those are (hint) values which should be respected when the given object/group is to be controlled by a given container object (e.g. an Edje object being "swallowed" into a given SWALLOW typed part, as in edje_object_part_swallow()). Check the complete syntax reference for EDC files.
Note
If the max EDC property was not declared for obj, this call will return the maximum size a given Edje object may have, for each axis.
On failure, this function will make all non-NULL size pointers' pointed variables be set to zero.
See also
edje_object_size_min_get()
References _edje_fetch(), _edje_recalc_do(), _Edje::collection, EDJE_INF_MAX_H, EDJE_INF_MAX_W, _Edje_Size::h, _Edje_Part_Collection::max, _Edje_Part_Collection::prop, and _Edje_Size::w.
edje_object_size_min_calc()
EAPI void edje_object_size_min_calc (Evas_Object * obj, Evas_Coord * minw, Evas_Coord * minh)
Calculate the minimum required size for a given Edje object.
Parameters
obj A handle to an Edje object
minw Pointer to a variable where to store the minimum required width
minh Pointer to a variable where to store the minimum required height
This call works exactly as edje_object_size_min_restricted_calc(), with the last two arguments set to 0. Please refer to its documentation, then.
References edje_object_size_min_restricted_calc().
Referenced by _edje_recalc_do().
edje_object_size_min_get()
EAPI void edje_object_size_min_get (const Evas_Object * obj, Evas_Coord * minw, Evas_Coord * minh)
Get the minimum size specified – as an EDC property – for a given Edje object.
Parameters
obj A handle to an Edje object
minw Pointer to a variable where to store the minimum width
minh Pointer to a variable where to store the minimum height
This function retrieves the obj object's minimum size values, as declared in its EDC group definition. Minimum size of groups have the following syntax
collections {
  group {
    name: "a_group";
    min: 100 100;
  }
}
where one declares a minimum size of 100 pixels both for width and height. Those are (hint) values which should be respected when the given object/group is to be controlled by a given container object (e.g. an Edje object being "swallowed" into a given SWALLOW typed part, as in edje_object_part_swallow()). Check the complete syntax reference for EDC files.
Note
If the min EDC property was not declared for obj, this call will return the value 0, for each axis.
On failure, this function will make all non-NULL size pointers' pointed variables be set to zero.
See also
edje_object_size_max_get()
References _edje_fetch(), _Edje::collection, _Edje_Size::h, _Edje_Part_Collection::min, _Edje_Part_Collection::prop, and _Edje_Size::w.
edje_object_size_min_restricted_calc()
EAPI void edje_object_size_min_restricted_calc (Evas_Object * obj, Evas_Coord * minw, Evas_Coord * minh, Evas_Coord restrictedw, Evas_Coord restrictedh)
Calculate the minimum required size for a given Edje object.
Parameters
obj A handle to an Edje object
minw Pointer to a variable where to store the minimum required width
minh Pointer to a variable where to store the minimum required height
restrictedw Do not allow object's calculated (minimum) width to be less than this value
restrictedh Do not allow object's calculated (minimum) height to be less than this value
This call will trigger an internal recalculation of all parts of the obj object, in order to return its minimum required dimensions for width and height. The user might choose to impose those minimum sizes, making the resulting calculation to get to values equal or bigger than restrictedw and restrictedh, for width and height, respectively.
Note
At the end of this call, obj won't be automatically resized to new dimensions, but just return the calculated sizes. The caller is the one up to change its geometry or not.
Warning
Be advised that invisible parts in obj will be taken into account in this calculation.
References _edje_fetch(), _edje_recalc(), _edje_recalc_do(), _Edje::calc_only, _Edje_Real_Part::chosen_description, _Edje::collection, _Edje::dirty, EDJE_PART_TYPE_TEXTBLOCK, ERR, _Edje_Part_Description_Common::fixed, _Edje::group, _Edje_Size::h, _Edje_Rectangle::h, _Edje_Part_Description_Common::h, _Edje::h, _Edje_Real_Part::h, _Edje::min, _Edje_Part::name, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::path, _Edje_Real_Part::req, _Edje::table_parts, _Edje::table_parts_size, _Edje_Part::type, _Edje_Size::w, _Edje_Rectangle::w, _Edje_Part_Description_Common::w, _Edje::w, and _Edje_Real_Part::w.
Referenced by _edje_entry_cursor_geometry_get(), and edje_object_size_min_calc().
edje_object_text_change_cb_set()
EAPI void edje_object_text_change_cb_set (Evas_Object * obj, Edje_Text_Change_Cb func, void * data)
Set the object text callback.
Parameters
obj A valid Evas_Object handle
func The callback function to handle the text change
data The data associated to the callback function.
This function sets the callback to be called when the text changes.
References _edje_fetch(), _Edje::data, edje_object_text_change_cb_set(), EDJE_PART_TYPE_GROUP, _Edje::func, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, _Edje::text_change, and _Edje_Part::type.
Referenced by edje_object_text_change_cb_set().
edje_object_text_class_set()
EAPI Eina_Bool edje_object_text_class_set (Evas_Object * obj, const char * text_class, const char * font, Evas_Font_Size size)
Sets Edje text class.
Parameters
obj A valid Evas_Object handle
text_class The text class name
font Font name
size Font Size
Returns
EINA_TRUE, on success or EINA_FALSE, on error
This function sets the text class for the Edje.
References _edje_fetch(), _edje_recalc(), _edje_textblock_style_all_update(), _Edje::dirty, edje_object_text_class_set(), EDJE_PART_TYPE_GROUP, _Edje_Text_Class::font, _Edje_Text_Class::name, _Edje_Real_Part::part, _Edje::recalc_call, _Edje_Text_Class::size, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, _Edje::text_classes, and _Edje_Part::type.
Referenced by edje_object_text_class_set().
edje_object_text_insert_filter_callback_add()
EAPI void edje_object_text_insert_filter_callback_add (Evas_Object * obj, const char * part, Edje_Text_Filter_Cb func, void * data)
Add a filter function for newly inserted text.
Whenever text is inserted (not the same as set) into the given part, the list of filter functions will be called to decide if and how the new text will be accepted. There are three types of filters, EDJE_TEXT_FILTER_TEXT, EDJE_TEXT_FILTER_FORMAT and EDJE_TEXT_FILTER_MARKUP. The text parameter in the func filter can be modified by the user and it's up to him to free the one passed if he's to change the pointer. If doing so, the newly set text should be malloc'ed, as once all the filters are called Edje will free it. If the text is to be rejected, freeing it and setting the pointer to NULL will make Edje break out of the filter cycle and reject the inserted text.
Warning
This function will be deprecated because of difficulty in use. The type(format, text, or markup) of text should be always checked in the filter function for correct filtering. Please use edje_object_text_markup_filter_callback_add() instead. There is no need to check the type of text in the filter function because the text is always markup.
If you use this function with edje_object_text_markup_filter_callback_add() together, all Edje_Text_Filter_Cb functions and Edje_Markup_Filter_Cb functions will be executed, and then filtered text will be inserted.
See also
edje_object_text_insert_filter_callback_del
edje_object_text_insert_filter_callback_del_full
edje_object_text_markup_filter_callback_add
Parameters
obj A valid Evas_Object handle
part The part name
func The callback function that will act as filter
data User provided data to pass to the filter function
References _edje_fetch(), _Edje_Text_Insert_Filter_Callback::data, _Edje_Text_Insert_Filter_Callback::func, _Edje_Text_Insert_Filter_Callback::part, and _Edje::text_insert_filter_callbacks.
edje_object_text_insert_filter_callback_del()
EAPI void* edje_object_text_insert_filter_callback_del (Evas_Object * obj, const char * part, Edje_Text_Filter_Cb func)
Delete a function from the filter list.
Delete the given func filter from the list in part. Returns the user data pointer given when added.
See also
edje_object_text_insert_filter_callback_add
edje_object_text_insert_filter_callback_del_full
Parameters
obj A valid Evas_Object handle
part The part name
func The function callback to remove
Returns
The user data pointer if successful, or NULL otherwise
References _edje_fetch(), _Edje_Text_Insert_Filter_Callback::data, _Edje_Text_Insert_Filter_Callback::func, _Edje_Text_Insert_Filter_Callback::part, and _Edje::text_insert_filter_callbacks.
edje_object_text_insert_filter_callback_del_full()
EAPI void* edje_object_text_insert_filter_callback_del_full (Evas_Object * obj, const char * part, Edje_Text_Filter_Cb func, void * data)
Delete a function and matching user data from the filter list.
Delete the given func filter and data user data from the list in part. Returns the user data pointer given when added.
See also
edje_object_text_insert_filter_callback_add
edje_object_text_insert_filter_callback_del
Parameters
obj A valid Evas_Object handle
part The part name
func The function callback to remove
data The data passed to the callback function
Returns
The same data pointer if successful, or NULL otherwise
References _edje_fetch(), _Edje_Text_Insert_Filter_Callback::data, _Edje_Text_Insert_Filter_Callback::func, _Edje_Text_Insert_Filter_Callback::part, and _Edje::text_insert_filter_callbacks.
edje_object_text_markup_filter_callback_add()
EAPI void edje_object_text_markup_filter_callback_add (Evas_Object * obj, const char * part, Edje_Markup_Filter_Cb func, void * data)
Add a markup filter function for newly inserted text.
Whenever text is inserted (not the same as set) into the given part, the list of markup filter functions will be called to decide if and how the new text will be accepted. The text parameter in the func filter is always markup. It can be modified by the user and it's up to him to free the one passed if he's to change the pointer. If doing so, the newly set text should be malloc'ed, as once all the filters are called Edje will free it. If the text is to be rejected, freeing it and setting the pointer to NULL will make Edje break out of the filter cycle and reject the inserted text. This function is different from edje_object_text_insert_filter_callback_add() in that the text parameter in the fucn filter is always markup.
Warning
If you use this function with edje_object_text_insert_filter_callback_add() togehter, all Edje_Text_Filter_Cb functions and Edje_Markup_Filter_Cb functions will be executed, and then filtered text will be inserted.
See also
edje_object_text_markup_filter_callback_del
edje_object_text_markup_filter_callback_del_full
edje_object_text_insert_filter_callback_add
Parameters
obj A valid Evas_Object handle
part The part name
func The callback function that will act as markup filter
data User provided data to pass to the filter function
Since
1.2.0
References _edje_fetch(), _Edje_Markup_Filter_Callback::data, _Edje_Markup_Filter_Callback::func, _Edje::markup_filter_callbacks, and _Edje_Markup_Filter_Callback::part.
edje_object_text_markup_filter_callback_del()
EAPI void* edje_object_text_markup_filter_callback_del (Evas_Object * obj, const char * part, Edje_Markup_Filter_Cb func)
Delete a function from the markup filter list.
Delete the given func filter from the list in part. Returns the user data pointer given when added.
See also
edje_object_text_markup_filter_callback_add
edje_object_text_markup_filter_callback_del_full
Parameters
obj A valid Evas_Object handle
part The part name
func The function callback to remove
Returns
The user data pointer if successful, or NULL otherwise
Since
1.2.0
References _edje_fetch(), _Edje_Markup_Filter_Callback::data, _Edje_Markup_Filter_Callback::func, _Edje::markup_filter_callbacks, and _Edje_Markup_Filter_Callback::part.
edje_object_text_markup_filter_callback_del_full()
EAPI void* edje_object_text_markup_filter_callback_del_full (Evas_Object * obj, const char * part, Edje_Markup_Filter_Cb func, void * data)
Delete a function and matching user data from the markup filter list.
Delete the given func filter and data user data from the list in part. Returns the user data pointer given when added.
See also
edje_object_text_markup_filter_callback_add
edje_object_text_markup_filter_callback_del
Parameters
obj A valid Evas_Object handle
part The part name
func The function callback to remove
data The data passed to the callback function
Returns
The same data pointer if successful, or NULL otherwise
Since
1.2.0
References _edje_fetch(), _Edje_Markup_Filter_Callback::data, _Edje_Markup_Filter_Callback::func, _Edje::markup_filter_callbacks, and _Edje_Markup_Filter_Callback::part.
edje_object_thaw()
EAPI int edje_object_thaw (Evas_Object * obj)
Thaws the Edje object.
Parameters
obj A handle to an Edje object.
Returns
The frozen state or 0 if the object is not frozen or on error.
This function thaws the given Edje object.
Note
: If sucessives freezes were done, an equal number of thaws will be required.
See also
edje_object_freeze()
References _edje_fetch(), _edje_thaw(), edje_object_thaw(), EDJE_PART_TYPE_GROUP, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_object_thaw().
edje_object_update_hints_get()
EAPI Eina_Bool edje_object_update_hints_get (Evas_Object * obj)
Wether or not Edje will update size hints on itself.
Parameters
obj A handle to an Edje object.
Returns
true if does, false if it doesn't.
References _edje_fetch(), and _Edje::update_hints.
Referenced by _edje_part_recalc().
edje_object_update_hints_set()
EAPI void edje_object_update_hints_set (Evas_Object * obj, Eina_Bool update)
Edje will automatically update the size hints on itself.
Parameters
obj A handle to an Edje object.
update Wether or not update the size hints.
By default edje doesn't set size hints on itself. With this function call, it will do so if update is true. Be carefully, it cost a lot to trigger this feature as it will recalc the object every time it make sense to be sure that's its minimal size hint is always accurate.
References _edje_fetch(), _edje_recalc(), _Edje::recalc_hints, and _Edje::update_hints.
Referenced by _edje_part_recalc().
edje_password_show_last_set()
EAPI void edje_password_show_last_set (Eina_Bool password_show_last)
Show last character in password mode.
Parameters
password_show_last If TRUE enable last character show in password mode.
This function enables last input to be visible when in password mode for few seconds or until the next input is entered.
The time out value is obtained by edje_password_show_last_timeout_set function.
See also
edje_password_show_last_timeout_set().
References _edje_password_show_last.
edje_password_show_last_timeout_set()
EAPI void edje_password_show_last_timeout_set (double password_show_last_timeout)
Set's the timeout value in last show password mode.
Parameters
password_show_last_timeout The timeout value.
This functions sets the time out value for which the last input entered in password mode will be visible.
This value can be used only when last show mode is set in password mode.
See also
edje_password_show_last_set().
References _edje_password_show_last_timeout, and FROM_DOUBLE.
edje_perspective_free()
EAPI void edje_perspective_free (Edje_Perspective * ps)
Delete the given perspective object.
Parameters
ps A valid perspective object, or NULL.
This function will delete the perspective object. If the perspective effect was being applied to any Edje object or part, this effect won't be applied anymore.
See also
edje_perspective_new()
References _Edje_Perspective::obj.
edje_perspective_global_get()
EAPI Eina_Bool edje_perspective_global_get (const Edje_Perspective * ps)
Get whether the given perspective object is global or not.
Parameters
ps The given perspective object.
Returns
EINA_TRUE if this perspective object is global, EINA_FALSE otherwise.
See also
edje_perspective_global_set()
References _Edje_Perspective::global.
edje_perspective_global_set()
EAPI void edje_perspective_global_set (Edje_Perspective * ps, Eina_Bool global)
Make this perspective object be global for its canvas.
Parameters
ps The given perspective object
global EINA_TRUE if the perspective should be global, EINA_FALSE otherwise.
The canvas which this perspective object is being set as global is the one given as argument upon the object creation (the evas parameter on the function edje_perspective_new(evas)).
There can be only one global perspective object set per canvas, and if a perspective object is set to global when there was already another global perspective set, the old one will be set as non-global.
A global perspective just affects a part if its Edje object doesn't have a perspective object set to it, and if the part doesn't point to another part to be used as perspective.
See also
edje_object_perspective_set()
edje_perspective_global_get()
edje_perspective_new()
References _edje_edjes, _edje_recalc_do(), _Edje::dirty, _Edje_Perspective::global, _Edje_Perspective::obj, _Edje::persp, and _Edje::recalc_call.
edje_perspective_new()
EAPI Edje_Perspective* edje_perspective_new (Evas * e)
Creates a new perspective in the given canvas.
Parameters
e The given canvas (Evas).
Returns
An Edje_Perspective object for this canvas, or NULL on errors.
This function creates a perspective object that can be set on an Edje object, or globally to all Edje objects on this canvas.
See also
edje_perspective_set()
edje_perspective_free()
References _Edje_Perspective::obj.
edje_perspective_set()
EAPI void edje_perspective_set (Edje_Perspective * ps, Evas_Coord px, Evas_Coord py, Evas_Coord z0, Evas_Coord foc)
Setup the transform for this perspective object.
This sets the parameters of the perspective transformation. X, Y and Z values are used. The px and py points specify the "infinite distance" point in the 3D conversion (where all lines converge to like when artists draw 3D by hand). The z0 value specifies the z value at which there is a 1:1 mapping between spatial coordinates and screen coordinates. Any points on this z value will not have their X and Y values modified in the transform. Those further away (Z value higher) will shrink into the distance, and those less than this value will expand and become bigger. The foc value determines the "focal length" of the camera. This is in reality the distance between the camera lens plane itself (at or closer than this rendering results are undefined) and the "z0" z value. This allows for some "depth" control and foc must be greater than 0.
Parameters
ps The perspective object
px The perspective distance X coordinate
py The perspective distance Y coordinate
z0 The "0" z plane value
foc The focal distance
References _edje_edjes, _edje_recalc_do(), _Edje::dirty, _Edje_Perspective::foc, _Edje_Perspective::global, _Edje::persp, _Edje_Perspective::px, _Edje_Perspective::py, _Edje::recalc_call, _Edje_Perspective::users, and _Edje_Perspective::z0.
edje_scale_get()
EAPI double edje_scale_get (void)
Retrieve Edje's global scaling factor.
Returns
The global scaling factor
This function returns Edje's global scaling factor.
See also
edje_scale_set() for more details
References _edje_scale, and TO_DOUBLE.
edje_scale_set()
EAPI void edje_scale_set (double scale)
Set Edje's global scaling factor.
Parameters
scale The global scaling factor (the default value is 1.0)
Edje allows one to build scalable interfaces. Scaling factors, which are set to neutral (1.0) values by default (no scaling, actual sizes), are of two types: global and individual. Edje's global scaling factor will affect all its objects which hadn't their individual scaling factors altered from the default value (which is zero). If they had it set differently, by edje_object_scale_set(), that factor will override the global one.
Scaling affects the values of minimum/maximum part sizes, which are multiplied by it. Font sizes are scaled, too.
Warning
Only parts which, at EDC level, had the "scale" property set to 1, will be affected by this function. Check the complete syntax reference for EDC files.
See also
edje_scale_get().
References _edje_edjes, _edje_scale, edje_object_calc_force(), and FROM_DOUBLE.
edje_string_get()
const char* edje_string_get (const Edje_String * es)
References _Edje_String::str.
Referenced by _edje_text_class_font_get(), _edje_text_recalc_apply(), edje_edit_data_value_get(), edje_edit_group_data_value_get(), edje_edit_state_font_get(), edje_edit_state_text_get(), edje_file_data_get(), and edje_object_data_get().
edje_string_id_get()
const char* edje_string_id_get (const Edje_String * es)
References _Edje_String::str.
edje_text_class_del()
void edje_text_class_del (const char * text_class)
Delete the text class.
Parameters
text_class The text class name string
This function deletes any values at the process level for the specified text class.
edje_text_class_list()
Eina_List* edje_text_class_list (void)
List text classes.
Returns
A list of text class names (strings). These strings are stringshares and the list must be free()'d by the caller.
This function lists all text classes known about by the current process.
edje_text_class_set()
EAPI Eina_Bool edje_text_class_set (const char * text_class, const char * font, Evas_Font_Size size)
Set the Edje text class.
Parameters
text_class The text class name
font The font name
size The font size
Returns
EINA_TRUE, on success or EINA_FALSE, on error
This function updates all Edje members at the process level which belong to this text class with the new font attributes. If the size is 0 then the font size will be kept with the previous size. If the size is less then 0 then the font size will be calculated in the percentage. For example, if the size is -50, then the font size will be scaled to half of the original size and if the size is -10 then the font size will be scaled as much as 0.1x.
See also
edje_text_class_get().
edje_thaw()
EAPI void edje_thaw (void)
Thaw Edje objects.
This function thaws all Edje animations in the current process.
Note
for thaw a specific object
See also
edje_object_thaw().
edje_freeze()
References _edje_freeze_calc_count, _edje_freeze_calc_list, and _edje_freeze_val.
Variable Documentation
_edje_fontset_append
char* _edje_fontset_append = NULL
Referenced by _edje_text_recalc_apply(), _edje_textblock_style_all_update(), _edje_textblock_style_parse_and_fix(), edje_fontset_append_get(), and edje_fontset_append_set().
_edje_freeze_calc_count
int _edje_freeze_calc_count = 0
Referenced by _edje_file_del(), _edje_recalc(), and edje_thaw().
_edje_freeze_calc_list
Eina_List* _edje_freeze_calc_list = NULL
Referenced by _edje_file_del(), _edje_recalc(), and edje_thaw().
_edje_freeze_val
int _edje_freeze_val = 0
Referenced by _edje_recalc(), edje_freeze(), edje_object_calc_force(), and edje_thaw().
_edje_password_show_last
Eina_Bool _edje_password_show_last = EINA_FALSE
Referenced by edje_password_show_last_set().
_edje_password_show_last_timeout
FLOAT_T _edje_password_show_last_timeout = ZERO
Referenced by edje_password_show_last_timeout_set().
_edje_scale
FLOAT_T _edje_scale = ZERO
Referenced by _edje_text_recalc_apply(), edje_scale_get(), and edje_scale_set().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59