src/lib/edje_box_layout.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_box_layout.c File Reference
Data Structures
struct _Edje_Part_Box_Animation
struct _Edje_Transition_Animation_Data
Typedefs
typedef struct _Edje_Transition_Animation_Data Edje_Transition_Animation_Data
Functions
Eina_Bool _edje_box_layout_add_child (Edje_Real_Part *rp, Evas_Object *child_obj)
Edje_Part_Box_Animation * _edje_box_layout_anim_new (Evas_Object *box)
void _edje_box_layout_free_data (void *data)
void _edje_box_layout_remove_child (Edje_Real_Part *rp, Evas_Object *child_obj)
void _edje_box_recalc_apply (Edje *ed __UNUSED__, Edje_Real_Part *ep, Edje_Calc_Params *p3 __UNUSED__, Edje_Part_Description_Box *chosen_desc)
Typedef Documentation
Edje_Transition_Animation_Data
typedef struct _Edje_Transition_Animation_Data Edje_Transition_Animation_Data
Function Documentation
_edje_box_layout_add_child()
Eina_Bool _edje_box_layout_add_child (Edje_Real_Part * rp, Evas_Object * child_obj)
References _Edje_Real_Part::anim, _Edje_Transition_Animation_Data::obj, _Edje_Part_Box_Animation::objs, and _Edje_Part_Box_Animation::recalculate.
Referenced by _edje_real_part_box_append(), _edje_real_part_box_insert_at(), _edje_real_part_box_insert_before(), and _edje_real_part_box_prepend().
_edje_box_layout_anim_new()
Edje_Part_Box_Animation* _edje_box_layout_anim_new (Evas_Object * box)
References _Edje_Part_Box_Animation::box.
_edje_box_layout_free_data()
void _edje_box_layout_free_data (void * data)
References _Edje_Part_Box_Animation::data, _Edje_Part_Box_Animation::end, _Edje_Part_Box_Animation::free_data, _Edje_Part_Box_Animation::objs, and _Edje_Part_Box_Animation::start.
Referenced by _edje_file_del().
_edje_box_layout_remove_child()
void _edje_box_layout_remove_child (Edje_Real_Part * rp, Evas_Object * child_obj)
References _Edje_Real_Part::anim, _Edje_Transition_Animation_Data::obj, _Edje_Part_Box_Animation::objs, and _Edje_Part_Box_Animation::recalculate.
Referenced by _edje_real_part_box_remove(), _edje_real_part_box_remove_all(), and _edje_real_part_box_remove_at().
_edje_box_recalc_apply()
void _edje_box_recalc_apply (Edje *ed __UNUSED__, Edje_Real_Part * ep, Edje_Calc_Params *p3 __UNUSED__, Edje_Part_Description_Box * chosen_desc)
References _Edje_Real_Part::anim, _Edje_Real_Part_State::description, _Edje_Real_Part::description_pos, _Edje_Part_Box_Animation::end, _Edje_Part_Box_Animation::layout, _Edje_Real_Part::param2, and ZERO.
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59