src/lib/edje_lua_script_only.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_lua_script_only.c File Reference
Functions
Eina_Bool _edje_lua_script_only (Edje *ed)
void _edje_lua_script_only_hide (Edje *ed)
void _edje_lua_script_only_init (Edje *ed)
void _edje_lua_script_only_message (Edje *ed, Edje_Message *em)
void _edje_lua_script_only_move (Edje *ed)
void _edje_lua_script_only_resize (Edje *ed)
void _edje_lua_script_only_show (Edje *ed)
void _edje_lua_script_only_shutdown (Edje *ed)
Function Documentation
_edje_lua_script_only()
Eina_Bool _edje_lua_script_only (Edje * ed)
References _Edje::collection, and _Edje_Part_Collection::lua_script_only.
_edje_lua_script_only_hide()
void _edje_lua_script_only_hide (Edje * ed)
References _edje_lua2_script_func_hide(), _Edje::collection, and _Edje::L.
_edje_lua_script_only_init()
void _edje_lua_script_only_init (Edje * ed)
References _edje_lua2_script_init(), and _Edje::collection.
_edje_lua_script_only_message()
void _edje_lua_script_only_message (Edje * ed, Edje_Message * em)
References _edje_lua2_script_func_message(), _Edje::collection, and _Edje::L.
Referenced by _edje_message_process().
_edje_lua_script_only_move()
void _edje_lua_script_only_move (Edje * ed)
References _edje_lua2_script_func_move(), _Edje::collection, and _Edje::L.
_edje_lua_script_only_resize()
void _edje_lua_script_only_resize (Edje * ed)
References _edje_lua2_script_func_resize(), _Edje::collection, and _Edje::L.
_edje_lua_script_only_show()
void _edje_lua_script_only_show (Edje * ed)
References _edje_lua2_script_func_show(), _Edje::collection, and _Edje::L.
_edje_lua_script_only_shutdown()
void _edje_lua_script_only_shutdown (Edje * ed)
References _edje_lua2_script_func_shutdown(), _Edje::collection, and _Edje::L.
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59