src/lib/edje_match.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_match.c File Reference
Data Structures
struct _Edje_State
struct _Edje_States
Macros
#define ALIGN(Size)
#define EDJE_MATCH_INIT_ARRAY(Func, Type, Source, Show)
#define EDJE_MATCH_INIT_LIST(Func, Type, Source, Show)
Typedefs
typedef struct _Edje_State Edje_State
Enumerations
enum status { patterns_not_found = 0 , patterns_found = 1 , patterns_syntax_error = 2 }
Functions
void _edje_signals_sources_patterns_clean (Edje_Signals_Sources_Patterns *ssp)
int edje_match_callback_exec (Edje_Patterns *ppat_signal, Edje_Patterns *ppat_source, const char *sig, const char *source, Eina_List *callbacks, Edje *ed, Eina_Bool prop)
Eina_List * edje_match_callback_hash_build (const Eina_List *callbacks, Eina_Rbtree **tree)
Eina_Bool edje_match_collection_dir_exec (const Edje_Patterns *ppat, const char *string)
EDJE_MATCH_INIT_ARRAY (edje_match_programs_signal_init, Edje_Program, signal, 0)
EDJE_MATCH_INIT_ARRAY (edje_match_programs_source_init, Edje_Program, source, 0)
EDJE_MATCH_INIT_LIST (edje_match_callback_signal_init, Edje_Signal_Callback, signal, 0)
EDJE_MATCH_INIT_LIST (edje_match_callback_source_init, Edje_Signal_Callback, source, 0)
EDJE_MATCH_INIT_LIST (edje_match_collection_dir_init, Edje_Part_Collection_Directory_Entry, entry, 0)
void edje_match_patterns_free (Edje_Patterns *ppat)
Eina_List * edje_match_program_hash_build (Edje_Program *const *programs, unsigned int count, Eina_Rbtree **tree)
Eina_Bool edje_match_programs_exec (const Edje_Patterns *ppat_signal, const Edje_Patterns *ppat_source, const char *sig, const char *source, Edje_Program **programs, Eina_Bool(*func)(Edje_Program *pr, void *data), void *data, Eina_Bool prop)
void edje_match_signal_source_free (Edje_Signal_Source_Char *key, __UNUSED__ void *data)
const Eina_List * edje_match_signal_source_hash_get (const char *sig, const char *source, const Eina_Rbtree *tree)
Macro Definition Documentation
ALIGN
#define ALIGN (Size)
Value:
  {                               \
     Size--;                      \
     Size |= sizeof (void *) - 1; \
     Size++;                      \
  };
EDJE_MATCH_INIT_ARRAY
#define EDJE_MATCH_INIT_ARRAY (Func, Type, Source, Show)
EDJE_MATCH_INIT_LIST
#define EDJE_MATCH_INIT_LIST (Func, Type, Source, Show)
Typedef Documentation
Edje_State
typedef struct _Edje_State Edje_State
Enumeration Type Documentation
status
enum status
Enumerator
patterns_not_found
patterns_found
patterns_syntax_error
Function Documentation
_edje_signals_sources_patterns_clean()
void _edje_signals_sources_patterns_clean (Edje_Signals_Sources_Patterns * ssp)
References edje_match_patterns_free(), _Edje_Signals_Sources_Patterns::signals_patterns, and _Edje_Signals_Sources_Patterns::sources_patterns.
Referenced by _edje_callbacks_patterns_clean(), and _edje_programs_patterns_clean().
edje_match_callback_exec()
int edje_match_callback_exec (Edje_Patterns * ppat_signal, Edje_Patterns * ppat_source, const char * sig, const char * source, Eina_List * callbacks, Edje * ed, Eina_Bool prop)
References _Edje_Patterns::ref.
edje_match_callback_hash_build()
Eina_List* edje_match_callback_hash_build (const Eina_List * callbacks, Eina_Rbtree ** tree)
References _Edje_Signal_Callback::signal, and _Edje_Signal_Callback::source.
edje_match_collection_dir_exec()
Eina_Bool edje_match_collection_dir_exec (const Edje_Patterns * ppat, const char * string)
Referenced by edje_file_group_exists().
EDJE_MATCH_INIT_ARRAY() [1/2]
EDJE_MATCH_INIT_ARRAY (edje_match_programs_signal_init , Edje_Program , signal , 0)
EDJE_MATCH_INIT_ARRAY() [2/2]
EDJE_MATCH_INIT_ARRAY (edje_match_programs_source_init , Edje_Program , source , 0)
EDJE_MATCH_INIT_LIST() [1/3]
EDJE_MATCH_INIT_LIST (edje_match_callback_signal_init , Edje_Signal_Callback , signal , 0)
EDJE_MATCH_INIT_LIST() [2/3]
EDJE_MATCH_INIT_LIST (edje_match_callback_source_init , Edje_Signal_Callback , source , 0)
EDJE_MATCH_INIT_LIST() [3/3]
EDJE_MATCH_INIT_LIST (edje_match_collection_dir_init , Edje_Part_Collection_Directory_Entry , entry , 0)
edje_match_patterns_free()
void edje_match_patterns_free (Edje_Patterns * ppat)
References _Edje_Patterns::delete_me, and _Edje_Patterns::ref.
Referenced by _edje_file_free(), _edje_signals_sources_patterns_clean(), and edje_file_group_exists().
edje_match_program_hash_build()
Eina_List* edje_match_program_hash_build (Edje_Program *const * programs, unsigned int count, Eina_Rbtree ** tree)
Referenced by _edje_programs_patterns_init().
edje_match_programs_exec()
Eina_Bool edje_match_programs_exec (const Edje_Patterns * ppat_signal, const Edje_Patterns * ppat_source, const char * sig, const char * source, Edje_Program ** programs, Eina_Bool(*)(Edje_Program *pr, void *data) func, void * data, Eina_Bool prop)
Referenced by _edje_emit_handle().
edje_match_signal_source_free()
void edje_match_signal_source_free (Edje_Signal_Source_Char * key, __UNUSED__ void * data)
References _Edje_Signal_Source_Char::list.
Referenced by _edje_callbacks_patterns_clean(), and _edje_programs_patterns_clean().
edje_match_signal_source_hash_get()
const Eina_List* edje_match_signal_source_hash_get (const char * sig, const char * source, const Eina_Rbtree * tree)
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59