src/lib/edje_edit.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_edit.c File Reference
Data Structures
struct _Edje_Edit
struct _Program_Script
struct _SrcFile
struct _SrcFile_List
Macros
#define BUF_APPEND(STR) ret &= eina_strbuf_append(buf, STR)
#define BUF_APPENDF(FMT, ...) ret &= eina_strbuf_append_printf(buf, FMT, ##__VA_ARGS__)
#define EDIT_ALLOC_POOL(Short, Type, Name)
#define EDIT_EMN(Tp, Sz, Ce) Ce->mp.Tp = eina_mempool_add("chained_mempool", #Tp, NULL, sizeof (Sz), 8);
#define EDJE_EDIT_IS_UNSTABLE_AND_I_KNOW_ABOUT_IT
#define EDJE_EDIT_PROGRAM_ID_SET(Array, Ed, It, Old, New)
#define EDJE_EDIT_PROGRAM_SWITCH(Array, Ed, It, Id1, Id2)
#define FUNC_COLOR(Code)
#define FUNC_GROUP_ACCESSOR(Class, Value)
#define FUNC_PART_API_STRING(Value)
#define FUNC_PART_DRAG_ID(Id)
#define FUNC_PART_DRAG_INT(Class, Value)
#define FUNC_STATE_DOUBLE(Class, Value)
#define FUNC_STATE_DOUBLE_FILL(Class, Type, Value)
#define FUNC_STATE_INT(Class, Value)
#define FUNC_STATE_INT_FILL(Class, Type, Value)
#define FUNC_STATE_OFFSET_INT(Sub, Value)
#define FUNC_STATE_REL(Sub, Value)
#define FUNC_STATE_RELATIVE_DOUBLE(Sub, Value)
#define FUNC_TEXT_BOOL_FIT(Value)
#define FUNC_TEXT_DOUBLE(Name, Value)
#define GET_ED_OR_RETURN(RET)
#define GET_EED_OR_RETURN(RET)
#define GET_EPR_OR_RETURN(RET)
#define GET_PD_OR_RETURN(RET)
#define GET_RP_OR_RETURN(RET)
#define I0 ""
#define I1 " "
#define I2 " "
#define I3 " "
#define I4 " "
#define I5 " "
#define I6 " "
#define I7 " "
#define PD_STRING_COPY(To, From, _x)
Typedefs
typedef struct _Edje_Edit Edje_Edit
typedef struct _Program_Script Program_Script
typedef struct _SrcFile SrcFile
typedef struct _SrcFile_List SrcFile_List
Functions
Eina_Bool _edje_edit_internal_save (Evas_Object *obj, int current_only)
EAPI Eina_Bool edje_edit_color_class_add (Evas_Object *obj, const char *name)
Create a new color class object in the given edje.
EAPI Eina_Bool edje_edit_color_class_colors_get (Evas_Object *obj, const char *class_name, int *r, int *g, int *b, int *a, int *r2, int *g2, int *b2, int *a2, int *r3, int *g3, int *b3, int *a3)
Get all the colors that compose the class.
EAPI Eina_Bool edje_edit_color_class_colors_set (Evas_Object *obj, const char *class_name, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Set the colors for the given color class.
EAPI Eina_Bool edje_edit_color_class_del (Evas_Object *obj, const char *name)
Delete the given class object from edje.
EAPI Eina_Bool edje_edit_color_class_name_set (Evas_Object *obj, const char *name, const char *newname)
Change the name of a color class.
EAPI Eina_List * edje_edit_color_classes_list_get (Evas_Object *obj)
Get the list of all the Color Classes in the given edje object.
EAPI const char * edje_edit_compiler_get (Evas_Object *obj)
Get the name of the program that compiled the edje file.
EAPI Eina_Bool edje_edit_data_add (Evas_Object *obj, const char *itemname, const char *value)
Create a new global data object in the given edje file.
EAPI Eina_Bool edje_edit_data_del (Evas_Object *obj, const char *itemname)
Delete the given data object from edje.
EAPI Eina_List * edje_edit_data_list_get (Evas_Object *obj)
Retrieves a list with the item names inside the data block.
EAPI Eina_Bool edje_edit_data_name_set (Evas_Object *obj, const char *itemname, const char *newname)
Change the name of the given data object.
EAPI const char * edje_edit_data_value_get (Evas_Object *obj, const char *itemname)
Get the data associated with the given itemname.
EAPI Eina_Bool edje_edit_data_value_set (Evas_Object *obj, const char *itemname, const char *value)
Set the data associated with the given itemname.
EAPI Eina_Bool edje_edit_external_add (Evas_Object *obj, const char *external)
Add an external module to be requested on edje load.
EAPI Eina_Bool edje_edit_external_del (Evas_Object *obj, const char *external)
Delete the given external from the list.
EAPI Eina_List * edje_edit_externals_list_get (Evas_Object *obj)
Get the list of all the externals requested in the given edje object.
EAPI Eina_Bool edje_edit_font_add (Evas_Object *obj, const char *path, const char *alias)
Add a new font to the edje file.
EAPI Eina_Bool edje_edit_font_del (Evas_Object *obj, const char *alias)
Delete font from the edje file.
EAPI const char * edje_edit_font_path_get (Evas_Object *obj, const char *alias)
Get font path for a given font alias.
EAPI Eina_List * edje_edit_fonts_list_get (Evas_Object *obj)
Get the list of all the fonts in the given edje.
EAPI Eina_Bool edje_edit_group_add (Evas_Object *obj, const char *name)
Create a new empty group in the given edje.
EAPI Eina_Bool edje_edit_group_data_add (Evas_Object *obj, const char *key, const char *value)
Create a new data object in the given edje file belonging to the current group.
EAPI Eina_Bool edje_edit_group_data_del (Evas_Object *obj, const char *key)
Delete the given data object from the group.
EAPI Eina_List * edje_edit_group_data_list_get (Evas_Object *obj)
Retrieves a list with the item names inside the data block at the group level.
EAPI Eina_Bool edje_edit_group_data_name_set (Evas_Object *obj, const char *key, const char *new_key)
Change the name of the given data object.
EAPI const char * edje_edit_group_data_value_get (Evas_Object *obj, const char *key)
Get the data associated with the given itemname.
EAPI Eina_Bool edje_edit_group_data_value_set (Evas_Object *obj, const char *key, const char *value)
Set the data associated with the given itemname.
EAPI Eina_Bool edje_edit_group_del (Evas_Object *obj, const char *group_name)
Delete the specified group from the given edje.
EAPI Eina_Bool edje_edit_group_exist (Evas_Object *obj, const char *group)
Check if a group with the given name exist in the edje.
EAPI Eina_Bool edje_edit_group_name_set (Evas_Object *obj, const char *new_name)
Set a new name for the current open group.
EAPI Eina_Bool edje_edit_image_add (Evas_Object *obj, const char *path)
Add an new image to the image collection.
EAPI int edje_edit_image_compression_rate_get (Evas_Object *obj, const char *image)
Get compression rate for the given image.
EAPI Edje_Edit_Image_Comp edje_edit_image_compression_type_get (Evas_Object *obj, const char *image)
Get compression type for the given image.
EAPI Eina_Bool edje_edit_image_data_add (Evas_Object *obj, const char *name, int id)
Add an image entry to the image collection.
EAPI Eina_Bool edje_edit_image_del (Evas_Object *obj, const char *name)
Delete an image from the image collection.
EAPI int edje_edit_image_id_get (Evas_Object *obj, const char *image_name)
Get image id for a given image name.
EAPI Eina_List * edje_edit_images_list_get (Evas_Object *obj)
Get the list of all the images in the given edje.
EAPI Evas_Object * edje_edit_object_add (Evas *e)
Adds an editable Edje object to the canvas.
EAPI const char * edje_edit_part_above_get (Evas_Object *obj, const char *part)
Get the name of part stacked above the one passed.
EAPI Eina_Bool edje_edit_part_add (Evas_Object *obj, const char *name, Edje_Part_Type type)
Create a new part in the given edje.
EAPI const char * edje_edit_part_below_get (Evas_Object *obj, const char *part)
Get the name of part stacked below the one passed.
EAPI const char * edje_edit_part_clip_to_get (Evas_Object *obj, const char *part)
Get the clip_to part.
EAPI Eina_Bool edje_edit_part_clip_to_set (Evas_Object *obj, const char *part, const char *clip_to)
Set a part to clip part to.
EAPI Eina_Bool edje_edit_part_del (Evas_Object *obj, const char *part)
Delete the given part from the edje.
EAPI int edje_edit_part_drag_x_get (Evas_Object *obj, const char *part)
Get horizontal dragable state for part.
EAPI void edje_edit_part_drag_x_set (Evas_Object *obj, const char *part, int drag)
Set horizontal dragable state for part.
EAPI int edje_edit_part_drag_y_get (Evas_Object *obj, const char *part)
Get vertical dragable state for part.
EAPI void edje_edit_part_drag_y_set (Evas_Object *obj, const char *part, int drag)
Set vertical dragable state for part.
EAPI Edje_Text_Effect edje_edit_part_effect_get (Evas_Object *obj, const char *part)
Get the effect for a given part.
EAPI void edje_edit_part_effect_set (Evas_Object *obj, const char *part, Edje_Text_Effect effect)
Set the effect for a given part.
EAPI Eina_Bool edje_edit_part_exist (Evas_Object *obj, const char *part)
Check if a part with the given name exist in the edje object.
EAPI Eina_Bool edje_edit_part_external_add (Evas_Object *obj, const char *name, const char *source)
Create a new part of type EXTERNAL in the given edje.
EAPI Evas_Event_Flags edje_edit_part_ignore_flags_get (Evas_Object *obj, const char *part)
Get ignore_flags for part.
EAPI void edje_edit_part_ignore_flags_set (Evas_Object *obj, const char *part, Evas_Event_Flags ignore_flags)
Set ignore_flags for part.
EAPI Eina_Bool edje_edit_part_mouse_events_get (Evas_Object *obj, const char *part)
Get mouse_events for part.
EAPI void edje_edit_part_mouse_events_set (Evas_Object *obj, const char *part, Eina_Bool mouse_events)
Set mouse_events for part.
EAPI Eina_Bool edje_edit_part_name_set (Evas_Object *obj, const char *part, const char *new_name)
Set a new name for part.
EAPI Eina_Bool edje_edit_part_repeat_events_get (Evas_Object *obj, const char *part)
Get repeat_events for part.
EAPI void edje_edit_part_repeat_events_set (Evas_Object *obj, const char *part, Eina_Bool repeat_events)
Set repeat_events for part.
EAPI Eina_Bool edje_edit_part_restack_above (Evas_Object *obj, const char *part)
Move the given part above the next one.
EAPI Eina_Bool edje_edit_part_restack_below (Evas_Object *obj, const char *part)
Move the given part below the previous one.
EAPI Eina_Bool edje_edit_part_scale_get (Evas_Object *obj, const char *part)
Get scale for the part.
EAPI void edje_edit_part_scale_set (Evas_Object *obj, const char *part, Eina_Bool scale)
Set scale property for the part.
EAPI const char * edje_edit_part_selected_state_get (Evas_Object *obj, const char *part, double *value)
Get the current selected state in part.
EAPI Eina_Bool edje_edit_part_selected_state_set (Evas_Object *obj, const char *part, const char *state, double value)
Set the current state in part.
EAPI const char * edje_edit_part_source_get (Evas_Object *obj, const char *part)
Get the source of part.
EAPI Eina_Bool edje_edit_part_source_set (Evas_Object *obj, const char *part, const char *source)
Set the source of part.
EAPI Eina_List * edje_edit_part_states_list_get (Evas_Object *obj, const char *part)
Get the list of all the states in the given part.
EAPI Edje_Part_Type edje_edit_part_type_get (Evas_Object *obj, const char *part)
Get the type of a part.
EAPI Eina_List * edje_edit_parts_list_get (Evas_Object *obj)
Get the list of all the parts in the given edje object.
EAPI void edje_edit_print_internal_status (Evas_Object *obj)
Print on standard output many information about the internal status of the edje object.
EAPI Edje_Action_Type edje_edit_program_action_get (Evas_Object *obj, const char *prog)
Get the action of a given program.
EAPI Eina_Bool edje_edit_program_action_set (Evas_Object *obj, const char *prog, Edje_Action_Type action)
Set the action of a given program.
EAPI Eina_Bool edje_edit_program_add (Evas_Object *obj, const char *name)
Add a new program to the edje file.
EAPI Eina_Bool edje_edit_program_after_add (Evas_Object *obj, const char *prog, const char *after)
Add a new program name to the list of 'afters' in the given program.
EAPI Eina_Bool edje_edit_program_after_del (Evas_Object *obj, const char *prog, const char *after)
Delete the given program from the list of 'afters' of the program.
EAPI Eina_Bool edje_edit_program_afters_clear (Evas_Object *obj, const char *prog)
Clear the 'afters' list of the given program.
EAPI Eina_List * edje_edit_program_afters_get (Evas_Object *obj, const char *prog)
Get the list of action that will be run after the give program.
EAPI const char * edje_edit_program_api_description_get (Evas_Object *obj, const char *prog)
Get api's description of a program.
EAPI Eina_Bool edje_edit_program_api_description_set (Evas_Object *obj, const char *prog, const char *description)
Set api's description of a program.
EAPI const char * edje_edit_program_api_name_get (Evas_Object *obj, const char *prog)
Get api's name of a program.
EAPI Eina_Bool edje_edit_program_api_name_set (Evas_Object *obj, const char *prog, const char *name)
Set api's name of a program.
EAPI Eina_Bool edje_edit_program_del (Evas_Object *obj, const char *prog)
Remove the given program from the edje file.
EAPI Eina_Bool edje_edit_program_exist (Evas_Object *obj, const char *prog)
Check if a program with the given name exist in the edje object.
EAPI const char * edje_edit_program_filter_part_get (Evas_Object *obj, const char *prog)
EAPI Eina_Bool edje_edit_program_filter_part_set (Evas_Object *obj, const char *prog, const char *filter_part)
EAPI const char * edje_edit_program_filter_state_get (Evas_Object *obj, const char *prog)
EAPI Eina_Bool edje_edit_program_filter_state_set (Evas_Object *obj, const char *prog, const char *filter_state)
EAPI double edje_edit_program_in_from_get (Evas_Object *obj, const char *prog)
Get in.from of a given program.
EAPI Eina_Bool edje_edit_program_in_from_set (Evas_Object *obj, const char *prog, double seconds)
Set in.from of a given program.
EAPI double edje_edit_program_in_range_get (Evas_Object *obj, const char *prog)
Get in.range of a given program.
EAPI Eina_Bool edje_edit_program_in_range_set (Evas_Object *obj, const char *prog, double seconds)
Set in.range of a given program.
EAPI Eina_Bool edje_edit_program_name_set (Evas_Object *obj, const char *prog, const char *new_name)
Set a new name for the given program.
EAPI Eina_Bool edje_edit_program_run (Evas_Object *obj, const char *prog)
Run the given program.
EAPI const char * edje_edit_program_signal_get (Evas_Object *obj, const char *prog)
Get signal of a given program.
EAPI Eina_Bool edje_edit_program_signal_set (Evas_Object *obj, const char *prog, const char *sig)
Set signal of the given program.
EAPI const char * edje_edit_program_source_get (Evas_Object *obj, const char *prog)
Get source of a given program.
EAPI Eina_Bool edje_edit_program_source_set (Evas_Object *obj, const char *prog, const char *source)
Set source of the given program.
EAPI const char * edje_edit_program_state2_get (Evas_Object *obj, const char *prog)
Get the state2 for the given program.
EAPI Eina_Bool edje_edit_program_state2_set (Evas_Object *obj, const char *prog, const char *state2)
Set the state2 for the given program.
EAPI const char * edje_edit_program_state_get (Evas_Object *obj, const char *prog)
Get the state for the given program.
EAPI Eina_Bool edje_edit_program_state_set (Evas_Object *obj, const char *prog, const char *state)
Set the state for the given program.
EAPI Eina_Bool edje_edit_program_target_add (Evas_Object *obj, const char *prog, const char *target)
Add a new target program to the list of 'targets' in the given program.
EAPI Eina_Bool edje_edit_program_target_del (Evas_Object *obj, const char *prog, const char *target)
Deletes a target from the list of 'targets' in the given program.
EAPI Eina_Bool edje_edit_program_targets_clear (Evas_Object *obj, const char *prog)
Clear the 'targets' list of the given program.
EAPI Eina_List * edje_edit_program_targets_get (Evas_Object *obj, const char *prog)
Get the list of the targets for the given program.
EAPI Edje_Tween_Mode edje_edit_program_transition_get (Evas_Object *obj, const char *prog)
Get the type of transition to use when apply animations.
EAPI Eina_Bool edje_edit_program_transition_set (Evas_Object *obj, const char *prog, Edje_Tween_Mode transition)
Set the type of transition to use when apply animations.
EAPI double edje_edit_program_transition_time_get (Evas_Object *obj, const char *prog)
Get the duration of the transition in seconds.
EAPI Eina_Bool edje_edit_program_transition_time_set (Evas_Object *obj, const char *prog, double seconds)
Set the duration of the transition in seconds.
EAPI double edje_edit_program_value2_get (Evas_Object *obj, const char *prog)
Get the value of state2 for the given program.
EAPI Eina_Bool edje_edit_program_value2_set (Evas_Object *obj, const char *prog, double value)
Set the value2 of state for the given program.
EAPI double edje_edit_program_value_get (Evas_Object *obj, const char *prog)
Get the value of state for the given program.
EAPI Eina_Bool edje_edit_program_value_set (Evas_Object *obj, const char *prog, double value)
Set the value of state for the given program.
EAPI Eina_List * edje_edit_programs_list_get (Evas_Object *obj)
Get the list of all the programs in the given edje object.
EAPI Eina_Bool edje_edit_save (Evas_Object *obj)
Save the modified edje object back to his file.
EAPI Eina_Bool edje_edit_save_all (Evas_Object *obj)
Saves every group back into the file.
EAPI Eina_Bool edje_edit_script_compile (Evas_Object *obj)
Compile the Embryo script for the given object.
EAPI const Eina_List * edje_edit_script_error_list_get (Evas_Object *obj)
Get the list of errors resulting from the last script build.
EAPI char * edje_edit_script_get (Evas_Object *obj)
Get the Embryo script for the group of the given object.
EAPI char * edje_edit_script_program_get (Evas_Object *obj, const char *prog)
Get the Embryo script for the given program.
EAPI void edje_edit_script_program_set (Evas_Object *obj, const char *prog, const char *code)
Set the Embryo script for the given program.
EAPI void edje_edit_script_set (Evas_Object *obj, const char *code)
Set the code for the group script.
EAPI Eina_Bool edje_edit_state_add (Evas_Object *obj, const char *part, const char *name, double value)
Create a new state to the give part.
EAPI unsigned char edje_edit_state_aspect_pref_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the aspect preference of a part state.
EAPI void edje_edit_state_aspect_pref_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char pref)
Set the aspect preference of a part state.
EAPI void edje_edit_state_color3_get (Evas_Object *obj, const char *part, const char *state, double value, int *r, int *g, int *b, int *a)
Get the color3 of a part state.
EAPI void edje_edit_state_color3_set (Evas_Object *obj, const char *part, const char *state, double value, int r, int g, int b, int a)
Set the color3 of a part state.
EAPI const char * edje_edit_state_color_class_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the color class of the given part state.
EAPI void edje_edit_state_color_class_set (Evas_Object *obj, const char *part, const char *state, double value, const char *color_class)
Set the color class of the given part state.
EAPI Eina_Bool edje_edit_state_copy (Evas_Object *obj, const char *part, const char *from, double val_from, const char *to, double val_to)
Copies the state from into to.
EAPI Eina_Bool edje_edit_state_del (Evas_Object *obj, const char *part, const char *state, double value)
Delete the given part state from the edje.
EAPI Eina_Bool edje_edit_state_exist (Evas_Object *obj, const char *part, const char *state, double value)
Check if a part state with the given name exist.
EAPI Eina_Bool edje_edit_state_external_param_bool_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Eina_Bool *val)
Get external parameter of type BOOL.
EAPI Eina_Bool edje_edit_state_external_param_bool_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Eina_Bool val)
Set external parameter of type BOOL.
EAPI Eina_Bool edje_edit_state_external_param_choice_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char **val)
Get external parameter of type CHOICE.
EAPI Eina_Bool edje_edit_state_external_param_choice_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char *val)
Set external parameter of type CHOICE.
EAPI Eina_Bool edje_edit_state_external_param_double_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, double *val)
Get external parameter of type DOUBLE.
EAPI Eina_Bool edje_edit_state_external_param_double_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, double val)
Set external parameter of type DOUBLE.
EAPI Eina_Bool edje_edit_state_external_param_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Edje_External_Param_Type *type, void **val)
Get the external parameter type and value.
EAPI Eina_Bool edje_edit_state_external_param_int_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, int *val)
Get external parameter of type INT.
EAPI Eina_Bool edje_edit_state_external_param_int_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, int val)
Set external parameter of type INT.
EAPI Eina_Bool edje_edit_state_external_param_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Edje_External_Param_Type type,...)
Set the external parameter type and value, adding it if it didn't exist before.
EAPI Eina_Bool edje_edit_state_external_param_string_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char **val)
Get external parameter of type STRING.
EAPI Eina_Bool edje_edit_state_external_param_string_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char *val)
Set external parameter of type STRING.
EAPI const Eina_List * edje_edit_state_external_params_list_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the list of parameters for an external part.
EAPI unsigned char edje_edit_state_image_border_fill_get (Evas_Object *obj, const char *part, const char *state, double value)
Get if the image center should be draw.
EAPI void edje_edit_state_image_border_fill_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char fill)
Set if the image center should be draw.
EAPI void edje_edit_state_image_border_get (Evas_Object *obj, const char *part, const char *state, double value, int *l, int *r, int *t, int *b)
Get the image border of a part state.
EAPI void edje_edit_state_image_border_set (Evas_Object *obj, const char *part, const char *state, double value, int l, int r, int t, int b)
Set the image border of a part state.
EAPI const char * edje_edit_state_image_get (Evas_Object *obj, const char *part, const char *state, double value)
Get normal image name for a given part state.
EAPI void edje_edit_state_image_set (Evas_Object *obj, const char *part, const char *state, double value, const char *image)
Set normal image for a given part state.
EAPI Eina_Bool edje_edit_state_name_set (Evas_Object *obj, const char *part, const char *state, double value, const char *new_name, double new_value)
Set a new name for the given state in the given part.
EAPI const char * edje_edit_state_text_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the text of a part state.
EAPI void edje_edit_state_text_set (Evas_Object *obj, const char *part, const char *state, double value, const char *text)
Set the text of a part state.
EAPI int edje_edit_state_text_size_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the text size of a part state.
EAPI void edje_edit_state_text_size_set (Evas_Object *obj, const char *part, const char *state, double value, int size)
Set the text size of a part state.
EAPI Eina_Bool edje_edit_state_tween_add (Evas_Object *obj, const char *part, const char *state, double value, const char *tween)
Add a new tween frame to the given part state.
EAPI Eina_Bool edje_edit_state_tween_del (Evas_Object *obj, const char *part, const char *state, double value, const char *tween)
Remove the first tween with the given name.
EAPI Eina_List * edje_edit_state_tweens_list_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the list of all the tweens images in the given part state.
EAPI Eina_Bool edje_edit_state_visible_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the visibility of a part state.
EAPI void edje_edit_state_visible_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool visible)
Set the visibility of a part state.
EAPI void edje_edit_string_free (const char *str)
Free a generic string (char *) allocated by an edje_edit_*_get() function.
EAPI void edje_edit_string_list_free (Eina_List *lst)
Free a generic Eina_List of (char *) allocated by an edje_edit_*_get() function.
EAPI Eina_Bool edje_edit_style_add (Evas_Object *obj, const char *style)
Create a new text style object in the given edje.
EAPI void edje_edit_style_del (Evas_Object *obj, const char *style)
Delete the given text style and all the child tags.
EAPI Eina_Bool edje_edit_style_tag_add (Evas_Object *obj, const char *style, const char *tag_name)
Add a new tag to the given text style.
EAPI void edje_edit_style_tag_del (Evas_Object *obj, const char *style, const char *tag)
Delete the given tag.
EAPI void edje_edit_style_tag_name_set (Evas_Object *obj, const char *style, const char *tag, const char *new_name)
Set the name of the given tag.
EAPI const char * edje_edit_style_tag_value_get (Evas_Object *obj, const char *style, const char *tag)
Get the value of the given tag.
EAPI void edje_edit_style_tag_value_set (Evas_Object *obj, const char *style, const char *tag, const char *new_value)
Set the value of the given tag.
EAPI Eina_List * edje_edit_style_tags_list_get (Evas_Object *obj, const char *style)
Get the list of all the tags name in the given text style.
EAPI Eina_List * edje_edit_styles_list_get (Evas_Object *obj)
Get the list of all the text styles in the given edje object.
EVAS_SMART_SUBCLASS_NEW (_edje_edit_type, _edje_edit, Edje_Smart_Api, Edje_Smart_Api, _edje_object_smart_class_get, NULL)
FUNC_COLOR (color)
FUNC_COLOR (color2)
FUNC_GROUP_ACCESSOR (max, h)
FUNC_GROUP_ACCESSOR (max, w)
FUNC_GROUP_ACCESSOR (min, h)
FUNC_GROUP_ACCESSOR (min, w)
FUNC_PART_API_STRING (description)
FUNC_PART_API_STRING (name)
FUNC_PART_DRAG_ID (confine)
FUNC_PART_DRAG_ID (event)
FUNC_PART_DRAG_INT (count, x)
FUNC_PART_DRAG_INT (count, y)
FUNC_PART_DRAG_INT (step, x)
FUNC_PART_DRAG_INT (step, y)
FUNC_STATE_DOUBLE (align, x)
FUNC_STATE_DOUBLE (align, y)
FUNC_STATE_DOUBLE (aspect, max)
FUNC_STATE_DOUBLE (aspect, min)
FUNC_STATE_DOUBLE_FILL (, size, x)
FUNC_STATE_DOUBLE_FILL (, size, y)
FUNC_STATE_DOUBLE_FILL (pos_, origin, x)
FUNC_STATE_DOUBLE_FILL (pos_, origin, y)
FUNC_STATE_INT (max, h)
FUNC_STATE_INT (max, w)
FUNC_STATE_INT (min, h)
FUNC_STATE_INT (min, w)
FUNC_STATE_INT_FILL (, size, x)
FUNC_STATE_INT_FILL (, size, y)
FUNC_STATE_INT_FILL (pos_, origin, x)
FUNC_STATE_INT_FILL (pos_, origin, y)
FUNC_STATE_OFFSET_INT (rel1, x)
FUNC_STATE_OFFSET_INT (rel1, y)
FUNC_STATE_OFFSET_INT (rel2, x)
FUNC_STATE_OFFSET_INT (rel2, y)
FUNC_STATE_REL (rel1, x)
FUNC_STATE_REL (rel1, y)
FUNC_STATE_REL (rel2, x)
FUNC_STATE_REL (rel2, y)
FUNC_STATE_RELATIVE_DOUBLE (rel1, x)
FUNC_STATE_RELATIVE_DOUBLE (rel1, y)
FUNC_STATE_RELATIVE_DOUBLE (rel2, x)
FUNC_STATE_RELATIVE_DOUBLE (rel2, y)
FUNC_TEXT_BOOL_FIT (x)
FUNC_TEXT_BOOL_FIT (y)
FUNC_TEXT_DOUBLE (align_x, align.x)
FUNC_TEXT_DOUBLE (align_y, align.y)
FUNC_TEXT_DOUBLE (elipsis, elipsis)
Text API
Functions to deal with text objects (see Edje Data Collection reference).
EAPI const char * edje_edit_state_font_get (Evas_Object *obj, const char *part, const char *state, double value)
Get font name for a given part state.
EAPI void edje_edit_state_font_set (Evas_Object *obj, const char *part, const char *state, double value, const char *font)
Set font name for a given part state.
Variables
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED = 0
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST = 0
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_REFERENCED = 0
Macro Definition Documentation
BUF_APPEND
#define BUF_APPEND (STR) ret &= eina_strbuf_append(buf, STR)
BUF_APPENDF
#define BUF_APPENDF (FMT, ...) ret &= eina_strbuf_append_printf(buf, FMT, ##__VA_ARGS__)
EDIT_ALLOC_POOL
#define EDIT_ALLOC_POOL (Short, Type, Name)
Value:
     case EDJE_PART_TYPE_##Short:                   \
       {                                \
          Edje_Part_Description_##Type *Name;           \
                                        \
          Name = eina_mempool_malloc(ce->mp.Short,          \
                     sizeof (Edje_Part_Description_##Type)); \
          memset(Name, 0, sizeof(Edje_Part_Description_##Type));    \
          pd = &Name->common;                   \
          ce->count.Short++;                    \
          break;                            \
       }
EDIT_EMN
#define EDIT_EMN (Tp, Sz, Ce) Ce->mp.Tp = eina_mempool_add("chained_mempool", #Tp, NULL, sizeof (Sz), 8);
EDJE_EDIT_IS_UNSTABLE_AND_I_KNOW_ABOUT_IT
#define EDJE_EDIT_IS_UNSTABLE_AND_I_KNOW_ABOUT_IT
EDJE_EDIT_PROGRAM_ID_SET
#define EDJE_EDIT_PROGRAM_ID_SET (Array, Ed, It, Old, New)
Value:
   for (It = 0; It < Ed->collection->programs.Array##_count; ++It)  \
     _edje_part_program_id_set(Ed->collection->programs.Array[It], Old, New);
EDJE_EDIT_PROGRAM_SWITCH
#define EDJE_EDIT_PROGRAM_SWITCH (Array, Ed, It, Id1, Id2)
Value:
   for (It = 0; It < Ed->collection->programs.Array##_count; ++It)  \
     _edje_part_program_id_switch(Ed->collection->programs.Array[i], Id1, Id2);
FUNC_COLOR
#define FUNC_COLOR (Code)
Value:
  EAPI void                             \
  edje_edit_state_##Code##_get(Evas_Object *obj, const char *part, const char *state, double value, int *r, int *g, int *b, int *a) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN();                        \
                                    \
     if (r) *r = pd->Code.r;                        \
     if (g) *g = pd->Code.g;                        \
     if (b) *b = pd->Code.b;                        \
     if (a) *a = pd->Code.a;                        \
  }                                 \
  EAPI void                             \
  edje_edit_state_##Code##_set(Evas_Object *obj, const char *part, const char *state, double value, int r, int g, int b, int a) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN();                        \
                                        \
     if (r > -1 && r < 256) pd->Code.r = r;             \
     if (g > -1 && g < 256) pd->Code.g = g;             \
     if (b > -1 && b < 256) pd->Code.b = b;             \
     if (a > -1 && a < 256) pd->Code.a = a;             \
                                        \
     edje_object_calc_force(obj);                   \
  }
FUNC_GROUP_ACCESSOR
#define FUNC_GROUP_ACCESSOR (Class, Value)
Value:
  EAPI int                          \
  edje_edit_group_##Class##_##Value##_get(Evas_Object *obj) \
  {                             \
     eina_error_set(0);                     \
     GET_ED_OR_RETURN(-1);                  \
     if (!ed->collection) return -1;                \
     return ed->collection->prop.Class.Value;           \
  }                             \
  EAPI void                         \
  edje_edit_group_##Class##_##Value##_set(Evas_Object *obj, int v)  \
  {                             \
     eina_error_set(0);                     \
     GET_ED_OR_RETURN();                    \
     ed->collection->prop.Class.Value = v;          \
  }
FUNC_PART_API_STRING
#define FUNC_PART_API_STRING (Value)
Value:
  EAPI const char *                         \
  edje_edit_part_api_##Value##_get(Evas_Object *obj, const char *part)  \
  {                                 \
     eina_error_set(0);                         \
     GET_RP_OR_RETURN(NULL);                        \
     return eina_stringshare_add(rp->part->api.Value);          \
  }                                 \
  EAPI Eina_Bool                            \
  edje_edit_part_api_##Value##_set(Evas_Object *obj, const char *part, const char *s) \
  {                                 \
     eina_error_set(0);                         \
     GET_RP_OR_RETURN(EINA_FALSE);                  \
     _edje_if_string_free(ed, rp->part->api.Value);         \
     rp->part->api.Value = eina_stringshare_add(s);         \
     return EINA_TRUE;                          \
  }
FUNC_PART_DRAG_ID
#define FUNC_PART_DRAG_ID (Id)
FUNC_PART_DRAG_INT
#define FUNC_PART_DRAG_INT (Class, Value)
Value:
  EAPI int                              \
  edje_edit_part_drag_##Class##_##Value##_get(Evas_Object *obj, const char *part) \
  {                                 \
     eina_error_set(0);                         \
     GET_RP_OR_RETURN(0);                       \
     return rp->part->dragable.Class##_##Value;             \
  }                                 \
  EAPI void                             \
  edje_edit_part_drag_##Class##_##Value##_set(Evas_Object *obj, const char *part, int v) \
  {                                 \
     eina_error_set(0);                         \
     GET_RP_OR_RETURN();                        \
     rp->part->dragable.Class##_##Value = v;                \
  }
FUNC_STATE_DOUBLE
#define FUNC_STATE_DOUBLE (Class, Value)
Value:
  EAPI double                               \
  edje_edit_state_##Class##_##Value##_get(Evas_Object *obj, const char *part, const char *state, double value) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN(0);                       \
     return TO_DOUBLE(pd->Class.Value);             \
  }                                 \
  EAPI void                             \
  edje_edit_state_##Class##_##Value##_set(Evas_Object *obj, const char *part, const char *state, double value, double v) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN();                        \
     pd->Class.Value = FROM_DOUBLE(v);              \
     edje_object_calc_force(obj);                   \
  }
FUNC_STATE_DOUBLE_FILL
#define FUNC_STATE_DOUBLE_FILL (Class, Type, Value)
FUNC_STATE_INT
#define FUNC_STATE_INT (Class, Value)
Value:
  EAPI int                              \
  edje_edit_state_##Class##_##Value##_get(Evas_Object *obj, const char *part, const char *state, double value) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN(0);                       \
     return pd->Class.Value;                    \
  }                                 \
  EAPI void                             \
  edje_edit_state_##Class##_##Value##_set(Evas_Object *obj, const char *part, const char *state, double value, int v) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN();                        \
     pd->Class.Value = v;                   \
     edje_object_calc_force(obj);                   \
  }
FUNC_STATE_INT_FILL
#define FUNC_STATE_INT_FILL (Class, Type, Value)
FUNC_STATE_OFFSET_INT
#define FUNC_STATE_OFFSET_INT (Sub, Value)
Value:
  EAPI int                              \
  edje_edit_state_##Sub##_offset_##Value##_get(Evas_Object *obj, const char *part, const char *state, double value) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN(0);                       \
     return pd->Sub.offset_##Value;             \
  }                                 \
  EAPI void                             \
  edje_edit_state_##Sub##_offset_##Value##_set(Evas_Object *obj, const char *part, const char *state, double value, double v) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN();                        \
     pd->Sub.offset_##Value = TO_INT(FROM_DOUBLE(v));       \
     edje_object_calc_force(obj);                   \
  }
FUNC_STATE_REL
#define FUNC_STATE_REL (Sub, Value)
FUNC_STATE_RELATIVE_DOUBLE
#define FUNC_STATE_RELATIVE_DOUBLE (Sub, Value)
Value:
  EAPI double                               \
  edje_edit_state_##Sub##_relative_##Value##_get(Evas_Object *obj, const char *part, const char *state, double value) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN(0);                       \
     return TO_DOUBLE(pd->Sub.relative_##Value);            \
  }                                 \
  EAPI void                             \
  edje_edit_state_##Sub##_relative_##Value##_set(Evas_Object *obj, const char *part, const char *state, double value, double v) \
  {                                 \
     eina_error_set(0);                         \
     GET_PD_OR_RETURN();                        \
     pd->Sub.relative_##Value = FROM_DOUBLE(v);         \
     edje_object_calc_force(obj);               \
  }
FUNC_TEXT_BOOL_FIT
#define FUNC_TEXT_BOOL_FIT (Value)
FUNC_TEXT_DOUBLE
#define FUNC_TEXT_DOUBLE (Name, Value)
GET_ED_OR_RETURN
#define GET_ED_OR_RETURN (RET)
Value:
   Edje *ed; \
   GET_EED_OR_RETURN(RET); \
   ed = (Edje *)eed;
GET_EED_OR_RETURN
#define GET_EED_OR_RETURN (RET)
Value:
   Edje_Edit *eed; \
   if (!evas_object_smart_type_check_ptr(obj, _edje_edit_type)) \
     return RET; \
   eed = evas_object_smart_data_get(obj); \
   if (!eed) return RET;
GET_EPR_OR_RETURN
#define GET_EPR_OR_RETURN (RET)
Value:
   Edje_Program *epr; \
   if (!evas_object_smart_type_check_ptr(obj, _edje_edit_type)) \
     return RET; \
   epr = _edje_program_get_byname(obj, prog); \
   if (!epr) return RET;
GET_PD_OR_RETURN
#define GET_PD_OR_RETURN (RET)
Value:
   Edje *ed; \
   Edje_Edit *eed; \
   Edje_Real_Part *rp; \
   Edje_Part_Description_Common *pd; \
   if (!evas_object_smart_type_check_ptr(obj, _edje_edit_type)) \
     return RET; \
   eed = evas_object_smart_data_get(obj); \
   if (!eed) return RET; \
   ed = (Edje *)eed; \
   rp = _edje_real_part_get(ed, part); \
   if (!rp) return RET; \
   pd = _edje_part_description_find_byname(eed, part, state, value); \
   if (!pd) return RET;
GET_RP_OR_RETURN
#define GET_RP_OR_RETURN (RET)
Value:
   Edje *ed; \
   Edje_Edit *eed; \
   Edje_Real_Part *rp; \
   if (!evas_object_smart_type_check_ptr(obj, _edje_edit_type)) \
     return RET; \
   eed = evas_object_smart_data_get(obj); \
   if (!eed) return RET; \
   ed = (Edje *)eed; \
   rp = _edje_real_part_get(ed, part); \
   if (!rp) return RET;
I0
#define I0 ""
I1
#define I1 " "
I2
#define I2 " "
I3
#define I3 " "
I4
#define I4 " "
I5
#define I5 " "
I6
#define I6 " "
I7
#define I7 " "
PD_STRING_COPY
#define PD_STRING_COPY (To, From, _x)
Value:
   _edje_if_string_free(ed, To->_x);            \
   To->_x = (char *)eina_stringshare_add(From->_x);
Typedef Documentation
Edje_Edit
typedef struct _Edje_Edit Edje_Edit
Program_Script
typedef struct _Program_Script Program_Script
SrcFile
typedef struct _SrcFile SrcFile
SrcFile_List
typedef struct _SrcFile_List SrcFile_List
Function Documentation
_edje_edit_internal_save()
Eina_Bool _edje_edit_internal_save (Evas_Object * obj, int current_only)
References _Edje_File::compiler, ERR, _Edje::file, GET_ED_OR_RETURN, INF, and _Edje_File::path.
Referenced by edje_edit_save(), and edje_edit_save_all().
edje_edit_color_class_add()
EAPI Eina_Bool edje_edit_color_class_add (Evas_Object * obj, const char * name)
Create a new color class object in the given edje.
If another class with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
name Name for the new color class.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_File::color_classes, _Edje::file, GET_ED_OR_RETURN, name, and _Edje_Color_Class::name.
edje_edit_color_class_colors_get()
EAPI Eina_Bool edje_edit_color_class_colors_get (Evas_Object * obj, const char * class_name, int * r, int * g, int * b, int * a, int * r2, int * g2, int * b2, int * a2, int * r3, int * g3, int * b3, int * a3)
Get all the colors that compose the class.
You can pass NULL to colors you are not intrested in.
Parameters
obj Object being edited.
class_name Color class to fetch values.
r Red component of main color.
g Green component of main color.
b Blue component of main color.
a Alpha component of main color.
r2 Red component of secondary color.
g2 Green component of secondary color.
b2 Blue component of secondary color.
a2 Alpha component of secondary color.
r3 Red component of tertiary color.
g3 Green component of tertiary color.
b3 Blue component of tertiary color.
a3 Alpha component of tertiary color.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_Color_Class::a, _Edje_Color_Class::a2, _Edje_Color_Class::a3, _Edje_Color_Class::b, _Edje_Color_Class::b2, _Edje_Color_Class::b3, _Edje_File::color_classes, _Edje::file, _Edje_Color_Class::g, _Edje_Color_Class::g2, _Edje_Color_Class::g3, GET_ED_OR_RETURN, _Edje_Color_Class::name, _Edje_Color_Class::r, _Edje_Color_Class::r2, and _Edje_Color_Class::r3.
edje_edit_color_class_colors_set()
EAPI Eina_Bool edje_edit_color_class_colors_set (Evas_Object * obj, const char * class_name, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Set the colors for the given color class.
If you set a color to -1 it will not be touched.
Parameters
obj Object being edited.
class_name Color class to fetch values.
r Red component of main color.
g Green component of main color.
b Blue component of main color.
a Alpha component of main color.
r2 Red component of secondary color.
g2 Green component of secondary color.
b2 Blue component of secondary color.
a2 Alpha component of secondary color.
r3 Red component of tertiary color.
g3 Green component of tertiary color.
b3 Blue component of tertiary color.
a3 Alpha component of tertiary color.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_Color_Class::a, _Edje_Color_Class::a2, _Edje_Color_Class::a3, _Edje_Color_Class::b, _Edje_Color_Class::b2, _Edje_Color_Class::b3, _Edje_File::color_classes, _Edje::file, _Edje_Color_Class::g, _Edje_Color_Class::g2, _Edje_Color_Class::g3, GET_ED_OR_RETURN, _Edje_Color_Class::name, _Edje_Color_Class::r, _Edje_Color_Class::r2, and _Edje_Color_Class::r3.
edje_edit_color_class_del()
EAPI Eina_Bool edje_edit_color_class_del (Evas_Object * obj, const char * name)
Delete the given class object from edje.
Parameters
obj Object being edited.
name Color class to delete.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_File::color_classes, _Edje::file, GET_ED_OR_RETURN, name, and _Edje_Color_Class::name.
edje_edit_color_class_name_set()
EAPI Eina_Bool edje_edit_color_class_name_set (Evas_Object * obj, const char * name, const char * newname)
Change the name of a color class.
Parameters
obj Object being edited.
name Color class to rename.
newname New name for the color class.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_File::color_classes, _Edje::file, GET_ED_OR_RETURN, name, and _Edje_Color_Class::name.
edje_edit_color_classes_list_get()
EAPI Eina_List* edje_edit_color_classes_list_get (Evas_Object * obj)
Get the list of all the Color Classes in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being one color class.
References _Edje_File::color_classes, _Edje::file, GET_ED_OR_RETURN, and _Edje_Color_Class::name.
edje_edit_compiler_get()
EAPI const char* edje_edit_compiler_get (Evas_Object * obj)
Get the name of the program that compiled the edje file.
Can be 'edje_cc' or 'edje_edit'
Parameters
obj Object being edited.
Returns
Compiler stored in the Edje file
References _Edje_File::compiler, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_add()
EAPI Eina_Bool edje_edit_data_add (Evas_Object * obj, const char * itemname, const char * value)
Create a new global data object in the given edje file.
If another data entry with the same name exists, nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
itemname Name for the new data entry.
value Value for the new data entry.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_File::data, _Edje::file, GET_ED_OR_RETURN, and _Edje_String::str.
edje_edit_data_del()
EAPI Eina_Bool edje_edit_data_del (Evas_Object * obj, const char * itemname)
Delete the given data object from edje.
Parameters
obj Object being edited.
itemname Data entry to remove from the global data block.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje_File::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_list_get()
EAPI Eina_List* edje_edit_data_list_get (Evas_Object * obj)
Retrieves a list with the item names inside the data block.
Parameters
obj Object being edited.
Returns
List of strings, each being a name entry in the global data block for the file.
References _Edje_File::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_name_set()
EAPI Eina_Bool edje_edit_data_name_set (Evas_Object * obj, const char * itemname, const char * newname)
Change the name of the given data object.
Parameters
obj Object being edited.
itemname Data entry to rename.
newname New name for the data entry.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje_File::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_value_get()
EAPI const char* edje_edit_data_value_get (Evas_Object * obj, const char * itemname)
Get the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry to fetch the value for.
Returns
Value of the given entry, or NULL if not found.
References _Edje_File::data, edje_string_get(), _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_value_set()
EAPI Eina_Bool edje_edit_data_value_set (Evas_Object * obj, const char * itemname, const char * value)
Set the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of data entry to change the value.
value New value for the entry.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje_File::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_external_add()
EAPI Eina_Bool edje_edit_external_add (Evas_Object * obj, const char * external)
Add an external module to be requested on edje load.
Parameters
obj Object being edited.
external Name of the external module to add to the list of autoload.
Returns
EINA_TRUE on success (or it was already there), EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_external_del()
EAPI Eina_Bool edje_edit_external_del (Evas_Object * obj, const char * external)
Delete the given external from the list.
Parameters
obj Object being edited.
external Name of the external module to remove from the autoload list.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_externals_list_get()
EAPI Eina_List* edje_edit_externals_list_get (Evas_Object * obj)
Get the list of all the externals requested in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being an entry in the block of automatically loaded external modules.
References _Edje_External_Directory::entries, _Edje_External_Directory::entries_count, _Edje_External_Directory_Entry::entry, _Edje_File::external_dir, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_font_add()
EAPI Eina_Bool edje_edit_font_add (Evas_Object * obj, const char * path, const char * alias)
Add a new font to the edje file.
The newly created font will be available to all the groups in the edje, not only the current one.
Parameters
obj Object being edited.
path The file path to load the font from.
alias The alias for file, or NULL to use filename
Returns
EINA_TRUE if font cat be loaded, EINA_FALSE otherwise.
References _Edje::file, _Edje_File::fonts, GET_ED_OR_RETURN, INF, and _Edje::path.
edje_edit_font_del()
EAPI Eina_Bool edje_edit_font_del (Evas_Object * obj, const char * alias)
Delete font from the edje file.
The font will be removed from all the groups in the edje, not only the current one.
Parameters
obj Object being edited.
alias The font alias
Returns
EINA_TRUE if successful, EINA_FALSE otherwise (including the case when the alias is not valid).
References ERR, _Edje::file, _Edje_File::fonts, GET_ED_OR_RETURN, INF, _Edje::path, and WRN.
edje_edit_font_path_get()
EAPI const char* edje_edit_font_path_get (Evas_Object * obj, const char * alias)
Get font path for a given font alias.
Remember to free the string with edje_edit_string_free()
Parameters
obj Object being edited.
alias The font alias.
Returns
The path of the given font alias.
References _Edje_Font_Directory_Entry::entry, _Edje_Font_Directory_Entry::file, _Edje::file, _Edje_File::fonts, and GET_ED_OR_RETURN.
edje_edit_fonts_list_get()
EAPI Eina_List* edje_edit_fonts_list_get (Evas_Object * obj)
Get the list of all the fonts in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A list containing all the fonts names found in the edje file.
References _Edje_Font_Directory_Entry::entry, _Edje::file, _Edje_File::fonts, and GET_ED_OR_RETURN.
edje_edit_group_add()
EAPI Eina_Bool edje_edit_group_add (Evas_Object * obj, const char * name)
Create a new empty group in the given edje.
If a group with the same name exist none is created.
Parameters
obj Object being edited.
name Name of the new group.
Returns
EINA_TRUE if successfully added the group, EINA_FALSE if an error occurred or if a group with the same name exists.
Add an edje (empty) group to an edje object's group set.
Parameters
obj The pointer to edje object.
name The name of the group.
Returns
1 If it could allocate memory to the part group added or zero if not.
This function adds, at run time, one more group, which will reside in memory, to the group set found in the .edj file which obj was loaded with. This group can be manipulated by other API functions, like edje_edit_part_add(), for example. If desired, the new group can be actually committed the respective .edj by use of edje_edit_save().
References _Edje_File::collection, _Edje::file, GET_ED_OR_RETURN, and name.
edje_edit_group_data_add()
EAPI Eina_Bool edje_edit_group_data_add (Evas_Object * obj, const char * itemname, const char * value)
Create a new data object in the given edje file belonging to the current group.
If another data entry with the same name exists, nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
itemname Name for the new data entry.
value Value for the new data entry.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, GET_ED_OR_RETURN, and _Edje_String::str.
edje_edit_group_data_del()
EAPI Eina_Bool edje_edit_group_data_del (Evas_Object * obj, const char * itemname)
Delete the given data object from the group.
Parameters
obj Object being edited.
itemname Name of the data entry to remove.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_data_list_get()
EAPI Eina_List* edje_edit_group_data_list_get (Evas_Object * obj)
Retrieves a list with the item names inside the data block at the group level.
Parameters
obj Object being edited.
Returns
List of strings, each being a name entry in the data block for the group.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_data_name_set()
EAPI Eina_Bool edje_edit_group_data_name_set (Evas_Object * obj, const char * itemname, const char * newname)
Change the name of the given data object.
Parameters
obj Object being edited.
itemname Name of the data entry to rename.
newname New name for the data entry.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_data_value_get()
EAPI const char* edje_edit_group_data_value_get (Evas_Object * obj, const char * itemname)
Get the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry.
Returns
Value of the data entry or NULL if not found.
References _Edje::collection, _Edje_Part_Collection::data, edje_string_get(), _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_data_value_set()
EAPI Eina_Bool edje_edit_group_data_value_set (Evas_Object * obj, const char * itemname, const char * value)
Set the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry to set the value.
value Value to set for the data entry.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_del()
EAPI Eina_Bool edje_edit_group_del (Evas_Object * obj, const char * group_name)
Delete the specified group from the given edje.
You can only delete a currently unused group. All the parts and the programs inside the group will be deleted as well, but not image or font embedded in the edje.
Parameters
obj Object being edited.
group_name Name of group to delete.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Delete the specified group from the edje file.
Parameters
obj The pointer to the edje object.
group_name Group to delete.
Returns
EINA_TRUE on success, EINA_FALSE on failure.
This function deletes the given group from the file obj is set to. This operation can't be undone as all references to the group are removed from the file. This function may fail if the group to be deleted is currently in use.
References _Edje_File::collection, _Edje::collection, EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED, EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST, EDJE_EDIT_ERROR_GROUP_REFERENCED, _Edje::file, GET_ED_OR_RETURN, _Edje::group, _Edje_Part_Collection_Directory_Entry::id, _Edje_Part_Collection::id, and _Edje_Part_Collection_Directory_Entry::ref.
edje_edit_group_exist()
EAPI Eina_Bool edje_edit_group_exist (Evas_Object * obj, const char * group)
Check if a group with the given name exist in the edje.
Parameters
obj Object being edited.
group Group name to check for.
Returns
EINA_TRUE if group exists, EINA_FALSE if not.
References _Edje_File::collection, _Edje::file, and GET_ED_OR_RETURN.
Referenced by edje_edit_group_name_set().
edje_edit_group_name_set()
EAPI Eina_Bool edje_edit_group_name_set (Evas_Object * obj, const char * new_name)
Set a new name for the current open group.
You can only rename a group that is currently loaded Note that the relative getter function don't exist as it doesn't make sense ;)
Parameters
obj Object being edited.
new_name New name for the group.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, edje_edit_group_exist(), GET_ED_OR_RETURN, and _Edje_Part_Collection::part.
edje_edit_image_add()
EAPI Eina_Bool edje_edit_image_add (Evas_Object * obj, const char * path)
Add an new image to the image collection.
This function add the given image inside the edje. Don't add a new image part but only put the image inside the edje file. It actually write directly to the file so you don't have to save. After you have to create a new image_part that use this image. Note that all the parts in the edje share the same image collection, thus you can/must use the same image for different part.
The format of the image files that can be loaded depend on the evas engine on your system
Parameters
obj Object being edited.
path The name of the image file to include in the edje.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::file, GET_ED_OR_RETURN, _Edje_File::image_dir, name, and _Edje::path.
edje_edit_image_compression_rate_get()
EAPI int edje_edit_image_compression_rate_get (Evas_Object * obj, const char * image)
Get compression rate for the given image.
Parameters
obj Object being edited.
image The name of the image.
Returns
The compression rate (if the imnage is EDJE_EDIT_IMAGE_COMP_LOSSY) or < 0, on errors.
References EDJE_IMAGE_SOURCE_TYPE_INLINE_LOSSY, _Edje_Image_Directory::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, _Edje::file, GET_ED_OR_RETURN, _Edje_File::image_dir, _Edje_Image_Directory_Entry::source_param, and _Edje_Image_Directory_Entry::source_type.
edje_edit_image_compression_type_get()
EAPI Edje_Edit_Image_Comp edje_edit_image_compression_type_get (Evas_Object * obj, const char * image)
Get compression type for the given image.
Parameters
obj Object being edited.
image The name of the image.
Returns
One of Image Compression types. (EDJE_EDIT_IMAGE_COMP_RAW, EDJE_EDIT_IMAGE_COMP_USER, EDJE_EDIT_IMAGE_COMP_COMP, EDJE_EDIT_IMAGE_COMP_LOSSY).
References EDJE_EDIT_IMAGE_COMP_COMP, EDJE_EDIT_IMAGE_COMP_LOSSY, EDJE_EDIT_IMAGE_COMP_RAW, EDJE_EDIT_IMAGE_COMP_USER, EDJE_IMAGE_SOURCE_TYPE_EXTERNAL, EDJE_IMAGE_SOURCE_TYPE_INLINE_LOSSY, EDJE_IMAGE_SOURCE_TYPE_INLINE_PERFECT, _Edje_Image_Directory::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, _Edje::file, GET_ED_OR_RETURN, _Edje_File::image_dir, _Edje_Image_Directory_Entry::source_param, and _Edje_Image_Directory_Entry::source_type.
edje_edit_image_data_add()
EAPI Eina_Bool edje_edit_image_data_add (Evas_Object * obj, const char * name, int id)
Add an image entry to the image collection.
This function adds the given image entry to the edje image collection. The image needs to be inside the eet already, with key name "images/id". After you have to create a new image_part that use this image, referring to it as "name". Note that all the parts in the edje share the same image collection, thus you can/must use the same image for different part.
Parameters
obj Object being edited.
name The image entry name.
id The image id.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::file, GET_ED_OR_RETURN, _Edje_File::image_dir, name, and _Edje::path.
edje_edit_image_del()
EAPI Eina_Bool edje_edit_image_del (Evas_Object * obj, const char * name)
Delete an image from the image collection.
It actually write directly to the file so you don't have to save.
Parameters
obj Object being edited.
name The name of the image file to include in the edje.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise (including the case when the name is not valid).
References _Edje_Image_Directory::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, ERR, _Edje::file, GET_ED_OR_RETURN, _Edje_Image_Directory_Entry::id, _Edje_File::image_dir, name, and _Edje::path.
edje_edit_image_id_get()
EAPI int edje_edit_image_id_get (Evas_Object * obj, const char * image_name)
Get image id for a given image name.
Parameters
obj Object being edited.
image_name The image name.
Returns
The id of the given image name.
References GET_EED_OR_RETURN.
edje_edit_images_list_get()
EAPI Eina_List* edje_edit_images_list_get (Evas_Object * obj)
Get the list of all the images in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A List containing all images names found in the edje file.
References _Edje_Image_Directory::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, _Edje::file, GET_ED_OR_RETURN, and _Edje_File::image_dir.
edje_edit_object_add()
EAPI Evas_Object* edje_edit_object_add (Evas * e)
Adds an editable Edje object to the canvas.
An Edje_Edit object is, for the most part, a standard Edje object. Only difference is you can use the Edje_Edit API on them.
Parameters
e Evas canvas where to add the object.
Returns
An Evas_Object of type Edje_Edit, or NULL if an error occurred.
References EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST.
edje_edit_part_above_get()
EAPI const char* edje_edit_part_above_get (Evas_Object * obj, const char * part)
Get the name of part stacked above the one passed.
Parameters
obj Object being edited.
part Name of part of which to check the one above.
Returns
Name of the part above. NULL if an error occurred or if part is the topmost part in the group.
References GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_add()
EAPI Eina_Bool edje_edit_part_add (Evas_Object * obj, const char * name, Edje_Part_Type type)
Create a new part in the given edje.
If another part with the same name just exists nothing is created and EINA_FALSE is returned. Note that this function also create a default description for the part.
Parameters
obj Object being edited.
name Name for the new part.
type Type of the new part. See Edje Data Collection reference for more info on this.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References EDJE_PART_TYPE_EXTERNAL, and type.
edje_edit_part_below_get()
EAPI const char* edje_edit_part_below_get (Evas_Object * obj, const char * part)
Get the name of part stacked below the one passed.
Parameters
obj Object being edited.
part Name of part of which to check the one below.
Returns
Name of the part below. NULL if an error occurred or if part is the bottommost part in the group.
References GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_clip_to_get()
EAPI const char* edje_edit_part_clip_to_get (Evas_Object * obj, const char * part)
Get the clip_to part.
Parameters
obj Object being edited.
part Name of the part whose clipper to get.
Returns
Name of the part part is clipped to. NULL is returned on errors and if the part don't have a clip.
References _Edje_Part::clip_to_id, GET_RP_OR_RETURN, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_clip_to_set()
EAPI Eina_Bool edje_edit_part_clip_to_set (Evas_Object * obj, const char * part, const char * clip_to)
Set a part to clip part to.
Parameters
obj Object being edited.
part Part to set the clipper to.
clip_to Part to use as clipper, if NULL then the clipping value will be cancelled (unset clipping).
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_real_part_get(), _Edje::base, _Edje_Real_Part::clip_to, _Edje_Part::clip_to_id, edje_object_calc_force(), GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Real_Part::swallowed_object.
edje_edit_part_del()
EAPI Eina_Bool edje_edit_part_del (Evas_Object * obj, const char * part)
Delete the given part from the edje.
All the reference to this part will be zeroed.
Parameters
obj Object being edited.
part Name of part to delete.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::base, _Edje_Real_Part::clip_to, _Edje_Real_Part_Drag::confine_to, _Edje_Real_Part::custom, _Edje_Real_Part::drag, GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Real_Part::object, _Edje_Real_Part::param1, _Edje_Real_Part::param2, _Edje_Real_Part::part, _Edje_Real_Part_State::rel1_to_x, _Edje_Real_Part_State::rel1_to_y, _Edje_Real_Part_State::rel2_to_x, _Edje_Real_Part_State::rel2_to_y, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Real_Part::text.
edje_edit_part_drag_x_get()
EAPI int edje_edit_part_drag_x_get (Evas_Object * obj, const char * part)
Get horizontal dragable state for part.
Parameters
obj Object being edited.
part Part to get if can be dragged horizontally;
Returns
1 (or -1) if the part can be dragged horizontally, 0 otherwise.
References _Edje_Part::dragable, GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part_Dragable::x.
edje_edit_part_drag_x_set()
EAPI void edje_edit_part_drag_x_set (Evas_Object * obj, const char * part, int drag)
Set horizontal dragable state for part.
Parameters
obj Object being edited.
part Part to set if should be dragged horizontally.
drag 1 (or -1) if the part should be dragged horizontally, 0 otherwise.
References _Edje_Real_Part::drag, _Edje_Part::dragable, GET_RP_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Dragable::x, and _Edje_Part_Dragable::y.
edje_edit_part_drag_y_get()
EAPI int edje_edit_part_drag_y_get (Evas_Object * obj, const char * part)
Get vertical dragable state for part.
Parameters
obj Object being edited.
part Part to get if can be dragged vertically.
Returns
1 (or - 1) if the part can be dragged vertically, 0 otherwise.
References _Edje_Part::dragable, GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part_Dragable::y.
edje_edit_part_drag_y_set()
EAPI void edje_edit_part_drag_y_set (Evas_Object * obj, const char * part, int drag)
Set vertical dragable state for part.
Parameters
obj Object being edited.
part Part to set if should be dragged vertically.
drag 1 (or -1) of the part shpuld be dragged vertically, 0 otherwise.
References _Edje_Real_Part::drag, _Edje_Part::dragable, GET_RP_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Dragable::x, and _Edje_Part_Dragable::y.
edje_edit_part_effect_get()
EAPI Edje_Text_Effect edje_edit_part_effect_get (Evas_Object * obj, const char * part)
Get the effect for a given part.
Gets the effect used for parts of type TEXT. See Edje Data Collection reference for more details.
Parameters
obj Object being edited.
part Part to get the effect of.
Returns
The effect set for the part.
References _Edje_Part::effect, GET_RP_OR_RETURN, and _Edje_Real_Part::part.
edje_edit_part_effect_set()
EAPI void edje_edit_part_effect_set (Evas_Object * obj, const char * part, Edje_Text_Effect effect)
Set the effect for a given part.
Parameters
obj Object being edited.
part Part to set the effect to. Only makes sense on type TEXT.
effect Effect to set for the part.
References edje_object_calc_force(), _Edje_Part::effect, GET_RP_OR_RETURN, and _Edje_Real_Part::part.
edje_edit_part_exist()
EAPI Eina_Bool edje_edit_part_exist (Evas_Object * obj, const char * part)
Check if a part with the given name exist in the edje object.
Parameters
obj Object being edited.
part Name of part to check for its existence.
Returns
EINA_TRUE if the part exists, EINA_FALSE if not.
References GET_RP_OR_RETURN.
edje_edit_part_external_add()
EAPI Eina_Bool edje_edit_part_external_add (Evas_Object * obj, const char * name, const char * source)
Create a new part of type EXTERNAL in the given edje.
If another part with the same name just exists nothing is created and EINA_FALSE is returned. Note that this function also create a default description for the part.
Parameters
obj Object being edited.
name Name for the new part.
source The registered external type to use for this part.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_part_ignore_flags_get()
EAPI Evas_Event_Flags edje_edit_part_ignore_flags_get (Evas_Object * obj, const char * part)
Get ignore_flags for part.
Parameters
obj Object being edited.
part Part to get which event_flags are being ignored.
Returns
The Event flags set to the part.
References GET_RP_OR_RETURN, _Edje_Part::ignore_flags, and _Edje_Real_Part::part.
edje_edit_part_ignore_flags_set()
EAPI void edje_edit_part_ignore_flags_set (Evas_Object * obj, const char * part, Evas_Event_Flags ignore_flags)
Set ignore_flags for part.
Parameters
obj Object being edited.
part Part to set which event flags will be ignored.
ignore_flags The Event flags to be ignored by the part.
References GET_RP_OR_RETURN, _Edje_Part::ignore_flags, _Edje_Real_Part::object, and _Edje_Real_Part::part.
edje_edit_part_mouse_events_get()
EAPI Eina_Bool edje_edit_part_mouse_events_get (Evas_Object * obj, const char * part)
Get mouse_events for part.
Parameters
obj Object being edited.
part Part to get if the mouse events is accepted.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_RP_OR_RETURN, _Edje_Part::mouse_events, and _Edje_Real_Part::part.
edje_edit_part_mouse_events_set()
EAPI void edje_edit_part_mouse_events_set (Evas_Object * obj, const char * part, Eina_Bool mouse_events)
Set mouse_events for part.
Parameters
obj Object being edited.
part The part to set if the mouse events is accepted.
mouse_events EINA_TRUE if part will accept mouse events, EINA_FALSE otherwise.
References _edje_callbacks_add(), _edje_callbacks_del(), GET_RP_OR_RETURN, _Edje_Part::mouse_events, _Edje_Real_Part::object, and _Edje_Real_Part::part.
edje_edit_part_name_set()
EAPI Eina_Bool edje_edit_part_name_set (Evas_Object * obj, const char * part, const char * new_name)
Set a new name for part.
Note that the relative getter function don't exist as it don't make sense ;)
Parameters
obj Object being edited.
part Name of part to rename.
new_name New name for the given part.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_real_part_get(), and GET_RP_OR_RETURN.
edje_edit_part_repeat_events_get()
EAPI Eina_Bool edje_edit_part_repeat_events_get (Evas_Object * obj, const char * part)
Get repeat_events for part.
Parameters
obj Object being edited.
part Part to set if will pass all events to the other parts.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::repeat_events.
edje_edit_part_repeat_events_set()
EAPI void edje_edit_part_repeat_events_set (Evas_Object * obj, const char * part, Eina_Bool repeat_events)
Set repeat_events for part.
Parameters
obj Object being edited.
part Part to set if will repeat all the received mouse events to other parts.
repeat_events EINA_TRUE if the events received will propagate to other parts, EINA_FALSE otherwise
References GET_RP_OR_RETURN, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Part::repeat_events.
edje_edit_part_restack_above()
EAPI Eina_Bool edje_edit_part_restack_above (Evas_Object * obj, const char * part)
Move the given part above the next one.
Parameters
obj Object being edited.
part Name of part to move one step above.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Real_Part::part, _Edje_Part_Collection::parts, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_restack_below()
EAPI Eina_Bool edje_edit_part_restack_below (Evas_Object * obj, const char * part)
Move the given part below the previous one.
Parameters
obj Object being edited.
part Name of part to move one step below.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Real_Part::part, _Edje_Part_Collection::parts, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_scale_get()
EAPI Eina_Bool edje_edit_part_scale_get (Evas_Object * obj, const char * part)
Get scale for the part.
Parameters
obj Object being edited.
part Part to get the scale value of.
Returns
Whether scale is on (EINA_TRUE) or not.
References GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::scale.
edje_edit_part_scale_set()
EAPI void edje_edit_part_scale_set (Evas_Object * obj, const char * part, Eina_Bool scale)
Set scale property for the part.
This property tells Edje that the given part should be scaled by the Edje scale factor.
Parameters
obj Object being edited.
part Part to set scale for.
scale Scale value to set.
References edje_object_calc_force(), GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::scale.
edje_edit_part_selected_state_get()
EAPI const char* edje_edit_part_selected_state_get (Evas_Object * obj, const char * part, double * value)
Get the current selected state in part.
Parameters
obj Object being edited.
part Part to get the selected state of.
value Pointer to a double where the value of the state will be stored.
Returns
The name of the currently selected state for the part.
References _Edje_Real_Part::chosen_description, GET_RP_OR_RETURN, _Edje_Part_Description_Common::name, _Edje_Part_Description_Common::state, and _Edje_Part_Description_Common::value.
edje_edit_part_selected_state_set()
EAPI Eina_Bool edje_edit_part_selected_state_set (Evas_Object * obj, const char * part, const char * state, double value)
Set the current state in part.
Parameters
obj Object being edited.
part Part to set the state of.
state Name of the state to set.
value Value of the state.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_RP_OR_RETURN.
edje_edit_part_source_get()
EAPI const char* edje_edit_part_source_get (Evas_Object * obj, const char * part)
Get the source of part.
The meaning of this parameter varies depending on the type of the part. For GROUP parts, it's the name of another group in the Edje file which will be autoloaded and swallowed on this part. For TEXTBLOCK parts, it's the name of a group to be used for selection display under the text. For EXTERNAL parts, it's the name of the registered external widget to load and swallow on this part.
Parameters
obj Object being edited.
part Part to get the source from.
Returns
Content of the source parameter or NULL if nothing set or an error occurred.
References GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::source.
edje_edit_part_source_set()
EAPI Eina_Bool edje_edit_part_source_set (Evas_Object * obj, const char * part, const char * source)
Set the source of part.
Parameters
obj Object being edited.
part Part to set the source of.
source Value for the source parameter.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
See also
edje_edit_part_source_get()
Note
You can't change the source for EXTERNAL parts, it's akin to changing the type of the part.
NOTE: This is not applied now. You must reload the edje to see the change.
References EDJE_PART_TYPE_EXTERNAL, GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_part_states_list_get()
EAPI Eina_List* edje_edit_part_states_list_get (Evas_Object * obj, const char * part)
Get the list of all the states in the given part.
Parameters
obj Object being edited.
part Part to get the states names list.
Returns
An Eina_List* of string (char *)containing all the states names found in part, including the float value (ex: "default 0.00").
Use edje_edit_string_list_free() when you don't need it anymore.
References _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, GET_RP_OR_RETURN, _Edje_Part_Description_Common::name, _Edje_Part::other, _Edje_Real_Part::part, _Edje_Part_Description_Common::state, and _Edje_Part_Description_Common::value.
edje_edit_part_type_get()
EAPI Edje_Part_Type edje_edit_part_type_get (Evas_Object * obj, const char * part)
Get the type of a part.
Parameters
obj Object being edited.
part Name of part to get the type of.
Returns
Type of the part. See Edje Data Collection reference for details.
References GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_parts_list_get()
EAPI Eina_List* edje_edit_parts_list_get (Evas_Object * obj)
Get the list of all the parts in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being the name for a part in the open group.
References GET_ED_OR_RETURN, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_print_internal_status()
EAPI void edje_edit_print_internal_status (Evas_Object * obj)
Print on standard output many information about the internal status of the edje object.
This is probably only useful to debug.
Parameters
obj Object being edited.
References GET_EED_OR_RETURN.
edje_edit_program_action_get()
EAPI Edje_Action_Type edje_edit_program_action_get (Evas_Object * obj, const char * prog)
Get the action of a given program.
Parameters
obj Object being edited.
prog The name of the program to get the action.
Returns
The action type, or -1 on errors. Action can be one of EDJE_ACTION_TYPE_NONE, _STATE_SET, ACTION_STOP, SIGNAL_EMIT, DRAG_VAL_SET, _DRAG_VAL_STEP, _DRAG_VAL_PAGE, _SCRIPT
References _Edje_Program::action, and GET_EPR_OR_RETURN.
edje_edit_program_action_set()
EAPI Eina_Bool edje_edit_program_action_set (Evas_Object * obj, const char * prog, Edje_Action_Type action)
Set the action of a given program.
Action can be one of EDJE_ACTION_TYPE_NONE, _STATE_SET, ACTION_STOP, SIGNAL_EMIT, DRAG_VAL_SET, _DRAG_VAL_STEP, _DRAG_VAL_PAGE, _SCRIPT
Parameters
obj Object being edited.
prog The name of the program to set the action.
action The new action type.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_Program::action, EDJE_ACTION_TYPE_LAST, EDJE_ACTION_TYPE_SCRIPT, GET_EED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Program::id, and _Edje_Edit::program_scripts.
edje_edit_program_add()
EAPI Eina_Bool edje_edit_program_add (Evas_Object * obj, const char * name)
Add a new program to the edje file.
If a program with the same name just exist the function will fail.
Parameters
obj Object being edited.
name The name of the new program.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_program_after_add()
EAPI Eina_Bool edje_edit_program_after_add (Evas_Object * obj, const char * prog, const char * after)
Add a new program name to the list of 'afters' in the given program.
All the programs listed in 'afters' will be executed after program execution.
Parameters
obj Object being edited.
prog The name of the program that contains the list of afters
after The name of another program to add to the afters list
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN.
edje_edit_program_after_del()
EAPI Eina_Bool edje_edit_program_after_del (Evas_Object * obj, const char * prog, const char * after)
Delete the given program from the list of 'afters' of the program.
Parameters
obj Object being edited.
prog The name of the program from where to remove the after.
after The name of the program to remove from the list of afters.
Returns
EINA_TRUE is successful or not in the list, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN.
edje_edit_program_afters_clear()
EAPI Eina_Bool edje_edit_program_afters_clear (Evas_Object * obj, const char * prog)
Clear the 'afters' list of the given program.
Parameters
obj Object being edited.
prog The name of the program to clear the 'afters' list.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_Program::after, and GET_EPR_OR_RETURN.
edje_edit_program_afters_get()
EAPI Eina_List* edje_edit_program_afters_get (Evas_Object * obj, const char * prog)
Get the list of action that will be run after the give program.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
prog The name of the program to get the list of actions
Returns
A list with all program names. or NULL on error.
References _Edje_Program::after, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Program_After::id, _Edje_Program::name, _Edje::table_programs, and _Edje::table_programs_size.
edje_edit_program_api_description_get()
EAPI const char* edje_edit_program_api_description_get (Evas_Object * obj, const char * prog)
Get api's description of a program.
Parameters
obj Object being edited.
prog Name of program.
Returns
description of the api if successful, NULL otherwise.
References _Edje_Program::api, _Edje_Program::description, and GET_EPR_OR_RETURN.
edje_edit_program_api_description_set()
EAPI Eina_Bool edje_edit_program_api_description_set (Evas_Object * obj, const char * prog, const char * description)
Set api's description of a program.
Parameters
obj Object being edited.
prog Name of the program.
description New description for the api property.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_api_name_get()
EAPI const char* edje_edit_program_api_name_get (Evas_Object * obj, const char * prog)
Get api's name of a program.
Parameters
obj Object being edited.
prog Name of program.
Returns
name of the api if successful, NULL otherwise.
References _Edje_Program::api, GET_EPR_OR_RETURN, and _Edje_Program::name.
edje_edit_program_api_name_set()
EAPI Eina_Bool edje_edit_program_api_name_set (Evas_Object * obj, const char * prog, const char * name)
Set api's name of a program.
Parameters
obj Object being edited.
prog Name of the part.
name New name for the api property.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_del()
EAPI Eina_Bool edje_edit_program_del (Evas_Object * obj, const char * prog)
Remove the given program from the edje file.
Parameters
obj Object being edited.
prog The name of the program to remove.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_program_remove(), _Edje::collection, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Program::id, _Edje_Edit::program_scripts, _Edje::table_programs, and _Edje::table_programs_size.
edje_edit_program_exist()
EAPI Eina_Bool edje_edit_program_exist (Evas_Object * obj, const char * prog)
Check if a program with the given name exist in the edje object.
Parameters
obj Object being edited.
prog The prog of the program that will be searched.
Returns
EINA_TRUE if the program exist, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN.
edje_edit_program_filter_part_get()
EAPI const char* edje_edit_program_filter_part_get (Evas_Object * obj, const char * prog)
References _Edje_Program::filter, GET_EPR_OR_RETURN, and _Edje_Program::part.
edje_edit_program_filter_part_set()
EAPI Eina_Bool edje_edit_program_filter_part_set (Evas_Object * obj, const char * prog, const char * filter_part)
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_filter_state_get()
EAPI const char* edje_edit_program_filter_state_get (Evas_Object * obj, const char * prog)
References _Edje_Program::filter, GET_EPR_OR_RETURN, and _Edje_Program::state.
edje_edit_program_filter_state_set()
EAPI Eina_Bool edje_edit_program_filter_state_set (Evas_Object * obj, const char * prog, const char * filter_state)
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_in_from_get()
EAPI double edje_edit_program_in_from_get (Evas_Object * obj, const char * prog)
Get in.from of a given program.
Parameters
obj Object being edited.
prog The name of the program to get the delay.
Returns
The delay.
References _Edje_Program::from, GET_EPR_OR_RETURN, and _Edje_Program::in.
edje_edit_program_in_from_set()
EAPI Eina_Bool edje_edit_program_in_from_set (Evas_Object * obj, const char * prog, double seconds)
Set in.from of a given program.
Parameters
obj Object being edited.
prog The name of the program to set the delay.
seconds Number of seconds to delay the program execution
References _Edje_Program::from, GET_EPR_OR_RETURN, and _Edje_Program::in.
edje_edit_program_in_range_get()
EAPI double edje_edit_program_in_range_get (Evas_Object * obj, const char * prog)
Get in.range of a given program.
Parameters
obj Object being edited.
prog The name of the program to get random delay.
Returns
The delay random.
References GET_EPR_OR_RETURN, _Edje_Program::in, and _Edje_Program::range.
edje_edit_program_in_range_set()
EAPI Eina_Bool edje_edit_program_in_range_set (Evas_Object * obj, const char * prog, double seconds)
Set in.range of a given program.
Parameters
obj Object being edited.
prog The name of the program to set random delay.
seconds Max random number of seconds to delay.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN, _Edje_Program::in, and _Edje_Program::range.
edje_edit_program_name_set()
EAPI Eina_Bool edje_edit_program_name_set (Evas_Object * obj, const char * prog, const char * new_name)
Set a new name for the given program.
Parameters
obj Object being edited.
prog The current program name.
new_name The new name to assign.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_run()
EAPI Eina_Bool edje_edit_program_run (Evas_Object * obj, const char * prog)
Run the given program.
Parameters
obj Object being edited.
prog The name of the program to execute.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_program_run(), GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_signal_get()
EAPI const char* edje_edit_program_signal_get (Evas_Object * obj, const char * prog)
Get signal of a given program.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
prog The name of the program to get the signal.
Returns
The signal value for program.
References GET_EPR_OR_RETURN, and _Edje_Program::signal.
edje_edit_program_signal_set()
EAPI Eina_Bool edje_edit_program_signal_set (Evas_Object * obj, const char * prog, const char * signal)
Set signal of the given program.
Parameters
obj Object being edited.
prog The name of the program to set the signal.
signal The new signal value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_program_remove(), _Edje::collection, GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_source_get()
EAPI const char* edje_edit_program_source_get (Evas_Object * obj, const char * prog)
Get source of a given program.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
prog The name of the program to get source.
Returns
The source value por program.
References GET_EPR_OR_RETURN, and _Edje_Program::source.
edje_edit_program_source_set()
EAPI Eina_Bool edje_edit_program_source_set (Evas_Object * obj, const char * prog, const char * source)
Set source of the given program.
Parameters
obj Object being edited.
prog The name of the program to set source.
source The new source value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_program_remove(), _Edje::collection, GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_state2_get()
EAPI const char* edje_edit_program_state2_get (Evas_Object * obj, const char * prog)
Get the state2 for the given program.
In a STATE_SET action is not used In a SIGNAL_EMIT action is the source of the emitted signal.
Parameters
obj Object being edited.
prog The name of the program to get the state2.
Returns
The source to emit for the program.
References GET_EPR_OR_RETURN, and _Edje_Program::state2.
edje_edit_program_state2_set()
EAPI Eina_Bool edje_edit_program_state2_set (Evas_Object * obj, const char * prog, const char * state2)
Set the state2 for the given program.
In a STATE_SET action is not used In a SIGNAL_EMIT action is the source of the emitted signal.
Parameters
obj Object being edited.
prog The name of the program to set the state2.
state2 The name of the state to set.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_state_get()
EAPI const char* edje_edit_program_state_get (Evas_Object * obj, const char * prog)
Get the state for the given program.
In a STATE_SET action this is the name of state to set. In a SIGNAL_EMIT action is the name of the signal to emit.
Parameters
obj Object being edited.
prog The name of the program to get the state.
Returns
The name of the state.
References GET_EPR_OR_RETURN, and _Edje_Program::state.
edje_edit_program_state_set()
EAPI Eina_Bool edje_edit_program_state_set (Evas_Object * obj, const char * prog, const char * state)
Set the state for the given program.
In a STATE_SET action this is the name of state to set. In a SIGNAL_EMIT action is the name of the signal to emit.
Parameters
obj Object being edited.
prog The name of the program to set a state.
state The nameo of the state to set (not including the state value)
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_target_add()
EAPI Eina_Bool edje_edit_program_target_add (Evas_Object * obj, const char * prog, const char * target)
Add a new target program to the list of 'targets' in the given program.
If program action is EDJE_ACTION_TYPE_ACTION_STOP, then 'target' must be an existing program name. If it's EDJE_ACTION_TYPE_STATE_SET, then 'target' must be an existing part name.
Parameters
obj Object being edited.
prog The name of the program to add a new target.
target The name of the new target itself.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_real_part_get(), _Edje_Program::action, EDJE_ACTION_TYPE_ACTION_STOP, EDJE_ACTION_TYPE_STATE_SET, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Part::id, and _Edje_Real_Part::part.
edje_edit_program_target_del()
EAPI Eina_Bool edje_edit_program_target_del (Evas_Object * obj, const char * prog, const char * target)
Deletes a target from the list of 'targets' in the given program.
If program action is EDJE_ACTION_TYPE_ACTION_STOP then 'target' must be an existing program name. If action is EDJE_ACTION_TYPE_STATE_SET then 'target' must be an existing part name.
Parameters
obj Object being edited.
prog The name of the program to del a target from the list of targets.
target The name of another program or another part.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_real_part_get(), _Edje_Program::action, EDJE_ACTION_TYPE_ACTION_STOP, EDJE_ACTION_TYPE_STATE_SET, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Part::id, and _Edje_Real_Part::part.
edje_edit_program_targets_clear()
EAPI Eina_Bool edje_edit_program_targets_clear (Evas_Object * obj, const char * prog)
Clear the 'targets' list of the given program.
Parameters
obj Object being edited.
prog The name of the program to cleaar the 'targets' list.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN, and _Edje_Program::targets.
edje_edit_program_targets_get()
EAPI Eina_List* edje_edit_program_targets_get (Evas_Object * obj, const char * prog)
Get the list of the targets for the given program.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
prog The name of the progrem to get the list of the targets.
Returns
A list with all the targets names, or NULL on error.
References _Edje_Program::action, EDJE_ACTION_TYPE_ACTION_STOP, EDJE_ACTION_TYPE_STATE_SET, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Program_Target::id, _Edje_Program::name, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, _Edje::table_parts_size, _Edje::table_programs, _Edje::table_programs_size, and _Edje_Program::targets.
edje_edit_program_transition_get()
EAPI Edje_Tween_Mode edje_edit_program_transition_get (Evas_Object * obj, const char * prog)
Get the type of transition to use when apply animations.
Can be one of: EDJE_TWEEN_MODE_NONE, EDJE_TWEEN_MODE_LINEAR, EDJE_TWEEN_MODE_SINUSOIDAL, EDJE_TWEEN_MODE_ACCELERATE or EDJE_TWEEN_MODE_DECELERATE.
Parameters
obj Object being edited.
prog The name of the program to get the transition.
Returns
The type of transition used by program.
References GET_EPR_OR_RETURN, _Edje_Program::mode, and _Edje_Program::tween.
edje_edit_program_transition_set()
EAPI Eina_Bool edje_edit_program_transition_set (Evas_Object * obj, const char * prog, Edje_Tween_Mode transition)
Set the type of transition to use when apply animations.
Can be one of: EDJE_TWEEN_MODE_NONE, EDJE_TWEEN_MODE_LINEAR, EDJE_TWEEN_MODE_SINUSOIDAL, EDJE_TWEEN_MODE_ACCELERATE or EDJE_TWEEN_MODE_DECELERATE.
Parameters
obj Object being edited.
prog The name of the program to set the transition.
transition The transition type to set
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN, _Edje_Program::mode, and _Edje_Program::tween.
edje_edit_program_transition_time_get()
EAPI double edje_edit_program_transition_time_get (Evas_Object * obj, const char * prog)
Get the duration of the transition in seconds.
Parameters
obj Object being edited.
prog The name of the program to get the transition time.
Returns
The duration of the transition.
References GET_EPR_OR_RETURN, _Edje_Program::time, TO_DOUBLE, and _Edje_Program::tween.
edje_edit_program_transition_time_set()
EAPI Eina_Bool edje_edit_program_transition_time_set (Evas_Object * obj, const char * prog, double seconds)
Set the duration of the transition in seconds.
Parameters
obj Object being edited.
prog The name of the program to set the transition time.
seconds The duration of the transition (in seconds).
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References FROM_DOUBLE, GET_EPR_OR_RETURN, _Edje_Program::time, and _Edje_Program::tween.
edje_edit_program_value2_get()
EAPI double edje_edit_program_value2_get (Evas_Object * obj, const char * prog)
Get the value of state2 for the given program.
Parameters
obj Object being edited.
prog The name of the program to get the state2 value.
Returns
The vale of the state2 for the program.
References GET_EPR_OR_RETURN, and _Edje_Program::value2.
edje_edit_program_value2_set()
EAPI Eina_Bool edje_edit_program_value2_set (Evas_Object * obj, const char * prog, double value)
Set the value2 of state for the given program.
This is used in DRAG_ACTION
Parameters
obj Object being edited.
prog The name of the program to set the state2 value.
value The value of the state2 to set.
References GET_EPR_OR_RETURN, and _Edje_Program::value2.
edje_edit_program_value_get()
EAPI double edje_edit_program_value_get (Evas_Object * obj, const char * prog)
Get the value of state for the given program.
In a STATE_SET action this is the value of state to set. Not used on SIGNAL_EMIT action.
Parameters
obj Object being edited.
prog The name of the program to get the value of state.
Returns
The value of state for the program.
References GET_EPR_OR_RETURN, and _Edje_Program::value.
edje_edit_program_value_set()
EAPI Eina_Bool edje_edit_program_value_set (Evas_Object * obj, const char * prog, double value)
Set the value of state for the given program.
In a STATE_SET action this is the value of state to set. Not used on SIGNAL_EMIT action.
Parameters
obj Object being edited.
prog The name of the program to set the value of state.
value The vale to set.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN, and _Edje_Program::value.
edje_edit_programs_list_get()
EAPI Eina_List* edje_edit_programs_list_get (Evas_Object * obj)
Get the list of all the programs in the given edje object.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
Returns
A list containing all the program names.
References GET_ED_OR_RETURN, _Edje_Program::name, _Edje::table_programs, and _Edje::table_programs_size.
edje_edit_save()
EAPI Eina_Bool edje_edit_save (Evas_Object * obj)
Save the modified edje object back to his file.
Use this function when you are done with your editing, all the change made to the current loaded group will be saved back to the original file.
Note
Source for the whole file will be auto generated and will overwrite any previously stored source.
Parameters
obj Object to save back to the file it was loaded from.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Todo:
Add a way to check what the error actually was, the way Edje Load does.
References _edje_edit_internal_save().
edje_edit_save_all()
EAPI Eina_Bool edje_edit_save_all (Evas_Object * obj)
Saves every group back into the file.
Parameters
obj Object to save.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
See also
edje_edit_save()
References _edje_edit_internal_save().
edje_edit_script_compile()
EAPI Eina_Bool edje_edit_script_compile (Evas_Object * obj)
Compile the Embryo script for the given object.
If required, this function will process all script code for the group and build the bytecode, updating the running Embryo VM Program if the build is succesful.
Parameters
obj The object being edited
References GET_EED_OR_RETURN, and _Edje_Edit::script_need_recompile.
edje_edit_script_error_list_get()
EAPI const Eina_List* edje_edit_script_error_list_get (Evas_Object * obj)
Get the list of errors resulting from the last script build.
Get the list of errors that resulted from the last attempt to rebuild the Embryo script for the edited group. This will be a standard Eina_List with Edje_Edit_Script_Error pointers as its data. The user should not do anything else but read the contents of this list. These errors can be the output of the embryo compiler, or internal errors generated by Edje_Edit if the preprocessing of the scripts failed.
Parameters
obj The object being edited
Returns
A constant list of Edje_Edit_Script_Error, or NULL if there are none
References _Edje_Edit::errors, and GET_EED_OR_RETURN.
edje_edit_script_get()
EAPI char* edje_edit_script_get (Evas_Object * obj)
Get the Embryo script for the group of the given object.
Get the shared script for the group under edition. Shared script means the script {} block for the group, not counting what's in each program. It returns a malloc'd duplicate of the code, so users are free to modify the contents directly and they should remember to free() it when done. NULL will be returned if there's no script or an error occurred.
Parameters
obj Object being edited.
Returns
The shared script code for this group.
References _Edje::collection, _Edje_Edit::embryo_source, and GET_ED_OR_RETURN.
edje_edit_script_program_get()
EAPI char* edje_edit_script_program_get (Evas_Object * obj, const char * prog)
Get the Embryo script for the given program.
Get the script code for the given program. Like the group script, this function returns a duplicate of the code that the user can modify at will and must free when done using it. NULL will be returned if the program doesn't exist, doesn't have any script or is not of type script.
Parameters
obj Object being edited
prog Program name
Returns
The program script code
References _Edje_Program::action, _Program_Script::code, EDJE_ACTION_TYPE_SCRIPT, GET_EED_OR_RETURN, GET_EPR_OR_RETURN, and _Edje_Edit::program_scripts.
edje_edit_script_program_set()
EAPI void edje_edit_script_program_set (Evas_Object * obj, const char * prog, const char * code)
Set the Embryo script for the given program.
Set the Embryo source code for the program prog. It must be an existing program of type EDJE_ACTION_TYPE_SCRIPT, or the function will fail and do nothing. Note that changing the code itself will not update the running VM, you need to call edje_edit_script_compile for it to get updated.
Parameters
obj The object being edited
prog The program name.
code The Embryo source
References _Edje_Program::action, _Program_Script::code, _Program_Script::dirty, EDJE_ACTION_TYPE_SCRIPT, GET_EED_OR_RETURN, GET_EPR_OR_RETURN, _Program_Script::processed, and _Edje_Edit::program_scripts.
edje_edit_script_set()
EAPI void edje_edit_script_set (Evas_Object * obj, const char * code)
Set the code for the group script.
Set the Embryo source code for the shared script of the edited group. Note that changing the code itself will not update the running VM, you need to call edje_edit_script_compile for it to get updated.
Parameters
obj The object being edited
code The Embryo source
References _Edje_Edit::embryo_processed, _Edje_Edit::embryo_source, _Edje_Edit::embryo_source_dirty, and GET_EED_OR_RETURN.
edje_edit_state_add()
EAPI Eina_Bool edje_edit_state_add (Evas_Object * obj, const char * part, const char * name, double value)
Create a new state to the give part.
Parameters
obj Object being edited.
part Part to set the name of the new state.
name Name for the new state (not including the state value).
value The state value.
Returns
EINA_TRUE if successfully, EINA_FALSE otherwise.
References edje_edit_state_exist(), GET_RP_OR_RETURN, and name.
edje_edit_state_aspect_pref_get()
EAPI unsigned char edje_edit_state_aspect_pref_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the aspect preference of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get aspect preference (not including the state value).
value The state value.
Returns
The aspect preference (0 = None, 1 = Vertical, 2 = Horizontal, 3 = Both)
References _Edje_Part_Description_Common::aspect, GET_PD_OR_RETURN, and _Edje_Aspect_Prefer::prefer.
edje_edit_state_aspect_pref_set()
EAPI void edje_edit_state_aspect_pref_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char pref)
Set the aspect preference of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set aspect preference (not including the state value).
value The state value.
pref The aspect preference to set (0 = None, 1 = Vertical, 2 = Horizontal, 3 = Both)
References _Edje_Part_Description_Common::aspect, GET_PD_OR_RETURN, and _Edje_Aspect_Prefer::prefer.
edje_edit_state_color3_get()
EAPI void edje_edit_state_color3_get (Evas_Object * obj, const char * part, const char * state, double value, int * r, int * g, int * b, int * a)
Get the color3 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color (not including the state value).
value The state value.
r A pointer to store the red value.
g A pointer to store the green value.
b A pointer to store the blue value.
a A pointer to store the alpha value.
References _Edje_Color::a, _Edje_Color::b, _Edje_Part_Description_Spec_Text::color3, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Color::g, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Color::r, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_color3_set()
EAPI void edje_edit_state_color3_set (Evas_Object * obj, const char * part, const char * state, double value, int r, int g, int b, int a)
Set the color3 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color (not including the state value).
value The state value.
r The red value of the color.
g The green value of the color.
b The blue value of the color.
a The alpha value of the color.
References _Edje_Color::a, _Edje_Color::b, _Edje_Part_Description_Spec_Text::color3, edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Color::g, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Color::r, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_color_class_get()
EAPI const char* edje_edit_state_color_class_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the color class of the given part state.
Remember to free the string with edje_edit_string_free()
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color class (not including the state value).
value The state value.
Returns
The current color class.
References _Edje_Part_Description_Common::color_class, and GET_PD_OR_RETURN.
edje_edit_state_color_class_set()
EAPI void edje_edit_state_color_class_set (Evas_Object * obj, const char * part, const char * state, double value, const char * color_class)
Set the color class of the given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color class (not including the state value).
value The state value.
color_class The color class to assign.
References GET_PD_OR_RETURN.
edje_edit_state_copy()
EAPI Eina_Bool edje_edit_state_copy (Evas_Object * obj, const char * part, const char * from, double val_from, const char * to, double val_to)
Copies the state from into to.
If to doesn't exist it will be created.
Parameters
obj Object being edited.
part Part that contain state.
from State to copy from (not including state value).
val_from The value of the state to copy from.
to State to copy into (not including state value).
val_to The value of the state to copy into.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_RP_OR_RETURN.
edje_edit_state_del()
EAPI Eina_Bool edje_edit_state_del (Evas_Object * obj, const char * part, const char * state, double value)
Delete the given part state from the edje.
Parameters
obj Object being edited.
part Part that contain state.
state The current name of the state (not including the state value).
value The state value.
Returns
EINA_TRUE if successfully, EINA_FALSE otherwise.
References edje_edit_state_exist(), and GET_RP_OR_RETURN.
edje_edit_state_exist()
EAPI Eina_Bool edje_edit_state_exist (Evas_Object * obj, const char * part, const char * state, double value)
Check if a part state with the given name exist.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to check (not including the state value).
value The state value.
Returns
EINA_TRUE if the part state exist, EINA_FALSE otherwise.
References GET_PD_OR_RETURN.
Referenced by edje_edit_state_add(), and edje_edit_state_del().
edje_edit_state_external_param_bool_get()
EAPI Eina_Bool edje_edit_state_external_param_bool_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Eina_Bool * val)
Get external parameter of type BOOL.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type BOOL (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::i, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_bool_set()
EAPI Eina_Bool edje_edit_state_external_param_bool_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Eina_Bool val)
Set external parameter of type BOOL.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type BOOL (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_BOOL.
edje_edit_state_external_param_choice_get()
EAPI Eina_Bool edje_edit_state_external_param_choice_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char ** val)
Get external parameter of type CHOICE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type CHOICE (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::s, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_choice_set()
EAPI Eina_Bool edje_edit_state_external_param_choice_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char * val)
Set external parameter of type CHOICE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type CHOICE (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_CHOICE.
edje_edit_state_external_param_double_get()
EAPI Eina_Bool edje_edit_state_external_param_double_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, double * val)
Get external parameter of type DOUBLE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type DOUBLE (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References _Edje_External_Param::d, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_double_set()
EAPI Eina_Bool edje_edit_state_external_param_double_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, double val)
Set external parameter of type DOUBLE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type DOUBLE (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_DOUBLE.
edje_edit_state_external_param_get()
EAPI Eina_Bool edje_edit_state_external_param_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Edje_External_Param_Type * type, void ** val)
Get the external parameter type and value.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter (not including the state value).
value The state value.
param The name of the paramter to look for.
type The type of the parameter will be stored here.
val Pointer to value will be stored here - DO NOT FREE IT!
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
References _Edje_External_Param::d, EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_EXTERNAL_PARAM_TYPE_STRING, EDJE_PART_TYPE_EXTERNAL, ERR, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::i, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::s, _Edje_External_Param::type, type, and _Edje_Part::type.
edje_edit_state_external_param_int_get()
EAPI Eina_Bool edje_edit_state_external_param_int_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, int * val)
Get external parameter of type INT.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type INT (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::i, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_int_set()
EAPI Eina_Bool edje_edit_state_external_param_int_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, int val)
Set external parameter of type INT.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type INT (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_INT.
edje_edit_state_external_param_set()
EAPI Eina_Bool edje_edit_state_external_param_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Edje_External_Param_Type type, ...)
Set the external parameter type and value, adding it if it didn't exist before.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter (not including the state value).
value The state value.
param The name of the paramter set.
type The type of the parameter.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise. Arguments should have proper sized values matching their types:
EDJE_EXTERNAL_PARAM_TYPE_INT: int
EDJE_EXTERNAL_PARAM_TYPE_BOOL: int
EDJE_EXTERNAL_PARAM_TYPE_DOUBLE: double
EDJE_EXTERNAL_PARAM_TYPE_STRING: char*
EDJE_EXTERNAL_PARAM_TYPE_CHOICE: char*
Note
: The validation of the parameter will occur only if the part is in the same state as the one being modified.
References EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::name, _Edje_Real_Part::part, type, and _Edje_Part::type.
Referenced by edje_edit_state_external_param_bool_set(), edje_edit_state_external_param_choice_set(), edje_edit_state_external_param_double_set(), edje_edit_state_external_param_int_set(), and edje_edit_state_external_param_string_set().
edje_edit_state_external_param_string_get()
EAPI Eina_Bool edje_edit_state_external_param_string_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char ** val)
Get external parameter of type STRING.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type STRING (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_STRING, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::s, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_string_set()
EAPI Eina_Bool edje_edit_state_external_param_string_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char * val)
Set external parameter of type STRING.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type STRING (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_STRING.
edje_edit_state_external_params_list_get()
EAPI const Eina_List* edje_edit_state_external_params_list_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the list of parameters for an external part.
DO NOT FREE THE LIST!
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get list of Edje_External_Param (not including the state value).
value The state value.
Returns
The list of Edje_External_Param.
References EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_font_get()
EAPI const char * edje_edit_state_font_get (Evas_Object * obj, const char * part, const char * state, double value)
Get font name for a given part state.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the name of the font used (not including the state value).
value The state value.
Returns
The name of the font used in the given part state.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, edje_string_get(), _Edje_Part_Description_Spec_Text::font, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_font_set()
EAPI void edje_edit_state_font_set (Evas_Object * obj, const char * part, const char * state, double value, const char * font)
Set font name for a given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the name of the font that will be used (not including the state value).
value The state value.
font The name of the font to use in the given part state.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_image_border_fill_get()
EAPI unsigned char edje_edit_state_image_border_fill_get (Evas_Object * obj, const char * part, const char * state, double value)
Get if the image center should be draw.
1 means to draw the center, 0 to don't draw it.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the image border fill (not including the state value).
value The state value.
Returns
1 if the center of the bordered image is draw, 0 otherwise.
References _Edje_Part_Description_Spec_Image::border, EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Part_Description_Spec_Border::no_fill, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_image_border_fill_set()
EAPI void edje_edit_state_image_border_fill_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char fill)
Set if the image center should be draw.
1 means to draw the center, 0 to don't draw it.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image border fill (not including the state value).
value The state value.
fill Fill to be se. 1 if the center of the bordered image is draw, 0 otherwise.
References _Edje_Part_Description_Spec_Image::border, edje_object_calc_force(), EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Part_Description_Spec_Border::no_fill, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_image_border_get()
EAPI void edje_edit_state_image_border_get (Evas_Object * obj, const char * part, const char * state, double value, int * l, int * r, int * t, int * b)
Get the image border of a part state.
Pass NULL to any of [r,g,b,a] to get only the others.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the image border (not including the state value).
value The state value.
l A pointer to store the left value
r A pointer to store the right value
t A pointer to store the top value
b A pointer to store the bottom value
References _Edje_Part_Description_Spec_Border::b, _Edje_Part_Description_Spec_Image::border, EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Part_Description_Spec_Border::l, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Border::r, _Edje_Part_Description_Spec_Border::t, and _Edje_Part::type.
edje_edit_state_image_border_set()
EAPI void edje_edit_state_image_border_set (Evas_Object * obj, const char * part, const char * state, double value, int l, int r, int t, int b)
Set the image border of a part state.
Pass -1 to any of [l,r,t,b] to leave the value untouched.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image border (not including the state value).
value The state value.
l Left border value (or -1).
r Right border value (or -1).
t Top border value (or -1).
b Bottom border value (or -1).
References _Edje_Part_Description_Spec_Border::b, _Edje_Part_Description_Spec_Image::border, edje_object_calc_force(), EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Part_Description_Spec_Border::l, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Border::r, _Edje_Part_Description_Spec_Border::t, and _Edje_Part::type.
edje_edit_state_image_get()
EAPI const char* edje_edit_state_image_get (Evas_Object * obj, const char * part, const char * state, double value)
Get normal image name for a given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the name that is being used (not including the state value).
value The state value.
Returns
The name of the image used by state.
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_image_set()
EAPI void edje_edit_state_image_set (Evas_Object * obj, const char * part, const char * state, double value, const char * image)
Set normal image for a given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image that will be used (not including the state value).
value The state value.
image The name of the image (must be an image contained in the edje file).
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_name_set()
EAPI Eina_Bool edje_edit_state_name_set (Evas_Object * obj, const char * part, const char * state, double value, const char * new_name, double new_value)
Set a new name for the given state in the given part.
Parameters
obj Object being edited.
part Part that contain state.
state Name of the state to rename.
value Value of the state to rename.
new_name The new name for the state.
new_value The new value for the state.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_PD_OR_RETURN.
edje_edit_state_text_get()
EAPI const char* edje_edit_state_text_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the text of a part state.
Remember to free the returned string with edje_edit_string_free().
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get text (not including the state value).
value The state value.
Returns
A newly allocated string containing the text for the given state.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, edje_string_get(), GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Text::text, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_text_set()
EAPI void edje_edit_state_text_set (Evas_Object * obj, const char * part, const char * state, double value, const char * text)
Set the text of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set text (not including the state value).
value The state value.
text The new text to assign.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_text_size_get()
EAPI int edje_edit_state_text_size_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the text size of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get text size (not including the state value).
value The state value.
Returns
The text size or -1 on errors.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Text::size, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_text_size_set()
EAPI void edje_edit_state_text_size_set (Evas_Object * obj, const char * part, const char * state, double value, int size)
Set the text size of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set text size (not including the state value).
value The state value.
size The new font size to set (in pixel)
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Text::size, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_tween_add()
EAPI Eina_Bool edje_edit_state_tween_add (Evas_Object * obj, const char * part, const char * state, double value, const char * tween)
Add a new tween frame to the given part state.
The tween param must be the name of an existing image.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to add a new tween frame (not including the state value).
value The state value.
tween The name of the image to add.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_tween_del()
EAPI Eina_Bool edje_edit_state_tween_del (Evas_Object * obj, const char * part, const char * state, double value, const char * tween)
Remove the first tween with the given name.
The image is not removed from the edje.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to del the tween (not including the state value).
value The state value.
tween The name of the image to del.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Image::tweens_count, and _Edje_Part::type.
edje_edit_state_tweens_list_get()
EAPI Eina_List* edje_edit_state_tweens_list_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the list of all the tweens images in the given part state.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the list of all the tweens images (not including the state value).
value The state value.
Returns
A string list containing all the image name that form a tween animation in the given part state.
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, name, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Image::tweens_count, and _Edje_Part::type.
edje_edit_state_visible_get()
EAPI Eina_Bool edje_edit_state_visible_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the visibility of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get visibility (not including the state value).
value The state value.
Returns
EINA_TRUE if the state is visible, EINA_FALSE otherwise.
References GET_PD_OR_RETURN, and _Edje_Part_Description_Common::visible.
edje_edit_state_visible_set()
EAPI void edje_edit_state_visible_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool visible)
Set the visibility of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set visibility (not including the state value).
value The state value.
visible To set state visible (EINA_TRUE if the state is visible, EINA_FALSE otherwise)
References edje_object_calc_force(), GET_PD_OR_RETURN, and _Edje_Part_Description_Common::visible.
edje_edit_string_free()
EAPI void edje_edit_string_free (const char * str)
Free a generic string (char *) allocated by an edje_edit_*_get() function.
Parameters
str String to free.
edje_edit_string_list_free()
EAPI void edje_edit_string_list_free (Eina_List * lst)
Free a generic Eina_List of (char *) allocated by an edje_edit_*_get() function.
Parameters
lst List of strings to free.
edje_edit_style_add()
EAPI Eina_Bool edje_edit_style_add (Evas_Object * obj, const char * style)
Create a new text style object in the given edje.
If another style with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
style Name for the new style.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_style_del()
EAPI void edje_edit_style_del (Evas_Object * obj, const char * style)
Delete the given text style and all the child tags.
Parameters
obj Object being edited.
style Style to delete.
References GET_ED_OR_RETURN.
edje_edit_style_tag_add()
EAPI Eina_Bool edje_edit_style_tag_add (Evas_Object * obj, const char * style, const char * tag_name)
Add a new tag to the given text style.
If another tag with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
style Style where to add the new tag.
tag_name Name for the new tag.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_style_tag_del()
EAPI void edje_edit_style_tag_del (Evas_Object * obj, const char * style, const char * tag)
Delete the given tag.
Parameters
obj Object being edited.
style Style from where to remove the tag.
tag Tag to delete.
References GET_ED_OR_RETURN.
edje_edit_style_tag_name_set()
EAPI void edje_edit_style_tag_name_set (Evas_Object * obj, const char * style, const char * tag, const char * new_name)
Set the name of the given tag.
Parameters
obj Object being edited.
style Style containing the tag to rename.
tag Tag to rename.
new_name New name for the tag.
References _Edje::file, GET_ED_OR_RETURN, and _Edje_File::styles.
edje_edit_style_tag_value_get()
EAPI const char* edje_edit_style_tag_value_get (Evas_Object * obj, const char * style, const char * tag)
Get the value of the given tag.
Parameters
obj Object being edited.
style Style containing the tag being.
tag Tag to get the value for.
Returns
Value of the given tag.
References _Edje::file, GET_ED_OR_RETURN, and _Edje_File::styles.
edje_edit_style_tag_value_set()
EAPI void edje_edit_style_tag_value_set (Evas_Object * obj, const char * style, const char * tag, const char * new_value)
Set the value of the given tag.
Parameters
obj Object being edited.
style Style containing the tag to change.
tag Name of the tag to set the value for.
new_value Value for the tag.
References _Edje::file, GET_ED_OR_RETURN, and _Edje_File::styles.
edje_edit_style_tags_list_get()
EAPI Eina_List* edje_edit_style_tags_list_get (Evas_Object * obj, const char * style)
Get the list of all the tags name in the given text style.
Parameters
obj Object being edited.
style Style to get the tags for.
Returns
List of strings, each being one tag in the given style.
References _Edje::file, GET_ED_OR_RETURN, and _Edje_File::styles.
edje_edit_styles_list_get()
EAPI Eina_List* edje_edit_styles_list_get (Evas_Object * obj)
Get the list of all the text styles in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being the name for a text style.
References _Edje::file, GET_ED_OR_RETURN, _Edje_Style::name, and _Edje_File::styles.
EVAS_SMART_SUBCLASS_NEW()
EVAS_SMART_SUBCLASS_NEW (_edje_edit_type , _edje_edit , Edje_Smart_Api , Edje_Smart_Api , _edje_object_smart_class_get , NULL)
FUNC_COLOR() [1/2]
FUNC_COLOR (color)
FUNC_COLOR() [2/2]
FUNC_COLOR (color2)
FUNC_GROUP_ACCESSOR() [1/4]
FUNC_GROUP_ACCESSOR (max , h)
FUNC_GROUP_ACCESSOR() [2/4]
FUNC_GROUP_ACCESSOR (max , w)
FUNC_GROUP_ACCESSOR() [3/4]
FUNC_GROUP_ACCESSOR (min , h)
FUNC_GROUP_ACCESSOR() [4/4]
FUNC_GROUP_ACCESSOR (min , w)
FUNC_PART_API_STRING() [1/2]
FUNC_PART_API_STRING (description)
FUNC_PART_API_STRING() [2/2]
FUNC_PART_API_STRING (name)
FUNC_PART_DRAG_ID() [1/2]
FUNC_PART_DRAG_ID (confine)
FUNC_PART_DRAG_ID() [2/2]
FUNC_PART_DRAG_ID (event)
FUNC_PART_DRAG_INT() [1/4]
FUNC_PART_DRAG_INT (count , x)
FUNC_PART_DRAG_INT() [2/4]
FUNC_PART_DRAG_INT (count , y)
FUNC_PART_DRAG_INT() [3/4]
FUNC_PART_DRAG_INT (step , x)
FUNC_PART_DRAG_INT() [4/4]
FUNC_PART_DRAG_INT (step , y)
FUNC_STATE_DOUBLE() [1/4]
FUNC_STATE_DOUBLE (align , x)
FUNC_STATE_DOUBLE() [2/4]
FUNC_STATE_DOUBLE (align , y)
FUNC_STATE_DOUBLE() [3/4]
FUNC_STATE_DOUBLE (aspect , max)
FUNC_STATE_DOUBLE() [4/4]
FUNC_STATE_DOUBLE (aspect , min)
FUNC_STATE_DOUBLE_FILL() [1/4]
FUNC_STATE_DOUBLE_FILL (size , x)
FUNC_STATE_DOUBLE_FILL() [2/4]
FUNC_STATE_DOUBLE_FILL (size , y)
FUNC_STATE_DOUBLE_FILL() [3/4]
FUNC_STATE_DOUBLE_FILL (pos_ , origin , x)
FUNC_STATE_DOUBLE_FILL() [4/4]
FUNC_STATE_DOUBLE_FILL (pos_ , origin , y)
FUNC_STATE_INT() [1/4]
FUNC_STATE_INT (max , h)
FUNC_STATE_INT() [2/4]
FUNC_STATE_INT (max , w)
FUNC_STATE_INT() [3/4]
FUNC_STATE_INT (min , h)
FUNC_STATE_INT() [4/4]
FUNC_STATE_INT (min , w)
FUNC_STATE_INT_FILL() [1/4]
FUNC_STATE_INT_FILL (size , x)
FUNC_STATE_INT_FILL() [2/4]
FUNC_STATE_INT_FILL (size , y)
FUNC_STATE_INT_FILL() [3/4]
FUNC_STATE_INT_FILL (pos_ , origin , x)
FUNC_STATE_INT_FILL() [4/4]
FUNC_STATE_INT_FILL (pos_ , origin , y)
FUNC_STATE_OFFSET_INT() [1/4]
FUNC_STATE_OFFSET_INT (rel1 , x)
FUNC_STATE_OFFSET_INT() [2/4]
FUNC_STATE_OFFSET_INT (rel1 , y)
FUNC_STATE_OFFSET_INT() [3/4]
FUNC_STATE_OFFSET_INT (rel2 , x)
FUNC_STATE_OFFSET_INT() [4/4]
FUNC_STATE_OFFSET_INT (rel2 , y)
FUNC_STATE_REL() [1/4]
FUNC_STATE_REL (rel1 , x)
FUNC_STATE_REL() [2/4]
FUNC_STATE_REL (rel1 , y)
FUNC_STATE_REL() [3/4]
FUNC_STATE_REL (rel2 , x)
FUNC_STATE_REL() [4/4]
FUNC_STATE_REL (rel2 , y)
FUNC_STATE_RELATIVE_DOUBLE() [1/4]
FUNC_STATE_RELATIVE_DOUBLE (rel1 , x)
FUNC_STATE_RELATIVE_DOUBLE() [2/4]
FUNC_STATE_RELATIVE_DOUBLE (rel1 , y)
FUNC_STATE_RELATIVE_DOUBLE() [3/4]
FUNC_STATE_RELATIVE_DOUBLE (rel2 , x)
FUNC_STATE_RELATIVE_DOUBLE() [4/4]
FUNC_STATE_RELATIVE_DOUBLE (rel2 , y)
FUNC_TEXT_BOOL_FIT() [1/2]
FUNC_TEXT_BOOL_FIT (x)
FUNC_TEXT_BOOL_FIT() [2/2]
FUNC_TEXT_BOOL_FIT (y)
FUNC_TEXT_DOUBLE() [1/3]
FUNC_TEXT_DOUBLE (align_x , align. x)
FUNC_TEXT_DOUBLE() [2/3]
FUNC_TEXT_DOUBLE (align_y , align. y)
FUNC_TEXT_DOUBLE() [3/3]
FUNC_TEXT_DOUBLE (elipsis , elipsis)
Variable Documentation
EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED = 0
Referenced by edje_edit_group_del().
EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST = 0
Referenced by edje_edit_group_del(), and edje_edit_object_add().
EDJE_EDIT_ERROR_GROUP_REFERENCED
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_REFERENCED = 0
Referenced by edje_edit_group_del().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59