src/lib/Edje.h File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
Edje.h File Reference
Edje Graphical Design Library.
Data Structures
struct _Edje_Entry_Change_Info
struct _Edje_External_Param
Struct that holds parameters for parts of type EXTERNAL.
struct _Edje_External_Param_Info
Struct holding information about an EXTERNAL part's parameters.
struct _Edje_External_Type
Information about an external type to be used.
struct _Edje_External_Type_Info
Convenience struct used to mass-register types of EXTERNAL objects.
struct _Edje_Message_Float
Structure passed as value on EDJE_MESSAGE_FLOAT messages.
struct _Edje_Message_Float_Set
Structure passed as value on EDJE_MESSAGE_FLOAT_SET messages.
struct _Edje_Message_Int
Structure passed as value on EDJE_MESSAGE_INT messages.
struct _Edje_Message_Int_Set
Structure passed as value on EDJE_MESSAGE_INT_SET messages.
struct _Edje_Message_String
Structure passed as value on EDJE_MESSAGE_STRING messages.
struct _Edje_Message_String_Float
Structure passed as value on EDJE_MESSAGE_STRING_FLOAT messages.
struct _Edje_Message_String_Float_Set
Structure passed as value on EDJE_MESSAGE_STRING_FLOAT_SET messages.
struct _Edje_Message_String_Int
Structure passed as value on EDJE_MESSAGE_STRING_INT messages.
struct _Edje_Message_String_Int_Set
Structure passed as value on EDJE_MESSAGE_STRING_INT_SET messages.
struct _Edje_Message_String_Set
Structure passed as value on EDJE_MESSAGE_STRING_SET messages.
struct _Edje_Version
Macros
#define EAPI
#define EDJE_EXTERNAL_DOUBLE_UNSET DBL_MAX
Helper macro to indicate an EXTERNAL's double parameter is undefined.
#define EDJE_EXTERNAL_INT_UNSET INT_MAX
Helper macro to indicate an EXTERNAL's integer parameter is undefined.
#define EDJE_EXTERNAL_PARAM_INFO_BOOL(name) EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT(name, 0)
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT(name, def) EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL(name, def, "false", "true")
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT_FLAGS(name, def, flags) EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL_FLAGS(name, def, "false", "true", flags)
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_FLAGS(name, flags) EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT_FLAGS(name, 0, flags)
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL(name, def, false_str, true_str) EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL_FLAGS(name, def, false_str, true_str, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL_FLAGS(name, def, false_str, true_str, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_BOOL, flags, {.b = {def, false_str, true_str}}}
#define EDJE_EXTERNAL_PARAM_INFO_CHOICE_DYNAMIC_FULL(name, def_get, query) EDJE_EXTERNAL_PARAM_INFO_CHOICE_DYNAMIC_FULL_FLAGS(name, def_get, query, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
#define EDJE_EXTERNAL_PARAM_INFO_CHOICE_DYNAMIC_FULL_FLAGS(name, def_get, query, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, flags, {.c = {NULL, NULL, def_get, query}}}
#define EDJE_EXTERNAL_PARAM_INFO_CHOICE_FULL(name, def, choices) EDJE_EXTERNAL_PARAM_INFO_CHOICE_FULL_FLAGS(name, def, choices, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
#define EDJE_EXTERNAL_PARAM_INFO_CHOICE_FULL_FLAGS(name, def, choices, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, flags, {.c = {def, choices, NULL, NULL}}}
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE(name) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT(name, 0.0)
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT(name, def) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL(name, def, EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_DOUBLE_UNSET)
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT_FLAGS(name, def, flags) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL_FLAGS(name, def, EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_DOUBLE_UNSET, flags)
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FLAGS(name, flags) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT_FLAGS(name, 0.0, flags)
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL(name, def, min, max, step) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL_FLAGS(name, def, min, max, step, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL_FLAGS(name, def, min, max, step, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, flags, {.d = {def, min, max, step}}}
#define EDJE_EXTERNAL_PARAM_INFO_INT(name) EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT(name, 0)
#define EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT(name, def) EDJE_EXTERNAL_PARAM_INFO_INT_FULL(name, def, EDJE_EXTERNAL_INT_UNSET, EDJE_EXTERNAL_INT_UNSET, EDJE_EXTERNAL_INT_UNSET)
#define EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT_FLAGS(name, def, flags) EDJE_EXTERNAL_PARAM_INFO_INT_FULL_FLAGS(name, def, EDJE_EXTERNAL_INT_UNSET, EDJE_EXTERNAL_INT_UNSET, EDJE_EXTERNAL_INT_UNSET, flags)
#define EDJE_EXTERNAL_PARAM_INFO_INT_FLAGS(name, flags) EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT_FLAGS(name, 0, flags)
#define EDJE_EXTERNAL_PARAM_INFO_INT_FULL(name, def, min, max, step) EDJE_EXTERNAL_PARAM_INFO_INT_FULL_FLAGS(name, def, min, max, step, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
#define EDJE_EXTERNAL_PARAM_INFO_INT_FULL_FLAGS(name, def, min, max, step, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_INT, flags, {.i = {def, min, max, step}}}
#define EDJE_EXTERNAL_PARAM_INFO_SENTINEL {NULL, 0, 0, {.s = {NULL, NULL, NULL}}}
#define EDJE_EXTERNAL_PARAM_INFO_STRING(name) EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT(name, NULL)
#define EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT(name, def) EDJE_EXTERNAL_PARAM_INFO_STRING_FULL(name, def, NULL, NULL)
#define EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT_FLAGS(name, def, flags) EDJE_EXTERNAL_PARAM_INFO_STRING_FULL_FLAGS(name, def, NULL, NULL, flags)
#define EDJE_EXTERNAL_PARAM_INFO_STRING_FLAGS(name, flags) EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT_FLAGS(name, NULL, flags)
#define EDJE_EXTERNAL_PARAM_INFO_STRING_FULL(name, def, accept, deny) EDJE_EXTERNAL_PARAM_INFO_STRING_FULL_FLAGS(name, def, accept, deny, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
#define EDJE_EXTERNAL_PARAM_INFO_STRING_FULL_FLAGS(name, def, accept, deny, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_STRING, flags, {.s = {def, accept, deny}}}
#define EDJE_EXTERNAL_TYPE_ABI_VERSION (3)
#define EDJE_TEXT_EFFECT_BASIC_SET(x, s) do { x = ((x) & ~EDJE_TEXT_EFFECT_MASK_BASIC) | (s); } while (0)
#define EDJE_TEXT_EFFECT_MASK_BASIC 0xf
#define EDJE_TEXT_EFFECT_MASK_SHADOW_DIRECTION (0x7 << 4)
#define EDJE_TEXT_EFFECT_SHADOW_DIRECTION_SET(x, s) do { x = ((x) & ~EDJE_TEXT_EFFECT_MASK_SHADOW_DIRECTION) | (s); } while (0)
#define EDJE_VERSION_MAJOR 1
#define EDJE_VERSION_MINOR 7
Typedefs
typedef enum _Edje_Action_Type Edje_Action_Type
typedef enum _Edje_Aspect_Control Edje_Aspect_Control
typedef enum _Edje_Cursor Edje_Cursor
typedef enum _Edje_Drag_Dir Edje_Drag_Dir
typedef struct _Edje_Entry_Change_Info Edje_Entry_Change_Info
typedef struct _Edje_External_Param Edje_External_Param
Struct that holds parameters for parts of type EXTERNAL.
typedef enum _Edje_External_Param_Flags Edje_External_Param_Flags
Flags that determine how a parameter may be accessed in different circumstances.
typedef struct _Edje_External_Param_Info Edje_External_Param_Info
Struct holding information about an EXTERNAL part's parameters.
typedef enum _Edje_External_Param_Type Edje_External_Param_Type
The possible types the parameters of an EXTERNAL part can be.
typedef struct _Edje_External_Type Edje_External_Type
typedef struct _Edje_External_Type_Info Edje_External_Type_Info
typedef enum _Edje_Input_Panel_Lang Edje_Input_Panel_Lang
typedef enum _Edje_Input_Panel_Layout Edje_Input_Panel_Layout
typedef enum _Edje_Input_Panel_Return_Key_Type Edje_Input_Panel_Return_Key_Type
typedef Evas_Object *(* Edje_Item_Provider_Cb) (void *data, Evas_Object *obj, const char *part, const char *item)
typedef enum _Edje_Load_Error Edje_Load_Error
Edje file loading error codes one can get - see edje_load_error_str() too.
typedef void(* Edje_Markup_Filter_Cb) (void *data, Evas_Object *obj, const char *part, char **text)
typedef struct _Edje_Message_Float Edje_Message_Float
typedef struct _Edje_Message_Float_Set Edje_Message_Float_Set
typedef void(* Edje_Message_Handler_Cb) (void *data, Evas_Object *obj, Edje_Message_Type type, int id, void *msg)
Edje message handler callback functions's prototype definition.
typedef struct _Edje_Message_Int Edje_Message_Int
typedef struct _Edje_Message_Int_Set Edje_Message_Int_Set
typedef struct _Edje_Message_String Edje_Message_String
typedef struct _Edje_Message_String_Float Edje_Message_String_Float
typedef struct _Edje_Message_String_Float_Set Edje_Message_String_Float_Set
typedef struct _Edje_Message_String_Int Edje_Message_String_Int
typedef struct _Edje_Message_String_Int_Set Edje_Message_String_Int_Set
typedef struct _Edje_Message_String_Set Edje_Message_String_Set
typedef enum _Edje_Message_Type Edje_Message_Type
Identifiers of Edje message types, which can be sent back and forth code and a given Edje object's theme file/group.
typedef enum _Edje_Object_Table_Homogeneous_Mode Edje_Object_Table_Homogeneous_Mode
typedef enum _Edje_Part_Type Edje_Part_Type
typedef struct _Edje_Perspective Edje_Perspective
typedef void(* Edje_Signal_Cb) (void *data, Evas_Object *obj, const char *emission, const char *source)
Edje signal callback functions's prototype definition.
typedef enum _Edje_Text_Autocapital_Type Edje_Text_Autocapital_Type
typedef void(* Edje_Text_Change_Cb) (void *data, Evas_Object *obj, const char *part)
typedef enum _Edje_Text_Effect Edje_Text_Effect
typedef void(* Edje_Text_Filter_Cb) (void *data, Evas_Object *obj, const char *part, Edje_Text_Filter_Type type, char **text)
typedef enum _Edje_Text_Filter_Type Edje_Text_Filter_Type
typedef enum _Edje_Tween_Mode Edje_Tween_Mode
typedef struct _Edje_Version Edje_Version
Enumerations
enum _Edje_Action_Type {
EDJE_ACTION_TYPE_NONE = 0 , EDJE_ACTION_TYPE_STATE_SET = 1 , EDJE_ACTION_TYPE_ACTION_STOP = 2 , EDJE_ACTION_TYPE_SIGNAL_EMIT = 3 ,
EDJE_ACTION_TYPE_DRAG_VAL_SET = 4 , EDJE_ACTION_TYPE_DRAG_VAL_STEP = 5 , EDJE_ACTION_TYPE_DRAG_VAL_PAGE = 6 , EDJE_ACTION_TYPE_SCRIPT = 7 ,
EDJE_ACTION_TYPE_FOCUS_SET = 8 , EDJE_ACTION_TYPE_RESERVED00 = 9 , EDJE_ACTION_TYPE_FOCUS_OBJECT = 10 , EDJE_ACTION_TYPE_PARAM_COPY = 11 ,
EDJE_ACTION_TYPE_PARAM_SET = 12 , EDJE_ACTION_TYPE_SOUND_SAMPLE = 13 , EDJE_ACTION_TYPE_SOUND_TONE = 14 , EDJE_ACTION_TYPE_LAST = 15
}
enum _Edje_Aspect_Control {
EDJE_ASPECT_CONTROL_NONE = 0 , EDJE_ASPECT_CONTROL_NEITHER = 1 , EDJE_ASPECT_CONTROL_HORIZONTAL = 2 , EDJE_ASPECT_CONTROL_VERTICAL = 3 ,
EDJE_ASPECT_CONTROL_BOTH = 4
}
enum _Edje_Cursor {
EDJE_CURSOR_MAIN , EDJE_CURSOR_SELECTION_BEGIN , EDJE_CURSOR_SELECTION_END , EDJE_CURSOR_PREEDIT_START ,
EDJE_CURSOR_PREEDIT_END , EDJE_CURSOR_USER , EDJE_CURSOR_USER_EXTRA
}
enum _Edje_Drag_Dir { EDJE_DRAG_DIR_NONE = 0 , EDJE_DRAG_DIR_X = 1 , EDJE_DRAG_DIR_Y = 2 , EDJE_DRAG_DIR_XY = 3 }
enum _Edje_External_Param_Flags {
EDJE_EXTERNAL_PARAM_FLAGS_NONE = 0 , EDJE_EXTERNAL_PARAM_FLAGS_GET = (1 << 0) , EDJE_EXTERNAL_PARAM_FLAGS_SET = (1 << 1) , EDJE_EXTERNAL_PARAM_FLAGS_STATE = (1 << 2) ,
EDJE_EXTERNAL_PARAM_FLAGS_CONSTRUCTOR = (1 << 3) , EDJE_EXTERNAL_PARAM_FLAGS_REGULAR
}
Flags that determine how a parameter may be accessed in different circumstances.
enum _Edje_External_Param_Type {
EDJE_EXTERNAL_PARAM_TYPE_INT , EDJE_EXTERNAL_PARAM_TYPE_DOUBLE , EDJE_EXTERNAL_PARAM_TYPE_STRING , EDJE_EXTERNAL_PARAM_TYPE_BOOL ,
EDJE_EXTERNAL_PARAM_TYPE_CHOICE , EDJE_EXTERNAL_PARAM_TYPE_MAX
}
The possible types the parameters of an EXTERNAL part can be.
enum _Edje_Input_Panel_Lang { EDJE_INPUT_PANEL_LANG_AUTOMATIC , EDJE_INPUT_PANEL_LANG_ALPHABET }
enum _Edje_Input_Panel_Layout {
EDJE_INPUT_PANEL_LAYOUT_NORMAL , EDJE_INPUT_PANEL_LAYOUT_NUMBER , EDJE_INPUT_PANEL_LAYOUT_EMAIL , EDJE_INPUT_PANEL_LAYOUT_URL ,
EDJE_INPUT_PANEL_LAYOUT_PHONENUMBER , EDJE_INPUT_PANEL_LAYOUT_IP , EDJE_INPUT_PANEL_LAYOUT_MONTH , EDJE_INPUT_PANEL_LAYOUT_NUMBERONLY ,
EDJE_INPUT_PANEL_LAYOUT_INVALID , EDJE_INPUT_PANEL_LAYOUT_HEX , EDJE_INPUT_PANEL_LAYOUT_TERMINAL , EDJE_INPUT_PANEL_LAYOUT_PASSWORD
}
enum _Edje_Input_Panel_Return_Key_Type {
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DEFAULT , EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DONE , EDJE_INPUT_PANEL_RETURN_KEY_TYPE_GO , EDJE_INPUT_PANEL_RETURN_KEY_TYPE_JOIN ,
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_LOGIN , EDJE_INPUT_PANEL_RETURN_KEY_TYPE_NEXT , EDJE_INPUT_PANEL_RETURN_KEY_TYPE_SEARCH , EDJE_INPUT_PANEL_RETURN_KEY_TYPE_SEND
}
enum _Edje_Load_Error {
EDJE_LOAD_ERROR_NONE = 0 , EDJE_LOAD_ERROR_GENERIC = 1 , EDJE_LOAD_ERROR_DOES_NOT_EXIST = 2 , EDJE_LOAD_ERROR_PERMISSION_DENIED = 3 ,
EDJE_LOAD_ERROR_RESOURCE_ALLOCATION_FAILED = 4 , EDJE_LOAD_ERROR_CORRUPT_FILE = 5 , EDJE_LOAD_ERROR_UNKNOWN_FORMAT = 6 , EDJE_LOAD_ERROR_INCOMPATIBLE_FILE = 7 ,
EDJE_LOAD_ERROR_UNKNOWN_COLLECTION = 8 , EDJE_LOAD_ERROR_RECURSIVE_REFERENCE = 9
}
enum _Edje_Message_Type {
EDJE_MESSAGE_NONE = 0 , EDJE_MESSAGE_SIGNAL = 1 , EDJE_MESSAGE_STRING = 2 , EDJE_MESSAGE_INT = 3 ,
EDJE_MESSAGE_FLOAT = 4 , EDJE_MESSAGE_STRING_SET = 5 , EDJE_MESSAGE_INT_SET = 6 , EDJE_MESSAGE_FLOAT_SET = 7 ,
EDJE_MESSAGE_STRING_INT = 8 , EDJE_MESSAGE_STRING_FLOAT = 9 , EDJE_MESSAGE_STRING_INT_SET = 10 , EDJE_MESSAGE_STRING_FLOAT_SET = 11
}
Identifiers of Edje message types, which can be sent back and forth code and a given Edje object's theme file/group.
enum _Edje_Object_Table_Homogeneous_Mode { EDJE_OBJECT_TABLE_HOMOGENEOUS_NONE = 0 , EDJE_OBJECT_TABLE_HOMOGENEOUS_TABLE = 1 , EDJE_OBJECT_TABLE_HOMOGENEOUS_ITEM = 2 }
enum _Edje_Part_Type {
EDJE_PART_TYPE_NONE = 0 , EDJE_PART_TYPE_RECTANGLE = 1 , EDJE_PART_TYPE_TEXT = 2 , EDJE_PART_TYPE_IMAGE = 3 ,
EDJE_PART_TYPE_SWALLOW = 4 , EDJE_PART_TYPE_TEXTBLOCK = 5 , EDJE_PART_TYPE_GRADIENT = 6 , EDJE_PART_TYPE_GROUP = 7 ,
EDJE_PART_TYPE_BOX = 8 , EDJE_PART_TYPE_TABLE = 9 , EDJE_PART_TYPE_EXTERNAL = 10 , EDJE_PART_TYPE_PROXY = 11 ,
EDJE_PART_TYPE_SPACER = 12 , EDJE_PART_TYPE_LAST = 13
}
enum _Edje_Text_Autocapital_Type { EDJE_TEXT_AUTOCAPITAL_TYPE_NONE , EDJE_TEXT_AUTOCAPITAL_TYPE_WORD , EDJE_TEXT_AUTOCAPITAL_TYPE_SENTENCE , EDJE_TEXT_AUTOCAPITAL_TYPE_ALLCHARACTER }
enum _Edje_Text_Effect {
EDJE_TEXT_EFFECT_NONE = 0 , EDJE_TEXT_EFFECT_PLAIN = 1 , EDJE_TEXT_EFFECT_OUTLINE = 2 , EDJE_TEXT_EFFECT_SOFT_OUTLINE = 3 ,
EDJE_TEXT_EFFECT_SHADOW = 4 , EDJE_TEXT_EFFECT_SOFT_SHADOW = 5 , EDJE_TEXT_EFFECT_OUTLINE_SHADOW = 6 , EDJE_TEXT_EFFECT_OUTLINE_SOFT_SHADOW = 7 ,
EDJE_TEXT_EFFECT_FAR_SHADOW = 8 , EDJE_TEXT_EFFECT_FAR_SOFT_SHADOW = 9 , EDJE_TEXT_EFFECT_GLOW = 10 , EDJE_TEXT_EFFECT_LAST = 11 ,
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM_RIGHT = (0x0 << 4) , EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM = (0x1 << 4) , EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM_LEFT = (0x2 << 4) , EDJE_TEXT_EFFECT_SHADOW_DIRECTION_LEFT = (0x3 << 4) ,
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP_LEFT = (0x4 << 4) , EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP = (0x5 << 4) , EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP_RIGHT = (0x6 << 4) , EDJE_TEXT_EFFECT_SHADOW_DIRECTION_RIGHT = (0x7 << 4)
}
enum _Edje_Text_Filter_Type { EDJE_TEXT_FILTER_TEXT = 0 , EDJE_TEXT_FILTER_FORMAT = 1 , EDJE_TEXT_FILTER_MARKUP = 2 }
enum _Edje_Tween_Mode {
EDJE_TWEEN_MODE_NONE = 0 , EDJE_TWEEN_MODE_LINEAR = 1 , EDJE_TWEEN_MODE_SINUSOIDAL = 2 , EDJE_TWEEN_MODE_ACCELERATE = 3 ,
EDJE_TWEEN_MODE_DECELERATE = 4 , EDJE_TWEEN_MODE_ACCELERATE_FACTOR = 5 , EDJE_TWEEN_MODE_DECELERATE_FACTOR = 6 , EDJE_TWEEN_MODE_SINUSOIDAL_FACTOR = 7 ,
EDJE_TWEEN_MODE_DIVISOR_INTERP = 8 , EDJE_TWEEN_MODE_BOUNCE = 9 , EDJE_TWEEN_MODE_SPRING = 10 , EDJE_TWEEN_MODE_LAST = 11 ,
EDJE_TWEEN_MODE_MASK = 0xff , EDJE_TWEEN_MODE_OPT_FROM_CURRENT = (1 << 31)
}
Functions
EAPI const Eina_List * edje_available_modules_get (void)
EAPI void edje_box_layout_register (const char *name, Evas_Object_Box_Layout func, void *(*layout_data_get)(void *), void(*layout_data_free)(void *), void(*free_data)(void *), void *data)
Registers a custom layout to be used in edje boxes.
EAPI void edje_collection_cache_flush (void)
Clean the collection cache.
EAPI int edje_collection_cache_get (void)
Return the collection cache size.
EAPI void edje_collection_cache_set (int count)
Set the collection cache size.
EAPI void edje_color_class_del (const char *color_class)
Delete edje color class.
EAPI Eina_Bool edje_color_class_get (const char *color_class, int *r, int *g, int *b, int *a, int *r2, int *g2, int *b2, int *a2, int *r3, int *g3, int *b3, int *a3)
Get Edje color class.
EAPI Eina_List * edje_color_class_list (void)
Lists color classes.
EAPI Eina_Bool edje_color_class_set (const char *color_class, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Set Edje color class.
EAPI const Edje_Perspective * edje_evas_global_perspective_get (const Evas *e)
Get the global perspective object set for this canvas.
EAPI void edje_extern_object_aspect_set (Evas_Object *obj, Edje_Aspect_Control aspect, Evas_Coord aw, Evas_Coord ah)
Set the object aspect size.
EAPI void edje_extern_object_max_size_set (Evas_Object *obj, Evas_Coord maxw, Evas_Coord maxh)
Set the object maximum size.
EAPI void edje_extern_object_min_size_set (Evas_Object *obj, Evas_Coord minw, Evas_Coord minh)
Set the object minimum size.
EAPI Eina_Iterator * edje_external_iterator_get (void)
Returns an interator of all the registered EXTERNAL types.
EAPI Eina_Bool edje_external_param_bool_get (const Eina_List *params, const char *key, Eina_Bool *ret)
Get the value of the given parameter of boolean type.
EAPI Eina_Bool edje_external_param_choice_get (const Eina_List *params, const char *key, const char **ret)
Get the value of the given parameter of choice type.
EAPI Eina_Bool edje_external_param_double_get (const Eina_List *params, const char *key, double *ret)
Get the value of the given parameter of double type.
EAPI Edje_External_Param * edje_external_param_find (const Eina_List *params, const char *key)
Conevenience function to find a specific parameter in a list of them.
EAPI const Edje_External_Param_Info * edje_external_param_info_get (const char *type_name)
Get the array of parameters information about a type given its name.
EAPI Eina_Bool edje_external_param_int_get (const Eina_List *params, const char *key, int *ret)
Get the value of the given parameter of integer type.
EAPI Eina_Bool edje_external_param_string_get (const Eina_List *params, const char *key, const char **ret)
Get the value of the given parameter of string type.
EAPI const char * edje_external_param_type_str (Edje_External_Param_Type type) EINA_PURE
Converts type identifier to string nicer representation.
EAPI unsigned int edje_external_type_abi_version_get (void) EINA_CONST
Return the current ABI version for Edje_External_Type structure.
EAPI void edje_external_type_array_register (const Edje_External_Type_Info *array)
Register a batch of types and their information.
EAPI void edje_external_type_array_unregister (const Edje_External_Type_Info *array)
Unregister a batch of given external type previously registered.
EAPI const Edje_External_Type * edje_external_type_get (const char *type_name)
Get the Edje_External_Type that defines an EXTERNAL type registered with the name type_name.
EAPI Eina_Bool edje_external_type_register (const char *type_name, const Edje_External_Type *type_info)
Register a type to be used by EXTERNAL parts.
EAPI Eina_Bool edje_external_type_unregister (const char *type_name)
Unregister a previously registered EXTERNAL type.
EAPI void edje_file_cache_flush (void)
Clean the file cache.
EAPI int edje_file_cache_get (void)
Return the file cache size.
EAPI void edje_file_cache_set (int count)
Set the file cache size.
EAPI Eina_List * edje_file_collection_list (const char *file)
Get a list of groups in an edje file.
EAPI void edje_file_collection_list_free (Eina_List *lst)
Free file collection list.
EAPI char * edje_file_data_get (const char *file, const char *key)
Get data from the file level data block of an edje file.
EAPI Eina_Bool edje_file_group_exists (const char *file, const char *glob)
Determine whether a group matching glob exists in an edje file.
EAPI const char * edje_fontset_append_get (void)
Get the edje append fontset.
EAPI void edje_fontset_append_set (const char *fonts)
Set the edje append fontset.
EAPI double edje_frametime_get (void)
Get edje trasitions' frame time.
EAPI void edje_frametime_set (double t)
Set edje trasitions' frame time.
EAPI void edje_freeze (void)
Freeze Edje objects.
EAPI int edje_init (void)
Initialize the Edje library.
EAPI const char * edje_load_error_str (Edje_Load_Error error)
Converts the given Edje file load error code into a string describing it in English.
EAPI void edje_message_signal_process (void)
Process all queued up edje messages.
EAPI Eina_Bool edje_module_load (const char *module)
EAPI Eina_List * edje_object_access_part_list_get (const Evas_Object *obj)
Retrieve a list all accessibility part names.
EAPI Evas_Object * edje_object_add (Evas *evas)
Instantiate a new Edje object.
EAPI Eina_Bool edje_object_animation_get (const Evas_Object *obj)
Get the Edje object's animation state.
EAPI void edje_object_animation_set (Evas_Object *obj, Eina_Bool on)
Set the object's animation state.
EAPI void edje_object_calc_force (Evas_Object *obj)
Force a Size/Geometry calculation.
EAPI void edje_object_color_class_del (Evas_Object *obj, const char *color_class)
Delete the object color class.
EAPI Eina_Bool edje_object_color_class_get (const Evas_Object *o, const char *color_class, int *r, int *g, int *b, int *a, int *r2, int *g2, int *b2, int *a2, int *r3, int *g3, int *b3, int *a3)
Gets the object color class.
EAPI Eina_Bool edje_object_color_class_set (Evas_Object *obj, const char *color_class, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Sets the object color class.
EAPI const char * edje_object_data_get (const Evas_Object *obj, const char *key)
Retrive an EDC data field's value from a given Edje object's group.
EAPI void edje_object_file_get (const Evas_Object *obj, const char **file, const char **group)
Get the file and group name that a given Edje object is bound to.
EAPI Eina_Bool edje_object_file_set (Evas_Object *obj, const char *file, const char *group)
Sets the EDJ file (and group within it) to load an Edje object's contents from.
EAPI int edje_object_freeze (Evas_Object *obj)
Freezes the Edje object.
EAPI void edje_object_item_provider_set (Evas_Object *obj, Edje_Item_Provider_Cb func, void *data)
Set the function that provides item objects for named items in an edje entry text.
EAPI Edje_Load_Error edje_object_load_error_get (const Evas_Object *obj)
Gets the (last) file loading error for a given Edje object.
EAPI void edje_object_message_handler_set (Evas_Object *obj, Edje_Message_Handler_Cb func, void *data)
Set an Edje message handler function for a given Edje object.
EAPI void edje_object_message_send (Evas_Object *obj, Edje_Message_Type type, int id, void *msg)
Send an (Edje) message to a given Edje object.
EAPI void edje_object_message_signal_process (Evas_Object *obj)
Process an object's message queue.
EAPI Eina_Bool edje_object_mirrored_get (const Evas_Object *obj)
Get the RTL orientation for this object.
EAPI void edje_object_mirrored_set (Evas_Object *obj, Eina_Bool rtl)
Set the RTL orientation for this object.
EAPI Eina_Bool edje_object_part_box_append (Evas_Object *obj, const char *part, Evas_Object *child)
Appends an object to the box.
EAPI Eina_Bool edje_object_part_box_insert_at (Evas_Object *obj, const char *part, Evas_Object *child, unsigned int pos)
Inserts an object to the box.
EAPI Eina_Bool edje_object_part_box_insert_before (Evas_Object *obj, const char *part, Evas_Object *child, const Evas_Object *reference)
Adds an object to the box.
EAPI Eina_Bool edje_object_part_box_prepend (Evas_Object *obj, const char *part, Evas_Object *child)
Prepends an object to the box.
EAPI Evas_Object * edje_object_part_box_remove (Evas_Object *obj, const char *part, Evas_Object *child)
Removes an object from the box.
EAPI Eina_Bool edje_object_part_box_remove_all (Evas_Object *obj, const char *part, Eina_Bool clear)
Removes all elements from the box.
EAPI Evas_Object * edje_object_part_box_remove_at (Evas_Object *obj, const char *part, unsigned int pos)
Removes an object from the box.
EAPI Edje_Drag_Dir edje_object_part_drag_dir_get (const Evas_Object *obj, const char *part)
Determine dragable directions.
EAPI Eina_Bool edje_object_part_drag_page (Evas_Object *obj, const char *part, double dx, double dy)
Pages x,y steps.
EAPI Eina_Bool edje_object_part_drag_page_get (const Evas_Object *obj, const char *part, double *dx, double *dy)
Gets the page step increments.
EAPI Eina_Bool edje_object_part_drag_page_set (Evas_Object *obj, const char *part, double dx, double dy)
Sets the page step increments.
EAPI Eina_Bool edje_object_part_drag_size_get (const Evas_Object *obj, const char *part, double *dw, double *dh)
Get the dragable object size.
EAPI Eina_Bool edje_object_part_drag_size_set (Evas_Object *obj, const char *part, double dw, double dh)
Set the dragable object size.
EAPI Eina_Bool edje_object_part_drag_step (Evas_Object *obj, const char *part, double dx, double dy)
Steps the dragable x,y steps.
EAPI Eina_Bool edje_object_part_drag_step_get (const Evas_Object *obj, const char *part, double *dx, double *dy)
Gets the drag step increment values.
EAPI Eina_Bool edje_object_part_drag_step_set (Evas_Object *obj, const char *part, double dx, double dy)
Sets the drag step increment.
EAPI Eina_Bool edje_object_part_drag_value_get (const Evas_Object *obj, const char *part, double *dx, double *dy)
Get the dragable object location.
EAPI Eina_Bool edje_object_part_drag_value_set (Evas_Object *obj, const char *part, double dx, double dy)
Set the dragable object location.
EAPI Eina_Bool edje_object_part_exists (const Evas_Object *obj, const char *part)
Check if an Edje part exists in a given Edje object's group definition.
EAPI Evas_Object * edje_object_part_external_content_get (const Evas_Object *obj, const char *part, const char *content)
Get an object contained in an part of type EXTERNAL.
EAPI Evas_Object * edje_object_part_external_object_get (const Evas_Object *obj, const char *part)
Get the object created by this external part.
EAPI Eina_Bool edje_object_part_external_param_get (const Evas_Object *obj, const char *part, Edje_External_Param *param)
Get the parameter for the external part.
EAPI Eina_Bool edje_object_part_external_param_set (Evas_Object *obj, const char *part, const Edje_External_Param *param)
Set the parameter for the external part.
EAPI Edje_External_Param_Type edje_object_part_external_param_type_get (const Evas_Object *obj, const char *part, const char *param)
Facility to query the type of the given parameter of the given part.
EAPI Eina_Bool edje_object_part_geometry_get (const Evas_Object *obj, const char *part, Evas_Coord *x, Evas_Coord *y, Evas_Coord *w, Evas_Coord *h)
Retrieve the geometry of a given Edje part, in a given Edje object's group definition, relative to the object's area
EAPI const Evas_Object * edje_object_part_object_get (const Evas_Object *obj, const char *part)
Get a handle to the Evas object implementing a given Edje part, in an Edje object.
EAPI const char * edje_object_part_state_get (const Evas_Object *obj, const char *part, double *val_ret)
Returns the state of the Edje part.
EAPI Eina_Bool edje_object_part_swallow (Evas_Object *obj, const char *part, Evas_Object *obj_swallow)
"Swallows" an object into one of the Edje object SWALLOW parts.
EAPI Evas_Object * edje_object_part_swallow_get (const Evas_Object *obj, const char *part)
Get the object currently swallowed by a part.
EAPI Evas_Object * edje_object_part_table_child_get (const Evas_Object *obj, const char *part, unsigned int col, unsigned int row)
Retrieve a child from a table.
EAPI Eina_Bool edje_object_part_table_clear (Evas_Object *obj, const char *part, Eina_Bool clear)
Removes all object from the table.
EAPI Eina_Bool edje_object_part_table_col_row_size_get (const Evas_Object *obj, const char *part, int *cols, int *rows)
Gets the number of columns and rows the table has.
EAPI Eina_Bool edje_object_part_table_pack (Evas_Object *obj, const char *part, Evas_Object *child_obj, unsigned short col, unsigned short row, unsigned short colspan, unsigned short rowspan)
Packs an object into the table.
EAPI Eina_Bool edje_object_part_table_unpack (Evas_Object *obj, const char *part, Evas_Object *child_obj)
Removes an object from the table.
EAPI const Eina_List * edje_object_part_text_anchor_geometry_get (const Evas_Object *obj, const char *part, const char *anchor)
Return a list of Evas_Textblock_Rectangle anchor rectangles.
EAPI const Eina_List * edje_object_part_text_anchor_list_get (const Evas_Object *obj, const char *part)
Return a list of char anchor names.
EAPI void edje_object_part_text_append (Evas_Object *obj, const char *part, const char *text)
Insert text for an object part.
EAPI Edje_Text_Autocapital_Type edje_object_part_text_autocapital_type_get (const Evas_Object *obj, const char *part)
Retrieves the autocapitalization type.
EAPI void edje_object_part_text_autocapital_type_set (Evas_Object *obj, const char *part, Edje_Text_Autocapital_Type autocapital_type)
Set the autocapitalization type on the immodule.
EAPI void edje_object_part_text_cursor_begin_set (Evas_Object *obj, const char *part, Edje_Cursor cur)
Moves the cursor to the beginning of the text part.
EAPI char * edje_object_part_text_cursor_content_get (const Evas_Object *obj, const char *part, Edje_Cursor cur)
Returns the content (char) at the cursor position.
EAPI Eina_Bool edje_object_part_text_cursor_coord_set (Evas_Object *obj, const char *part, Edje_Cursor cur, Evas_Coord x, Evas_Coord y)
Position the given cursor to a X,Y position.
EAPI void edje_object_part_text_cursor_copy (Evas_Object *obj, const char *part, Edje_Cursor src, Edje_Cursor dst)
Copy the cursor to another cursor.
EAPI Eina_Bool edje_object_part_text_cursor_down (Evas_Object *obj, const char *part, Edje_Cursor cur)
Moves the cursor to the char below the current cursor position.
EAPI void edje_object_part_text_cursor_end_set (Evas_Object *obj, const char *part, Edje_Cursor cur)
Moves the cursor to the end of the text part.
EAPI void edje_object_part_text_cursor_geometry_get (const Evas_Object *obj, const char *part, Evas_Coord *x, Evas_Coord *y, Evas_Coord *w, Evas_Coord *h)
Returns the cursor geometry of the part relative to the edje object.
EAPI Eina_Bool edje_object_part_text_cursor_is_format_get (const Evas_Object *obj, const char *part, Edje_Cursor cur)
Returns whether the cursor points to a format.
EAPI Eina_Bool edje_object_part_text_cursor_is_visible_format_get (const Evas_Object *obj, const char *part, Edje_Cursor cur)
Return true if the cursor points to a visible format For example \t, \n, item and etc.
EAPI void edje_object_part_text_cursor_line_begin_set (Evas_Object *obj, const char *part, Edje_Cursor cur)
Move the cursor to the beginning of the line.
EAPI void edje_object_part_text_cursor_line_end_set (Evas_Object *obj, const char *part, Edje_Cursor cur)
Move the cursor to the end of the line.
EAPI Eina_Bool edje_object_part_text_cursor_next (Evas_Object *obj, const char *part, Edje_Cursor cur)
Advances the cursor to the next cursor position.
EAPI int edje_object_part_text_cursor_pos_get (const Evas_Object *obj, const char *part, Edje_Cursor cur)
Retrieves the current position of the cursor.
EAPI void edje_object_part_text_cursor_pos_set (Evas_Object *obj, const char *part, Edje_Cursor cur, int pos)
Sets the cursor position to the given value.
EAPI Eina_Bool edje_object_part_text_cursor_prev (Evas_Object *obj, const char *part, Edje_Cursor cur)
Moves the cursor to the previous char.
EAPI Eina_Bool edje_object_part_text_cursor_up (Evas_Object *obj, const char *part, Edje_Cursor cur)
Move the cursor to the char above the current cursor position.
EAPI Eina_Bool edje_object_part_text_escaped_set (Evas_Object *obj, const char *part, const char *text)
Sets the text for an object part, but converts HTML escapes to UTF8.
EAPI const char * edje_object_part_text_get (const Evas_Object *obj, const char *part)
Return the text of the object part.
EAPI void * edje_object_part_text_imf_context_get (const Evas_Object *obj, const char *part)
Get the input method context in entry.
EAPI void edje_object_part_text_imf_context_reset (const Evas_Object *obj, const char *part)
Reset the input method context if needed.
EAPI Eina_Bool edje_object_part_text_input_panel_enabled_get (const Evas_Object *obj, const char *part)
Retrieve the attribute to show the input panel automatically.
EAPI void edje_object_part_text_input_panel_enabled_set (Evas_Object *obj, const char *part, Eina_Bool enabled)
Sets the attribute to show the input panel automatically.
EAPI void edje_object_part_text_input_panel_hide (const Evas_Object *obj, const char *part)
Hide the input panel (virtual keyboard).
EAPI void edje_object_part_text_input_panel_imdata_get (const Evas_Object *obj, const char *part, void *data, int *len)
Get the specific data of the current active input panel.
EAPI void edje_object_part_text_input_panel_imdata_set (Evas_Object *obj, const char *part, const void *data, int len)
Set the input panel-specific data to deliver to the input panel.
EAPI Edje_Input_Panel_Lang edje_object_part_text_input_panel_language_get (const Evas_Object *obj, const char *part)
Get the language mode of the input panel.
EAPI void edje_object_part_text_input_panel_language_set (Evas_Object *obj, const char *part, Edje_Input_Panel_Lang lang)
Set the language mode of the input panel.
EAPI Edje_Input_Panel_Layout edje_object_part_text_input_panel_layout_get (const Evas_Object *obj, const char *part)
Get the layout of the input panel.
EAPI void edje_object_part_text_input_panel_layout_set (Evas_Object *obj, const char *part, Edje_Input_Panel_Layout layout)
Set the layout of the input panel.
EAPI Eina_Bool edje_object_part_text_input_panel_return_key_disabled_get (const Evas_Object *obj, const char *part)
Get whether the return key on the input panel should be disabled or not.
EAPI void edje_object_part_text_input_panel_return_key_disabled_set (Evas_Object *obj, const char *part, Eina_Bool disabled)
Set the return key on the input panel to be disabled.
EAPI Edje_Input_Panel_Return_Key_Type edje_object_part_text_input_panel_return_key_type_get (const Evas_Object *obj, const char *part)
Get the "return" key type.
EAPI void edje_object_part_text_input_panel_return_key_type_set (Evas_Object *obj, const char *part, Edje_Input_Panel_Return_Key_Type return_key_type)
Set the "return" key type.
EAPI void edje_object_part_text_input_panel_show (const Evas_Object *obj, const char *part)
Show the input panel (virtual keyboard) based on the input panel property such as layout, autocapital types, and so on.
EAPI void edje_object_part_text_insert (Evas_Object *obj, const char *part, const char *text)
Insert text for an object part.
EAPI Eina_Bool edje_object_part_text_item_geometry_get (const Evas_Object *obj, const char *part, const char *item, Evas_Coord *cx, Evas_Coord *cy, Evas_Coord *cw, Evas_Coord *ch)
Return item geometry.
EAPI const Eina_List * edje_object_part_text_item_list_get (const Evas_Object *obj, const char *part)
Return a list of char item names.
EAPI Eina_Bool edje_object_part_text_prediction_allow_get (const Evas_Object *obj, const char *part)
Get whether the prediction is allowed or not.
EAPI void edje_object_part_text_prediction_allow_set (Evas_Object *obj, const char *part, Eina_Bool prediction)
Set whether the prediction is allowed or not.
EAPI void edje_object_part_text_select_abort (const Evas_Object *obj, const char *part)
Aborts any selection action on a part.
EAPI void edje_object_part_text_select_all (const Evas_Object *obj, const char *part)
Set the selection to be everything.
EAPI void edje_object_part_text_select_allow_set (const Evas_Object *obj, const char *part, Eina_Bool allow)
Enables selection if the entry is an EXPLICIT selection mode type.
EAPI void edje_object_part_text_select_begin (const Evas_Object *obj, const char *part)
Starts selecting at current cursor position.
EAPI void edje_object_part_text_select_extend (const Evas_Object *obj, const char *part)
Extends the current selection to the current cursor position.
EAPI void edje_object_part_text_select_none (const Evas_Object *obj, const char *part)
Set the selection to be none.
EAPI const char * edje_object_part_text_selection_get (const Evas_Object *obj, const char *part)
Return the selection text of the object part.
EAPI Eina_Bool edje_object_part_text_set (Evas_Object *obj, const char *part, const char *text)
Sets the text for an object part.
EAPI const char * edje_object_part_text_style_user_peek (const Evas_Object *obj, const char *part)
Return the text of the object part.
EAPI void edje_object_part_text_style_user_pop (Evas_Object *obj, const char *part)
Delete the top style form the user style stack.
EAPI void edje_object_part_text_style_user_push (Evas_Object *obj, const char *part, const char *style)
Set the style of the.
EAPI char * edje_object_part_text_unescaped_get (const Evas_Object *obj, const char *part)
Returns the text of the object part, without escaping.
EAPI Eina_Bool edje_object_part_text_unescaped_set (Evas_Object *obj, const char *part, const char *text_to_escape)
Sets the raw (non escaped) text for an object part.
EAPI void edje_object_part_text_user_insert (const Evas_Object *obj, const char *part, const char *text)
Deletes the selection and emits a change event.
EAPI void edje_object_part_unswallow (Evas_Object *obj, Evas_Object *obj_swallow)
Unswallow an object.
EAPI Eina_Bool edje_object_parts_extends_calc (Evas_Object *obj, Evas_Coord *x, Evas_Coord *y, Evas_Coord *w, Evas_Coord *h)
Calculate the geometry of the region, relative to a given Edje object's area, occupied by all parts in the object
EAPI const Edje_Perspective * edje_object_perspective_get (const Evas_Object *obj)
Get the current perspective used on this Edje object.
EAPI void edje_object_perspective_set (Evas_Object *obj, Edje_Perspective *ps)
Set the given perspective object on this Edje object.
EAPI Eina_Bool edje_object_play_get (const Evas_Object *obj)
Get the Edje object's state.
EAPI void edje_object_play_set (Evas_Object *obj, Eina_Bool play)
Set the Edje object to playing or paused states.
EAPI Eina_Bool edje_object_preload (Evas_Object *obj, Eina_Bool cancel)
Preload the images on the Edje Object in the background.
EAPI double edje_object_scale_get (const Evas_Object *obj)
Get a given Edje object's scaling factor.
EAPI Eina_Bool edje_object_scale_set (Evas_Object *obj, double scale)
Set the scaling factor for a given Edje object.
EAPI void edje_object_signal_callback_add (Evas_Object *obj, const char *emission, const char *source, Edje_Signal_Cb func, void *data)
Add a callback for an arriving Edje signal, emitted by a given Ejde object.
EAPI void * edje_object_signal_callback_del (Evas_Object *obj, const char *emission, const char *source, Edje_Signal_Cb func)
Remove a signal-triggered callback from an object.
EAPI void * edje_object_signal_callback_del_full (Evas_Object *obj, const char *emission, const char *source, Edje_Signal_Cb func, void *data)
Unregister/delete a callback set for an arriving Edje signal, emitted by a given Ejde object.
EAPI void * edje_object_signal_callback_extra_data_get (void)
Get extra data passed to callbacks.
EAPI void edje_object_signal_emit (Evas_Object *obj, const char *emission, const char *source)
Send/emit an Edje signal to a given Edje object.
EAPI void edje_object_size_max_get (const Evas_Object *obj, Evas_Coord *maxw, Evas_Coord *maxh)
Get the maximum size specified – as an EDC property – for a given Edje object.
EAPI void edje_object_size_min_calc (Evas_Object *obj, Evas_Coord *minw, Evas_Coord *minh)
Calculate the minimum required size for a given Edje object.
EAPI void edje_object_size_min_get (const Evas_Object *obj, Evas_Coord *minw, Evas_Coord *minh)
Get the minimum size specified – as an EDC property – for a given Edje object.
EAPI void edje_object_size_min_restricted_calc (Evas_Object *obj, Evas_Coord *minw, Evas_Coord *minh, Evas_Coord restrictedw, Evas_Coord restrictedh)
Calculate the minimum required size for a given Edje object.
EAPI void edje_object_text_change_cb_set (Evas_Object *obj, Edje_Text_Change_Cb func, void *data)
Set the object text callback.
EAPI Eina_Bool edje_object_text_class_set (Evas_Object *obj, const char *text_class, const char *font, Evas_Font_Size size)
Sets Edje text class.
EAPI void edje_object_text_insert_filter_callback_add (Evas_Object *obj, const char *part, Edje_Text_Filter_Cb func, void *data)
Add a filter function for newly inserted text.
EAPI void * edje_object_text_insert_filter_callback_del (Evas_Object *obj, const char *part, Edje_Text_Filter_Cb func)
Delete a function from the filter list.
EAPI void * edje_object_text_insert_filter_callback_del_full (Evas_Object *obj, const char *part, Edje_Text_Filter_Cb func, void *data)
Delete a function and matching user data from the filter list.
EAPI void edje_object_text_markup_filter_callback_add (Evas_Object *obj, const char *part, Edje_Markup_Filter_Cb func, void *data)
Add a markup filter function for newly inserted text.
EAPI void * edje_object_text_markup_filter_callback_del (Evas_Object *obj, const char *part, Edje_Markup_Filter_Cb func)
Delete a function from the markup filter list.
EAPI void * edje_object_text_markup_filter_callback_del_full (Evas_Object *obj, const char *part, Edje_Markup_Filter_Cb func, void *data)
Delete a function and matching user data from the markup filter list.
EAPI int edje_object_thaw (Evas_Object *obj)
Thaws the Edje object.
EAPI Eina_Bool edje_object_update_hints_get (Evas_Object *obj)
Wether or not Edje will update size hints on itself.
EAPI void edje_object_update_hints_set (Evas_Object *obj, Eina_Bool update)
Edje will automatically update the size hints on itself.
EAPI void edje_password_show_last_set (Eina_Bool password_show_last)
Show last character in password mode.
EAPI void edje_password_show_last_timeout_set (double password_show_last_timeout)
Set's the timeout value in last show password mode.
EAPI void edje_perspective_free (Edje_Perspective *ps)
Delete the given perspective object.
EAPI Eina_Bool edje_perspective_global_get (const Edje_Perspective *ps)
Get whether the given perspective object is global or not.
EAPI void edje_perspective_global_set (Edje_Perspective *ps, Eina_Bool global)
Make this perspective object be global for its canvas.
EAPI Edje_Perspective * edje_perspective_new (Evas *e)
Creates a new perspective in the given canvas.
EAPI void edje_perspective_set (Edje_Perspective *ps, Evas_Coord px, Evas_Coord py, Evas_Coord z0, Evas_Coord foc)
Setup the transform for this perspective object.
EAPI double edje_scale_get (void)
Retrieve Edje's global scaling factor.
EAPI void edje_scale_set (double scale)
Set Edje's global scaling factor.
EAPI int edje_shutdown (void)
Shutdown the Edje library.
EAPI void edje_text_class_del (const char *text_class)
Delete the text class.
EAPI Eina_List * edje_text_class_list (void)
List text classes.
EAPI Eina_Bool edje_text_class_set (const char *text_class, const char *font, Evas_Font_Size size)
Set the Edje text class.
EAPI void edje_thaw (void)
Thaw Edje objects.
Variables
EAPI Edje_Version * edje_version
Detailed Description
Edje Graphical Design Library.
These routines are used for Edje.
Macro Definition Documentation
EAPI
#define EAPI
EDJE_EXTERNAL_DOUBLE_UNSET
#define EDJE_EXTERNAL_DOUBLE_UNSET DBL_MAX
Helper macro to indicate an EXTERNAL's double parameter is undefined.
EDJE_EXTERNAL_INT_UNSET
#define EDJE_EXTERNAL_INT_UNSET INT_MAX
Helper macro to indicate an EXTERNAL's integer parameter is undefined.
EDJE_EXTERNAL_PARAM_INFO_BOOL
#define EDJE_EXTERNAL_PARAM_INFO_BOOL (name) EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT(name, 0)
EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT (name, def) EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL(name, def, "false", "true")
EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT_FLAGS (name, def, flags) EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL_FLAGS(name, def, "false", "true", flags)
EDJE_EXTERNAL_PARAM_INFO_BOOL_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_FLAGS (name, flags) EDJE_EXTERNAL_PARAM_INFO_BOOL_DEFAULT_FLAGS(name, 0, flags)
EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL (name, def, false_str, true_str) EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL_FLAGS(name, def, false_str, true_str, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_BOOL_FULL_FLAGS (name, def, false_str, true_str, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_BOOL, flags, {.b = {def, false_str, true_str}}}
EDJE_EXTERNAL_PARAM_INFO_CHOICE_DYNAMIC_FULL
#define EDJE_EXTERNAL_PARAM_INFO_CHOICE_DYNAMIC_FULL (name, def_get, query) EDJE_EXTERNAL_PARAM_INFO_CHOICE_DYNAMIC_FULL_FLAGS(name, def_get, query, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
EDJE_EXTERNAL_PARAM_INFO_CHOICE_DYNAMIC_FULL_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_CHOICE_DYNAMIC_FULL_FLAGS (name, def_get, query, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, flags, {.c = {NULL, NULL, def_get, query}}}
EDJE_EXTERNAL_PARAM_INFO_CHOICE_FULL
#define EDJE_EXTERNAL_PARAM_INFO_CHOICE_FULL (name, def, choices) EDJE_EXTERNAL_PARAM_INFO_CHOICE_FULL_FLAGS(name, def, choices, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
EDJE_EXTERNAL_PARAM_INFO_CHOICE_FULL_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_CHOICE_FULL_FLAGS (name, def, choices, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, flags, {.c = {def, choices, NULL, NULL}}}
EDJE_EXTERNAL_PARAM_INFO_DOUBLE
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE (name) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT(name, 0.0)
EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT (name, def) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL(name, def, EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_DOUBLE_UNSET)
EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT_FLAGS (name, def, flags) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL_FLAGS(name, def, EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_DOUBLE_UNSET, flags)
EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FLAGS (name, flags) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_DEFAULT_FLAGS(name, 0.0, flags)
EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL (name, def, min, max, step) EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL_FLAGS(name, def, min, max, step, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_DOUBLE_FULL_FLAGS (name, def, min, max, step, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, flags, {.d = {def, min, max, step}}}
EDJE_EXTERNAL_PARAM_INFO_INT
#define EDJE_EXTERNAL_PARAM_INFO_INT (name) EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT(name, 0)
EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT
#define EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT (name, def) EDJE_EXTERNAL_PARAM_INFO_INT_FULL(name, def, EDJE_EXTERNAL_INT_UNSET, EDJE_EXTERNAL_INT_UNSET, EDJE_EXTERNAL_INT_UNSET)
EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT_FLAGS (name, def, flags) EDJE_EXTERNAL_PARAM_INFO_INT_FULL_FLAGS(name, def, EDJE_EXTERNAL_INT_UNSET, EDJE_EXTERNAL_INT_UNSET, EDJE_EXTERNAL_INT_UNSET, flags)
EDJE_EXTERNAL_PARAM_INFO_INT_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_INT_FLAGS (name, flags) EDJE_EXTERNAL_PARAM_INFO_INT_DEFAULT_FLAGS(name, 0, flags)
EDJE_EXTERNAL_PARAM_INFO_INT_FULL
#define EDJE_EXTERNAL_PARAM_INFO_INT_FULL (name, def, min, max, step) EDJE_EXTERNAL_PARAM_INFO_INT_FULL_FLAGS(name, def, min, max, step, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
EDJE_EXTERNAL_PARAM_INFO_INT_FULL_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_INT_FULL_FLAGS (name, def, min, max, step, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_INT, flags, {.i = {def, min, max, step}}}
EDJE_EXTERNAL_PARAM_INFO_SENTINEL
#define EDJE_EXTERNAL_PARAM_INFO_SENTINEL {NULL, 0, 0, {.s = {NULL, NULL, NULL}}}
EDJE_EXTERNAL_PARAM_INFO_STRING
#define EDJE_EXTERNAL_PARAM_INFO_STRING (name) EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT(name, NULL)
EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT
#define EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT (name, def) EDJE_EXTERNAL_PARAM_INFO_STRING_FULL(name, def, NULL, NULL)
EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT_FLAGS (name, def, flags) EDJE_EXTERNAL_PARAM_INFO_STRING_FULL_FLAGS(name, def, NULL, NULL, flags)
EDJE_EXTERNAL_PARAM_INFO_STRING_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_STRING_FLAGS (name, flags) EDJE_EXTERNAL_PARAM_INFO_STRING_DEFAULT_FLAGS(name, NULL, flags)
EDJE_EXTERNAL_PARAM_INFO_STRING_FULL
#define EDJE_EXTERNAL_PARAM_INFO_STRING_FULL (name, def, accept, deny) EDJE_EXTERNAL_PARAM_INFO_STRING_FULL_FLAGS(name, def, accept, deny, EDJE_EXTERNAL_PARAM_FLAGS_REGULAR)
EDJE_EXTERNAL_PARAM_INFO_STRING_FULL_FLAGS
#define EDJE_EXTERNAL_PARAM_INFO_STRING_FULL_FLAGS (name, def, accept, deny, flags) {name, EDJE_EXTERNAL_PARAM_TYPE_STRING, flags, {.s = {def, accept, deny}}}
EDJE_EXTERNAL_TYPE_ABI_VERSION
#define EDJE_EXTERNAL_TYPE_ABI_VERSION (3)
EDJE_TEXT_EFFECT_BASIC_SET
#define EDJE_TEXT_EFFECT_BASIC_SET (x, s) do { x = ((x) & ~EDJE_TEXT_EFFECT_MASK_BASIC) | (s); } while (0)
EDJE_TEXT_EFFECT_MASK_BASIC
#define EDJE_TEXT_EFFECT_MASK_BASIC 0xf
EDJE_TEXT_EFFECT_MASK_SHADOW_DIRECTION
#define EDJE_TEXT_EFFECT_MASK_SHADOW_DIRECTION (0x7 << 4)
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_SET
#define EDJE_TEXT_EFFECT_SHADOW_DIRECTION_SET (x, s) do { x = ((x) & ~EDJE_TEXT_EFFECT_MASK_SHADOW_DIRECTION) | (s); } while (0)
EDJE_VERSION_MAJOR
#define EDJE_VERSION_MAJOR 1
EDJE_VERSION_MINOR
#define EDJE_VERSION_MINOR 7
Typedef Documentation
Edje_Action_Type
typedef enum _Edje_Action_Type Edje_Action_Type
Edje_Aspect_Control
typedef enum _Edje_Aspect_Control Edje_Aspect_Control
Edje_Cursor
typedef enum _Edje_Cursor Edje_Cursor
Edje_Drag_Dir
typedef enum _Edje_Drag_Dir Edje_Drag_Dir
Edje_Entry_Change_Info
typedef struct _Edje_Entry_Change_Info Edje_Entry_Change_Info
Since
1.1.0
Edje_External_Param
typedef struct _Edje_External_Param Edje_External_Param
Struct that holds parameters for parts of type EXTERNAL.
Edje_External_Param_Flags
typedef enum _Edje_External_Param_Flags Edje_External_Param_Flags
Flags that determine how a parameter may be accessed in different circumstances.
Edje_External_Param_Info
typedef struct _Edje_External_Param_Info Edje_External_Param_Info
Struct holding information about an EXTERNAL part's parameters.
When creating types to use with EXTERNAL parts, an array of this type is used to describe the different parameters the object uses.
This struct holds the name, type and flags that define how and when the parameter is used, as well as information specific to each type, like the maximum or minimum value, that can be used by editors to restrict the range of values to set for each parameter.
Edje_External_Param_Type
typedef enum _Edje_External_Param_Type Edje_External_Param_Type
The possible types the parameters of an EXTERNAL part can be.
Edje_External_Type
typedef struct _Edje_External_Type Edje_External_Type
Edje_External_Type_Info
typedef struct _Edje_External_Type_Info Edje_External_Type_Info
Edje_Input_Panel_Lang
typedef enum _Edje_Input_Panel_Lang Edje_Input_Panel_Lang
Edje_Input_Panel_Layout
typedef enum _Edje_Input_Panel_Layout Edje_Input_Panel_Layout
Edje_Input_Panel_Return_Key_Type
typedef enum _Edje_Input_Panel_Return_Key_Type Edje_Input_Panel_Return_Key_Type
Edje_Item_Provider_Cb
typedef Evas_Object*(* Edje_Item_Provider_Cb) (void *data, Evas_Object *obj, const char *part, const char *item)
Edje_Load_Error
typedef enum _Edje_Load_Error Edje_Load_Error
Edje file loading error codes one can get - see edje_load_error_str() too.
Edje_Markup_Filter_Cb
typedef void(* Edje_Markup_Filter_Cb) (void *data, Evas_Object *obj, const char *part, char **text)
Edje_Message_Float
typedef struct _Edje_Message_Float Edje_Message_Float
Edje_Message_Float_Set
typedef struct _Edje_Message_Float_Set Edje_Message_Float_Set
Edje_Message_Handler_Cb
typedef void(* Edje_Message_Handler_Cb) (void *data, Evas_Object *obj, Edje_Message_Type type, int id, void *msg)
Edje message handler callback functions's prototype definition.
data will have the auxiliary data pointer set at the time the callback registration. obj will be a pointer the Edje object where the message comes from. type will identify the type of the given message and msg will be a pointer the message's contents, de facto, which depend on type.
Edje_Message_Int
typedef struct _Edje_Message_Int Edje_Message_Int
Edje_Message_Int_Set
typedef struct _Edje_Message_Int_Set Edje_Message_Int_Set
Edje_Message_String
typedef struct _Edje_Message_String Edje_Message_String
Edje_Message_String_Float
typedef struct _Edje_Message_String_Float Edje_Message_String_Float
Edje_Message_String_Float_Set
typedef struct _Edje_Message_String_Float_Set Edje_Message_String_Float_Set
Edje_Message_String_Int
typedef struct _Edje_Message_String_Int Edje_Message_String_Int
Edje_Message_String_Int_Set
typedef struct _Edje_Message_String_Int_Set Edje_Message_String_Int_Set
Edje_Message_String_Set
typedef struct _Edje_Message_String_Set Edje_Message_String_Set
Edje_Message_Type
typedef enum _Edje_Message_Type Edje_Message_Type
Identifiers of Edje message types, which can be sent back and forth code and a given Edje object's theme file/group.
See also
edje_object_message_send()
edje_object_message_handler_set()
Edje_Object_Table_Homogeneous_Mode
typedef enum _Edje_Object_Table_Homogeneous_Mode Edje_Object_Table_Homogeneous_Mode
Edje_Part_Type
typedef enum _Edje_Part_Type Edje_Part_Type
Edje_Perspective
typedef struct _Edje_Perspective Edje_Perspective
Edje_Signal_Cb
typedef void(* Edje_Signal_Cb) (void *data, Evas_Object *obj, const char *emission, const char *source)
Edje signal callback functions's prototype definition.
data will have the auxiliary data pointer set at the time the callback registration. obj will be a pointer the Edje object where the signal comes from. emission will identify the exact signal's emission string and source the exact signal's source one.
Examples
edje-color-class.c.
Edje_Text_Autocapital_Type
typedef enum _Edje_Text_Autocapital_Type Edje_Text_Autocapital_Type
Edje_Text_Change_Cb
typedef void(* Edje_Text_Change_Cb) (void *data, Evas_Object *obj, const char *part)
Edje_Text_Effect
typedef enum _Edje_Text_Effect Edje_Text_Effect
Edje_Text_Filter_Cb
typedef void(* Edje_Text_Filter_Cb) (void *data, Evas_Object *obj, const char *part, Edje_Text_Filter_Type type, char **text)
Edje_Text_Filter_Type
typedef enum _Edje_Text_Filter_Type Edje_Text_Filter_Type
Edje_Tween_Mode
typedef enum _Edje_Tween_Mode Edje_Tween_Mode
Edje_Version
typedef struct _Edje_Version Edje_Version
Enumeration Type Documentation
_Edje_Action_Type
enum _Edje_Action_Type
Enumerator
EDJE_ACTION_TYPE_NONE
EDJE_ACTION_TYPE_STATE_SET
EDJE_ACTION_TYPE_ACTION_STOP
EDJE_ACTION_TYPE_SIGNAL_EMIT
EDJE_ACTION_TYPE_DRAG_VAL_SET
EDJE_ACTION_TYPE_DRAG_VAL_STEP
EDJE_ACTION_TYPE_DRAG_VAL_PAGE
EDJE_ACTION_TYPE_SCRIPT
EDJE_ACTION_TYPE_FOCUS_SET
EDJE_ACTION_TYPE_RESERVED00
EDJE_ACTION_TYPE_FOCUS_OBJECT
EDJE_ACTION_TYPE_PARAM_COPY
EDJE_ACTION_TYPE_PARAM_SET
EDJE_ACTION_TYPE_SOUND_SAMPLE
Since
1.1
EDJE_ACTION_TYPE_SOUND_TONE
Since
1.1
EDJE_ACTION_TYPE_LAST
_Edje_Aspect_Control
enum _Edje_Aspect_Control
Enumerator
EDJE_ASPECT_CONTROL_NONE
EDJE_ASPECT_CONTROL_NEITHER
EDJE_ASPECT_CONTROL_HORIZONTAL
EDJE_ASPECT_CONTROL_VERTICAL
EDJE_ASPECT_CONTROL_BOTH
_Edje_Cursor
enum _Edje_Cursor
Enumerator
EDJE_CURSOR_MAIN
EDJE_CURSOR_SELECTION_BEGIN
EDJE_CURSOR_SELECTION_END
EDJE_CURSOR_PREEDIT_START
EDJE_CURSOR_PREEDIT_END
EDJE_CURSOR_USER
EDJE_CURSOR_USER_EXTRA
_Edje_Drag_Dir
enum _Edje_Drag_Dir
Enumerator
EDJE_DRAG_DIR_NONE
EDJE_DRAG_DIR_X
EDJE_DRAG_DIR_Y
EDJE_DRAG_DIR_XY
_Edje_External_Param_Flags
enum _Edje_External_Param_Flags
Flags that determine how a parameter may be accessed in different circumstances.
Enumerator
EDJE_EXTERNAL_PARAM_FLAGS_NONE
Property is incapable of operations, this is used to catch bogus flags.
EDJE_EXTERNAL_PARAM_FLAGS_GET
Property can be read/get.
EDJE_EXTERNAL_PARAM_FLAGS_SET
Property can be written/set.
This only enables edje_object_part_external_param_set() and Embryo scripts. To enable the parameter being set from state description whenever it changes state, use EDJE_EXTERNAL_PARAM_FLAGS_STATE.
EDJE_EXTERNAL_PARAM_FLAGS_STATE
Property can be set from state description.
EDJE_EXTERNAL_PARAM_FLAGS_CONSTRUCTOR
This property is only set once when the object is constructed using its value from "default" 0.0 state description.
Setting this overrides EDJE_EXTERNAL_PARAM_FLAGS_STATE.
EDJE_EXTERNAL_PARAM_FLAGS_REGULAR
Convenience flag that sets property as GET, SET and STATE.
_Edje_External_Param_Type
enum _Edje_External_Param_Type
The possible types the parameters of an EXTERNAL part can be.
Enumerator
EDJE_EXTERNAL_PARAM_TYPE_INT
Parameter value is an integer.
EDJE_EXTERNAL_PARAM_TYPE_DOUBLE
Parameter value is a double.
EDJE_EXTERNAL_PARAM_TYPE_STRING
Parameter value is a string.
EDJE_EXTERNAL_PARAM_TYPE_BOOL
Parameter value is boolean.
EDJE_EXTERNAL_PARAM_TYPE_CHOICE
Parameter value is one of a set of predefined string choices.
EDJE_EXTERNAL_PARAM_TYPE_MAX
Sentinel.
Don't use.
_Edje_Input_Panel_Lang
enum _Edje_Input_Panel_Lang
Enumerator
EDJE_INPUT_PANEL_LANG_AUTOMATIC
Automatic.
Since
1.2
EDJE_INPUT_PANEL_LANG_ALPHABET
Alphabet.
Since
1.2
_Edje_Input_Panel_Layout
enum _Edje_Input_Panel_Layout
Enumerator
EDJE_INPUT_PANEL_LAYOUT_NORMAL
Default layout.
EDJE_INPUT_PANEL_LAYOUT_NUMBER
Number layout.
EDJE_INPUT_PANEL_LAYOUT_EMAIL
Email layout.
EDJE_INPUT_PANEL_LAYOUT_URL
URL layout.
EDJE_INPUT_PANEL_LAYOUT_PHONENUMBER
Phone Number layout.
EDJE_INPUT_PANEL_LAYOUT_IP
IP layout.
EDJE_INPUT_PANEL_LAYOUT_MONTH
Month layout.
EDJE_INPUT_PANEL_LAYOUT_NUMBERONLY
Number Only layout.
EDJE_INPUT_PANEL_LAYOUT_INVALID
Never use this.
EDJE_INPUT_PANEL_LAYOUT_HEX
Hexadecimal layout.
Since
1.2
EDJE_INPUT_PANEL_LAYOUT_TERMINAL
Command-line terminal layout.
Since
1.2
EDJE_INPUT_PANEL_LAYOUT_PASSWORD
Like normal, but no auto-correct, no auto-capitalization etc.
Since
1.2
_Edje_Input_Panel_Return_Key_Type
enum _Edje_Input_Panel_Return_Key_Type
Enumerator
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DEFAULT
Default.
Since
1.2
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DONE
Done.
Since
1.2
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_GO
Go.
Since
1.2
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_JOIN
Join.
Since
1.2
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_LOGIN
Login.
Since
1.2
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_NEXT
Next.
Since
1.2
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_SEARCH
Search or magnifier icon.
Since
1.2
EDJE_INPUT_PANEL_RETURN_KEY_TYPE_SEND
Send.
Since
1.2
_Edje_Load_Error
enum _Edje_Load_Error
Enumerator
EDJE_LOAD_ERROR_NONE
No error happened, the loading was successful.
EDJE_LOAD_ERROR_GENERIC
A generic error happened during the loading.
EDJE_LOAD_ERROR_DOES_NOT_EXIST
The file pointed to did not exist.
EDJE_LOAD_ERROR_PERMISSION_DENIED
Permission to read the given file was denied.
EDJE_LOAD_ERROR_RESOURCE_ALLOCATION_FAILED
Resource allocation failed during the loading.
EDJE_LOAD_ERROR_CORRUPT_FILE
The file pointed to was corrupt.
EDJE_LOAD_ERROR_UNKNOWN_FORMAT
The file pointed to had an unknown format.
EDJE_LOAD_ERROR_INCOMPATIBLE_FILE
The file pointed to is incompatible, i.e., it doesn't match the library's current version's format.
EDJE_LOAD_ERROR_UNKNOWN_COLLECTION
The group/collection set to load from was not found in the file.
EDJE_LOAD_ERROR_RECURSIVE_REFERENCE
The group/collection set to load from had recursive references on its components.
_Edje_Message_Type
enum _Edje_Message_Type
Identifiers of Edje message types, which can be sent back and forth code and a given Edje object's theme file/group.
See also
edje_object_message_send()
edje_object_message_handler_set()
Enumerator
EDJE_MESSAGE_NONE
EDJE_MESSAGE_SIGNAL
EDJE_MESSAGE_STRING
A message with a string as value.
Use Edje_Message_String structs as message body, for this type.
EDJE_MESSAGE_INT
A message with an integer number as value.
Use Edje_Message_Int structs as message body, for this type.
EDJE_MESSAGE_FLOAT
A message with a floating pointer number as value.
Use Edje_Message_Float structs as message body, for this type.
EDJE_MESSAGE_STRING_SET
A message with a list of strings as value.
Use Edje_Message_String_Set structs as message body, for this type.
EDJE_MESSAGE_INT_SET
A message with a list of integer numbers as value.
Use Edje_Message_Int_Set structs as message body, for this type.
EDJE_MESSAGE_FLOAT_SET
A message with a list of floating point numbers as value.
Use Edje_Message_Float_Set structs as message body, for this type.
EDJE_MESSAGE_STRING_INT
A message with a struct containing a string and an integer number as value.
Use Edje_Message_String_Int structs as message body, for this type.
EDJE_MESSAGE_STRING_FLOAT
A message with a struct containing a string and a floating point number as value.
Use Edje_Message_String_Float structs as message body, for this type.
EDJE_MESSAGE_STRING_INT_SET
A message with a struct containing a string and list of integer numbers as value.
Use Edje_Message_String_Int_Set structs as message body, for this type.
EDJE_MESSAGE_STRING_FLOAT_SET
A message with a struct containing a string and list of floating point numbers as value.
Use Edje_Message_String_Float_Set structs as message body, for this type.
_Edje_Object_Table_Homogeneous_Mode
enum _Edje_Object_Table_Homogeneous_Mode
Enumerator
EDJE_OBJECT_TABLE_HOMOGENEOUS_NONE
EDJE_OBJECT_TABLE_HOMOGENEOUS_TABLE
EDJE_OBJECT_TABLE_HOMOGENEOUS_ITEM
_Edje_Part_Type
enum _Edje_Part_Type
Enumerator
EDJE_PART_TYPE_NONE
EDJE_PART_TYPE_RECTANGLE
EDJE_PART_TYPE_TEXT
EDJE_PART_TYPE_IMAGE
EDJE_PART_TYPE_SWALLOW
EDJE_PART_TYPE_TEXTBLOCK
EDJE_PART_TYPE_GRADIENT
EDJE_PART_TYPE_GROUP
EDJE_PART_TYPE_BOX
EDJE_PART_TYPE_TABLE
EDJE_PART_TYPE_EXTERNAL
EDJE_PART_TYPE_PROXY
EDJE_PART_TYPE_SPACER
Since
1.7
EDJE_PART_TYPE_LAST
_Edje_Text_Autocapital_Type
enum _Edje_Text_Autocapital_Type
Enumerator
EDJE_TEXT_AUTOCAPITAL_TYPE_NONE
EDJE_TEXT_AUTOCAPITAL_TYPE_WORD
EDJE_TEXT_AUTOCAPITAL_TYPE_SENTENCE
EDJE_TEXT_AUTOCAPITAL_TYPE_ALLCHARACTER
_Edje_Text_Effect
enum _Edje_Text_Effect
Enumerator
EDJE_TEXT_EFFECT_NONE
EDJE_TEXT_EFFECT_PLAIN
EDJE_TEXT_EFFECT_OUTLINE
EDJE_TEXT_EFFECT_SOFT_OUTLINE
EDJE_TEXT_EFFECT_SHADOW
EDJE_TEXT_EFFECT_SOFT_SHADOW
EDJE_TEXT_EFFECT_OUTLINE_SHADOW
EDJE_TEXT_EFFECT_OUTLINE_SOFT_SHADOW
EDJE_TEXT_EFFECT_FAR_SHADOW
EDJE_TEXT_EFFECT_FAR_SOFT_SHADOW
EDJE_TEXT_EFFECT_GLOW
EDJE_TEXT_EFFECT_LAST
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM_RIGHT
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM_LEFT
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_LEFT
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP_LEFT
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP_RIGHT
EDJE_TEXT_EFFECT_SHADOW_DIRECTION_RIGHT
_Edje_Text_Filter_Type
enum _Edje_Text_Filter_Type
Enumerator
EDJE_TEXT_FILTER_TEXT
EDJE_TEXT_FILTER_FORMAT
EDJE_TEXT_FILTER_MARKUP
_Edje_Tween_Mode
enum _Edje_Tween_Mode
Enumerator
EDJE_TWEEN_MODE_NONE
EDJE_TWEEN_MODE_LINEAR
EDJE_TWEEN_MODE_SINUSOIDAL
EDJE_TWEEN_MODE_ACCELERATE
EDJE_TWEEN_MODE_DECELERATE
EDJE_TWEEN_MODE_ACCELERATE_FACTOR
EDJE_TWEEN_MODE_DECELERATE_FACTOR
EDJE_TWEEN_MODE_SINUSOIDAL_FACTOR
EDJE_TWEEN_MODE_DIVISOR_INTERP
EDJE_TWEEN_MODE_BOUNCE
EDJE_TWEEN_MODE_SPRING
EDJE_TWEEN_MODE_LAST
EDJE_TWEEN_MODE_MASK
EDJE_TWEEN_MODE_OPT_FROM_CURRENT
Function Documentation
edje_available_modules_get()
EAPI const Eina_List* edje_available_modules_get (void)
References _modules_found, _modules_paths, and EDJE_MODULE_NAME.
edje_box_layout_register()
EAPI void edje_box_layout_register (const char * name, Evas_Object_Box_Layout func, void *(*)(void *) layout_data_get, void(*)(void *) layout_data_free, void(*)(void *) free_data, void * data)
Registers a custom layout to be used in edje boxes.
Parameters
name The name of the layout
func The function defining the layout
layout_data_get This function gets the custom data pointer for func
layout_data_free Passed to func to free its private data when needed
free_data Frees data
data Private pointer passed to layout_data_get
This function registers custom layouts that can be referred from themes by the registered name. The Evas_Object_Box_Layout functions receive two pointers for internal use, one being private data, and the other the function to free that data when it's not longer needed. From Edje, this private data will be retrieved by calling layout_data_get, and layout_data_free will be the free function passed to func. layout_data_get will be called with data as its parameter, and this one will be freed by free_data whenever the layout is unregistered from Edje.
Examples
edje-box2.c.
References name.
edje_collection_cache_flush()
EAPI void edje_collection_cache_flush (void)
Clean the collection cache.
This function cleans the collection cache, but keeps this cache's size to the last value set.
See also
edje_collection_cache_set()
edje_collection_cache_get()
edje_collection_cache_get()
EAPI int edje_collection_cache_get (void)
Return the collection cache size.
Returns
The collection cache size, in edje object units. Default is 16.
This function returns the collection cache size set by edje_collection_cache_set().
See also
edje_collection_cache_set()
edje_collection_cache_flush()
edje_collection_cache_set()
EAPI void edje_collection_cache_set (int count)
Set the collection cache size.
Parameters
count The collection cache size, in edje object units. Default is 16.
This function sets the collection cache size. Edje keeps this cache in order to prevent duplicates of edje {collection,group,part} entries in memory. The collection cache size can be retrieved with edje_collection_cache_get().
See also
edje_collection_cache_get()
edje_collection_cache_flush()
edje_color_class_del()
EAPI void edje_color_class_del (const char * color_class)
Delete edje color class.
Parameters
color_class This function deletes any values at the process level for the specified color class.
Note
Deleting the color class will revert it to the values defined in the theme file.
Deleting the color class will emit the signal "color_class,del" to all the Edje objects in the running program.
Examples
edje-color-class.c.
edje_color_class_get()
EAPI Eina_Bool edje_color_class_get (const char * color_class, int * r, int * g, int * b, int * a, int * r2, int * g2, int * b2, int * a2, int * r3, int * g3, int * b3, int * a3)
Get Edje color class.
Parameters
color_class
r Object Red value
g Object Green value
b Object Blue value
a Object Alpha value
r2 Outline Red value
g2 Outline Green value
b2 Outline Blue value
a2 Outline Alpha value
r3 Shadow Red value
g3 Shadow Green value
b3 Shadow Blue value
a3 Shadow Alpha value
Returns
EINA_TRUE if found or EINA_FALSE if not found and all values are zeroed.
This function gets the color values for a process level color class. This value is the globally set and not per-object, that is, the value that would be used by objects if they did not override with edje_object_color_class_set().
The first color is the object, the second is the text outline, and the third is the text shadow. (Note that the second two only apply to text parts).
See also
edje_color_class_set().
Note
unlike Evas, Edje colors are not pre-multiplied. That is, half-transparent white is 255 255 255 128.
Examples
edje-color-class.c.
edje_color_class_list()
EAPI Eina_List* edje_color_class_list (void)
Lists color classes.
Returns
A list of color class names (strings). These strings and the list must be free()'d by the caller.
This function lists all color classes known about by the current process.
Examples
edje-color-class.c.
edje_color_class_set()
EAPI Eina_Bool edje_color_class_set (const char * color_class, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Set Edje color class.
Parameters
color_class
r Object Red value
g Object Green value
b Object Blue value
a Object Alpha value
r2 Outline Red value
g2 Outline Green value
b2 Outline Blue value
a2 Outline Alpha value
r3 Shadow Red value
g3 Shadow Green value
b3 Shadow Blue value
a3 Shadow Alpha value
This function sets the color values for a process level color class. This will cause all edje parts in the current process that have the specified color class to have their colors multiplied by these values. (Object level color classes set by edje_object_color_class_set() will override the values set by this function).
The first color is the object, the second is the text outline, and the third is the text shadow. (Note that the second two only apply to text parts).
Setting color emits a signal "color_class,set" with source being the given color class in all objects.
See also
edje_color_class_set().
Note
unlike Evas, Edje colors are not pre-multiplied. That is, half-transparent white is 255 255 255 128.
Examples
edje-color-class.c.
edje_evas_global_perspective_get()
EAPI const Edje_Perspective* edje_evas_global_perspective_get (const Evas * e)
Get the global perspective object set for this canvas.
Parameters
e The given canvas (Evas).
Returns
The perspective object set as global for this canvas. Or NULL if there is no global perspective set and on errors.
This function will return the perspective object that was set as global with edje_perspective_global_set().
See also
edje_perspective_global_set()
edje_perspective_global_get()
edje_extern_object_aspect_set()
EAPI void edje_extern_object_aspect_set (Evas_Object * obj, Edje_Aspect_Control aspect, Evas_Coord aw, Evas_Coord ah)
Set the object aspect size.
Parameters
obj A valid Evas_Object handle
aspect The aspect control axes
aw The aspect radio width
ah The aspect ratio height
This sets the desired aspect ratio to keep an object that will be swallowed by Edje. The width and height define a preferred size ASPECT and the object may be scaled to be larger or smaller, but retaining the relative scale of both aspect width and height.
References _Edje_Real_Part::aspect, EDJE_ASPECT_CONTROL_BOTH, EDJE_ASPECT_CONTROL_HORIZONTAL, EDJE_ASPECT_CONTROL_NEITHER, EDJE_ASPECT_CONTROL_NONE, EDJE_ASPECT_CONTROL_VERTICAL, _Edje_Aspect::h, _Edje_Aspect::mode, _Edje_Real_Part::swallow_params, and _Edje_Aspect::w.
edje_extern_object_max_size_set()
EAPI void edje_extern_object_max_size_set (Evas_Object * obj, Evas_Coord maxw, Evas_Coord maxh)
Set the object maximum size.
Parameters
obj A valid Evas_Object handle
maxw The maximum width
maxh The maximum height
This sets the maximum size restriction for the object.
References _Edje_Size::h, _Edje_Real_Part::max, _Edje_Real_Part::swallow_params, and _Edje_Size::w.
edje_extern_object_min_size_set()
EAPI void edje_extern_object_min_size_set (Evas_Object * obj, Evas_Coord minw, Evas_Coord minh)
Set the object minimum size.
Parameters
obj A valid Evas_Object handle
minw The minimum width
minh The minimum height
This sets the minimum size restriction for the object.
References _Edje_Size::h, _Edje_Real_Part::min, _Edje_Real_Part::swallow_params, and _Edje_Size::w.
edje_external_iterator_get()
EAPI Eina_Iterator* edje_external_iterator_get (void)
Returns an interator of all the registered EXTERNAL types.
Each item in the iterator is an Eina_Hash_Tuple which has the type of the external in the key and Edje_External_Type as data.
const Eina_Hash_Tuple *tuple;
Eina_Iterator *itr;
const Eina_List *l, *modules;
const char *s;
modules = edje_available_modules_get();
EINA_LIST_FOREACH(modules, l, s)
  {
     if (!edje_module_load(s))
       printf("Error loading edje module: %s\n", s);
  }
itr = edje_external_iterator_get();
EINA_ITERATOR_FOREACH(itr, tuple)
  {
     const char *name = tuple->key;
     const Edje_External_Type *type = tuple->data;
     if ((!type) ||
         (type->abi_version != edje_external_type_abi_version_get()))
       {
          printf("Error: invalid type %p (abi: %d, expected: %d)\n",
                  type, type ? type->abi_version : 0,
                  edje_external_type_abi_version_get());
          continue;
       }
     printf("%s: %s (%s) label='%s' desc='%s'\n",
            name, type->module, type->module_name,
            type->label_get ? type->label_get(type->data) : "",
            type->description_get ? type->description_get(type->data) : "");
  }
edje_external_param_bool_get()
EAPI Eina_Bool edje_external_param_bool_get (const Eina_List * params, const char * key, Eina_Bool * ret)
Get the value of the given parameter of boolean type.
Look for the key parameter in the params list and return its value in ret. If the parameter is found and is of type EDJE_EXTERNAL_PARAM_TYPE_BOOL, its value will be stored in the Eina_Bool pointed by ret, returning EINA_TRUE. In any other case, the function returns EINA_FALSE.
Parameters
params List of parameters where to look
key Name of the parameter to fetch
ret Eina_Bool pointer where to store the value, must not be NULL.
Returns
EINA_TRUE if the parameter was found and is of boolean type, EINA_FALSE otherwise.
References edje_external_param_find(), EDJE_EXTERNAL_PARAM_TYPE_BOOL, _Edje_External_Param::i, and _Edje_External_Param::type.
edje_external_param_choice_get()
EAPI Eina_Bool edje_external_param_choice_get (const Eina_List * params, const char * key, const char ** ret)
Get the value of the given parameter of choice type.
Look for the key parameter in the params list and return its value in ret. If the parameter is found and is of type EDJE_EXTERNAL_PARAM_TYPE_CHOICE, its value will be stored in the string pointed by ret, returning EINA_TRUE. In any other case, the function returns EINA_FALSE.
The string stored in ret must not be freed or modified.
Parameters
params List of parameters where to look
key Name of the parameter to fetch
ret String pointer where to store the value, must not be NULL.
Returns
EINA_TRUE if the parameter was found and is of integer type, EINA_FALSE otherwise.
References edje_external_param_find(), EDJE_EXTERNAL_PARAM_TYPE_CHOICE, _Edje_External_Param::s, and _Edje_External_Param::type.
edje_external_param_double_get()
EAPI Eina_Bool edje_external_param_double_get (const Eina_List * params, const char * key, double * ret)
Get the value of the given parameter of double type.
Look for the key parameter in the params list and return its value in ret. If the parameter is found and is of type EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, its value will be stored in the double pointed by ret, returning EINA_TRUE. In any other case, the function returns EINA_FALSE.
Parameters
params List of parameters where to look
key Name of the parameter to fetch
ret Double pointer where to store the value, must not be NULL.
Returns
EINA_TRUE if the parameter was found and is of double type, EINA_FALSE otherwise.
References _Edje_External_Param::d, edje_external_param_find(), EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, and _Edje_External_Param::type.
edje_external_param_find()
EAPI Edje_External_Param* edje_external_param_find (const Eina_List * params, const char * key)
Conevenience function to find a specific parameter in a list of them.
Parameters
params The list of parameters for the external
key The parameter to look for
Returns
The matching Edje_External_Param or NULL if it's not found.
References _Edje_External_Param::name.
Referenced by edje_external_param_bool_get(), edje_external_param_choice_get(), edje_external_param_double_get(), edje_external_param_int_get(), and edje_external_param_string_get().
edje_external_param_info_get()
EAPI const Edje_External_Param_Info* edje_external_param_info_get (const char * type_name)
Get the array of parameters information about a type given its name.
Note
the type names and other strings are static, that means they are NOT translated. One must use Edje_External_Type::translate() to translate those.
Returns
the NULL terminated array, or NULL if type is unknown or it does not have any parameter information.
See also
edje_external_type_get()
References type.
edje_external_param_int_get()
EAPI Eina_Bool edje_external_param_int_get (const Eina_List * params, const char * key, int * ret)
Get the value of the given parameter of integer type.
Look for the key parameter in the params list and return its value in ret. If the parameter is found and is of type EDJE_EXTERNAL_PARAM_TYPE_INT, its value will be stored in the int pointed by ret, returning EINA_TRUE. In any other case, the function returns EINA_FALSE.
Parameters
params List of parameters where to look
key Name of the parameter to fetch
ret Int pointer where to store the value, must not be NULL.
Returns
EINA_TRUE if the parameter was found and is of integer type, EINA_FALSE otherwise.
References edje_external_param_find(), EDJE_EXTERNAL_PARAM_TYPE_INT, _Edje_External_Param::i, and _Edje_External_Param::type.
edje_external_param_string_get()
EAPI Eina_Bool edje_external_param_string_get (const Eina_List * params, const char * key, const char ** ret)
Get the value of the given parameter of string type.
Look for the key parameter in the params list and return its value in ret. If the parameter is found and is of type EDJE_EXTERNAL_PARAM_TYPE_STRING, its value will be stored in the pointer pointed by ret, returning EINA_TRUE. In any other case, the function returns EINA_FALSE.
The string stored in ret must not be freed or modified.
Parameters
params List of parameters where to look
key Name of the parameter to fetch
ret String pointer where to store the value, must not be NULL.
Returns
EINA_TRUE if the parameter was found and is of string type, EINA_FALSE otherwise.
References edje_external_param_find(), EDJE_EXTERNAL_PARAM_TYPE_STRING, _Edje_External_Param::s, and _Edje_External_Param::type.
edje_external_param_type_str()
EAPI const char* edje_external_param_type_str (Edje_External_Param_Type type)
Converts type identifier to string nicer representation.
This may be used to debug or other informational purposes.
Parameters
type the identifier to convert.
Returns
the string with the string representation, or "(unknown)".
References EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_EXTERNAL_PARAM_TYPE_STRING, and type.
edje_external_type_abi_version_get()
EAPI unsigned int edje_external_type_abi_version_get (void)
Return the current ABI version for Edje_External_Type structure.
Always check this number before accessing Edje_External_Type in your own software. If the number is not the same, your software may access invalid memory and crash, or just get garbage values.
Warning
NEVER, EVER define your own Edje_External_Type using the return of this function as it will change as Edje library (libedje.so) changes, but your type definition will not. Instead, use EDJE_EXTERNAL_TYPE_ABI_VERSION.
Summary:
use edje_external_type_abi_version_get() to check.
use EDJE_EXTERNAL_TYPE_ABI_VERSION to define/declare.
Returns
The external ABI version the Edje library was compiled with. That is, the value EDJE_EXTERNAL_TYPE_ABI_VERSION had at that moment.
References EDJE_EXTERNAL_TYPE_ABI_VERSION.
edje_external_type_array_register()
EAPI void edje_external_type_array_register (const Edje_External_Type_Info * array)
Register a batch of types and their information.
When several types will be registered it is recommended to use this function instead of several calls to edje_external_type_register(), as it is faster.
Note
The contents of the array will be referenced directly for as long as the type remains registered, so both the name and info in the array must be kept alive during all this period (usually, the entire program lifetime). The most common case would be to keep the array as a static const type anyway.
Parameters
array NULL terminated array with type name and information. Note that type name or information are referenced directly, so they must be kept alive after this function returns!
Returns
EINA_TRUE on success, EINA_FALSE on failure (like type already registered).
See also
edje_external_type_register()
References _Edje_External_Type::abi_version, EDJE_EXTERNAL_TYPE_ABI_VERSION, ERR, _Edje_External_Type_Info::info, and _Edje_External_Type_Info::name.
edje_external_type_array_unregister()
EAPI void edje_external_type_array_unregister (const Edje_External_Type_Info * array)
Unregister a batch of given external type previously registered.
Parameters
array NULL terminated array, should be the same as the one used to register with edje_external_type_array_register()
See also
edje_external_type_unregister()
References _Edje_External_Type_Info::name.
edje_external_type_get()
EAPI const Edje_External_Type* edje_external_type_get (const char * type_name)
Get the Edje_External_Type that defines an EXTERNAL type registered with the name type_name.
edje_external_type_register()
EAPI Eina_Bool edje_external_type_register (const char * type_name, const Edje_External_Type * type_info)
Register a type to be used by EXTERNAL parts.
Edje supports parts of type EXTERNAL, which will call user defined functions to create and manipulate the object that's allocated in that part. This is done by expecifying in the source property of the part the name of the external to use, which must be one registered with this function.
Parameters
type_name name to register and be known by edje's "source:" parameter of "type: EXTERNAL" parts.
type_info meta-information describing how to interact with it.
Returns
EINA_TRUE on success, EINA_FALSE on failure (like type already registered).
See also
edje_external_type_array_register()
References _Edje_External_Type::abi_version, EDJE_EXTERNAL_TYPE_ABI_VERSION, and ERR.
edje_external_type_unregister()
EAPI Eina_Bool edje_external_type_unregister (const char * type_name)
Unregister a previously registered EXTERNAL type.
Parameters
type_name name to unregister. It should have been registered with edje_external_type_register() before.
Returns
EINA_TRUE on success, EINA_FALSE on failure (like type_name did not exist).
See also
edje_external_type_array_unregister()
edje_file_cache_flush()
EAPI void edje_file_cache_flush (void)
Clean the file cache.
This function cleans the file cache entries, but keeps this cache's size to the last value set.
See also
edje_file_cache_set()
edje_file_cache_get()
Referenced by _edje_file_cache_shutdown().
edje_file_cache_get()
EAPI int edje_file_cache_get (void)
Return the file cache size.
Returns
The file cache size in edje file units. Default is 16.
This function returns the file cache size set by edje_file_cache_set().
See also
edje_file_cache_set()
edje_file_cache_flush()
edje_file_cache_set()
EAPI void edje_file_cache_set (int count)
Set the file cache size.
Parameters
count The file cache size in edje file units. Default is 16.
This function sets the file cache size. Edje keeps this cache in order to prevent duplicates of edje file entries in memory. The file cache size can be retrieved with edje_file_cache_get().
See also
edje_file_cache_get()
edje_file_cache_flush()
edje_file_collection_list()
EAPI Eina_List* edje_file_collection_list (const char * file)
Get a list of groups in an edje file.
Parameters
file The path to the edje file
Returns
The Eina_List of group names (char *)
Note: the list must be freed using edje_file_collection_list_free() when you are done with it.
References _edje_cache_file_coll_open(), _edje_cache_file_unref(), and _Edje_File::collection.
edje_file_collection_list_free()
EAPI void edje_file_collection_list_free (Eina_List * lst)
Free file collection list.
Parameters
lst The Eina_List of groups
Frees the list returned by edje_file_collection_list().
edje_file_data_get()
EAPI char* edje_file_data_get (const char * file, const char * key)
Get data from the file level data block of an edje file.
Parameters
file The path to the .edj file
key The data key
Returns
The string value of the data. Must be freed by the user when no longer needed.
If an edje file is built from the following edc:
data { item: "key1" "value1"; item: "key2" "value2"; } collections { ... }
Then, edje_file_data_get("key1") will return "value1"
References _edje_cache_file_coll_open(), _edje_cache_file_unref(), _Edje_File::data, and edje_string_get().
edje_file_group_exists()
EAPI Eina_Bool edje_file_group_exists (const char * file, const char * glob)
Determine whether a group matching glob exists in an edje file.
Parameters
file The file path
glob A glob to match on
Returns
1 if a match is found, 0 otherwise
References _edje_cache_file_coll_open(), _edje_cache_file_unref(), _Edje_File::collection, _Edje_File::collection_patterns, edje_match_collection_dir_exec(), edje_match_collection_dir_init(), edje_match_patterns_free(), and INF.
edje_fontset_append_get()
EAPI const char* edje_fontset_append_get (void)
Get the edje append fontset.
Returns
The edje append fontset.
This function returns the edje append fontset set by edje_fontset_append_set() function.
See also
edje_fontset_append_set().
References _edje_fontset_append.
edje_fontset_append_set()
EAPI void edje_fontset_append_set (const char * fonts)
Set the edje append fontset.
Parameters
fonts The fontset to append.
This function sets the edje append fontset.
References _edje_fontset_append.
edje_frametime_get()
EAPI double edje_frametime_get (void)
Get edje trasitions' frame time.
Returns
The frame time, in seconds.
This function returns the edje frame time set by edje_frametime_set() or the default value 1/30.
See also
edje_frametime_set()
edje_frametime_set()
EAPI void edje_frametime_set (double t)
Set edje trasitions' frame time.
Parameters
t The frame time, in seconds. Default value is 1/30.
This function sets the edje built-in animations' frame time (thus, affecting their resolution) by calling ecore_animator_frametime_set(). This frame time can be retrieved with edje_frametime_get().
See also
edje_frametime_get()
Examples
edje-perspective.c.
edje_freeze()
EAPI void edje_freeze (void)
Freeze Edje objects.
This function freezes all Edje animations in the current process.
Note
: for freeze a specific object
See also
edje_object_freeze().
edje_thaw()
References _edje_edjes, _edje_freeze_val, and edje_object_freeze().
edje_init()
EAPI int edje_init (void)
Initialize the Edje library.
Returns
The new init count. The initial value is zero.
This function initializes the Ejde library, making the proper calls to internal initialization functions. It will also initialize its dependencies, making calls to eina_init(), ecore_init(), embryo_init() and eet_init(). So, there is no need to call those functions again, in your code. To shutdown Edje there is the function edje_shutdown().
See also
edje_shutdown()
eina_init()
ecore_init()
embryo_init()
eet_init()
Examples
edje-basic.c, edje-box.c, edje-box2.c, edje-color-class.c, edje-drag.c, edje-perspective.c, edje-signals-messages.c, edje-swallow.c, edje-table.c, and edje-text.c.
edje_load_error_str()
EAPI const char* edje_load_error_str (Edje_Load_Error error)
Converts the given Edje file load error code into a string describing it in English.
Parameters
error the error code, a value in Edje_Load_Error.
Returns
Always returns a valid string. If the given error is not supported, "Unknown error" is returned.
edje_object_file_set() is a function which sets an error value, afterwards, which can be fetched with edje_object_load_error_get(). The function in question is meant to be used in conjunction with the latter, for pretty-printing any possible error cause.
Examples
edje-basic.c, and edje-signals-messages.c.
References EDJE_LOAD_ERROR_CORRUPT_FILE, EDJE_LOAD_ERROR_DOES_NOT_EXIST, EDJE_LOAD_ERROR_GENERIC, EDJE_LOAD_ERROR_INCOMPATIBLE_FILE, EDJE_LOAD_ERROR_NONE, EDJE_LOAD_ERROR_PERMISSION_DENIED, EDJE_LOAD_ERROR_RECURSIVE_REFERENCE, EDJE_LOAD_ERROR_RESOURCE_ALLOCATION_FAILED, EDJE_LOAD_ERROR_UNKNOWN_COLLECTION, and EDJE_LOAD_ERROR_UNKNOWN_FORMAT.
edje_message_signal_process()
EAPI void edje_message_signal_process (void)
Process all queued up edje messages.
This function triggers the processing of messages addressed to any (alive) edje objects.
References _edje_message_queue_process().
edje_module_load()
EAPI Eina_Bool edje_module_load (const char * module)
References _edje_module_handle_load().
edje_object_access_part_list_get()
EAPI Eina_List* edje_object_access_part_list_get (const Evas_Object * obj)
Retrieve a list all accessibility part names.
Parameters
obj A valid Evas_Object handle
Returns
A list all accessibility part names on obj
Since
1.7.0
References _edje_fetch(), _Edje_Part::access, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_object_add()
EAPI Evas_Object* edje_object_add (Evas * evas)
Instantiate a new Edje object.
Parameters
evas A valid Evas handle, the canvas to place the new object in
Returns
A handle to the new object created or NULL, on errors.
This function creates a new Edje smart object, returning its Evas_Object handle. An Edje object is useless without a (source) file set to it, so you'd most probably call edje_object_file_set() afterwards, like in:
Evas_Object *edje;
edje = edje_object_add(canvas);
if (!edje)
  {
     fprintf(stderr, "could not create edje object!\n");
     return NULL;
  }
if (!edje_object_file_set(edje, "theme.edj", "group_name"))
  {
     int err = edje_object_load_error_get(edje);
     const char *errmsg = edje_load_error_str(err);
     fprintf(stderr, "could not load 'group_name' from theme.edj: %s",
        errmsg);
     evas_object_del(edje);
     return NULL;
  }
Note
You can get a callback every time edje re-calculates the object (either due to animation or some kind of signal or input). This is called in-line just after the recalculation has occurred. It is a good idea not to go and delete or alter the object inside this callbacks, simply make a note that the recalculation has taken place and then do something about it outside the callback. to register a callback use code like:
evas_object_smart_callback_add(edje_obj, "recalc", my_cb, my_cb_data);
See also
evas_object_smart_callback_add()
Note
Before creating the first Edje object in your code, remember to initialize the library, with edje_init(), or unexpected behavior might occur.
Examples
edje-basic.c, edje-box.c, edje-box2.c, edje-color-class.c, edje-drag.c, edje-perspective.c, edje-signals-messages.c, edje-swallow.c, edje-table.c, and edje-text.c.
References _edje_lib_ref().
edje_object_animation_get()
EAPI Eina_Bool edje_object_animation_get (const Evas_Object * obj)
Get the Edje object's animation state.
Parameters
obj A handle to an Edje object.
Returns
EINA_FALSE on error or if object is not animated; EINA_TRUE if animated.
This function returns if the animation is stopped or not. The animation state is set by edje_object_animation_set().
See also
edje_object_animation_set().
References _edje_fetch(), _Edje::delete_me, and _Edje::no_anim.
edje_object_animation_set()
EAPI void edje_object_animation_set (Evas_Object * obj, Eina_Bool on)
Set the object's animation state.
Parameters
obj A handle to an Edje object.
on The animation state. EINA_TRUE to starts or EINA_FALSE to stops.
This function starts or stops an Edje object's animation. The information if it's stopped can be retrieved by edje_object_animation_get().
See also
edje_object_animation_get()
References _edje_block(), _edje_block_break(), _edje_emit(), _edje_fetch(), _edje_freeze(), _edje_program_run_iterate(), _edje_thaw(), _edje_unblock(), _Edje::actions, _Edje::delete_me, edje_object_animation_set(), EDJE_PART_TYPE_GROUP, _Edje::no_anim, _Edje_Real_Part::part, _Edje_Running_Program::program, _Edje_Running_Program::start_time, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, _Edje_Program::time, TO_DOUBLE, _Edje_Program::tween, and _Edje_Part::type.
Referenced by edje_object_animation_set().
edje_object_calc_force()
EAPI void edje_object_calc_force (Evas_Object * obj)
Force a Size/Geometry calculation.
Parameters
obj A valid Evas_Object handle
Forces the object obj to recalculation layout regardless of freeze/thaw.
Examples
edje-perspective.c.
References _edje_fetch(), _edje_freeze_val, _edje_recalc_do(), _Edje::dirty, and _Edje::freeze.
Referenced by edje_edit_part_clip_to_set(), edje_edit_part_effect_set(), edje_edit_part_scale_set(), edje_edit_state_color3_set(), edje_edit_state_image_border_fill_set(), edje_edit_state_image_border_set(), edje_edit_state_text_size_set(), edje_edit_state_visible_set(), edje_object_scale_set(), and edje_scale_set().
edje_object_color_class_del()
EAPI void edje_object_color_class_del (Evas_Object * obj, const char * color_class)
Delete the object color class.
Parameters
obj The edje object's reference.
color_class The color class to be deleted.
This function deletes any values at the object level for the specified object and color class.
Note
Deleting the color class will revert it to the values defined by edje_color_class_set() or the color class defined in the theme file.
Deleting the color class will emit the signal "color_class,del" for the given Edje object.
Examples
edje-color-class.c.
References _edje_emit(), _edje_fetch(), _edje_recalc(), _Edje::color_classes, _Edje::dirty, edje_object_color_class_del(), EDJE_PART_TYPE_GROUP, _Edje_Real_Part::part, _Edje::recalc_call, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_object_color_class_del().
edje_object_color_class_get()
EAPI Eina_Bool edje_object_color_class_get (const Evas_Object * o, const char * color_class, int * r, int * g, int * b, int * a, int * r2, int * g2, int * b2, int * a2, int * r3, int * g3, int * b3, int * a3)
Gets the object color class.
Parameters
o A valid Evas_Object handle
color_class
r Object Red value
g Object Green value
b Object Blue value
a Object Alpha value
r2 Outline Red value
g2 Outline Green value
b2 Outline Blue value
a2 Outline Alpha value
r3 Shadow Red value
g3 Shadow Green value
b3 Shadow Blue value
a3 Shadow Alpha value
Returns
EINA_TRUE if found or EINA_FALSE if not found and all values are zeroed.
This function gets the color values for an object level color class. If no explicit object color is set, then global values will be used.
The first color is the object, the second is the text outline, and the third is the text shadow. (Note that the second two only apply to text parts).
Note
unlike Evas, Edje colors are not pre-multiplied. That is, half-transparent white is 255 255 255 128.
References _edje_color_class_find(), _edje_fetch(), and S.
edje_object_color_class_set()
EAPI Eina_Bool edje_object_color_class_set (Evas_Object * obj, const char * color_class, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Sets the object color class.
Parameters
obj A valid Evas_Object handle
color_class
r Object Red value
g Object Green value
b Object Blue value
a Object Alpha value
r2 Outline Red value
g2 Outline Green value
b2 Outline Blue value
a2 Outline Alpha value
r3 Shadow Red value
g3 Shadow Green value
b3 Shadow Blue value
a3 Shadow Alpha value
This function sets the color values for an object level color class. This will cause all edje parts in the specified object that have the specified color class to have their colors multiplied by these values.
The first color is the object, the second is the text outline, and the third is the text shadow. (Note that the second two only apply to text parts).
Setting color emits a signal "color_class,set" with source being the given color.
Note
unlike Evas, Edje colors are not pre-multiplied. That is, half-transparent white is 255 255 255 128.
Examples
edje-color-class.c.
References _edje_emit(), _edje_fetch(), _edje_recalc(), _Edje_Color_Class::a, _Edje_Color_Class::a2, _Edje_Color_Class::a3, _Edje_Color_Class::b, _Edje_Color_Class::b2, _Edje_Color_Class::b3, _Edje::color_classes, _Edje::dirty, edje_object_color_class_set(), EDJE_PART_TYPE_GROUP, _Edje_Color_Class::g, _Edje_Color_Class::g2, _Edje_Color_Class::g3, _Edje_Color_Class::name, _Edje_Real_Part::part, _Edje_Color_Class::r, _Edje_Color_Class::r2, _Edje_Color_Class::r3, _Edje::recalc_call, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_object_color_class_set().
edje_object_data_get()
EAPI const char* edje_object_data_get (const Evas_Object * obj, const char * key)
Retrive an EDC data field's value from a given Edje object's group.
Parameters
obj A handle to an Edje object
key The data field's key string
Returns
The data's value string. Must not be freed.
This function fetches an EDC data field's value, which is declared on the objects building EDC file, under its group. EDC data blocks are most commonly used to pass arbitrary parameters from an application's theme to its code.
They look like the following:
collections {
  group {
    name: "a_group";
    data {
  item: "key1" "value1";
  item: "key2" "value2";
    }
  }
}
EDC data fields always hold strings as values, hence the return type of this function. Check the complete syntax reference for EDC files.
Warning
Do not confuse this call with edje_file_data_get(), which queries for a global EDC data field on an EDC declaration file.
See also
edje_object_file_set()
Examples
edje-basic.c.
References _edje_fetch(), _Edje::collection, _Edje_Part_Collection::data, and edje_string_get().
edje_object_file_get()
EAPI void edje_object_file_get (const Evas_Object * obj, const char ** file, const char ** group)
Get the file and group name that a given Edje object is bound to.
Parameters
obj A handle to an Edje object
file A pointer to a variable whero to store the file's path
group A pointer to a variable where to store the group name in
This gets the EDJ file's path, with the respective group set for the given Edje object. If obj is either not an Edje file, or has not had its file/group set previously, by edje_object_file_set(), then both file and group will be set to NULL, indicating an error.
See also
edje_object_file_set()
Note
Use NULL pointers on the file/group components you're not interested in: they'll be ignored by the function.
References _edje_fetch(), _Edje::group, and _Edje::path.
edje_object_file_set()
EAPI Eina_Bool edje_object_file_set (Evas_Object * obj, const char * file, const char * group)
Sets the EDJ file (and group within it) to load an Edje object's contents from.
Parameters
obj A handle to an Edje object
file The path to the EDJ file to load from
group The name of the group, in file, which implements an Edje object
Returns
EINA_TRUE, on success or EINA_FALSE, on errors (check edje_object_load_error_get() after this call to get errors causes)
Edje expects EDJ files, which are theming objects' descriptions and resources packed together in an EET file, to read Edje object definitions from. They usually are created with the .edj extension. EDJ files, in turn, are assembled from textual object description files, where one describes Edje objects declaratively – the EDC files (see the syntax for those files).
Those description files were designed so that many Edje object definitions – also called groups (or collections) – could be packed together in the same EDJ file, so that a whole application's theme could be packed in one file only. This is the reason for the group argument.
Use this function after you instantiate a new Edje object, so that you can "give him life", telling where to get its contents from.
See also
edje_object_add()
edje_object_file_get()
Examples
edje-basic.c, edje-box.c, edje-box2.c, edje-color-class.c, edje-drag.c, edje-perspective.c, edje-signals-messages.c, edje-swallow.c, edje-table.c, and edje-text.c.
References _edje_fetch(), _edje_object_orientation_inform(), _Edje::api, and _Edje_Smart_Api::file_set.
edje_object_freeze()
EAPI int edje_object_freeze (Evas_Object * obj)
Freezes the Edje object.
Parameters
obj A handle to an Edje object.
Returns
The frozen state or 0 on Error
This function puts all changes on hold. Successive freezes will nest, requiring an equal number of thaws.
See also
edje_object_thaw()
References _edje_fetch(), _edje_freeze(), edje_object_freeze(), EDJE_PART_TYPE_GROUP, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_freeze(), and edje_object_freeze().
edje_object_item_provider_set()
EAPI void edje_object_item_provider_set (Evas_Object * obj, Edje_Item_Provider_Cb func, void * data)
Set the function that provides item objects for named items in an edje entry text.
Parameters
obj A valid Evas Object handle
func The function to call (or NULL to disable) to get item objects
data The data pointer to pass to the func callback
Item objects may be deleted any time by Edje, and will be deleted when the Edje object is deleted (or file is set to a new file).
References _edje_fetch(), _Edje::data, _Edje::func, and _Edje::item_provider.
edje_object_load_error_get()
EAPI Edje_Load_Error edje_object_load_error_get (const Evas_Object * obj)
Gets the (last) file loading error for a given Edje object.
Parameters
obj A handlet to an Edje object
Returns
The Edje loading error, one of:
EDJE_LOAD_ERROR_NONE
EDJE_LOAD_ERROR_GENERIC
EDJE_LOAD_ERROR_DOES_NOT_EXIST
EDJE_LOAD_ERROR_PERMISSION_DENIED
EDJE_LOAD_ERROR_RESOURCE_ALLOCATION_FAILED
EDJE_LOAD_ERROR_CORRUPT_FILE
EDJE_LOAD_ERROR_UNKNOWN_FORMAT
EDJE_LOAD_ERROR_INCOMPATIBLE_FILE
EDJE_LOAD_ERROR_UNKNOWN_COLLECTION
EDJE_LOAD_ERROR_RECURSIVE_REFERENCE
This function is meant to be used after an Edje EDJ file loading, what takes place with the edje_object_file_set() function. If that function does not return EINA_TRUE, one should check for the reason of failure with this one.
See also
edje_load_error_str()
Examples
edje-basic.c, and edje-signals-messages.c.
References _edje_fetch(), EDJE_LOAD_ERROR_NONE, and _Edje::load_error.
edje_object_message_handler_set()
EAPI void edje_object_message_handler_set (Evas_Object * obj, Edje_Message_Handler_Cb func, void * data)
Set an Edje message handler function for a given Edje object.
Parameters
obj A handle to an Edje object
func The function to handle messages coming from obj
data Auxiliary data to be passed to func
Edje messages are one of the communication interfaces between code and a given Edje object's theme. With messages, one can communicate values beyond strings (which are the subject of Edje signals – see edje_object_signal_emit()), like float and integer numbers. Moreover, messages can be identified by integer numbers. See Edje_Message_Type for the full list of message types.
For scriptable programs on an Edje object's defining EDC file which send messages with the send_message() primitive, one can attach handler functions, to be called in the code which creates that object (see the syntax for EDC files).
This function associates a message handler function and the attached data pointer to the object obj.
See also
edje_object_message_send()
Examples
edje-signals-messages.c.
References _edje_fetch(), and _edje_message_cb_set().
edje_object_message_send()
EAPI void edje_object_message_send (Evas_Object * obj, Edje_Message_Type type, int id, void * msg)
Send an (Edje) message to a given Edje object.
Parameters
obj A handle to an Edje object
type The type of message to send to obj
id A identification number for the message to be sent
msg The message's body, a struct depending on type
This function sends an Edje message to obj and to all of its child objects, if it has any (swallowed objects are one kind of child object). type and msg must be matched accordingly, as documented in Edje_Message_Type.
The id argument as a form of code and theme defining a common interface on message communication. One should define the same IDs on both code and EDC declaration (see the syntax for EDC files), to individualize messages (binding them to a given context).
The function to handle messages arriving from obj is set with edje_object_message_handler_set().
Examples
edje-signals-messages.c.
Referenced by _edje_emit_full().
edje_object_message_signal_process()
EAPI void edje_object_message_signal_process (Evas_Object * obj)
Process an object's message queue.
Parameters
obj A handle to an Edje object.
This function goes through the object message queue processing the pending messages for this specific Edje object. Normally they'd be processed only at idle time.
References _edje_fetch(), and _Edje::groups.
edje_object_mirrored_get()
EAPI Eina_Bool edje_object_mirrored_get (const Evas_Object * obj)
Get the RTL orientation for this object.
You can RTL orientation explicitly with edje_object_mirrored_set.
Parameters
obj A handle to an Edje object.
Returns
EINA_TRUE if the flag is set or EINA_FALSE if not.
Since
1.1.0
References _edje_fetch(), and _Edje::is_rtl.
Referenced by _edje_object_orientation_inform(), and _edje_part_description_find().
edje_object_mirrored_set()
EAPI void edje_object_mirrored_set (Evas_Object * obj, Eina_Bool rtl)
Set the RTL orientation for this object.
Parameters
obj A handle to an Edje object.
rtl new value of flag EINA_TRUE/EINA_FALSE
Since
1.1.0
References _edje_fetch(), _edje_object_orientation_inform(), _edje_part_description_apply(), _edje_recalc_do(), _Edje_Real_Part::chosen_description, _Edje_Real_Part_State::description, _Edje::is_rtl, _Edje_Part_Description_Common::name, _Edje_Real_Part::param1, _Edje_Part_Description_Common::state, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part_Description_Common::value.
edje_object_part_box_append()
EAPI Eina_Bool edje_object_part_box_append (Evas_Object * obj, const char * part, Evas_Object * child)
Appends an object to the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to append
Returns
EINA_TRUE: Successfully added.
EINA_FALSE: An error occurred.
Appends child to the box indicated by part.
See also
edje_object_part_box_prepend()
edje_object_part_box_insert_before()
edje_object_part_box_insert_at()
Examples
edje-box.c, and edje-box2.c.
References _edje_fetch(), _edje_real_part_box_append(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_BOX, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_box_insert_at()
EAPI Eina_Bool edje_object_part_box_insert_at (Evas_Object * obj, const char * part, Evas_Object * child, unsigned int pos)
Inserts an object to the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to insert
pos The position where to insert child
Returns
EINA_TRUE: Successfully added.
EINA_FALSE: An error occurred.
Adds child to the box indicated by part, in the position given by pos.
See also
edje_object_part_box_append()
edje_object_part_box_prepend()
edje_object_part_box_insert_before()
Examples
edje-box.c, and edje-box2.c.
References _edje_fetch(), _edje_real_part_box_insert_at(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_BOX, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_box_insert_before()
EAPI Eina_Bool edje_object_part_box_insert_before (Evas_Object * obj, const char * part, Evas_Object * child, const Evas_Object * reference)
Adds an object to the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to insert
reference The object to be used as reference
Returns
EINA_TRUE: Successfully added.
EINA_FALSE: An error occurred.
Inserts child in the box given by part, in the position marked by reference.
See also
edje_object_part_box_append()
edje_object_part_box_prepend()
edje_object_part_box_insert_at()
Examples
edje-box.c.
References _edje_fetch(), _edje_real_part_box_insert_before(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_BOX, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_box_prepend()
EAPI Eina_Bool edje_object_part_box_prepend (Evas_Object * obj, const char * part, Evas_Object * child)
Prepends an object to the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to prepend
Returns
EINA_TRUE: Successfully added.
EINA_FALSE: An error occurred.
Prepends child to the box indicated by part.
See also
edje_object_part_box_append()
edje_object_part_box_insert_before()
edje_object_part_box_insert_at()
References _edje_fetch(), _edje_real_part_box_prepend(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_BOX, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_box_remove()
EAPI Evas_Object* edje_object_part_box_remove (Evas_Object * obj, const char * part, Evas_Object * child)
Removes an object from the box.
Parameters
obj A valid Evas_Object handle
part The part name
child The object to remove
Returns
Pointer to the object removed, or NULL.
Removes child from the box indicated by part.
See also
edje_object_part_box_remove_at()
edje_object_part_box_remove_all()
Examples
edje-box.c.
References _edje_fetch(), _edje_real_part_box_remove(), _edje_real_part_recursive_get(), _edje_user_definition_free(), _Edje_User_Defined::box, EDJE_PART_TYPE_BOX, EDJE_USER_BOX_PACK, _Edje_Real_Part::part, _Edje_User_Defined::part, _Edje_Part::type, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_box_remove_all()
EAPI Eina_Bool edje_object_part_box_remove_all (Evas_Object * obj, const char * part, Eina_Bool clear)
Removes all elements from the box.
Parameters
obj A valid Evas_Object handle
part The part name
clear Delete objects on removal
Returns
1: Successfully cleared.
0: An error occurred.
Removes all the external objects from the box indicated by part. Elements created from the theme will not be removed.
See also
edje_object_part_box_remove()
edje_object_part_box_remove_at()
Examples
edje-box.c.
References _edje_fetch(), _edje_real_part_box_remove_all(), _edje_real_part_recursive_get(), _edje_user_definition_free(), EDJE_PART_TYPE_BOX, EDJE_USER_BOX_PACK, _Edje_Real_Part::part, _Edje_User_Defined::part, _Edje_Part::type, _Edje_User_Defined::type, and _Edje::user_defined.
edje_object_part_box_remove_at()
EAPI Evas_Object* edje_object_part_box_remove_at (Evas_Object * obj, const char * part, unsigned int pos)
Removes an object from the box.
Parameters
obj A valid Evas_Object handle
part The part name
pos The position index of the object (starts counting from 0)
Returns
Pointer to the object removed, or NULL.
Removes from the box indicated by part, the object in the position pos.
See also
edje_object_part_box_remove()
edje_object_part_box_remove_all()
Examples
edje-box2.c.
References _edje_fetch(), _edje_real_part_box_remove_at(), _edje_real_part_recursive_get(), _edje_user_definition_free(), _Edje_User_Defined::box, EDJE_PART_TYPE_BOX, EDJE_USER_BOX_PACK, _Edje_Real_Part::part, _Edje_User_Defined::part, _Edje_Part::type, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_dir_get()
EAPI Edje_Drag_Dir edje_object_part_drag_dir_get (const Evas_Object * obj, const char * part)
Determine dragable directions.
Parameters
obj A valid Evas_Object handle
part The part name
The dragable directions are defined in the EDC file, inside the dragable section, by the attributes x and y. See the Edje Data Collection reference for more information.
Returns
EDJE_DRAG_DIR_NONE: Not dragable
EDJE_DRAG_DIR_X: Dragable in X direction
EDJE_DRAG_DIR_Y: Dragable in Y direction
EDJE_DRAG_DIR_XY: Dragable in X & Y directions
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Part::dragable, EDJE_DRAG_DIR_NONE, EDJE_DRAG_DIR_X, EDJE_DRAG_DIR_XY, EDJE_DRAG_DIR_Y, _Edje_Real_Part::part, _Edje_Part_Dragable::x, and _Edje_Part_Dragable::y.
edje_object_part_drag_page()
EAPI Eina_Bool edje_object_part_drag_page (Evas_Object * obj, const char * part, double dx, double dy)
Pages x,y steps.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x step
dy The y step
Pages x,y where the increment is defined by edje_object_part_drag_page_set.
Values for dx and dy are real numbers that range from 0 to 1.
Warning
Paging is bugged!
See also
edje_object_part_drag_step()
Examples
edje-drag.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part_Drag::count, _Edje_Real_Part_Drag::down, _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_PAGE, FLOAT_T, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_page_get()
EAPI Eina_Bool edje_object_part_drag_page_get (const Evas_Object * obj, const char * part, double * dx, double * dy)
Gets the page step increments.
Parameters
obj A valid Evas_Object handle
part The part name
dx The dx page increment pointer
dy The dy page increment pointer
Gets the x,y page step increments for the dragable object.
See also
edje_object_part_drag_page_set()
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::drag, _Edje_Real_Part_Drag::page, TO_DOUBLE, _Edje_Position_Scale::x, and _Edje_Position_Scale::y.
edje_object_part_drag_page_set()
EAPI Eina_Bool edje_object_part_drag_page_set (Evas_Object * obj, const char * part, double dx, double dy)
Sets the page step increments.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x page step increment
dy The y page step increment
Sets the x,y page step increment values.
Values for dx and dy are real numbers that range from 0 to 1, representing the relative size of the dragable area on that axis by which the part will be moved.
See also
edje_object_part_drag_page_get()
Examples
edje-drag.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_PAGE, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_size_get()
EAPI Eina_Bool edje_object_part_drag_size_get (const Evas_Object * obj, const char * part, double * dw, double * dh)
Get the dragable object size.
Parameters
obj A valid Evas_Object handle
part The part name
dw The drag width pointer
dh The drag height pointer
Gets the dragable object size.
See also
edje_object_part_drag_size_set()
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::drag, _Edje_Real_Part_Drag::size, TO_DOUBLE, _Edje_Position_Scale::x, and _Edje_Position_Scale::y.
edje_object_part_drag_size_set()
EAPI Eina_Bool edje_object_part_drag_size_set (Evas_Object * obj, const char * part, double dw, double dh)
Set the dragable object size.
Parameters
obj A valid Evas_Object handle
part The part name
dw The drag width
dh The drag height
Values for dw and dh are real numbers that range from 0 to 1, representing the relative size of the dragable area on that axis.
Sets the size of the dragable object.
See also
edje_object_part_drag_size_get()
Examples
edje-drag.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part::drag, _Edje_User_Defined::drag_size, EDJE_USER_DRAG_SIZE, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_step()
EAPI Eina_Bool edje_object_part_drag_step (Evas_Object * obj, const char * part, double dx, double dy)
Steps the dragable x,y steps.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x step
dy The y step
Steps x,y where the step increment is the amount set by edje_object_part_drag_step_set.
Values for dx and dy are real numbers that range from 0 to 1.
See also
edje_object_part_drag_page()
Examples
edje-drag.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part_Drag::count, _Edje_Real_Part_Drag::down, _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_STEP, FLOAT_T, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_step_get()
EAPI Eina_Bool edje_object_part_drag_step_get (const Evas_Object * obj, const char * part, double * dx, double * dy)
Gets the drag step increment values.
Parameters
obj A valid Evas_Object handle
part The part
dx The x step increment pointer
dy The y step increment pointer
Gets the x and y step increments for the dragable object.
See also
edje_object_part_drag_step_set()
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::drag, _Edje_Real_Part_Drag::step, TO_DOUBLE, _Edje_Position_Scale::x, and _Edje_Position_Scale::y.
edje_object_part_drag_step_set()
EAPI Eina_Bool edje_object_part_drag_step_set (Evas_Object * obj, const char * part, double dx, double dy)
Sets the drag step increment.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x step amount
dy The y step amount
Sets the x,y step increments for a dragable object.
Values for dx and dy are real numbers that range from 0 to 1, representing the relative size of the dragable area on that axis by which the part will be moved.
See also
edje_object_part_drag_step_get()
Examples
edje-drag.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_STEP, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_drag_value_get()
EAPI Eina_Bool edje_object_part_drag_value_get (const Evas_Object * obj, const char * part, double * dx, double * dy)
Get the dragable object location.
Parameters
obj A valid Evas_Object handle
part The part name
dx The X value pointer
dy The Y value pointer
Values for dx and dy are real numbers that range from 0 to 1, representing the relative position to the dragable area on that axis.
See also
edje_object_part_drag_value_set()
Gets the drag location values.
Examples
edje-drag.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::drag, _Edje_Part::dragable, _Edje_Real_Part::part, TO_DOUBLE, _Edje_Real_Part_Drag::val, _Edje_Position_Scale::x, _Edje_Part_Dragable::x, _Edje_Position_Scale::y, and _Edje_Part_Dragable::y.
edje_object_part_drag_value_set()
EAPI Eina_Bool edje_object_part_drag_value_set (Evas_Object * obj, const char * part, double dx, double dy)
Set the dragable object location.
Parameters
obj A valid Evas_Object handle
part The part name
dx The x value
dy The y value
Places the dragable object at the given location.
Values for dx and dy are real numbers that range from 0 to 1, representing the relative position to the dragable area on that axis.
This value means, for the vertical axis, that 0.0 will be at the top if the first parameter of y in the dragable part theme is 1, and at bottom if it is -1.
For the horizontal axis, 0.0 means left if the first parameter of x in the dragable part theme is 1, and right if it is -1.
See also
edje_object_part_drag_value_get()
Examples
edje-drag.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part_Drag::count, _Edje_Real_Part_Drag::down, _Edje_Real_Part::drag, _Edje_User_Defined::drag_position, EDJE_USER_DRAG_VALUE, _Edje_User_Defined::part, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_exists()
EAPI Eina_Bool edje_object_part_exists (const Evas_Object * obj, const char * part)
Check if an Edje part exists in a given Edje object's group definition.
Parameters
obj A handle to an Edje object
part The part's name to check for existence in obj's group
Returns
EINA_TRUE, if the Edje part exists in obj's group or EINA_FALSE, otherwise (and on errors)
This function returns if a given part exists in the Edje group bound to object obj (with edje_object_file_set()).
This call is useful, for example, when one could expect or not a given GUI element, depending on the theme applied to obj.
Examples
edje-basic.c.
References _edje_fetch(), and _edje_real_part_recursive_get().
edje_object_part_external_content_get()
EAPI Evas_Object* edje_object_part_external_content_get (const Evas_Object * obj, const char * part, const char * content)
Get an object contained in an part of type EXTERNAL.
The content string must not be NULL. Its actual value depends on the code providing the EXTERNAL.
Parameters
obj The Edje object
part The name of the part holding the EXTERNAL
content A string identifying which content from the EXTERNAL to get
References _edje_external_content_get(), _edje_fetch(), _edje_real_part_recursive_get(), ERR, and _Edje_Real_Part::swallowed_object.
edje_object_part_external_object_get()
EAPI Evas_Object* edje_object_part_external_object_get (const Evas_Object * obj, const char * part)
Get the object created by this external part.
Parts of type external creates the part object using information provided by external plugins. It's somehow like "swallow" (edje_object_part_swallow()), but it's all set automatically.
This function returns the part created by such external plugins and being currently managed by this Edje.
Note
Almost all swallow rules apply: you should not move, resize, hide, show, set the color or clipper of such part. It's a bit more restrictive as one must never delete this object!
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The externally created object, or NULL if there is none or part is not an external.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), EDJE_PART_TYPE_EXTERNAL, ERR, _Edje_Part::name, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, and _Edje_Part::type.
edje_object_part_external_param_get()
EAPI Eina_Bool edje_object_part_external_param_get (const Evas_Object * obj, const char * part, Edje_External_Param * param)
Get the parameter for the external part.
Parts of type external may carry extra properties that have meanings defined by the external plugin. For instance, it may be a string that defines a button label. This property can be modified by state parameters, by explicit calls to edje_object_part_external_param_set() or getting the actual object with edje_object_part_external_object_get() and calling native functions.
This function asks the external plugin what is the current value, independent on how it was set.
Parameters
obj A valid Evas_Object handle
part The part name
param the parameter details. It is used as both input and output variable. This pointer should be valid, and the parameter must exist in Edje_External_Type::parameters_info, with the exact type, otherwise the operation will fail and EINA_FALSE will be returned.
Returns
EINA_TRUE if everything went fine and param members are filled with information, EINA_FALSE on errors and param member values are not set or valid.
References _edje_external_param_get(), _edje_fetch(), _edje_real_part_recursive_get(), ERR, and _Edje_External_Param::name.
edje_object_part_external_param_set()
EAPI Eina_Bool edje_object_part_external_param_set (Evas_Object * obj, const char * part, const Edje_External_Param * param)
Set the parameter for the external part.
Parts of type external may carry extra properties that have meanings defined by the external plugin. For instance, it may be a string that defines a button label and setting this property will change that label on the fly.
Note
external parts have parameters set when they change states. Those parameters will never be changed by this function. The interpretation of how state_set parameters and param_set will interact is up to the external plugin.
this function will not check if parameter value is valid using Edje_External_Param_Info minimum, maximum, valid choices and others. However these should be checked by the underlying implementation provided by the external plugin. This is done for performance reasons.
Parameters
obj A valid Evas_Object handle
part The part name
param the parameter details, including its name, type and actual value. This pointer should be valid, and the parameter must exist in Edje_External_Type::parameters_info, with the exact type, otherwise the operation will fail and EINA_FALSE will be returned.
Returns
EINA_TRUE if everything went fine, EINA_FALSE on errors.
References _edje_external_param_set(), _edje_fetch(), _edje_real_part_recursive_get(), ERR, and _Edje_External_Param::name.
edje_object_part_external_param_type_get()
EAPI Edje_External_Param_Type edje_object_part_external_param_type_get (const Evas_Object * obj, const char * part, const char * param)
Facility to query the type of the given parameter of the given part.
Parameters
obj A valid Evas_Object handle
part The part name
param the parameter name to use.
Returns
EDJE_EXTERNAL_PARAM_TYPE_MAX on errors, or another value from Edje_External_Param_Type on success.
References _edje_fetch(), _edje_real_part_recursive_get(), EDJE_EXTERNAL_PARAM_TYPE_MAX, ERR, _Edje_External_Param_Info::name, _Edje_Real_Part::swallowed_object, _Edje_External_Param_Info::type, and type.
edje_object_part_geometry_get()
EAPI Eina_Bool edje_object_part_geometry_get (const Evas_Object * obj, const char * part, Evas_Coord * x, Evas_Coord * y, Evas_Coord * w, Evas_Coord * h)
Retrieve the geometry of a given Edje part, in a given Edje object's group definition, relative to the object's area
Parameters
obj A handle to an Edje object
part The Edje part's name
x A pointer to a variable where to store the part's x coordinate
y A pointer to a variable where to store the part's y coordinate
w A pointer to a variable where to store the part's width
h A pointer to a variable where to store the part's height
This function gets the geometry of an Edje part within its group. The x and y coordinates are relative to the top left corner of the whole obj object's area.
Note
Use NULL pointers on the geometry components you're not interested in: they'll be ignored by the function.
On failure, this function will make all non-NULL geometry pointers' pointed variables be set to zero.
Examples
edje-basic.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::h, _Edje_Real_Part::w, _Edje_Real_Part::x, and _Edje_Real_Part::y.
edje_object_part_object_get()
EAPI const Evas_Object* edje_object_part_object_get (const Evas_Object * obj, const char * part)
Get a handle to the Evas object implementing a given Edje part, in an Edje object.
Parameters
obj A handle to an Edje object
part The Edje part's name
Returns
A pointer to the Evas object implementing the given part, or NULL on failure (e.g. the given part doesn't exist)
This function gets a pointer of the Evas object corresponding to a given part in the obj object's group.
You should never modify the state of the returned object (with evas_object_move() or evas_object_hide() for example), because it's meant to be managed by Edje, solely. You are safe to query information about its current state (with evas_object_visible_get() or evas_object_color_get() for example), though.
Examples
edje-basic.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), and _Edje_Real_Part::object.
edje_object_part_state_get()
EAPI const char* edje_object_part_state_get (const Evas_Object * obj, const char * part, double * val_ret)
Returns the state of the Edje part.
Parameters
obj A valid Evas_Object handle
part The part name
val_ret
Returns
The part state:
"default" for the default state
"" for other states
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _Edje_Real_Part::chosen_description, _Edje_Real_Part_State::description, INF, _Edje_Part_Description_Common::name, _Edje_Real_Part::param1, _Edje_Part_Description_Common::state, and _Edje_Part_Description_Common::value.
edje_object_part_swallow()
EAPI Eina_Bool edje_object_part_swallow (Evas_Object * obj, const char * part, Evas_Object * obj_swallow)
"Swallows" an object into one of the Edje object SWALLOW parts.
Parameters
obj A valid Edje object handle
part The swallow part's name
obj_swallow The object to occupy that part
Swallowing an object into an Edje object is, for a given part of type SWALLOW in the EDC group which gave life to obj, to set an external object to be controlled by obj, being displayed exactly over that part's region inside the whole Edje object's viewport.
From this point on, obj will have total control over obj_swallow's geometry and visibility. For instance, if obj is visible, as in evas_object_show(), the swallowed object will be visible too – if the given SWALLOW part it's in is also visible. Other actions on obj will also reflect on the swallowed object as well (e.g. resizing, moving, raising/lowering, etc.).
Finally, all internal changes to part, specifically, will reflect on the displaying of obj_swallow, for example state changes leading to different visibility states, geometries, positions, etc.
If an object has already been swallowed into this part, then it will first be unswallowed (as in edje_object_part_unswallow()) before the new object is swallowed.
Note
obj won't delete the swallowed object once it is deleted – obj_swallow will get to an unparented state again.
For more details on EDC SWALLOW parts, see syntaxreference".
Examples
edje-swallow.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_real_part_swallow(), _edje_recalc_do(), DBG, _Edje_Real_Part::edje, edje_object_part_unswallow(), EDJE_PART_TYPE_SWALLOW, ERR, _Edje_Part::name, _Edje::obj, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, and _Edje_Part::type.
edje_object_part_swallow_get()
EAPI Evas_Object* edje_object_part_swallow_get (const Evas_Object * obj, const char * part)
Get the object currently swallowed by a part.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The swallowed object, or NULL if there is none.
Examples
edje-swallow.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), and _Edje_Real_Part::swallowed_object.
edje_object_part_table_child_get()
EAPI Evas_Object* edje_object_part_table_child_get (const Evas_Object * obj, const char * part, unsigned int col, unsigned int row)
Retrieve a child from a table.
Parameters
obj A valid Evas_Object handle
part The part name
col The column of the child to get
row The row of the child to get
Returns
The child Evas_Object
References _edje_fetch(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TABLE, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_table_clear()
EAPI Eina_Bool edje_object_part_table_clear (Evas_Object * obj, const char * part, Eina_Bool clear)
Removes all object from the table.
Parameters
obj A valid Evas_Object handle
part The part name
clear If set, will delete subobjs on remove
Returns
EINA_TRUE clear the table, EINA_FALSE on failure
Removes all object from the table indicated by part, except the internal ones set from the theme.
Examples
edje-table.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_real_part_table_clear(), EDJE_PART_TYPE_TABLE, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_table_col_row_size_get()
EAPI Eina_Bool edje_object_part_table_col_row_size_get (const Evas_Object * obj, const char * part, int * cols, int * rows)
Gets the number of columns and rows the table has.
Parameters
obj A valid Evas_Object handle
part The part name
cols Pointer where to store number of columns (can be NULL)
rows Pointer where to store number of rows (can be NULL)
Returns
EINA_TRUE get some data, EINA_FALSE on failure
Retrieves the size of the table in number of columns and rows.
Examples
edje-table.c.
References _edje_fetch(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TABLE, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_table_pack()
EAPI Eina_Bool edje_object_part_table_pack (Evas_Object * obj, const char * part, Evas_Object * child_obj, unsigned short col, unsigned short row, unsigned short colspan, unsigned short rowspan)
Packs an object into the table.
Parameters
obj A valid Evas_Object handle
part The part name
child_obj The object to pack in
col The column to place it in
row The row to place it in
colspan Columns the child will take
rowspan Rows the child will take
Returns
EINA_TRUE object was added, EINA_FALSE on failure
Packs an object into the table indicated by part.
Examples
edje-table.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_real_part_table_pack(), EDJE_PART_TYPE_TABLE, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_table_unpack()
EAPI Eina_Bool edje_object_part_table_unpack (Evas_Object * obj, const char * part, Evas_Object * child_obj)
Removes an object from the table.
Parameters
obj A valid Evas_Object handle
part The part name
child_obj The object to pack in
Returns
EINA_TRUE object removed, EINA_FALSE on failure
Removes an object from the table indicated by part.
Examples
edje-table.c.
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_real_part_table_unpack(), _edje_user_definition_free(), EDJE_PART_TYPE_TABLE, EDJE_USER_TABLE_PACK, _Edje_Real_Part::part, _Edje_User_Defined::part, _Edje_User_Defined::table, _Edje_Part::type, _Edje_User_Defined::type, _Edje_User_Defined::u, and _Edje::user_defined.
edje_object_part_text_anchor_geometry_get()
EAPI const Eina_List* edje_object_part_text_anchor_geometry_get (const Evas_Object * obj, const char * part, const char * anchor)
Return a list of Evas_Textblock_Rectangle anchor rectangles.
Parameters
obj A valid Evas_Object handle
part The part name
anchor The anchor name
Returns
The list of anchor rects (const Evas_Textblock_Rectangle *), do not modify! Geometry is relative to entry part.
This function return a list of Evas_Textblock_Rectangle anchor rectangles.
References _edje_entry_anchor_geometry_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_anchor_list_get()
EAPI const Eina_List* edje_object_part_text_anchor_list_get (const Evas_Object * obj, const char * part)
Return a list of char anchor names.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The list of anchors (const char *), do not modify!
This function returns a list of char anchor names.
References _edje_entry_anchors_list(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_append()
EAPI void edje_object_part_text_append (Evas_Object * obj, const char * part, const char * text)
Insert text for an object part.
Parameters
obj A valid Evas Object handle
part The part name
text The text string
This function inserts the text for an object part at the end; It does not move the cursor.
Since
1.1
References _edje_fetch(), _edje_object_part_text_raw_append(), _edje_real_part_recursive_get(), _edje_recalc(), _Edje::data, _Edje::dirty, _Edje_Real_Part::edje, EDJE_PART_TYPE_TEXTBLOCK, _Edje::func, _Edje_Real_Part::part, _Edje::recalc_call, _Edje::recalc_hints, _Edje::text_change, and _Edje_Part::type.
edje_object_part_text_autocapital_type_get()
EAPI Edje_Text_Autocapital_Type edje_object_part_text_autocapital_type_get (const Evas_Object * obj, const char * part)
Retrieves the autocapitalization type.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The autocapitalization type
Since
1.1.0
References _edje_entry_autocapital_type_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_TEXT_AUTOCAPITAL_TYPE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_autocapital_type_set()
EAPI void edje_object_part_text_autocapital_type_set (Evas_Object * obj, const char * part, Edje_Text_Autocapital_Type autocapital_type)
Set the autocapitalization type on the immodule.
Parameters
obj A valid Evas_Object handle
part The part name
autocapital_type The type of autocapitalization
Since
1.1.0
References _edje_entry_autocapital_type_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_begin_set()
EAPI void edje_object_part_text_cursor_begin_set (Evas_Object * obj, const char * part, Edje_Cursor cur)
Moves the cursor to the beginning of the text part.
See also
evas_textblock_cursor_paragraph_first
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_begin(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_content_get()
EAPI char* edje_object_part_text_cursor_content_get (const Evas_Object * obj, const char * part, Edje_Cursor cur)
Returns the content (char) at the cursor position.
See also
evas_textblock_cursor_content_get
You must free the return (if not NULL) after you are done with it.
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to use
Returns
The character string pointed to (may be a multi-byte utf8 sequence) terminated by a nul byte.
References _edje_entry_cursor_content_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_coord_set()
EAPI Eina_Bool edje_object_part_text_cursor_coord_set (Evas_Object * obj, const char * part, Edje_Cursor cur, Evas_Coord x, Evas_Coord y)
Position the given cursor to a X,Y position.
This is frequently used with the user cursor.
Parameters
obj An Edje object.
part The part containing the object.
cur The cursor to adjust.
x X Coordinate.
y Y Coordinate.
Returns
True on success, false on error.
References _edje_entry_cursor_coord_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_copy()
EAPI void edje_object_part_text_cursor_copy (Evas_Object * obj, const char * part, Edje_Cursor src, Edje_Cursor dst)
Copy the cursor to another cursor.
Parameters
obj A valid Evas_Object handle
part The part name
src the cursor to copy from
dst the cursor to copy to
References _edje_entry_cursor_copy(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_down()
EAPI Eina_Bool edje_object_part_text_cursor_down (Evas_Object * obj, const char * part, Edje_Cursor cur)
Moves the cursor to the char below the current cursor position.
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_down(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_end_set()
EAPI void edje_object_part_text_cursor_end_set (Evas_Object * obj, const char * part, Edje_Cursor cur)
Moves the cursor to the end of the text part.
See also
evas_textblock_cursor_paragraph_last
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_end(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_geometry_get()
EAPI void edje_object_part_text_cursor_geometry_get (const Evas_Object * obj, const char * part, Evas_Coord * x, Evas_Coord * y, Evas_Coord * w, Evas_Coord * h)
Returns the cursor geometry of the part relative to the edje object.
Parameters
obj A valid Evas_Object handle
part The part name
x Cursor X position
y Cursor Y position
w Cursor width
h Cursor height
References _edje_entry_cursor_geometry_get(), _edje_fetch(), _edje_real_part_recursive_get(), _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, _Edje_Real_Part::part, _Edje::x, and _Edje::y.
edje_object_part_text_cursor_is_format_get()
EAPI Eina_Bool edje_object_part_text_cursor_is_format_get (const Evas_Object * obj, const char * part, Edje_Cursor cur)
Returns whether the cursor points to a format.
See also
evas_textblock_cursor_is_format
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to adjust.
Returns
EINA_TRUE if it's true, EINA_FALSE otherwise.
References _edje_entry_cursor_is_format_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_is_visible_format_get()
EAPI Eina_Bool edje_object_part_text_cursor_is_visible_format_get (const Evas_Object * obj, const char * part, Edje_Cursor cur)
Return true if the cursor points to a visible format For example \t, \n, item and etc.
See also
evas_textblock_cursor_format_is_visible_get
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to adjust.
References _edje_entry_cursor_is_visible_format_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_line_begin_set()
EAPI void edje_object_part_text_cursor_line_begin_set (Evas_Object * obj, const char * part, Edje_Cursor cur)
Move the cursor to the beginning of the line.
See also
evas_textblock_cursor_line_char_first
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_line_begin(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_line_end_set()
EAPI void edje_object_part_text_cursor_line_end_set (Evas_Object * obj, const char * part, Edje_Cursor cur)
Move the cursor to the end of the line.
See also
evas_textblock_cursor_line_char_last
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_line_end(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_next()
EAPI Eina_Bool edje_object_part_text_cursor_next (Evas_Object * obj, const char * part, Edje_Cursor cur)
Advances the cursor to the next cursor position.
See also
evas_textblock_cursor_char_next
Parameters
obj A valid Evas_Object handle
part The part name
cur The edje cursor to advance
References _edje_entry_cursor_next(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_pos_get()
EAPI int edje_object_part_text_cursor_pos_get (const Evas_Object * obj, const char * part, Edje_Cursor cur)
Retrieves the current position of the cursor.
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to get the position
Returns
The cursor position
Since
1.1.0
References _edje_entry_cursor_pos_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_pos_set()
EAPI void edje_object_part_text_cursor_pos_set (Evas_Object * obj, const char * part, Edje_Cursor cur, int pos)
Sets the cursor position to the given value.
Parameters
obj A valid Evas_Object handle
part The part name
cur The cursor to move
pos the position of the cursor
Since
1.1.0
References _edje_entry_cursor_pos_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_prev()
EAPI Eina_Bool edje_object_part_text_cursor_prev (Evas_Object * obj, const char * part, Edje_Cursor cur)
Moves the cursor to the previous char.
See also
evas_textblock_cursor_char_prev
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_prev(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_cursor_up()
EAPI Eina_Bool edje_object_part_text_cursor_up (Evas_Object * obj, const char * part, Edje_Cursor cur)
Move the cursor to the char above the current cursor position.
Parameters
obj A valid Evas_Object handle
part The part name
cur the edje cursor to work on
References _edje_entry_cursor_up(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_escaped_set()
EAPI Eina_Bool edje_object_part_text_escaped_set (Evas_Object * obj, const char * part, const char * text)
Sets the text for an object part, but converts HTML escapes to UTF8.
This converts the given string text to UTF8 assuming it contains HTML style escapes like "&amp;" and "&copy;" etc. IF the part is of type TEXT, as opposed to TEXTBLOCK.
Parameters
obj A valid Evas Object handle
part The part name
text The text string
Returns
EINA_BOOL on success, EINA_FALSE otherwise
Since
1.2
References _edje_fetch(), _edje_object_part_text_raw_set(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TEXT, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_text_get()
EAPI const char* edje_object_part_text_get (const Evas_Object * obj, const char * part)
Return the text of the object part.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The text string
This function returns the text associated to the object part.
See also
edje_object_part_text_set().
References _edje_entry_text_get(), _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part::entry_mode, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje_Real_Part::text, and _Edje_Part::type.
Referenced by _edje_external_param_get().
edje_object_part_text_imf_context_get()
EAPI void* edje_object_part_text_imf_context_get (const Evas_Object * obj, const char * part)
Get the input method context in entry.
If ecore_imf was not available when edje was compiled, this function returns NULL otherwise, the returned pointer is an Ecore_IMF *
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The input method context (Ecore_IMF_Context *) in entry
Since
1.2.0
References _edje_entry_imf_context_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_imf_context_reset()
EAPI void edje_object_part_text_imf_context_reset (const Evas_Object * obj, const char * part)
Reset the input method context if needed.
This can be necessary in the case where modifying the buffer would confuse on-going input method behavior
Parameters
obj A valid Evas_Object handle
part The part name
Since
1.2.0
References _edje_entry_imf_context_reset(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_enabled_get()
EAPI Eina_Bool edje_object_part_text_input_panel_enabled_get (const Evas_Object * obj, const char * part)
Retrieve the attribute to show the input panel automatically.
See also
edje_object_part_text_input_panel_enabled_set
Parameters
obj A valid Evas_Object handle
part The part name
Returns
EINA_TRUE if it supports or EINA_FALSE otherwise
Since
1.1.0
References _edje_entry_input_panel_enabled_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_enabled_set()
EAPI void edje_object_part_text_input_panel_enabled_set (Evas_Object * obj, const char * part, Eina_Bool enabled)
Sets the attribute to show the input panel automatically.
Parameters
obj A valid Evas_Object handle
part The part name
enabled If true, the input panel is appeared when entry is clicked or has a focus
Since
1.1.0
References _edje_entry_input_panel_enabled_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_hide()
EAPI void edje_object_part_text_input_panel_hide (const Evas_Object * obj, const char * part)
Hide the input panel (virtual keyboard).
See also
edje_object_part_text_input_panel_show
Note that input panel is shown or hidden automatically according to the focus state. This API can be used in the case of manually controlling by using edje_object_part_text_input_panel_enabled_set.
Parameters
obj A valid Evas_Object handle
part The part name
Since
1.2.0
References _edje_entry_input_panel_hide(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_imdata_get()
EAPI void edje_object_part_text_input_panel_imdata_get (const Evas_Object * obj, const char * part, void * data, int * len)
Get the specific data of the current active input panel.
Parameters
obj A valid Evas_Object handle
part The part name
data The specific data to be got from the input panel
len The length of data
Since
1.2.0
References _edje_entry_input_panel_imdata_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_imdata_set()
EAPI void edje_object_part_text_input_panel_imdata_set (Evas_Object * obj, const char * part, const void * data, int len)
Set the input panel-specific data to deliver to the input panel.
This API is used by applications to deliver specific data to the input panel. The data format MUST be negotiated by both application and the input panel. The size and format of data are defined by the input panel.
Parameters
obj A valid Evas_Object handle
part The part name
data The specific data to be set to the input panel.
len the length of data, in bytes, to send to the input panel
Since
1.2.0
References _edje_entry_input_panel_imdata_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_language_get()
EAPI Edje_Input_Panel_Lang edje_object_part_text_input_panel_language_get (const Evas_Object * obj, const char * part)
Get the language mode of the input panel.
See edje_object_part_text_input_panel_language_set for more details.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
input panel language type
Since
1.2.0
References _edje_entry_input_panel_language_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_INPUT_PANEL_LANG_AUTOMATIC, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_language_set()
EAPI void edje_object_part_text_input_panel_language_set (Evas_Object * obj, const char * part, Edje_Input_Panel_Lang lang)
Set the language mode of the input panel.
This API can be used if you want to show the Alphabet keyboard.
Parameters
obj A valid Evas_Object handle
part The part name
lang the language to be set to the input panel.
Since
1.2.0
References _edje_entry_input_panel_language_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_layout_get()
EAPI Edje_Input_Panel_Layout edje_object_part_text_input_panel_layout_get (const Evas_Object * obj, const char * part)
Get the layout of the input panel.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
Layout type of the input panel
See also
edje_object_part_text_input_panel_layout_set
Since
1.1
References _edje_entry_input_panel_layout_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_INPUT_PANEL_LAYOUT_INVALID, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_layout_set()
EAPI void edje_object_part_text_input_panel_layout_set (Evas_Object * obj, const char * part, Edje_Input_Panel_Layout layout)
Set the layout of the input panel.
The layout of the input panel or virtual keyboard can make it easier or harder to enter content. This allows you to hint what kind of input you are expecting to enter and thus have the input panel automatically come up with the right mode.
Parameters
obj A valid Evas_Object handle
part The part name
layout layout type
Since
1.1
References _edje_entry_input_panel_layout_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_return_key_disabled_get()
EAPI Eina_Bool edje_object_part_text_input_panel_return_key_disabled_get (const Evas_Object * obj, const char * part)
Get whether the return key on the input panel should be disabled or not.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
EINA_TRUE if it should be disabled
Since
1.2.0
References _edje_entry_input_panel_return_key_disabled_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_return_key_disabled_set()
EAPI void edje_object_part_text_input_panel_return_key_disabled_set (Evas_Object * obj, const char * part, Eina_Bool disabled)
Set the return key on the input panel to be disabled.
Parameters
obj A valid Evas_Object handle
part The part name
disabled The state
Since
1.2.0
References _edje_entry_input_panel_return_key_disabled_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_return_key_type_get()
EAPI Edje_Input_Panel_Return_Key_Type edje_object_part_text_input_panel_return_key_type_get (const Evas_Object * obj, const char * part)
Get the "return" key type.
See also
edje_object_part_text_input_panel_return_key_type_set() for more details
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The type of "return" key on the input panel
Since
1.2.0
References _edje_entry_input_panel_return_key_type_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DEFAULT, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_return_key_type_set()
EAPI void edje_object_part_text_input_panel_return_key_type_set (Evas_Object * obj, const char * part, Edje_Input_Panel_Return_Key_Type return_key_type)
Set the "return" key type.
This type is used to set string or icon on the "return" key of the input panel.
An input panel displays the string or icon associated with this type
Parameters
obj A valid Evas_Object handle
part The part name
return_key_type The type of "return" key on the input panel
Since
1.2.0
References _edje_entry_input_panel_return_key_type_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_input_panel_show()
EAPI void edje_object_part_text_input_panel_show (const Evas_Object * obj, const char * part)
Show the input panel (virtual keyboard) based on the input panel property such as layout, autocapital types, and so on.
Note that input panel is shown or hidden automatically according to the focus state. This API can be used in the case of manually controlling by using edje_object_part_text_input_panel_enabled_set.
Parameters
obj A valid Evas_Object handle
part The part name
Since
1.2.0
References _edje_entry_input_panel_show(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_insert()
EAPI void edje_object_part_text_insert (Evas_Object * obj, const char * part, const char * text)
Insert text for an object part.
Parameters
obj A valid Evas Object handle
part The part name
text The text string
This function inserts the text for an object part just before the cursor position.
References _edje_entry_text_markup_insert(), _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc(), _Edje::data, _Edje::dirty, _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part::entry_mode, _Edje::func, _Edje_Real_Part::part, _Edje::recalc_call, _Edje::recalc_hints, _Edje::text_change, and _Edje_Part::type.
edje_object_part_text_item_geometry_get()
EAPI Eina_Bool edje_object_part_text_item_geometry_get (const Evas_Object * obj, const char * part, const char * item, Evas_Coord * cx, Evas_Coord * cy, Evas_Coord * cw, Evas_Coord * ch)
Return item geometry.
Parameters
obj A valid Evas_Object handle
part The part name
item The item name
cx Item x return (relative to entry part)
cy Item y return (relative to entry part)
cw Item width return
ch Item height return
Returns
1 if item exists, 0 if not
This function return a list of Evas_Textblock_Rectangle item rectangles.
References _edje_entry_item_geometry_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_item_list_get()
EAPI const Eina_List* edje_object_part_text_item_list_get (const Evas_Object * obj, const char * part)
Return a list of char item names.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The list of items (const char *), do not modify!
This function returns a list of char item names.
References _edje_entry_items_list(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_prediction_allow_get()
EAPI Eina_Bool edje_object_part_text_prediction_allow_get (const Evas_Object * obj, const char * part)
Get whether the prediction is allowed or not.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
EINA_TRUE if prediction feature is allowed.
Since
1.2.0
References _edje_entry_prediction_allow_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_prediction_allow_set()
EAPI void edje_object_part_text_prediction_allow_set (Evas_Object * obj, const char * part, Eina_Bool prediction)
Set whether the prediction is allowed or not.
Parameters
obj A valid Evas_Object handle
part The part name
prediction If true, the prediction feature is allowed.
Since
1.2.0
References _edje_entry_prediction_allow_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_abort()
EAPI void edje_object_part_text_select_abort (const Evas_Object * obj, const char * part)
Aborts any selection action on a part.
Parameters
obj A valid Evas_Object handle
part The part name
References _edje_entry_select_abort(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_all()
EAPI void edje_object_part_text_select_all (const Evas_Object * obj, const char * part)
Set the selection to be everything.
Parameters
obj A valid Evas_Object handle
part The part name
This function selects all text of the object of the part.
Examples
edje-text.c.
References _edje_entry_select_all(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_allow_set()
EAPI void edje_object_part_text_select_allow_set (const Evas_Object * obj, const char * part, Eina_Bool allow)
Enables selection if the entry is an EXPLICIT selection mode type.
Parameters
obj A valid Evas_Object handle
part The part name
allow EINA_TRUE to enable, EINA_FALSE otherwise
The default is to not allow selection. This function only affects user selection, functions such as edje_object_part_text_select_all() and edje_object_part_text_select_none() are not affected.
Examples
edje-text.c.
References _edje_entry_select_allow_set(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_begin()
EAPI void edje_object_part_text_select_begin (const Evas_Object * obj, const char * part)
Starts selecting at current cursor position.
Parameters
obj A valid Evas_Object handle
part The part name
References _edje_entry_select_begin(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_extend()
EAPI void edje_object_part_text_select_extend (const Evas_Object * obj, const char * part)
Extends the current selection to the current cursor position.
Parameters
obj A valid Evas_Object handle
part The part name
References _edje_entry_select_extend(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_select_none()
EAPI void edje_object_part_text_select_none (const Evas_Object * obj, const char * part)
Set the selection to be none.
Parameters
obj A valid Evas_Object handle
part The part name
This function sets the selection text to be none.
Examples
edje-text.c.
References _edje_entry_select_none(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_selection_get()
EAPI const char* edje_object_part_text_selection_get (const Evas_Object * obj, const char * part)
Return the selection text of the object part.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The text string
This function returns selection text of the object part.
See also
edje_object_part_text_select_all()
edje_object_part_text_select_none()
Examples
edje-text.c.
References _edje_entry_selection_get(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_text_set()
EAPI Eina_Bool edje_object_part_text_set (Evas_Object * obj, const char * part, const char * text)
Sets the text for an object part.
Parameters
obj A valid Evas Object handle
part The part name
text The text string
Returns
EINA_BOOL on success, EINA_FALSE otherwise
Examples
edje-color-class.c, and edje-text.c.
References _edje_fetch(), _edje_object_part_text_raw_set(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::part, and _Edje_Part::type.
Referenced by _edje_external_param_set().
edje_object_part_text_style_user_peek()
EAPI const char* edje_object_part_text_style_user_peek (const Evas_Object * obj, const char * part)
Return the text of the object part.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The text string
This function returns the style associated with the textblock part.
Since
1.2.0
References _edje_fetch(), _edje_real_part_recursive_get(), EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_text_style_user_pop()
EAPI void edje_object_part_text_style_user_pop (Evas_Object * obj, const char * part)
Delete the top style form the user style stack.
Parameters
obj A valid Evas_Object handle
part The part name
Since
1.2.0
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc(), EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::recalc_hints, and _Edje_Part::type.
edje_object_part_text_style_user_push()
EAPI void edje_object_part_text_style_user_push (Evas_Object * obj, const char * part, const char * style)
Set the style of the.
Parameters
obj A valid Evas_Object handle
part The part name
style The style to set (textblock conventions).
This function sets the style associated with the textblock part.
Since
1.2.0
References _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc(), EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::recalc_hints, and _Edje_Part::type.
edje_object_part_text_unescaped_get()
EAPI char* edje_object_part_text_unescaped_get (const Evas_Object * obj, const char * part)
Returns the text of the object part, without escaping.
Parameters
obj A valid Evas_Object handle
part The part name
Returns
The allocated text string without escaping, or NULL on problems.
This function is the counterpart of edje_object_part_text_unescaped_set(). Please notice that the result is newly allocated memory and should be released with free() when done.
See also
edje_object_part_text_unescaped_set().
Examples
edje-text.c.
References _edje_entry_text_get(), _edje_fetch(), _edje_real_part_recursive_get(), _edje_recalc_do(), _edje_text_unescape(), EDJE_ENTRY_EDIT_MODE_NONE, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part::entry_mode, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje_Real_Part::text, and _Edje_Part::type.
edje_object_part_text_unescaped_set()
EAPI Eina_Bool edje_object_part_text_unescaped_set (Evas_Object * obj, const char * part, const char * text_to_escape)
Sets the raw (non escaped) text for an object part.
Parameters
obj A valid Evas Object handle
part The part name
text_to_escape The text string
This funciton will not do escape for you if it is a TEXTBLOCK part, that is, if text contain tags, these tags will not be interpreted/parsed by TEXTBLOCK.
See also
edje_object_part_text_unescaped_get().
References _edje_fetch(), _edje_object_part_text_raw_set(), _edje_real_part_recursive_get(), _edje_text_escape(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Real_Part::part, and _Edje_Part::type.
edje_object_part_text_user_insert()
EAPI void edje_object_part_text_user_insert (const Evas_Object * obj, const char * part, const char * text)
Deletes the selection and emits a change event.
Parameters
obj A valid Evas_Object handle
part The part name
text The text string
Since
1.2.0
References _edje_entry_user_insert(), _edje_fetch(), _edje_real_part_recursive_get(), EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
edje_object_part_unswallow()
EAPI void edje_object_part_unswallow (Evas_Object * obj, Evas_Object * obj_swallow)
Unswallow an object.
Parameters
obj A valid Evas_Object handle
obj_swallow The swallowed object
Causes the edje to regurgitate a previously swallowed object. :)
Note
obj_swallow will not be deleted or hidden.
obj_swallow may appear shown on the evas depending on its state when it got unswallowed. Make sure you delete it or hide it if you do not want it to.
References _edje_fetch(), _edje_real_part_swallow_clear(), _edje_recalc_do(), _edje_user_definition_free(), _Edje::dirty, _Edje_Real_Part::edje, EDJE_PART_TYPE_SWALLOW, EDJE_USER_SWALLOW, ERR, _Edje_Size::h, _Edje_Real_Part::max, _Edje_Real_Part::min, _Edje_Part::name, _Edje_Real_Part::part, _Edje::recalc_call, _Edje_User_Defined::swallow, _Edje_Real_Part::swallow_params, _Edje_Real_Part::swallowed_object, _Edje_Part::type, _Edje_User_Defined::type, _Edje_User_Defined::u, _Edje::user_defined, and _Edje_Size::w.
Referenced by _edje_real_part_swallow(), and edje_object_part_swallow().
edje_object_parts_extends_calc()
EAPI Eina_Bool edje_object_parts_extends_calc (Evas_Object * obj, Evas_Coord * x, Evas_Coord * y, Evas_Coord * w, Evas_Coord * h)
Calculate the geometry of the region, relative to a given Edje object's area, occupied by all parts in the object
Parameters
obj A handle to an Edje object
x A pointer to a variable where to store the parts region's x coordinate
y A pointer to a variable where to store the parts region's y coordinate
w A pointer to a variable where to store the parts region's width
h A pointer to a variable where to store the parts region's height
This function gets the geometry of the rectangle equal to the area required to group all parts in obj's group/collection. The x and y coordinates are relative to the top left corner of the whole obj object's area. Parts placed out of the group's boundaries will also be taken in account, so that x and y may be negative.
Note
Use NULL pointers on the geometry components you're not interested in: they'll be ignored by the function.
On failure, this function will make all non-NULL geometry pointers' pointed variables be set to zero.
Examples
edje-basic.c.
References _edje_fetch(), _edje_recalc_do(), _Edje::calc_only, _Edje::dirty, _Edje_Real_Part::h, _Edje::table_parts, _Edje::table_parts_size, _Edje_Real_Part::w, _Edje_Real_Part::x, and _Edje_Real_Part::y.
edje_object_perspective_get()
EAPI const Edje_Perspective* edje_object_perspective_get (const Evas_Object * obj)
Get the current perspective used on this Edje object.
Parameters
obj the given Edje object.
Returns
The perspective object being used on this Edje object. Or NULL if there was none, and on errors.
See also
edje_object_perspective_set()
References _Edje::persp.
edje_object_perspective_set()
EAPI void edje_object_perspective_set (Evas_Object * obj, Edje_Perspective * ps)
Set the given perspective object on this Edje object.
Parameters
obj The Edje object on the perspective will be set.
ps The perspective object that will be used.
Make the given perspective object be the default perspective for this Edje object.
There can be only one perspective object per Edje object, and if a previous one was set, it will be removed and the new perspective object will be used.
An Edje perspective will only affect a part if it doesn't point to another part to be used as perspective.
See also
edje_object_perspective_new()
edje_object_perspective_get()
edje_perspective_set()
References _edje_recalc_do(), _Edje::dirty, _Edje::persp, _Edje::recalc_call, and _Edje_Perspective::users.
edje_object_play_get()
EAPI Eina_Bool edje_object_play_get (const Evas_Object * obj)
Get the Edje object's state.
Parameters
obj A handle to an Edje object.
Returns
EINA_FALSE if the object is not connected, its delete_me flag is set, or it is at paused state; EINA_TRUE if the object is at playing state.
This function tells if an Edje object is playing or not. This state is set by edje_object_play_set().
See also
edje_object_play_set().
References _edje_fetch(), _Edje::delete_me, and _Edje::paused.
edje_object_play_set()
EAPI void edje_object_play_set (Evas_Object * obj, Eina_Bool play)
Set the Edje object to playing or paused states.
Parameters
obj A handle to an Edje object.
play Object state (EINA_TRUE to playing, EINA_FALSE to paused).
This function sets the Edje object obj to playing or paused states, depending on the parameter play. This has no effect if the object was already at that state.
See also
edje_object_play_get().
References _edje_fetch(), _Edje::actions, _Edje::delete_me, edje_object_play_set(), EDJE_PART_TYPE_GROUP, _Edje_Real_Part::part, _Edje::paused, _Edje::paused_at, _Edje_Running_Program::start_time, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_object_play_set().
edje_object_preload()
EAPI Eina_Bool edje_object_preload (Evas_Object * obj, Eina_Bool cancel)
Preload the images on the Edje Object in the background.
Parameters
obj A handle to an Edje object
cancel EINA_FALSE will add it the preloading work queue, EINA_TRUE will remove it (if it was issued before).
Returns
EINA_FASLE if obj was not a valid Edje object otherwise EINA_TRUE
This function requests the preload of all data images (on the given object) in the background. The work is queued before being processed (because there might be other pending requests of this type). It emits a signal "preload,done" when finished.
Note
Use EINA_TRUE on scenarios where you don't need the image data preloaded anymore.
References _edje_fetch(), _edje_recalc_do(), EDJE_PART_TYPE_GROUP, EDJE_PART_TYPE_IMAGE, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::preload_count, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
edje_object_scale_get()
EAPI double edje_object_scale_get (const Evas_Object * obj)
Get a given Edje object's scaling factor.
Parameters
obj A handle to an Edje object
This function returns the individual scaling factor set on the obj Edje object.
See also
edje_object_scale_set() for more details
Examples
edje-basic.c.
References _edje_fetch(), _Edje::scale, and TO_DOUBLE.
edje_object_scale_set()
EAPI Eina_Bool edje_object_scale_set (Evas_Object * obj, double scale)
Set the scaling factor for a given Edje object.
Parameters
obj A handle to an Edje object
scale The scaling factor (the default value is 0.0, meaning individual scaling not set)
This function sets an individual scaling factor on the obj Edje object. This property (or Edje's global scaling factor, when applicable), will affect this object's part sizes. If scale is not zero, than the individual scaling will override any global scaling set, for the object obj's parts. Put it back to zero to get the effects of the global scaling again.
Warning
Only parts which, at EDC level, had the "scale" property set to 1, will be affected by this function. Check the complete syntax reference for EDC files.
See also
edje_object_scale_get()
edje_scale_get() for more details
Examples
edje-basic.c.
References _edje_fetch(), edje_object_calc_force(), edje_object_scale_set(), EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, FROM_DOUBLE, _Edje::groups, _Edje_Real_Part::items, _Edje::obj, _Edje_Real_Part::part, _Edje::scale, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by _edje_part_recalc(), and edje_object_scale_set().
edje_object_signal_callback_add()
EAPI void edje_object_signal_callback_add (Evas_Object * obj, const char * emission, const char * source, Edje_Signal_Cb func, void * data)
Add a callback for an arriving Edje signal, emitted by a given Ejde object.
Parameters
obj A handle to an Edje object
emission The signal's "emission" string
source The signal's "source" string
func The callback function to be executed when the signal is emitted.
data A pointer to data to pass in to func.
Edje signals are one of the communication interfaces between code and a given Edje object's theme. With signals, one can communicate two string values at a time, which are:
"emission" value: the name of the signal, in general
"source" value: a name for the signal's context, in general
Though there are those common uses for the two strings, one is free to use them however they like.
This function adds a callback function to a signal emitted by obj, to be issued every time an EDC program like the following
program {
  name: "emit_example";
  action: SIGNAL_EMIT "a_signal" "a_source";
}
is run, if emission and source are given those same values, here.
Signal callback registration is powerful, in the way that blobs may be used to match multiple signals at once. All the "*?[\" set of fnmatch() operators can be used, both for emission and source.
Edje has internal signals it will emit, automatically, on various actions taking place on group parts. For example, the mouse cursor being moved, pressed, released, etc., over a given part's area, all generate individual signals.
By using something like
edje_object_signal_callback_add(obj, "mouse,down,*", "button.*",
                                signal_cb, NULL);
being "button.*" the pattern for the names of parts implementing buttons on an interface, you'd be registering for notifications on events of mouse buttons being pressed down on either of those parts (those events all have the "mouse,down," common prefix on their names, with a suffix giving the button number). The actual emission and source strings of an event will be passed in as the emission and source parameters of the callback function (e.g. "mouse,down,2" and "button.close"), for each of those events.
Note
See the syntax for EDC files
See also
edje_object_signal_emit() on how to emits Edje signals from code to a an object
edje_object_signal_callback_del_full()
Examples
edje-color-class.c, edje-drag.c, edje-perspective.c, and edje-signals-messages.c.
edje_object_signal_callback_del()
EAPI void* edje_object_signal_callback_del (Evas_Object * obj, const char * emission, const char * source, Edje_Signal_Cb func)
Remove a signal-triggered callback from an object.
Parameters
obj A valid Evas_Object handle.
emission The emission string.
source The source string.
func The callback function.
Returns
The data pointer
This function removes a callback, previously attached to the emittion of a signal, from the object obj. The parameters emission, source and func must match exactly those passed to a previous call to edje_object_signal_callback_add(). The data pointer that was passed to this call will be returned.
See also
edje_object_signal_callback_add().
edje_object_signal_callback_del_full().
edje_object_signal_callback_del_full()
EAPI void* edje_object_signal_callback_del_full (Evas_Object * obj, const char * emission, const char * source, Edje_Signal_Cb func, void * data)
Unregister/delete a callback set for an arriving Edje signal, emitted by a given Ejde object.
Parameters
obj A handle to an Edje object
emission The signal's "emission" string
source The signal's "source" string
func The callback function passed on the callback's registration
data The pointer given to be passed as data to func
Returns
data, on success or NULL, on errors (or if data had this value)
This function removes a callback, previously attached to the emittion of a signal, from the object obj. The parameters emission, source, func and data must match exactly those passed to a previous call to edje_object_signal_callback_add(). The data pointer that was passed to this call will be returned.
See also
edje_object_signal_callback_add().
edje_object_signal_callback_del().
References _edje_callbacks_patterns_clean(), _edje_fetch(), _Edje::callbacks, _Edje_Signal_Callback::data, _Edje::delete_callbacks, _Edje::delete_me, _Edje_Signal_Callback::delete_me, _Edje_Signal_Callback::func, _Edje_Signal_Callback::signal, _Edje_Signal_Callback::source, and _Edje::walking_callbacks.
edje_object_signal_callback_extra_data_get()
EAPI void* edje_object_signal_callback_extra_data_get (void)
Get extra data passed to callbacks.
Returns
the extra data for that callback.
Some callbacks pass extra information. This function gives access to that extra information. It's somehow like event_info in smart callbacks.
See also
edje_object_signal_callback_add() for more on Edje signals.
Since
1.1.0
edje_object_signal_emit()
EAPI void edje_object_signal_emit (Evas_Object * obj, const char * emission, const char * source)
Send/emit an Edje signal to a given Edje object.
Parameters
obj A handle to an Edje object
emission The signal's "emission" string
source The signal's "source" string
This function sends a signal to the object obj. An Edje program, at obj's EDC specification level, can respond to a signal by having declared matching 'signal' and 'source' fields on its block (see the syntax for EDC files).
As an example,
edje_object_signal_emit(obj, "a_signal", "");
would trigger a program which had an EDC declaration block like
program {
 name: "a_program";
 signal: "a_signal";
 source: "";
 action: ...
}
See also
edje_object_signal_callback_add() for more on Edje signals.
Examples
edje-perspective.c, and edje-signals-messages.c.
References _edje_emit(), _edje_fetch(), and _Edje::delete_me.
Referenced by _edje_object_orientation_inform().
edje_object_size_max_get()
EAPI void edje_object_size_max_get (const Evas_Object * obj, Evas_Coord * maxw, Evas_Coord * maxh)
Get the maximum size specified – as an EDC property – for a given Edje object.
Parameters
obj A handle to an Edje object
maxw Pointer to a variable where to store the maximum width
maxh Pointer to a variable where to store the maximum height
This function retrieves the obj object's maximum size values, as declared in its EDC group definition. Maximum size of groups have the following syntax
collections {
  group {
    name: "a_group";
    max: 100 100;
  }
}
where one declares a maximum size of 100 pixels both for width and height. Those are (hint) values which should be respected when the given object/group is to be controlled by a given container object (e.g. an Edje object being "swallowed" into a given SWALLOW typed part, as in edje_object_part_swallow()). Check the complete syntax reference for EDC files.
Note
If the max EDC property was not declared for obj, this call will return the maximum size a given Edje object may have, for each axis.
On failure, this function will make all non-NULL size pointers' pointed variables be set to zero.
See also
edje_object_size_min_get()
Examples
edje-basic.c.
References _edje_fetch(), _edje_recalc_do(), _Edje::collection, EDJE_INF_MAX_H, EDJE_INF_MAX_W, _Edje_Size::h, _Edje_Part_Collection::max, _Edje_Part_Collection::prop, and _Edje_Size::w.
edje_object_size_min_calc()
EAPI void edje_object_size_min_calc (Evas_Object * obj, Evas_Coord * minw, Evas_Coord * minh)
Calculate the minimum required size for a given Edje object.
Parameters
obj A handle to an Edje object
minw Pointer to a variable where to store the minimum required width
minh Pointer to a variable where to store the minimum required height
This call works exactly as edje_object_size_min_restricted_calc(), with the last two arguments set to 0. Please refer to its documentation, then.
Examples
edje-basic.c.
References edje_object_size_min_restricted_calc().
Referenced by _edje_recalc_do().
edje_object_size_min_get()
EAPI void edje_object_size_min_get (const Evas_Object * obj, Evas_Coord * minw, Evas_Coord * minh)
Get the minimum size specified – as an EDC property – for a given Edje object.
Parameters
obj A handle to an Edje object
minw Pointer to a variable where to store the minimum width
minh Pointer to a variable where to store the minimum height
This function retrieves the obj object's minimum size values, as declared in its EDC group definition. Minimum size of groups have the following syntax
collections {
  group {
    name: "a_group";
    min: 100 100;
  }
}
where one declares a minimum size of 100 pixels both for width and height. Those are (hint) values which should be respected when the given object/group is to be controlled by a given container object (e.g. an Edje object being "swallowed" into a given SWALLOW typed part, as in edje_object_part_swallow()). Check the complete syntax reference for EDC files.
Note
If the min EDC property was not declared for obj, this call will return the value 0, for each axis.
On failure, this function will make all non-NULL size pointers' pointed variables be set to zero.
See also
edje_object_size_max_get()
Examples
edje-basic.c.
References _edje_fetch(), _Edje::collection, _Edje_Size::h, _Edje_Part_Collection::min, _Edje_Part_Collection::prop, and _Edje_Size::w.
edje_object_size_min_restricted_calc()
EAPI void edje_object_size_min_restricted_calc (Evas_Object * obj, Evas_Coord * minw, Evas_Coord * minh, Evas_Coord restrictedw, Evas_Coord restrictedh)
Calculate the minimum required size for a given Edje object.
Parameters
obj A handle to an Edje object
minw Pointer to a variable where to store the minimum required width
minh Pointer to a variable where to store the minimum required height
restrictedw Do not allow object's calculated (minimum) width to be less than this value
restrictedh Do not allow object's calculated (minimum) height to be less than this value
This call will trigger an internal recalculation of all parts of the obj object, in order to return its minimum required dimensions for width and height. The user might choose to impose those minimum sizes, making the resulting calculation to get to values equal or bigger than restrictedw and restrictedh, for width and height, respectively.
Note
At the end of this call, obj won't be automatically resized to new dimensions, but just return the calculated sizes. The caller is the one up to change its geometry or not.
Warning
Be advised that invisible parts in obj will be taken into account in this calculation.
Examples
edje-basic.c.
References _edje_fetch(), _edje_recalc(), _edje_recalc_do(), _Edje::calc_only, _Edje_Real_Part::chosen_description, _Edje::collection, _Edje::dirty, EDJE_PART_TYPE_TEXTBLOCK, ERR, _Edje_Part_Description_Common::fixed, _Edje::group, _Edje_Size::h, _Edje_Rectangle::h, _Edje_Part_Description_Common::h, _Edje::h, _Edje_Real_Part::h, _Edje::min, _Edje_Part::name, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::path, _Edje_Real_Part::req, _Edje::table_parts, _Edje::table_parts_size, _Edje_Part::type, _Edje_Size::w, _Edje_Rectangle::w, _Edje_Part_Description_Common::w, _Edje::w, and _Edje_Real_Part::w.
Referenced by _edje_entry_cursor_geometry_get(), and edje_object_size_min_calc().
edje_object_text_change_cb_set()
EAPI void edje_object_text_change_cb_set (Evas_Object * obj, Edje_Text_Change_Cb func, void * data)
Set the object text callback.
Parameters
obj A valid Evas_Object handle
func The callback function to handle the text change
data The data associated to the callback function.
This function sets the callback to be called when the text changes.
Examples
edje-text.c.
References _edje_fetch(), _Edje::data, edje_object_text_change_cb_set(), EDJE_PART_TYPE_GROUP, _Edje::func, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, _Edje::text_change, and _Edje_Part::type.
Referenced by edje_object_text_change_cb_set().
edje_object_text_class_set()
EAPI Eina_Bool edje_object_text_class_set (Evas_Object * obj, const char * text_class, const char * font, Evas_Font_Size size)
Sets Edje text class.
Parameters
obj A valid Evas_Object handle
text_class The text class name
font Font name
size Font Size
Returns
EINA_TRUE, on success or EINA_FALSE, on error
This function sets the text class for the Edje.
References _edje_fetch(), _edje_recalc(), _edje_textblock_style_all_update(), _Edje::dirty, edje_object_text_class_set(), EDJE_PART_TYPE_GROUP, _Edje_Text_Class::font, _Edje_Text_Class::name, _Edje_Real_Part::part, _Edje::recalc_call, _Edje_Text_Class::size, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, _Edje::text_classes, and _Edje_Part::type.
Referenced by edje_object_text_class_set().
edje_object_text_insert_filter_callback_add()
EAPI void edje_object_text_insert_filter_callback_add (Evas_Object * obj, const char * part, Edje_Text_Filter_Cb func, void * data)
Add a filter function for newly inserted text.
Whenever text is inserted (not the same as set) into the given part, the list of filter functions will be called to decide if and how the new text will be accepted. There are three types of filters, EDJE_TEXT_FILTER_TEXT, EDJE_TEXT_FILTER_FORMAT and EDJE_TEXT_FILTER_MARKUP. The text parameter in the func filter can be modified by the user and it's up to him to free the one passed if he's to change the pointer. If doing so, the newly set text should be malloc'ed, as once all the filters are called Edje will free it. If the text is to be rejected, freeing it and setting the pointer to NULL will make Edje break out of the filter cycle and reject the inserted text.
Warning
This function will be deprecated because of difficulty in use. The type(format, text, or markup) of text should be always checked in the filter function for correct filtering. Please use edje_object_text_markup_filter_callback_add() instead. There is no need to check the type of text in the filter function because the text is always markup.
If you use this function with edje_object_text_markup_filter_callback_add() together, all Edje_Text_Filter_Cb functions and Edje_Markup_Filter_Cb functions will be executed, and then filtered text will be inserted.
See also
edje_object_text_insert_filter_callback_del
edje_object_text_insert_filter_callback_del_full
edje_object_text_markup_filter_callback_add
Parameters
obj A valid Evas_Object handle
part The part name
func The callback function that will act as filter
data User provided data to pass to the filter function
References _edje_fetch(), _Edje_Text_Insert_Filter_Callback::data, _Edje_Text_Insert_Filter_Callback::func, _Edje_Text_Insert_Filter_Callback::part, and _Edje::text_insert_filter_callbacks.
edje_object_text_insert_filter_callback_del()
EAPI void* edje_object_text_insert_filter_callback_del (Evas_Object * obj, const char * part, Edje_Text_Filter_Cb func)
Delete a function from the filter list.
Delete the given func filter from the list in part. Returns the user data pointer given when added.
See also
edje_object_text_insert_filter_callback_add
edje_object_text_insert_filter_callback_del_full
Parameters
obj A valid Evas_Object handle
part The part name
func The function callback to remove
Returns
The user data pointer if successful, or NULL otherwise
References _edje_fetch(), _Edje_Text_Insert_Filter_Callback::data, _Edje_Text_Insert_Filter_Callback::func, _Edje_Text_Insert_Filter_Callback::part, and _Edje::text_insert_filter_callbacks.
edje_object_text_insert_filter_callback_del_full()
EAPI void* edje_object_text_insert_filter_callback_del_full (Evas_Object * obj, const char * part, Edje_Text_Filter_Cb func, void * data)
Delete a function and matching user data from the filter list.
Delete the given func filter and data user data from the list in part. Returns the user data pointer given when added.
See also
edje_object_text_insert_filter_callback_add
edje_object_text_insert_filter_callback_del
Parameters
obj A valid Evas_Object handle
part The part name
func The function callback to remove
data The data passed to the callback function
Returns
The same data pointer if successful, or NULL otherwise
References _edje_fetch(), _Edje_Text_Insert_Filter_Callback::data, _Edje_Text_Insert_Filter_Callback::func, _Edje_Text_Insert_Filter_Callback::part, and _Edje::text_insert_filter_callbacks.
edje_object_text_markup_filter_callback_add()
EAPI void edje_object_text_markup_filter_callback_add (Evas_Object * obj, const char * part, Edje_Markup_Filter_Cb func, void * data)
Add a markup filter function for newly inserted text.
Whenever text is inserted (not the same as set) into the given part, the list of markup filter functions will be called to decide if and how the new text will be accepted. The text parameter in the func filter is always markup. It can be modified by the user and it's up to him to free the one passed if he's to change the pointer. If doing so, the newly set text should be malloc'ed, as once all the filters are called Edje will free it. If the text is to be rejected, freeing it and setting the pointer to NULL will make Edje break out of the filter cycle and reject the inserted text. This function is different from edje_object_text_insert_filter_callback_add() in that the text parameter in the fucn filter is always markup.
Warning
If you use this function with edje_object_text_insert_filter_callback_add() togehter, all Edje_Text_Filter_Cb functions and Edje_Markup_Filter_Cb functions will be executed, and then filtered text will be inserted.
See also
edje_object_text_markup_filter_callback_del
edje_object_text_markup_filter_callback_del_full
edje_object_text_insert_filter_callback_add
Parameters
obj A valid Evas_Object handle
part The part name
func The callback function that will act as markup filter
data User provided data to pass to the filter function
Since
1.2.0
References _edje_fetch(), _Edje_Markup_Filter_Callback::data, _Edje_Markup_Filter_Callback::func, _Edje::markup_filter_callbacks, and _Edje_Markup_Filter_Callback::part.
edje_object_text_markup_filter_callback_del()
EAPI void* edje_object_text_markup_filter_callback_del (Evas_Object * obj, const char * part, Edje_Markup_Filter_Cb func)
Delete a function from the markup filter list.
Delete the given func filter from the list in part. Returns the user data pointer given when added.
See also
edje_object_text_markup_filter_callback_add
edje_object_text_markup_filter_callback_del_full
Parameters
obj A valid Evas_Object handle
part The part name
func The function callback to remove
Returns
The user data pointer if successful, or NULL otherwise
Since
1.2.0
References _edje_fetch(), _Edje_Markup_Filter_Callback::data, _Edje_Markup_Filter_Callback::func, _Edje::markup_filter_callbacks, and _Edje_Markup_Filter_Callback::part.
edje_object_text_markup_filter_callback_del_full()
EAPI void* edje_object_text_markup_filter_callback_del_full (Evas_Object * obj, const char * part, Edje_Markup_Filter_Cb func, void * data)
Delete a function and matching user data from the markup filter list.
Delete the given func filter and data user data from the list in part. Returns the user data pointer given when added.
See also
edje_object_text_markup_filter_callback_add
edje_object_text_markup_filter_callback_del
Parameters
obj A valid Evas_Object handle
part The part name
func The function callback to remove
data The data passed to the callback function
Returns
The same data pointer if successful, or NULL otherwise
Since
1.2.0
References _edje_fetch(), _Edje_Markup_Filter_Callback::data, _Edje_Markup_Filter_Callback::func, _Edje::markup_filter_callbacks, and _Edje_Markup_Filter_Callback::part.
edje_object_thaw()
EAPI int edje_object_thaw (Evas_Object * obj)
Thaws the Edje object.
Parameters
obj A handle to an Edje object.
Returns
The frozen state or 0 if the object is not frozen or on error.
This function thaws the given Edje object.
Note
: If sucessives freezes were done, an equal number of thaws will be required.
See also
edje_object_freeze()
References _edje_fetch(), _edje_thaw(), edje_object_thaw(), EDJE_PART_TYPE_GROUP, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Part::type.
Referenced by edje_object_thaw().
edje_object_update_hints_get()
EAPI Eina_Bool edje_object_update_hints_get (Evas_Object * obj)
Wether or not Edje will update size hints on itself.
Parameters
obj A handle to an Edje object.
Returns
true if does, false if it doesn't.
References _edje_fetch(), and _Edje::update_hints.
Referenced by _edje_part_recalc().
edje_object_update_hints_set()
EAPI void edje_object_update_hints_set (Evas_Object * obj, Eina_Bool update)
Edje will automatically update the size hints on itself.
Parameters
obj A handle to an Edje object.
update Wether or not update the size hints.
By default edje doesn't set size hints on itself. With this function call, it will do so if update is true. Be carefully, it cost a lot to trigger this feature as it will recalc the object every time it make sense to be sure that's its minimal size hint is always accurate.
References _edje_fetch(), _edje_recalc(), _Edje::recalc_hints, and _Edje::update_hints.
Referenced by _edje_part_recalc().
edje_password_show_last_set()
EAPI void edje_password_show_last_set (Eina_Bool password_show_last)
Show last character in password mode.
Parameters
password_show_last If TRUE enable last character show in password mode.
This function enables last input to be visible when in password mode for few seconds or until the next input is entered.
The time out value is obtained by edje_password_show_last_timeout_set function.
See also
edje_password_show_last_timeout_set().
References _edje_password_show_last.
edje_password_show_last_timeout_set()
EAPI void edje_password_show_last_timeout_set (double password_show_last_timeout)
Set's the timeout value in last show password mode.
Parameters
password_show_last_timeout The timeout value.
This functions sets the time out value for which the last input entered in password mode will be visible.
This value can be used only when last show mode is set in password mode.
See also
edje_password_show_last_set().
References _edje_password_show_last_timeout, and FROM_DOUBLE.
edje_perspective_free()
EAPI void edje_perspective_free (Edje_Perspective * ps)
Delete the given perspective object.
Parameters
ps A valid perspective object, or NULL.
This function will delete the perspective object. If the perspective effect was being applied to any Edje object or part, this effect won't be applied anymore.
See also
edje_perspective_new()
References _Edje_Perspective::obj.
edje_perspective_global_get()
EAPI Eina_Bool edje_perspective_global_get (const Edje_Perspective * ps)
Get whether the given perspective object is global or not.
Parameters
ps The given perspective object.
Returns
EINA_TRUE if this perspective object is global, EINA_FALSE otherwise.
See also
edje_perspective_global_set()
References _Edje_Perspective::global.
edje_perspective_global_set()
EAPI void edje_perspective_global_set (Edje_Perspective * ps, Eina_Bool global)
Make this perspective object be global for its canvas.
Parameters
ps The given perspective object
global EINA_TRUE if the perspective should be global, EINA_FALSE otherwise.
The canvas which this perspective object is being set as global is the one given as argument upon the object creation (the evas parameter on the function edje_perspective_new(evas)).
There can be only one global perspective object set per canvas, and if a perspective object is set to global when there was already another global perspective set, the old one will be set as non-global.
A global perspective just affects a part if its Edje object doesn't have a perspective object set to it, and if the part doesn't point to another part to be used as perspective.
See also
edje_object_perspective_set()
edje_perspective_global_get()
edje_perspective_new()
Examples
edje-perspective.c.
References _edje_edjes, _edje_recalc_do(), _Edje::dirty, _Edje_Perspective::global, _Edje_Perspective::obj, _Edje::persp, and _Edje::recalc_call.
edje_perspective_new()
EAPI Edje_Perspective* edje_perspective_new (Evas * e)
Creates a new perspective in the given canvas.
Parameters
e The given canvas (Evas).
Returns
An Edje_Perspective object for this canvas, or NULL on errors.
This function creates a perspective object that can be set on an Edje object, or globally to all Edje objects on this canvas.
See also
edje_perspective_set()
edje_perspective_free()
Examples
edje-perspective.c.
References _Edje_Perspective::obj.
edje_perspective_set()
EAPI void edje_perspective_set (Edje_Perspective * ps, Evas_Coord px, Evas_Coord py, Evas_Coord z0, Evas_Coord foc)
Setup the transform for this perspective object.
This sets the parameters of the perspective transformation. X, Y and Z values are used. The px and py points specify the "infinite distance" point in the 3D conversion (where all lines converge to like when artists draw 3D by hand). The z0 value specifies the z value at which there is a 1:1 mapping between spatial coordinates and screen coordinates. Any points on this z value will not have their X and Y values modified in the transform. Those further away (Z value higher) will shrink into the distance, and those less than this value will expand and become bigger. The foc value determines the "focal length" of the camera. This is in reality the distance between the camera lens plane itself (at or closer than this rendering results are undefined) and the "z0" z value. This allows for some "depth" control and foc must be greater than 0.
Parameters
ps The perspective object
px The perspective distance X coordinate
py The perspective distance Y coordinate
z0 The "0" z plane value
foc The focal distance
Examples
edje-perspective.c.
References _edje_edjes, _edje_recalc_do(), _Edje::dirty, _Edje_Perspective::foc, _Edje_Perspective::global, _Edje::persp, _Edje_Perspective::px, _Edje_Perspective::py, _Edje::recalc_call, _Edje_Perspective::users, and _Edje_Perspective::z0.
edje_scale_get()
EAPI double edje_scale_get (void)
Retrieve Edje's global scaling factor.
Returns
The global scaling factor
This function returns Edje's global scaling factor.
See also
edje_scale_set() for more details
Examples
edje-basic.c.
References _edje_scale, and TO_DOUBLE.
edje_scale_set()
EAPI void edje_scale_set (double scale)
Set Edje's global scaling factor.
Parameters
scale The global scaling factor (the default value is 1.0)
Edje allows one to build scalable interfaces. Scaling factors, which are set to neutral (1.0) values by default (no scaling, actual sizes), are of two types: global and individual. Edje's global scaling factor will affect all its objects which hadn't their individual scaling factors altered from the default value (which is zero). If they had it set differently, by edje_object_scale_set(), that factor will override the global one.
Scaling affects the values of minimum/maximum part sizes, which are multiplied by it. Font sizes are scaled, too.
Warning
Only parts which, at EDC level, had the "scale" property set to 1, will be affected by this function. Check the complete syntax reference for EDC files.
See also
edje_scale_get().
Examples
edje-basic.c.
References _edje_edjes, _edje_scale, edje_object_calc_force(), and FROM_DOUBLE.
edje_shutdown()
EAPI int edje_shutdown (void)
Shutdown the Edje library.
Returns
The number of times the library has been initialised without being shutdown.
This function shuts down the Edje library. It will also call the shutdown functions of its dependencies, which are eina_shutdown(), ecore_shutdown(), embryo_shutdown() and eet_shutdown(), so there is no need to call these functions again, in your code.
See also
edje_init()
eina_shutdown()
ecore_shutdown()
embryo_shutdown()
eet_shutdown()
Examples
edje-basic.c, edje-box.c, edje-box2.c, edje-color-class.c, edje-drag.c, edje-perspective.c, edje-signals-messages.c, edje-swallow.c, edje-table.c, and edje-text.c.
edje_text_class_del()
EAPI void edje_text_class_del (const char * text_class)
Delete the text class.
Parameters
text_class The text class name string
This function deletes any values at the process level for the specified text class.
edje_text_class_list()
EAPI Eina_List* edje_text_class_list (void)
List text classes.
Returns
A list of text class names (strings). These strings are stringshares and the list must be free()'d by the caller.
This function lists all text classes known about by the current process.
edje_text_class_set()
EAPI Eina_Bool edje_text_class_set (const char * text_class, const char * font, Evas_Font_Size size)
Set the Edje text class.
Parameters
text_class The text class name
font The font name
size The font size
Returns
EINA_TRUE, on success or EINA_FALSE, on error
This function updates all Edje members at the process level which belong to this text class with the new font attributes. If the size is 0 then the font size will be kept with the previous size. If the size is less then 0 then the font size will be calculated in the percentage. For example, if the size is -50, then the font size will be scaled to half of the original size and if the size is -10 then the font size will be scaled as much as 0.1x.
See also
edje_text_class_get().
edje_thaw()
EAPI void edje_thaw (void)
Thaw Edje objects.
This function thaws all Edje animations in the current process.
Note
for thaw a specific object
See also
edje_object_thaw().
edje_freeze()
References _edje_freeze_calc_count, _edje_freeze_calc_list, and _edje_freeze_val.
Variable Documentation
edje_version
EAPI Edje_Version* edje_version extern
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59