src/lib/Edje_Edit.h File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
Edje_Edit.h File Reference
Functions to deal with edje internal object.
Data Structures
struct _Edje_Edit_Script_Error
Macros
#define EAPI
Typedefs
typedef enum _Edje_Edit_Image_Comp Edje_Edit_Image_Comp
typedef struct _Edje_Edit_Script_Error Edje_Edit_Script_Error
Enumerations
enum _Edje_Edit_Image_Comp { EDJE_EDIT_IMAGE_COMP_RAW , EDJE_EDIT_IMAGE_COMP_USER , EDJE_EDIT_IMAGE_COMP_COMP , EDJE_EDIT_IMAGE_COMP_LOSSY }
Functions
General API
General functions that don't fit in other cateories.
EAPI const char * edje_edit_compiler_get (Evas_Object *obj)
Get the name of the program that compiled the edje file.
EAPI Evas_Object * edje_edit_object_add (Evas *e)
Adds an editable Edje object to the canvas.
EAPI void edje_edit_print_internal_status (Evas_Object *obj)
Print on standard output many information about the internal status of the edje object.
EAPI Eina_Bool edje_edit_save (Evas_Object *obj)
Save the modified edje object back to his file.
EAPI Eina_Bool edje_edit_save_all (Evas_Object *obj)
Saves every group back into the file.
EAPI void edje_edit_string_free (const char *str)
Free a generic string (char *) allocated by an edje_edit_*_get() function.
EAPI void edje_edit_string_list_free (Eina_List *lst)
Free a generic Eina_List of (char *) allocated by an edje_edit_*_get() function.
Groups API
Functions to deal with groups property (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_group_add (Evas_Object *obj, const char *name)
Create a new empty group in the given edje.
EAPI Eina_Bool edje_edit_group_del (Evas_Object *obj, const char *group_name)
Delete the specified group from the given edje.
EAPI Eina_Bool edje_edit_group_exist (Evas_Object *obj, const char *group)
Check if a group with the given name exist in the edje.
EAPI int edje_edit_group_max_h_get (Evas_Object *obj)
Get the group maximum height.
EAPI void edje_edit_group_max_h_set (Evas_Object *obj, int h)
Set the group maximum height.
EAPI int edje_edit_group_max_w_get (Evas_Object *obj)
Get the group maximum width.
EAPI void edje_edit_group_max_w_set (Evas_Object *obj, int w)
Set the group maximum width.
EAPI int edje_edit_group_min_h_get (Evas_Object *obj)
Get the group minimum height.
EAPI void edje_edit_group_min_h_set (Evas_Object *obj, int h)
Set the group minimum height.
EAPI int edje_edit_group_min_w_get (Evas_Object *obj)
Get the group minimum width.
EAPI void edje_edit_group_min_w_set (Evas_Object *obj, int w)
Set the group minimum width.
EAPI Eina_Bool edje_edit_group_name_set (Evas_Object *obj, const char *new_name)
Set a new name for the current open group.
Data API
Functions to deal with data embedded in the edje (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_data_add (Evas_Object *obj, const char *itemname, const char *value)
Create a new global data object in the given edje file.
EAPI Eina_Bool edje_edit_data_del (Evas_Object *obj, const char *itemname)
Delete the given data object from edje.
EAPI Eina_List * edje_edit_data_list_get (Evas_Object *obj)
Retrieves a list with the item names inside the data block.
EAPI Eina_Bool edje_edit_data_name_set (Evas_Object *obj, const char *itemname, const char *newname)
Change the name of the given data object.
EAPI const char * edje_edit_data_value_get (Evas_Object *obj, const char *itemname)
Get the data associated with the given itemname.
EAPI Eina_Bool edje_edit_data_value_set (Evas_Object *obj, const char *itemname, const char *value)
Set the data associated with the given itemname.
EAPI Eina_Bool edje_edit_group_data_add (Evas_Object *obj, const char *itemname, const char *value)
Create a new data object in the given edje file belonging to the current group.
EAPI Eina_Bool edje_edit_group_data_del (Evas_Object *obj, const char *itemname)
Delete the given data object from the group.
EAPI Eina_List * edje_edit_group_data_list_get (Evas_Object *obj)
Retrieves a list with the item names inside the data block at the group level.
EAPI Eina_Bool edje_edit_group_data_name_set (Evas_Object *obj, const char *itemname, const char *newname)
Change the name of the given data object.
EAPI const char * edje_edit_group_data_value_get (Evas_Object *obj, const char *itemname)
Get the data associated with the given itemname.
EAPI Eina_Bool edje_edit_group_data_value_set (Evas_Object *obj, const char *itemname, const char *value)
Set the data associated with the given itemname.
Color Classes API
Functions to deal with Color Classes (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_color_class_add (Evas_Object *obj, const char *name)
Create a new color class object in the given edje.
EAPI Eina_Bool edje_edit_color_class_colors_get (Evas_Object *obj, const char *class_name, int *r, int *g, int *b, int *a, int *r2, int *g2, int *b2, int *a2, int *r3, int *g3, int *b3, int *a3)
Get all the colors that compose the class.
EAPI Eina_Bool edje_edit_color_class_colors_set (Evas_Object *obj, const char *class_name, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Set the colors for the given color class.
EAPI Eina_Bool edje_edit_color_class_del (Evas_Object *obj, const char *name)
Delete the given class object from edje.
EAPI Eina_Bool edje_edit_color_class_name_set (Evas_Object *obj, const char *name, const char *newname)
Change the name of a color class.
EAPI Eina_List * edje_edit_color_classes_list_get (Evas_Object *obj)
Get the list of all the Color Classes in the given edje object.
Text styles API
Functions to deal with text styles (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_style_add (Evas_Object *obj, const char *style)
Create a new text style object in the given edje.
EAPI void edje_edit_style_del (Evas_Object *obj, const char *style)
Delete the given text style and all the child tags.
EAPI Eina_Bool edje_edit_style_tag_add (Evas_Object *obj, const char *style, const char *tag_name)
Add a new tag to the given text style.
EAPI void edje_edit_style_tag_del (Evas_Object *obj, const char *style, const char *tag)
Delete the given tag.
EAPI void edje_edit_style_tag_name_set (Evas_Object *obj, const char *style, const char *tag, const char *new_name)
Set the name of the given tag.
EAPI const char * edje_edit_style_tag_value_get (Evas_Object *obj, const char *style, const char *tag)
Get the value of the given tag.
EAPI void edje_edit_style_tag_value_set (Evas_Object *obj, const char *style, const char *tag, const char *new_value)
Set the value of the given tag.
EAPI Eina_List * edje_edit_style_tags_list_get (Evas_Object *obj, const char *style)
Get the list of all the tags name in the given text style.
EAPI Eina_List * edje_edit_styles_list_get (Evas_Object *obj)
Get the list of all the text styles in the given edje object.
Externals API
Functions to deal with list of external modules (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_external_add (Evas_Object *obj, const char *external)
Add an external module to be requested on edje load.
EAPI Eina_Bool edje_edit_external_del (Evas_Object *obj, const char *external)
Delete the given external from the list.
EAPI Eina_List * edje_edit_externals_list_get (Evas_Object *obj)
Get the list of all the externals requested in the given edje object.
Parts API
Functions to deal with part objects (see Edje Data Collection reference).
EAPI const char * edje_edit_part_above_get (Evas_Object *obj, const char *part)
Get the name of part stacked above the one passed.
EAPI Eina_Bool edje_edit_part_add (Evas_Object *obj, const char *name, Edje_Part_Type type)
Create a new part in the given edje.
EAPI const char * edje_edit_part_api_description_get (Evas_Object *obj, const char *part)
Get api's description of a part.
EAPI Eina_Bool edje_edit_part_api_description_set (Evas_Object *obj, const char *part, const char *description)
Set api's description of a part.
EAPI const char * edje_edit_part_api_name_get (Evas_Object *obj, const char *part)
Get api's name of a part.
EAPI Eina_Bool edje_edit_part_api_name_set (Evas_Object *obj, const char *part, const char *name)
Set api's name of a part.
EAPI const char * edje_edit_part_below_get (Evas_Object *obj, const char *part)
Get the name of part stacked below the one passed.
EAPI const char * edje_edit_part_clip_to_get (Evas_Object *obj, const char *part)
Get the clip_to part.
EAPI Eina_Bool edje_edit_part_clip_to_set (Evas_Object *obj, const char *part, const char *clip_to)
Set a part to clip part to.
EAPI Eina_Bool edje_edit_part_del (Evas_Object *obj, const char *part)
Delete the given part from the edje.
EAPI const char * edje_edit_part_drag_confine_get (Evas_Object *obj, const char *part)
Get the name of the part that is used as 'confine' for the given draggies.
EAPI void edje_edit_part_drag_confine_set (Evas_Object *obj, const char *part, const char *confine)
Set the name of the part that is used as 'confine' for the given draggies.
EAPI int edje_edit_part_drag_count_x_get (Evas_Object *obj, const char *part)
Get horizontal dragable count for part.
EAPI void edje_edit_part_drag_count_x_set (Evas_Object *obj, const char *part, int count)
Set horizontal dragable count for part.
EAPI int edje_edit_part_drag_count_y_get (Evas_Object *obj, const char *part)
Get vertical dragable count for part.
EAPI void edje_edit_part_drag_count_y_set (Evas_Object *obj, const char *part, int count)
Set vertical dragable count for part.
EAPI const char * edje_edit_part_drag_event_get (Evas_Object *obj, const char *part)
Get the name of the part that is used as the receiver of the drag event.
EAPI void edje_edit_part_drag_event_set (Evas_Object *obj, const char *part, const char *event)
Set the name of the part that will receive events from the given draggies.
EAPI int edje_edit_part_drag_step_x_get (Evas_Object *obj, const char *part)
Get horizontal dragable step for part.
EAPI void edje_edit_part_drag_step_x_set (Evas_Object *obj, const char *part, int step)
Set horizontal dragable state for part.
EAPI int edje_edit_part_drag_step_y_get (Evas_Object *obj, const char *part)
Get vertical dragable step for part.
EAPI void edje_edit_part_drag_step_y_set (Evas_Object *obj, const char *part, int step)
Set vertical dragable state for part.
EAPI int edje_edit_part_drag_x_get (Evas_Object *obj, const char *part)
Get horizontal dragable state for part.
EAPI void edje_edit_part_drag_x_set (Evas_Object *obj, const char *part, int drag)
Set horizontal dragable state for part.
EAPI int edje_edit_part_drag_y_get (Evas_Object *obj, const char *part)
Get vertical dragable state for part.
EAPI void edje_edit_part_drag_y_set (Evas_Object *obj, const char *part, int drag)
Set vertical dragable state for part.
EAPI Edje_Text_Effect edje_edit_part_effect_get (Evas_Object *obj, const char *part)
Get the effect for a given part.
EAPI void edje_edit_part_effect_set (Evas_Object *obj, const char *part, Edje_Text_Effect effect)
Set the effect for a given part.
EAPI Eina_Bool edje_edit_part_exist (Evas_Object *obj, const char *part)
Check if a part with the given name exist in the edje object.
EAPI Eina_Bool edje_edit_part_external_add (Evas_Object *obj, const char *name, const char *source)
Create a new part of type EXTERNAL in the given edje.
EAPI Evas_Event_Flags edje_edit_part_ignore_flags_get (Evas_Object *obj, const char *part)
Get ignore_flags for part.
EAPI void edje_edit_part_ignore_flags_set (Evas_Object *obj, const char *part, Evas_Event_Flags ignore_flags)
Set ignore_flags for part.
EAPI Eina_Bool edje_edit_part_mouse_events_get (Evas_Object *obj, const char *part)
Get mouse_events for part.
EAPI void edje_edit_part_mouse_events_set (Evas_Object *obj, const char *part, Eina_Bool mouse_events)
Set mouse_events for part.
EAPI Eina_Bool edje_edit_part_name_set (Evas_Object *obj, const char *part, const char *new_name)
Set a new name for part.
EAPI Eina_Bool edje_edit_part_repeat_events_get (Evas_Object *obj, const char *part)
Get repeat_events for part.
EAPI void edje_edit_part_repeat_events_set (Evas_Object *obj, const char *part, Eina_Bool repeat_events)
Set repeat_events for part.
EAPI Eina_Bool edje_edit_part_restack_above (Evas_Object *obj, const char *part)
Move the given part above the next one.
EAPI Eina_Bool edje_edit_part_restack_below (Evas_Object *obj, const char *part)
Move the given part below the previous one.
EAPI Eina_Bool edje_edit_part_scale_get (Evas_Object *obj, const char *part)
Get scale for the part.
EAPI void edje_edit_part_scale_set (Evas_Object *obj, const char *part, Eina_Bool scale)
Set scale property for the part.
EAPI const char * edje_edit_part_selected_state_get (Evas_Object *obj, const char *part, double *value)
Get the current selected state in part.
EAPI Eina_Bool edje_edit_part_selected_state_set (Evas_Object *obj, const char *part, const char *state, double value)
Set the current state in part.
EAPI const char * edje_edit_part_source_get (Evas_Object *obj, const char *part)
Get the source of part.
EAPI Eina_Bool edje_edit_part_source_set (Evas_Object *obj, const char *part, const char *source)
Set the source of part.
EAPI Edje_Part_Type edje_edit_part_type_get (Evas_Object *obj, const char *part)
Get the type of a part.
EAPI Eina_List * edje_edit_parts_list_get (Evas_Object *obj)
Get the list of all the parts in the given edje object.
States API
Functions to deal with part states (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_part_states_list_get (Evas_Object *obj, const char *part)
Get the list of all the states in the given part.
EAPI Eina_Bool edje_edit_state_add (Evas_Object *obj, const char *part, const char *name, double value)
Create a new state to the give part.
EAPI double edje_edit_state_align_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the horizontal align value of a part state.
EAPI void edje_edit_state_align_x_set (Evas_Object *obj, const char *part, const char *state, double value, double align)
Set the horizontal align value of a part state.
EAPI double edje_edit_state_align_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the vertical align value of a part state.
EAPI void edje_edit_state_align_y_set (Evas_Object *obj, const char *part, const char *state, double value, double align)
Set the vertical align value of a part state.
EAPI double edje_edit_state_aspect_max_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the maximum aspect value of a part state.
EAPI void edje_edit_state_aspect_max_set (Evas_Object *obj, const char *part, const char *state, double value, double aspect)
Set the maximum aspect value of a part state.
EAPI double edje_edit_state_aspect_min_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the minimum aspect value of a part state.
EAPI void edje_edit_state_aspect_min_set (Evas_Object *obj, const char *part, const char *state, double value, double aspect)
Set the minimum aspect value of a part state.
EAPI unsigned char edje_edit_state_aspect_pref_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the aspect preference of a part state.
EAPI void edje_edit_state_aspect_pref_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char pref)
Set the aspect preference of a part state.
EAPI void edje_edit_state_color2_get (Evas_Object *obj, const char *part, const char *state, double value, int *r, int *g, int *b, int *a)
Get the color2 of a part state.
EAPI void edje_edit_state_color2_set (Evas_Object *obj, const char *part, const char *state, double value, int r, int g, int b, int a)
Set the color2 of a part state.
EAPI void edje_edit_state_color3_get (Evas_Object *obj, const char *part, const char *state, double value, int *r, int *g, int *b, int *a)
Get the color3 of a part state.
EAPI void edje_edit_state_color3_set (Evas_Object *obj, const char *part, const char *state, double value, int r, int g, int b, int a)
Set the color3 of a part state.
EAPI const char * edje_edit_state_color_class_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the color class of the given part state.
EAPI void edje_edit_state_color_class_set (Evas_Object *obj, const char *part, const char *state, double value, const char *color_class)
Set the color class of the given part state.
EAPI void edje_edit_state_color_get (Evas_Object *obj, const char *part, const char *state, double value, int *r, int *g, int *b, int *a)
Get the color of a part state.
EAPI void edje_edit_state_color_set (Evas_Object *obj, const char *part, const char *state, double value, int r, int g, int b, int a)
Set the color of a part state.
EAPI Eina_Bool edje_edit_state_copy (Evas_Object *obj, const char *part, const char *from, double val_from, const char *to, double val_to)
Copies the state from into to.
EAPI Eina_Bool edje_edit_state_del (Evas_Object *obj, const char *part, const char *state, double value)
Delete the given part state from the edje.
EAPI Eina_Bool edje_edit_state_exist (Evas_Object *obj, const char *part, const char *state, double value)
Check if a part state with the given name exist.
EAPI Eina_Bool edje_edit_state_external_param_bool_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Eina_Bool *val)
Get external parameter of type BOOL.
EAPI Eina_Bool edje_edit_state_external_param_bool_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Eina_Bool val)
Set external parameter of type BOOL.
EAPI Eina_Bool edje_edit_state_external_param_choice_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char **val)
Get external parameter of type CHOICE.
EAPI Eina_Bool edje_edit_state_external_param_choice_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char *val)
Set external parameter of type CHOICE.
EAPI Eina_Bool edje_edit_state_external_param_double_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, double *val)
Get external parameter of type DOUBLE.
EAPI Eina_Bool edje_edit_state_external_param_double_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, double val)
Set external parameter of type DOUBLE.
EAPI Eina_Bool edje_edit_state_external_param_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Edje_External_Param_Type *type, void **val)
Get the external parameter type and value.
EAPI Eina_Bool edje_edit_state_external_param_int_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, int *val)
Get external parameter of type INT.
EAPI Eina_Bool edje_edit_state_external_param_int_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, int val)
Set external parameter of type INT.
EAPI Eina_Bool edje_edit_state_external_param_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Edje_External_Param_Type type,...)
Set the external parameter type and value, adding it if it didn't exist before.
EAPI Eina_Bool edje_edit_state_external_param_string_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char **val)
Get external parameter of type STRING.
EAPI Eina_Bool edje_edit_state_external_param_string_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char *val)
Set external parameter of type STRING.
EAPI const Eina_List * edje_edit_state_external_params_list_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the list of parameters for an external part.
EAPI int edje_edit_state_fill_origin_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the fill horizontal origin offset value of a part state.
EAPI void edje_edit_state_fill_origin_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the fill horizontal origin offset value of a part state.
EAPI int edje_edit_state_fill_origin_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the fill vertical origin offset value of a part state.
EAPI void edje_edit_state_fill_origin_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Set the fill vertical origin offset value of a part state.
EAPI double edje_edit_state_fill_origin_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the fill horizontal origin relative value of a part state.
EAPI void edje_edit_state_fill_origin_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the fill horizontal origin relative value of a part state.
EAPI double edje_edit_state_fill_origin_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the fill vertical origin relative value of a part state.
EAPI void edje_edit_state_fill_origin_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Set the fill horizontal origin relative value of a part state.
EAPI int edje_edit_state_fill_size_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the fill horizontal size offset value of a part state.
EAPI void edje_edit_state_fill_size_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the fill horizontal size offset value of a part state.
EAPI int edje_edit_state_fill_size_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the fill vertical size offset value of a part state.
EAPI void edje_edit_state_fill_size_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Set the fill vertical size offset value of a part state.
EAPI double edje_edit_state_fill_size_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the fill horizontal size relative value of a part state.
EAPI void edje_edit_state_fill_size_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the fill horizontal size relative value of a part state.
EAPI double edje_edit_state_fill_size_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the fill vertical size relative value of a part state.
EAPI void edje_edit_state_fill_size_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the fill vertical size relative value of a part state.
EAPI int edje_edit_state_max_h_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the maximum height value of a part state.
EAPI void edje_edit_state_max_h_set (Evas_Object *obj, const char *part, const char *state, double value, int max_h)
Set the maximum height value of a part state.
EAPI int edje_edit_state_max_w_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the maximum width value of a part state.
EAPI void edje_edit_state_max_w_set (Evas_Object *obj, const char *part, const char *state, double value, int max_w)
Set the maximum width value of a part state.
EAPI int edje_edit_state_min_h_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the minimum height value of a part state.
EAPI void edje_edit_state_min_h_set (Evas_Object *obj, const char *part, const char *state, double value, int min_h)
Set the minimum height value of a part state.
EAPI int edje_edit_state_min_w_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the minimum width value of a part state.
EAPI void edje_edit_state_min_w_set (Evas_Object *obj, const char *part, const char *state, double value, int min_w)
Set the minimum width value of a part state.
EAPI Eina_Bool edje_edit_state_name_set (Evas_Object *obj, const char *part, const char *state, double value, const char *new_name, double new_value)
Set a new name for the given state in the given part.
EAPI int edje_edit_state_rel1_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the 'rel1 offset X' value of state.
EAPI void edje_edit_state_rel1_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the 'rel1 offset X' value of state.
EAPI int edje_edit_state_rel1_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the 'rel1 offset Y' value of state.
EAPI void edje_edit_state_rel1_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Set the 'rel1 offset Y' value of state.
EAPI double edje_edit_state_rel1_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the 'rel1 relative X' value of state.
EAPI void edje_edit_state_rel1_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the 'rel1 relative X' value of state.
EAPI double edje_edit_state_rel1_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the 'rel1 relative Y' value of state.
EAPI void edje_edit_state_rel1_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Set the 'rel1 relative Y' value of state.
EAPI const char * edje_edit_state_rel1_to_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the part name rel1x is relative to.
EAPI void edje_edit_state_rel1_to_x_set (Evas_Object *obj, const char *part, const char *state, double value, const char *rel_to)
Set the part rel1x is relative to.
EAPI const char * edje_edit_state_rel1_to_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the part name rel1y is relative to.
EAPI void edje_edit_state_rel1_to_y_set (Evas_Object *obj, const char *part, const char *state, double value, const char *rel_to)
Set the part rel1y is relative to.
EAPI int edje_edit_state_rel2_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the 'rel2 offset X' value of state.
EAPI void edje_edit_state_rel2_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the 'rel2 offset X' value of state.
EAPI int edje_edit_state_rel2_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the 'rel2 offset Y' value of state.
EAPI void edje_edit_state_rel2_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Set the 'rel2 offset Y' value of state.
EAPI double edje_edit_state_rel2_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the 'rel2 relative X' value of state.
EAPI void edje_edit_state_rel2_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Set the 'rel2 relative X' value of state.
EAPI double edje_edit_state_rel2_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the 'rel2 relative Y' value of state.
EAPI void edje_edit_state_rel2_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Set the 'rel2 relative Y' value of state.
EAPI const char * edje_edit_state_rel2_to_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the part name rel2x is relative to.
EAPI void edje_edit_state_rel2_to_x_set (Evas_Object *obj, const char *part, const char *state, double value, const char *rel_to)
Set the part rel2x is relative to.
EAPI const char * edje_edit_state_rel2_to_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the part name rel2y is relative to.
EAPI void edje_edit_state_rel2_to_y_set (Evas_Object *obj, const char *part, const char *state, double value, const char *rel_to)
Set the part rel2y is relative to.
EAPI Eina_Bool edje_edit_state_visible_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the visibility of a part state.
EAPI void edje_edit_state_visible_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool visible)
Set the visibility of a part state.
Text API
Functions to deal with text objects (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_font_add (Evas_Object *obj, const char *path, const char *alias)
Add a new font to the edje file.
EAPI Eina_Bool edje_edit_font_del (Evas_Object *obj, const char *alias)
Delete font from the edje file.
EAPI const char * edje_edit_font_path_get (Evas_Object *obj, const char *alias)
Get font path for a given font alias.
EAPI Eina_List * edje_edit_fonts_list_get (Evas_Object *obj)
Get the list of all the fonts in the given edje.
EAPI const char * edje_edit_state_font_get (Evas_Object *obj, const char *part, const char *state, double value)
Get font name for a given part state.
EAPI void edje_edit_state_font_set (Evas_Object *obj, const char *part, const char *state, double value, const char *font)
Set font name for a given part state.
EAPI double edje_edit_state_text_align_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the text horizontal align of a part state.
EAPI void edje_edit_state_text_align_x_set (Evas_Object *obj, const char *part, const char *state, double value, double align)
Set the text horizontal align of a part state.
EAPI double edje_edit_state_text_align_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the text vertical align of a part state.
EAPI void edje_edit_state_text_align_y_set (Evas_Object *obj, const char *part, const char *state, double value, double align)
Set the text vertical align of a part state.
EAPI double edje_edit_state_text_elipsis_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the text elipsis of a part state.
EAPI void edje_edit_state_text_elipsis_set (Evas_Object *obj, const char *part, const char *state, double value, double balance)
Set the text vertical align of a part state.
EAPI Eina_Bool edje_edit_state_text_fit_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get if the text part fit it's container horizontally.
EAPI void edje_edit_state_text_fit_x_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool fit)
Set if the text part should fit it's container horizontally.
EAPI Eina_Bool edje_edit_state_text_fit_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get if the text part fit it's container vertically.
EAPI void edje_edit_state_text_fit_y_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool fit)
Set if the text part should fit it's container vertically.
EAPI const char * edje_edit_state_text_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the text of a part state.
EAPI void edje_edit_state_text_set (Evas_Object *obj, const char *part, const char *state, double value, const char *text)
Set the text of a part state.
EAPI int edje_edit_state_text_size_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the text size of a part state.
EAPI void edje_edit_state_text_size_set (Evas_Object *obj, const char *part, const char *state, double value, int size)
Set the text size of a part state.
Images API
Functions to deal with image objects (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_image_add (Evas_Object *obj, const char *path)
Add an new image to the image collection.
EAPI int edje_edit_image_compression_rate_get (Evas_Object *obj, const char *image)
Get compression rate for the given image.
EAPI Edje_Edit_Image_Comp edje_edit_image_compression_type_get (Evas_Object *obj, const char *image)
Get compression type for the given image.
EAPI Eina_Bool edje_edit_image_data_add (Evas_Object *obj, const char *name, int id)
Add an image entry to the image collection.
EAPI Eina_Bool edje_edit_image_del (Evas_Object *obj, const char *name)
Delete an image from the image collection.
EAPI int edje_edit_image_id_get (Evas_Object *obj, const char *image_name)
Get image id for a given image name.
EAPI Eina_List * edje_edit_images_list_get (Evas_Object *obj)
Get the list of all the images in the given edje.
EAPI unsigned char edje_edit_state_image_border_fill_get (Evas_Object *obj, const char *part, const char *state, double value)
Get if the image center should be draw.
EAPI void edje_edit_state_image_border_fill_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char fill)
Set if the image center should be draw.
EAPI void edje_edit_state_image_border_get (Evas_Object *obj, const char *part, const char *state, double value, int *l, int *r, int *t, int *b)
Get the image border of a part state.
EAPI void edje_edit_state_image_border_set (Evas_Object *obj, const char *part, const char *state, double value, int l, int r, int t, int b)
Set the image border of a part state.
EAPI const char * edje_edit_state_image_get (Evas_Object *obj, const char *part, const char *state, double value)
Get normal image name for a given part state.
EAPI void edje_edit_state_image_set (Evas_Object *obj, const char *part, const char *state, double value, const char *image)
Set normal image for a given part state.
EAPI Eina_Bool edje_edit_state_tween_add (Evas_Object *obj, const char *part, const char *state, double value, const char *tween)
Add a new tween frame to the given part state.
EAPI Eina_Bool edje_edit_state_tween_del (Evas_Object *obj, const char *part, const char *state, double value, const char *tween)
Remove the first tween with the given name.
EAPI Eina_List * edje_edit_state_tweens_list_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the list of all the tweens images in the given part state.
Spectrum API
Functions to manage spectrum (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_spectra_add (Evas_Object *obj, const char *name)
Add a new spectra in the given edje object.
EAPI Eina_Bool edje_edit_spectra_del (Evas_Object *obj, const char *spectra)
Delete the given spectra from the edje object.
EAPI Eina_Bool edje_edit_spectra_name_set (Evas_Object *obj, const char *spectra, const char *name)
Change the name of the given spectra.
EAPI Eina_Bool edje_edit_spectra_stop_color_get (Evas_Object *obj, const char *spectra, int stop_number, int *r, int *g, int *b, int *a, int *d)
Get the colors of the given stop.
EAPI Eina_Bool edje_edit_spectra_stop_color_set (Evas_Object *obj, const char *spectra, int stop_number, int r, int g, int b, int a, int d)
Set the colors of the given stop.
EAPI int edje_edit_spectra_stop_num_get (Evas_Object *obj, const char *spectra)
Get the number of stops in the given spectra.
EAPI Eina_Bool edje_edit_spectra_stop_num_set (Evas_Object *obj, const char *spectra, int num)
Set the number of stops in the given spectra.
EAPI Eina_List * edje_edit_spectrum_list_get (Evas_Object *obj)
Get the list of all the spectrum in the given edje object.
Gradient API
Functions to deal with gradient objects (see Edje Data Collection reference).
EAPI int edje_edit_state_gradient_angle_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the angle of the gradient.
EAPI void edje_edit_state_gradient_angle_set (Evas_Object *obj, const char *part, const char *state, double value, int angle)
Set the angle of the gradient.
EAPI int edje_edit_state_gradient_rel1_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the gradient rel1 horizontal offset value.
EAPI Eina_Bool edje_edit_state_gradient_rel1_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, int val)
Set the gradient rel1 horizontal offset value.
EAPI int edje_edit_state_gradient_rel1_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the gradient rel1 vertical offset value.
EAPI Eina_Bool edje_edit_state_gradient_rel1_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, int val)
Set the gradient rel1 vertical offset value.
EAPI double edje_edit_state_gradient_rel1_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the gradient rel1 horizontal relative value.
EAPI Eina_Bool edje_edit_state_gradient_rel1_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double val)
Set the gradient rel1 horizontal relative value.
EAPI double edje_edit_state_gradient_rel1_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the gradient rel1 vertical relative value.
EAPI Eina_Bool edje_edit_state_gradient_rel1_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double val)
Set the gradient rel1 vertical relative value.
EAPI int edje_edit_state_gradient_rel2_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the gradient rel2 horizontal offset value.
EAPI Eina_Bool edje_edit_state_gradient_rel2_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, int val)
Set the gradient rel2 horizontal offset value.
EAPI int edje_edit_state_gradient_rel2_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the gradient rel2 vertical offset value.
EAPI Eina_Bool edje_edit_state_gradient_rel2_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, int val)
Set the gradient rel2 vertical offset value.
EAPI double edje_edit_state_gradient_rel2_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the gradient rel2 horizontal relative value.
EAPI Eina_Bool edje_edit_state_gradient_rel2_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double val)
Set the gradient rel2 horizontal relative value.
EAPI double edje_edit_state_gradient_rel2_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the gradient rel2 vertical relative value.
EAPI Eina_Bool edje_edit_state_gradient_rel2_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double val)
Set the gradient rel2 vertical relative value.
EAPI const char * edje_edit_state_gradient_spectra_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the spectra used by part state.
EAPI Eina_Bool edje_edit_state_gradient_spectra_set (Evas_Object *obj, const char *part, const char *state, double value, const char *spectra)
Set the spectra used by part state.
EAPI const char * edje_edit_state_gradient_type_get (Evas_Object *obj, const char *part, const char *state, double value)
Get the type of gradient.
EAPI Eina_Bool edje_edit_state_gradient_type_set (Evas_Object *obj, const char *part, const char *state, double value, const char *type)
Set the type of gradient.
EAPI Eina_Bool edje_edit_state_gradient_use_fill_get (Evas_Object *obj, const char *part, const char *state, double value)
Get if the current gradient use the fill properties or the gradient_rel as params.
Programs API
Functions to deal with programs (see Edje Data Collection reference).
EAPI Edje_Action_Type edje_edit_program_action_get (Evas_Object *obj, const char *prog)
Get the action of a given program.
EAPI Eina_Bool edje_edit_program_action_set (Evas_Object *obj, const char *prog, Edje_Action_Type action)
Set the action of a given program.
EAPI Eina_Bool edje_edit_program_add (Evas_Object *obj, const char *name)
Add a new program to the edje file.
EAPI Eina_Bool edje_edit_program_after_add (Evas_Object *obj, const char *prog, const char *after)
Add a new program name to the list of 'afters' in the given program.
EAPI Eina_Bool edje_edit_program_after_del (Evas_Object *obj, const char *prog, const char *after)
Delete the given program from the list of 'afters' of the program.
EAPI Eina_Bool edje_edit_program_afters_clear (Evas_Object *obj, const char *prog)
Clear the 'afters' list of the given program.
EAPI Eina_List * edje_edit_program_afters_get (Evas_Object *obj, const char *prog)
Get the list of action that will be run after the give program.
EAPI const char * edje_edit_program_api_description_get (Evas_Object *obj, const char *prog)
Get api's description of a program.
EAPI Eina_Bool edje_edit_program_api_description_set (Evas_Object *obj, const char *prog, const char *description)
Set api's description of a program.
EAPI const char * edje_edit_program_api_name_get (Evas_Object *obj, const char *prog)
Get api's name of a program.
EAPI Eina_Bool edje_edit_program_api_name_set (Evas_Object *obj, const char *prog, const char *name)
Set api's name of a program.
EAPI Eina_Bool edje_edit_program_del (Evas_Object *obj, const char *prog)
Remove the given program from the edje file.
EAPI Eina_Bool edje_edit_program_exist (Evas_Object *obj, const char *prog)
Check if a program with the given name exist in the edje object.
EAPI const char * edje_edit_program_filter_part_get (Evas_Object *obj, const char *prog)
EAPI Eina_Bool edje_edit_program_filter_part_set (Evas_Object *obj, const char *prog, const char *filter_part)
EAPI double edje_edit_program_in_from_get (Evas_Object *obj, const char *prog)
Get in.from of a given program.
EAPI Eina_Bool edje_edit_program_in_from_set (Evas_Object *obj, const char *prog, double seconds)
Set in.from of a given program.
EAPI double edje_edit_program_in_range_get (Evas_Object *obj, const char *prog)
Get in.range of a given program.
EAPI Eina_Bool edje_edit_program_in_range_set (Evas_Object *obj, const char *prog, double seconds)
Set in.range of a given program.
EAPI Eina_Bool edje_edit_program_name_set (Evas_Object *obj, const char *prog, const char *new_name)
Set a new name for the given program.
EAPI Eina_Bool edje_edit_program_run (Evas_Object *obj, const char *prog)
Run the given program.
EAPI const char * edje_edit_program_signal_get (Evas_Object *obj, const char *prog)
Get signal of a given program.
EAPI Eina_Bool edje_edit_program_signal_set (Evas_Object *obj, const char *prog, const char *signal)
Set signal of the given program.
EAPI const char * edje_edit_program_source_get (Evas_Object *obj, const char *prog)
Get source of a given program.
EAPI Eina_Bool edje_edit_program_source_set (Evas_Object *obj, const char *prog, const char *source)
Set source of the given program.
EAPI const char * edje_edit_program_state2_get (Evas_Object *obj, const char *prog)
Get the state2 for the given program.
EAPI Eina_Bool edje_edit_program_state2_set (Evas_Object *obj, const char *prog, const char *state2)
Set the state2 for the given program.
EAPI const char * edje_edit_program_state_get (Evas_Object *obj, const char *prog)
Get the state for the given program.
EAPI Eina_Bool edje_edit_program_state_set (Evas_Object *obj, const char *prog, const char *state)
Set the state for the given program.
EAPI Eina_Bool edje_edit_program_target_add (Evas_Object *obj, const char *prog, const char *target)
Add a new target program to the list of 'targets' in the given program.
EAPI Eina_Bool edje_edit_program_target_del (Evas_Object *obj, const char *prog, const char *target)
Deletes a target from the list of 'targets' in the given program.
EAPI Eina_Bool edje_edit_program_targets_clear (Evas_Object *obj, const char *prog)
Clear the 'targets' list of the given program.
EAPI Eina_List * edje_edit_program_targets_get (Evas_Object *obj, const char *prog)
Get the list of the targets for the given program.
EAPI Edje_Tween_Mode edje_edit_program_transition_get (Evas_Object *obj, const char *prog)
Get the type of transition to use when apply animations.
EAPI Eina_Bool edje_edit_program_transition_set (Evas_Object *obj, const char *prog, Edje_Tween_Mode transition)
Set the type of transition to use when apply animations.
EAPI double edje_edit_program_transition_time_get (Evas_Object *obj, const char *prog)
Get the duration of the transition in seconds.
EAPI Eina_Bool edje_edit_program_transition_time_set (Evas_Object *obj, const char *prog, double seconds)
Set the duration of the transition in seconds.
EAPI double edje_edit_program_value2_get (Evas_Object *obj, const char *prog)
Get the value of state2 for the given program.
EAPI Eina_Bool edje_edit_program_value2_set (Evas_Object *obj, const char *prog, double value)
Set the value2 of state for the given program.
EAPI double edje_edit_program_value_get (Evas_Object *obj, const char *prog)
Get the value of state for the given program.
EAPI Eina_Bool edje_edit_program_value_set (Evas_Object *obj, const char *prog, double value)
Set the value of state for the given program.
EAPI Eina_List * edje_edit_programs_list_get (Evas_Object *obj)
Get the list of all the programs in the given edje object.
Scripts API
Functions to deal with embryo scripts (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_script_compile (Evas_Object *obj)
Compile the Embryo script for the given object.
EAPI const Eina_List * edje_edit_script_error_list_get (Evas_Object *obj)
Get the list of errors resulting from the last script build.
EAPI char * edje_edit_script_get (Evas_Object *obj)
Get the Embryo script for the group of the given object.
EAPI char * edje_edit_script_program_get (Evas_Object *obj, const char *prog)
Get the Embryo script for the given program.
EAPI void edje_edit_script_program_set (Evas_Object *obj, const char *prog, const char *code)
Set the Embryo script for the given program.
EAPI void edje_edit_script_set (Evas_Object *obj, const char *code)
Set the code for the group script.
Variables
Error API
to deal with error messages (see Edje Data Collection reference).
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_REFERENCED
Detailed Description
Functions to deal with edje internal object.
Don't use in standard situations. The use of any of the edje_edit_* functions can break your theme ability, remember that the program must be separated from the interface!
This was intended ONLY for use in an actual edje editor program. Unless you are writing one of these, do NOT use this API here.
The API can be used to query or set every part of an edje object in real time. You can manage every aspect of parts, part states, programs, script and whatever is contained in the edje file. For a reference of what all parameter means look at the complete Edje Data Collection reference.
Don't forget to free all the strings and the lists returned by any edje_edit_*() functions using edje_edit_string_free() and edje_edit_string_list_free() when you don't need anymore.
Example: print all the part in a loaded edje_object
Eina_List *parts, *l;
char *part;
parts = edje_edit_parts_list_get(edje_object);
EINA_LIST_FOREACH(parts, l, part)
{
   printf("Part: %s\n", part);
}
edje_edit_string_list_free(parts);
Example: Change the color of a rect inside an edje file
Evas_Object *edje;
edje = edje_edit_object_add(evas);
edje_object_file_set(edje, "edj/file/name", "group to load");
edje_edit_state_color_set(edje, "MyRectName", "default", 0.00, 255, 255, 0, 255);
edje_edit_save(edje);
Macro Definition Documentation
EAPI
#define EAPI
Typedef Documentation
Edje_Edit_Image_Comp
typedef enum _Edje_Edit_Image_Comp Edje_Edit_Image_Comp
Edje_Edit_Script_Error
typedef struct _Edje_Edit_Script_Error Edje_Edit_Script_Error
Enumeration Type Documentation
_Edje_Edit_Image_Comp
enum _Edje_Edit_Image_Comp
Enumerator
EDJE_EDIT_IMAGE_COMP_RAW
EDJE_EDIT_IMAGE_COMP_USER
EDJE_EDIT_IMAGE_COMP_COMP
EDJE_EDIT_IMAGE_COMP_LOSSY
Function Documentation
edje_edit_color_class_add()
EAPI Eina_Bool edje_edit_color_class_add (Evas_Object * obj, const char * name)
Create a new color class object in the given edje.
If another class with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
name Name for the new color class.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_File::color_classes, _Edje::file, GET_ED_OR_RETURN, name, and _Edje_Color_Class::name.
edje_edit_color_class_colors_get()
EAPI Eina_Bool edje_edit_color_class_colors_get (Evas_Object * obj, const char * class_name, int * r, int * g, int * b, int * a, int * r2, int * g2, int * b2, int * a2, int * r3, int * g3, int * b3, int * a3)
Get all the colors that compose the class.
You can pass NULL to colors you are not intrested in.
Parameters
obj Object being edited.
class_name Color class to fetch values.
r Red component of main color.
g Green component of main color.
b Blue component of main color.
a Alpha component of main color.
r2 Red component of secondary color.
g2 Green component of secondary color.
b2 Blue component of secondary color.
a2 Alpha component of secondary color.
r3 Red component of tertiary color.
g3 Green component of tertiary color.
b3 Blue component of tertiary color.
a3 Alpha component of tertiary color.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_Color_Class::a, _Edje_Color_Class::a2, _Edje_Color_Class::a3, _Edje_Color_Class::b, _Edje_Color_Class::b2, _Edje_Color_Class::b3, _Edje_File::color_classes, _Edje::file, _Edje_Color_Class::g, _Edje_Color_Class::g2, _Edje_Color_Class::g3, GET_ED_OR_RETURN, _Edje_Color_Class::name, _Edje_Color_Class::r, _Edje_Color_Class::r2, and _Edje_Color_Class::r3.
edje_edit_color_class_colors_set()
EAPI Eina_Bool edje_edit_color_class_colors_set (Evas_Object * obj, const char * class_name, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Set the colors for the given color class.
If you set a color to -1 it will not be touched.
Parameters
obj Object being edited.
class_name Color class to fetch values.
r Red component of main color.
g Green component of main color.
b Blue component of main color.
a Alpha component of main color.
r2 Red component of secondary color.
g2 Green component of secondary color.
b2 Blue component of secondary color.
a2 Alpha component of secondary color.
r3 Red component of tertiary color.
g3 Green component of tertiary color.
b3 Blue component of tertiary color.
a3 Alpha component of tertiary color.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_Color_Class::a, _Edje_Color_Class::a2, _Edje_Color_Class::a3, _Edje_Color_Class::b, _Edje_Color_Class::b2, _Edje_Color_Class::b3, _Edje_File::color_classes, _Edje::file, _Edje_Color_Class::g, _Edje_Color_Class::g2, _Edje_Color_Class::g3, GET_ED_OR_RETURN, _Edje_Color_Class::name, _Edje_Color_Class::r, _Edje_Color_Class::r2, and _Edje_Color_Class::r3.
edje_edit_color_class_del()
EAPI Eina_Bool edje_edit_color_class_del (Evas_Object * obj, const char * name)
Delete the given class object from edje.
Parameters
obj Object being edited.
name Color class to delete.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_File::color_classes, _Edje::file, GET_ED_OR_RETURN, name, and _Edje_Color_Class::name.
edje_edit_color_class_name_set()
EAPI Eina_Bool edje_edit_color_class_name_set (Evas_Object * obj, const char * name, const char * newname)
Change the name of a color class.
Parameters
obj Object being edited.
name Color class to rename.
newname New name for the color class.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_File::color_classes, _Edje::file, GET_ED_OR_RETURN, name, and _Edje_Color_Class::name.
edje_edit_color_classes_list_get()
EAPI Eina_List* edje_edit_color_classes_list_get (Evas_Object * obj)
Get the list of all the Color Classes in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being one color class.
References _Edje_File::color_classes, _Edje::file, GET_ED_OR_RETURN, and _Edje_Color_Class::name.
edje_edit_compiler_get()
EAPI const char* edje_edit_compiler_get (Evas_Object * obj)
Get the name of the program that compiled the edje file.
Can be 'edje_cc' or 'edje_edit'
Parameters
obj Object being edited.
Returns
Compiler stored in the Edje file
References _Edje_File::compiler, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_add()
EAPI Eina_Bool edje_edit_data_add (Evas_Object * obj, const char * itemname, const char * value)
Create a new global data object in the given edje file.
If another data entry with the same name exists, nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
itemname Name for the new data entry.
value Value for the new data entry.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_File::data, _Edje::file, GET_ED_OR_RETURN, and _Edje_String::str.
edje_edit_data_del()
EAPI Eina_Bool edje_edit_data_del (Evas_Object * obj, const char * itemname)
Delete the given data object from edje.
Parameters
obj Object being edited.
itemname Data entry to remove from the global data block.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje_File::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_list_get()
EAPI Eina_List* edje_edit_data_list_get (Evas_Object * obj)
Retrieves a list with the item names inside the data block.
Parameters
obj Object being edited.
Returns
List of strings, each being a name entry in the global data block for the file.
References _Edje_File::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_name_set()
EAPI Eina_Bool edje_edit_data_name_set (Evas_Object * obj, const char * itemname, const char * newname)
Change the name of the given data object.
Parameters
obj Object being edited.
itemname Data entry to rename.
newname New name for the data entry.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje_File::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_value_get()
EAPI const char* edje_edit_data_value_get (Evas_Object * obj, const char * itemname)
Get the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry to fetch the value for.
Returns
Value of the given entry, or NULL if not found.
References _Edje_File::data, edje_string_get(), _Edje::file, and GET_ED_OR_RETURN.
edje_edit_data_value_set()
EAPI Eina_Bool edje_edit_data_value_set (Evas_Object * obj, const char * itemname, const char * value)
Set the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of data entry to change the value.
value New value for the entry.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje_File::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_external_add()
EAPI Eina_Bool edje_edit_external_add (Evas_Object * obj, const char * external)
Add an external module to be requested on edje load.
Parameters
obj Object being edited.
external Name of the external module to add to the list of autoload.
Returns
EINA_TRUE on success (or it was already there), EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_external_del()
EAPI Eina_Bool edje_edit_external_del (Evas_Object * obj, const char * external)
Delete the given external from the list.
Parameters
obj Object being edited.
external Name of the external module to remove from the autoload list.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_externals_list_get()
EAPI Eina_List* edje_edit_externals_list_get (Evas_Object * obj)
Get the list of all the externals requested in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being an entry in the block of automatically loaded external modules.
References _Edje_External_Directory::entries, _Edje_External_Directory::entries_count, _Edje_External_Directory_Entry::entry, _Edje_File::external_dir, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_font_add()
EAPI Eina_Bool edje_edit_font_add (Evas_Object * obj, const char * path, const char * alias)
Add a new font to the edje file.
The newly created font will be available to all the groups in the edje, not only the current one.
Parameters
obj Object being edited.
path The file path to load the font from.
alias The alias for file, or NULL to use filename
Returns
EINA_TRUE if font cat be loaded, EINA_FALSE otherwise.
References _Edje::file, _Edje_File::fonts, GET_ED_OR_RETURN, INF, and _Edje::path.
edje_edit_font_del()
EAPI Eina_Bool edje_edit_font_del (Evas_Object * obj, const char * alias)
Delete font from the edje file.
The font will be removed from all the groups in the edje, not only the current one.
Parameters
obj Object being edited.
alias The font alias
Returns
EINA_TRUE if successful, EINA_FALSE otherwise (including the case when the alias is not valid).
References ERR, _Edje::file, _Edje_File::fonts, GET_ED_OR_RETURN, INF, _Edje::path, and WRN.
edje_edit_font_path_get()
EAPI const char* edje_edit_font_path_get (Evas_Object * obj, const char * alias)
Get font path for a given font alias.
Remember to free the string with edje_edit_string_free()
Parameters
obj Object being edited.
alias The font alias.
Returns
The path of the given font alias.
References _Edje_Font_Directory_Entry::entry, _Edje_Font_Directory_Entry::file, _Edje::file, _Edje_File::fonts, and GET_ED_OR_RETURN.
edje_edit_fonts_list_get()
EAPI Eina_List* edje_edit_fonts_list_get (Evas_Object * obj)
Get the list of all the fonts in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A list containing all the fonts names found in the edje file.
References _Edje_Font_Directory_Entry::entry, _Edje::file, _Edje_File::fonts, and GET_ED_OR_RETURN.
edje_edit_group_add()
EAPI Eina_Bool edje_edit_group_add (Evas_Object * obj, const char * name)
Create a new empty group in the given edje.
If a group with the same name exist none is created.
Parameters
obj Object being edited.
name Name of the new group.
Returns
EINA_TRUE if successfully added the group, EINA_FALSE if an error occurred or if a group with the same name exists.
Add an edje (empty) group to an edje object's group set.
Parameters
obj The pointer to edje object.
name The name of the group.
Returns
1 If it could allocate memory to the part group added or zero if not.
This function adds, at run time, one more group, which will reside in memory, to the group set found in the .edj file which obj was loaded with. This group can be manipulated by other API functions, like edje_edit_part_add(), for example. If desired, the new group can be actually committed the respective .edj by use of edje_edit_save().
References _Edje_File::collection, _Edje::file, GET_ED_OR_RETURN, and name.
edje_edit_group_data_add()
EAPI Eina_Bool edje_edit_group_data_add (Evas_Object * obj, const char * itemname, const char * value)
Create a new data object in the given edje file belonging to the current group.
If another data entry with the same name exists, nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
itemname Name for the new data entry.
value Value for the new data entry.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, GET_ED_OR_RETURN, and _Edje_String::str.
edje_edit_group_data_del()
EAPI Eina_Bool edje_edit_group_data_del (Evas_Object * obj, const char * itemname)
Delete the given data object from the group.
Parameters
obj Object being edited.
itemname Name of the data entry to remove.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_data_list_get()
EAPI Eina_List* edje_edit_group_data_list_get (Evas_Object * obj)
Retrieves a list with the item names inside the data block at the group level.
Parameters
obj Object being edited.
Returns
List of strings, each being a name entry in the data block for the group.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_data_name_set()
EAPI Eina_Bool edje_edit_group_data_name_set (Evas_Object * obj, const char * itemname, const char * newname)
Change the name of the given data object.
Parameters
obj Object being edited.
itemname Name of the data entry to rename.
newname New name for the data entry.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_data_value_get()
EAPI const char* edje_edit_group_data_value_get (Evas_Object * obj, const char * itemname)
Get the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry.
Returns
Value of the data entry or NULL if not found.
References _Edje::collection, _Edje_Part_Collection::data, edje_string_get(), _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_data_value_set()
EAPI Eina_Bool edje_edit_group_data_value_set (Evas_Object * obj, const char * itemname, const char * value)
Set the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry to set the value.
value Value to set for the data entry.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, _Edje_Part_Collection::data, _Edje::file, and GET_ED_OR_RETURN.
edje_edit_group_del()
EAPI Eina_Bool edje_edit_group_del (Evas_Object * obj, const char * group_name)
Delete the specified group from the given edje.
You can only delete a currently unused group. All the parts and the programs inside the group will be deleted as well, but not image or font embedded in the edje.
Parameters
obj Object being edited.
group_name Name of group to delete.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Delete the specified group from the edje file.
Parameters
obj The pointer to the edje object.
group_name Group to delete.
Returns
EINA_TRUE on success, EINA_FALSE on failure.
This function deletes the given group from the file obj is set to. This operation can't be undone as all references to the group are removed from the file. This function may fail if the group to be deleted is currently in use.
References _Edje_File::collection, _Edje::collection, EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED, EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST, EDJE_EDIT_ERROR_GROUP_REFERENCED, _Edje::file, GET_ED_OR_RETURN, _Edje::group, _Edje_Part_Collection_Directory_Entry::id, _Edje_Part_Collection::id, and _Edje_Part_Collection_Directory_Entry::ref.
edje_edit_group_exist()
EAPI Eina_Bool edje_edit_group_exist (Evas_Object * obj, const char * group)
Check if a group with the given name exist in the edje.
Parameters
obj Object being edited.
group Group name to check for.
Returns
EINA_TRUE if group exists, EINA_FALSE if not.
References _Edje_File::collection, _Edje::file, and GET_ED_OR_RETURN.
Referenced by edje_edit_group_name_set().
edje_edit_group_max_h_get()
EAPI int edje_edit_group_max_h_get (Evas_Object * obj)
Get the group maximum height.
Parameters
obj Object being edited.
Returns
The maximum height set for the group. -1 if an error occurred.
edje_edit_group_max_h_set()
EAPI void edje_edit_group_max_h_set (Evas_Object * obj, int h)
Set the group maximum height.
Parameters
obj Object being edited.
h New maximum height for the group.
edje_edit_group_max_w_get()
EAPI int edje_edit_group_max_w_get (Evas_Object * obj)
Get the group maximum width.
Parameters
obj Object being edited.
Returns
The maximum width set for the group. -1 if an error occurred.
edje_edit_group_max_w_set()
EAPI void edje_edit_group_max_w_set (Evas_Object * obj, int w)
Set the group maximum width.
Parameters
obj Object being edited.
w New maximum width for the group.
edje_edit_group_min_h_get()
EAPI int edje_edit_group_min_h_get (Evas_Object * obj)
Get the group minimum height.
Parameters
obj Object being edited.
Returns
The minimum height set for the group. -1 if an error occurred.
edje_edit_group_min_h_set()
EAPI void edje_edit_group_min_h_set (Evas_Object * obj, int h)
Set the group minimum height.
Parameters
obj Object being edited.
h New minimum height for the group.
edje_edit_group_min_w_get()
EAPI int edje_edit_group_min_w_get (Evas_Object * obj)
Get the group minimum width.
Parameters
obj Object being edited.
Returns
The minimum width set for the group. -1 if an error occurred.
edje_edit_group_min_w_set()
EAPI void edje_edit_group_min_w_set (Evas_Object * obj, int w)
Set the group minimum width.
Parameters
obj Object being edited.
w New minimum width for the group.
edje_edit_group_name_set()
EAPI Eina_Bool edje_edit_group_name_set (Evas_Object * obj, const char * new_name)
Set a new name for the current open group.
You can only rename a group that is currently loaded Note that the relative getter function don't exist as it doesn't make sense ;)
Parameters
obj Object being edited.
new_name New name for the group.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, edje_edit_group_exist(), GET_ED_OR_RETURN, and _Edje_Part_Collection::part.
edje_edit_image_add()
EAPI Eina_Bool edje_edit_image_add (Evas_Object * obj, const char * path)
Add an new image to the image collection.
This function add the given image inside the edje. Don't add a new image part but only put the image inside the edje file. It actually write directly to the file so you don't have to save. After you have to create a new image_part that use this image. Note that all the parts in the edje share the same image collection, thus you can/must use the same image for different part.
The format of the image files that can be loaded depend on the evas engine on your system
Parameters
obj Object being edited.
path The name of the image file to include in the edje.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::file, GET_ED_OR_RETURN, _Edje_File::image_dir, name, and _Edje::path.
edje_edit_image_compression_rate_get()
EAPI int edje_edit_image_compression_rate_get (Evas_Object * obj, const char * image)
Get compression rate for the given image.
Parameters
obj Object being edited.
image The name of the image.
Returns
The compression rate (if the imnage is EDJE_EDIT_IMAGE_COMP_LOSSY) or < 0, on errors.
References EDJE_IMAGE_SOURCE_TYPE_INLINE_LOSSY, _Edje_Image_Directory::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, _Edje::file, GET_ED_OR_RETURN, _Edje_File::image_dir, _Edje_Image_Directory_Entry::source_param, and _Edje_Image_Directory_Entry::source_type.
edje_edit_image_compression_type_get()
EAPI Edje_Edit_Image_Comp edje_edit_image_compression_type_get (Evas_Object * obj, const char * image)
Get compression type for the given image.
Parameters
obj Object being edited.
image The name of the image.
Returns
One of Image Compression types. (EDJE_EDIT_IMAGE_COMP_RAW, EDJE_EDIT_IMAGE_COMP_USER, EDJE_EDIT_IMAGE_COMP_COMP, EDJE_EDIT_IMAGE_COMP_LOSSY).
References EDJE_EDIT_IMAGE_COMP_COMP, EDJE_EDIT_IMAGE_COMP_LOSSY, EDJE_EDIT_IMAGE_COMP_RAW, EDJE_EDIT_IMAGE_COMP_USER, EDJE_IMAGE_SOURCE_TYPE_EXTERNAL, EDJE_IMAGE_SOURCE_TYPE_INLINE_LOSSY, EDJE_IMAGE_SOURCE_TYPE_INLINE_PERFECT, _Edje_Image_Directory::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, _Edje::file, GET_ED_OR_RETURN, _Edje_File::image_dir, _Edje_Image_Directory_Entry::source_param, and _Edje_Image_Directory_Entry::source_type.
edje_edit_image_data_add()
EAPI Eina_Bool edje_edit_image_data_add (Evas_Object * obj, const char * name, int id)
Add an image entry to the image collection.
This function adds the given image entry to the edje image collection. The image needs to be inside the eet already, with key name "images/id". After you have to create a new image_part that use this image, referring to it as "name". Note that all the parts in the edje share the same image collection, thus you can/must use the same image for different part.
Parameters
obj Object being edited.
name The image entry name.
id The image id.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::file, GET_ED_OR_RETURN, _Edje_File::image_dir, name, and _Edje::path.
edje_edit_image_del()
EAPI Eina_Bool edje_edit_image_del (Evas_Object * obj, const char * name)
Delete an image from the image collection.
It actually write directly to the file so you don't have to save.
Parameters
obj Object being edited.
name The name of the image file to include in the edje.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise (including the case when the name is not valid).
References _Edje_Image_Directory::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, ERR, _Edje::file, GET_ED_OR_RETURN, _Edje_Image_Directory_Entry::id, _Edje_File::image_dir, name, and _Edje::path.
edje_edit_image_id_get()
EAPI int edje_edit_image_id_get (Evas_Object * obj, const char * image_name)
Get image id for a given image name.
Parameters
obj Object being edited.
image_name The image name.
Returns
The id of the given image name.
References GET_EED_OR_RETURN.
edje_edit_images_list_get()
EAPI Eina_List* edje_edit_images_list_get (Evas_Object * obj)
Get the list of all the images in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A List containing all images names found in the edje file.
References _Edje_Image_Directory::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, _Edje::file, GET_ED_OR_RETURN, and _Edje_File::image_dir.
edje_edit_object_add()
EAPI Evas_Object* edje_edit_object_add (Evas * e)
Adds an editable Edje object to the canvas.
An Edje_Edit object is, for the most part, a standard Edje object. Only difference is you can use the Edje_Edit API on them.
Parameters
e Evas canvas where to add the object.
Returns
An Evas_Object of type Edje_Edit, or NULL if an error occurred.
References EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST.
edje_edit_part_above_get()
EAPI const char* edje_edit_part_above_get (Evas_Object * obj, const char * part)
Get the name of part stacked above the one passed.
Parameters
obj Object being edited.
part Name of part of which to check the one above.
Returns
Name of the part above. NULL if an error occurred or if part is the topmost part in the group.
References GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_add()
EAPI Eina_Bool edje_edit_part_add (Evas_Object * obj, const char * name, Edje_Part_Type type)
Create a new part in the given edje.
If another part with the same name just exists nothing is created and EINA_FALSE is returned. Note that this function also create a default description for the part.
Parameters
obj Object being edited.
name Name for the new part.
type Type of the new part. See Edje Data Collection reference for more info on this.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References EDJE_PART_TYPE_EXTERNAL, and type.
edje_edit_part_api_description_get()
EAPI const char* edje_edit_part_api_description_get (Evas_Object * obj, const char * part)
Get api's description of a part.
Parameters
obj Object being edited.
part Name of the part.
Returns
description of the api if successful, NULL otherwise.
edje_edit_part_api_description_set()
EAPI Eina_Bool edje_edit_part_api_description_set (Evas_Object * obj, const char * part, const char * description)
Set api's description of a part.
Parameters
obj Object being edited.
part Name of part.
description New description for the api property.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_part_api_name_get()
EAPI const char* edje_edit_part_api_name_get (Evas_Object * obj, const char * part)
Get api's name of a part.
Parameters
obj Object being edited.
part Name of the part.
Returns
name of the api if successful, NULL otherwise.
edje_edit_part_api_name_set()
EAPI Eina_Bool edje_edit_part_api_name_set (Evas_Object * obj, const char * part, const char * name)
Set api's name of a part.
Parameters
obj Object being edited.
part Name of the part.
name New name for the api property.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_part_below_get()
EAPI const char* edje_edit_part_below_get (Evas_Object * obj, const char * part)
Get the name of part stacked below the one passed.
Parameters
obj Object being edited.
part Name of part of which to check the one below.
Returns
Name of the part below. NULL if an error occurred or if part is the bottommost part in the group.
References GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_clip_to_get()
EAPI const char* edje_edit_part_clip_to_get (Evas_Object * obj, const char * part)
Get the clip_to part.
Parameters
obj Object being edited.
part Name of the part whose clipper to get.
Returns
Name of the part part is clipped to. NULL is returned on errors and if the part don't have a clip.
References _Edje_Part::clip_to_id, GET_RP_OR_RETURN, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_clip_to_set()
EAPI Eina_Bool edje_edit_part_clip_to_set (Evas_Object * obj, const char * part, const char * clip_to)
Set a part to clip part to.
Parameters
obj Object being edited.
part Part to set the clipper to.
clip_to Part to use as clipper, if NULL then the clipping value will be cancelled (unset clipping).
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_real_part_get(), _Edje::base, _Edje_Real_Part::clip_to, _Edje_Part::clip_to_id, edje_object_calc_force(), GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Real_Part::swallowed_object.
edje_edit_part_del()
EAPI Eina_Bool edje_edit_part_del (Evas_Object * obj, const char * part)
Delete the given part from the edje.
All the reference to this part will be zeroed.
Parameters
obj Object being edited.
part Name of part to delete.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::base, _Edje_Real_Part::clip_to, _Edje_Real_Part_Drag::confine_to, _Edje_Real_Part::custom, _Edje_Real_Part::drag, GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Real_Part::object, _Edje_Real_Part::param1, _Edje_Real_Part::param2, _Edje_Real_Part::part, _Edje_Real_Part_State::rel1_to_x, _Edje_Real_Part_State::rel1_to_y, _Edje_Real_Part_State::rel2_to_x, _Edje_Real_Part_State::rel2_to_y, _Edje::table_parts, _Edje::table_parts_size, and _Edje_Real_Part::text.
edje_edit_part_drag_confine_get()
EAPI const char* edje_edit_part_drag_confine_get (Evas_Object * obj, const char * part)
Get the name of the part that is used as 'confine' for the given draggies.
Parameters
obj Object being edited.
part Part to get the name that is used as 'confine' for the given draggies.
Returns
The name of the confine part or NULL (if unset).
edje_edit_part_drag_confine_set()
EAPI void edje_edit_part_drag_confine_set (Evas_Object * obj, const char * part, const char * confine)
Set the name of the part that is used as 'confine' for the given draggies.
Parameters
obj Object being edited.
part Part to set the name that is used as 'confine' for the given draggies.
confine The name of the confine part or NULL to unset confine.
edje_edit_part_drag_count_x_get()
EAPI int edje_edit_part_drag_count_x_get (Evas_Object * obj, const char * part)
Get horizontal dragable count for part.
Parameters
obj Object being edited.
part Part to get the drag horizontal count value.
edje_edit_part_drag_count_x_set()
EAPI void edje_edit_part_drag_count_x_set (Evas_Object * obj, const char * part, int count)
Set horizontal dragable count for part.
Parameters
obj Object being edited.
part Part to set the drag horizontal count value.
count The count value.
edje_edit_part_drag_count_y_get()
EAPI int edje_edit_part_drag_count_y_get (Evas_Object * obj, const char * part)
Get vertical dragable count for part.
Parameters
obj Object being edited.
part Part to get the drag vertical count value.
edje_edit_part_drag_count_y_set()
EAPI void edje_edit_part_drag_count_y_set (Evas_Object * obj, const char * part, int count)
Set vertical dragable count for part.
Parameters
obj Object being edited.
part Part to set the drag vertical count value.
count The count value.
edje_edit_part_drag_event_get()
EAPI const char* edje_edit_part_drag_event_get (Evas_Object * obj, const char * part)
Get the name of the part that is used as the receiver of the drag event.
Parameters
obj Object being edited.
part Part to get the name that is used as the receiver of the drag event.
Returns
The name of the part that will receive events, or NULL (if unset).
edje_edit_part_drag_event_set()
EAPI void edje_edit_part_drag_event_set (Evas_Object * obj, const char * part, const char * event)
Set the name of the part that will receive events from the given draggies.
Parameters
obj Object being edited.
part Part to set the name that will receive events from the given draggies.
event The name of the part that will receive events, or NULL to unset.
edje_edit_part_drag_step_x_get()
EAPI int edje_edit_part_drag_step_x_get (Evas_Object * obj, const char * part)
Get horizontal dragable step for part.
Parameters
obj Object being edited.
part Part to get the drag horizontal step value.
Returns
The step value.
edje_edit_part_drag_step_x_set()
EAPI void edje_edit_part_drag_step_x_set (Evas_Object * obj, const char * part, int step)
Set horizontal dragable state for part.
Parameters
obj Object being edited.
part Part to set the drag horizontal step value.
step The step the will be dragged.
edje_edit_part_drag_step_y_get()
EAPI int edje_edit_part_drag_step_y_get (Evas_Object * obj, const char * part)
Get vertical dragable step for part.
Parameters
obj Object being edited.
part Part to get the drag vertical step value.
Returns
The step value.
edje_edit_part_drag_step_y_set()
EAPI void edje_edit_part_drag_step_y_set (Evas_Object * obj, const char * part, int step)
Set vertical dragable state for part.
Parameters
obj Object being edited.
part Part to set the drag vertical step value.
step The step the will be dragged.
edje_edit_part_drag_x_get()
EAPI int edje_edit_part_drag_x_get (Evas_Object * obj, const char * part)
Get horizontal dragable state for part.
Parameters
obj Object being edited.
part Part to get if can be dragged horizontally;
Returns
1 (or -1) if the part can be dragged horizontally, 0 otherwise.
References _Edje_Part::dragable, GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part_Dragable::x.
edje_edit_part_drag_x_set()
EAPI void edje_edit_part_drag_x_set (Evas_Object * obj, const char * part, int drag)
Set horizontal dragable state for part.
Parameters
obj Object being edited.
part Part to set if should be dragged horizontally.
drag 1 (or -1) if the part should be dragged horizontally, 0 otherwise.
References _Edje_Real_Part::drag, _Edje_Part::dragable, GET_RP_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Dragable::x, and _Edje_Part_Dragable::y.
edje_edit_part_drag_y_get()
EAPI int edje_edit_part_drag_y_get (Evas_Object * obj, const char * part)
Get vertical dragable state for part.
Parameters
obj Object being edited.
part Part to get if can be dragged vertically.
Returns
1 (or - 1) if the part can be dragged vertically, 0 otherwise.
References _Edje_Part::dragable, GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part_Dragable::y.
edje_edit_part_drag_y_set()
EAPI void edje_edit_part_drag_y_set (Evas_Object * obj, const char * part, int drag)
Set vertical dragable state for part.
Parameters
obj Object being edited.
part Part to set if should be dragged vertically.
drag 1 (or -1) of the part shpuld be dragged vertically, 0 otherwise.
References _Edje_Real_Part::drag, _Edje_Part::dragable, GET_RP_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Dragable::x, and _Edje_Part_Dragable::y.
edje_edit_part_effect_get()
EAPI Edje_Text_Effect edje_edit_part_effect_get (Evas_Object * obj, const char * part)
Get the effect for a given part.
Gets the effect used for parts of type TEXT. See Edje Data Collection reference for more details.
Parameters
obj Object being edited.
part Part to get the effect of.
Returns
The effect set for the part.
References _Edje_Part::effect, GET_RP_OR_RETURN, and _Edje_Real_Part::part.
edje_edit_part_effect_set()
EAPI void edje_edit_part_effect_set (Evas_Object * obj, const char * part, Edje_Text_Effect effect)
Set the effect for a given part.
Parameters
obj Object being edited.
part Part to set the effect to. Only makes sense on type TEXT.
effect Effect to set for the part.
References edje_object_calc_force(), _Edje_Part::effect, GET_RP_OR_RETURN, and _Edje_Real_Part::part.
edje_edit_part_exist()
EAPI Eina_Bool edje_edit_part_exist (Evas_Object * obj, const char * part)
Check if a part with the given name exist in the edje object.
Parameters
obj Object being edited.
part Name of part to check for its existence.
Returns
EINA_TRUE if the part exists, EINA_FALSE if not.
References GET_RP_OR_RETURN.
edje_edit_part_external_add()
EAPI Eina_Bool edje_edit_part_external_add (Evas_Object * obj, const char * name, const char * source)
Create a new part of type EXTERNAL in the given edje.
If another part with the same name just exists nothing is created and EINA_FALSE is returned. Note that this function also create a default description for the part.
Parameters
obj Object being edited.
name Name for the new part.
source The registered external type to use for this part.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_part_ignore_flags_get()
EAPI Evas_Event_Flags edje_edit_part_ignore_flags_get (Evas_Object * obj, const char * part)
Get ignore_flags for part.
Parameters
obj Object being edited.
part Part to get which event_flags are being ignored.
Returns
The Event flags set to the part.
References GET_RP_OR_RETURN, _Edje_Part::ignore_flags, and _Edje_Real_Part::part.
edje_edit_part_ignore_flags_set()
EAPI void edje_edit_part_ignore_flags_set (Evas_Object * obj, const char * part, Evas_Event_Flags ignore_flags)
Set ignore_flags for part.
Parameters
obj Object being edited.
part Part to set which event flags will be ignored.
ignore_flags The Event flags to be ignored by the part.
References GET_RP_OR_RETURN, _Edje_Part::ignore_flags, _Edje_Real_Part::object, and _Edje_Real_Part::part.
edje_edit_part_mouse_events_get()
EAPI Eina_Bool edje_edit_part_mouse_events_get (Evas_Object * obj, const char * part)
Get mouse_events for part.
Parameters
obj Object being edited.
part Part to get if the mouse events is accepted.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_RP_OR_RETURN, _Edje_Part::mouse_events, and _Edje_Real_Part::part.
edje_edit_part_mouse_events_set()
EAPI void edje_edit_part_mouse_events_set (Evas_Object * obj, const char * part, Eina_Bool mouse_events)
Set mouse_events for part.
Parameters
obj Object being edited.
part The part to set if the mouse events is accepted.
mouse_events EINA_TRUE if part will accept mouse events, EINA_FALSE otherwise.
References _edje_callbacks_add(), _edje_callbacks_del(), GET_RP_OR_RETURN, _Edje_Part::mouse_events, _Edje_Real_Part::object, and _Edje_Real_Part::part.
edje_edit_part_name_set()
EAPI Eina_Bool edje_edit_part_name_set (Evas_Object * obj, const char * part, const char * new_name)
Set a new name for part.
Note that the relative getter function don't exist as it don't make sense ;)
Parameters
obj Object being edited.
part Name of part to rename.
new_name New name for the given part.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_real_part_get(), and GET_RP_OR_RETURN.
edje_edit_part_repeat_events_get()
EAPI Eina_Bool edje_edit_part_repeat_events_get (Evas_Object * obj, const char * part)
Get repeat_events for part.
Parameters
obj Object being edited.
part Part to set if will pass all events to the other parts.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::repeat_events.
edje_edit_part_repeat_events_set()
EAPI void edje_edit_part_repeat_events_set (Evas_Object * obj, const char * part, Eina_Bool repeat_events)
Set repeat_events for part.
Parameters
obj Object being edited.
part Part to set if will repeat all the received mouse events to other parts.
repeat_events EINA_TRUE if the events received will propagate to other parts, EINA_FALSE otherwise
References GET_RP_OR_RETURN, _Edje_Real_Part::object, _Edje_Real_Part::part, and _Edje_Part::repeat_events.
edje_edit_part_restack_above()
EAPI Eina_Bool edje_edit_part_restack_above (Evas_Object * obj, const char * part)
Move the given part above the next one.
Parameters
obj Object being edited.
part Name of part to move one step above.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Real_Part::part, _Edje_Part_Collection::parts, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_restack_below()
EAPI Eina_Bool edje_edit_part_restack_below (Evas_Object * obj, const char * part)
Move the given part below the previous one.
Parameters
obj Object being edited.
part Name of part to move one step below.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje::collection, GET_RP_OR_RETURN, _Edje_Part::id, _Edje_Real_Part::part, _Edje_Part_Collection::parts, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_part_scale_get()
EAPI Eina_Bool edje_edit_part_scale_get (Evas_Object * obj, const char * part)
Get scale for the part.
Parameters
obj Object being edited.
part Part to get the scale value of.
Returns
Whether scale is on (EINA_TRUE) or not.
References GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::scale.
edje_edit_part_scale_set()
EAPI void edje_edit_part_scale_set (Evas_Object * obj, const char * part, Eina_Bool scale)
Set scale property for the part.
This property tells Edje that the given part should be scaled by the Edje scale factor.
Parameters
obj Object being edited.
part Part to set scale for.
scale Scale value to set.
References edje_object_calc_force(), GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::scale.
edje_edit_part_selected_state_get()
EAPI const char* edje_edit_part_selected_state_get (Evas_Object * obj, const char * part, double * value)
Get the current selected state in part.
Parameters
obj Object being edited.
part Part to get the selected state of.
value Pointer to a double where the value of the state will be stored.
Returns
The name of the currently selected state for the part.
References _Edje_Real_Part::chosen_description, GET_RP_OR_RETURN, _Edje_Part_Description_Common::name, _Edje_Part_Description_Common::state, and _Edje_Part_Description_Common::value.
edje_edit_part_selected_state_set()
EAPI Eina_Bool edje_edit_part_selected_state_set (Evas_Object * obj, const char * part, const char * state, double value)
Set the current state in part.
Parameters
obj Object being edited.
part Part to set the state of.
state Name of the state to set.
value Value of the state.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_RP_OR_RETURN.
edje_edit_part_source_get()
EAPI const char* edje_edit_part_source_get (Evas_Object * obj, const char * part)
Get the source of part.
The meaning of this parameter varies depending on the type of the part. For GROUP parts, it's the name of another group in the Edje file which will be autoloaded and swallowed on this part. For TEXTBLOCK parts, it's the name of a group to be used for selection display under the text. For EXTERNAL parts, it's the name of the registered external widget to load and swallow on this part.
Parameters
obj Object being edited.
part Part to get the source from.
Returns
Content of the source parameter or NULL if nothing set or an error occurred.
References GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::source.
edje_edit_part_source_set()
EAPI Eina_Bool edje_edit_part_source_set (Evas_Object * obj, const char * part, const char * source)
Set the source of part.
Parameters
obj Object being edited.
part Part to set the source of.
source Value for the source parameter.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
See also
edje_edit_part_source_get()
Note
You can't change the source for EXTERNAL parts, it's akin to changing the type of the part.
NOTE: This is not applied now. You must reload the edje to see the change.
References EDJE_PART_TYPE_EXTERNAL, GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_part_states_list_get()
EAPI Eina_List* edje_edit_part_states_list_get (Evas_Object * obj, const char * part)
Get the list of all the states in the given part.
Parameters
obj Object being edited.
part Part to get the states names list.
Returns
An Eina_List* of string (char *)containing all the states names found in part, including the float value (ex: "default 0.00").
Use edje_edit_string_list_free() when you don't need it anymore.
References _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, GET_RP_OR_RETURN, _Edje_Part_Description_Common::name, _Edje_Part::other, _Edje_Real_Part::part, _Edje_Part_Description_Common::state, and _Edje_Part_Description_Common::value.
edje_edit_part_type_get()
EAPI Edje_Part_Type edje_edit_part_type_get (Evas_Object * obj, const char * part)
Get the type of a part.
Parameters
obj Object being edited.
part Name of part to get the type of.
Returns
Type of the part. See Edje Data Collection reference for details.
References GET_RP_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_parts_list_get()
EAPI Eina_List* edje_edit_parts_list_get (Evas_Object * obj)
Get the list of all the parts in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being the name for a part in the open group.
References GET_ED_OR_RETURN, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
edje_edit_print_internal_status()
EAPI void edje_edit_print_internal_status (Evas_Object * obj)
Print on standard output many information about the internal status of the edje object.
This is probably only useful to debug.
Parameters
obj Object being edited.
References GET_EED_OR_RETURN.
edje_edit_program_action_get()
EAPI Edje_Action_Type edje_edit_program_action_get (Evas_Object * obj, const char * prog)
Get the action of a given program.
Parameters
obj Object being edited.
prog The name of the program to get the action.
Returns
The action type, or -1 on errors. Action can be one of EDJE_ACTION_TYPE_NONE, _STATE_SET, ACTION_STOP, SIGNAL_EMIT, DRAG_VAL_SET, _DRAG_VAL_STEP, _DRAG_VAL_PAGE, _SCRIPT
References _Edje_Program::action, and GET_EPR_OR_RETURN.
edje_edit_program_action_set()
EAPI Eina_Bool edje_edit_program_action_set (Evas_Object * obj, const char * prog, Edje_Action_Type action)
Set the action of a given program.
Action can be one of EDJE_ACTION_TYPE_NONE, _STATE_SET, ACTION_STOP, SIGNAL_EMIT, DRAG_VAL_SET, _DRAG_VAL_STEP, _DRAG_VAL_PAGE, _SCRIPT
Parameters
obj Object being edited.
prog The name of the program to set the action.
action The new action type.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_Program::action, EDJE_ACTION_TYPE_LAST, EDJE_ACTION_TYPE_SCRIPT, GET_EED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Program::id, and _Edje_Edit::program_scripts.
edje_edit_program_add()
EAPI Eina_Bool edje_edit_program_add (Evas_Object * obj, const char * name)
Add a new program to the edje file.
If a program with the same name just exist the function will fail.
Parameters
obj Object being edited.
name The name of the new program.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_program_after_add()
EAPI Eina_Bool edje_edit_program_after_add (Evas_Object * obj, const char * prog, const char * after)
Add a new program name to the list of 'afters' in the given program.
All the programs listed in 'afters' will be executed after program execution.
Parameters
obj Object being edited.
prog The name of the program that contains the list of afters
after The name of another program to add to the afters list
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN.
edje_edit_program_after_del()
EAPI Eina_Bool edje_edit_program_after_del (Evas_Object * obj, const char * prog, const char * after)
Delete the given program from the list of 'afters' of the program.
Parameters
obj Object being edited.
prog The name of the program from where to remove the after.
after The name of the program to remove from the list of afters.
Returns
EINA_TRUE is successful or not in the list, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN.
edje_edit_program_afters_clear()
EAPI Eina_Bool edje_edit_program_afters_clear (Evas_Object * obj, const char * prog)
Clear the 'afters' list of the given program.
Parameters
obj Object being edited.
prog The name of the program to clear the 'afters' list.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _Edje_Program::after, and GET_EPR_OR_RETURN.
edje_edit_program_afters_get()
EAPI Eina_List* edje_edit_program_afters_get (Evas_Object * obj, const char * prog)
Get the list of action that will be run after the give program.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
prog The name of the program to get the list of actions
Returns
A list with all program names. or NULL on error.
References _Edje_Program::after, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Program_After::id, _Edje_Program::name, _Edje::table_programs, and _Edje::table_programs_size.
edje_edit_program_api_description_get()
EAPI const char* edje_edit_program_api_description_get (Evas_Object * obj, const char * prog)
Get api's description of a program.
Parameters
obj Object being edited.
prog Name of program.
Returns
description of the api if successful, NULL otherwise.
References _Edje_Program::api, _Edje_Program::description, and GET_EPR_OR_RETURN.
edje_edit_program_api_description_set()
EAPI Eina_Bool edje_edit_program_api_description_set (Evas_Object * obj, const char * prog, const char * description)
Set api's description of a program.
Parameters
obj Object being edited.
prog Name of the program.
description New description for the api property.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_api_name_get()
EAPI const char* edje_edit_program_api_name_get (Evas_Object * obj, const char * prog)
Get api's name of a program.
Parameters
obj Object being edited.
prog Name of program.
Returns
name of the api if successful, NULL otherwise.
References _Edje_Program::api, GET_EPR_OR_RETURN, and _Edje_Program::name.
edje_edit_program_api_name_set()
EAPI Eina_Bool edje_edit_program_api_name_set (Evas_Object * obj, const char * prog, const char * name)
Set api's name of a program.
Parameters
obj Object being edited.
prog Name of the part.
name New name for the api property.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_del()
EAPI Eina_Bool edje_edit_program_del (Evas_Object * obj, const char * prog)
Remove the given program from the edje file.
Parameters
obj Object being edited.
prog The name of the program to remove.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_program_remove(), _Edje::collection, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Program::id, _Edje_Edit::program_scripts, _Edje::table_programs, and _Edje::table_programs_size.
edje_edit_program_exist()
EAPI Eina_Bool edje_edit_program_exist (Evas_Object * obj, const char * prog)
Check if a program with the given name exist in the edje object.
Parameters
obj Object being edited.
prog The prog of the program that will be searched.
Returns
EINA_TRUE if the program exist, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN.
edje_edit_program_filter_part_get()
EAPI const char* edje_edit_program_filter_part_get (Evas_Object * obj, const char * prog)
References _Edje_Program::filter, GET_EPR_OR_RETURN, and _Edje_Program::part.
edje_edit_program_filter_part_set()
EAPI Eina_Bool edje_edit_program_filter_part_set (Evas_Object * obj, const char * prog, const char * filter_part)
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_in_from_get()
EAPI double edje_edit_program_in_from_get (Evas_Object * obj, const char * prog)
Get in.from of a given program.
Parameters
obj Object being edited.
prog The name of the program to get the delay.
Returns
The delay.
References _Edje_Program::from, GET_EPR_OR_RETURN, and _Edje_Program::in.
edje_edit_program_in_from_set()
EAPI Eina_Bool edje_edit_program_in_from_set (Evas_Object * obj, const char * prog, double seconds)
Set in.from of a given program.
Parameters
obj Object being edited.
prog The name of the program to set the delay.
seconds Number of seconds to delay the program execution
References _Edje_Program::from, GET_EPR_OR_RETURN, and _Edje_Program::in.
edje_edit_program_in_range_get()
EAPI double edje_edit_program_in_range_get (Evas_Object * obj, const char * prog)
Get in.range of a given program.
Parameters
obj Object being edited.
prog The name of the program to get random delay.
Returns
The delay random.
References GET_EPR_OR_RETURN, _Edje_Program::in, and _Edje_Program::range.
edje_edit_program_in_range_set()
EAPI Eina_Bool edje_edit_program_in_range_set (Evas_Object * obj, const char * prog, double seconds)
Set in.range of a given program.
Parameters
obj Object being edited.
prog The name of the program to set random delay.
seconds Max random number of seconds to delay.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN, _Edje_Program::in, and _Edje_Program::range.
edje_edit_program_name_set()
EAPI Eina_Bool edje_edit_program_name_set (Evas_Object * obj, const char * prog, const char * new_name)
Set a new name for the given program.
Parameters
obj Object being edited.
prog The current program name.
new_name The new name to assign.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_run()
EAPI Eina_Bool edje_edit_program_run (Evas_Object * obj, const char * prog)
Run the given program.
Parameters
obj Object being edited.
prog The name of the program to execute.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_program_run(), GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_signal_get()
EAPI const char* edje_edit_program_signal_get (Evas_Object * obj, const char * prog)
Get signal of a given program.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
prog The name of the program to get the signal.
Returns
The signal value for program.
References GET_EPR_OR_RETURN, and _Edje_Program::signal.
edje_edit_program_signal_set()
EAPI Eina_Bool edje_edit_program_signal_set (Evas_Object * obj, const char * prog, const char * signal)
Set signal of the given program.
Parameters
obj Object being edited.
prog The name of the program to set the signal.
signal The new signal value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_program_remove(), _Edje::collection, GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_source_get()
EAPI const char* edje_edit_program_source_get (Evas_Object * obj, const char * prog)
Get source of a given program.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
prog The name of the program to get source.
Returns
The source value por program.
References GET_EPR_OR_RETURN, and _Edje_Program::source.
edje_edit_program_source_set()
EAPI Eina_Bool edje_edit_program_source_set (Evas_Object * obj, const char * prog, const char * source)
Set source of the given program.
Parameters
obj Object being edited.
prog The name of the program to set source.
source The new source value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_program_remove(), _Edje::collection, GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_state2_get()
EAPI const char* edje_edit_program_state2_get (Evas_Object * obj, const char * prog)
Get the state2 for the given program.
In a STATE_SET action is not used In a SIGNAL_EMIT action is the source of the emitted signal.
Parameters
obj Object being edited.
prog The name of the program to get the state2.
Returns
The source to emit for the program.
References GET_EPR_OR_RETURN, and _Edje_Program::state2.
edje_edit_program_state2_set()
EAPI Eina_Bool edje_edit_program_state2_set (Evas_Object * obj, const char * prog, const char * state2)
Set the state2 for the given program.
In a STATE_SET action is not used In a SIGNAL_EMIT action is the source of the emitted signal.
Parameters
obj Object being edited.
prog The name of the program to set the state2.
state2 The name of the state to set.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_state_get()
EAPI const char* edje_edit_program_state_get (Evas_Object * obj, const char * prog)
Get the state for the given program.
In a STATE_SET action this is the name of state to set. In a SIGNAL_EMIT action is the name of the signal to emit.
Parameters
obj Object being edited.
prog The name of the program to get the state.
Returns
The name of the state.
References GET_EPR_OR_RETURN, and _Edje_Program::state.
edje_edit_program_state_set()
EAPI Eina_Bool edje_edit_program_state_set (Evas_Object * obj, const char * prog, const char * state)
Set the state for the given program.
In a STATE_SET action this is the name of state to set. In a SIGNAL_EMIT action is the name of the signal to emit.
Parameters
obj Object being edited.
prog The name of the program to set a state.
state The nameo of the state to set (not including the state value)
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN, and GET_EPR_OR_RETURN.
edje_edit_program_target_add()
EAPI Eina_Bool edje_edit_program_target_add (Evas_Object * obj, const char * prog, const char * target)
Add a new target program to the list of 'targets' in the given program.
If program action is EDJE_ACTION_TYPE_ACTION_STOP, then 'target' must be an existing program name. If it's EDJE_ACTION_TYPE_STATE_SET, then 'target' must be an existing part name.
Parameters
obj Object being edited.
prog The name of the program to add a new target.
target The name of the new target itself.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_real_part_get(), _Edje_Program::action, EDJE_ACTION_TYPE_ACTION_STOP, EDJE_ACTION_TYPE_STATE_SET, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Part::id, and _Edje_Real_Part::part.
edje_edit_program_target_del()
EAPI Eina_Bool edje_edit_program_target_del (Evas_Object * obj, const char * prog, const char * target)
Deletes a target from the list of 'targets' in the given program.
If program action is EDJE_ACTION_TYPE_ACTION_STOP then 'target' must be an existing program name. If action is EDJE_ACTION_TYPE_STATE_SET then 'target' must be an existing part name.
Parameters
obj Object being edited.
prog The name of the program to del a target from the list of targets.
target The name of another program or another part.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References _edje_real_part_get(), _Edje_Program::action, EDJE_ACTION_TYPE_ACTION_STOP, EDJE_ACTION_TYPE_STATE_SET, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Part::id, and _Edje_Real_Part::part.
edje_edit_program_targets_clear()
EAPI Eina_Bool edje_edit_program_targets_clear (Evas_Object * obj, const char * prog)
Clear the 'targets' list of the given program.
Parameters
obj Object being edited.
prog The name of the program to cleaar the 'targets' list.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN, and _Edje_Program::targets.
edje_edit_program_targets_get()
EAPI Eina_List* edje_edit_program_targets_get (Evas_Object * obj, const char * prog)
Get the list of the targets for the given program.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
prog The name of the progrem to get the list of the targets.
Returns
A list with all the targets names, or NULL on error.
References _Edje_Program::action, EDJE_ACTION_TYPE_ACTION_STOP, EDJE_ACTION_TYPE_STATE_SET, GET_ED_OR_RETURN, GET_EPR_OR_RETURN, _Edje_Program_Target::id, _Edje_Program::name, _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, _Edje::table_parts_size, _Edje::table_programs, _Edje::table_programs_size, and _Edje_Program::targets.
edje_edit_program_transition_get()
EAPI Edje_Tween_Mode edje_edit_program_transition_get (Evas_Object * obj, const char * prog)
Get the type of transition to use when apply animations.
Can be one of: EDJE_TWEEN_MODE_NONE, EDJE_TWEEN_MODE_LINEAR, EDJE_TWEEN_MODE_SINUSOIDAL, EDJE_TWEEN_MODE_ACCELERATE or EDJE_TWEEN_MODE_DECELERATE.
Parameters
obj Object being edited.
prog The name of the program to get the transition.
Returns
The type of transition used by program.
References GET_EPR_OR_RETURN, _Edje_Program::mode, and _Edje_Program::tween.
edje_edit_program_transition_set()
EAPI Eina_Bool edje_edit_program_transition_set (Evas_Object * obj, const char * prog, Edje_Tween_Mode transition)
Set the type of transition to use when apply animations.
Can be one of: EDJE_TWEEN_MODE_NONE, EDJE_TWEEN_MODE_LINEAR, EDJE_TWEEN_MODE_SINUSOIDAL, EDJE_TWEEN_MODE_ACCELERATE or EDJE_TWEEN_MODE_DECELERATE.
Parameters
obj Object being edited.
prog The name of the program to set the transition.
transition The transition type to set
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN, _Edje_Program::mode, and _Edje_Program::tween.
edje_edit_program_transition_time_get()
EAPI double edje_edit_program_transition_time_get (Evas_Object * obj, const char * prog)
Get the duration of the transition in seconds.
Parameters
obj Object being edited.
prog The name of the program to get the transition time.
Returns
The duration of the transition.
References GET_EPR_OR_RETURN, _Edje_Program::time, TO_DOUBLE, and _Edje_Program::tween.
edje_edit_program_transition_time_set()
EAPI Eina_Bool edje_edit_program_transition_time_set (Evas_Object * obj, const char * prog, double seconds)
Set the duration of the transition in seconds.
Parameters
obj Object being edited.
prog The name of the program to set the transition time.
seconds The duration of the transition (in seconds).
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References FROM_DOUBLE, GET_EPR_OR_RETURN, _Edje_Program::time, and _Edje_Program::tween.
edje_edit_program_value2_get()
EAPI double edje_edit_program_value2_get (Evas_Object * obj, const char * prog)
Get the value of state2 for the given program.
Parameters
obj Object being edited.
prog The name of the program to get the state2 value.
Returns
The vale of the state2 for the program.
References GET_EPR_OR_RETURN, and _Edje_Program::value2.
edje_edit_program_value2_set()
EAPI Eina_Bool edje_edit_program_value2_set (Evas_Object * obj, const char * prog, double value)
Set the value2 of state for the given program.
This is used in DRAG_ACTION
Parameters
obj Object being edited.
prog The name of the program to set the state2 value.
value The value of the state2 to set.
References GET_EPR_OR_RETURN, and _Edje_Program::value2.
edje_edit_program_value_get()
EAPI double edje_edit_program_value_get (Evas_Object * obj, const char * prog)
Get the value of state for the given program.
In a STATE_SET action this is the value of state to set. Not used on SIGNAL_EMIT action.
Parameters
obj Object being edited.
prog The name of the program to get the value of state.
Returns
The value of state for the program.
References GET_EPR_OR_RETURN, and _Edje_Program::value.
edje_edit_program_value_set()
EAPI Eina_Bool edje_edit_program_value_set (Evas_Object * obj, const char * prog, double value)
Set the value of state for the given program.
In a STATE_SET action this is the value of state to set. Not used on SIGNAL_EMIT action.
Parameters
obj Object being edited.
prog The name of the program to set the value of state.
value The vale to set.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_EPR_OR_RETURN, and _Edje_Program::value.
edje_edit_programs_list_get()
EAPI Eina_List* edje_edit_programs_list_get (Evas_Object * obj)
Get the list of all the programs in the given edje object.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
Returns
A list containing all the program names.
References GET_ED_OR_RETURN, _Edje_Program::name, _Edje::table_programs, and _Edje::table_programs_size.
edje_edit_save()
EAPI Eina_Bool edje_edit_save (Evas_Object * obj)
Save the modified edje object back to his file.
Use this function when you are done with your editing, all the change made to the current loaded group will be saved back to the original file.
Note
Source for the whole file will be auto generated and will overwrite any previously stored source.
Parameters
obj Object to save back to the file it was loaded from.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Todo:
Add a way to check what the error actually was, the way Edje Load does.
References _edje_edit_internal_save().
edje_edit_save_all()
EAPI Eina_Bool edje_edit_save_all (Evas_Object * obj)
Saves every group back into the file.
Parameters
obj Object to save.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
See also
edje_edit_save()
References _edje_edit_internal_save().
edje_edit_script_compile()
EAPI Eina_Bool edje_edit_script_compile (Evas_Object * obj)
Compile the Embryo script for the given object.
If required, this function will process all script code for the group and build the bytecode, updating the running Embryo VM Program if the build is succesful.
Parameters
obj The object being edited
References GET_EED_OR_RETURN, and _Edje_Edit::script_need_recompile.
edje_edit_script_error_list_get()
EAPI const Eina_List* edje_edit_script_error_list_get (Evas_Object * obj)
Get the list of errors resulting from the last script build.
Get the list of errors that resulted from the last attempt to rebuild the Embryo script for the edited group. This will be a standard Eina_List with Edje_Edit_Script_Error pointers as its data. The user should not do anything else but read the contents of this list. These errors can be the output of the embryo compiler, or internal errors generated by Edje_Edit if the preprocessing of the scripts failed.
Parameters
obj The object being edited
Returns
A constant list of Edje_Edit_Script_Error, or NULL if there are none
References _Edje_Edit::errors, and GET_EED_OR_RETURN.
edje_edit_script_get()
EAPI char* edje_edit_script_get (Evas_Object * obj)
Get the Embryo script for the group of the given object.
Get the shared script for the group under edition. Shared script means the script {} block for the group, not counting what's in each program. It returns a malloc'd duplicate of the code, so users are free to modify the contents directly and they should remember to free() it when done. NULL will be returned if there's no script or an error occurred.
Parameters
obj Object being edited.
Returns
The shared script code for this group.
References _Edje::collection, _Edje_Edit::embryo_source, and GET_ED_OR_RETURN.
edje_edit_script_program_get()
EAPI char* edje_edit_script_program_get (Evas_Object * obj, const char * prog)
Get the Embryo script for the given program.
Get the script code for the given program. Like the group script, this function returns a duplicate of the code that the user can modify at will and must free when done using it. NULL will be returned if the program doesn't exist, doesn't have any script or is not of type script.
Parameters
obj Object being edited
prog Program name
Returns
The program script code
References _Edje_Program::action, _Program_Script::code, EDJE_ACTION_TYPE_SCRIPT, GET_EED_OR_RETURN, GET_EPR_OR_RETURN, and _Edje_Edit::program_scripts.
edje_edit_script_program_set()
EAPI void edje_edit_script_program_set (Evas_Object * obj, const char * prog, const char * code)
Set the Embryo script for the given program.
Set the Embryo source code for the program prog. It must be an existing program of type EDJE_ACTION_TYPE_SCRIPT, or the function will fail and do nothing. Note that changing the code itself will not update the running VM, you need to call edje_edit_script_compile for it to get updated.
Parameters
obj The object being edited
prog The program name.
code The Embryo source
References _Edje_Program::action, _Program_Script::code, _Program_Script::dirty, EDJE_ACTION_TYPE_SCRIPT, GET_EED_OR_RETURN, GET_EPR_OR_RETURN, _Program_Script::processed, and _Edje_Edit::program_scripts.
edje_edit_script_set()
EAPI void edje_edit_script_set (Evas_Object * obj, const char * code)
Set the code for the group script.
Set the Embryo source code for the shared script of the edited group. Note that changing the code itself will not update the running VM, you need to call edje_edit_script_compile for it to get updated.
Parameters
obj The object being edited
code The Embryo source
References _Edje_Edit::embryo_processed, _Edje_Edit::embryo_source, _Edje_Edit::embryo_source_dirty, and GET_EED_OR_RETURN.
edje_edit_spectra_add()
EAPI Eina_Bool edje_edit_spectra_add (Evas_Object * obj, const char * name)
Add a new spectra in the given edje object.
Parameters
obj Object being edited.
name The name of the spectra to include in the edje.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_spectra_del()
EAPI Eina_Bool edje_edit_spectra_del (Evas_Object * obj, const char * spectra)
Delete the given spectra from the edje object.
Parameters
obj Object being edited.
spectra The name of the spectra to delete.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_spectra_name_set()
EAPI Eina_Bool edje_edit_spectra_name_set (Evas_Object * obj, const char * spectra, const char * name)
Change the name of the given spectra.
Parameters
obj Object being edited.
spectra The name of the current spectra.
name The new name to assign.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_spectra_stop_color_get()
EAPI Eina_Bool edje_edit_spectra_stop_color_get (Evas_Object * obj, const char * spectra, int stop_number, int * r, int * g, int * b, int * a, int * d)
Get the colors of the given stop.
Parameters
obj Object being edited.
spectra The name of the spectra.
stop_number The number of the stop,
r Where to store the red color value,
g Where to store the green color value,
b Where to store the blue color value,
a Where to store the alpha color value,
d Where to store the delta stop value,
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_spectra_stop_color_set()
EAPI Eina_Bool edje_edit_spectra_stop_color_set (Evas_Object * obj, const char * spectra, int stop_number, int r, int g, int b, int a, int d)
Set the colors of the given stop.
Parameters
obj Object being edited.
spectra The name of the spectra.
stop_number The number of the stops,
r The red color value to set,
g The green color value to set,
b The blue color value to set,
a The alpha color value to set,
d The delta stop value to set,
edje_edit_spectra_stop_num_get()
EAPI int edje_edit_spectra_stop_num_get (Evas_Object * obj, const char * spectra)
Get the number of stops in the given spectra.
Parameters
obj Object being edited.
spectra The name of the spectra.
Returns
The number of stops (or 0 on errors).
edje_edit_spectra_stop_num_set()
EAPI Eina_Bool edje_edit_spectra_stop_num_set (Evas_Object * obj, const char * spectra, int num)
Set the number of stops in the given spectra.
Parameters
obj Object being edited.
spectra The name of the spectra.
num The number of stops you want
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_spectrum_list_get()
EAPI Eina_List* edje_edit_spectrum_list_get (Evas_Object * obj)
Get the list of all the spectrum in the given edje object.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
Returns
A list containing all the spectra names.
edje_edit_state_add()
EAPI Eina_Bool edje_edit_state_add (Evas_Object * obj, const char * part, const char * name, double value)
Create a new state to the give part.
Parameters
obj Object being edited.
part Part to set the name of the new state.
name Name for the new state (not including the state value).
value The state value.
Returns
EINA_TRUE if successfully, EINA_FALSE otherwise.
References edje_edit_state_exist(), GET_RP_OR_RETURN, and name.
edje_edit_state_align_x_get()
EAPI double edje_edit_state_align_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get horizontal align (not including the state value).
value The state value.
Returns
The horizontal align value for the given state
edje_edit_state_align_x_set()
EAPI void edje_edit_state_align_x_set (Evas_Object * obj, const char * part, const char * state, double value, double align)
Set the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get horizontal align (not including the state value).
value The state value.
align The new vertical align value.
edje_edit_state_align_y_get()
EAPI double edje_edit_state_align_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get horizontal align (not including the state value).
value The state value.
Returns
The vertical align value for the given state
edje_edit_state_align_y_set()
EAPI void edje_edit_state_align_y_set (Evas_Object * obj, const char * part, const char * state, double value, double align)
Set the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get vertical align (not including the state value).
value The state value.
align The new vertical align value.
edje_edit_state_aspect_max_get()
EAPI double edje_edit_state_aspect_max_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the maximum aspect value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get maximum aspect (not including the state value).
value The state value.
Returns
The maximum aspect
edje_edit_state_aspect_max_set()
EAPI void edje_edit_state_aspect_max_set (Evas_Object * obj, const char * part, const char * state, double value, double aspect)
Set the maximum aspect value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set maximum aspect (not including the state value).
value The state value.
aspect Maximum aspect value.
edje_edit_state_aspect_min_get()
EAPI double edje_edit_state_aspect_min_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the minimum aspect value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get minimum aspect (not including the state value).
value The state value.
Returns
The minimum aspect
edje_edit_state_aspect_min_set()
EAPI void edje_edit_state_aspect_min_set (Evas_Object * obj, const char * part, const char * state, double value, double aspect)
Set the minimum aspect value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set minimum aspect (not including the state value).
value The state value.
aspect Minimum aspect value.
edje_edit_state_aspect_pref_get()
EAPI unsigned char edje_edit_state_aspect_pref_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the aspect preference of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get aspect preference (not including the state value).
value The state value.
Returns
The aspect preference (0 = None, 1 = Vertical, 2 = Horizontal, 3 = Both)
References _Edje_Part_Description_Common::aspect, GET_PD_OR_RETURN, and _Edje_Aspect_Prefer::prefer.
edje_edit_state_aspect_pref_set()
EAPI void edje_edit_state_aspect_pref_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char pref)
Set the aspect preference of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set aspect preference (not including the state value).
value The state value.
pref The aspect preference to set (0 = None, 1 = Vertical, 2 = Horizontal, 3 = Both)
References _Edje_Part_Description_Common::aspect, GET_PD_OR_RETURN, and _Edje_Aspect_Prefer::prefer.
edje_edit_state_color2_get()
EAPI void edje_edit_state_color2_get (Evas_Object * obj, const char * part, const char * state, double value, int * r, int * g, int * b, int * a)
Get the color2 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color (not including the state value).
value The state value.
r A pointer to store the red value.
g A pointer to store the green value.
b A pointer to store the blue value.
a A pointer to store the alpha value.
edje_edit_state_color2_set()
EAPI void edje_edit_state_color2_set (Evas_Object * obj, const char * part, const char * state, double value, int r, int g, int b, int a)
Set the color2 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color (not including the state value).
value The state value.
r The red value of the color.
g The green value of the color.
b The blue value of the color.
a The alpha value of the color.
edje_edit_state_color3_get()
EAPI void edje_edit_state_color3_get (Evas_Object * obj, const char * part, const char * state, double value, int * r, int * g, int * b, int * a)
Get the color3 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color (not including the state value).
value The state value.
r A pointer to store the red value.
g A pointer to store the green value.
b A pointer to store the blue value.
a A pointer to store the alpha value.
References _Edje_Color::a, _Edje_Color::b, _Edje_Part_Description_Spec_Text::color3, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Color::g, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Color::r, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_color3_set()
EAPI void edje_edit_state_color3_set (Evas_Object * obj, const char * part, const char * state, double value, int r, int g, int b, int a)
Set the color3 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color (not including the state value).
value The state value.
r The red value of the color.
g The green value of the color.
b The blue value of the color.
a The alpha value of the color.
References _Edje_Color::a, _Edje_Color::b, _Edje_Part_Description_Spec_Text::color3, edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Color::g, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Color::r, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_color_class_get()
EAPI const char* edje_edit_state_color_class_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the color class of the given part state.
Remember to free the string with edje_edit_string_free()
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color class (not including the state value).
value The state value.
Returns
The current color class.
References _Edje_Part_Description_Common::color_class, and GET_PD_OR_RETURN.
edje_edit_state_color_class_set()
EAPI void edje_edit_state_color_class_set (Evas_Object * obj, const char * part, const char * state, double value, const char * color_class)
Set the color class of the given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color class (not including the state value).
value The state value.
color_class The color class to assign.
References GET_PD_OR_RETURN.
edje_edit_state_color_get()
EAPI void edje_edit_state_color_get (Evas_Object * obj, const char * part, const char * state, double value, int * r, int * g, int * b, int * a)
Get the color of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color (not including the state value).
value The state value.
r A pointer to store the red value.
g A pointer to store the green value.
b A pointer to store the blue value.
a A pointer to store the alpha value.
edje_edit_state_color_set()
EAPI void edje_edit_state_color_set (Evas_Object * obj, const char * part, const char * state, double value, int r, int g, int b, int a)
Set the color of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color (not including the state value).
value The state value.
r The red value of the color.
g The green value of the color.
b The blue value of the color.
a The alpha value of the color.
edje_edit_state_copy()
EAPI Eina_Bool edje_edit_state_copy (Evas_Object * obj, const char * part, const char * from, double val_from, const char * to, double val_to)
Copies the state from into to.
If to doesn't exist it will be created.
Parameters
obj Object being edited.
part Part that contain state.
from State to copy from (not including state value).
val_from The value of the state to copy from.
to State to copy into (not including state value).
val_to The value of the state to copy into.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_RP_OR_RETURN.
edje_edit_state_del()
EAPI Eina_Bool edje_edit_state_del (Evas_Object * obj, const char * part, const char * state, double value)
Delete the given part state from the edje.
Parameters
obj Object being edited.
part Part that contain state.
state The current name of the state (not including the state value).
value The state value.
Returns
EINA_TRUE if successfully, EINA_FALSE otherwise.
References edje_edit_state_exist(), and GET_RP_OR_RETURN.
edje_edit_state_exist()
EAPI Eina_Bool edje_edit_state_exist (Evas_Object * obj, const char * part, const char * state, double value)
Check if a part state with the given name exist.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to check (not including the state value).
value The state value.
Returns
EINA_TRUE if the part state exist, EINA_FALSE otherwise.
References GET_PD_OR_RETURN.
Referenced by edje_edit_state_add(), and edje_edit_state_del().
edje_edit_state_external_param_bool_get()
EAPI Eina_Bool edje_edit_state_external_param_bool_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Eina_Bool * val)
Get external parameter of type BOOL.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type BOOL (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::i, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_bool_set()
EAPI Eina_Bool edje_edit_state_external_param_bool_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Eina_Bool val)
Set external parameter of type BOOL.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type BOOL (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_BOOL.
edje_edit_state_external_param_choice_get()
EAPI Eina_Bool edje_edit_state_external_param_choice_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char ** val)
Get external parameter of type CHOICE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type CHOICE (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::s, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_choice_set()
EAPI Eina_Bool edje_edit_state_external_param_choice_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char * val)
Set external parameter of type CHOICE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type CHOICE (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_CHOICE.
edje_edit_state_external_param_double_get()
EAPI Eina_Bool edje_edit_state_external_param_double_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, double * val)
Get external parameter of type DOUBLE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type DOUBLE (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References _Edje_External_Param::d, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_double_set()
EAPI Eina_Bool edje_edit_state_external_param_double_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, double val)
Set external parameter of type DOUBLE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type DOUBLE (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_DOUBLE.
edje_edit_state_external_param_get()
EAPI Eina_Bool edje_edit_state_external_param_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Edje_External_Param_Type * type, void ** val)
Get the external parameter type and value.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter (not including the state value).
value The state value.
param The name of the paramter to look for.
type The type of the parameter will be stored here.
val Pointer to value will be stored here - DO NOT FREE IT!
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
References _Edje_External_Param::d, EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_EXTERNAL_PARAM_TYPE_STRING, EDJE_PART_TYPE_EXTERNAL, ERR, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::i, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::s, _Edje_External_Param::type, type, and _Edje_Part::type.
edje_edit_state_external_param_int_get()
EAPI Eina_Bool edje_edit_state_external_param_int_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, int * val)
Get external parameter of type INT.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type INT (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::i, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_int_set()
EAPI Eina_Bool edje_edit_state_external_param_int_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, int val)
Set external parameter of type INT.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type INT (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_INT.
edje_edit_state_external_param_set()
EAPI Eina_Bool edje_edit_state_external_param_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Edje_External_Param_Type type, ...)
Set the external parameter type and value, adding it if it didn't exist before.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter (not including the state value).
value The state value.
param The name of the paramter set.
type The type of the parameter.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise. Arguments should have proper sized values matching their types:
EDJE_EXTERNAL_PARAM_TYPE_INT: int
EDJE_EXTERNAL_PARAM_TYPE_BOOL: int
EDJE_EXTERNAL_PARAM_TYPE_DOUBLE: double
EDJE_EXTERNAL_PARAM_TYPE_STRING: char*
EDJE_EXTERNAL_PARAM_TYPE_CHOICE: char*
Note
: The validation of the parameter will occur only if the part is in the same state as the one being modified.
References EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::name, _Edje_Real_Part::part, type, and _Edje_Part::type.
Referenced by edje_edit_state_external_param_bool_set(), edje_edit_state_external_param_choice_set(), edje_edit_state_external_param_double_set(), edje_edit_state_external_param_int_set(), and edje_edit_state_external_param_string_set().
edje_edit_state_external_param_string_get()
EAPI Eina_Bool edje_edit_state_external_param_string_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char ** val)
Get external parameter of type STRING.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type STRING (not including the state value).
value The state value.
param The name of the paramter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_STRING, EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_External_Param::name, _Edje_Real_Part::part, _Edje_External_Param::s, _Edje_External_Param::type, and _Edje_Part::type.
edje_edit_state_external_param_string_set()
EAPI Eina_Bool edje_edit_state_external_param_string_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char * val)
Set external parameter of type STRING.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type STRING (not including the state value).
value The state value.
param The name of the paramter.
val Value will be stored here.
Returns
EINA_TRUE if it was set, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_STRING.
edje_edit_state_external_params_list_get()
EAPI const Eina_List* edje_edit_state_external_params_list_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the list of parameters for an external part.
DO NOT FREE THE LIST!
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get list of Edje_External_Param (not including the state value).
value The state value.
Returns
The list of Edje_External_Param.
References EDJE_PART_TYPE_EXTERNAL, _Edje_Part_Description_External::external_params, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_fill_origin_offset_x_get()
EAPI int edje_edit_state_fill_origin_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the fill horizontal origin offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill horizontal origin offset relative to area (not including the state value).
value The state value.
Returns
The fill horizontal origin offset relative to area.
edje_edit_state_fill_origin_offset_x_set()
EAPI void edje_edit_state_fill_origin_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the fill horizontal origin offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal origin offset relative to area (not including the state value).
value The state value.
x The fill horizontal origin offset value.
edje_edit_state_fill_origin_offset_y_get()
EAPI int edje_edit_state_fill_origin_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the fill vertical origin offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill vertical origin offset relative to area (not including the state value).
value The state value.
Returns
The fill vertical origin offset value.
edje_edit_state_fill_origin_offset_y_set()
EAPI void edje_edit_state_fill_origin_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Set the fill vertical origin offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill vertical origin offset relative to area (not including the state value).
value The state value.
y The fill vertical origin offset value.
edje_edit_state_fill_origin_relative_x_get()
EAPI double edje_edit_state_fill_origin_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the fill horizontal origin relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the fill horizontal origin relative to area (not including the state value).
value The state value.
Returns
The fill horizontal origin relative to area.
edje_edit_state_fill_origin_relative_x_set()
EAPI void edje_edit_state_fill_origin_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the fill horizontal origin relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal origin relative to area (not including the state value).
value The state value.
x The fill horizontal origin value.
edje_edit_state_fill_origin_relative_y_get()
EAPI double edje_edit_state_fill_origin_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the fill vertical origin relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill vertical origin relative to area (not including the state value).
value The state value.
Returns
The fill vertical origin relative to area.
edje_edit_state_fill_origin_relative_y_set()
EAPI void edje_edit_state_fill_origin_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Set the fill horizontal origin relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill vertical origin relative to area (not including the state value).
value The state value.
y The fill vertical origin value.
edje_edit_state_fill_size_offset_x_get()
EAPI int edje_edit_state_fill_size_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the fill horizontal size offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill horizontal size offset relative to area (not including the state value).
value The state value.
Returns
The fill horizontal size offset relative to area.
edje_edit_state_fill_size_offset_x_set()
EAPI void edje_edit_state_fill_size_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the fill horizontal size offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal size offset relative value (not including the state value).
value The state value.
x The horizontal size offset value.
edje_edit_state_fill_size_offset_y_get()
EAPI int edje_edit_state_fill_size_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the fill vertical size offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill vertical size offset relative to area (not including the state value).
value The state value.
Returns
The fill vertical size offset relative to area.
edje_edit_state_fill_size_offset_y_set()
EAPI void edje_edit_state_fill_size_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Set the fill vertical size offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill vertical size offset relative value (not including the state value).
value The state value.
y The vertical size offset value.
edje_edit_state_fill_size_relative_x_get()
EAPI double edje_edit_state_fill_size_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the fill horizontal size relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill horizontal size relative to area (not including the state value).
value The state value.
Returns
The fill horizontal size relative to area.
edje_edit_state_fill_size_relative_x_set()
EAPI void edje_edit_state_fill_size_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the fill horizontal size relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal size relative value (not including the state value).
value The state value.
x The horizontal size relative value.
edje_edit_state_fill_size_relative_y_get()
EAPI double edje_edit_state_fill_size_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the fill vertical size relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill vertical size relative to area (not including the state value).
value The state value.
Returns
The fill vertical size relative to area.
edje_edit_state_fill_size_relative_y_set()
EAPI void edje_edit_state_fill_size_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the fill vertical size relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill vertical size relative value (not including the state value).
value The state value.
x The vertical size relative value.
edje_edit_state_font_get()
EAPI const char* edje_edit_state_font_get (Evas_Object * obj, const char * part, const char * state, double value)
Get font name for a given part state.
Parameters
obj Object being edited.
part The name of the part to get the font of.
state The state of the part to get the font of.
value Value of the state.
Returns
Font used by the part or NULL if error or nothing is set.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the name of the font used (not including the state value).
value The state value.
Returns
The name of the font used in the given part state.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, edje_string_get(), _Edje_Part_Description_Spec_Text::font, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_font_set()
EAPI void edje_edit_state_font_set (Evas_Object * obj, const char * part, const char * state, double value, const char * font)
Set font name for a given part state.
Font name can be any alias of an internal font in the Edje file and, if it doesn't match any, Edje will look for a font with the given name in the system fonts.
Parameters
obj Object being edited.
part Part to set the font of.
state State in which the font is set.
value Value of the state.
font The font name to use.
obj Object being edited.
part Part that contain state.
state The name of the state to set the name of the font that will be used (not including the state value).
value The state value.
font The name of the font to use in the given part state.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_gradient_angle_get()
EAPI int edje_edit_state_gradient_angle_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the angle of the gradient.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get the angle (not including the state value).
value The state value.
Returns
The angle of the gradient.
edje_edit_state_gradient_angle_set()
EAPI void edje_edit_state_gradient_angle_set (Evas_Object * obj, const char * part, const char * state, double value, int angle)
Set the angle of the gradient.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set the angle (not including the state value).
value The state value.
angle The angle to set.
edje_edit_state_gradient_rel1_offset_x_get()
EAPI int edje_edit_state_gradient_rel1_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the gradient rel1 horizontal offset value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get rel1 offset x value (not including the state value).
value The state value.
Returns
The gradient rel1 horizontal offset value.
edje_edit_state_gradient_rel1_offset_x_set()
EAPI Eina_Bool edje_edit_state_gradient_rel1_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, int val)
Set the gradient rel1 horizontal offset value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set rel1 offset x value (not including the state value).
value The state value.
val The rel1 offset x value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_state_gradient_rel1_offset_y_get()
EAPI int edje_edit_state_gradient_rel1_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the gradient rel1 vertical offset value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get rel1 offset y value (not including the state value).
value The state value.
Returns
The gradient rel1 vertical offset value.
edje_edit_state_gradient_rel1_offset_y_set()
EAPI Eina_Bool edje_edit_state_gradient_rel1_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, int val)
Set the gradient rel1 vertical offset value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set rel1 offset y value (not including the state value).
value The state value.
val The rel1 offset y value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_state_gradient_rel1_relative_x_get()
EAPI double edje_edit_state_gradient_rel1_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the gradient rel1 horizontal relative value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get rel1 relative x value (not including the state value).
value The state value.
Returns
The gradient rel1 horizontal relative value.
edje_edit_state_gradient_rel1_relative_x_set()
EAPI Eina_Bool edje_edit_state_gradient_rel1_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double val)
Set the gradient rel1 horizontal relative value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set rel1 relative x value (not including the state value).
value The state value.
val The rel1 relative x to be set,
Returns
EINA_TRUE if successful, EINA_FALSE otherwise..
edje_edit_state_gradient_rel1_relative_y_get()
EAPI double edje_edit_state_gradient_rel1_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the gradient rel1 vertical relative value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get rel1 relative y value (not including the state value).
value The state value.
Returns
The gradient rel1 vertical relative value.
edje_edit_state_gradient_rel1_relative_y_set()
EAPI Eina_Bool edje_edit_state_gradient_rel1_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double val)
Set the gradient rel1 vertical relative value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set rel1 relative y value (not including the state value).
value The state value.
val The rel1 relative y to be set,
Returns
EINA_TRUE if successful, EINA_FALSE otherwise..
edje_edit_state_gradient_rel2_offset_x_get()
EAPI int edje_edit_state_gradient_rel2_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the gradient rel2 horizontal offset value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get rel2 offset x value (not including the state value).
value The state value.
Returns
The gradient rel2 horizontal offset value.
edje_edit_state_gradient_rel2_offset_x_set()
EAPI Eina_Bool edje_edit_state_gradient_rel2_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, int val)
Set the gradient rel2 horizontal offset value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set rel2 offset x value (not including the state value).
value The state value.
val The rel2 offset x value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_state_gradient_rel2_offset_y_get()
EAPI int edje_edit_state_gradient_rel2_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the gradient rel2 vertical offset value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get rel2 offset y value (not including the state value).
value The state value.
Returns
The gradient rel2 vertical offset value.
edje_edit_state_gradient_rel2_offset_y_set()
EAPI Eina_Bool edje_edit_state_gradient_rel2_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, int val)
Set the gradient rel2 vertical offset value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set rel2 offset y value (not including the state value).
value The state value.
val The rel2 offset y value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_state_gradient_rel2_relative_x_get()
EAPI double edje_edit_state_gradient_rel2_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the gradient rel2 horizontal relative value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get rel2 relative x value (not including the state value).
value The state value.
Returns
The gradient rel2 horizontal relative value.
edje_edit_state_gradient_rel2_relative_x_set()
EAPI Eina_Bool edje_edit_state_gradient_rel2_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double val)
Set the gradient rel2 horizontal relative value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set rel2 relative x value (not including the state value).
value The state value.
val The rel2 relative x to be set,
Returns
EINA_TRUE if successful, EINA_FALSE otherwise..
edje_edit_state_gradient_rel2_relative_y_get()
EAPI double edje_edit_state_gradient_rel2_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the gradient rel2 vertical relative value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get rel2 relative y value (not including the state value).
value The state value.
Returns
The gradient rel2 vertical relative value.
edje_edit_state_gradient_rel2_relative_y_set()
EAPI Eina_Bool edje_edit_state_gradient_rel2_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double val)
Set the gradient rel2 vertical relative value.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set rel2 relative y value (not including the state value).
value The state value.
val The rel2 relative y to be set,
Returns
EINA_TRUE if successful, EINA_FALSE otherwise..
edje_edit_state_gradient_spectra_get()
EAPI const char* edje_edit_state_gradient_spectra_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the spectra used by part state.
Remember to free the string with edje_edit_string_free().
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get the spectra name used (not including the state value).
value The state value.
Returns
The spectra name used in state.
edje_edit_state_gradient_spectra_set()
EAPI Eina_Bool edje_edit_state_gradient_spectra_set (Evas_Object * obj, const char * part, const char * state, double value, const char * spectra)
Set the spectra used by part state.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set the spectra (not including the state value).
value The state value.
spectra The spectra name to assign
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_state_gradient_type_get()
EAPI const char* edje_edit_state_gradient_type_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the type of gradient.
Remember to free the string with edje_edit_string_free().
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to get the gradient type (not including the state value).
value The state value.
Returns
The type of gradient used in state. (linear, linear.diag, linear.codiag, radial, rectangular, angular, sinosoidal)
edje_edit_state_gradient_type_set()
EAPI Eina_Bool edje_edit_state_gradient_type_set (Evas_Object * obj, const char * part, const char * state, double value, const char * type)
Set the type of gradient.
Gradient type can be on of the following: linear, linear.diag, linear.codiag, radial, rectangular, angular, sinusoidal
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set the gradient type (not including the state value).
value The state value.
type The type of gradient to use.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_state_gradient_use_fill_get()
EAPI Eina_Bool edje_edit_state_gradient_use_fill_get (Evas_Object * obj, const char * part, const char * state, double value)
Get if the current gradient use the fill properties or the gradient_rel as params.
Parameters
obj Object being edited.
part The part that contain state.
state The name of the state to set the gradient type (not including the state value).
value The state value.
Returns
EINA_TRUE if gradient use the fill properties, EINA_FALSE otherwise.
edje_edit_state_image_border_fill_get()
EAPI unsigned char edje_edit_state_image_border_fill_get (Evas_Object * obj, const char * part, const char * state, double value)
Get if the image center should be draw.
1 means to draw the center, 0 to don't draw it.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the image border fill (not including the state value).
value The state value.
Returns
1 if the center of the bordered image is draw, 0 otherwise.
References _Edje_Part_Description_Spec_Image::border, EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Part_Description_Spec_Border::no_fill, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_image_border_fill_set()
EAPI void edje_edit_state_image_border_fill_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char fill)
Set if the image center should be draw.
1 means to draw the center, 0 to don't draw it.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image border fill (not including the state value).
value The state value.
fill Fill to be se. 1 if the center of the bordered image is draw, 0 otherwise.
References _Edje_Part_Description_Spec_Image::border, edje_object_calc_force(), EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Part_Description_Spec_Border::no_fill, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_image_border_get()
EAPI void edje_edit_state_image_border_get (Evas_Object * obj, const char * part, const char * state, double value, int * l, int * r, int * t, int * b)
Get the image border of a part state.
Pass NULL to any of [r,g,b,a] to get only the others.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the image border (not including the state value).
value The state value.
l A pointer to store the left value
r A pointer to store the right value
t A pointer to store the top value
b A pointer to store the bottom value
References _Edje_Part_Description_Spec_Border::b, _Edje_Part_Description_Spec_Image::border, EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Part_Description_Spec_Border::l, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Border::r, _Edje_Part_Description_Spec_Border::t, and _Edje_Part::type.
edje_edit_state_image_border_set()
EAPI void edje_edit_state_image_border_set (Evas_Object * obj, const char * part, const char * state, double value, int l, int r, int t, int b)
Set the image border of a part state.
Pass -1 to any of [l,r,t,b] to leave the value untouched.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image border (not including the state value).
value The state value.
l Left border value (or -1).
r Right border value (or -1).
t Top border value (or -1).
b Bottom border value (or -1).
References _Edje_Part_Description_Spec_Border::b, _Edje_Part_Description_Spec_Image::border, edje_object_calc_force(), EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Part_Description_Spec_Border::l, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Border::r, _Edje_Part_Description_Spec_Border::t, and _Edje_Part::type.
edje_edit_state_image_get()
EAPI const char* edje_edit_state_image_get (Evas_Object * obj, const char * part, const char * state, double value)
Get normal image name for a given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the name that is being used (not including the state value).
value The state value.
Returns
The name of the image used by state.
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_image_set()
EAPI void edje_edit_state_image_set (Evas_Object * obj, const char * part, const char * state, double value, const char * image)
Set normal image for a given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image that will be used (not including the state value).
value The state value.
image The name of the image (must be an image contained in the edje file).
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_max_h_get()
EAPI int edje_edit_state_max_h_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the maximum height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get maximum height (not including the state value).
value The state value.
Returns
The maximum height value.
edje_edit_state_max_h_set()
EAPI void edje_edit_state_max_h_set (Evas_Object * obj, const char * part, const char * state, double value, int max_h)
Set the maximum height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set maximum height (not including the state value).
value The state value.
max_h Maximum height value.
edje_edit_state_max_w_get()
EAPI int edje_edit_state_max_w_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the maximum width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get maximum width (not including the state value).
value The state value.
Returns
The maximum width value.
edje_edit_state_max_w_set()
EAPI void edje_edit_state_max_w_set (Evas_Object * obj, const char * part, const char * state, double value, int max_w)
Set the maximum width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set maximum width (not including the state value).
value The state value.
max_w Maximum width value.
edje_edit_state_min_h_get()
EAPI int edje_edit_state_min_h_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the minimum height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get minimum height (not including the state value).
value The state value.
Returns
The minimum height value.
edje_edit_state_min_h_set()
EAPI void edje_edit_state_min_h_set (Evas_Object * obj, const char * part, const char * state, double value, int min_h)
Set the minimum height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set minimum height (not including the state value).
value The state value.
min_h Minimum height value.
edje_edit_state_min_w_get()
EAPI int edje_edit_state_min_w_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the minimum width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get minimum width (not including the state value).
value The state value.
Returns
The minimum width value.
edje_edit_state_min_w_set()
EAPI void edje_edit_state_min_w_set (Evas_Object * obj, const char * part, const char * state, double value, int min_w)
Set the minimum width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set minimum width (not including the state value).
value The state value.
min_w Minimum width value.
edje_edit_state_name_set()
EAPI Eina_Bool edje_edit_state_name_set (Evas_Object * obj, const char * part, const char * state, double value, const char * new_name, double new_value)
Set a new name for the given state in the given part.
Parameters
obj Object being edited.
part Part that contain state.
state Name of the state to rename.
value Value of the state to rename.
new_name The new name for the state.
new_value The new value for the state.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_PD_OR_RETURN.
edje_edit_state_rel1_offset_x_get()
EAPI int edje_edit_state_rel1_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the 'rel1 offset X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel1 offset X' (not including the state value).
value The state value.
Returns
The 'rel1 offset X' value of the part state.
edje_edit_state_rel1_offset_x_set()
EAPI void edje_edit_state_rel1_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the 'rel1 offset X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel1 offset X' (not including the state value).
value The state value.
x The new 'rel1 offset X' value to set'.
edje_edit_state_rel1_offset_y_get()
EAPI int edje_edit_state_rel1_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the 'rel1 offset Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel1 offset Y' (not including the state value).
value The state value.
Returns
The 'rel1 offset Y' value of the part state.
edje_edit_state_rel1_offset_y_set()
EAPI void edje_edit_state_rel1_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Set the 'rel1 offset Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel1 offset Y' (not including the state value).
value The state value.
y The new 'rel1 offset Y' value to set'.
edje_edit_state_rel1_relative_x_get()
EAPI double edje_edit_state_rel1_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the 'rel1 relative X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel1 relative X' (not including the state value).
value The state value.
Returns
The 'rel1 relative X' value of the part state.
edje_edit_state_rel1_relative_x_set()
EAPI void edje_edit_state_rel1_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the 'rel1 relative X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel1 relative X' (not including the state value).
value The state value.
x The new 'rel1 relative X' value to set'.
edje_edit_state_rel1_relative_y_get()
EAPI double edje_edit_state_rel1_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the 'rel1 relative Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel1 relative Y' (not including the state value).
value The state value.
Returns
The 'rel1 relative Y' value of the part state.
edje_edit_state_rel1_relative_y_set()
EAPI void edje_edit_state_rel1_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Set the 'rel1 relative Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel1 relative Y' (not including the state value).
value The state value.
y The new 'rel1 relative Y' value to set'.
edje_edit_state_rel1_to_x_get()
EAPI const char* edje_edit_state_rel1_to_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the part name rel1x is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The state that contain which the part name rel1x is relative to (not including the state value).
value The state value.
Returns
The part name rel1x is relative to or NULL if the part is relative to the whole interface.
edje_edit_state_rel1_to_x_set()
EAPI void edje_edit_state_rel1_to_x_set (Evas_Object * obj, const char * part, const char * state, double value, const char * rel_to)
Set the part rel1x is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set rel1x is relative to (not including the state value).
value The state value.
rel_to The name of the part that is used as container/parent (NULL make the part relative to the whole interface).
Returns
The part name rel1x is relative to or NULL if the part is relative to the whole interface.
edje_edit_state_rel1_to_y_get()
EAPI const char* edje_edit_state_rel1_to_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the part name rel1y is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The state that contain which the part name rel1y is relative to (not including the state value).
value The state value.
Returns
The part name rel1y is relative to or NULL if the part is relative to the whole interface.
edje_edit_state_rel1_to_y_set()
EAPI void edje_edit_state_rel1_to_y_set (Evas_Object * obj, const char * part, const char * state, double value, const char * rel_to)
Set the part rel1y is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set rel1y is relative to (not including the state value).
value The state value.
rel_to The name of the part that is used as container/parent (NULL make the part relative to the whole interface).
Returns
The part name rel1y is relative to or NULL if the part is relative to the whole interface.
edje_edit_state_rel2_offset_x_get()
EAPI int edje_edit_state_rel2_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the 'rel2 offset X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel2 offset X' (not including the state value).
value The state value.
Returns
The 'rel2 offset X' value of the part state.
edje_edit_state_rel2_offset_x_set()
EAPI void edje_edit_state_rel2_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the 'rel2 offset X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel2 offset X' (not including the state value).
value The state value.
x The new 'rel2 offset X' value to set'.
edje_edit_state_rel2_offset_y_get()
EAPI int edje_edit_state_rel2_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the 'rel2 offset Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel2 offset Y' (not including the state value).
value The state value.
Returns
The 'rel2 offset Y' value of the part state.
edje_edit_state_rel2_offset_y_set()
EAPI void edje_edit_state_rel2_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Set the 'rel2 offset Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel2 offset Y' (not including the state value).
value The state value.
y The new 'rel2 offset Y' value to set'.
edje_edit_state_rel2_relative_x_get()
EAPI double edje_edit_state_rel2_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the 'rel2 relative X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel2 relative X' (not including the state value).
value The state value.
Returns
The 'rel2 relative X' value of the part state.
edje_edit_state_rel2_relative_x_set()
EAPI void edje_edit_state_rel2_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Set the 'rel2 relative X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel2 relative X' (not including the state value).
value The state value.
x The new 'rel2 relative X' value to set'.
edje_edit_state_rel2_relative_y_get()
EAPI double edje_edit_state_rel2_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the 'rel2 relative Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel2 relative Y' (not including the state value).
value The state value.
Returns
The 'rel2 relative Y' value of the part state.
edje_edit_state_rel2_relative_y_set()
EAPI void edje_edit_state_rel2_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Set the 'rel2 relative Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel2 relative Y' (not including the state value).
value The state value.
y The new 'rel2 relative Y' value to set'.
edje_edit_state_rel2_to_x_get()
EAPI const char* edje_edit_state_rel2_to_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the part name rel2x is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The state that contain which the part name rel2x is relative to (not including the state value).
value The state value.
Returns
The part name rel2x is relative to or NULL if the part is relative to the whole interface.
edje_edit_state_rel2_to_x_set()
EAPI void edje_edit_state_rel2_to_x_set (Evas_Object * obj, const char * part, const char * state, double value, const char * rel_to)
Set the part rel2x is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set rel2x is relative to (not including the state value).
value The state value.
rel_to The name of the part that is used as container/parent (NULL make the part relative to the whole interface).
Returns
The part name rel2x is relative to or NULL if the part is relative to the whole interface.
edje_edit_state_rel2_to_y_get()
EAPI const char* edje_edit_state_rel2_to_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the part name rel2y is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The state that contain which the part name rel2y is relative to (not including the state value).
value The state value.
Returns
The part name rel2y is relative to or NULL if the part is relative to the whole interface.
edje_edit_state_rel2_to_y_set()
EAPI void edje_edit_state_rel2_to_y_set (Evas_Object * obj, const char * part, const char * state, double value, const char * rel_to)
Set the part rel2y is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set rel2y is relative to (not including the state value).
value The state value.
rel_to The name of the part that is used as container/parent (NULL make the part relative to the whole interface).
Returns
The part name rel2y is relative to or NULL if the part is relative to the whole interface.
edje_edit_state_text_align_x_get()
EAPI double edje_edit_state_text_align_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the text horizontal align of a part state.
The value range is from 0.0(right) to 1.0(left)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the text horizontal align (not including the state value).
value The state value.
Returns
The text horizont align value
edje_edit_state_text_align_x_set()
EAPI void edje_edit_state_text_align_x_set (Evas_Object * obj, const char * part, const char * state, double value, double align)
Set the text horizontal align of a part state.
The value range is from 0.0(right) to 1.0(left)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the text horizontal align (not including the state value).
value The state value.
align The new text horizontal align value
edje_edit_state_text_align_y_get()
EAPI double edje_edit_state_text_align_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the text vertical align of a part state.
The value range is from 0.0(top) to 1.0(bottom)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the text vertical align (not including the state value).
value The state value.
Returns
The text horizont align value
edje_edit_state_text_align_y_set()
EAPI void edje_edit_state_text_align_y_set (Evas_Object * obj, const char * part, const char * state, double value, double align)
Set the text vertical align of a part state.
The value range is from 0.0(top) to 1.0(bottom)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the text vertical align (not including the state value).
value The state value.
align The new text vertical align value
edje_edit_state_text_elipsis_get()
EAPI double edje_edit_state_text_elipsis_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the text elipsis of a part state.
The value range is from 0.0(right) to 1.0(left)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the text elipses value (not including the state value).
value The state value.
Returns
The text elipsis value
edje_edit_state_text_elipsis_set()
EAPI void edje_edit_state_text_elipsis_set (Evas_Object * obj, const char * part, const char * state, double value, double balance)
Set the text vertical align of a part state.
The value range is from 0.0(right) to 1.0(left)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the text elipses value (not including the state value).
value The state value.
balance The position where to cut the string
edje_edit_state_text_fit_x_get()
EAPI Eina_Bool edje_edit_state_text_fit_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Get if the text part fit it's container horizontally.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the if the text part fit it's container horizontally (not including the state value).
value The state value.
Returns
EINA_TRUE If the part fit it's container horizontally, EINA_FALSE otherwise.
edje_edit_state_text_fit_x_set()
EAPI void edje_edit_state_text_fit_x_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool fit)
Set if the text part should fit it's container horizontally.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the if the text part fit it's container horizontally (not including the state value).
value The state value.
fit EINA_TRUE to make the text fit it's container horizontally, EINA_FALSE otherwise.
edje_edit_state_text_fit_y_get()
EAPI Eina_Bool edje_edit_state_text_fit_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Get if the text part fit it's container vertically.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the if the text part fit it's container vertically (not including the state value).
value The state value.
Returns
EINA_TRUE If the part fit it's container vertically, EINA_FALSE otherwise.
edje_edit_state_text_fit_y_set()
EAPI void edje_edit_state_text_fit_y_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool fit)
Set if the text part should fit it's container vertically.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the if the text part fit it's container vertically (not including the state value).
value The state value.
fit EINA_TRUE to make the text fit it's container vertically, EINA_FALSE otherwise.
edje_edit_state_text_get()
EAPI const char* edje_edit_state_text_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the text of a part state.
Remember to free the returned string with edje_edit_string_free().
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get text (not including the state value).
value The state value.
Returns
A newly allocated string containing the text for the given state.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, edje_string_get(), GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Text::text, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_text_set()
EAPI void edje_edit_state_text_set (Evas_Object * obj, const char * part, const char * state, double value, const char * text)
Set the text of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set text (not including the state value).
value The state value.
text The new text to assign.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_text_size_get()
EAPI int edje_edit_state_text_size_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the text size of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get text size (not including the state value).
value The state value.
Returns
The text size or -1 on errors.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Text::size, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_text_size_set()
EAPI void edje_edit_state_text_size_set (Evas_Object * obj, const char * part, const char * state, double value, int size)
Set the text size of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set text size (not including the state value).
value The state value.
size The new font size to set (in pixel)
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, GET_PD_OR_RETURN, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Text::size, _Edje_Part_Description_Text::text, and _Edje_Part::type.
edje_edit_state_tween_add()
EAPI Eina_Bool edje_edit_state_tween_add (Evas_Object * obj, const char * part, const char * state, double value, const char * tween)
Add a new tween frame to the given part state.
The tween param must be the name of an existing image.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to add a new tween frame (not including the state value).
value The state value.
tween The name of the image to add.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Real_Part::part, and _Edje_Part::type.
edje_edit_state_tween_del()
EAPI Eina_Bool edje_edit_state_tween_del (Evas_Object * obj, const char * part, const char * state, double value, const char * tween)
Remove the first tween with the given name.
The image is not removed from the edje.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to del the tween (not including the state value).
value The state value.
tween The name of the image to del.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Image::tweens_count, and _Edje_Part::type.
edje_edit_state_tweens_list_get()
EAPI Eina_List* edje_edit_state_tweens_list_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the list of all the tweens images in the given part state.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the list of all the tweens images (not including the state value).
value The state value.
Returns
A string list containing all the image name that form a tween animation in the given part state.
References EDJE_PART_TYPE_IMAGE, GET_PD_OR_RETURN, _Edje_Part_Description_Image::image, name, _Edje_Real_Part::part, _Edje_Part_Description_Spec_Image::tweens_count, and _Edje_Part::type.
edje_edit_state_visible_get()
EAPI Eina_Bool edje_edit_state_visible_get (Evas_Object * obj, const char * part, const char * state, double value)
Get the visibility of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get visibility (not including the state value).
value The state value.
Returns
EINA_TRUE if the state is visible, EINA_FALSE otherwise.
References GET_PD_OR_RETURN, and _Edje_Part_Description_Common::visible.
edje_edit_state_visible_set()
EAPI void edje_edit_state_visible_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool visible)
Set the visibility of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set visibility (not including the state value).
value The state value.
visible To set state visible (EINA_TRUE if the state is visible, EINA_FALSE otherwise)
References edje_object_calc_force(), GET_PD_OR_RETURN, and _Edje_Part_Description_Common::visible.
edje_edit_string_free()
EAPI void edje_edit_string_free (const char * str)
Free a generic string (char *) allocated by an edje_edit_*_get() function.
Parameters
str String to free.
edje_edit_string_list_free()
EAPI void edje_edit_string_list_free (Eina_List * lst)
Free a generic Eina_List of (char *) allocated by an edje_edit_*_get() function.
Parameters
lst List of strings to free.
edje_edit_style_add()
EAPI Eina_Bool edje_edit_style_add (Evas_Object * obj, const char * style)
Create a new text style object in the given edje.
If another style with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
style Name for the new style.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_style_del()
EAPI void edje_edit_style_del (Evas_Object * obj, const char * style)
Delete the given text style and all the child tags.
Parameters
obj Object being edited.
style Style to delete.
References GET_ED_OR_RETURN.
edje_edit_style_tag_add()
EAPI Eina_Bool edje_edit_style_tag_add (Evas_Object * obj, const char * style, const char * tag_name)
Add a new tag to the given text style.
If another tag with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
style Style where to add the new tag.
tag_name Name for the new tag.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
References GET_ED_OR_RETURN.
edje_edit_style_tag_del()
EAPI void edje_edit_style_tag_del (Evas_Object * obj, const char * style, const char * tag)
Delete the given tag.
Parameters
obj Object being edited.
style Style from where to remove the tag.
tag Tag to delete.
References GET_ED_OR_RETURN.
edje_edit_style_tag_name_set()
EAPI void edje_edit_style_tag_name_set (Evas_Object * obj, const char * style, const char * tag, const char * new_name)
Set the name of the given tag.
Parameters
obj Object being edited.
style Style containing the tag to rename.
tag Tag to rename.
new_name New name for the tag.
References _Edje::file, GET_ED_OR_RETURN, and _Edje_File::styles.
edje_edit_style_tag_value_get()
EAPI const char* edje_edit_style_tag_value_get (Evas_Object * obj, const char * style, const char * tag)
Get the value of the given tag.
Parameters
obj Object being edited.
style Style containing the tag being.
tag Tag to get the value for.
Returns
Value of the given tag.
References _Edje::file, GET_ED_OR_RETURN, and _Edje_File::styles.
edje_edit_style_tag_value_set()
EAPI void edje_edit_style_tag_value_set (Evas_Object * obj, const char * style, const char * tag, const char * new_value)
Set the value of the given tag.
Parameters
obj Object being edited.
style Style containing the tag to change.
tag Name of the tag to set the value for.
new_value Value for the tag.
References _Edje::file, GET_ED_OR_RETURN, and _Edje_File::styles.
edje_edit_style_tags_list_get()
EAPI Eina_List* edje_edit_style_tags_list_get (Evas_Object * obj, const char * style)
Get the list of all the tags name in the given text style.
Parameters
obj Object being edited.
style Style to get the tags for.
Returns
List of strings, each being one tag in the given style.
References _Edje::file, GET_ED_OR_RETURN, and _Edje_File::styles.
edje_edit_styles_list_get()
EAPI Eina_List* edje_edit_styles_list_get (Evas_Object * obj)
Get the list of all the text styles in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being the name for a text style.
References _Edje::file, GET_ED_OR_RETURN, _Edje_Style::name, and _Edje_File::styles.
Variable Documentation
EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED extern
Referenced by edje_edit_group_del().
EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST extern
Referenced by edje_edit_group_del(), and edje_edit_object_add().
EDJE_EDIT_ERROR_GROUP_REFERENCED
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_REFERENCED extern
Referenced by edje_edit_group_del().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59