src/lib/edje_entry.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_entry.c File Reference
Data Structures
struct _Anchor
struct _Entry
struct _Sel
Typedefs
typedef struct _Anchor Anchor
typedef struct _Entry Entry
typedef struct _Sel Sel
Functions
const Eina_List * _edje_entry_anchor_geometry_get (Edje_Real_Part *rp, const char *anchor)
const Eina_List * _edje_entry_anchors_list (Edje_Real_Part *rp)
Edje_Text_Autocapital_Type _edje_entry_autocapital_type_get (Edje_Real_Part *rp)
void _edje_entry_autocapital_type_set (Edje_Real_Part *rp, Edje_Text_Autocapital_Type autocapital_type)
void _edje_entry_cursor_begin (Edje_Real_Part *rp, Edje_Cursor cur)
char * _edje_entry_cursor_content_get (Edje_Real_Part *rp, Edje_Cursor cur)
Eina_Bool _edje_entry_cursor_coord_set (Edje_Real_Part *rp, Edje_Cursor cur, Evas_Coord x, Evas_Coord y)
void _edje_entry_cursor_copy (Edje_Real_Part *rp, Edje_Cursor cur, Edje_Cursor dst)
Eina_Bool _edje_entry_cursor_down (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_end (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_geometry_get (Edje_Real_Part *rp, Evas_Coord *cx, Evas_Coord *cy, Evas_Coord *cw, Evas_Coord *ch)
Eina_Bool _edje_entry_cursor_is_format_get (Edje_Real_Part *rp, Edje_Cursor cur)
Eina_Bool _edje_entry_cursor_is_visible_format_get (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_line_begin (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_line_end (Edje_Real_Part *rp, Edje_Cursor cur)
Eina_Bool _edje_entry_cursor_next (Edje_Real_Part *rp, Edje_Cursor cur)
int _edje_entry_cursor_pos_get (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_pos_set (Edje_Real_Part *rp, Edje_Cursor cur, int pos)
Eina_Bool _edje_entry_cursor_prev (Edje_Real_Part *rp, Edje_Cursor cur)
Eina_Bool _edje_entry_cursor_up (Edje_Real_Part *rp, Edje_Cursor cur)
void * _edje_entry_imf_context_get (Edje_Real_Part *rp)
void _edje_entry_imf_context_reset (Edje_Real_Part *rp)
void _edje_entry_init (Edje *ed)
Eina_Bool _edje_entry_input_panel_enabled_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_enabled_set (Edje_Real_Part *rp, Eina_Bool enabled)
void _edje_entry_input_panel_hide (Edje_Real_Part *rp)
void _edje_entry_input_panel_imdata_get (Edje_Real_Part *rp, void *data __UNUSED__, int *len __UNUSED__)
void _edje_entry_input_panel_imdata_set (Edje_Real_Part *rp, const void *data __UNUSED__, int len __UNUSED__)
Edje_Input_Panel_Lang _edje_entry_input_panel_language_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_language_set (Edje_Real_Part *rp, Edje_Input_Panel_Lang lang)
Edje_Input_Panel_Layout _edje_entry_input_panel_layout_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_layout_set (Edje_Real_Part *rp, Edje_Input_Panel_Layout layout)
Eina_Bool _edje_entry_input_panel_return_key_disabled_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_return_key_disabled_set (Edje_Real_Part *rp, Eina_Bool disabled __UNUSED__)
Edje_Input_Panel_Return_Key_Type _edje_entry_input_panel_return_key_type_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_return_key_type_set (Edje_Real_Part *rp, Edje_Input_Panel_Return_Key_Type return_key_type __UNUSED__)
void _edje_entry_input_panel_show (Edje_Real_Part *rp)
Eina_Bool _edje_entry_item_geometry_get (Edje_Real_Part *rp, const char *item, Evas_Coord *cx, Evas_Coord *cy, Evas_Coord *cw, Evas_Coord *ch)
const Eina_List * _edje_entry_items_list (Edje_Real_Part *rp)
Eina_Bool _edje_entry_prediction_allow_get (Edje_Real_Part *rp)
void _edje_entry_prediction_allow_set (Edje_Real_Part *rp, Eina_Bool prediction)
void _edje_entry_real_part_configure (Edje_Real_Part *rp)
void _edje_entry_real_part_init (Edje_Real_Part *rp)
void _edje_entry_real_part_shutdown (Edje_Real_Part *rp)
void _edje_entry_select_abort (Edje_Real_Part *rp)
void _edje_entry_select_all (Edje_Real_Part *rp)
Eina_Bool _edje_entry_select_allow_get (const Edje_Real_Part *rp)
void _edje_entry_select_allow_set (Edje_Real_Part *rp, Eina_Bool allow)
void _edje_entry_select_begin (Edje_Real_Part *rp)
void _edje_entry_select_extend (Edje_Real_Part *rp)
void _edje_entry_select_none (Edje_Real_Part *rp)
const char * _edje_entry_selection_get (Edje_Real_Part *rp)
void _edje_entry_set_cursor_end (Edje_Real_Part *rp)
void _edje_entry_set_cursor_start (Edje_Real_Part *rp)
void _edje_entry_shutdown (Edje *ed)
const char * _edje_entry_text_get (Edje_Real_Part *rp)
void _edje_entry_text_markup_append (Edje_Real_Part *rp, const char *text)
void _edje_entry_text_markup_insert (Edje_Real_Part *rp, const char *text)
void _edje_entry_text_markup_set (Edje_Real_Part *rp, const char *text)
void _edje_entry_user_insert (Edje_Real_Part *rp, const char *text)
Typedef Documentation
Anchor
typedef struct _Anchor Anchor
Entry
typedef struct _Entry Entry
Sel
typedef struct _Sel Sel
Function Documentation
_edje_entry_anchor_geometry_get()
const Eina_List* _edje_entry_anchor_geometry_get (Edje_Real_Part * rp, const char * anchor)
References _Entry::anchors, _Edje_Real_Part::entry_data, _Anchor::item, _Anchor::name, and _Anchor::sel.
Referenced by edje_object_part_text_anchor_geometry_get().
_edje_entry_anchors_list()
const Eina_List* _edje_entry_anchors_list (Edje_Real_Part * rp)
References _Entry::anchorlist, _Entry::anchors, _Edje_Real_Part::entry_data, _Anchor::item, and _Anchor::name.
Referenced by edje_object_part_text_anchor_list_get().
_edje_entry_autocapital_type_get()
Edje_Text_Autocapital_Type _edje_entry_autocapital_type_get (Edje_Real_Part * rp)
References EDJE_TEXT_AUTOCAPITAL_TYPE_NONE, and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_autocapital_type_get().
_edje_entry_autocapital_type_set()
void _edje_entry_autocapital_type_set (Edje_Real_Part * rp, Edje_Text_Autocapital_Type autocapital_type)
References EDJE_ENTRY_EDIT_MODE_PASSWORD, EDJE_TEXT_AUTOCAPITAL_TYPE_NONE, _Edje_Real_Part::entry_data, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
Referenced by edje_object_part_text_autocapital_type_set().
_edje_entry_cursor_begin()
void _edje_entry_cursor_begin (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_begin_set().
_edje_entry_cursor_content_get()
char* _edje_entry_cursor_content_get (Edje_Real_Part * rp, Edje_Cursor cur)
Referenced by edje_object_part_text_cursor_content_get().
_edje_entry_cursor_coord_set()
Eina_Bool _edje_entry_cursor_coord_set (Edje_Real_Part * rp, Edje_Cursor cur, Evas_Coord x, Evas_Coord y)
Referenced by edje_object_part_text_cursor_coord_set().
_edje_entry_cursor_copy()
void _edje_entry_cursor_copy (Edje_Real_Part * rp, Edje_Cursor cur, Edje_Cursor dst)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_copy().
_edje_entry_cursor_down()
Eina_Bool _edje_entry_cursor_down (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_down().
_edje_entry_cursor_end()
void _edje_entry_cursor_end (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_end_set().
_edje_entry_cursor_geometry_get()
void _edje_entry_cursor_geometry_get (Edje_Real_Part * rp, Evas_Coord * cx, Evas_Coord * cy, Evas_Coord * cw, Evas_Coord * ch)
References _Entry::cursor, _Entry::cursor_fg, _Edje_Part::cursor_mode, EDJE_ENTRY_CURSOR_MODE_BEFORE, EDJE_ENTRY_CURSOR_MODE_UNDER, edje_object_size_min_restricted_calc(), _Edje_Real_Part::entry_data, _Edje_Real_Part::object, and _Edje_Real_Part::part.
Referenced by edje_object_part_text_cursor_geometry_get().
_edje_entry_cursor_is_format_get()
Eina_Bool _edje_entry_cursor_is_format_get (Edje_Real_Part * rp, Edje_Cursor cur)
Referenced by edje_object_part_text_cursor_is_format_get().
_edje_entry_cursor_is_visible_format_get()
Eina_Bool _edje_entry_cursor_is_visible_format_get (Edje_Real_Part * rp, Edje_Cursor cur)
Referenced by edje_object_part_text_cursor_is_visible_format_get().
_edje_entry_cursor_line_begin()
void _edje_entry_cursor_line_begin (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_line_begin_set().
_edje_entry_cursor_line_end()
void _edje_entry_cursor_line_end (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_line_end_set().
_edje_entry_cursor_next()
Eina_Bool _edje_entry_cursor_next (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_next().
_edje_entry_cursor_pos_get()
int _edje_entry_cursor_pos_get (Edje_Real_Part * rp, Edje_Cursor cur)
Referenced by edje_object_part_text_cursor_pos_get().
_edje_entry_cursor_pos_set()
void _edje_entry_cursor_pos_set (Edje_Real_Part * rp, Edje_Cursor cur, int pos)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_pos_set().
_edje_entry_cursor_prev()
Eina_Bool _edje_entry_cursor_prev (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_prev().
_edje_entry_cursor_up()
Eina_Bool _edje_entry_cursor_up (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_up().
_edje_entry_imf_context_get()
void* _edje_entry_imf_context_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_imf_context_get().
_edje_entry_imf_context_reset()
void _edje_entry_imf_context_reset (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by _edje_entry_select_abort(), _edje_entry_select_all(), _edje_entry_select_begin(), _edje_entry_select_extend(), _edje_entry_text_markup_insert(), _edje_entry_text_markup_set(), and edje_object_part_text_imf_context_reset().
_edje_entry_init()
void _edje_entry_init (Edje * ed)
References _Edje::entries_inited, _Edje::has_entries, and _Edje::obj.
_edje_entry_input_panel_enabled_get()
Eina_Bool _edje_entry_input_panel_enabled_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, and _Entry::input_panel_enable.
Referenced by edje_object_part_text_input_panel_enabled_get().
_edje_entry_input_panel_enabled_set()
void _edje_entry_input_panel_enabled_set (Edje_Real_Part * rp, Eina_Bool enabled)
References _Edje_Real_Part::entry_data, and _Entry::input_panel_enable.
Referenced by edje_object_part_text_input_panel_enabled_set().
_edje_entry_input_panel_hide()
void _edje_entry_input_panel_hide (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_hide().
_edje_entry_input_panel_imdata_get()
void _edje_entry_input_panel_imdata_get (Edje_Real_Part * rp, void *data __UNUSED__, int *len __UNUSED__)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_imdata_get().
_edje_entry_input_panel_imdata_set()
void _edje_entry_input_panel_imdata_set (Edje_Real_Part * rp, const void *data __UNUSED__, int len __UNUSED__)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_imdata_set().
_edje_entry_input_panel_language_get()
Edje_Input_Panel_Lang _edje_entry_input_panel_language_get (Edje_Real_Part * rp)
References EDJE_INPUT_PANEL_LANG_AUTOMATIC, _Edje_Real_Part::entry_data, and _Entry::input_panel_lang.
Referenced by edje_object_part_text_input_panel_language_get().
_edje_entry_input_panel_language_set()
void _edje_entry_input_panel_language_set (Edje_Real_Part * rp, Edje_Input_Panel_Lang lang)
References _Edje_Real_Part::entry_data, and _Entry::input_panel_lang.
Referenced by edje_object_part_text_input_panel_language_set().
_edje_entry_input_panel_layout_get()
Edje_Input_Panel_Layout _edje_entry_input_panel_layout_get (Edje_Real_Part * rp)
References EDJE_INPUT_PANEL_LAYOUT_INVALID, and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_layout_get().
_edje_entry_input_panel_layout_set()
void _edje_entry_input_panel_layout_set (Edje_Real_Part * rp, Edje_Input_Panel_Layout layout)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_layout_set().
_edje_entry_input_panel_return_key_disabled_get()
Eina_Bool _edje_entry_input_panel_return_key_disabled_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_return_key_disabled_get().
_edje_entry_input_panel_return_key_disabled_set()
void _edje_entry_input_panel_return_key_disabled_set (Edje_Real_Part * rp, Eina_Bool disabled __UNUSED__)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_return_key_disabled_set().
_edje_entry_input_panel_return_key_type_get()
Edje_Input_Panel_Return_Key_Type _edje_entry_input_panel_return_key_type_get (Edje_Real_Part * rp)
References EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DEFAULT, and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_return_key_type_get().
_edje_entry_input_panel_return_key_type_set()
void _edje_entry_input_panel_return_key_type_set (Edje_Real_Part * rp, Edje_Input_Panel_Return_Key_Type return_key_type __UNUSED__)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_return_key_type_set().
_edje_entry_input_panel_show()
void _edje_entry_input_panel_show (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_show().
_edje_entry_item_geometry_get()
Eina_Bool _edje_entry_item_geometry_get (Edje_Real_Part * rp, const char * item, Evas_Coord * cx, Evas_Coord * cy, Evas_Coord * cw, Evas_Coord * ch)
References _Entry::anchors, _Edje_Real_Part::entry_data, _Anchor::item, _Anchor::name, and _Anchor::start.
Referenced by edje_object_part_text_item_geometry_get().
_edje_entry_items_list()
const Eina_List* _edje_entry_items_list (Edje_Real_Part * rp)
References _Entry::anchors, _Edje_Real_Part::entry_data, _Anchor::item, _Entry::itemlist, and _Anchor::name.
Referenced by edje_object_part_text_item_list_get().
_edje_entry_prediction_allow_get()
Eina_Bool _edje_entry_prediction_allow_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, and _Entry::prediction_allow.
Referenced by edje_object_part_text_prediction_allow_get().
_edje_entry_prediction_allow_set()
void _edje_entry_prediction_allow_set (Edje_Real_Part * rp, Eina_Bool prediction)
References _Edje_Real_Part::entry_data, and _Entry::prediction_allow.
Referenced by edje_object_part_text_prediction_allow_set().
_edje_entry_real_part_configure()
void _edje_entry_real_part_configure (Edje_Real_Part * rp)
References _Edje_Part::cursor_mode, EDJE_ENTRY_CURSOR_MODE_BEFORE, EDJE_ENTRY_CURSOR_MODE_UNDER, _Edje_Real_Part::entry_data, and _Edje_Real_Part::part.
_edje_entry_real_part_init()
void _edje_entry_real_part_init (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, _Edje_Real_Part::object, and _Entry::rp.
_edje_entry_real_part_shutdown()
void _edje_entry_real_part_shutdown (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by _edje_file_del().
_edje_entry_select_abort()
void _edje_entry_select_abort (Edje_Real_Part * rp)
References _edje_entry_imf_context_reset(), _Edje_Real_Part::entry_data, and _Entry::selecting.
Referenced by edje_object_part_text_select_abort().
_edje_entry_select_all()
void _edje_entry_select_all (Edje_Real_Part * rp)
References _edje_entry_imf_context_reset(), and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_select_all().
_edje_entry_select_allow_get()
Eina_Bool _edje_entry_select_allow_get (const Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, and _Entry::select_allow.
_edje_entry_select_allow_set()
void _edje_entry_select_allow_set (Edje_Real_Part * rp, Eina_Bool allow)
References EDJE_ENTRY_SELECTION_MODE_DEFAULT, _Edje_Real_Part::entry_data, _Edje_Real_Part::part, _Entry::select_allow, and _Edje_Part::select_mode.
Referenced by edje_object_part_text_select_allow_set().
_edje_entry_select_begin()
void _edje_entry_select_begin (Edje_Real_Part * rp)
References _edje_entry_imf_context_reset(), and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_select_begin().
_edje_entry_select_extend()
void _edje_entry_select_extend (Edje_Real_Part * rp)
References _edje_entry_imf_context_reset(), and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_select_extend().
_edje_entry_select_none()
void _edje_entry_select_none (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_select_none().
_edje_entry_selection_get()
const char* _edje_entry_selection_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, _Entry::have_selection, _Entry::sel_end, _Entry::sel_start, and _Entry::selection.
Referenced by edje_object_part_text_selection_get().
_edje_entry_set_cursor_end()
void _edje_entry_set_cursor_end (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
_edje_entry_set_cursor_start()
void _edje_entry_set_cursor_start (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
_edje_entry_shutdown()
void _edje_entry_shutdown (Edje * ed)
References _Edje::entries_inited, _Edje::has_entries, and _Edje::obj.
Referenced by _edje_file_del().
_edje_entry_text_get()
const char* _edje_entry_text_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, and _Edje_Real_Part::object.
Referenced by edje_object_part_text_get(), and edje_object_part_text_unescaped_get().
_edje_entry_text_markup_append()
void _edje_entry_text_markup_append (Edje_Real_Part * rp, const char * text)
References _Edje_Real_Part::entry_data, and _Edje_Real_Part::object.
Referenced by _edje_object_part_text_raw_append().
_edje_entry_text_markup_insert()
void _edje_entry_text_markup_insert (Edje_Real_Part * rp, const char * text)
References _edje_entry_imf_context_reset(), _Edje_Real_Part::entry_data, and _Entry::have_selection.
Referenced by edje_object_part_text_insert().
_edje_entry_text_markup_set()
void _edje_entry_text_markup_set (Edje_Real_Part * rp, const char * text)
References _edje_entry_imf_context_reset(), and _Edje_Real_Part::entry_data.
Referenced by _edje_object_part_text_raw_set().
_edje_entry_user_insert()
void _edje_entry_user_insert (Edje_Real_Part * rp, const char * text)
References _Edje_Entry_Change_Info::change, _Edje_Real_Part::entry_data, _Entry::have_selection, _Edje_Entry_Change_Info::insert, and _Edje_Real_Part::object.
Referenced by edje_object_part_text_user_insert().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59