src/lib/edje_textblock_styles.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_textblock_styles.c File Reference
Functions
void _edje_textblock_style_all_update (Edje *ed)
void _edje_textblock_style_cleanup (Edje_File *edf)
void _edje_textblock_style_parse_and_fix (Edje_File *edf)
void _edje_textblock_styles_add (Edje *ed)
void _edje_textblock_styles_del (Edje *ed)
Function Documentation
_edje_textblock_style_all_update()
void _edje_textblock_style_all_update (Edje * ed)
References _edje_fontset_append, _edje_text_class_find(), _edje_text_size_calc(), _Edje::file, _Edje_Style_Tag::font, _Edje_Text_Class::font, _Edje_Style_Tag::font_size, _Edje_Style_Tag::key, _Edje_File::path, _Edje_Text_Class::size, _Edje_Style::style, _Edje_File::styles, _Edje_Style::tags, _Edje_Style_Tag::text_class, and _Edje_Style_Tag::value.
Referenced by edje_object_text_class_set().
_edje_textblock_style_cleanup()
void _edje_textblock_style_cleanup (Edje_File * edf)
References _Edje_Style_Tag::font, _Edje_File::free_strings, _Edje_Style_Tag::key, _Edje_Style::name, _Edje_Style::style, _Edje_File::styles, _Edje_Style::tags, _Edje_Style_Tag::text_class, and _Edje_Style_Tag::value.
Referenced by _edje_file_free().
_edje_textblock_style_parse_and_fix()
void _edje_textblock_style_parse_and_fix (Edje_File * edf)
References _edje_fontset_append, _Edje_Style_Tag::key, _Edje_File::path, _Edje_Style::style, _Edje_File::styles, and _Edje_Style::tags.
_edje_textblock_styles_add()
void _edje_textblock_styles_add (Edje * ed)
References _edje_text_class_member_add(), _Edje::file, _Edje_File::styles, _Edje_Style::tags, and _Edje_Style_Tag::text_class.
_edje_textblock_styles_del()
void _edje_textblock_styles_del (Edje * ed)
References _edje_text_class_member_del(), _Edje::file, _Edje_File::styles, _Edje_Style::tags, and _Edje_Style_Tag::text_class.
Referenced by _edje_file_del().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59