src/lib/edje_embryo.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_embryo.c File Reference
Macros
#define ALLOC_COPY_DESC(Short, Type, To, Spec)
#define ALLOC_DESC(Short, Type, To) case EDJE_PART_TYPE_##Short: To = calloc(1, sizeof (Edje_Part_Description_##Type)); break;
#define DUP(x) x ? (char *)eina_stringshare_add(x) : NULL
Functions
void _edje_embryo_globals_init (Edje *ed)
void _edje_embryo_script_init (Edje_Part_Collection *edc)
void _edje_embryo_script_reset (Edje *ed)
void _edje_embryo_script_shutdown (Edje_Part_Collection *edc)
void _edje_embryo_test_run (Edje *ed, const char *fname, const char *sig, const char *src)
Macro Definition Documentation
ALLOC_COPY_DESC
#define ALLOC_COPY_DESC (Short, Type, To, Spec)
Value:
    case EDJE_PART_TYPE_##Short:                    \
      {                             \
         Edje_Part_Description_##Type *tmp;             \
         Edje_Part_Description_##Type *new;             \
                                    \
         tmp = (Edje_Part_Description_##Type *) parent;     \
                                    \
         new = calloc(1, sizeof (Edje_Part_Description_##Type));    \
         new->Spec = tmp->Spec;                 \
         d = &new->common;                      \
         break;                         \
      }
ALLOC_DESC
#define ALLOC_DESC (Short, Type, To) case EDJE_PART_TYPE_##Short: To = calloc(1, sizeof (Edje_Part_Description_##Type)); break;
DUP
#define DUP (x) x ? (char *)eina_stringshare_add(x) : NULL
Function Documentation
_edje_embryo_globals_init()
void _edje_embryo_globals_init (Edje * ed)
References _Edje::collection, EDJE_VAR_MAGIC_BASE, and _Edje_Part_Collection::script.
Referenced by _edje_embryo_script_reset(), _edje_embryo_test_run(), and _edje_message_process().
_edje_embryo_script_init()
void _edje_embryo_script_init (Edje_Part_Collection * edc)
References _Edje_Part_Collection::script.
_edje_embryo_script_reset()
void _edje_embryo_script_reset (Edje * ed)
References _edje_embryo_globals_init(), _Edje::collection, and _Edje_Part_Collection::script.
Referenced by _edje_message_process().
_edje_embryo_script_shutdown()
void _edje_embryo_script_shutdown (Edje_Part_Collection * edc)
References _Edje_Part_Collection::script.
Referenced by _edje_collection_free().
_edje_embryo_test_run()
void _edje_embryo_test_run (Edje * ed, const char * fname, const char * sig, const char * src)
References _edje_embryo_globals_init(), _Edje::collection, ERR, _Edje::file, _Edje_Part_Collection::part, _Edje_File::path, and _Edje_Part_Collection::script.
Referenced by _edje_program_run().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59