src/lib/edje_cache.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_cache.c File Reference
Macros
#define INIT_EMP(Tp, Sz, Ce)
#define INIT_EMP_BOTH(Tp, Sz, Ce)
Functions
void _edje_cache_coll_clean (Edje_File *edf)
void _edje_cache_coll_flush (Edje_File *edf)
void _edje_cache_coll_unref (Edje_File *edf, Edje_Part_Collection *edc)
Edje_File * _edje_cache_file_coll_open (const char *file, const char *coll, int *error_ret, Edje_Part_Collection **edc_ret, Edje *ed)
void _edje_cache_file_unref (Edje_File *edf)
void _edje_file_cache_shutdown (void)
EAPI void edje_collection_cache_flush (void)
Clean the collection cache.
EAPI int edje_collection_cache_get (void)
Return the collection cache size.
EAPI void edje_collection_cache_set (int count)
Set the collection cache size.
EAPI void edje_file_cache_flush (void)
Clean the file cache.
EAPI int edje_file_cache_get (void)
Return the file cache size.
EAPI void edje_file_cache_set (int count)
Set the file cache size.
Macro Definition Documentation
INIT_EMP
#define INIT_EMP (Tp, Sz, Ce)
Value:
   buffer = alloca(strlen(ce->entry) + strlen(#Tp) + 2);               \
   sprintf(buffer, "%s/%s", ce->entry, #Tp);                           \
   Ce->mp.Tp = eina_mempool_add("one_big", buffer, NULL, sizeof (Sz), Ce->count.Tp); \
   _emp_##Tp = Ce->mp.Tp;
INIT_EMP_BOTH
#define INIT_EMP_BOTH (Tp, Sz, Ce)
Value:
   INIT_EMP(Tp, Sz, Ce)                                                 \
   Ce->mp_rtl.Tp = eina_mempool_add("one_big", buffer, NULL,            \
         sizeof (Sz), Ce->count.Tp);
Function Documentation
_edje_cache_coll_clean()
void _edje_cache_coll_clean (Edje_File * edf)
References _Edje_File::collection_cache.
Referenced by _edje_cache_coll_unref().
_edje_cache_coll_flush()
void _edje_cache_coll_flush (Edje_File * edf)
References _edje_collection_free(), _Edje_File::collection, _Edje_File::collection_cache, and _Edje_Part_Collection::part.
Referenced by _edje_cache_coll_unref(), and _edje_file_free().
_edje_cache_coll_unref()
void _edje_cache_coll_unref (Edje_File * edf, Edje_Part_Collection * edc)
References _edje_cache_coll_clean(), _edje_cache_coll_flush(), _edje_collection_free(), _Edje_File::collection, _Edje_File::collection_cache, _Edje_File::dangling, ERR, _Edje_Part_Collection::part, _Edje_Part_Collection_Directory_Entry::ref, and _Edje_Part_Collection::references.
Referenced by _edje_file_del().
_edje_cache_file_coll_open()
Edje_File* _edje_cache_file_coll_open (const char * file, const char * coll, int * error_ret, Edje_Part_Collection ** edc_ret, Edje * ed)
References EDJE_LOAD_ERROR_DOES_NOT_EXIST.
Referenced by _edje_file_add(), edje_file_collection_list(), edje_file_data_get(), and edje_file_group_exists().
_edje_cache_file_unref()
void _edje_cache_file_unref (Edje_File * edf)
References _edje_file_free(), _Edje_File::dangling, and _Edje_File::references.
Referenced by _edje_file_add(), _edje_file_del(), edje_file_collection_list(), edje_file_data_get(), and edje_file_group_exists().
_edje_file_cache_shutdown()
void _edje_file_cache_shutdown (void)
References edje_file_cache_flush().
edje_collection_cache_flush()
EAPI void edje_collection_cache_flush (void)
Clean the collection cache.
This function cleans the collection cache, but keeps this cache's size to the last value set.
See also
edje_collection_cache_set()
edje_collection_cache_get()
edje_collection_cache_get()
EAPI int edje_collection_cache_get (void)
Return the collection cache size.
Returns
The collection cache size, in edje object units. Default is 16.
This function returns the collection cache size set by edje_collection_cache_set().
See also
edje_collection_cache_set()
edje_collection_cache_flush()
edje_collection_cache_set()
EAPI void edje_collection_cache_set (int count)
Set the collection cache size.
Parameters
count The collection cache size, in edje object units. Default is 16.
This function sets the collection cache size. Edje keeps this cache in order to prevent duplicates of edje {collection,group,part} entries in memory. The collection cache size can be retrieved with edje_collection_cache_get().
See also
edje_collection_cache_get()
edje_collection_cache_flush()
edje_file_cache_flush()
EAPI void edje_file_cache_flush (void)
Clean the file cache.
This function cleans the file cache entries, but keeps this cache's size to the last value set.
See also
edje_file_cache_set()
edje_file_cache_get()
Referenced by _edje_file_cache_shutdown().
edje_file_cache_get()
EAPI int edje_file_cache_get (void)
Return the file cache size.
Returns
The file cache size in edje file units. Default is 16.
This function returns the file cache size set by edje_file_cache_set().
See also
edje_file_cache_set()
edje_file_cache_flush()
edje_file_cache_set()
EAPI void edje_file_cache_set (int count)
Set the file cache size.
Parameters
count The file cache size in edje file units. Default is 16.
This function sets the file cache size. Edje keeps this cache in order to prevent duplicates of edje file entries in memory. The file cache size can be retrieved with edje_file_cache_get().
See also
edje_file_cache_get()
edje_file_cache_flush()
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59