src/lib/edje_calc.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_calc.c File Reference
Macros
#define EDIT_ALLOC_POOL_RTL(Short, Type, Name)
#define FFP(_x1, _x2, _p)
#define FINTP(_x1, _x2, _p)
#define IMAGES "edje/images/"
#define INTP(_x1, _x2, _p) TO_INT(FINTP(_x1, _x2, _p))
#define MIX(P1, P2, P3, pos, info) P3->info = P1->info + TO_INT(SCALE(pos, P2->info - P1->info));
#define RECALC_SINGLE_TEXT_USING_APPLY 1
Functions
void _edje_dragable_pos_set (Edje *ed, Edje_Real_Part *ep, FLOAT_T x, FLOAT_T y)
void _edje_part_description_apply (Edje *ed, Edje_Real_Part *ep, const char *d1, double v1, const char *d2, double v2)
Edje_Part_Description_Common * _edje_part_description_find (Edje *ed, Edje_Real_Part *rp, const char *name, double val)
int _edje_part_dragable_calc (Edje *ed __UNUSED__, Edje_Real_Part *ep, FLOAT_T *x, FLOAT_T *y)
void _edje_part_pos_set (Edje *ed, Edje_Real_Part *ep, int mode, FLOAT_T pos, FLOAT_T v1, FLOAT_T v2)
void _edje_part_recalc (Edje *ed, Edje_Real_Part *ep, int flags, Edje_Calc_Params *state)
void _edje_part_recalc_1 (Edje *ed, Edje_Real_Part *ep)
void _edje_recalc (Edje *ed)
void _edje_recalc_do (Edje *ed)
Macro Definition Documentation
EDIT_ALLOC_POOL_RTL
#define EDIT_ALLOC_POOL_RTL (Short, Type, Name)
Value:
case EDJE_PART_TYPE_##Short:                                          \
{                                                                     \
   Edje_Part_Description_##Type * Name;                               \
   Name = eina_mempool_malloc(ce->mp_rtl.Short,                       \
                              sizeof (Edje_Part_Description_##Type)); \
   memset(Name, 0, sizeof(Edje_Part_Description_##Type));             \
   desc_rtl = &Name->common;                                          \
   memsize = sizeof(Edje_Part_Description_##Type);                    \
   break;                                                             \
}
FFP
#define FFP (_x1, _x2, _p)
Value:
  (((_x1) == (_x2))       \
   ? (_x1)                \
   : ADD(_x1, MUL(_p, SUB(_x2, _x1))));
FINTP
#define FINTP (_x1, _x2, _p)
Value:
  (((_x1) == (_x2))         \
   ? FROM_INT((_x1))        \
   : ADD(FROM_INT(_x1),     \
         SCALE((_p), (_x2) - (_x1))))
IMAGES
#define IMAGES "edje/images/"
INTP
#define INTP (_x1, _x2, _p) TO_INT(FINTP(_x1, _x2, _p))
MIX
#define MIX (P1, P2, P3, pos, info) P3->info = P1->info + TO_INT(SCALE(pos, P2->info - P1->info));
RECALC_SINGLE_TEXT_USING_APPLY
#define RECALC_SINGLE_TEXT_USING_APPLY 1
Function Documentation
_edje_dragable_pos_set()
void _edje_dragable_pos_set (Edje * ed, Edje_Real_Part * ep, FLOAT_T x, FLOAT_T y)
References _edje_recalc(), _Edje::dirty, _Edje_Real_Part::drag, _Edje_Real_Part_Drag::need_reset, _Edje::recalc_call, _Edje_Real_Part_Drag::tmp, _Edje_Real_Part_Drag::x, and _Edje_Real_Part_Drag::y.
Referenced by _edje_program_run().
_edje_part_description_apply()
void _edje_part_description_apply (Edje * ed, Edje_Real_Part * ep, const char * d1, double v1, const char * d2, double v2)
References _edje_external_parsed_params_free(), _edje_part_description_find(), _edje_real_part_state_mp, _Edje_Real_Part::chosen_description, _Edje_Part::default_desc, _Edje_Real_Part_State::description, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_IMAGE, _Edje_Real_Part_State::external_params, _Edje_Part_Description_Image::image, _Edje_Real_Part::param1, _Edje_Real_Part::param2, _Edje_Real_Part::part, _Edje_Real_Part_State::set, _Edje_Real_Part::swallowed_object, _Edje_Part_Description_Spec_Image::tweens_count, and _Edje_Part::type.
Referenced by _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), and edje_object_mirrored_set().
_edje_part_description_find()
Edje_Part_Description_Common* _edje_part_description_find (Edje * ed, Edje_Real_Part * rp, const char * name, double val)
References _Edje_Part_Description_List::desc_count, _Edje_Part_Description_List::desc_rtl, edje_object_mirrored_get(), name, _Edje::obj, _Edje_Part::other, and _Edje_Real_Part::part.
Referenced by _edje_part_description_apply().
_edje_part_dragable_calc()
int _edje_part_dragable_calc (Edje *ed __UNUSED__, Edje_Real_Part * ep, FLOAT_T * x, FLOAT_T * y)
References ADD, _Edje_Real_Part_Drag::confine_to, DIV, _Edje_Real_Part::drag, _Edje_Part::dragable, FLOAT_T, FROM_INT, _Edje_Real_Part::h, _Edje_Real_Part::part, _Edje_Real_Part_Drag::tmp, _Edje_Real_Part::w, _Edje_Part_Dragable::x, _Edje_Real_Part_Drag::x, _Edje_Real_Part::x, _Edje_Part_Dragable::y, _Edje_Real_Part_Drag::y, _Edje_Real_Part::y, and ZERO.
_edje_part_pos_set()
void _edje_part_pos_set (Edje * ed, Edje_Real_Part * ep, int mode, FLOAT_T pos, FLOAT_T v1, FLOAT_T v2)
References ADD, CLAMP, COS, _Edje_Real_Part::description_pos, _Edje::dirty, DIV2, EDJE_TWEEN_MODE_ACCELERATE, EDJE_TWEEN_MODE_ACCELERATE_FACTOR, EDJE_TWEEN_MODE_BOUNCE, EDJE_TWEEN_MODE_DECELERATE, EDJE_TWEEN_MODE_DECELERATE_FACTOR, EDJE_TWEEN_MODE_DIVISOR_INTERP, EDJE_TWEEN_MODE_LINEAR, EDJE_TWEEN_MODE_MASK, EDJE_TWEEN_MODE_SINUSOIDAL, EDJE_TWEEN_MODE_SINUSOIDAL_FACTOR, EDJE_TWEEN_MODE_SPRING, FLOAT_T, FROM_DOUBLE, FROM_INT, MUL, PI, _Edje::recalc_call, SIN, SUB, TO_DOUBLE, and ZERO.
Referenced by _edje_program_end(), _edje_program_run(), and _edje_program_run_iterate().
_edje_part_recalc()
void _edje_part_recalc (Edje * ed, Edje_Real_Part * ep, int flags, Edje_Calc_Params * state)
References _edje_fetch(), _edje_recalc_do(), _Edje_Real_Part::calculated, _Edje_Real_Part::calculating, _Edje_Real_Part::chosen_description, _Edje_Real_Part_Drag::confine_to, _Edje_Real_Part_State::description, _Edje_Real_Part::description_pos, _Edje_Real_Part::drag, edje_object_scale_set(), edje_object_update_hints_get(), edje_object_update_hints_set(), EDJE_PART_TYPE_GRADIENT, EDJE_PART_TYPE_GROUP, EDJE_PART_TYPE_PROXY, ERR, FLAG_NONE, FLAG_X, FLAG_XY, FLAG_Y, FLOAT_T, FROM_DOUBLE, _Edje_Size::limit, _Edje_Part_Description_Common::min, _Edje_Part::name, _Edje_Real_Part::param1, _Edje_Real_Part::param2, _Edje_Real_Part::part, _Edje_Real_Part_State::rel1_to_x, _Edje_Real_Part_State::rel1_to_y, _Edje_Real_Part_State::rel2_to_x, _Edje_Real_Part_State::rel2_to_y, _Edje_Part::scale, _Edje::scale, _Edje::state, _Edje_Real_Part::swallowed_object, TO_DOUBLE, _Edje_Part::type, and ZERO.
Referenced by _edje_part_recalc_1(), _edje_program_run(), and _edje_recalc_do().
_edje_part_recalc_1()
void _edje_part_recalc_1 (Edje * ed, Edje_Real_Part * ep)
References _edje_part_recalc(), and FLAG_XY.
_edje_recalc()
void _edje_recalc (Edje * ed)
References _edje_freeze_calc_count, _edje_freeze_calc_list, _edje_freeze_val, _Edje::calc_only, _Edje::freeze, _Edje::freeze_calc, _Edje::obj, and _Edje::recalc.
Referenced by _edje_dragable_pos_set(), _edje_object_part_text_raw_append(), _edje_object_part_text_raw_set(), _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), _edje_thaw(), edje_object_color_class_del(), edje_object_color_class_set(), edje_object_part_text_append(), edje_object_part_text_insert(), edje_object_part_text_style_user_pop(), edje_object_part_text_style_user_push(), edje_object_size_min_restricted_calc(), edje_object_text_class_set(), and edje_object_update_hints_set().
_edje_recalc_do()
void _edje_recalc_do (Edje * ed)
References _edje_emit(), _edje_part_recalc(), _Edje::calc_only, _Edje_Real_Part::calculated, _Edje_Real_Part::calculating, _Edje_Real_Part::chosen_description, _Edje::collection, _Edje::dirty, edje_object_size_min_calc(), EDJE_PART_LIMIT_BELOW, EDJE_PART_LIMIT_OVER, EDJE_PART_LIMIT_UNKNOWN, EDJE_PART_LIMIT_ZERO, FLAG_NONE, FLAG_XY, _Edje_Real_Part::h, _Edje::have_mapped_part, _Edje_Part_Limit::height, _Edje_Part_Description_Common::limit, _Edje_Part_Collection::limits, name, _Edje::obj, _Edje_Part_Limit::part, _Edje_Part_Collection::parts, _Edje_Part_Collection::parts_count, _Edje::recalc, _Edje::recalc_call, _Edje::recalc_hints, _Edje::state, _Edje::table_parts, _Edje::table_parts_size, _Edje::update_hints, _Edje_Real_Part::w, and _Edje_Part_Limit::width.
Referenced by _edje_part_recalc(), _edje_program_run(), _edje_user_definition_free(), edje_object_calc_force(), edje_object_mirrored_set(), edje_object_part_drag_dir_get(), edje_object_part_drag_page_get(), edje_object_part_drag_size_get(), edje_object_part_drag_step_get(), edje_object_part_drag_value_get(), edje_object_part_external_object_get(), edje_object_part_geometry_get(), edje_object_part_object_get(), edje_object_part_state_get(), edje_object_part_swallow(), edje_object_part_swallow_get(), edje_object_part_text_get(), edje_object_part_text_unescaped_get(), edje_object_part_unswallow(), edje_object_parts_extends_calc(), edje_object_perspective_set(), edje_object_preload(), edje_object_size_max_get(), edje_object_size_min_restricted_calc(), edje_perspective_global_set(), and edje_perspective_set().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59