src/lib/edje_private.h File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_private.h File Reference
Data Structures
struct _Edje
struct _Edje_Aspect
struct _Edje_Aspect_Prefer
struct _Edje_Calc_Params
struct _Edje_Color
struct _Edje_Color_Class
struct _Edje_External_Directory
struct _Edje_External_Directory_Entry
struct _Edje_File
struct _Edje_Font_Directory_Entry
struct _Edje_Image_Directory
struct _Edje_Image_Directory_Entry
struct _Edje_Image_Directory_Set
struct _Edje_Image_Directory_Set_Entry
struct _Edje_Limit
struct _Edje_Markup_Filter_Callback
struct _Edje_Message
struct _Edje_Message_Signal
struct _Edje_Message_Signal_Data
struct _Edje_Multisense_Env
struct _Edje_Pack_Element
struct _Edje_Part
struct _Edje_Part_Api
struct _Edje_Part_Collection
struct _Edje_Part_Collection_Directory_Entry
struct _Edje_Part_Description_Box
struct _Edje_Part_Description_Common
struct _Edje_Part_Description_External
struct _Edje_Part_Description_Image
struct _Edje_Part_Description_List
struct _Edje_Part_Description_Proxy
struct _Edje_Part_Description_Spec_Border
struct _Edje_Part_Description_Spec_Box
struct _Edje_Part_Description_Spec_Fill
struct _Edje_Part_Description_Spec_Image
struct _Edje_Part_Description_Spec_Proxy
struct _Edje_Part_Description_Spec_Table
struct _Edje_Part_Description_Spec_Text
struct _Edje_Part_Description_Table
struct _Edje_Part_Description_Text
struct _Edje_Part_Dragable
struct _Edje_Part_Image_Id
struct _Edje_Part_Limit
struct _Edje_Patterns
struct _Edje_Pending_Program
struct _Edje_Perspective
struct _Edje_Position
struct _Edje_Position_Scale
struct _Edje_Program
struct _Edje_Program_After
struct _Edje_Program_Target
struct _Edje_Real_Part
struct _Edje_Real_Part_Drag
struct _Edje_Real_Part_Set
struct _Edje_Real_Part_State
struct _Edje_Rectangle
struct _Edje_Running_Program
struct _Edje_Signal_Callback
struct _Edje_Signal_Source_Char
struct _Edje_Signals_Sources_Patterns
struct _Edje_Size
struct _Edje_Smart_Api
struct _Edje_Sound_Directory
struct _Edje_Sound_Sample
struct _Edje_Sound_Tone
struct _Edje_String
struct _Edje_Style
struct _Edje_Style_Tag
struct _Edje_Text_Class
struct _Edje_Text_Insert_Filter_Callback
struct _Edje_Text_Style
struct _Edje_User_Defined
struct _Edje_Var
struct _Edje_Var_Animator
struct _Edje_Var_Float
struct _Edje_Var_Hash
struct _Edje_Var_Int
struct _Edje_Var_List
struct _Edje_Var_Pool
struct _Edje_Var_String
struct _Edje_Var_Timer
Macros
#define _edje_lua2_error(L, err_code) _edje_lua2_error_full(__FILE__, __FUNCTION__, __LINE__, L, err_code)
#define _edje_lua_error(L, err_code) __edje_lua_error(__FILE__, __FUNCTION__, __LINE__, L, err_code)
#define _edje_lua_panic_here() setjmp(_edje_lua_panic_jmp)
#define _GNU_SOURCE
#define ABS(x) ((x) < 0 ? -(x) : (x))
#define ADD(a, b) ((a) + (b))
#define CHKPARAM(n) if (params[0] != (sizeof(Embryo_Cell) * (n))) return -1;
#define CLAMP(x, min, max) (((x) > (max)) ? (max) : (((x) < (min)) ? (min) : (x)))
#define COS(a) cos(a)
#define CRIT(...) EINA_LOG_DOM_CRIT(_edje_default_log_dom, __VA_ARGS__)
#define DBG(...) EINA_LOG_DOM_DBG(_edje_default_log_dom, __VA_ARGS__)
#define DIV(a, b) ((a) / (b))
#define DIV2(a) ((a) / 2.0)
#define EDJE_DEFAULT_LOG_COLOR EINA_COLOR_CYAN
#define EDJE_ENTRY_CURSOR_MODE_BEFORE 1
#define EDJE_ENTRY_CURSOR_MODE_UNDER 0
#define EDJE_ENTRY_EDIT_MODE_EDITABLE 2
#define EDJE_ENTRY_EDIT_MODE_NONE 0
#define EDJE_ENTRY_EDIT_MODE_PASSWORD 3
#define EDJE_ENTRY_EDIT_MODE_SELECTABLE 1
#define EDJE_ENTRY_SELECTION_MODE_DEFAULT 0
#define EDJE_ENTRY_SELECTION_MODE_EXPLICIT 1
#define EDJE_FILE_MINOR 4
#define EDJE_FILE_VERSION 3
#define EDJE_IMAGE_SOURCE_TYPE_EXTERNAL 3
#define EDJE_IMAGE_SOURCE_TYPE_INLINE_LOSSY 2
#define EDJE_IMAGE_SOURCE_TYPE_INLINE_PERFECT 1
#define EDJE_IMAGE_SOURCE_TYPE_LAST 4
#define EDJE_IMAGE_SOURCE_TYPE_NONE 0
#define EDJE_INF_MAX_H 100000
#define EDJE_INF_MAX_W 100000
#define EDJE_ORIENTATION_AUTO 0
#define EDJE_ORIENTATION_LTR 1
#define EDJE_ORIENTATION_RTL 2
#define EDJE_PART_PATH_SEPARATOR ':'
#define EDJE_PART_PATH_SEPARATOR_INDEXL '['
#define EDJE_PART_PATH_SEPARATOR_INDEXR ']'
#define EDJE_PART_PATH_SEPARATOR_STRING ":"
#define EDJE_SMART_API_INIT(smart_class_init) {smart_class_init, EDJE_SMART_API_VERSION, NULL}
#define EDJE_SMART_API_INIT_NAME_VERSION(name) EDJE_SMART_API_INIT(EVAS_SMART_CLASS_INIT_NAME_VERSION(name))
#define EDJE_SMART_API_INIT_NULL EDJE_SMART_API_INIT(EVAS_SMART_CLASS_INIT_NULL)
#define EDJE_SMART_API_INIT_VERSION EDJE_SMART_API_INIT(EVAS_SMART_CLASS_INIT_VERSION)
#define EDJE_SMART_API_VERSION 1
#define EDJE_SOUND_SOURCE_TYPE_INLINE_AS_IS 4
#define EDJE_SOUND_SOURCE_TYPE_INLINE_COMP 2
#define EDJE_SOUND_SOURCE_TYPE_INLINE_LOSSY 3
#define EDJE_SOUND_SOURCE_TYPE_INLINE_RAW 1
#define EDJE_SOUND_SOURCE_TYPE_NONE 0
#define EDJE_STATE_PARAM_ALIGNMENT 1
#define EDJE_STATE_PARAM_ASPECT 5
#define EDJE_STATE_PARAM_ASPECT_PREF 6
#define EDJE_STATE_PARAM_BORDER 18
#define EDJE_STATE_PARAM_COLOR 7
#define EDJE_STATE_PARAM_COLOR2 8
#define EDJE_STATE_PARAM_COLOR3 9
#define EDJE_STATE_PARAM_COLOR_CLASS 10
#define EDJE_STATE_PARAM_FILL_POS 20
#define EDJE_STATE_PARAM_FILL_SIZE 21
#define EDJE_STATE_PARAM_FILL_SMOOTH 19
#define EDJE_STATE_PARAM_IMAGE 17
#define EDJE_STATE_PARAM_LAST 43
#define EDJE_STATE_PARAM_MAP_BACK_CULL 39
#define EDJE_STATE_PARAM_MAP_LIGNT 34
#define EDJE_STATE_PARAM_MAP_OM 32
#define EDJE_STATE_PARAM_MAP_PERSP 33
#define EDJE_STATE_PARAM_MAP_PERSP_ON 40
#define EDJE_STATE_PARAM_MAP_ROT_CENTER 35
#define EDJE_STATE_PARAM_MAP_ROT_X 36
#define EDJE_STATE_PARAM_MAP_ROT_Y 37
#define EDJE_STATE_PARAM_MAP_ROT_Z 38
#define EDJE_STATE_PARAM_MAX 3
#define EDJE_STATE_PARAM_MIN 2
#define EDJE_STATE_PARAM_NONE 0
#define EDJE_STATE_PARAM_PERSP_FOCAL 42
#define EDJE_STATE_PARAM_PERSP_ZPLANE 41
#define EDJE_STATE_PARAM_REL1 11
#define EDJE_STATE_PARAM_REL1_OFFSET 13
#define EDJE_STATE_PARAM_REL1_TO 12
#define EDJE_STATE_PARAM_REL2 14
#define EDJE_STATE_PARAM_REL2_OFFSET 16
#define EDJE_STATE_PARAM_REL2_TO 15
#define EDJE_STATE_PARAM_STEP 4
#define EDJE_STATE_PARAM_TEXT 22
#define EDJE_STATE_PARAM_TEXT_ALIGN 30
#define EDJE_STATE_PARAM_TEXT_CLASS 23
#define EDJE_STATE_PARAM_TEXT_FIT 27
#define EDJE_STATE_PARAM_TEXT_FONT 24
#define EDJE_STATE_PARAM_TEXT_MAX 29
#define EDJE_STATE_PARAM_TEXT_MIN 28
#define EDJE_STATE_PARAM_TEXT_SIZE 26
#define EDJE_STATE_PARAM_TEXT_STYLE 25
#define EDJE_STATE_PARAM_VISIBLE 31
#define EDJE_T_FLOAT EET_T_DOUBLE
#define EDJE_VAR_FLOAT 2
#define EDJE_VAR_HASH 5
#define EDJE_VAR_INT 1
#define EDJE_VAR_LIST 4
#define EDJE_VAR_MAGIC_BASE 0x12fe84ba
#define EDJE_VAR_NONE 0
#define EDJE_VAR_STRING 3
#define ERR(...) EINA_LOG_DOM_ERR(_edje_default_log_dom, __VA_ARGS__)
#define FLAG_NONE 0
#define FLAG_X 0x01
#define FLAG_XY (FLAG_X | FLAG_Y)
#define FLAG_Y 0x02
#define FLOAT_T double
#define FROM_DOUBLE(a) (a)
#define FROM_INT(a) (double)(a)
#define GETFLOAT(val, par)
#define GETFLOAT_T(val, par)
#define GETINT(val, par)
#define GETSTR(str, par)
#define GETSTREVAS(str, par)
#define HASNPARAMS(n) (params[0] == (sizeof(Embryo_Cell) * (n)))
#define INF(...) EINA_LOG_DOM_INFO(_edje_default_log_dom, __VA_ARGS__)
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
#define MUL(a, b) ((a) * (b))
#define PART_TYPE_FIELDS(TYPE)
#define PI 3.14159265358979323846
#define SCALE(a, b) ((a) * (double)(b))
#define SETFLOAT(val, par)
#define SETFLOAT_T(val, par)
#define SETINT(val, par)
#define SETSTR(str, par)
#define SETSTRALLOCATE(s)
#define SIN(a) sin(a)
#define SQRT(a) sqrt(a)
#define SUB(a, b) ((a) - (b))
#define TO_DOUBLE(a) (double)(a)
#define TO_INT(a) (int)(a)
#define WRN(...) EINA_LOG_DOM_WARN(_edje_default_log_dom, __VA_ARGS__)
#define ZERO 0.0
Typedefs
typedef struct _Edje Edje
typedef struct _Edje_Position_Scale Edje_Alignment
typedef struct _Edje_Aspect Edje_Aspect
typedef struct _Edje_Aspect_Prefer Edje_Aspect_Prefer
typedef struct _Edje_Calc_Params Edje_Calc_Params
typedef struct _Edje_Color Edje_Color
typedef struct _Edje_Color_Class Edje_Color_Class
typedef struct _Edje_External_Directory Edje_External_Directory
typedef struct _Edje_External_Directory_Entry Edje_External_Directory_Entry
typedef struct _Edje_File Edje_File
typedef enum _Edje_Fill Edje_Fill
typedef struct _Edje_Font_Directory_Entry Edje_Font_Directory_Entry
typedef struct _Edje_Image_Directory Edje_Image_Directory
typedef struct _Edje_Image_Directory_Entry Edje_Image_Directory_Entry
typedef struct _Edje_Image_Directory_Set Edje_Image_Directory_Set
typedef struct _Edje_Image_Directory_Set_Entry Edje_Image_Directory_Set_Entry
typedef struct _Edje_Limit Edje_Limit
typedef struct _Edje_Markup_Filter_Callback Edje_Markup_Filter_Callback
typedef enum _Edje_Match_Error Edje_Match_Error
typedef struct _Edje_Message Edje_Message
typedef struct _Edje_Message_Signal Edje_Message_Signal
typedef struct _Edje_Message_Signal_Data Edje_Message_Signal_Data
typedef struct _Edje_Multisense_Env Edje_Multisense_Env
typedef struct _Edje_Pack_Element Edje_Pack_Element
typedef struct _Edje_Part Edje_Part
typedef struct _Edje_Part_Api Edje_Part_Api
typedef struct _Edje_Part_Box_Animation Edje_Part_Box_Animation
typedef struct _Edje_Part_Collection Edje_Part_Collection
typedef struct _Edje_Part_Collection_Directory_Entry Edje_Part_Collection_Directory_Entry
typedef struct _Edje_Part_Description_Box Edje_Part_Description_Box
typedef struct _Edje_Part_Description_Common Edje_Part_Description_Common
typedef struct _Edje_Part_Description_External Edje_Part_Description_External
typedef struct _Edje_Part_Description_Image Edje_Part_Description_Image
typedef struct _Edje_Part_Description_List Edje_Part_Description_List
typedef struct _Edje_Part_Description_Proxy Edje_Part_Description_Proxy
typedef struct _Edje_Part_Description_Spec_Border Edje_Part_Description_Spec_Border
typedef struct _Edje_Part_Description_Spec_Box Edje_Part_Description_Spec_Box
typedef struct _Edje_Part_Description_Spec_Fill Edje_Part_Description_Spec_Fill
typedef struct _Edje_Part_Description_Spec_Image Edje_Part_Description_Spec_Image
typedef struct _Edje_Part_Description_Spec_Proxy Edje_Part_Description_Spec_Proxy
typedef struct _Edje_Part_Description_Spec_Table Edje_Part_Description_Spec_Table
typedef struct _Edje_Part_Description_Spec_Text Edje_Part_Description_Spec_Text
typedef struct _Edje_Part_Description_Table Edje_Part_Description_Table
typedef struct _Edje_Part_Description_Text Edje_Part_Description_Text
typedef struct _Edje_Part_Dragable Edje_Part_Dragable
typedef struct _Edje_Part_Image_Id Edje_Part_Image_Id
typedef struct _Edje_Part_Limit Edje_Part_Limit
typedef struct _Edje_Patterns Edje_Patterns
typedef struct _Edje_Pending_Program Edje_Pending_Program
typedef struct _Edje_Position Edje_Position
typedef struct _Edje_Position_Scale Edje_Position_Scale
typedef struct _Edje_Program Edje_Program
typedef struct _Edje_Program_After Edje_Program_After
typedef struct _Edje_Program_Target Edje_Program_Target
typedef enum _Edje_Queue Edje_Queue
typedef struct _Edje_Real_Part Edje_Real_Part
typedef struct _Edje_Real_Part_Drag Edje_Real_Part_Drag
typedef struct _Edje_Real_Part_Set Edje_Real_Part_Set
typedef struct _Edje_Real_Part_State Edje_Real_Part_State
typedef struct _Edje_Rectangle Edje_Rectangle
typedef struct _Edje_Running_Program Edje_Running_Program
typedef struct _Edje_Signal_Callback Edje_Signal_Callback
typedef struct _Edje_Signal_Source_Char Edje_Signal_Source_Char
typedef struct _Edje_Signals_Sources_Patterns Edje_Signals_Sources_Patterns
typedef struct _Edje_Size Edje_Size
typedef struct _Edje_Smart_Api Edje_Smart_Api
typedef struct _Edje_Sound_Directory Edje_Sound_Directory
typedef struct _Edje_Sound_Sample Edje_Sound_Sample
typedef struct _Edje_Sound_Tone Edje_Sound_Tone
typedef struct _Edje_States Edje_States
typedef struct _Edje_String Edje_String
typedef struct _Edje_Style Edje_Style
typedef struct _Edje_Style_Tag Edje_Style_Tag
typedef struct _Edje_Text_Class Edje_Text_Class
typedef struct _Edje_Text_Insert_Filter_Callback Edje_Text_Insert_Filter_Callback
typedef struct _Edje_Text_Style Edje_Text_Style
typedef struct _Edje_User_Defined Edje_User_Defined
typedef enum _Edje_User_Defined_Type Edje_User_Defined_Type
typedef struct _Edje_Var Edje_Var
typedef struct _Edje_Var_Animator Edje_Var_Animator
typedef struct _Edje_Var_Float Edje_Var_Float
typedef struct _Edje_Var_Hash Edje_Var_Hash
typedef struct _Edje_Var_Int Edje_Var_Int
typedef struct _Edje_Var_List Edje_Var_List
typedef struct _Edje_Var_Pool Edje_Var_Pool
typedef struct _Edje_Var_String Edje_Var_String
typedef struct _Edje_Var_Timer Edje_Var_Timer
typedef Eina_Bool(* MULTISENSE_FACTORY_INIT_FUNC) (Edje_Multisense_Env *)
Enumerations
enum _Edje_Fill { EDJE_FILL_TYPE_SCALE = 0 , EDJE_FILL_TYPE_TILE }
enum _Edje_Match_Error { EDJE_MATCH_OK , EDJE_MATCH_ALLOC_ERROR , EDJE_MATCH_SYNTAX_ERROR }
enum _Edje_Queue { EDJE_QUEUE_APP , EDJE_QUEUE_SCRIPT }
enum _Edje_User_Defined_Type {
EDJE_USER_SWALLOW , EDJE_USER_BOX_PACK , EDJE_USER_TABLE_PACK , EDJE_USER_STRING ,
EDJE_USER_DRAG_STEP , EDJE_USER_DRAG_PAGE , EDJE_USER_DRAG_VALUE , EDJE_USER_DRAG_SIZE
}
enum Edje_Internal_Aspect {
EDJE_ASPECT_PREFER_NONE , EDJE_ASPECT_PREFER_VERTICAL , EDJE_ASPECT_PREFER_HORIZONTAL , EDJE_ASPECT_PREFER_BOTH ,
EDJE_ASPECT_PREFER_SOURCE
}
enum Edje_Part_Limit_State { EDJE_PART_LIMIT_UNKNOWN = 0 , EDJE_PART_LIMIT_BELOW , EDJE_PART_LIMIT_ZERO , EDJE_PART_LIMIT_OVER }
Functions
void __edje_lua_error (const char *file, const char *fnc, int line, lua_State *L, int err_code)
int _edje_block (Edje *ed)
int _edje_block_break (Edje *ed)
void _edje_block_violate (Edje *ed)
void _edje_box_init (void)
Eina_Bool _edje_box_layout_add_child (Edje_Real_Part *rp, Evas_Object *child_obj)
Edje_Part_Box_Animation * _edje_box_layout_anim_new (Evas_Object *box)
Eina_Bool _edje_box_layout_find (const char *name, Evas_Object_Box_Layout *cb, void **data, void(**free_data)(void *data))
void _edje_box_layout_free_data (void *data)
void _edje_box_layout_remove_child (Edje_Real_Part *rp, Evas_Object *child_obj)
void _edje_box_recalc_apply (Edje *ed __UNUSED__, Edje_Real_Part *ep, Edje_Calc_Params *p3, Edje_Part_Description_Box *chosen_desc)
void _edje_box_shutdown (void)
void _edje_cache_coll_clean (Edje_File *edf)
void _edje_cache_coll_flush (Edje_File *edf)
void _edje_cache_coll_unref (Edje_File *edf, Edje_Part_Collection *edc)
Edje_File * _edje_cache_file_coll_open (const char *file, const char *coll, int *error_ret, Edje_Part_Collection **edc_ret, Edje *ed)
void _edje_cache_file_unref (Edje_File *edf)
void _edje_callbacks_add (Evas_Object *obj, Edje *ed, Edje_Real_Part *rp)
void _edje_callbacks_del (Evas_Object *obj, Edje *ed)
void _edje_callbacks_focus_add (Evas_Object *obj, Edje *ed, Edje_Real_Part *rp)
void _edje_callbacks_focus_del (Evas_Object *obj, Edje *ed)
void _edje_callbacks_patterns_clean (Edje *ed)
Evas_Object * _edje_children_get (Edje_Real_Part *rp, const char *partid)
void _edje_clean_objects (Edje *ed)
void _edje_collection_free (Edje_File *edf, Edje_Part_Collection *ec, Edje_Part_Collection_Directory_Entry *ce)
void _edje_collection_free_part_description_clean (int type, Edje_Part_Description_Common *desc, Eina_Bool free_strings)
void _edje_collection_free_part_description_free (int type, Edje_Part_Description_Common *desc, Edje_Part_Collection_Directory_Entry *ce, Eina_Bool free_strings)
Edje_Color_Class * _edje_color_class_find (Edje *ed, const char *color_class)
void _edje_color_class_hash_free (void)
void _edje_color_class_member_add (Edje *ed, const char *color_class)
void _edje_color_class_member_del (Edje *ed, const char *color_class)
void _edje_color_class_member_direct_del (const char *color_class, void *lookup)
void _edje_color_class_members_free (void)
void _edje_color_class_on_del (Edje *ed, Edje_Part *ep)
void _edje_del (Edje *ed)
void _edje_dragable_pos_set (Edje *ed, Edje_Real_Part *ep, FLOAT_T x, FLOAT_T y)
EAPI void _edje_edd_init (void)
EAPI void _edje_edd_shutdown (void)
void _edje_embryo_globals_init (Edje *ed)
void _edje_embryo_script_init (Edje_Part_Collection *edc)
void _edje_embryo_script_reset (Edje *ed)
void _edje_embryo_script_shutdown (Edje_Part_Collection *edc)
void _edje_embryo_test_run (Edje *ed, const char *fname, const char *sig, const char *src)
void _edje_emit (Edje *ed, const char *sig, const char *src)
void _edje_emit_full (Edje *ed, const char *sig, const char *src, void *data, void(*free_func)(void *))
void _edje_emit_handle (Edje *ed, const char *sig, const char *src, Edje_Message_Signal_Data *data, Eina_Bool prop)
const Eina_List * _edje_entry_anchor_geometry_get (Edje_Real_Part *rp, const char *anchor)
const Eina_List * _edje_entry_anchors_list (Edje_Real_Part *rp)
Edje_Text_Autocapital_Type _edje_entry_autocapital_type_get (Edje_Real_Part *rp)
void _edje_entry_autocapital_type_set (Edje_Real_Part *rp, Edje_Text_Autocapital_Type autocapital_type)
void _edje_entry_cursor_begin (Edje_Real_Part *rp, Edje_Cursor cur)
char * _edje_entry_cursor_content_get (Edje_Real_Part *rp, Edje_Cursor cur)
Eina_Bool _edje_entry_cursor_coord_set (Edje_Real_Part *rp, Edje_Cursor cur, int x, int y)
void _edje_entry_cursor_copy (Edje_Real_Part *rp, Edje_Cursor cur, Edje_Cursor dst)
Eina_Bool _edje_entry_cursor_down (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_end (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_geometry_get (Edje_Real_Part *rp, Evas_Coord *cx, Evas_Coord *cy, Evas_Coord *cw, Evas_Coord *ch)
Eina_Bool _edje_entry_cursor_is_format_get (Edje_Real_Part *rp, Edje_Cursor cur)
Eina_Bool _edje_entry_cursor_is_visible_format_get (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_line_begin (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_line_end (Edje_Real_Part *rp, Edje_Cursor cur)
Eina_Bool _edje_entry_cursor_next (Edje_Real_Part *rp, Edje_Cursor cur)
int _edje_entry_cursor_pos_get (Edje_Real_Part *rp, Edje_Cursor cur)
void _edje_entry_cursor_pos_set (Edje_Real_Part *rp, Edje_Cursor cur, int pos)
Eina_Bool _edje_entry_cursor_prev (Edje_Real_Part *rp, Edje_Cursor cur)
Eina_Bool _edje_entry_cursor_up (Edje_Real_Part *rp, Edje_Cursor cur)
void * _edje_entry_imf_context_get (Edje_Real_Part *rp)
void _edje_entry_imf_context_reset (Edje_Real_Part *rp)
void _edje_entry_init (Edje *ed)
Eina_Bool _edje_entry_input_panel_enabled_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_enabled_set (Edje_Real_Part *rp, Eina_Bool enabled)
void _edje_entry_input_panel_hide (Edje_Real_Part *rp)
void _edje_entry_input_panel_imdata_get (Edje_Real_Part *rp, void *data, int *len)
void _edje_entry_input_panel_imdata_set (Edje_Real_Part *rp, const void *data, int len)
Edje_Input_Panel_Lang _edje_entry_input_panel_language_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_language_set (Edje_Real_Part *rp, Edje_Input_Panel_Lang lang)
Edje_Input_Panel_Layout _edje_entry_input_panel_layout_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_layout_set (Edje_Real_Part *rp, Edje_Input_Panel_Layout layout)
Eina_Bool _edje_entry_input_panel_return_key_disabled_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_return_key_disabled_set (Edje_Real_Part *rp, Eina_Bool disabled)
Edje_Input_Panel_Return_Key_Type _edje_entry_input_panel_return_key_type_get (Edje_Real_Part *rp)
void _edje_entry_input_panel_return_key_type_set (Edje_Real_Part *rp, Edje_Input_Panel_Return_Key_Type return_key_type)
void _edje_entry_input_panel_show (Edje_Real_Part *rp)
Eina_Bool _edje_entry_item_geometry_get (Edje_Real_Part *rp, const char *item, Evas_Coord *cx, Evas_Coord *cy, Evas_Coord *cw, Evas_Coord *ch)
const Eina_List * _edje_entry_items_list (Edje_Real_Part *rp)
Eina_Bool _edje_entry_prediction_allow_get (Edje_Real_Part *rp)
void _edje_entry_prediction_allow_set (Edje_Real_Part *rp, Eina_Bool prediction)
void _edje_entry_real_part_configure (Edje_Real_Part *rp)
void _edje_entry_real_part_init (Edje_Real_Part *rp)
void _edje_entry_real_part_shutdown (Edje_Real_Part *rp)
void _edje_entry_select_abort (Edje_Real_Part *rp)
void _edje_entry_select_all (Edje_Real_Part *rp)
Eina_Bool _edje_entry_select_allow_get (const Edje_Real_Part *rp)
void _edje_entry_select_allow_set (Edje_Real_Part *rp, Eina_Bool allow)
void _edje_entry_select_begin (Edje_Real_Part *rp)
void _edje_entry_select_extend (Edje_Real_Part *rp)
void _edje_entry_select_none (Edje_Real_Part *rp)
const char * _edje_entry_selection_get (Edje_Real_Part *rp)
void _edje_entry_set_cursor_end (Edje_Real_Part *rp)
void _edje_entry_set_cursor_start (Edje_Real_Part *rp)
void _edje_entry_shutdown (Edje *ed)
const char * _edje_entry_text_get (Edje_Real_Part *rp)
void _edje_entry_text_markup_append (Edje_Real_Part *rp, const char *text)
void _edje_entry_text_markup_insert (Edje_Real_Part *rp, const char *text)
void _edje_entry_text_markup_set (Edje_Real_Part *rp, const char *text)
void _edje_entry_user_insert (Edje_Real_Part *rp, const char *text)
Evas_Object * _edje_external_content_get (const Evas_Object *obj, const char *content) EINA_ARG_NONNULL(1
void _edje_external_init ()
Eina_Bool _edje_external_param_get (const Evas_Object *obj, Edje_Real_Part *rp, Edje_External_Param *param) EINA_ARG_NONNULL(2)
Eina_Bool _edje_external_param_set (Evas_Object *obj, Edje_Real_Part *rp, const Edje_External_Param *param) EINA_ARG_NONNULL(2)
Evas_Object void _edje_external_params_free (Eina_List *params, Eina_Bool free_strings)
void * _edje_external_params_parse (Evas_Object *obj, const Eina_List *params)
void _edje_external_parsed_params_free (Evas_Object *obj, void *params)
void _edje_external_recalc_apply (Edje *ed, Edje_Real_Part *ep, Edje_Calc_Params *params, Edje_Part_Description_Common *chosen_desc)
void _edje_external_shutdown ()
void _edje_external_signal_emit (Evas_Object *obj, const char *emission, const char *source)
Evas_Object * _edje_external_type_add (const char *type_name, Evas *evas, Evas_Object *parent, const Eina_List *params, const char *part_name)
Edje * _edje_fetch (const Evas_Object *obj) EINA_PURE
void _edje_file_add (Edje *ed)
void _edje_file_cache_shutdown (void)
void _edje_file_del (Edje *ed)
void _edje_file_free (Edje_File *edf)
int _edje_freeze (Edje *ed)
void _edje_lib_ref (void)
void _edje_lib_unref (void)
void _edje_lua2_error_full (const char *file, const char *fnc, int line, lua_State *L, int err_code)
void _edje_lua2_script_func_hide (Edje *ed)
void _edje_lua2_script_func_message (Edje *ed, Edje_Message *em)
void _edje_lua2_script_func_move (Edje *ed)
void _edje_lua2_script_func_resize (Edje *ed)
void _edje_lua2_script_func_show (Edje *ed)
void _edje_lua2_script_func_shutdown (Edje *ed)
void _edje_lua2_script_func_signal (Edje *ed, const char *sig, const char *src)
void _edje_lua2_script_init (Edje *ed)
void _edje_lua2_script_load (Edje_Part_Collection *edc, void *data, int size)
void _edje_lua2_script_shutdown (Edje *ed)
void _edje_lua2_script_unload (Edje_Part_Collection *edc)
void _edje_lua_free_reg (lua_State *L, void *ptr)
void _edje_lua_free_thread (Edje *ed, lua_State *L)
void _edje_lua_get_reg (lua_State *L, void *ptr)
void _edje_lua_group_fn_new (Edje *ed)
void _edje_lua_init ()
void _edje_lua_new_reg (lua_State *L, int index, void *ptr)
lua_State * _edje_lua_new_thread (Edje *ed, lua_State *L)
void _edje_lua_script_fn_new (Edje *ed)
Eina_Bool _edje_lua_script_only (Edje *ed)
void _edje_lua_script_only_hide (Edje *ed)
void _edje_lua_script_only_init (Edje *ed)
void _edje_lua_script_only_message (Edje *ed, Edje_Message *em)
void _edje_lua_script_only_move (Edje *ed)
void _edje_lua_script_only_resize (Edje *ed)
void _edje_lua_script_only_show (Edje *ed)
void _edje_lua_script_only_shutdown (Edje *ed)
void _edje_lua_shutdown ()
lua_State * _edje_lua_state_get ()
void _edje_message_cb_set (Edje *ed, void(*func)(void *data, Evas_Object *obj, Edje_Message_Type type, int id, void *msg), void *data)
void _edje_message_del (Edje *ed)
void _edje_message_free (Edje_Message *em)
void _edje_message_init (void)
Edje_Message * _edje_message_new (Edje *ed, Edje_Queue queue, Edje_Message_Type type, int id)
void _edje_message_parameters_push (Edje_Message *em)
void _edje_message_process (Edje_Message *em)
void _edje_message_propornot_send (Edje *ed, Edje_Queue queue, Edje_Message_Type type, int id, void *emsg, Eina_Bool prop)
void _edje_message_queue_clear (void)
void _edje_message_queue_process (void)
void _edje_message_send (Edje *ed, Edje_Queue queue, Edje_Message_Type type, int id, void *emsg)
void _edje_message_shutdown (void)
Eina_Module * _edje_module_handle_load (const char *module)
void _edje_module_init ()
void _edje_module_shutdown ()
void _edje_multisense_init (void)
Eina_Bool _edje_multisense_internal_sound_sample_play (Edje *ed, const char *sample_name, const double speed)
Eina_Bool _edje_multisense_internal_sound_tone_play (Edje *ed, const char *tone_name, const double duration)
void _edje_multisense_shutdown (void)
int _edje_object_file_set_internal (Evas_Object *obj, const char *file, const char *group, const char *parent, Eina_List *group_path)
void _edje_object_orientation_inform (Evas_Object *obj)
void _edje_object_part_swallow_changed_hints_cb (void *data, Evas *e, Evas_Object *obj, void *event_info)
void _edje_object_part_swallow_free_cb (void *data, Evas *e, Evas_Object *obj, void *event_info)
Eina_Bool _edje_object_part_text_raw_set (Evas_Object *obj, Edje_Real_Part *rp, const char *part, const char *text)
const Edje_Smart_Api * _edje_object_smart_class_get (void)
void _edje_object_smart_set (Edje_Smart_Api *sc)
void _edje_part_description_apply (Edje *ed, Edje_Real_Part *ep, const char *d1, double v1, const char *d2, double v2)
Edje_Part_Description_Common * _edje_part_description_find (Edje *ed, Edje_Real_Part *rp, const char *name, double val)
int _edje_part_dragable_calc (Edje *ed, Edje_Real_Part *ep, FLOAT_T *x, FLOAT_T *y)
void _edje_part_pos_set (Edje *ed, Edje_Real_Part *ep, int mode, FLOAT_T pos, FLOAT_T v1, FLOAT_T v2)
void _edje_part_recalc (Edje *ed, Edje_Real_Part *ep, int flags, Edje_Calc_Params *state)
void _edje_part_recalc_1 (Edje *ed, Edje_Real_Part *ep)
Eina_Bool _edje_pending_timer_cb (void *data)
void _edje_program_end (Edje *ed, Edje_Running_Program *runp)
EAPI void _edje_program_insert (Edje_Part_Collection *ed, Edje_Program *p)
EAPI void _edje_program_remove (Edje_Part_Collection *ed, Edje_Program *p)
void _edje_program_run (Edje *ed, Edje_Program *pr, Eina_Bool force, const char *ssig, const char *ssrc)
Eina_Bool _edje_program_run_iterate (Edje_Running_Program *runp, double tim)
void _edje_programs_patterns_clean (Edje *ed)
void _edje_programs_patterns_init (Edje *ed)
Eina_Bool _edje_real_part_box_append (Edje_Real_Part *rp, Evas_Object *child_obj)
Eina_Bool _edje_real_part_box_insert_at (Edje_Real_Part *rp, Evas_Object *child_obj, unsigned int pos)
Eina_Bool _edje_real_part_box_insert_before (Edje_Real_Part *rp, Evas_Object *child_obj, const Evas_Object *ref)
Eina_Bool _edje_real_part_box_prepend (Edje_Real_Part *rp, Evas_Object *child_obj)
Evas_Object * _edje_real_part_box_remove (Edje_Real_Part *rp, Evas_Object *child_obj)
Eina_Bool _edje_real_part_box_remove_all (Edje_Real_Part *rp, Eina_Bool clear)
Evas_Object * _edje_real_part_box_remove_at (Edje_Real_Part *rp, unsigned int pos)
Edje_Real_Part * _edje_real_part_get (const Edje *ed, const char *part)
Edje_Real_Part * _edje_real_part_recursive_get (const Edje *ed, const char *part)
void _edje_real_part_swallow (Edje_Real_Part *rp, Evas_Object *obj_swallow, Eina_Bool hints_update)
void _edje_real_part_swallow_clear (Edje_Real_Part *rp)
void _edje_real_part_table_clear (Edje_Real_Part *rp, Eina_Bool clear)
Eina_Bool _edje_real_part_table_pack (Edje_Real_Part *rp, Evas_Object *child_obj, unsigned short col, unsigned short row, unsigned short colspan, unsigned short rowspan)
Eina_Bool _edje_real_part_table_unpack (Edje_Real_Part *rp, Evas_Object *child_obj)
void _edje_recalc (Edje *ed)
void _edje_recalc_do (Edje *ed)
void _edje_ref (Edje *ed)
Eina_Bool _edje_script_only (Edje *ed)
void _edje_script_only_hide (Edje *ed)
void _edje_script_only_init (Edje *ed)
void _edje_script_only_message (Edje *ed, Edje_Message *em)
void _edje_script_only_move (Edje *ed)
void _edje_script_only_resize (Edje *ed)
void _edje_script_only_show (Edje *ed)
void _edje_script_only_shutdown (Edje *ed)
void _edje_signals_sources_patterns_clean (Edje_Signals_Sources_Patterns *ssp)
void _edje_subobj_register (Edje *ed, Evas_Object *ob)
void _edje_subobj_unregister (Edje *ed, Evas_Object *ob)
Edje_Text_Class * _edje_text_class_find (Edje *ed, const char *text_class)
const char * _edje_text_class_font_get (Edje *ed, Edje_Part_Description_Text *chosen_desc, int *size, char **free_later)
void _edje_text_class_hash_free (void)
void _edje_text_class_member_add (Edje *ed, const char *text_class)
void _edje_text_class_member_del (Edje *ed, const char *text_class)
void _edje_text_class_member_direct_del (const char *text_class, void *lookup)
void _edje_text_class_members_free (void)
char * _edje_text_escape (const char *text)
void _edje_text_init (void)
void _edje_text_part_on_add (Edje *ed, Edje_Real_Part *ep)
void _edje_text_part_on_del (Edje *ed, Edje_Part *ep)
void _edje_text_recalc_apply (Edje *ed, Edje_Real_Part *ep, Edje_Calc_Params *params, Edje_Part_Description_Text *chosen_desc)
Evas_Font_Size _edje_text_size_calc (Evas_Font_Size size, Edje_Text_Class *tc)
char * _edje_text_unescape (const char *text)
void _edje_textblock_style_all_update (Edje *ed)
void _edje_textblock_style_cleanup (Edje_File *edf)
void _edje_textblock_style_parse_and_fix (Edje_File *edf)
void _edje_textblock_styles_add (Edje *ed)
void _edje_textblock_styles_del (Edje *ed)
int _edje_thaw (Edje *ed)
Eina_Bool _edje_timer_cb (void *data)
int _edje_unblock (Edje *ed)
void _edje_unref (Edje *ed)
void _edje_user_definition_free (Edje_User_Defined *eud)
void _edje_user_definition_remove (Edje_User_Defined *eud, Evas_Object *child)
int _edje_var_anim_add (Edje *ed, double len, const char *fname, int val)
void _edje_var_anim_del (Edje *ed, int id)
double _edje_var_float_get (Edje *ed, int id)
void _edje_var_float_set (Edje *ed, int id, double v)
void _edje_var_free (Edje_Var *var)
void _edje_var_init (Edje *ed)
int _edje_var_int_get (Edje *ed, int id)
void _edje_var_int_set (Edje *ed, int id, int v)
int _edje_var_list_count_get (Edje *ed, int id)
void _edje_var_list_float_append (Edje *ed, int id, double v)
void _edje_var_list_float_insert (Edje *ed, int id, int n, double v)
void _edje_var_list_float_prepend (Edje *ed, int id, double v)
void _edje_var_list_int_append (Edje *ed, int id, int v)
void _edje_var_list_int_insert (Edje *ed, int id, int n, int v)
void _edje_var_list_int_prepend (Edje *ed, int id, int v)
Edje_Var * _edje_var_list_nth (Edje *ed, int id, int n)
double _edje_var_list_nth_float_get (Edje *ed, int id, int n)
void _edje_var_list_nth_float_set (Edje *ed, int id, int n, double v)
int _edje_var_list_nth_int_get (Edje *ed, int id, int n)
void _edje_var_list_nth_int_set (Edje *ed, int id, int n, int v)
const char * _edje_var_list_nth_str_get (Edje *ed, int id, int n)
void _edje_var_list_nth_str_set (Edje *ed, int id, int n, const char *v)
void _edje_var_list_remove_nth (Edje *ed, int id, int n)
void _edje_var_list_str_append (Edje *ed, int id, const char *v)
void _edje_var_list_str_insert (Edje *ed, int id, int n, const char *v)
void _edje_var_list_str_prepend (Edje *ed, int id, const char *v)
void _edje_var_list_var_append (Edje *ed, int id, Edje_Var *var)
void _edje_var_list_var_append_relative (Edje *ed, int id, Edje_Var *var, Edje_Var *relative)
void _edje_var_list_var_prepend (Edje *ed, int id, Edje_Var *var)
void _edje_var_list_var_prepend_relative (Edje *ed, int id, Edje_Var *var, Edje_Var *relative)
Edje_Var * _edje_var_new (void)
void _edje_var_shutdown (Edje *ed)
const char * _edje_var_str_get (Edje *ed, int id)
void _edje_var_str_set (Edje *ed, int id, const char *str)
int _edje_var_string_id_get (Edje *ed, const char *string)
int _edje_var_timer_add (Edje *ed, double in, const char *fname, int val)
void _edje_var_timer_del (Edje *ed, int id)
double _edje_var_var_float_get (Edje *ed, Edje_Var *var)
void _edje_var_var_float_set (Edje *ed, Edje_Var *var, double v)
int _edje_var_var_int_get (Edje *ed, Edje_Var *var)
void _edje_var_var_int_set (Edje *ed, Edje_Var *var, int v)
const char * _edje_var_var_str_get (Edje *ed, Edje_Var *var)
void _edje_var_var_str_set (Edje *ed, Edje_Var *var, const char *str)
void * alloca (size_t)
int edje_match_callback_exec (Edje_Patterns *ppat_signal, Edje_Patterns *ppat_source, const char *signal, const char *source, Eina_List *callbacks, Edje *ed, Eina_Bool prop)
Eina_List * edje_match_callback_hash_build (const Eina_List *callbacks, Eina_Rbtree **tree)
Edje_Patterns * edje_match_callback_signal_init (const Eina_List *lst)
Edje_Patterns * edje_match_callback_source_init (const Eina_List *lst)
Eina_Bool edje_match_collection_dir_exec (const Edje_Patterns *ppat, const char *string)
Edje_Patterns * edje_match_collection_dir_init (const Eina_List *lst)
void edje_match_patterns_free (Edje_Patterns *ppat)
Eina_List * edje_match_program_hash_build (Edje_Program *const *programs, unsigned int count, Eina_Rbtree **tree)
Eina_Bool edje_match_programs_exec (const Edje_Patterns *ppat_signal, const Edje_Patterns *ppat_source, const char *signal, const char *source, Edje_Program **programs, Eina_Bool(*func)(Edje_Program *pr, void *data), void *data, Eina_Bool prop)
Edje_Patterns * edje_match_programs_signal_init (Edje_Program *const *array, unsigned int count)
Edje_Patterns * edje_match_programs_source_init (Edje_Program *const *array, unsigned int count)
void edje_match_signal_source_free (Edje_Signal_Source_Char *key, void *data)
const Eina_List * edje_match_signal_source_hash_get (const char *signal, const char *source, const Eina_Rbtree *tree)
void edje_object_propagate_callback_add (Evas_Object *obj, void(*func)(void *data, Evas_Object *o, const char *emission, const char *source), void *data)
const char * edje_string_get (const Edje_String *es)
const char * edje_string_id_get (const Edje_String *es)
Variables
int _edje_anim_count
Eina_List * _edje_animators
EAPI int _edje_default_log_dom
EAPI Eet_Data_Descriptor * _edje_edd_edje_file
EAPI Eet_Data_Descriptor * _edje_edd_edje_part_collection
Eina_List * _edje_edjes
char * _edje_fontset_append
int _edje_freeze_calc_count
Eina_List * _edje_freeze_calc_list
int _edje_freeze_val
jmp_buf _edje_lua_panic_jmp
Eina_Bool _edje_password_show_last
FLOAT_T _edje_password_show_last_timeout
Eina_Mempool * _edje_real_part_mp
Eina_Mempool * _edje_real_part_state_mp
FLOAT_T _edje_scale
Ecore_Animator * _edje_timer
Eina_Mempool * _emp_BOX
Eina_Mempool * _emp_EXTERNAL
Eina_Mempool * _emp_GROUP
Eina_Mempool * _emp_IMAGE
Eina_Mempool * _emp_part
Eina_Mempool * _emp_PROXY
Eina_Mempool * _emp_RECTANGLE
Eina_Mempool * _emp_SPACER
Eina_Mempool * _emp_SWALLOW
Eina_Mempool * _emp_TABLE
Eina_Mempool * _emp_TEXT
Eina_Mempool * _emp_TEXTBLOCK
Macro Definition Documentation
_edje_lua2_error
#define _edje_lua2_error (L, err_code) _edje_lua2_error_full(__FILE__, __FUNCTION__, __LINE__, L, err_code)
_edje_lua_error
#define _edje_lua_error (L, err_code) __edje_lua_error(__FILE__, __FUNCTION__, __LINE__, L, err_code)
_edje_lua_panic_here
#define _edje_lua_panic_here () setjmp(_edje_lua_panic_jmp)
_GNU_SOURCE
#define _GNU_SOURCE
ABS
#define ABS (x) ((x) < 0 ? -(x) : (x))
ADD
#define ADD (a, b) ((a) + (b))
CHKPARAM
#define CHKPARAM (n) if (params[0] != (sizeof(Embryo_Cell) * (n))) return -1;
CLAMP
#define CLAMP (x, min, max) (((x) > (max)) ? (max) : (((x) < (min)) ? (min) : (x)))
COS
#define COS (a) cos(a)
CRIT
#define CRIT (...) EINA_LOG_DOM_CRIT(_edje_default_log_dom, __VA_ARGS__)
DBG
#define DBG (...) EINA_LOG_DOM_DBG(_edje_default_log_dom, __VA_ARGS__)
DIV
#define DIV (a, b) ((a) / (b))
DIV2
#define DIV2 (a) ((a) / 2.0)
EDJE_DEFAULT_LOG_COLOR
#define EDJE_DEFAULT_LOG_COLOR EINA_COLOR_CYAN
EDJE_ENTRY_CURSOR_MODE_BEFORE
#define EDJE_ENTRY_CURSOR_MODE_BEFORE 1
EDJE_ENTRY_CURSOR_MODE_UNDER
#define EDJE_ENTRY_CURSOR_MODE_UNDER 0
EDJE_ENTRY_EDIT_MODE_EDITABLE
#define EDJE_ENTRY_EDIT_MODE_EDITABLE 2
EDJE_ENTRY_EDIT_MODE_NONE
#define EDJE_ENTRY_EDIT_MODE_NONE 0
EDJE_ENTRY_EDIT_MODE_PASSWORD
#define EDJE_ENTRY_EDIT_MODE_PASSWORD 3
EDJE_ENTRY_EDIT_MODE_SELECTABLE
#define EDJE_ENTRY_EDIT_MODE_SELECTABLE 1
EDJE_ENTRY_SELECTION_MODE_DEFAULT
#define EDJE_ENTRY_SELECTION_MODE_DEFAULT 0
EDJE_ENTRY_SELECTION_MODE_EXPLICIT
#define EDJE_ENTRY_SELECTION_MODE_EXPLICIT 1
EDJE_FILE_MINOR
#define EDJE_FILE_MINOR 4
EDJE_FILE_VERSION
#define EDJE_FILE_VERSION 3
EDJE_IMAGE_SOURCE_TYPE_EXTERNAL
#define EDJE_IMAGE_SOURCE_TYPE_EXTERNAL 3
EDJE_IMAGE_SOURCE_TYPE_INLINE_LOSSY
#define EDJE_IMAGE_SOURCE_TYPE_INLINE_LOSSY 2
EDJE_IMAGE_SOURCE_TYPE_INLINE_PERFECT
#define EDJE_IMAGE_SOURCE_TYPE_INLINE_PERFECT 1
EDJE_IMAGE_SOURCE_TYPE_LAST
#define EDJE_IMAGE_SOURCE_TYPE_LAST 4
EDJE_IMAGE_SOURCE_TYPE_NONE
#define EDJE_IMAGE_SOURCE_TYPE_NONE 0
EDJE_INF_MAX_H
#define EDJE_INF_MAX_H 100000
EDJE_INF_MAX_W
#define EDJE_INF_MAX_W 100000
EDJE_ORIENTATION_AUTO
#define EDJE_ORIENTATION_AUTO 0
EDJE_ORIENTATION_LTR
#define EDJE_ORIENTATION_LTR 1
EDJE_ORIENTATION_RTL
#define EDJE_ORIENTATION_RTL 2
EDJE_PART_PATH_SEPARATOR
#define EDJE_PART_PATH_SEPARATOR ':'
EDJE_PART_PATH_SEPARATOR_INDEXL
#define EDJE_PART_PATH_SEPARATOR_INDEXL '['
EDJE_PART_PATH_SEPARATOR_INDEXR
#define EDJE_PART_PATH_SEPARATOR_INDEXR ']'
EDJE_PART_PATH_SEPARATOR_STRING
#define EDJE_PART_PATH_SEPARATOR_STRING ":"
EDJE_SMART_API_INIT
#define EDJE_SMART_API_INIT (smart_class_init) {smart_class_init, EDJE_SMART_API_VERSION, NULL}
EDJE_SMART_API_INIT_NAME_VERSION
#define EDJE_SMART_API_INIT_NAME_VERSION (name) EDJE_SMART_API_INIT(EVAS_SMART_CLASS_INIT_NAME_VERSION(name))
EDJE_SMART_API_INIT_NULL
#define EDJE_SMART_API_INIT_NULL EDJE_SMART_API_INIT(EVAS_SMART_CLASS_INIT_NULL)
EDJE_SMART_API_INIT_VERSION
#define EDJE_SMART_API_INIT_VERSION EDJE_SMART_API_INIT(EVAS_SMART_CLASS_INIT_VERSION)
EDJE_SMART_API_VERSION
#define EDJE_SMART_API_VERSION 1
EDJE_SOUND_SOURCE_TYPE_INLINE_AS_IS
#define EDJE_SOUND_SOURCE_TYPE_INLINE_AS_IS 4
EDJE_SOUND_SOURCE_TYPE_INLINE_COMP
#define EDJE_SOUND_SOURCE_TYPE_INLINE_COMP 2
EDJE_SOUND_SOURCE_TYPE_INLINE_LOSSY
#define EDJE_SOUND_SOURCE_TYPE_INLINE_LOSSY 3
EDJE_SOUND_SOURCE_TYPE_INLINE_RAW
#define EDJE_SOUND_SOURCE_TYPE_INLINE_RAW 1
EDJE_SOUND_SOURCE_TYPE_NONE
#define EDJE_SOUND_SOURCE_TYPE_NONE 0
EDJE_STATE_PARAM_ALIGNMENT
#define EDJE_STATE_PARAM_ALIGNMENT 1
EDJE_STATE_PARAM_ASPECT
#define EDJE_STATE_PARAM_ASPECT 5
EDJE_STATE_PARAM_ASPECT_PREF
#define EDJE_STATE_PARAM_ASPECT_PREF 6
EDJE_STATE_PARAM_BORDER
#define EDJE_STATE_PARAM_BORDER 18
EDJE_STATE_PARAM_COLOR
#define EDJE_STATE_PARAM_COLOR 7
EDJE_STATE_PARAM_COLOR2
#define EDJE_STATE_PARAM_COLOR2 8
EDJE_STATE_PARAM_COLOR3
#define EDJE_STATE_PARAM_COLOR3 9
EDJE_STATE_PARAM_COLOR_CLASS
#define EDJE_STATE_PARAM_COLOR_CLASS 10
EDJE_STATE_PARAM_FILL_POS
#define EDJE_STATE_PARAM_FILL_POS 20
EDJE_STATE_PARAM_FILL_SIZE
#define EDJE_STATE_PARAM_FILL_SIZE 21
EDJE_STATE_PARAM_FILL_SMOOTH
#define EDJE_STATE_PARAM_FILL_SMOOTH 19
EDJE_STATE_PARAM_IMAGE
#define EDJE_STATE_PARAM_IMAGE 17
EDJE_STATE_PARAM_LAST
#define EDJE_STATE_PARAM_LAST 43
EDJE_STATE_PARAM_MAP_BACK_CULL
#define EDJE_STATE_PARAM_MAP_BACK_CULL 39
EDJE_STATE_PARAM_MAP_LIGNT
#define EDJE_STATE_PARAM_MAP_LIGNT 34
EDJE_STATE_PARAM_MAP_OM
#define EDJE_STATE_PARAM_MAP_OM 32
EDJE_STATE_PARAM_MAP_PERSP
#define EDJE_STATE_PARAM_MAP_PERSP 33
EDJE_STATE_PARAM_MAP_PERSP_ON
#define EDJE_STATE_PARAM_MAP_PERSP_ON 40
EDJE_STATE_PARAM_MAP_ROT_CENTER
#define EDJE_STATE_PARAM_MAP_ROT_CENTER 35
EDJE_STATE_PARAM_MAP_ROT_X
#define EDJE_STATE_PARAM_MAP_ROT_X 36
EDJE_STATE_PARAM_MAP_ROT_Y
#define EDJE_STATE_PARAM_MAP_ROT_Y 37
EDJE_STATE_PARAM_MAP_ROT_Z
#define EDJE_STATE_PARAM_MAP_ROT_Z 38
EDJE_STATE_PARAM_MAX
#define EDJE_STATE_PARAM_MAX 3
EDJE_STATE_PARAM_MIN
#define EDJE_STATE_PARAM_MIN 2
EDJE_STATE_PARAM_NONE
#define EDJE_STATE_PARAM_NONE 0
EDJE_STATE_PARAM_PERSP_FOCAL
#define EDJE_STATE_PARAM_PERSP_FOCAL 42
EDJE_STATE_PARAM_PERSP_ZPLANE
#define EDJE_STATE_PARAM_PERSP_ZPLANE 41
EDJE_STATE_PARAM_REL1
#define EDJE_STATE_PARAM_REL1 11
EDJE_STATE_PARAM_REL1_OFFSET
#define EDJE_STATE_PARAM_REL1_OFFSET 13
EDJE_STATE_PARAM_REL1_TO
#define EDJE_STATE_PARAM_REL1_TO 12
EDJE_STATE_PARAM_REL2
#define EDJE_STATE_PARAM_REL2 14
EDJE_STATE_PARAM_REL2_OFFSET
#define EDJE_STATE_PARAM_REL2_OFFSET 16
EDJE_STATE_PARAM_REL2_TO
#define EDJE_STATE_PARAM_REL2_TO 15
EDJE_STATE_PARAM_STEP
#define EDJE_STATE_PARAM_STEP 4
EDJE_STATE_PARAM_TEXT
#define EDJE_STATE_PARAM_TEXT 22
EDJE_STATE_PARAM_TEXT_ALIGN
#define EDJE_STATE_PARAM_TEXT_ALIGN 30
EDJE_STATE_PARAM_TEXT_CLASS
#define EDJE_STATE_PARAM_TEXT_CLASS 23
EDJE_STATE_PARAM_TEXT_FIT
#define EDJE_STATE_PARAM_TEXT_FIT 27
EDJE_STATE_PARAM_TEXT_FONT
#define EDJE_STATE_PARAM_TEXT_FONT 24
EDJE_STATE_PARAM_TEXT_MAX
#define EDJE_STATE_PARAM_TEXT_MAX 29
EDJE_STATE_PARAM_TEXT_MIN
#define EDJE_STATE_PARAM_TEXT_MIN 28
EDJE_STATE_PARAM_TEXT_SIZE
#define EDJE_STATE_PARAM_TEXT_SIZE 26
EDJE_STATE_PARAM_TEXT_STYLE
#define EDJE_STATE_PARAM_TEXT_STYLE 25
EDJE_STATE_PARAM_VISIBLE
#define EDJE_STATE_PARAM_VISIBLE 31
EDJE_T_FLOAT
#define EDJE_T_FLOAT EET_T_DOUBLE
EDJE_VAR_FLOAT
#define EDJE_VAR_FLOAT 2
EDJE_VAR_HASH
#define EDJE_VAR_HASH 5
EDJE_VAR_INT
#define EDJE_VAR_INT 1
EDJE_VAR_LIST
#define EDJE_VAR_LIST 4
EDJE_VAR_MAGIC_BASE
#define EDJE_VAR_MAGIC_BASE 0x12fe84ba
EDJE_VAR_NONE
#define EDJE_VAR_NONE 0
EDJE_VAR_STRING
#define EDJE_VAR_STRING 3
ERR
#define ERR (...) EINA_LOG_DOM_ERR(_edje_default_log_dom, __VA_ARGS__)
FLAG_NONE
#define FLAG_NONE 0
FLAG_X
#define FLAG_X 0x01
FLAG_XY
#define FLAG_XY (FLAG_X | FLAG_Y)
FLAG_Y
#define FLAG_Y 0x02
FLOAT_T
#define FLOAT_T double
FROM_DOUBLE
#define FROM_DOUBLE (a) (a)
FROM_INT
#define FROM_INT (a) (double)(a)
GETFLOAT
#define GETFLOAT (val, par)
Value:
   { \
   float *___cptr; \
   if ((___cptr = (float *)embryo_data_address_get(ep, (par)))) { \
      val = *___cptr; } }
GETFLOAT_T
#define GETFLOAT_T (val, par)
Value:
  {                                 \
     float *___cptr;                            \
     if ((___cptr = (float *)embryo_data_address_get(ep, (par))))   \
       {                                \
      val = FROM_DOUBLE(*___cptr);                  \
       }                                \
  }
GETINT
#define GETINT (val, par)
Value:
   {            \
   int *___cptr; \
   if ((___cptr = (int *)embryo_data_address_get(ep, (par)))) { \
      val = *___cptr; } }
GETSTR
#define GETSTR (str, par)
Value:
   { \
   Embryo_Cell *___cptr; \
   int ___l; \
   str = NULL; \
   if ((___cptr = embryo_data_address_get(ep, (par)))) { \
      ___l = embryo_data_string_length_get(ep, ___cptr); \
      if (((str) = alloca(___l + 1))) \
    embryo_data_string_get(ep, ___cptr, (str)); } }
GETSTREVAS
#define GETSTREVAS (str, par)
Value:
   { \
   if ((str)) { \
      if ((par) && (!strcmp((par), (str)))) return 0; \
      if ((par)) eina_stringshare_del((par)); \
      (par) = (char *)eina_stringshare_add((str)); } \
   else (par) = NULL; }
HASNPARAMS
#define HASNPARAMS (n) (params[0] == (sizeof(Embryo_Cell) * (n)))
INF
#define INF (...) EINA_LOG_DOM_INFO(_edje_default_log_dom, __VA_ARGS__)
MIN
#define MIN (a, b) (((a) < (b)) ? (a) : (b))
MUL
#define MUL (a, b) ((a) * (b))
PART_TYPE_FIELDS
#define PART_TYPE_FIELDS (TYPE)
Value:
      TYPE      RECTANGLE;        \
      TYPE      TEXT;             \
      TYPE      IMAGE;            \
      TYPE      PROXY;            \
      TYPE      SWALLOW;          \
      TYPE      TEXTBLOCK;        \
      TYPE      GROUP;            \
      TYPE      BOX;              \
      TYPE      TABLE;            \
      TYPE      SPACER;   \
      TYPE      EXTERNAL;
PI
#define PI 3.14159265358979323846
SCALE
#define SCALE (a, b) ((a) * (double)(b))
SETFLOAT
#define SETFLOAT (val, par)
Value:
   { \
   float *___cptr; \
   if ((___cptr = (float *)embryo_data_address_get(ep, (par)))) { \
      *___cptr = (float)val; } }
SETFLOAT_T
#define SETFLOAT_T (val, par)
Value:
  {                                 \
     float *___cptr;                            \
     if ((___cptr = (float *)embryo_data_address_get(ep, (par))))   \
       {                                \
      *___cptr = (float) TO_DOUBLE(val);                \
       }                                \
  }
SETINT
#define SETINT (val, par)
Value:
   { \
   int *___cptr; \
   if ((___cptr = (int *)embryo_data_address_get(ep, (par)))) { \
      *___cptr = (int)val; } }
SETSTR
#define SETSTR (str, par)
Value:
   { \
   Embryo_Cell *___cptr; \
   if ((___cptr = embryo_data_address_get(ep, (par)))) { \
      embryo_data_string_set(ep, str, ___cptr); } }
SETSTRALLOCATE
#define SETSTRALLOCATE (s)
Value:
  {                     \
     if (s) {                   \
    if ((int) strlen((s)) < params[4]) {    \
       SETSTR((s), params[3]); }        \
    else {                  \
       char *ss;                \
       ss = alloca(strlen((s)) + 1);    \
       strcpy(ss, (s));         \
       ss[params[4] - 2] = 0;       \
       SETSTR(ss, params[3]); } }       \
     else                    \
       SETSTR("", params[3]);           \
  }
SIN
#define SIN (a) sin(a)
SQRT
#define SQRT (a) sqrt(a)
SUB
#define SUB (a, b) ((a) - (b))
TO_DOUBLE
#define TO_DOUBLE (a) (double)(a)
TO_INT
#define TO_INT (a) (int)(a)
WRN
#define WRN (...) EINA_LOG_DOM_WARN(_edje_default_log_dom, __VA_ARGS__)
ZERO
#define ZERO 0.0
Typedef Documentation
Edje
typedef struct _Edje Edje
Edje_Alignment
typedef struct _Edje_Position_Scale Edje_Alignment
Edje_Aspect
typedef struct _Edje_Aspect Edje_Aspect
Edje_Aspect_Prefer
typedef struct _Edje_Aspect_Prefer Edje_Aspect_Prefer
Edje_Calc_Params
typedef struct _Edje_Calc_Params Edje_Calc_Params
Edje_Color
typedef struct _Edje_Color Edje_Color
Edje_Color_Class
typedef struct _Edje_Color_Class Edje_Color_Class
Edje_External_Directory
typedef struct _Edje_External_Directory Edje_External_Directory
Edje_External_Directory_Entry
typedef struct _Edje_External_Directory_Entry Edje_External_Directory_Entry
Edje_File
typedef struct _Edje_File Edje_File
Edje_Fill
typedef enum _Edje_Fill Edje_Fill
Edje_Font_Directory_Entry
typedef struct _Edje_Font_Directory_Entry Edje_Font_Directory_Entry
Edje_Image_Directory
typedef struct _Edje_Image_Directory Edje_Image_Directory
Edje_Image_Directory_Entry
typedef struct _Edje_Image_Directory_Entry Edje_Image_Directory_Entry
Edje_Image_Directory_Set
typedef struct _Edje_Image_Directory_Set Edje_Image_Directory_Set
Edje_Image_Directory_Set_Entry
typedef struct _Edje_Image_Directory_Set_Entry Edje_Image_Directory_Set_Entry
Edje_Limit
typedef struct _Edje_Limit Edje_Limit
Edje_Markup_Filter_Callback
typedef struct _Edje_Markup_Filter_Callback Edje_Markup_Filter_Callback
Edje_Match_Error
typedef enum _Edje_Match_Error Edje_Match_Error
Edje_Message
typedef struct _Edje_Message Edje_Message
Edje_Message_Signal
typedef struct _Edje_Message_Signal Edje_Message_Signal
Edje_Message_Signal_Data
typedef struct _Edje_Message_Signal_Data Edje_Message_Signal_Data
Edje_Multisense_Env
typedef struct _Edje_Multisense_Env Edje_Multisense_Env
Edje_Pack_Element
typedef struct _Edje_Pack_Element Edje_Pack_Element
Edje_Part
typedef struct _Edje_Part Edje_Part
Edje_Part_Api
typedef struct _Edje_Part_Api Edje_Part_Api
Edje_Part_Box_Animation
typedef struct _Edje_Part_Box_Animation Edje_Part_Box_Animation
Edje_Part_Collection
typedef struct _Edje_Part_Collection Edje_Part_Collection
Edje_Part_Collection_Directory_Entry
typedef struct _Edje_Part_Collection_Directory_Entry Edje_Part_Collection_Directory_Entry
Edje_Part_Description_Box
typedef struct _Edje_Part_Description_Box Edje_Part_Description_Box
Edje_Part_Description_Common
typedef struct _Edje_Part_Description_Common Edje_Part_Description_Common
Edje_Part_Description_External
typedef struct _Edje_Part_Description_External Edje_Part_Description_External
Edje_Part_Description_Image
typedef struct _Edje_Part_Description_Image Edje_Part_Description_Image
Edje_Part_Description_List
typedef struct _Edje_Part_Description_List Edje_Part_Description_List
Edje_Part_Description_Proxy
typedef struct _Edje_Part_Description_Proxy Edje_Part_Description_Proxy
Edje_Part_Description_Spec_Border
typedef struct _Edje_Part_Description_Spec_Border Edje_Part_Description_Spec_Border
Edje_Part_Description_Spec_Box
typedef struct _Edje_Part_Description_Spec_Box Edje_Part_Description_Spec_Box
Edje_Part_Description_Spec_Fill
typedef struct _Edje_Part_Description_Spec_Fill Edje_Part_Description_Spec_Fill
Edje_Part_Description_Spec_Image
typedef struct _Edje_Part_Description_Spec_Image Edje_Part_Description_Spec_Image
Edje_Part_Description_Spec_Proxy
typedef struct _Edje_Part_Description_Spec_Proxy Edje_Part_Description_Spec_Proxy
Edje_Part_Description_Spec_Table
typedef struct _Edje_Part_Description_Spec_Table Edje_Part_Description_Spec_Table
Edje_Part_Description_Spec_Text
typedef struct _Edje_Part_Description_Spec_Text Edje_Part_Description_Spec_Text
Edje_Part_Description_Table
typedef struct _Edje_Part_Description_Table Edje_Part_Description_Table
Edje_Part_Description_Text
typedef struct _Edje_Part_Description_Text Edje_Part_Description_Text
Edje_Part_Dragable
typedef struct _Edje_Part_Dragable Edje_Part_Dragable
Edje_Part_Image_Id
typedef struct _Edje_Part_Image_Id Edje_Part_Image_Id
Edje_Part_Limit
typedef struct _Edje_Part_Limit Edje_Part_Limit
Edje_Patterns
typedef struct _Edje_Patterns Edje_Patterns
Edje_Pending_Program
typedef struct _Edje_Pending_Program Edje_Pending_Program
Edje_Position
typedef struct _Edje_Position Edje_Position
Edje_Position_Scale
typedef struct _Edje_Position_Scale Edje_Position_Scale
Edje_Program
typedef struct _Edje_Program Edje_Program
Edje_Program_After
typedef struct _Edje_Program_After Edje_Program_After
Edje_Program_Target
typedef struct _Edje_Program_Target Edje_Program_Target
Edje_Queue
typedef enum _Edje_Queue Edje_Queue
Edje_Real_Part
typedef struct _Edje_Real_Part Edje_Real_Part
Edje_Real_Part_Drag
typedef struct _Edje_Real_Part_Drag Edje_Real_Part_Drag
Edje_Real_Part_Set
typedef struct _Edje_Real_Part_Set Edje_Real_Part_Set
Edje_Real_Part_State
typedef struct _Edje_Real_Part_State Edje_Real_Part_State
Edje_Rectangle
typedef struct _Edje_Rectangle Edje_Rectangle
Edje_Running_Program
typedef struct _Edje_Running_Program Edje_Running_Program
Edje_Signal_Callback
typedef struct _Edje_Signal_Callback Edje_Signal_Callback
Edje_Signal_Source_Char
typedef struct _Edje_Signal_Source_Char Edje_Signal_Source_Char
Edje_Signals_Sources_Patterns
typedef struct _Edje_Signals_Sources_Patterns Edje_Signals_Sources_Patterns
Edje_Size
typedef struct _Edje_Size Edje_Size
Edje_Smart_Api
typedef struct _Edje_Smart_Api Edje_Smart_Api
Edje_Sound_Directory
typedef struct _Edje_Sound_Directory Edje_Sound_Directory
Edje_Sound_Sample
typedef struct _Edje_Sound_Sample Edje_Sound_Sample
Edje_Sound_Tone
typedef struct _Edje_Sound_Tone Edje_Sound_Tone
Edje_States
typedef struct _Edje_States Edje_States
Edje_String
typedef struct _Edje_String Edje_String
Edje_Style
typedef struct _Edje_Style Edje_Style
Edje_Style_Tag
typedef struct _Edje_Style_Tag Edje_Style_Tag
Edje_Text_Class
typedef struct _Edje_Text_Class Edje_Text_Class
Edje_Text_Insert_Filter_Callback
typedef struct _Edje_Text_Insert_Filter_Callback Edje_Text_Insert_Filter_Callback
Edje_Text_Style
typedef struct _Edje_Text_Style Edje_Text_Style
Edje_User_Defined
typedef struct _Edje_User_Defined Edje_User_Defined
Edje_User_Defined_Type
typedef enum _Edje_User_Defined_Type Edje_User_Defined_Type
Edje_Var
typedef struct _Edje_Var Edje_Var
Edje_Var_Animator
typedef struct _Edje_Var_Animator Edje_Var_Animator
Edje_Var_Float
typedef struct _Edje_Var_Float Edje_Var_Float
Edje_Var_Hash
typedef struct _Edje_Var_Hash Edje_Var_Hash
Edje_Var_Int
typedef struct _Edje_Var_Int Edje_Var_Int
Edje_Var_List
typedef struct _Edje_Var_List Edje_Var_List
Edje_Var_Pool
typedef struct _Edje_Var_Pool Edje_Var_Pool
Edje_Var_String
typedef struct _Edje_Var_String Edje_Var_String
Edje_Var_Timer
typedef struct _Edje_Var_Timer Edje_Var_Timer
MULTISENSE_FACTORY_INIT_FUNC
typedef Eina_Bool(* MULTISENSE_FACTORY_INIT_FUNC) (Edje_Multisense_Env *)
Enumeration Type Documentation
_Edje_Fill
enum _Edje_Fill
Enumerator
EDJE_FILL_TYPE_SCALE
EDJE_FILL_TYPE_TILE
_Edje_Match_Error
enum _Edje_Match_Error
Enumerator
EDJE_MATCH_OK
EDJE_MATCH_ALLOC_ERROR
EDJE_MATCH_SYNTAX_ERROR
_Edje_Queue
enum _Edje_Queue
Enumerator
EDJE_QUEUE_APP
EDJE_QUEUE_SCRIPT
_Edje_User_Defined_Type
enum _Edje_User_Defined_Type
Enumerator
EDJE_USER_SWALLOW
EDJE_USER_BOX_PACK
EDJE_USER_TABLE_PACK
EDJE_USER_STRING
EDJE_USER_DRAG_STEP
EDJE_USER_DRAG_PAGE
EDJE_USER_DRAG_VALUE
EDJE_USER_DRAG_SIZE
Edje_Internal_Aspect
enum Edje_Internal_Aspect
Enumerator
EDJE_ASPECT_PREFER_NONE
EDJE_ASPECT_PREFER_VERTICAL
EDJE_ASPECT_PREFER_HORIZONTAL
EDJE_ASPECT_PREFER_BOTH
EDJE_ASPECT_PREFER_SOURCE
Edje_Part_Limit_State
enum Edje_Part_Limit_State
Enumerator
EDJE_PART_LIMIT_UNKNOWN
EDJE_PART_LIMIT_BELOW
EDJE_PART_LIMIT_ZERO
EDJE_PART_LIMIT_OVER
Function Documentation
__edje_lua_error()
void __edje_lua_error (const char * file, const char * fnc, int line, lua_State * L, int err_code)
_edje_block()
int _edje_block (Edje * ed)
References _edje_ref(), and _Edje::block.
Referenced by _edje_emit_handle(), _edje_program_run(), _edje_program_run_iterate(), _edje_timer_cb(), and edje_object_animation_set().
_edje_block_break()
int _edje_block_break (Edje * ed)
References _Edje::block_break.
Referenced by _edje_emit_handle(), _edje_program_run(), _edje_program_run_iterate(), _edje_timer_cb(), and edje_object_animation_set().
_edje_block_violate()
void _edje_block_violate (Edje * ed)
References _Edje::block, and _Edje::block_break.
Referenced by _edje_file_del().
_edje_box_init()
void _edje_box_init (void)
_edje_box_layout_add_child()
Eina_Bool _edje_box_layout_add_child (Edje_Real_Part * rp, Evas_Object * child_obj)
References _Edje_Real_Part::anim, _Edje_Transition_Animation_Data::obj, _Edje_Part_Box_Animation::objs, and _Edje_Part_Box_Animation::recalculate.
Referenced by _edje_real_part_box_append(), _edje_real_part_box_insert_at(), _edje_real_part_box_insert_before(), and _edje_real_part_box_prepend().
_edje_box_layout_anim_new()
Edje_Part_Box_Animation* _edje_box_layout_anim_new (Evas_Object * box)
References _Edje_Part_Box_Animation::box.
_edje_box_layout_find()
Eina_Bool _edje_box_layout_find (const char * name, Evas_Object_Box_Layout * cb, void ** data, void(**)(void *data) free_data)
References edje_box_layout_builtin::cb, and name.
_edje_box_layout_free_data()
void _edje_box_layout_free_data (void * data)
References _Edje_Part_Box_Animation::data, _Edje_Part_Box_Animation::end, _Edje_Part_Box_Animation::free_data, _Edje_Part_Box_Animation::objs, and _Edje_Part_Box_Animation::start.
Referenced by _edje_file_del().
_edje_box_layout_remove_child()
void _edje_box_layout_remove_child (Edje_Real_Part * rp, Evas_Object * child_obj)
References _Edje_Real_Part::anim, _Edje_Transition_Animation_Data::obj, _Edje_Part_Box_Animation::objs, and _Edje_Part_Box_Animation::recalculate.
Referenced by _edje_real_part_box_remove(), _edje_real_part_box_remove_all(), and _edje_real_part_box_remove_at().
_edje_box_recalc_apply()
void _edje_box_recalc_apply (Edje *ed __UNUSED__, Edje_Real_Part * ep, Edje_Calc_Params * p3, Edje_Part_Description_Box * chosen_desc)
_edje_box_shutdown()
void _edje_box_shutdown (void)
_edje_cache_coll_clean()
void _edje_cache_coll_clean (Edje_File * edf)
References _Edje_File::collection_cache.
Referenced by _edje_cache_coll_unref().
_edje_cache_coll_flush()
void _edje_cache_coll_flush (Edje_File * edf)
References _edje_collection_free(), _Edje_File::collection, _Edje_File::collection_cache, and _Edje_Part_Collection::part.
Referenced by _edje_cache_coll_unref(), and _edje_file_free().
_edje_cache_coll_unref()
void _edje_cache_coll_unref (Edje_File * edf, Edje_Part_Collection * edc)
References _edje_cache_coll_clean(), _edje_cache_coll_flush(), _edje_collection_free(), _Edje_File::collection, _Edje_File::collection_cache, _Edje_File::dangling, ERR, _Edje_Part_Collection::part, _Edje_Part_Collection_Directory_Entry::ref, and _Edje_Part_Collection::references.
Referenced by _edje_file_del().
_edje_cache_file_coll_open()
Edje_File* _edje_cache_file_coll_open (const char * file, const char * coll, int * error_ret, Edje_Part_Collection ** edc_ret, Edje * ed)
References EDJE_LOAD_ERROR_DOES_NOT_EXIST.
Referenced by _edje_file_add(), edje_file_collection_list(), edje_file_data_get(), and edje_file_group_exists().
_edje_cache_file_unref()
void _edje_cache_file_unref (Edje_File * edf)
References _edje_file_free(), _Edje_File::dangling, and _Edje_File::references.
Referenced by _edje_file_add(), _edje_file_del(), edje_file_collection_list(), edje_file_data_get(), and edje_file_group_exists().
_edje_callbacks_add()
void _edje_callbacks_add (Evas_Object * obj, Edje * ed, Edje_Real_Part * rp)
Referenced by edje_edit_part_mouse_events_set().
_edje_callbacks_del()
void _edje_callbacks_del (Evas_Object * obj, Edje * ed)
Referenced by _edje_file_del(), _edje_real_part_swallow_clear(), and edje_edit_part_mouse_events_set().
_edje_callbacks_focus_add()
void _edje_callbacks_focus_add (Evas_Object * obj, Edje * ed, Edje_Real_Part * rp)
_edje_callbacks_focus_del()
void _edje_callbacks_focus_del (Evas_Object * obj, Edje * ed)
Referenced by _edje_file_del(), and _edje_real_part_swallow_clear().
_edje_callbacks_patterns_clean()
void _edje_callbacks_patterns_clean (Edje * ed)
References _edje_signals_sources_patterns_clean(), _Edje::callbacks, _Edje_Program_Data::ed, edje_match_signal_source_free(), _Edje::patterns, and _Edje::walking_callbacks.
Referenced by _edje_del(), edje_object_propagate_callback_add(), edje_object_signal_callback_add(), edje_object_signal_callback_del(), and edje_object_signal_callback_del_full().
_edje_children_get()
Evas_Object* _edje_children_get (Edje_Real_Part * rp, const char * partid)
References _edje_external_content_get(), EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_TABLE, name, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje_Real_Part::swallowed_object, and _Edje_Part::type.
Referenced by _edje_emit_full(), and _edje_real_part_recursive_get_helper().
_edje_clean_objects()
void _edje_clean_objects (Edje * ed)
References _Edje::base, and _Edje::obj.
_edje_collection_free()
void _edje_collection_free (Edje_File * edf, Edje_Part_Collection * ec, Edje_Part_Collection_Directory_Entry * ce)
References _edje_collection_free_part_description_clean(), _edje_embryo_script_shutdown(), _edje_lua2_script_unload(), _Edje_Part_Collection::alias, _Edje_Part_Collection::aliased, _Edje_Part_Collection::data, _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, _Edje_Part_Description_List::desc_rtl, EDJE_LOAD_PROGRAM_FREE, _Edje_File::free_strings, _Edje_Part::items, _Edje_Part_Collection_Directory_Entry::mp, _Edje_Part_Collection_Directory_Entry::mp_rtl, _Edje_Part::name, _Edje_Part::other, _Edje_Part_Collection_Directory_Entry::part, _Edje_Part_Collection::parts, _Edje_Part_Collection::parts_count, _Edje_Part_Collection_Directory_Entry::ref, _Edje_Part_Collection::script, and _Edje_Part::type.
Referenced by _edje_cache_coll_flush(), and _edje_cache_coll_unref().
_edje_collection_free_part_description_clean()
void _edje_collection_free_part_description_clean (int type, Edje_Part_Description_Common * desc, Eina_Bool free_strings)
References _edje_external_params_free(), _Edje_Part_Description_Common::color_class, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_IMAGE, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part_Description_External::external_params, _Edje_Part_Description_Spec_Text::font, _Edje_Part_Description_Image::image, _Edje_String::str, _Edje_Part_Description_Spec_Text::style, _Edje_Part_Description_Spec_Text::text, _Edje_Part_Description_Text::text, _Edje_Part_Description_Spec_Text::text_class, _Edje_Part_Description_Spec_Image::tweens, _Edje_Part_Description_Spec_Image::tweens_count, and type.
Referenced by _edje_collection_free(), _edje_collection_free_part_description_free(), and _edje_file_del().
_edje_collection_free_part_description_free()
void _edje_collection_free_part_description_free (int type, Edje_Part_Description_Common * desc, Edje_Part_Collection_Directory_Entry * ce, Eina_Bool free_strings)
References _edje_collection_free_part_description_clean(), FREE_POOL, and type.
_edje_color_class_find()
Edje_Color_Class* _edje_color_class_find (Edje * ed, const char * color_class)
References _Edje::color_classes.
Referenced by edje_object_color_class_get().
_edje_color_class_hash_free()
void _edje_color_class_hash_free (void)
_edje_color_class_member_add()
void _edje_color_class_member_add (Edje * ed, const char * color_class)
_edje_color_class_member_del()
void _edje_color_class_member_del (Edje * ed, const char * color_class)
Referenced by _edje_color_class_on_del().
_edje_color_class_member_direct_del()
void _edje_color_class_member_direct_del (const char * color_class, void * lookup)
_edje_color_class_members_free()
void _edje_color_class_members_free (void)
_edje_color_class_on_del()
void _edje_color_class_on_del (Edje * ed, Edje_Part * ep)
References _edje_color_class_member_del(), _Edje_Part_Description_Common::color_class, _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, and _Edje_Part::other.
Referenced by _edje_file_del().
_edje_del()
void _edje_del (Edje * ed)
References _edje_animators, _edje_callbacks_patterns_clean(), _edje_file_del(), _edje_message_del(), _Edje::actions, _Edje::callbacks, _Edje::color_classes, _Edje::delete_me, _Edje_Text_Class::font, _Edje::group, _Edje::markup_filter_callbacks, _Edje_Text_Class::name, _Edje::parent, _Edje_Text_Insert_Filter_Callback::part, _Edje::path, _Edje::pending_actions, _Edje::processing_messages, _Edje_Signal_Callback::signal, _Edje_Signal_Callback::source, _Edje::text_classes, and _Edje::text_insert_filter_callbacks.
Referenced by _edje_unref().
_edje_dragable_pos_set()
void _edje_dragable_pos_set (Edje * ed, Edje_Real_Part * ep, FLOAT_T x, FLOAT_T y)
References _edje_recalc(), _Edje::dirty, _Edje_Real_Part::drag, _Edje_Real_Part_Drag::need_reset, _Edje::recalc_call, _Edje_Real_Part_Drag::tmp, _Edje_Real_Part_Drag::x, and _Edje_Real_Part_Drag::y.
Referenced by _edje_program_run().
_edje_edd_init()
EAPI void _edje_edd_init (void)
References _edje_edd_edje_color_class, _edje_edd_edje_external_directory, _edje_edd_edje_external_directory_entry, _edje_edd_edje_font_directory_entry, _edje_edd_edje_image_directory, _edje_edd_edje_image_directory_entry, _edje_edd_edje_image_directory_set, _edje_edd_edje_image_directory_set_entry, _edje_edd_edje_part_collection_directory_entry, _edje_edd_edje_sound_directory, _edje_edd_edje_sound_sample, _edje_edd_edje_sound_tone, _edje_edd_edje_string, _edje_edd_edje_style, _edje_edd_edje_style_tag, _Edje_Image_Directory_Set_Entry::max, _Edje_Image_Directory_Set_Entry::min, name, and _Edje_Part_Collection_Directory_Entry::part.
_edje_edd_shutdown()
EAPI void _edje_edd_shutdown (void)
References _edje_edd_edje_color_class, _edje_edd_edje_external_directory, _edje_edd_edje_external_directory_entry, _edje_edd_edje_external_param, _edje_edd_edje_file, _edje_edd_edje_font_directory_entry, _edje_edd_edje_image_directory, _edje_edd_edje_image_directory_entry, _edje_edd_edje_image_directory_set, _edje_edd_edje_image_directory_set_entry, _edje_edd_edje_limit, _edje_edd_edje_limit_pointer, _edje_edd_edje_pack_element, _edje_edd_edje_pack_element_pointer, _edje_edd_edje_part, _edje_edd_edje_part_collection, _edje_edd_edje_part_collection_directory_entry, _edje_edd_edje_part_description_box, _edje_edd_edje_part_description_box_pointer, _edje_edd_edje_part_description_external, _edje_edd_edje_part_description_external_pointer, _edje_edd_edje_part_description_group, _edje_edd_edje_part_description_group_pointer, _edje_edd_edje_part_description_image, _edje_edd_edje_part_description_image_pointer, _edje_edd_edje_part_description_proxy, _edje_edd_edje_part_description_proxy_pointer, _edje_edd_edje_part_description_rectangle, _edje_edd_edje_part_description_rectangle_pointer, _edje_edd_edje_part_description_spacer, _edje_edd_edje_part_description_spacer_pointer, _edje_edd_edje_part_description_swallow, _edje_edd_edje_part_description_swallow_pointer, _edje_edd_edje_part_description_table, _edje_edd_edje_part_description_table_pointer, _edje_edd_edje_part_description_text, _edje_edd_edje_part_description_text_pointer, _edje_edd_edje_part_description_textblock, _edje_edd_edje_part_description_textblock_pointer, _edje_edd_edje_part_description_variant, _edje_edd_edje_part_description_variant_list, _edje_edd_edje_part_image_id, _edje_edd_edje_part_image_id_pointer, _edje_edd_edje_part_limit, _edje_edd_edje_part_pointer, _edje_edd_edje_program, _edje_edd_edje_program_after, _edje_edd_edje_program_pointer, _edje_edd_edje_program_target, _edje_edd_edje_sound_directory, _edje_edd_edje_sound_sample, _edje_edd_edje_sound_tone, _edje_edd_edje_string, _edje_edd_edje_style, _edje_edd_edje_style_tag, and FREED.
_edje_embryo_globals_init()
void _edje_embryo_globals_init (Edje * ed)
References _Edje::collection, EDJE_VAR_MAGIC_BASE, and _Edje_Part_Collection::script.
Referenced by _edje_embryo_script_reset(), _edje_embryo_test_run(), and _edje_message_process().
_edje_embryo_script_init()
void _edje_embryo_script_init (Edje_Part_Collection * edc)
References _Edje_Part_Collection::script.
_edje_embryo_script_reset()
void _edje_embryo_script_reset (Edje * ed)
References _edje_embryo_globals_init(), _Edje::collection, and _Edje_Part_Collection::script.
Referenced by _edje_message_process().
_edje_embryo_script_shutdown()
void _edje_embryo_script_shutdown (Edje_Part_Collection * edc)
References _Edje_Part_Collection::script.
Referenced by _edje_collection_free().
_edje_embryo_test_run()
void _edje_embryo_test_run (Edje * ed, const char * fname, const char * sig, const char * src)
References _edje_embryo_globals_init(), _Edje::collection, ERR, _Edje::file, _Edje_Part_Collection::part, _Edje_File::path, and _Edje_Part_Collection::script.
Referenced by _edje_program_run().
_edje_emit()
void _edje_emit (Edje * ed, const char * sig, const char * src)
References _edje_emit_full().
Referenced by _edje_emit_full(), _edje_program_run(), _edje_recalc_do(), edje_object_animation_set(), edje_object_color_class_del(), edje_object_color_class_set(), and edje_object_signal_emit().
_edje_emit_full()
void _edje_emit_full (Edje * ed, const char * sig, const char * src, void * data, void(*)(void *) free_func)
References _edje_children_get(), _edje_emit(), _edje_external_signal_emit(), _edje_fetch(), _edje_message_send(), _edje_real_part_get(), _Edje_Part_Collection::alias, alloca(), _Edje_Part_Collection::broadcast_signal, _Edje::collection, _Edje_Message_Signal_Data::data, _Edje_Message_Signal::data, _Edje::delete_me, EDJE_MESSAGE_SIGNAL, edje_object_message_send(), EDJE_PART_PATH_SEPARATOR, EDJE_PART_PATH_SEPARATOR_INDEXL, EDJE_PART_PATH_SEPARATOR_INDEXR, EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_GROUP, EDJE_PART_TYPE_TABLE, EDJE_QUEUE_SCRIPT, _Edje_Message_Signal_Data::free_func, _Edje::obj, _Edje_Real_Part::part, _Edje_Message_Signal_Data::ref, _Edje_Message_Signal::sig, _Edje_Message_Signal::src, _Edje_Real_Part::swallowed_object, and _Edje_Part::type.
Referenced by _edje_emit().
_edje_emit_handle()
void _edje_emit_handle (Edje * ed, const char * sig, const char * src, Edje_Message_Signal_Data * data, Eina_Bool prop)
References _edje_block(), _edje_block_break(), _edje_freeze(), _edje_lua2_script_func_signal(), _edje_program_run(), _edje_real_part_get(), _edje_ref(), alloca(), _Edje_Real_Part::chosen_description, _Edje::collection, _Edje::delete_me, _Edje_Program_Data::ed, edje_match_programs_exec(), _Edje_Program::exec, _Edje_Program::filter, _Edje::L, _Edje_Program_Data::matches, _Edje_Part_Description_Common::name, _Edje_Program::part, _Edje::patterns, _Edje_Real_Part::program, _Edje_Signals_Sources_Patterns::programs, _Edje::programs, _Edje_Signals_Sources_Patterns::signals_patterns, _Edje_Program_Data::source, _Edje_Signals_Sources_Patterns::sources_patterns, _Edje_Program::state, _Edje_Part_Description_Common::state, _Edje::table_programs_size, and _Edje_Signals_Sources_Patterns::u.
Referenced by _edje_message_process().
_edje_entry_anchor_geometry_get()
const Eina_List* _edje_entry_anchor_geometry_get (Edje_Real_Part * rp, const char * anchor)
References _Entry::anchors, _Edje_Real_Part::entry_data, _Anchor::item, _Anchor::name, and _Anchor::sel.
Referenced by edje_object_part_text_anchor_geometry_get().
_edje_entry_anchors_list()
const Eina_List* _edje_entry_anchors_list (Edje_Real_Part * rp)
References _Entry::anchorlist, _Entry::anchors, _Edje_Real_Part::entry_data, _Anchor::item, and _Anchor::name.
Referenced by edje_object_part_text_anchor_list_get().
_edje_entry_autocapital_type_get()
Edje_Text_Autocapital_Type _edje_entry_autocapital_type_get (Edje_Real_Part * rp)
References EDJE_TEXT_AUTOCAPITAL_TYPE_NONE, and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_autocapital_type_get().
_edje_entry_autocapital_type_set()
void _edje_entry_autocapital_type_set (Edje_Real_Part * rp, Edje_Text_Autocapital_Type autocapital_type)
References EDJE_ENTRY_EDIT_MODE_PASSWORD, EDJE_TEXT_AUTOCAPITAL_TYPE_NONE, _Edje_Real_Part::entry_data, _Edje_Part::entry_mode, and _Edje_Real_Part::part.
Referenced by edje_object_part_text_autocapital_type_set().
_edje_entry_cursor_begin()
void _edje_entry_cursor_begin (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_begin_set().
_edje_entry_cursor_content_get()
char* _edje_entry_cursor_content_get (Edje_Real_Part * rp, Edje_Cursor cur)
Referenced by edje_object_part_text_cursor_content_get().
_edje_entry_cursor_coord_set()
Eina_Bool _edje_entry_cursor_coord_set (Edje_Real_Part * rp, Edje_Cursor cur, int x, int y)
_edje_entry_cursor_copy()
void _edje_entry_cursor_copy (Edje_Real_Part * rp, Edje_Cursor cur, Edje_Cursor dst)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_copy().
_edje_entry_cursor_down()
Eina_Bool _edje_entry_cursor_down (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_down().
_edje_entry_cursor_end()
void _edje_entry_cursor_end (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_end_set().
_edje_entry_cursor_geometry_get()
void _edje_entry_cursor_geometry_get (Edje_Real_Part * rp, Evas_Coord * cx, Evas_Coord * cy, Evas_Coord * cw, Evas_Coord * ch)
References _Entry::cursor, _Entry::cursor_fg, _Edje_Part::cursor_mode, EDJE_ENTRY_CURSOR_MODE_BEFORE, EDJE_ENTRY_CURSOR_MODE_UNDER, edje_object_size_min_restricted_calc(), _Edje_Real_Part::entry_data, _Edje_Real_Part::object, and _Edje_Real_Part::part.
Referenced by edje_object_part_text_cursor_geometry_get().
_edje_entry_cursor_is_format_get()
Eina_Bool _edje_entry_cursor_is_format_get (Edje_Real_Part * rp, Edje_Cursor cur)
Referenced by edje_object_part_text_cursor_is_format_get().
_edje_entry_cursor_is_visible_format_get()
Eina_Bool _edje_entry_cursor_is_visible_format_get (Edje_Real_Part * rp, Edje_Cursor cur)
Referenced by edje_object_part_text_cursor_is_visible_format_get().
_edje_entry_cursor_line_begin()
void _edje_entry_cursor_line_begin (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_line_begin_set().
_edje_entry_cursor_line_end()
void _edje_entry_cursor_line_end (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_line_end_set().
_edje_entry_cursor_next()
Eina_Bool _edje_entry_cursor_next (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_next().
_edje_entry_cursor_pos_get()
int _edje_entry_cursor_pos_get (Edje_Real_Part * rp, Edje_Cursor cur)
Referenced by edje_object_part_text_cursor_pos_get().
_edje_entry_cursor_pos_set()
void _edje_entry_cursor_pos_set (Edje_Real_Part * rp, Edje_Cursor cur, int pos)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_pos_set().
_edje_entry_cursor_prev()
Eina_Bool _edje_entry_cursor_prev (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_prev().
_edje_entry_cursor_up()
Eina_Bool _edje_entry_cursor_up (Edje_Real_Part * rp, Edje_Cursor cur)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_cursor_up().
_edje_entry_imf_context_get()
void* _edje_entry_imf_context_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_imf_context_get().
_edje_entry_imf_context_reset()
void _edje_entry_imf_context_reset (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by _edje_entry_select_abort(), _edje_entry_select_all(), _edje_entry_select_begin(), _edje_entry_select_extend(), _edje_entry_text_markup_insert(), _edje_entry_text_markup_set(), and edje_object_part_text_imf_context_reset().
_edje_entry_init()
void _edje_entry_init (Edje * ed)
References _Edje::entries_inited, _Edje::has_entries, and _Edje::obj.
_edje_entry_input_panel_enabled_get()
Eina_Bool _edje_entry_input_panel_enabled_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, and _Entry::input_panel_enable.
Referenced by edje_object_part_text_input_panel_enabled_get().
_edje_entry_input_panel_enabled_set()
void _edje_entry_input_panel_enabled_set (Edje_Real_Part * rp, Eina_Bool enabled)
References _Edje_Real_Part::entry_data, and _Entry::input_panel_enable.
Referenced by edje_object_part_text_input_panel_enabled_set().
_edje_entry_input_panel_hide()
void _edje_entry_input_panel_hide (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_hide().
_edje_entry_input_panel_imdata_get()
void _edje_entry_input_panel_imdata_get (Edje_Real_Part * rp, void * data, int * len)
_edje_entry_input_panel_imdata_set()
void _edje_entry_input_panel_imdata_set (Edje_Real_Part * rp, const void * data, int len)
_edje_entry_input_panel_language_get()
Edje_Input_Panel_Lang _edje_entry_input_panel_language_get (Edje_Real_Part * rp)
References EDJE_INPUT_PANEL_LANG_AUTOMATIC, _Edje_Real_Part::entry_data, and _Entry::input_panel_lang.
Referenced by edje_object_part_text_input_panel_language_get().
_edje_entry_input_panel_language_set()
void _edje_entry_input_panel_language_set (Edje_Real_Part * rp, Edje_Input_Panel_Lang lang)
References _Edje_Real_Part::entry_data, and _Entry::input_panel_lang.
Referenced by edje_object_part_text_input_panel_language_set().
_edje_entry_input_panel_layout_get()
Edje_Input_Panel_Layout _edje_entry_input_panel_layout_get (Edje_Real_Part * rp)
References EDJE_INPUT_PANEL_LAYOUT_INVALID, and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_layout_get().
_edje_entry_input_panel_layout_set()
void _edje_entry_input_panel_layout_set (Edje_Real_Part * rp, Edje_Input_Panel_Layout layout)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_layout_set().
_edje_entry_input_panel_return_key_disabled_get()
Eina_Bool _edje_entry_input_panel_return_key_disabled_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_return_key_disabled_get().
_edje_entry_input_panel_return_key_disabled_set()
void _edje_entry_input_panel_return_key_disabled_set (Edje_Real_Part * rp, Eina_Bool disabled)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_return_key_disabled_set().
_edje_entry_input_panel_return_key_type_get()
Edje_Input_Panel_Return_Key_Type _edje_entry_input_panel_return_key_type_get (Edje_Real_Part * rp)
References EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DEFAULT, and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_return_key_type_get().
_edje_entry_input_panel_return_key_type_set()
void _edje_entry_input_panel_return_key_type_set (Edje_Real_Part * rp, Edje_Input_Panel_Return_Key_Type return_key_type)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_return_key_type_set().
_edje_entry_input_panel_show()
void _edje_entry_input_panel_show (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_input_panel_show().
_edje_entry_item_geometry_get()
Eina_Bool _edje_entry_item_geometry_get (Edje_Real_Part * rp, const char * item, Evas_Coord * cx, Evas_Coord * cy, Evas_Coord * cw, Evas_Coord * ch)
References _Entry::anchors, _Edje_Real_Part::entry_data, _Anchor::item, _Anchor::name, and _Anchor::start.
Referenced by edje_object_part_text_item_geometry_get().
_edje_entry_items_list()
const Eina_List* _edje_entry_items_list (Edje_Real_Part * rp)
References _Entry::anchors, _Edje_Real_Part::entry_data, _Anchor::item, _Entry::itemlist, and _Anchor::name.
Referenced by edje_object_part_text_item_list_get().
_edje_entry_prediction_allow_get()
Eina_Bool _edje_entry_prediction_allow_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, and _Entry::prediction_allow.
Referenced by edje_object_part_text_prediction_allow_get().
_edje_entry_prediction_allow_set()
void _edje_entry_prediction_allow_set (Edje_Real_Part * rp, Eina_Bool prediction)
References _Edje_Real_Part::entry_data, and _Entry::prediction_allow.
Referenced by edje_object_part_text_prediction_allow_set().
_edje_entry_real_part_configure()
void _edje_entry_real_part_configure (Edje_Real_Part * rp)
References _Edje_Part::cursor_mode, EDJE_ENTRY_CURSOR_MODE_BEFORE, EDJE_ENTRY_CURSOR_MODE_UNDER, _Edje_Real_Part::entry_data, and _Edje_Real_Part::part.
_edje_entry_real_part_init()
void _edje_entry_real_part_init (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, _Edje_Real_Part::object, and _Entry::rp.
_edje_entry_real_part_shutdown()
void _edje_entry_real_part_shutdown (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by _edje_file_del().
_edje_entry_select_abort()
void _edje_entry_select_abort (Edje_Real_Part * rp)
References _edje_entry_imf_context_reset(), _Edje_Real_Part::entry_data, and _Entry::selecting.
Referenced by edje_object_part_text_select_abort().
_edje_entry_select_all()
void _edje_entry_select_all (Edje_Real_Part * rp)
References _edje_entry_imf_context_reset(), and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_select_all().
_edje_entry_select_allow_get()
Eina_Bool _edje_entry_select_allow_get (const Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, and _Entry::select_allow.
_edje_entry_select_allow_set()
void _edje_entry_select_allow_set (Edje_Real_Part * rp, Eina_Bool allow)
References EDJE_ENTRY_SELECTION_MODE_DEFAULT, _Edje_Real_Part::entry_data, _Edje_Real_Part::part, _Entry::select_allow, and _Edje_Part::select_mode.
Referenced by edje_object_part_text_select_allow_set().
_edje_entry_select_begin()
void _edje_entry_select_begin (Edje_Real_Part * rp)
References _edje_entry_imf_context_reset(), and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_select_begin().
_edje_entry_select_extend()
void _edje_entry_select_extend (Edje_Real_Part * rp)
References _edje_entry_imf_context_reset(), and _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_select_extend().
_edje_entry_select_none()
void _edje_entry_select_none (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
Referenced by edje_object_part_text_select_none().
_edje_entry_selection_get()
const char* _edje_entry_selection_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, _Entry::have_selection, _Entry::sel_end, _Entry::sel_start, and _Entry::selection.
Referenced by edje_object_part_text_selection_get().
_edje_entry_set_cursor_end()
void _edje_entry_set_cursor_end (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
_edje_entry_set_cursor_start()
void _edje_entry_set_cursor_start (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data.
_edje_entry_shutdown()
void _edje_entry_shutdown (Edje * ed)
References _Edje::entries_inited, _Edje::has_entries, and _Edje::obj.
Referenced by _edje_file_del().
_edje_entry_text_get()
const char* _edje_entry_text_get (Edje_Real_Part * rp)
References _Edje_Real_Part::entry_data, and _Edje_Real_Part::object.
Referenced by edje_object_part_text_get(), and edje_object_part_text_unescaped_get().
_edje_entry_text_markup_append()
void _edje_entry_text_markup_append (Edje_Real_Part * rp, const char * text)
References _Edje_Real_Part::entry_data, and _Edje_Real_Part::object.
Referenced by _edje_object_part_text_raw_append().
_edje_entry_text_markup_insert()
void _edje_entry_text_markup_insert (Edje_Real_Part * rp, const char * text)
References _edje_entry_imf_context_reset(), _Edje_Real_Part::entry_data, and _Entry::have_selection.
Referenced by edje_object_part_text_insert().
_edje_entry_text_markup_set()
void _edje_entry_text_markup_set (Edje_Real_Part * rp, const char * text)
References _edje_entry_imf_context_reset(), and _Edje_Real_Part::entry_data.
Referenced by _edje_object_part_text_raw_set().
_edje_entry_user_insert()
void _edje_entry_user_insert (Edje_Real_Part * rp, const char * text)
References _Edje_Entry_Change_Info::change, _Edje_Real_Part::entry_data, _Entry::have_selection, _Edje_Entry_Change_Info::insert, and _Edje_Real_Part::object.
Referenced by edje_object_part_text_user_insert().
_edje_external_content_get()
Evas_Object* _edje_external_content_get (const Evas_Object * obj, const char * content)
_edje_external_init()
void _edje_external_init ()
_edje_external_param_get()
Eina_Bool _edje_external_param_get (const Evas_Object * obj, Edje_Real_Part * rp, Edje_External_Param * param)
References EDJE_EXTERNAL_PARAM_TYPE_STRING, edje_object_part_text_get(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, ERR, _Edje_External_Param::name, _Edje_Part::name, _Edje_Real_Part::part, _Edje_External_Param::s, _Edje_Real_Part::swallowed_object, _Edje_External_Param::type, type, and _Edje_Part::type.
Referenced by edje_object_part_external_param_get().
_edje_external_param_set()
Eina_Bool _edje_external_param_set (Evas_Object * obj, Edje_Real_Part * rp, const Edje_External_Param * param)
References EDJE_EXTERNAL_PARAM_TYPE_STRING, edje_object_part_text_set(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, ERR, _Edje_External_Param::name, _Edje_Part::name, _Edje_Real_Part::part, _Edje_External_Param::s, _Edje_Real_Part::swallowed_object, _Edje_External_Param::type, type, and _Edje_Part::type.
Referenced by edje_object_part_external_param_set().
_edje_external_params_free()
Evas_Object void _edje_external_params_free (Eina_List * params, Eina_Bool free_strings)
References _Edje_External_Param::name, and _Edje_External_Param::s.
Referenced by _edje_collection_free_part_description_clean().
_edje_external_params_parse()
void* _edje_external_params_parse (Evas_Object * obj, const Eina_List * params)
References type.
_edje_external_parsed_params_free()
void _edje_external_parsed_params_free (Evas_Object * obj, void * params)
References type.
Referenced by _edje_file_del(), and _edje_part_description_apply().
_edje_external_recalc_apply()
void _edje_external_recalc_apply (Edje * ed, Edje_Real_Part * ep, Edje_Calc_Params * params, Edje_Part_Description_Common * chosen_desc)
_edje_external_shutdown()
void _edje_external_shutdown ()
_edje_external_signal_emit()
void _edje_external_signal_emit (Evas_Object * obj, const char * emission, const char * source)
References ERR, and type.
Referenced by _edje_emit_full().
_edje_external_type_add()
Evas_Object* _edje_external_type_add (const char * type_name, Evas * evas, Evas_Object * parent, const Eina_List * params, const char * part_name)
References type.
_edje_fetch()
Edje* _edje_fetch (const Evas_Object * obj)
References _Edje::delete_me.
Referenced by _edje_emit_full(), _edje_message_cb_set(), _edje_object_file_set_internal(), _edje_part_recalc(), _edje_real_part_recursive_get_helper(), edje_object_access_part_list_get(), edje_object_animation_get(), edje_object_animation_set(), edje_object_calc_force(), edje_object_color_class_del(), edje_object_color_class_get(), edje_object_color_class_set(), edje_object_data_get(), edje_object_file_get(), edje_object_file_set(), edje_object_freeze(), edje_object_item_provider_set(), edje_object_load_error_get(), edje_object_message_handler_set(), edje_object_message_signal_process(), edje_object_mirrored_get(), edje_object_mirrored_set(), edje_object_part_box_append(), edje_object_part_box_insert_at(), edje_object_part_box_insert_before(), edje_object_part_box_prepend(), edje_object_part_box_remove(), edje_object_part_box_remove_all(), edje_object_part_box_remove_at(), edje_object_part_drag_dir_get(), edje_object_part_drag_page(), edje_object_part_drag_page_get(), edje_object_part_drag_page_set(), edje_object_part_drag_size_get(), edje_object_part_drag_size_set(), edje_object_part_drag_step(), edje_object_part_drag_step_get(), edje_object_part_drag_step_set(), edje_object_part_drag_value_get(), edje_object_part_drag_value_set(), edje_object_part_exists(), edje_object_part_external_content_get(), edje_object_part_external_object_get(), edje_object_part_external_param_get(), edje_object_part_external_param_set(), edje_object_part_external_param_type_get(), edje_object_part_geometry_get(), edje_object_part_object_get(), edje_object_part_state_get(), edje_object_part_swallow(), edje_object_part_swallow_get(), edje_object_part_table_child_get(), edje_object_part_table_clear(), edje_object_part_table_col_row_size_get(), edje_object_part_table_pack(), edje_object_part_table_unpack(), edje_object_part_text_anchor_geometry_get(), edje_object_part_text_anchor_list_get(), edje_object_part_text_append(), edje_object_part_text_autocapital_type_get(), edje_object_part_text_autocapital_type_set(), edje_object_part_text_cursor_begin_set(), edje_object_part_text_cursor_content_get(), edje_object_part_text_cursor_coord_set(), edje_object_part_text_cursor_copy(), edje_object_part_text_cursor_down(), edje_object_part_text_cursor_end_set(), edje_object_part_text_cursor_geometry_get(), edje_object_part_text_cursor_is_format_get(), edje_object_part_text_cursor_is_visible_format_get(), edje_object_part_text_cursor_line_begin_set(), edje_object_part_text_cursor_line_end_set(), edje_object_part_text_cursor_next(), edje_object_part_text_cursor_pos_get(), edje_object_part_text_cursor_pos_set(), edje_object_part_text_cursor_prev(), edje_object_part_text_cursor_up(), edje_object_part_text_escaped_set(), edje_object_part_text_get(), edje_object_part_text_imf_context_get(), edje_object_part_text_imf_context_reset(), edje_object_part_text_input_panel_enabled_get(), edje_object_part_text_input_panel_enabled_set(), edje_object_part_text_input_panel_hide(), edje_object_part_text_input_panel_imdata_get(), edje_object_part_text_input_panel_imdata_set(), edje_object_part_text_input_panel_language_get(), edje_object_part_text_input_panel_language_set(), edje_object_part_text_input_panel_layout_get(), edje_object_part_text_input_panel_layout_set(), edje_object_part_text_input_panel_return_key_disabled_get(), edje_object_part_text_input_panel_return_key_disabled_set(), edje_object_part_text_input_panel_return_key_type_get(), edje_object_part_text_input_panel_return_key_type_set(), edje_object_part_text_input_panel_show(), edje_object_part_text_insert(), edje_object_part_text_item_geometry_get(), edje_object_part_text_item_list_get(), edje_object_part_text_prediction_allow_get(), edje_object_part_text_prediction_allow_set(), edje_object_part_text_select_abort(), edje_object_part_text_select_all(), edje_object_part_text_select_allow_set(), edje_object_part_text_select_begin(), edje_object_part_text_select_extend(), edje_object_part_text_select_none(), edje_object_part_text_selection_get(), edje_object_part_text_set(), edje_object_part_text_style_user_peek(), edje_object_part_text_style_user_pop(), edje_object_part_text_style_user_push(), edje_object_part_text_unescaped_get(), edje_object_part_text_unescaped_set(), edje_object_part_text_user_insert(), edje_object_part_unswallow(), edje_object_parts_extends_calc(), edje_object_play_get(), edje_object_play_set(), edje_object_preload(), edje_object_propagate_callback_add(), edje_object_scale_get(), edje_object_scale_set(), edje_object_signal_callback_add(), edje_object_signal_callback_del(), edje_object_signal_callback_del_full(), edje_object_signal_emit(), edje_object_size_max_get(), edje_object_size_min_get(), edje_object_size_min_restricted_calc(), edje_object_text_change_cb_set(), edje_object_text_class_set(), edje_object_text_insert_filter_callback_add(), edje_object_text_insert_filter_callback_del(), edje_object_text_insert_filter_callback_del_full(), edje_object_text_markup_filter_callback_add(), edje_object_text_markup_filter_callback_del(), edje_object_text_markup_filter_callback_del_full(), edje_object_thaw(), edje_object_update_hints_get(), and edje_object_update_hints_set().
_edje_file_add()
void _edje_file_add (Edje * ed)
References _edje_cache_file_coll_open(), _edje_cache_file_unref(), _edje_edd_edje_file, _Edje::collection, _Edje::file, _Edje::group, _Edje::load_error, and _Edje::path.
_edje_file_cache_shutdown()
void _edje_file_cache_shutdown (void)
References edje_file_cache_flush().
_edje_file_del()
void _edje_file_del (Edje * ed)
References _edje_anim_count, _edje_animators, _edje_block_violate(), _edje_box_layout_free_data(), _edje_cache_coll_unref(), _edje_cache_file_unref(), _edje_callbacks_del(), _edje_callbacks_focus_del(), _edje_collection_free_part_description_clean(), _edje_color_class_on_del(), _edje_entry_real_part_shutdown(), _edje_entry_shutdown(), _edje_external_parsed_params_free(), _edje_freeze_calc_count, _edje_freeze_calc_list, _edje_lua2_script_shutdown(), _edje_message_del(), _edje_programs_patterns_clean(), _edje_real_part_mp, _edje_real_part_state_mp, _edje_real_part_swallow_clear(), _edje_subobj_unregister(), _edje_text_part_on_del(), _edje_textblock_styles_del(), _edje_unref(), _edje_user_definition_free(), _edje_var_shutdown(), _Edje::actions, _Edje_Real_Part::anim, _Edje::collection, _Edje_Real_Part::custom, _Edje_Real_Part_State::description, _Edje_Real_Part::drag, _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_GROUP, _Edje_Part::entry_mode, _Edje_Real_Part_State::external_params, _Edje::file, _Edje::focused_part, _Edje_File::free_strings, _Edje::freeze_calc, _Edje::groups, _Edje_Real_Part::items, _Edje::L, _Edje::obj, _Edje_Real_Part::object, _Edje_Real_Part::param1, _Edje_Real_Part::param2, _Edje_Real_Part::part, _Edje_Part_Collection::parts, _Edje_Part_Collection::parts_count, _Edje::pending_actions, _Edje_Real_Part_State::set, _Edje::subobjs, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, _Edje::table_programs, _Edje::table_programs_size, _Edje_Real_Part::text, _Edje_Pending_Program::timer, _Edje_Part::type, and _Edje::user_defined.
Referenced by _edje_del().
_edje_file_free()
void _edje_file_free (Edje_File * edf)
References _edje_cache_coll_flush(), _edje_textblock_style_cleanup(), _Edje_File::collection, _Edje_File::collection_cache, _Edje_File::collection_patterns, _Edje_File::color_classes, _Edje_File::color_hash, _Edje_File::compiler, _Edje_File::data, edje_match_patterns_free(), _Edje_File::ef, _Edje_External_Directory::entries, _Edje_Image_Directory::entries, _Edje_Image_Directory_Set::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, _Edje_File::external_dir, _Edje_File::fonts, _Edje_File::free_strings, HASH_FREE, _Edje_File::image_dir, _Edje_Sound_Sample::name, _Edje_Sound_Tone::name, _Edje_Color_Class::name, _Edje_File::path, _Edje_Sound_Directory::samples, _Edje_Sound_Directory::samples_count, _Edje_Image_Directory::sets, _Edje_Image_Directory::sets_count, _Edje_Sound_Sample::snd_src, _Edje_File::sound_dir, _Edje_Sound_Directory::tones, and _Edje_Sound_Directory::tones_count.
Referenced by _edje_cache_file_unref().
_edje_freeze()
int _edje_freeze (Edje * ed)
References _Edje::freeze.
Referenced by _edje_emit_handle(), _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), _edje_timer_cb(), edje_object_animation_set(), and edje_object_freeze().
_edje_lib_ref()
void _edje_lib_ref (void)
Referenced by edje_object_add().
_edje_lib_unref()
void _edje_lib_unref (void)
_edje_lua2_error_full()
void _edje_lua2_error_full (const char * file, const char * fnc, int line, lua_State * L, int err_code)
References _edje_default_log_dom.
_edje_lua2_script_func_hide()
void _edje_lua2_script_func_hide (Edje * ed)
References _edje_lua2_error, and _Edje::L.
Referenced by _edje_lua_script_only_hide().
_edje_lua2_script_func_message()
void _edje_lua2_script_func_message (Edje * ed, Edje_Message * em)
References _edje_lua2_error, EDJE_MESSAGE_FLOAT, EDJE_MESSAGE_FLOAT_SET, EDJE_MESSAGE_INT, EDJE_MESSAGE_INT_SET, EDJE_MESSAGE_NONE, EDJE_MESSAGE_SIGNAL, EDJE_MESSAGE_STRING, EDJE_MESSAGE_STRING_FLOAT, EDJE_MESSAGE_STRING_FLOAT_SET, EDJE_MESSAGE_STRING_INT, EDJE_MESSAGE_STRING_INT_SET, EDJE_MESSAGE_STRING_SET, _Edje_Message::id, _Edje::L, _Edje_Message::msg, and _Edje_Message::type.
Referenced by _edje_lua_script_only_message().
_edje_lua2_script_func_move()
void _edje_lua2_script_func_move (Edje * ed)
References _edje_lua2_error, _Edje::L, _Edje::x, and _Edje::y.
Referenced by _edje_lua_script_only_move().
_edje_lua2_script_func_resize()
void _edje_lua2_script_func_resize (Edje * ed)
References _edje_lua2_error, _Edje::h, _Edje::L, and _Edje::w.
Referenced by _edje_lua_script_only_resize().
_edje_lua2_script_func_show()
void _edje_lua2_script_func_show (Edje * ed)
References _edje_lua2_error, and _Edje::L.
Referenced by _edje_lua_script_only_show().
_edje_lua2_script_func_shutdown()
void _edje_lua2_script_func_shutdown (Edje * ed)
References _edje_lua2_error, _edje_lua2_script_shutdown(), and _Edje::L.
Referenced by _edje_lua_script_only_shutdown().
_edje_lua2_script_func_signal()
void _edje_lua2_script_func_signal (Edje * ed, const char * sig, const char * src)
References _edje_lua2_error, and _Edje::L.
Referenced by _edje_emit_handle().
_edje_lua2_script_init()
void _edje_lua2_script_init (Edje * ed)
References _Edje::L, and MAX_LUA_MEM.
Referenced by _edje_lua_script_only_init().
_edje_lua2_script_load()
void _edje_lua2_script_load (Edje_Part_Collection * edc, void * data, int size)
_edje_lua2_script_shutdown()
void _edje_lua2_script_shutdown (Edje * ed)
References ERR, _Edje_Lua_Obj::free_func, _Edje::L, and _Edje::lua_objs.
Referenced by _edje_file_del(), and _edje_lua2_script_func_shutdown().
_edje_lua2_script_unload()
void _edje_lua2_script_unload (Edje_Part_Collection * edc)
_edje_lua_free_reg()
void _edje_lua_free_reg (lua_State * L, void * ptr)
_edje_lua_free_thread()
void _edje_lua_free_thread (Edje * ed, lua_State * L)
_edje_lua_get_reg()
void _edje_lua_get_reg (lua_State * L, void * ptr)
_edje_lua_group_fn_new()
void _edje_lua_group_fn_new (Edje * ed)
_edje_lua_init()
void _edje_lua_init ()
_edje_lua_new_reg()
void _edje_lua_new_reg (lua_State * L, int index, void * ptr)
_edje_lua_new_thread()
lua_State* _edje_lua_new_thread (Edje * ed, lua_State * L)
_edje_lua_script_fn_new()
void _edje_lua_script_fn_new (Edje * ed)
_edje_lua_script_only()
Eina_Bool _edje_lua_script_only (Edje * ed)
References _Edje::collection, and _Edje_Part_Collection::lua_script_only.
_edje_lua_script_only_hide()
void _edje_lua_script_only_hide (Edje * ed)
References _edje_lua2_script_func_hide(), _Edje::collection, and _Edje::L.
_edje_lua_script_only_init()
void _edje_lua_script_only_init (Edje * ed)
References _edje_lua2_script_init(), and _Edje::collection.
_edje_lua_script_only_message()
void _edje_lua_script_only_message (Edje * ed, Edje_Message * em)
References _edje_lua2_script_func_message(), _Edje::collection, and _Edje::L.
Referenced by _edje_message_process().
_edje_lua_script_only_move()
void _edje_lua_script_only_move (Edje * ed)
References _edje_lua2_script_func_move(), _Edje::collection, and _Edje::L.
_edje_lua_script_only_resize()
void _edje_lua_script_only_resize (Edje * ed)
References _edje_lua2_script_func_resize(), _Edje::collection, and _Edje::L.
_edje_lua_script_only_show()
void _edje_lua_script_only_show (Edje * ed)
References _edje_lua2_script_func_show(), _Edje::collection, and _Edje::L.
_edje_lua_script_only_shutdown()
void _edje_lua_script_only_shutdown (Edje * ed)
References _edje_lua2_script_func_shutdown(), _Edje::collection, and _Edje::L.
_edje_lua_shutdown()
void _edje_lua_shutdown ()
_edje_lua_state_get()
lua_State* _edje_lua_state_get ()
_edje_message_cb_set()
void _edje_message_cb_set (Edje * ed, void(*)(void *data, Evas_Object *obj, Edje_Message_Type type, int id, void *msg) func, void * data)
References _edje_fetch(), _Edje::data, _Edje::func, _Edje::message, and _Edje::subobjs.
Referenced by edje_object_message_handler_set().
_edje_message_del()
void _edje_message_del (Edje * ed)
References _Edje::message, and _Edje::num.
Referenced by _edje_del(), and _edje_file_del().
_edje_message_free()
void _edje_message_free (Edje_Message * em)
References _Edje_Message_String_Set::count, _Edje_Message_Signal_Data::data, _Edje_Message_Signal::data, EDJE_MESSAGE_FLOAT, EDJE_MESSAGE_FLOAT_SET, EDJE_MESSAGE_INT, EDJE_MESSAGE_INT_SET, EDJE_MESSAGE_NONE, EDJE_MESSAGE_SIGNAL, EDJE_MESSAGE_STRING, EDJE_MESSAGE_STRING_FLOAT, EDJE_MESSAGE_STRING_FLOAT_SET, EDJE_MESSAGE_STRING_INT, EDJE_MESSAGE_STRING_INT_SET, EDJE_MESSAGE_STRING_SET, _Edje_Message_Signal_Data::free_func, _Edje_Message::msg, _Edje_Message_Signal_Data::ref, _Edje_Message_Signal::sig, _Edje_Message_Signal::src, _Edje_Message_String::str, _Edje_Message_String_Set::str, _Edje_Message_String_Int::str, _Edje_Message_String_Float::str, _Edje_Message_String_Int_Set::str, _Edje_Message_String_Float_Set::str, and _Edje_Message::type.
_edje_message_init()
void _edje_message_init (void)
_edje_message_new()
Edje_Message* _edje_message_new (Edje * ed, Edje_Queue queue, Edje_Message_Type type, int id)
References _Edje_Message::edje, _Edje_Message::id, _Edje::message, _Edje::num, _Edje_Message::queue, type, and _Edje_Message::type.
Referenced by _edje_message_propornot_send().
_edje_message_parameters_push()
void _edje_message_parameters_push (Edje_Message * em)
References _Edje::collection, _Edje_Message::edje, EDJE_MESSAGE_FLOAT, EDJE_MESSAGE_FLOAT_SET, EDJE_MESSAGE_INT, EDJE_MESSAGE_INT_SET, EDJE_MESSAGE_NONE, EDJE_MESSAGE_STRING, EDJE_MESSAGE_STRING_FLOAT, EDJE_MESSAGE_STRING_FLOAT_SET, EDJE_MESSAGE_STRING_INT, EDJE_MESSAGE_STRING_INT_SET, EDJE_MESSAGE_STRING_SET, _Edje_Message::id, _Edje_Message::msg, _Edje_Part_Collection::script, and _Edje_Message::type.
Referenced by _edje_message_process(), and _edje_script_only_message().
_edje_message_process()
void _edje_message_process (Edje_Message * em)
References _edje_embryo_globals_init(), _edje_embryo_script_reset(), _edje_emit_handle(), _edje_lua_script_only_message(), _edje_message_parameters_push(), _edje_script_only(), _edje_script_only_message(), _Edje::collection, _Edje::data, _Edje_Message::edje, EDJE_MESSAGE_SIGNAL, EDJE_QUEUE_APP, ERR, _Edje::file, _Edje::func, _Edje_Message::id, _Edje::L, _Edje::message, _Edje_Message::msg, _Edje::obj, _Edje_Part_Collection::part, _Edje_File::path, _Edje_Message::propagated, _Edje_Message::queue, _Edje_Part_Collection::script, and _Edje_Message::type.
_edje_message_propornot_send()
void _edje_message_propornot_send (Edje * ed, Edje_Queue queue, Edje_Message_Type type, int id, void * emsg, Eina_Bool prop)
References _edje_message_new(), _Edje_Message::propagated, and type.
Referenced by _edje_message_send().
_edje_message_queue_clear()
void _edje_message_queue_clear (void)
Referenced by _edje_message_shutdown().
_edje_message_queue_process()
void _edje_message_queue_process (void)
Referenced by edje_message_signal_process().
_edje_message_send()
void _edje_message_send (Edje * ed, Edje_Queue queue, Edje_Message_Type type, int id, void * emsg)
References _edje_message_propornot_send(), and type.
Referenced by _edje_emit_full().
_edje_message_shutdown()
void _edje_message_shutdown (void)
References _edje_message_queue_clear().
_edje_module_handle_load()
Eina_Module* _edje_module_handle_load (const char * module)
References _modules_paths, _registered_modules, and EDJE_MODULE_NAME.
Referenced by edje_module_load().
_edje_module_init()
void _edje_module_init ()
References _modules_paths, and _registered_modules.
_edje_module_shutdown()
void _edje_module_shutdown ()
References _modules_found, _modules_paths, and _registered_modules.
_edje_multisense_init()
void _edje_multisense_init (void)
_edje_multisense_internal_sound_sample_play()
Eina_Bool _edje_multisense_internal_sound_sample_play (Edje * ed, const char * sample_name, const double speed)
References _Edje_Multisense_Sound_Action::action, BUF_LEN, _Edje_Multisense_Sound_Action::ed, EDJE_PLAY_SAMPLE, ERR, _Edje_Multisense_Sound_Action::sample, _Edje_Sample_Action::sample_name, _Edje_Sample_Action::speed, and _Edje_Multisense_Sound_Action::type.
Referenced by _edje_program_run().
_edje_multisense_internal_sound_tone_play()
Eina_Bool _edje_multisense_internal_sound_tone_play (Edje * ed, const char * tone_name, const double duration)
References _Edje_Multisense_Sound_Action::action, BUF_LEN, _Edje_Tone_Action::duration, _Edje_Multisense_Sound_Action::ed, EDJE_PLAY_TONE, ERR, _Edje_Multisense_Sound_Action::tone, _Edje_Tone_Action::tone_name, and _Edje_Multisense_Sound_Action::type.
Referenced by _edje_program_run().
_edje_multisense_shutdown()
void _edje_multisense_shutdown (void)
_edje_object_file_set_internal()
int _edje_object_file_set_internal (Evas_Object * obj, const char * file, const char * group, const char * parent, Eina_List * group_path)
References _edje_fetch(), _Edje::file, _Edje::group, _Edje_File::mtime, and _Edje::path.
_edje_object_orientation_inform()
void _edje_object_orientation_inform (Evas_Object * obj)
References edje_object_mirrored_get(), and edje_object_signal_emit().
Referenced by edje_object_file_set(), and edje_object_mirrored_set().
_edje_object_part_swallow_changed_hints_cb()
void _edje_object_part_swallow_changed_hints_cb (void * data, Evas * e, Evas_Object * obj, void * event_info)
_edje_object_part_swallow_free_cb()
void _edje_object_part_swallow_free_cb (void * data, Evas * e, Evas_Object * obj, void * event_info)
_edje_object_part_text_raw_set()
Eina_Bool _edje_object_part_text_raw_set (Evas_Object * obj, Edje_Real_Part * rp, const char * part, const char * text)
References _edje_entry_text_markup_set(), _edje_recalc(), _Edje::data, _Edje::dirty, _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, _Edje_Part::entry_mode, _Edje::func, _Edje_Real_Part::part, _Edje::recalc_call, _Edje::recalc_hints, _Edje_Real_Part::text, and _Edje::text_change.
Referenced by edje_object_part_text_escaped_set(), edje_object_part_text_set(), and edje_object_part_text_unescaped_set().
_edje_object_smart_class_get()
const Edje_Smart_Api* _edje_object_smart_class_get (void)
References _edje_object_smart_set().
_edje_object_smart_set()
void _edje_object_smart_set (Edje_Smart_Api * sc)
References _Edje_Smart_Api::base.
Referenced by _edje_object_smart_class_get().
_edje_part_description_apply()
void _edje_part_description_apply (Edje * ed, Edje_Real_Part * ep, const char * d1, double v1, const char * d2, double v2)
References _edje_external_parsed_params_free(), _edje_part_description_find(), _edje_real_part_state_mp, _Edje_Real_Part::chosen_description, _Edje_Part::default_desc, _Edje_Real_Part_State::description, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_IMAGE, _Edje_Real_Part_State::external_params, _Edje_Part_Description_Image::image, _Edje_Real_Part::param1, _Edje_Real_Part::param2, _Edje_Real_Part::part, _Edje_Real_Part_State::set, _Edje_Real_Part::swallowed_object, _Edje_Part_Description_Spec_Image::tweens_count, and _Edje_Part::type.
Referenced by _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), and edje_object_mirrored_set().
_edje_part_description_find()
Edje_Part_Description_Common* _edje_part_description_find (Edje * ed, Edje_Real_Part * rp, const char * name, double val)
References _Edje_Part_Description_List::desc_count, _Edje_Part_Description_List::desc_rtl, edje_object_mirrored_get(), name, _Edje::obj, _Edje_Part::other, and _Edje_Real_Part::part.
Referenced by _edje_part_description_apply().
_edje_part_dragable_calc()
int _edje_part_dragable_calc (Edje * ed, Edje_Real_Part * ep, FLOAT_T * x, FLOAT_T * y)
_edje_part_pos_set()
void _edje_part_pos_set (Edje * ed, Edje_Real_Part * ep, int mode, FLOAT_T pos, FLOAT_T v1, FLOAT_T v2)
References ADD, CLAMP, COS, _Edje_Real_Part::description_pos, _Edje::dirty, DIV2, EDJE_TWEEN_MODE_ACCELERATE, EDJE_TWEEN_MODE_ACCELERATE_FACTOR, EDJE_TWEEN_MODE_BOUNCE, EDJE_TWEEN_MODE_DECELERATE, EDJE_TWEEN_MODE_DECELERATE_FACTOR, EDJE_TWEEN_MODE_DIVISOR_INTERP, EDJE_TWEEN_MODE_LINEAR, EDJE_TWEEN_MODE_MASK, EDJE_TWEEN_MODE_SINUSOIDAL, EDJE_TWEEN_MODE_SINUSOIDAL_FACTOR, EDJE_TWEEN_MODE_SPRING, FLOAT_T, FROM_DOUBLE, FROM_INT, MUL, PI, _Edje::recalc_call, SIN, SUB, TO_DOUBLE, and ZERO.
Referenced by _edje_program_end(), _edje_program_run(), and _edje_program_run_iterate().
_edje_part_recalc()
void _edje_part_recalc (Edje * ed, Edje_Real_Part * ep, int flags, Edje_Calc_Params * state)
References _edje_fetch(), _edje_recalc_do(), _Edje_Real_Part::calculated, _Edje_Real_Part::calculating, _Edje_Real_Part::chosen_description, _Edje_Real_Part_Drag::confine_to, _Edje_Real_Part_State::description, _Edje_Real_Part::description_pos, _Edje_Real_Part::drag, edje_object_scale_set(), edje_object_update_hints_get(), edje_object_update_hints_set(), EDJE_PART_TYPE_GRADIENT, EDJE_PART_TYPE_GROUP, EDJE_PART_TYPE_PROXY, ERR, FLAG_NONE, FLAG_X, FLAG_XY, FLAG_Y, FLOAT_T, FROM_DOUBLE, _Edje_Size::limit, _Edje_Part_Description_Common::min, _Edje_Part::name, _Edje_Real_Part::param1, _Edje_Real_Part::param2, _Edje_Real_Part::part, _Edje_Real_Part_State::rel1_to_x, _Edje_Real_Part_State::rel1_to_y, _Edje_Real_Part_State::rel2_to_x, _Edje_Real_Part_State::rel2_to_y, _Edje_Part::scale, _Edje::scale, _Edje::state, _Edje_Real_Part::swallowed_object, TO_DOUBLE, _Edje_Part::type, and ZERO.
Referenced by _edje_part_recalc_1(), _edje_program_run(), and _edje_recalc_do().
_edje_part_recalc_1()
void _edje_part_recalc_1 (Edje * ed, Edje_Real_Part * ep)
References _edje_part_recalc(), and FLAG_XY.
_edje_pending_timer_cb()
Eina_Bool _edje_pending_timer_cb (void * data)
References _edje_program_run(), _Edje_Pending_Program::edje, _Edje::pending_actions, and _Edje_Pending_Program::program.
Referenced by _edje_program_run().
_edje_program_end()
void _edje_program_end (Edje * ed, Edje_Running_Program * runp)
References _edje_anim_count, _edje_animators, _edje_freeze(), _edje_part_description_apply(), _edje_part_pos_set(), _edje_recalc(), _edje_ref(), _edje_thaw(), _edje_unref(), _Edje::actions, _Edje::delete_me, _Edje_Running_Program::delete_me, _Edje_Program_Target::id, _Edje_Program::mode, _Edje_Real_Part::program, _Edje_Running_Program::program, _Edje_Program::state, _Edje::table_parts, _Edje::table_parts_size, _Edje_Program::targets, _Edje_Program::tween, _Edje_Program::v1, _Edje_Program::v2, _Edje_Program::value, _Edje::walking_actions, and ZERO.
Referenced by _edje_program_run().
_edje_program_insert()
EAPI void _edje_program_insert (Edje_Part_Collection * ed, Edje_Program * p)
References _Edje_Part_Collection::nocmp, _Edje_Part_Collection::nocmp_count, _Edje_Part_Collection::programs, _Edje_Program::signal, _Edje_Program::source, _Edje_Part_Collection::strcmp, and _Edje_Part_Collection::strcmp_count.
_edje_program_remove()
EAPI void _edje_program_remove (Edje_Part_Collection * ed, Edje_Program * p)
References _Edje_Part_Collection::nocmp, _Edje_Part_Collection::nocmp_count, _Edje_Part_Collection::programs, _Edje_Program::signal, _Edje_Program::source, _Edje_Part_Collection::strcmp, and _Edje_Part_Collection::strcmp_count.
Referenced by edje_edit_program_del(), edje_edit_program_signal_set(), and edje_edit_program_source_set().
_edje_program_run()
void _edje_program_run (Edje * ed, Edje_Program * pr, Eina_Bool force, const char * ssig, const char * ssrc)
References _edje_anim_count, _edje_animators, _edje_block(), _edje_block_break(), _edje_dragable_pos_set(), _edje_embryo_test_run(), _edje_emit(), _edje_freeze(), _edje_multisense_internal_sound_sample_play(), _edje_multisense_internal_sound_tone_play(), _edje_part_description_apply(), _edje_part_pos_set(), _edje_part_recalc(), _edje_pending_timer_cb(), _edje_program_end(), _edje_program_run(), _edje_recalc(), _edje_recalc_do(), _edje_ref(), _edje_timer, _edje_timer_cb(), _Edje_Program::action, _Edje::actions, _Edje_Program::after, _Edje_Real_Part_Drag::count, _Edje_Real_Part::current, _Edje::delete_me, _Edje_Real_Part_State::description, _Edje_Real_Part_Drag::down, _Edje_Real_Part::drag, _Edje_Part::dragable, _Edje_Program::dst, _Edje_Program::duration, _Edje_Running_Program::edje, _Edje_Pending_Program::edje, EDJE_ACTION_TYPE_ACTION_STOP, EDJE_ACTION_TYPE_DRAG_VAL_PAGE, EDJE_ACTION_TYPE_DRAG_VAL_SET, EDJE_ACTION_TYPE_DRAG_VAL_STEP, EDJE_ACTION_TYPE_FOCUS_OBJECT, EDJE_ACTION_TYPE_FOCUS_SET, EDJE_ACTION_TYPE_PARAM_COPY, EDJE_ACTION_TYPE_SCRIPT, EDJE_ACTION_TYPE_SIGNAL_EMIT, EDJE_ACTION_TYPE_SOUND_SAMPLE, EDJE_ACTION_TYPE_SOUND_TONE, EDJE_ACTION_TYPE_STATE_SET, EDJE_TWEEN_MODE_OPT_FROM_CURRENT, ERR, FLAG_XY, _Edje::focused_part, _Edje_Program::from, _Edje::group, _Edje_Program::id, _Edje_Program_Target::id, _Edje_Program_After::id, _Edje_Program::in, _Edje_Program::mode, _Edje_Program::name, _Edje_Part::name, _Edje_Part_Description_Common::name, _Edje::no_anim, _Edje::obj, _Edje_Real_Part::object, _Edje_Real_Part_Drag::page, _Edje_Program::param, _Edje_Real_Part::param1, _Edje_Real_Part::part, _Edje::path, _Edje::pending_actions, _Edje_Real_Part::program, _Edje_Running_Program::program, _Edje_Pending_Program::program, _Edje_Program::range, _Edje_Program::sample_name, _Edje_Program::speed, _Edje_Program::src, _Edje_Running_Program::start_time, _Edje_Program::state, _Edje_Part_Description_Common::state, _Edje_Program::state2, _Edje_Real_Part_Drag::step, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, _Edje::table_programs, _Edje::table_programs_size, _Edje_Program::targets, _Edje_Program::time, _Edje_Pending_Program::timer, _Edje_Program::tone_name, _Edje_Program::tween, _Edje_Program::v1, _Edje_Program::v2, _Edje_Real_Part_Drag::val, _Edje_Program::value, _Edje_Part_Description_Common::value, _Edje_Program::value2, _Edje_Position_Scale::x, _Edje_Part_Dragable::x, _Edje_Position_Scale::y, _Edje_Part_Dragable::y, and ZERO.
Referenced by _edje_emit_handle(), _edje_pending_timer_cb(), _edje_program_run(), _edje_program_run_iterate(), and edje_edit_program_run().
_edje_program_run_iterate()
Eina_Bool _edje_program_run_iterate (Edje_Running_Program * runp, double tim)
References _edje_anim_count, _edje_animators, _edje_block(), _edje_block_break(), _edje_freeze(), _edje_part_description_apply(), _edje_part_pos_set(), _edje_program_run(), _edje_recalc(), _edje_ref(), _edje_thaw(), _edje_unblock(), _edje_unref(), _Edje::actions, _Edje_Program::after, _Edje::delete_me, _Edje_Running_Program::delete_me, DIV, _Edje_Running_Program::edje, FLOAT_T, FROM_DOUBLE, FROM_INT, _Edje_Program_Target::id, _Edje_Program_After::id, _Edje_Program::mode, _Edje_Real_Part::program, _Edje_Running_Program::program, _Edje_Running_Program::start_time, _Edje_Program::state, _Edje::table_parts, _Edje::table_parts_size, _Edje::table_programs, _Edje::table_programs_size, _Edje_Program::targets, _Edje_Program::time, _Edje_Program::tween, _Edje_Program::v1, _Edje_Program::v2, _Edje_Program::value, _Edje::walking_actions, and ZERO.
Referenced by _edje_timer_cb(), and edje_object_animation_set().
_edje_programs_patterns_clean()
void _edje_programs_patterns_clean (Edje * ed)
References _edje_signals_sources_patterns_clean(), edje_match_signal_source_free(), _Edje_Signals_Sources_Patterns::exact_match, _Edje::patterns, _Edje_Signals_Sources_Patterns::programs, _Edje::programs, and _Edje_Signals_Sources_Patterns::u.
Referenced by _edje_file_del().
_edje_programs_patterns_init()
void _edje_programs_patterns_init (Edje * ed)
References _Edje::collection, EDJE_DUMP_PROGRAM, EDJE_LOAD_PROGRAMS_ADD, edje_match_program_hash_build(), edje_match_programs_signal_init(), edje_match_programs_source_init(), _Edje_Signals_Sources_Patterns::exact_match, _Edje_Part_Collection::fnmatch_count, _Edje::group, INF, _Edje_Part_Collection::nocmp_count, _Edje::patterns, _Edje_Part_Collection::programs, _Edje_Signals_Sources_Patterns::programs, _Edje::programs, _Edje_Signals_Sources_Patterns::signals_patterns, _Edje_Signals_Sources_Patterns::sources_patterns, _Edje_Part_Collection::strcmp, _Edje_Part_Collection::strcmp_count, _Edje_Part_Collection::strncmp_count, _Edje_Part_Collection::strrncmp_count, and _Edje_Signals_Sources_Patterns::u.
_edje_real_part_box_append()
Eina_Bool _edje_real_part_box_append (Edje_Real_Part * rp, Evas_Object * child_obj)
References _edje_box_layout_add_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_append().
_edje_real_part_box_insert_at()
Eina_Bool _edje_real_part_box_insert_at (Edje_Real_Part * rp, Evas_Object * child_obj, unsigned int pos)
References _edje_box_layout_add_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_insert_at().
_edje_real_part_box_insert_before()
Eina_Bool _edje_real_part_box_insert_before (Edje_Real_Part * rp, Evas_Object * child_obj, const Evas_Object * ref)
References _edje_box_layout_add_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_insert_before().
_edje_real_part_box_prepend()
Eina_Bool _edje_real_part_box_prepend (Edje_Real_Part * rp, Evas_Object * child_obj)
References _edje_box_layout_add_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_prepend().
_edje_real_part_box_remove()
Evas_Object* _edje_real_part_box_remove (Edje_Real_Part * rp, Evas_Object * child_obj)
References _edje_box_layout_remove_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_remove().
_edje_real_part_box_remove_all()
Eina_Bool _edje_real_part_box_remove_all (Edje_Real_Part * rp, Eina_Bool clear)
References _edje_box_layout_remove_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_remove_all().
_edje_real_part_box_remove_at()
Evas_Object* _edje_real_part_box_remove_at (Edje_Real_Part * rp, unsigned int pos)
References _edje_box_layout_remove_child(), and _Edje_Real_Part::object.
Referenced by edje_object_part_box_remove_at().
_edje_real_part_get()
Edje_Real_Part* _edje_real_part_get (const Edje * ed, const char * part)
References _Edje_Part::name, _Edje_Real_Part::part, _Edje::table_parts, and _Edje::table_parts_size.
Referenced by _edje_emit_full(), _edje_emit_handle(), _edje_real_part_recursive_get_helper(), edje_edit_part_clip_to_set(), edje_edit_part_name_set(), edje_edit_program_target_add(), and edje_edit_program_target_del().
_edje_real_part_recursive_get()
Edje_Real_Part* _edje_real_part_recursive_get (const Edje * ed, const char * part)
References _edje_real_part_recursive_get_helper(), and EDJE_PART_PATH_SEPARATOR_STRING.
Referenced by _edje_real_part_recursive_get_helper(), _edje_user_definition_free(), edje_object_part_box_append(), edje_object_part_box_insert_at(), edje_object_part_box_insert_before(), edje_object_part_box_prepend(), edje_object_part_box_remove(), edje_object_part_box_remove_all(), edje_object_part_box_remove_at(), edje_object_part_drag_dir_get(), edje_object_part_drag_page(), edje_object_part_drag_page_get(), edje_object_part_drag_page_set(), edje_object_part_drag_size_get(), edje_object_part_drag_size_set(), edje_object_part_drag_step(), edje_object_part_drag_step_get(), edje_object_part_drag_step_set(), edje_object_part_drag_value_get(), edje_object_part_drag_value_set(), edje_object_part_exists(), edje_object_part_external_content_get(), edje_object_part_external_object_get(), edje_object_part_external_param_get(), edje_object_part_external_param_set(), edje_object_part_external_param_type_get(), edje_object_part_geometry_get(), edje_object_part_object_get(), edje_object_part_state_get(), edje_object_part_swallow(), edje_object_part_swallow_get(), edje_object_part_table_child_get(), edje_object_part_table_clear(), edje_object_part_table_col_row_size_get(), edje_object_part_table_pack(), edje_object_part_table_unpack(), edje_object_part_text_anchor_geometry_get(), edje_object_part_text_anchor_list_get(), edje_object_part_text_append(), edje_object_part_text_autocapital_type_get(), edje_object_part_text_autocapital_type_set(), edje_object_part_text_cursor_begin_set(), edje_object_part_text_cursor_content_get(), edje_object_part_text_cursor_coord_set(), edje_object_part_text_cursor_copy(), edje_object_part_text_cursor_down(), edje_object_part_text_cursor_end_set(), edje_object_part_text_cursor_geometry_get(), edje_object_part_text_cursor_is_format_get(), edje_object_part_text_cursor_is_visible_format_get(), edje_object_part_text_cursor_line_begin_set(), edje_object_part_text_cursor_line_end_set(), edje_object_part_text_cursor_next(), edje_object_part_text_cursor_pos_get(), edje_object_part_text_cursor_pos_set(), edje_object_part_text_cursor_prev(), edje_object_part_text_cursor_up(), edje_object_part_text_escaped_set(), edje_object_part_text_get(), edje_object_part_text_imf_context_get(), edje_object_part_text_imf_context_reset(), edje_object_part_text_input_panel_enabled_get(), edje_object_part_text_input_panel_enabled_set(), edje_object_part_text_input_panel_hide(), edje_object_part_text_input_panel_imdata_get(), edje_object_part_text_input_panel_imdata_set(), edje_object_part_text_input_panel_language_get(), edje_object_part_text_input_panel_language_set(), edje_object_part_text_input_panel_layout_get(), edje_object_part_text_input_panel_layout_set(), edje_object_part_text_input_panel_return_key_disabled_get(), edje_object_part_text_input_panel_return_key_disabled_set(), edje_object_part_text_input_panel_return_key_type_get(), edje_object_part_text_input_panel_return_key_type_set(), edje_object_part_text_input_panel_show(), edje_object_part_text_insert(), edje_object_part_text_item_geometry_get(), edje_object_part_text_item_list_get(), edje_object_part_text_prediction_allow_get(), edje_object_part_text_prediction_allow_set(), edje_object_part_text_select_abort(), edje_object_part_text_select_all(), edje_object_part_text_select_allow_set(), edje_object_part_text_select_begin(), edje_object_part_text_select_extend(), edje_object_part_text_select_none(), edje_object_part_text_selection_get(), edje_object_part_text_set(), edje_object_part_text_style_user_peek(), edje_object_part_text_style_user_pop(), edje_object_part_text_style_user_push(), edje_object_part_text_unescaped_get(), edje_object_part_text_unescaped_set(), and edje_object_part_text_user_insert().
_edje_real_part_swallow()
void _edje_real_part_swallow (Edje_Real_Part * rp, Evas_Object * obj_swallow, Eina_Bool hints_update)
References _Edje_Real_Part::edje, edje_object_part_unswallow(), _Edje::obj, and _Edje_Real_Part::swallowed_object.
Referenced by edje_object_part_swallow().
_edje_real_part_swallow_clear()
void _edje_real_part_swallow_clear (Edje_Real_Part * rp)
References _edje_callbacks_del(), _edje_callbacks_focus_del(), _edje_object_part_swallow_changed_hints_cb(), _edje_object_part_swallow_free_cb(), _Edje_Real_Part::edje, _Edje_Part::mouse_events, _Edje_Real_Part::part, and _Edje_Real_Part::swallowed_object.
Referenced by _edje_file_del(), _edje_user_definition_free(), and edje_object_part_unswallow().
_edje_real_part_table_clear()
void _edje_real_part_table_clear (Edje_Real_Part * rp, Eina_Bool clear)
References _Edje_Real_Part::object.
Referenced by edje_object_part_table_clear().
_edje_real_part_table_pack()
Eina_Bool _edje_real_part_table_pack (Edje_Real_Part * rp, Evas_Object * child_obj, unsigned short col, unsigned short row, unsigned short colspan, unsigned short rowspan)
References _Edje_Real_Part::object.
Referenced by edje_object_part_table_pack().
_edje_real_part_table_unpack()
Eina_Bool _edje_real_part_table_unpack (Edje_Real_Part * rp, Evas_Object * child_obj)
References _Edje_Real_Part::object.
Referenced by edje_object_part_table_unpack().
_edje_recalc()
void _edje_recalc (Edje * ed)
References _edje_freeze_calc_count, _edje_freeze_calc_list, _edje_freeze_val, _Edje::calc_only, _Edje::freeze, _Edje::freeze_calc, _Edje::obj, and _Edje::recalc.
Referenced by _edje_dragable_pos_set(), _edje_object_part_text_raw_append(), _edje_object_part_text_raw_set(), _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), _edje_thaw(), edje_object_color_class_del(), edje_object_color_class_set(), edje_object_part_text_append(), edje_object_part_text_insert(), edje_object_part_text_style_user_pop(), edje_object_part_text_style_user_push(), edje_object_size_min_restricted_calc(), edje_object_text_class_set(), and edje_object_update_hints_set().
_edje_recalc_do()
void _edje_recalc_do (Edje * ed)
References _edje_emit(), _edje_part_recalc(), _Edje::calc_only, _Edje_Real_Part::calculated, _Edje_Real_Part::calculating, _Edje_Real_Part::chosen_description, _Edje::collection, _Edje::dirty, edje_object_size_min_calc(), EDJE_PART_LIMIT_BELOW, EDJE_PART_LIMIT_OVER, EDJE_PART_LIMIT_UNKNOWN, EDJE_PART_LIMIT_ZERO, FLAG_NONE, FLAG_XY, _Edje_Real_Part::h, _Edje::have_mapped_part, _Edje_Part_Limit::height, _Edje_Part_Description_Common::limit, _Edje_Part_Collection::limits, name, _Edje::obj, _Edje_Part_Limit::part, _Edje_Part_Collection::parts, _Edje_Part_Collection::parts_count, _Edje::recalc, _Edje::recalc_call, _Edje::recalc_hints, _Edje::state, _Edje::table_parts, _Edje::table_parts_size, _Edje::update_hints, _Edje_Real_Part::w, and _Edje_Part_Limit::width.
Referenced by _edje_part_recalc(), _edje_program_run(), _edje_user_definition_free(), edje_object_calc_force(), edje_object_mirrored_set(), edje_object_part_drag_dir_get(), edje_object_part_drag_page_get(), edje_object_part_drag_size_get(), edje_object_part_drag_step_get(), edje_object_part_drag_value_get(), edje_object_part_external_object_get(), edje_object_part_geometry_get(), edje_object_part_object_get(), edje_object_part_state_get(), edje_object_part_swallow(), edje_object_part_swallow_get(), edje_object_part_text_get(), edje_object_part_text_unescaped_get(), edje_object_part_unswallow(), edje_object_parts_extends_calc(), edje_object_perspective_set(), edje_object_preload(), edje_object_size_max_get(), edje_object_size_min_restricted_calc(), edje_perspective_global_set(), and edje_perspective_set().
_edje_ref()
void _edje_ref (Edje * ed)
References _Edje::references.
Referenced by _edje_block(), _edje_emit_handle(), _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), and _edje_timer_cb().
_edje_script_only()
Eina_Bool _edje_script_only (Edje * ed)
References _Edje::collection, _Edje_Part_Collection::script, and _Edje_Part_Collection::script_only.
Referenced by _edje_message_process().
_edje_script_only_hide()
void _edje_script_only_hide (Edje * ed)
References ADDJ, DELJ, IFFN, IFNJ, and SI.
_edje_script_only_init()
void _edje_script_only_init (Edje * ed)
References _edje_script_only_move(), CLFN, _Edje::collection, EXPF, GTFN, _Edje_Part_Collection::script, and _Edje::script_only_data.
_edje_script_only_message()
void _edje_script_only_message (Edje * ed, Edje_Message * em)
References _edje_message_parameters_push(), CLFN, IFNO, and SI.
Referenced by _edje_message_process().
_edje_script_only_move()
void _edje_script_only_move (Edje * ed)
References ADDJ, DELJ, and SI.
Referenced by _edje_script_only_init().
_edje_script_only_resize()
void _edje_script_only_resize (Edje * ed)
References ADDJ, DELJ, IFFN, and SI.
_edje_script_only_show()
void _edje_script_only_show (Edje * ed)
References ADDJ, DELJ, IFFN, IFNJ, and SI.
_edje_script_only_shutdown()
void _edje_script_only_shutdown (Edje * ed)
References CLFN, DELJ, and SI.
_edje_signals_sources_patterns_clean()
void _edje_signals_sources_patterns_clean (Edje_Signals_Sources_Patterns * ssp)
References edje_match_patterns_free(), _Edje_Signals_Sources_Patterns::signals_patterns, and _Edje_Signals_Sources_Patterns::sources_patterns.
Referenced by _edje_callbacks_patterns_clean(), and _edje_programs_patterns_clean().
_edje_subobj_register()
void _edje_subobj_register (Edje * ed, Evas_Object * ob)
References _Edje::subobjs.
_edje_subobj_unregister()
void _edje_subobj_unregister (Edje * ed, Evas_Object * ob)
References _Edje::subobjs.
Referenced by _edje_file_del().
_edje_text_class_find()
Edje_Text_Class* _edje_text_class_find (Edje * ed, const char * text_class)
References _Edje_Text_Class::name, and _Edje::text_classes.
Referenced by _edje_text_class_font_get(), and _edje_textblock_style_all_update().
_edje_text_class_font_get()
const char* _edje_text_class_font_get (Edje * ed, Edje_Part_Description_Text * chosen_desc, int * size, char ** free_later)
References _edje_text_class_find(), edje_string_get(), _Edje_Part_Description_Spec_Text::font, _Edje_Part_Description_Spec_Text::size, _Edje_Part_Description_Text::text, and _Edje_Part_Description_Spec_Text::text_class.
Referenced by _edje_text_recalc_apply().
_edje_text_class_hash_free()
void _edje_text_class_hash_free (void)
_edje_text_class_member_add()
void _edje_text_class_member_add (Edje * ed, const char * text_class)
Referenced by _edje_text_part_on_add(), and _edje_textblock_styles_add().
_edje_text_class_member_del()
void _edje_text_class_member_del (Edje * ed, const char * text_class)
Referenced by _edje_text_part_on_del(), and _edje_textblock_styles_del().
_edje_text_class_member_direct_del()
void _edje_text_class_member_direct_del (const char * text_class, void * lookup)
_edje_text_class_members_free()
void _edje_text_class_members_free (void)
_edje_text_escape()
char* _edje_text_escape (const char * text)
Referenced by edje_object_part_text_unescaped_set().
_edje_text_init()
void _edje_text_init (void)
_edje_text_part_on_add()
void _edje_text_part_on_add (Edje * ed, Edje_Real_Part * ep)
References _edje_text_class_member_add(), _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, EDJE_PART_TYPE_TEXT, _Edje_Part::other, _Edje_Real_Part::part, _Edje_Part_Description_Text::text, _Edje_Part_Description_Spec_Text::text_class, and _Edje_Part::type.
_edje_text_part_on_del()
void _edje_text_part_on_del (Edje * ed, Edje_Part * ep)
References _edje_text_class_member_del(), _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part::other, _Edje_Part_Description_Text::text, _Edje_Part_Description_Spec_Text::text_class, and _Edje_Part::type.
Referenced by _edje_file_del().
_edje_text_recalc_apply()
void _edje_text_recalc_apply (Edje * ed, Edje_Real_Part * ep, Edje_Calc_Params * params, Edje_Part_Description_Text * chosen_desc)
References _edje_fontset_append, _edje_scale, _edje_text_class_font_get(), alloca(), edje_string_get(), _Edje::file, _Edje_Part_Description_Spec_Text::fit_x, _Edje_Part_Description_Spec_Text::fit_y, FLOAT_T, _Edje_File::fonts, _Edje_Calc_Params::h, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::path, _Edje_Part::scale, _Edje::scale, _Edje_Part_Description_Spec_Text::text, _Edje_Part_Description_Text::text, _Edje_Calc_Params::text, _Edje_Real_Part::text, TO_DOUBLE, _Edje_Calc_Params::type, and _Edje_Calc_Params::w.
_edje_text_size_calc()
Evas_Font_Size _edje_text_size_calc (Evas_Font_Size size, Edje_Text_Class * tc)
References _Edje_Text_Class::size.
Referenced by _edje_textblock_style_all_update().
_edje_text_unescape()
char* _edje_text_unescape (const char * text)
Referenced by edje_object_part_text_unescaped_get().
_edje_textblock_style_all_update()
void _edje_textblock_style_all_update (Edje * ed)
References _edje_fontset_append, _edje_text_class_find(), _edje_text_size_calc(), _Edje::file, _Edje_Style_Tag::font, _Edje_Text_Class::font, _Edje_Style_Tag::font_size, _Edje_Style_Tag::key, _Edje_File::path, _Edje_Text_Class::size, _Edje_Style::style, _Edje_File::styles, _Edje_Style::tags, _Edje_Style_Tag::text_class, and _Edje_Style_Tag::value.
Referenced by edje_object_text_class_set().
_edje_textblock_style_cleanup()
void _edje_textblock_style_cleanup (Edje_File * edf)
References _Edje_Style_Tag::font, _Edje_File::free_strings, _Edje_Style_Tag::key, _Edje_Style::name, _Edje_Style::style, _Edje_File::styles, _Edje_Style::tags, _Edje_Style_Tag::text_class, and _Edje_Style_Tag::value.
Referenced by _edje_file_free().
_edje_textblock_style_parse_and_fix()
void _edje_textblock_style_parse_and_fix (Edje_File * edf)
References _edje_fontset_append, _Edje_Style_Tag::key, _Edje_File::path, _Edje_Style::style, _Edje_File::styles, and _Edje_Style::tags.
_edje_textblock_styles_add()
void _edje_textblock_styles_add (Edje * ed)
References _edje_text_class_member_add(), _Edje::file, _Edje_File::styles, _Edje_Style::tags, and _Edje_Style_Tag::text_class.
_edje_textblock_styles_del()
void _edje_textblock_styles_del (Edje * ed)
References _edje_text_class_member_del(), _Edje::file, _Edje_File::styles, _Edje_Style::tags, and _Edje_Style_Tag::text_class.
Referenced by _edje_file_del().
_edje_thaw()
int _edje_thaw (Edje * ed)
References _edje_recalc(), _Edje::freeze, and _Edje::recalc.
Referenced by _edje_program_end(), _edje_program_run_iterate(), _edje_timer_cb(), edje_object_animation_set(), and edje_object_thaw().
_edje_timer_cb()
Eina_Bool _edje_timer_cb (void * data)
_edje_unblock()
int _edje_unblock (Edje * ed)
References _edje_unref(), _Edje::block, and _Edje::block_break.
Referenced by _edje_program_run_iterate(), _edje_timer_cb(), and edje_object_animation_set().
_edje_unref()
void _edje_unref (Edje * ed)
References _edje_del(), and _Edje::references.
Referenced by _edje_file_del(), _edje_program_end(), _edje_program_run_iterate(), _edje_timer_cb(), and _edje_unblock().
_edje_user_definition_free()
void _edje_user_definition_free (Edje_User_Defined * eud)
References _edje_real_part_recursive_get(), _edje_real_part_swallow_clear(), _edje_recalc_do(), _Edje_User_Defined::box, _Edje::dirty, _Edje_User_Defined::ed, _Edje_Real_Part::edje, EDJE_USER_BOX_PACK, EDJE_USER_SWALLOW, _Edje_Size::h, _Edje_Real_Part::max, _Edje_Real_Part::min, _Edje_User_Defined::part, _Edje::recalc_call, _Edje_User_Defined::swallow, _Edje_Real_Part::swallow_params, _Edje_Real_Part::swallowed_object, _Edje_User_Defined::type, _Edje_User_Defined::u, _Edje::user_defined, and _Edje_Size::w.
Referenced by _edje_file_del(), _edje_object_part_swallow_free_cb(), edje_object_part_box_remove(), edje_object_part_box_remove_all(), edje_object_part_box_remove_at(), edje_object_part_table_unpack(), and edje_object_part_unswallow().
_edje_user_definition_remove()
void _edje_user_definition_remove (Edje_User_Defined * eud, Evas_Object * child)
References _Edje_User_Defined::ed, and _Edje::user_defined.
_edje_var_anim_add()
int _edje_var_anim_add (Edje * ed, double len, const char * fname, int val)
References _Edje_Var_Pool::animators, _Edje::collection, _Edje_Var_Animator::edje, _Edje_Var_Animator::func, _Edje_Var_Animator::id, _Edje_Var_Pool::id_count, _Edje_Var_Animator::len, _Edje_Part_Collection::script, _Edje_Var_Animator::start, _Edje_Var_Animator::val, and _Edje::var_pool.
_edje_var_anim_del()
void _edje_var_anim_del (Edje * ed, int id)
_edje_var_float_get()
double _edje_var_float_get (Edje * ed, int id)
References _edje_var_var_float_get(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_float_set()
void _edje_var_float_set (Edje * ed, int id, double v)
References _edje_var_var_float_set(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_free()
void _edje_var_free (Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_STRING, _Edje_Var::s, _Edje_Var::type, and _Edje_Var_String::v.
Referenced by _edje_var_list_remove_nth(), and _edje_var_shutdown().
_edje_var_init()
void _edje_var_init (Edje * ed)
References _Edje::collection, _Edje_Part_Collection::script, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_int_get()
int _edje_var_int_get (Edje * ed, int id)
References _edje_var_var_int_get(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_int_set()
void _edje_var_int_set (Edje * ed, int id, int v)
References _edje_var_var_int_set(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_count_get()
int _edje_var_list_count_get (Edje * ed, int id)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_float_append()
void _edje_var_list_float_append (Edje * ed, int id, double v)
References _edje_var_list_var_append(), _edje_var_new(), _edje_var_var_float_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_float_insert()
void _edje_var_list_float_insert (Edje * ed, int id, int n, double v)
References _edje_var_list_nth(), _edje_var_list_var_append(), _edje_var_list_var_prepend_relative(), _edje_var_new(), _edje_var_var_float_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_float_prepend()
void _edje_var_list_float_prepend (Edje * ed, int id, double v)
References _edje_var_list_var_prepend(), _edje_var_new(), _edje_var_var_float_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_int_append()
void _edje_var_list_int_append (Edje * ed, int id, int v)
References _edje_var_list_var_append(), _edje_var_new(), _edje_var_var_int_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_int_insert()
void _edje_var_list_int_insert (Edje * ed, int id, int n, int v)
References _edje_var_list_nth(), _edje_var_list_var_append(), _edje_var_list_var_prepend_relative(), _edje_var_new(), _edje_var_var_int_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_int_prepend()
void _edje_var_list_int_prepend (Edje * ed, int id, int v)
References _edje_var_list_var_prepend(), _edje_var_new(), _edje_var_var_int_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth()
Edje_Var* _edje_var_list_nth (Edje * ed, int id, int n)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_var_list_float_insert(), _edje_var_list_int_insert(), _edje_var_list_nth_float_get(), _edje_var_list_nth_float_set(), _edje_var_list_nth_int_get(), _edje_var_list_nth_int_set(), _edje_var_list_nth_str_get(), _edje_var_list_nth_str_set(), and _edje_var_list_str_insert().
_edje_var_list_nth_float_get()
double _edje_var_list_nth_float_get (Edje * ed, int id, int n)
References _edje_var_list_nth(), _edje_var_var_float_get(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_float_set()
void _edje_var_list_nth_float_set (Edje * ed, int id, int n, double v)
References _edje_var_list_nth(), _edje_var_var_float_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_int_get()
int _edje_var_list_nth_int_get (Edje * ed, int id, int n)
References _edje_var_list_nth(), _edje_var_var_int_get(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_int_set()
void _edje_var_list_nth_int_set (Edje * ed, int id, int n, int v)
References _edje_var_list_nth(), _edje_var_var_int_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_str_get()
const char* _edje_var_list_nth_str_get (Edje * ed, int id, int n)
References _edje_var_list_nth(), _edje_var_var_str_get(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_nth_str_set()
void _edje_var_list_nth_str_set (Edje * ed, int id, int n, const char * v)
References _edje_var_list_nth(), _edje_var_var_str_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_remove_nth()
void _edje_var_list_remove_nth (Edje * ed, int id, int n)
References _edje_var_free(), _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_str_append()
void _edje_var_list_str_append (Edje * ed, int id, const char * v)
References _edje_var_list_var_append(), _edje_var_new(), _edje_var_var_str_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_str_insert()
void _edje_var_list_str_insert (Edje * ed, int id, int n, const char * v)
References _edje_var_list_nth(), _edje_var_list_var_append(), _edje_var_list_var_prepend_relative(), _edje_var_new(), _edje_var_var_str_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_str_prepend()
void _edje_var_list_str_prepend (Edje * ed, int id, const char * v)
References _edje_var_list_var_prepend(), _edje_var_new(), _edje_var_var_str_set(), EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, EDJE_VAR_NONE, _Edje_Var_Pool::size, _Edje_Var::type, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_var_append()
void _edje_var_list_var_append (Edje * ed, int id, Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_var_list_float_append(), _edje_var_list_float_insert(), _edje_var_list_int_append(), _edje_var_list_int_insert(), _edje_var_list_str_append(), and _edje_var_list_str_insert().
_edje_var_list_var_append_relative()
void _edje_var_list_var_append_relative (Edje * ed, int id, Edje_Var * var, Edje_Var * relative)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_list_var_prepend()
void _edje_var_list_var_prepend (Edje * ed, int id, Edje_Var * var)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_var_list_float_prepend(), _edje_var_list_int_prepend(), and _edje_var_list_str_prepend().
_edje_var_list_var_prepend_relative()
void _edje_var_list_var_prepend_relative (Edje * ed, int id, Edje_Var * var, Edje_Var * relative)
References _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_MAGIC_BASE, _Edje_Var::l, _Edje_Var_Pool::size, _Edje_Var::type, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_var_list_float_insert(), _edje_var_list_int_insert(), and _edje_var_list_str_insert().
_edje_var_new()
Edje_Var* _edje_var_new (void)
Referenced by _edje_var_list_float_append(), _edje_var_list_float_insert(), _edje_var_list_float_prepend(), _edje_var_list_int_append(), _edje_var_list_int_insert(), _edje_var_list_int_prepend(), _edje_var_list_str_append(), _edje_var_list_str_insert(), and _edje_var_list_str_prepend().
_edje_var_shutdown()
void _edje_var_shutdown (Edje * ed)
References _edje_var_free(), _Edje_Var_Pool::animators, _Edje_Var::data, EDJE_VAR_LIST, EDJE_VAR_STRING, _Edje_Var::l, _Edje_Var::s, _Edje_Var_Pool::size, _Edje_Var_Timer::timer, _Edje_Var_Pool::timers, _Edje_Var::type, _Edje_Var_String::v, _Edje_Var_List::v, _Edje::var_pool, and _Edje_Var_Pool::vars.
Referenced by _edje_file_del().
_edje_var_str_get()
const char* _edje_var_str_get (Edje * ed, int id)
References _edje_var_var_str_get(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_str_set()
void _edje_var_str_set (Edje * ed, int id, const char * str)
References _edje_var_var_str_set(), EDJE_VAR_MAGIC_BASE, _Edje_Var_Pool::size, _Edje::var_pool, and _Edje_Var_Pool::vars.
_edje_var_string_id_get()
int _edje_var_string_id_get (Edje * ed, const char * string)
References _Edje::collection, and _Edje_Part_Collection::script.
_edje_var_timer_add()
int _edje_var_timer_add (Edje * ed, double in, const char * fname, int val)
References _Edje::collection, _Edje_Var_Timer::edje, _Edje_Var_Timer::func, _Edje_Var_Timer::id, _Edje_Var_Pool::id_count, _Edje_Part_Collection::script, _Edje_Var_Timer::timer, _Edje_Var_Timer::val, and _Edje::var_pool.
_edje_var_timer_del()
void _edje_var_timer_del (Edje * ed, int id)
_edje_var_var_float_get()
double _edje_var_var_float_get (Edje * ed, Edje_Var * var)
_edje_var_var_float_set()
void _edje_var_var_float_set (Edje * ed, Edje_Var * var, double v)
_edje_var_var_int_get()
int _edje_var_var_int_get (Edje * ed, Edje_Var * var)
_edje_var_var_int_set()
void _edje_var_var_int_set (Edje * ed, Edje_Var * var, int v)
_edje_var_var_str_get()
const char* _edje_var_var_str_get (Edje * ed, Edje_Var * var)
_edje_var_var_str_set()
void _edje_var_var_str_set (Edje * ed, Edje_Var * var, const char * str)
alloca()
void* alloca (size_t)
Referenced by _edje_emit_full(), _edje_emit_handle(), and _edje_text_recalc_apply().
edje_match_callback_exec()
int edje_match_callback_exec (Edje_Patterns * ppat_signal, Edje_Patterns * ppat_source, const char * signal, const char * source, Eina_List * callbacks, Edje * ed, Eina_Bool prop)
References _Edje_Patterns::ref.
edje_match_callback_hash_build()
Eina_List* edje_match_callback_hash_build (const Eina_List * callbacks, Eina_Rbtree ** tree)
References _Edje_Signal_Callback::signal, and _Edje_Signal_Callback::source.
edje_match_callback_signal_init()
Edje_Patterns* edje_match_callback_signal_init (const Eina_List * lst)
edje_match_callback_source_init()
Edje_Patterns* edje_match_callback_source_init (const Eina_List * lst)
edje_match_collection_dir_exec()
Eina_Bool edje_match_collection_dir_exec (const Edje_Patterns * ppat, const char * string)
Referenced by edje_file_group_exists().
edje_match_collection_dir_init()
Edje_Patterns* edje_match_collection_dir_init (const Eina_List * lst)
Referenced by edje_file_group_exists().
edje_match_patterns_free()
void edje_match_patterns_free (Edje_Patterns * ppat)
References _Edje_Patterns::delete_me, and _Edje_Patterns::ref.
Referenced by _edje_file_free(), _edje_signals_sources_patterns_clean(), and edje_file_group_exists().
edje_match_program_hash_build()
Eina_List* edje_match_program_hash_build (Edje_Program *const * programs, unsigned int count, Eina_Rbtree ** tree)
Referenced by _edje_programs_patterns_init().
edje_match_programs_exec()
Eina_Bool edje_match_programs_exec (const Edje_Patterns * ppat_signal, const Edje_Patterns * ppat_source, const char * signal, const char * source, Edje_Program ** programs, Eina_Bool(*)(Edje_Program *pr, void *data) func, void * data, Eina_Bool prop)
Referenced by _edje_emit_handle().
edje_match_programs_signal_init()
Edje_Patterns* edje_match_programs_signal_init (Edje_Program *const * array, unsigned int count)
Referenced by _edje_programs_patterns_init().
edje_match_programs_source_init()
Edje_Patterns* edje_match_programs_source_init (Edje_Program *const * array, unsigned int count)
Referenced by _edje_programs_patterns_init().
edje_match_signal_source_free()
void edje_match_signal_source_free (Edje_Signal_Source_Char * key, void * data)
edje_match_signal_source_hash_get()
const Eina_List* edje_match_signal_source_hash_get (const char * signal, const char * source, const Eina_Rbtree * tree)
edje_object_propagate_callback_add()
void edje_object_propagate_callback_add (Evas_Object * obj, void(*)(void *data, Evas_Object *o, const char *emission, const char *source) func, void * data)
References _edje_callbacks_patterns_clean(), _edje_fetch(), _Edje::callbacks, _Edje_Signal_Callback::data, _Edje::delete_me, _Edje_Signal_Callback::func, _Edje_Signal_Callback::just_added, _Edje::just_added_callbacks, _Edje_Signal_Callback::propagate, _Edje_Signal_Callback::signal, _Edje_Signal_Callback::source, and _Edje::walking_callbacks.
edje_string_get()
const char* edje_string_get (const Edje_String * es)
References _Edje_String::str.
Referenced by _edje_text_class_font_get(), _edje_text_recalc_apply(), edje_edit_data_value_get(), edje_edit_group_data_value_get(), edje_edit_state_font_get(), edje_edit_state_text_get(), edje_file_data_get(), and edje_object_data_get().
edje_string_id_get()
const char* edje_string_id_get (const Edje_String * es)
References _Edje_String::str.
Variable Documentation
_edje_anim_count
int _edje_anim_count extern
Referenced by _edje_file_del(), _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), and _edje_timer_cb().
_edje_animators
Eina_List* _edje_animators extern
Referenced by _edje_del(), _edje_file_del(), _edje_program_end(), _edje_program_run(), _edje_program_run_iterate(), and _edje_timer_cb().
_edje_default_log_dom
EAPI int _edje_default_log_dom extern
Referenced by _edje_lua2_error_full().
_edje_edd_edje_file
EAPI Eet_Data_Descriptor* _edje_edd_edje_file extern
Referenced by _edje_edd_shutdown(), and _edje_file_add().
_edje_edd_edje_part_collection
EAPI Eet_Data_Descriptor* _edje_edd_edje_part_collection extern
Referenced by _edje_edd_shutdown().
_edje_edjes
Eina_List* _edje_edjes extern
Referenced by edje_freeze(), edje_perspective_global_set(), edje_perspective_set(), and edje_scale_set().
_edje_fontset_append
char* _edje_fontset_append extern
Referenced by _edje_text_recalc_apply(), _edje_textblock_style_all_update(), _edje_textblock_style_parse_and_fix(), edje_fontset_append_get(), and edje_fontset_append_set().
_edje_freeze_calc_count
int _edje_freeze_calc_count extern
Referenced by _edje_file_del(), _edje_recalc(), and edje_thaw().
_edje_freeze_calc_list
Eina_List* _edje_freeze_calc_list extern
Referenced by _edje_file_del(), _edje_recalc(), and edje_thaw().
_edje_freeze_val
int _edje_freeze_val extern
Referenced by _edje_recalc(), edje_freeze(), edje_object_calc_force(), and edje_thaw().
_edje_lua_panic_jmp
jmp_buf _edje_lua_panic_jmp extern
_edje_password_show_last
Eina_Bool _edje_password_show_last extern
Referenced by edje_password_show_last_set().
_edje_password_show_last_timeout
FLOAT_T _edje_password_show_last_timeout extern
Referenced by edje_password_show_last_timeout_set().
_edje_real_part_mp
Eina_Mempool* _edje_real_part_mp extern
Referenced by _edje_file_del().
_edje_real_part_state_mp
Eina_Mempool* _edje_real_part_state_mp extern
Referenced by _edje_file_del(), and _edje_part_description_apply().
_edje_scale
FLOAT_T _edje_scale extern
Referenced by _edje_text_recalc_apply(), edje_scale_get(), and edje_scale_set().
_edje_timer
Ecore_Animator* _edje_timer extern
Referenced by _edje_program_run(), and _edje_timer_cb().
_emp_BOX
Eina_Mempool* _emp_BOX extern
_emp_EXTERNAL
Eina_Mempool* _emp_EXTERNAL extern
_emp_GROUP
Eina_Mempool* _emp_GROUP extern
_emp_IMAGE
Eina_Mempool* _emp_IMAGE extern
_emp_part
Eina_Mempool* _emp_part extern
_emp_PROXY
Eina_Mempool* _emp_PROXY extern
_emp_RECTANGLE
Eina_Mempool* _emp_RECTANGLE extern
_emp_SPACER
Eina_Mempool* _emp_SPACER extern
_emp_SWALLOW
Eina_Mempool* _emp_SWALLOW extern
_emp_TABLE
Eina_Mempool* _emp_TABLE extern
_emp_TEXT
Eina_Mempool* _emp_TEXT extern
_emp_TEXTBLOCK
Eina_Mempool* _emp_TEXTBLOCK extern
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59