src/lib/edje_load.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_load.c File Reference
Data Structures
struct _Edje_Drag_Items
struct _Edje_Table_Items
Macros
#define EDJE_DUMP_PROGRAM(Section)
#define EDJE_LOAD_BUILD_TABLE(Array, Ed, It, Tmp)
#define EDJE_LOAD_PROGRAM_FREE(Array, Ec, It, FreeStrings)
#define EDJE_LOAD_PROGRAMS_ADD(Array, Ed, It, Git, All)
#define FREE_POOL(Type, Ce, Desc)
#define HASH_FREE(Hash)
Typedefs
typedef struct _Edje_Drag_Items Edje_Drag_Items
typedef struct _Edje_Table_Items Edje_Table_Items
Functions
void _edje_collection_free (Edje_File *edf, Edje_Part_Collection *ec, Edje_Part_Collection_Directory_Entry *ce)
void _edje_collection_free_part_description_clean (int type, Edje_Part_Description_Common *desc, Eina_Bool free_strings)
void _edje_collection_free_part_description_free (int type, Edje_Part_Description_Common *desc, Edje_Part_Collection_Directory_Entry *ce, Eina_Bool free_strings)
void _edje_file_add (Edje *ed)
void _edje_file_del (Edje *ed)
void _edje_file_free (Edje_File *edf)
int _edje_object_file_set_internal (Evas_Object *obj, const char *file, const char *group, const char *parent, Eina_List *group_path)
void _edje_programs_patterns_clean (Edje *ed)
void _edje_programs_patterns_init (Edje *ed)
EAPI Eina_List * edje_file_collection_list (const char *file)
Get a list of groups in an edje file.
EAPI void edje_file_collection_list_free (Eina_List *lst)
Free file collection list.
EAPI char * edje_file_data_get (const char *file, const char *key)
Get data from the file level data block of an edje file.
EAPI Eina_Bool edje_file_group_exists (const char *file, const char *glob)
Determine whether a group matching glob exists in an edje file.
EAPI const char * edje_load_error_str (Edje_Load_Error error)
Converts the given Edje file load error code into a string describing it in English.
EAPI void edje_object_file_get (const Evas_Object *obj, const char **file, const char **group)
Get the file and group name that a given Edje object is bound to.
EAPI Eina_Bool edje_object_file_set (Evas_Object *obj, const char *file, const char *group)
Sets the EDJ file (and group within it) to load an Edje object's contents from.
EAPI Edje_Load_Error edje_object_load_error_get (const Evas_Object *obj)
Gets the (last) file loading error for a given Edje object.
Macro Definition Documentation
EDJE_DUMP_PROGRAM
#define EDJE_DUMP_PROGRAM (Section)
Value:
       for (i = 0; i < ed->collection->programs.Section##_count; i++)   \
     INF(#Section" for ('%s', '%s')", ed->collection->programs.Section[i]->signal, ed->collection->programs.Section[i]->source);
EDJE_LOAD_BUILD_TABLE
#define EDJE_LOAD_BUILD_TABLE (Array, Ed, It, Tmp)
Value:
               for (It = 0; It < Ed->collection->programs.Array##_count; ++It) \
             {                      \
                Tmp = Ed->collection->programs.Array[It];   \
                Ed->table_programs[Tmp->id] = Tmp;      \
             }
EDJE_LOAD_PROGRAM_FREE
#define EDJE_LOAD_PROGRAM_FREE (Array, Ec, It, FreeStrings)
Value:
   for (It = 0; It < Ec->programs.Array##_count; ++It)      \
     _edje_program_free(Ec->programs.Array[It], FreeStrings);   \
   free(Ec->programs.Array);
EDJE_LOAD_PROGRAMS_ADD
#define EDJE_LOAD_PROGRAMS_ADD (Array, Ed, It, Git, All)
Value:
   for (It = 0; It < Ed->collection->programs.Array##_count; ++It, ++Git) \
     All[Git] = Ed->collection->programs.Array[It];
FREE_POOL
#define FREE_POOL (Type, Ce, Desc)
Value:
   case EDJE_PART_TYPE_##Type: eina_mempool_free(Ce->mp.Type, Desc);    \
                               ce->count.Type--;                        \
                               break;
HASH_FREE
#define HASH_FREE (Hash)
Value:
   if (Hash) eina_hash_free(Hash);      \
   Hash = NULL;
Typedef Documentation
Edje_Drag_Items
typedef struct _Edje_Drag_Items Edje_Drag_Items
Edje_Table_Items
typedef struct _Edje_Table_Items Edje_Table_Items
Function Documentation
_edje_collection_free()
void _edje_collection_free (Edje_File * edf, Edje_Part_Collection * ec, Edje_Part_Collection_Directory_Entry * ce)
References _edje_collection_free_part_description_clean(), _edje_embryo_script_shutdown(), _edje_lua2_script_unload(), _Edje_Part_Collection::alias, _Edje_Part_Collection::aliased, _Edje_Part_Collection::data, _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, _Edje_Part_Description_List::desc_rtl, EDJE_LOAD_PROGRAM_FREE, _Edje_File::free_strings, _Edje_Part::items, _Edje_Part_Collection_Directory_Entry::mp, _Edje_Part_Collection_Directory_Entry::mp_rtl, _Edje_Part::name, _Edje_Part::other, _Edje_Part_Collection_Directory_Entry::part, _Edje_Part_Collection::parts, _Edje_Part_Collection::parts_count, _Edje_Part_Collection_Directory_Entry::ref, _Edje_Part_Collection::script, and _Edje_Part::type.
Referenced by _edje_cache_coll_flush(), and _edje_cache_coll_unref().
_edje_collection_free_part_description_clean()
void _edje_collection_free_part_description_clean (int type, Edje_Part_Description_Common * desc, Eina_Bool free_strings)
References _edje_external_params_free(), _Edje_Part_Description_Common::color_class, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_IMAGE, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part_Description_External::external_params, _Edje_Part_Description_Spec_Text::font, _Edje_Part_Description_Image::image, _Edje_String::str, _Edje_Part_Description_Spec_Text::style, _Edje_Part_Description_Spec_Text::text, _Edje_Part_Description_Text::text, _Edje_Part_Description_Spec_Text::text_class, _Edje_Part_Description_Spec_Image::tweens, _Edje_Part_Description_Spec_Image::tweens_count, and type.
Referenced by _edje_collection_free(), _edje_collection_free_part_description_free(), and _edje_file_del().
_edje_collection_free_part_description_free()
void _edje_collection_free_part_description_free (int type, Edje_Part_Description_Common * desc, Edje_Part_Collection_Directory_Entry * ce, Eina_Bool free_strings)
References _edje_collection_free_part_description_clean(), FREE_POOL, and type.
_edje_file_add()
void _edje_file_add (Edje * ed)
References _edje_cache_file_coll_open(), _edje_cache_file_unref(), _edje_edd_edje_file, _Edje::collection, _Edje::file, _Edje::group, _Edje::load_error, and _Edje::path.
_edje_file_del()
void _edje_file_del (Edje * ed)
References _edje_anim_count, _edje_animators, _edje_block_violate(), _edje_box_layout_free_data(), _edje_cache_coll_unref(), _edje_cache_file_unref(), _edje_callbacks_del(), _edje_callbacks_focus_del(), _edje_collection_free_part_description_clean(), _edje_color_class_on_del(), _edje_entry_real_part_shutdown(), _edje_entry_shutdown(), _edje_external_parsed_params_free(), _edje_freeze_calc_count, _edje_freeze_calc_list, _edje_lua2_script_shutdown(), _edje_message_del(), _edje_programs_patterns_clean(), _edje_real_part_mp, _edje_real_part_state_mp, _edje_real_part_swallow_clear(), _edje_subobj_unregister(), _edje_text_part_on_del(), _edje_textblock_styles_del(), _edje_unref(), _edje_user_definition_free(), _edje_var_shutdown(), _Edje::actions, _Edje_Real_Part::anim, _Edje::collection, _Edje_Real_Part::custom, _Edje_Real_Part_State::description, _Edje_Real_Part::drag, _Edje_Real_Part::edje, EDJE_ENTRY_EDIT_MODE_NONE, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_GROUP, _Edje_Part::entry_mode, _Edje_Real_Part_State::external_params, _Edje::file, _Edje::focused_part, _Edje_File::free_strings, _Edje::freeze_calc, _Edje::groups, _Edje_Real_Part::items, _Edje::L, _Edje::obj, _Edje_Real_Part::object, _Edje_Real_Part::param1, _Edje_Real_Part::param2, _Edje_Real_Part::part, _Edje_Part_Collection::parts, _Edje_Part_Collection::parts_count, _Edje::pending_actions, _Edje_Real_Part_State::set, _Edje::subobjs, _Edje_Real_Part::swallowed_object, _Edje::table_parts, _Edje::table_parts_size, _Edje::table_programs, _Edje::table_programs_size, _Edje_Real_Part::text, _Edje_Pending_Program::timer, _Edje_Part::type, and _Edje::user_defined.
Referenced by _edje_del().
_edje_file_free()
void _edje_file_free (Edje_File * edf)
References _edje_cache_coll_flush(), _edje_textblock_style_cleanup(), _Edje_File::collection, _Edje_File::collection_cache, _Edje_File::collection_patterns, _Edje_File::color_classes, _Edje_File::color_hash, _Edje_File::compiler, _Edje_File::data, edje_match_patterns_free(), _Edje_File::ef, _Edje_External_Directory::entries, _Edje_Image_Directory::entries, _Edje_Image_Directory_Set::entries, _Edje_Image_Directory::entries_count, _Edje_Image_Directory_Entry::entry, _Edje_File::external_dir, _Edje_File::fonts, _Edje_File::free_strings, HASH_FREE, _Edje_File::image_dir, _Edje_Sound_Sample::name, _Edje_Sound_Tone::name, _Edje_Color_Class::name, _Edje_File::path, _Edje_Sound_Directory::samples, _Edje_Sound_Directory::samples_count, _Edje_Image_Directory::sets, _Edje_Image_Directory::sets_count, _Edje_Sound_Sample::snd_src, _Edje_File::sound_dir, _Edje_Sound_Directory::tones, and _Edje_Sound_Directory::tones_count.
Referenced by _edje_cache_file_unref().
_edje_object_file_set_internal()
int _edje_object_file_set_internal (Evas_Object * obj, const char * file, const char * group, const char * parent, Eina_List * group_path)
References _edje_fetch(), _Edje::file, _Edje::group, _Edje_File::mtime, and _Edje::path.
_edje_programs_patterns_clean()
void _edje_programs_patterns_clean (Edje * ed)
References _edje_signals_sources_patterns_clean(), edje_match_signal_source_free(), _Edje_Signals_Sources_Patterns::exact_match, _Edje::patterns, _Edje_Signals_Sources_Patterns::programs, _Edje::programs, and _Edje_Signals_Sources_Patterns::u.
Referenced by _edje_file_del().
_edje_programs_patterns_init()
void _edje_programs_patterns_init (Edje * ed)
References _Edje::collection, EDJE_DUMP_PROGRAM, EDJE_LOAD_PROGRAMS_ADD, edje_match_program_hash_build(), edje_match_programs_signal_init(), edje_match_programs_source_init(), _Edje_Signals_Sources_Patterns::exact_match, _Edje_Part_Collection::fnmatch_count, _Edje::group, INF, _Edje_Part_Collection::nocmp_count, _Edje::patterns, _Edje_Part_Collection::programs, _Edje_Signals_Sources_Patterns::programs, _Edje::programs, _Edje_Signals_Sources_Patterns::signals_patterns, _Edje_Signals_Sources_Patterns::sources_patterns, _Edje_Part_Collection::strcmp, _Edje_Part_Collection::strcmp_count, _Edje_Part_Collection::strncmp_count, _Edje_Part_Collection::strrncmp_count, and _Edje_Signals_Sources_Patterns::u.
edje_file_collection_list()
EAPI Eina_List* edje_file_collection_list (const char * file)
Get a list of groups in an edje file.
Parameters
file The path to the edje file
Returns
The Eina_List of group names (char *)
Note: the list must be freed using edje_file_collection_list_free() when you are done with it.
References _edje_cache_file_coll_open(), _edje_cache_file_unref(), and _Edje_File::collection.
edje_file_collection_list_free()
EAPI void edje_file_collection_list_free (Eina_List * lst)
Free file collection list.
Parameters
lst The Eina_List of groups
Frees the list returned by edje_file_collection_list().
edje_file_data_get()
EAPI char* edje_file_data_get (const char * file, const char * key)
Get data from the file level data block of an edje file.
Parameters
file The path to the .edj file
key The data key
Returns
The string value of the data. Must be freed by the user when no longer needed.
If an edje file is built from the following edc:
data { item: "key1" "value1"; item: "key2" "value2"; } collections { ... }
Then, edje_file_data_get("key1") will return "value1"
References _edje_cache_file_coll_open(), _edje_cache_file_unref(), _Edje_File::data, and edje_string_get().
edje_file_group_exists()
EAPI Eina_Bool edje_file_group_exists (const char * file, const char * glob)
Determine whether a group matching glob exists in an edje file.
Parameters
file The file path
glob A glob to match on
Returns
1 if a match is found, 0 otherwise
References _edje_cache_file_coll_open(), _edje_cache_file_unref(), _Edje_File::collection, _Edje_File::collection_patterns, edje_match_collection_dir_exec(), edje_match_collection_dir_init(), edje_match_patterns_free(), and INF.
edje_load_error_str()
EAPI const char* edje_load_error_str (Edje_Load_Error error)
Converts the given Edje file load error code into a string describing it in English.
Parameters
error the error code, a value in Edje_Load_Error.
Returns
Always returns a valid string. If the given error is not supported, "Unknown error" is returned.
edje_object_file_set() is a function which sets an error value, afterwards, which can be fetched with edje_object_load_error_get(). The function in question is meant to be used in conjunction with the latter, for pretty-printing any possible error cause.
References EDJE_LOAD_ERROR_CORRUPT_FILE, EDJE_LOAD_ERROR_DOES_NOT_EXIST, EDJE_LOAD_ERROR_GENERIC, EDJE_LOAD_ERROR_INCOMPATIBLE_FILE, EDJE_LOAD_ERROR_NONE, EDJE_LOAD_ERROR_PERMISSION_DENIED, EDJE_LOAD_ERROR_RECURSIVE_REFERENCE, EDJE_LOAD_ERROR_RESOURCE_ALLOCATION_FAILED, EDJE_LOAD_ERROR_UNKNOWN_COLLECTION, and EDJE_LOAD_ERROR_UNKNOWN_FORMAT.
edje_object_file_get()
EAPI void edje_object_file_get (const Evas_Object * obj, const char ** file, const char ** group)
Get the file and group name that a given Edje object is bound to.
Parameters
obj A handle to an Edje object
file A pointer to a variable whero to store the file's path
group A pointer to a variable where to store the group name in
This gets the EDJ file's path, with the respective group set for the given Edje object. If obj is either not an Edje file, or has not had its file/group set previously, by edje_object_file_set(), then both file and group will be set to NULL, indicating an error.
See also
edje_object_file_set()
Note
Use NULL pointers on the file/group components you're not interested in: they'll be ignored by the function.
References _edje_fetch(), _Edje::group, and _Edje::path.
edje_object_file_set()
EAPI Eina_Bool edje_object_file_set (Evas_Object * obj, const char * file, const char * group)
Sets the EDJ file (and group within it) to load an Edje object's contents from.
Parameters
obj A handle to an Edje object
file The path to the EDJ file to load from
group The name of the group, in file, which implements an Edje object
Returns
EINA_TRUE, on success or EINA_FALSE, on errors (check edje_object_load_error_get() after this call to get errors causes)
Edje expects EDJ files, which are theming objects' descriptions and resources packed together in an EET file, to read Edje object definitions from. They usually are created with the .edj extension. EDJ files, in turn, are assembled from textual object description files, where one describes Edje objects declaratively – the EDC files (see the syntax for those files).
Those description files were designed so that many Edje object definitions – also called groups (or collections) – could be packed together in the same EDJ file, so that a whole application's theme could be packed in one file only. This is the reason for the group argument.
Use this function after you instantiate a new Edje object, so that you can "give him life", telling where to get its contents from.
See also
edje_object_add()
edje_object_file_get()
References _edje_fetch(), _edje_object_orientation_inform(), _Edje::api, and _Edje_Smart_Api::file_set.
edje_object_load_error_get()
EAPI Edje_Load_Error edje_object_load_error_get (const Evas_Object * obj)
Gets the (last) file loading error for a given Edje object.
Parameters
obj A handlet to an Edje object
Returns
The Edje loading error, one of:
EDJE_LOAD_ERROR_NONE
EDJE_LOAD_ERROR_GENERIC
EDJE_LOAD_ERROR_DOES_NOT_EXIST
EDJE_LOAD_ERROR_PERMISSION_DENIED
EDJE_LOAD_ERROR_RESOURCE_ALLOCATION_FAILED
EDJE_LOAD_ERROR_CORRUPT_FILE
EDJE_LOAD_ERROR_UNKNOWN_FORMAT
EDJE_LOAD_ERROR_INCOMPATIBLE_FILE
EDJE_LOAD_ERROR_UNKNOWN_COLLECTION
EDJE_LOAD_ERROR_RECURSIVE_REFERENCE
This function is meant to be used after an Edje EDJ file loading, what takes place with the edje_object_file_set() function. If that function does not return EINA_TRUE, one should check for the reason of failure with this one.
See also
edje_load_error_str()
References _edje_fetch(), EDJE_LOAD_ERROR_NONE, and _Edje::load_error.
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59