src/lib/edje_text.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_text.c File Reference
Macros
#define _ELLIP_STR "\xE2\x80\xA6"
Functions
const char * _edje_text_class_font_get (Edje *ed, Edje_Part_Description_Text *chosen_desc, int *size, char **free_later)
void _edje_text_init (void)
void _edje_text_part_on_add (Edje *ed, Edje_Real_Part *ep)
void _edje_text_part_on_del (Edje *ed, Edje_Part *pt)
void _edje_text_recalc_apply (Edje *ed, Edje_Real_Part *ep, Edje_Calc_Params *params, Edje_Part_Description_Text *chosen_desc)
Evas_Font_Size _edje_text_size_calc (Evas_Font_Size size, Edje_Text_Class *tc)
Macro Definition Documentation
_ELLIP_STR
#define _ELLIP_STR "\xE2\x80\xA6"
Function Documentation
_edje_text_class_font_get()
const char* _edje_text_class_font_get (Edje * ed, Edje_Part_Description_Text * chosen_desc, int * size, char ** free_later)
References _edje_text_class_find(), edje_string_get(), _Edje_Part_Description_Spec_Text::font, _Edje_Part_Description_Spec_Text::size, _Edje_Part_Description_Text::text, and _Edje_Part_Description_Spec_Text::text_class.
Referenced by _edje_text_recalc_apply().
_edje_text_init()
void _edje_text_init (void)
_edje_text_part_on_add()
void _edje_text_part_on_add (Edje * ed, Edje_Real_Part * ep)
References _edje_text_class_member_add(), _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, EDJE_PART_TYPE_TEXT, _Edje_Part::other, _Edje_Real_Part::part, _Edje_Part_Description_Text::text, _Edje_Part_Description_Spec_Text::text_class, and _Edje_Part::type.
_edje_text_part_on_del()
void _edje_text_part_on_del (Edje * ed, Edje_Part * pt)
References _edje_text_class_member_del(), _Edje_Part::default_desc, _Edje_Part_Description_List::desc, _Edje_Part_Description_List::desc_count, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, _Edje_Part::other, _Edje_Part_Description_Text::text, _Edje_Part_Description_Spec_Text::text_class, and _Edje_Part::type.
Referenced by _edje_file_del().
_edje_text_recalc_apply()
void _edje_text_recalc_apply (Edje * ed, Edje_Real_Part * ep, Edje_Calc_Params * params, Edje_Part_Description_Text * chosen_desc)
References _edje_fontset_append, _edje_scale, _edje_text_class_font_get(), alloca(), edje_string_get(), _Edje::file, _Edje_Part_Description_Spec_Text::fit_x, _Edje_Part_Description_Spec_Text::fit_y, FLOAT_T, _Edje_File::fonts, _Edje_Calc_Params::h, _Edje_Real_Part::object, _Edje_Real_Part::part, _Edje::path, _Edje_Part::scale, _Edje::scale, _Edje_Part_Description_Spec_Text::text, _Edje_Part_Description_Text::text, _Edje_Calc_Params::text, _Edje_Real_Part::text, TO_DOUBLE, _Edje_Calc_Params::type, and _Edje_Calc_Params::w.
_edje_text_size_calc()
Evas_Font_Size _edje_text_size_calc (Evas_Font_Size size, Edje_Text_Class * tc)
References _Edje_Text_Class::size.
Referenced by _edje_textblock_style_all_update().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59