src/lib/edje_message_queue.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_message_queue.c File Reference
Functions
void _edje_message_cb_set (Edje *ed, void(*func)(void *data, Evas_Object *obj, Edje_Message_Type type, int id, void *msg), void *data)
void _edje_message_del (Edje *ed)
void _edje_message_free (Edje_Message *em)
void _edje_message_init (void)
Edje_Message * _edje_message_new (Edje *ed, Edje_Queue queue, Edje_Message_Type type, int id)
void _edje_message_parameters_push (Edje_Message *em)
void _edje_message_process (Edje_Message *em)
void _edje_message_propornot_send (Edje *ed, Edje_Queue queue, Edje_Message_Type type, int id, void *emsg, Eina_Bool prop)
void _edje_message_queue_clear (void)
void _edje_message_queue_process (void)
void _edje_message_send (Edje *ed, Edje_Queue queue, Edje_Message_Type type, int id, void *emsg)
void _edje_message_shutdown (void)
EAPI void edje_message_signal_process (void)
Process all queued up edje messages.
EAPI void edje_object_message_handler_set (Evas_Object *obj, Edje_Message_Handler_Cb func, void *data)
Set an Edje message handler function for a given Edje object.
EAPI void edje_object_message_send (Evas_Object *obj, Edje_Message_Type type, int id, void *msg)
Send an (Edje) message to a given Edje object.
EAPI void edje_object_message_signal_process (Evas_Object *obj)
Process an object's message queue.
Function Documentation
_edje_message_cb_set()
void _edje_message_cb_set (Edje * ed, void(*)(void *data, Evas_Object *obj, Edje_Message_Type type, int id, void *msg) func, void * data)
References _edje_fetch(), _Edje::data, _Edje::func, _Edje::message, and _Edje::subobjs.
Referenced by edje_object_message_handler_set().
_edje_message_del()
void _edje_message_del (Edje * ed)
References _Edje::message, and _Edje::num.
Referenced by _edje_del(), and _edje_file_del().
_edje_message_free()
void _edje_message_free (Edje_Message * em)
References _Edje_Message_String_Set::count, _Edje_Message_Signal_Data::data, _Edje_Message_Signal::data, EDJE_MESSAGE_FLOAT, EDJE_MESSAGE_FLOAT_SET, EDJE_MESSAGE_INT, EDJE_MESSAGE_INT_SET, EDJE_MESSAGE_NONE, EDJE_MESSAGE_SIGNAL, EDJE_MESSAGE_STRING, EDJE_MESSAGE_STRING_FLOAT, EDJE_MESSAGE_STRING_FLOAT_SET, EDJE_MESSAGE_STRING_INT, EDJE_MESSAGE_STRING_INT_SET, EDJE_MESSAGE_STRING_SET, _Edje_Message_Signal_Data::free_func, _Edje_Message::msg, _Edje_Message_Signal_Data::ref, _Edje_Message_Signal::sig, _Edje_Message_Signal::src, _Edje_Message_String::str, _Edje_Message_String_Set::str, _Edje_Message_String_Int::str, _Edje_Message_String_Float::str, _Edje_Message_String_Int_Set::str, _Edje_Message_String_Float_Set::str, and _Edje_Message::type.
_edje_message_init()
void _edje_message_init (void)
_edje_message_new()
Edje_Message* _edje_message_new (Edje * ed, Edje_Queue queue, Edje_Message_Type type, int id)
References _Edje_Message::edje, _Edje_Message::id, _Edje::message, _Edje::num, _Edje_Message::queue, type, and _Edje_Message::type.
Referenced by _edje_message_propornot_send().
_edje_message_parameters_push()
void _edje_message_parameters_push (Edje_Message * em)
References _Edje::collection, _Edje_Message::edje, EDJE_MESSAGE_FLOAT, EDJE_MESSAGE_FLOAT_SET, EDJE_MESSAGE_INT, EDJE_MESSAGE_INT_SET, EDJE_MESSAGE_NONE, EDJE_MESSAGE_STRING, EDJE_MESSAGE_STRING_FLOAT, EDJE_MESSAGE_STRING_FLOAT_SET, EDJE_MESSAGE_STRING_INT, EDJE_MESSAGE_STRING_INT_SET, EDJE_MESSAGE_STRING_SET, _Edje_Message::id, _Edje_Message::msg, _Edje_Part_Collection::script, and _Edje_Message::type.
Referenced by _edje_message_process(), and _edje_script_only_message().
_edje_message_process()
void _edje_message_process (Edje_Message * em)
References _edje_embryo_globals_init(), _edje_embryo_script_reset(), _edje_emit_handle(), _edje_lua_script_only_message(), _edje_message_parameters_push(), _edje_script_only(), _edje_script_only_message(), _Edje::collection, _Edje::data, _Edje_Message::edje, EDJE_MESSAGE_SIGNAL, EDJE_QUEUE_APP, ERR, _Edje::file, _Edje::func, _Edje_Message::id, _Edje::L, _Edje::message, _Edje_Message::msg, _Edje::obj, _Edje_Part_Collection::part, _Edje_File::path, _Edje_Message::propagated, _Edje_Message::queue, _Edje_Part_Collection::script, and _Edje_Message::type.
_edje_message_propornot_send()
void _edje_message_propornot_send (Edje * ed, Edje_Queue queue, Edje_Message_Type type, int id, void * emsg, Eina_Bool prop)
References _edje_message_new(), _Edje_Message::propagated, and type.
Referenced by _edje_message_send().
_edje_message_queue_clear()
void _edje_message_queue_clear (void)
Referenced by _edje_message_shutdown().
_edje_message_queue_process()
void _edje_message_queue_process (void)
Referenced by edje_message_signal_process().
_edje_message_send()
void _edje_message_send (Edje * ed, Edje_Queue queue, Edje_Message_Type type, int id, void * emsg)
References _edje_message_propornot_send(), and type.
Referenced by _edje_emit_full().
_edje_message_shutdown()
void _edje_message_shutdown (void)
References _edje_message_queue_clear().
edje_message_signal_process()
EAPI void edje_message_signal_process (void)
Process all queued up edje messages.
This function triggers the processing of messages addressed to any (alive) edje objects.
References _edje_message_queue_process().
edje_object_message_handler_set()
EAPI void edje_object_message_handler_set (Evas_Object * obj, Edje_Message_Handler_Cb func, void * data)
Set an Edje message handler function for a given Edje object.
Parameters
obj A handle to an Edje object
func The function to handle messages coming from obj
data Auxiliary data to be passed to func
Edje messages are one of the communication interfaces between code and a given Edje object's theme. With messages, one can communicate values beyond strings (which are the subject of Edje signals – see edje_object_signal_emit()), like float and integer numbers. Moreover, messages can be identified by integer numbers. See Edje_Message_Type for the full list of message types.
For scriptable programs on an Edje object's defining EDC file which send messages with the send_message() primitive, one can attach handler functions, to be called in the code which creates that object (see the syntax for EDC files).
This function associates a message handler function and the attached data pointer to the object obj.
See also
edje_object_message_send()
References _edje_fetch(), and _edje_message_cb_set().
edje_object_message_send()
EAPI void edje_object_message_send (Evas_Object * obj, Edje_Message_Type type, int id, void * msg)
Send an (Edje) message to a given Edje object.
Parameters
obj A handle to an Edje object
type The type of message to send to obj
id A identification number for the message to be sent
msg The message's body, a struct depending on type
This function sends an Edje message to obj and to all of its child objects, if it has any (swallowed objects are one kind of child object). type and msg must be matched accordingly, as documented in Edje_Message_Type.
The id argument as a form of code and theme defining a common interface on message communication. One should define the same IDs on both code and EDC declaration (see the syntax for EDC files), to individualize messages (binding them to a given context).
The function to handle messages arriving from obj is set with edje_object_message_handler_set().
Referenced by _edje_emit_full().
edje_object_message_signal_process()
EAPI void edje_object_message_signal_process (Evas_Object * obj)
Process an object's message queue.
Parameters
obj A handle to an Edje object.
This function goes through the object message queue processing the pending messages for this specific Edje object. Normally they'd be processed only at idle time.
References _edje_fetch(), and _Edje::groups.
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59