src/lib/edje_callbacks.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_callbacks.c File Reference
Functions
void _edje_callbacks_add (Evas_Object *obj, Edje *ed, Edje_Real_Part *rp)
void _edje_callbacks_del (Evas_Object *obj, Edje *ed)
void _edje_callbacks_focus_add (Evas_Object *obj, Edje *ed, Edje_Real_Part *rp)
void _edje_callbacks_focus_del (Evas_Object *obj, Edje *ed)
Eina_Bool _edje_pending_timer_cb (void *data)
Eina_Bool _edje_timer_cb (void *data __UNUSED__)
Function Documentation
_edje_callbacks_add()
void _edje_callbacks_add (Evas_Object * obj, Edje * ed, Edje_Real_Part * rp)
Referenced by edje_edit_part_mouse_events_set().
_edje_callbacks_del()
void _edje_callbacks_del (Evas_Object * obj, Edje * ed)
Referenced by _edje_file_del(), _edje_real_part_swallow_clear(), and edje_edit_part_mouse_events_set().
_edje_callbacks_focus_add()
void _edje_callbacks_focus_add (Evas_Object * obj, Edje * ed, Edje_Real_Part * rp)
_edje_callbacks_focus_del()
void _edje_callbacks_focus_del (Evas_Object * obj, Edje * ed)
Referenced by _edje_file_del(), and _edje_real_part_swallow_clear().
_edje_pending_timer_cb()
Eina_Bool _edje_pending_timer_cb (void * data)
References _edje_program_run(), _Edje_Pending_Program::edje, _Edje::pending_actions, and _Edje_Pending_Program::program.
Referenced by _edje_program_run().
_edje_timer_cb()
Eina_Bool _edje_timer_cb (void *data __UNUSED__)
References _edje_anim_count, _edje_animators, _edje_block(), _edje_block_break(), _edje_freeze(), _edje_program_run_iterate(), _edje_ref(), _edje_thaw(), _edje_timer, _edje_unblock(), _edje_unref(), _Edje::actions, _Edje::delete_me, _Edje_Running_Program::delete_me, _Edje_Running_Program::edje, _Edje::paused, and _Edje::walking_actions.
Referenced by _edje_program_run().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59