src/lib/edje_lua2.c File Reference
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Edje Documentation at Tue Nov 5 2013
Files
Edje Edit API
Examples
LUA scripting
Edje API
EDC Reference
Releted Pages
Main Page
edje_lua2.c File Reference
Data Structures
struct _Edje_Lua_Alloc
struct _Edje_Lua_Animator
struct _Edje_Lua_Evas_Object
struct _Edje_Lua_Map
struct _Edje_Lua_Obj
struct _Edje_Lua_Timer
struct _Edje_Lua_Transition
Macros
#define _ELUA_PLANT_EVAS_OBJECT(type, meta, free)
#define ELO "|-ELO"
#define IMAGES "edje/images/"
#define LC(...) EINA_LOG_DOM_CRIT(_log_domain, __VA_ARGS__)
#define LD(...) EINA_LOG_DOM_DBG(_log_domain, __VA_ARGS__)
#define LE(...) EINA_LOG_DOM_ERR(_log_domain, __VA_ARGS__)
#define LI(...) EINA_LOG_DOM_INFO(_log_domain, __VA_ARGS__)
#define LW(...) EINA_LOG_DOM_WARN(_log_domain, __VA_ARGS__)
#define MAX_LUA_MEM (4 * (1024 * 1024))
#define RASTER_FORGOT_WHY "this is here."
Typedefs
typedef struct _Edje_Lua_Alloc Edje_Lua_Alloc
typedef struct _Edje_Lua_Animator Edje_Lua_Animator
typedef struct _Edje_Lua_Evas_Object Edje_Lua_Evas_Object
typedef struct _Edje_Lua_Map Edje_Lua_Map
typedef struct _Edje_Lua_Obj Edje_Lua_Obj
typedef struct _Edje_Lua_Timer Edje_Lua_Timer
typedef struct _Edje_Lua_Transition Edje_Lua_Transition
Functions
void _edje_lua2_error_full (const char *file, const char *fnc, int line, lua_State *L, int err_code)
void _edje_lua2_script_func_hide (Edje *ed)
void _edje_lua2_script_func_message (Edje *ed, Edje_Message *em)
void _edje_lua2_script_func_move (Edje *ed)
void _edje_lua2_script_func_resize (Edje *ed)
void _edje_lua2_script_func_show (Edje *ed)
void _edje_lua2_script_func_shutdown (Edje *ed)
void _edje_lua2_script_func_signal (Edje *ed, const char *sig, const char *src)
void _edje_lua2_script_init (Edje *ed)
void _edje_lua2_script_load (Edje_Part_Collection *edc __UNUSED__, void *data __UNUSED__, int size __UNUSED__)
void _edje_lua2_script_shutdown (Edje *ed)
void _edje_lua2_script_unload (Edje_Part_Collection *edc __UNUSED__)
Macro Definition Documentation
_ELUA_PLANT_EVAS_OBJECT
#define _ELUA_PLANT_EVAS_OBJECT (type, meta, free)
Value:
   Edje *ed = (Edje *)_elua_table_ptr_get(L, _elua_key);     \
   type *elo;                                                \
   elo = (type *)_elua_obj_new(L, ed, sizeof(type), meta);   \
   elo->obj.free_func = free;
ELO
#define ELO "|-ELO"
IMAGES
#define IMAGES "edje/images/"
LC
#define LC (...) EINA_LOG_DOM_CRIT(_log_domain, __VA_ARGS__)
LD
#define LD (...) EINA_LOG_DOM_DBG(_log_domain, __VA_ARGS__)
LE
#define LE (...) EINA_LOG_DOM_ERR(_log_domain, __VA_ARGS__)
LI
#define LI (...) EINA_LOG_DOM_INFO(_log_domain, __VA_ARGS__)
LW
#define LW (...) EINA_LOG_DOM_WARN(_log_domain, __VA_ARGS__)
MAX_LUA_MEM
#define MAX_LUA_MEM (4 * (1024 * 1024))
RASTER_FORGOT_WHY
#define RASTER_FORGOT_WHY "this is here."
Typedef Documentation
Edje_Lua_Alloc
typedef struct _Edje_Lua_Alloc Edje_Lua_Alloc
Edje_Lua_Animator
typedef struct _Edje_Lua_Animator Edje_Lua_Animator
Edje_Lua_Evas_Object
typedef struct _Edje_Lua_Evas_Object Edje_Lua_Evas_Object
Edje_Lua_Map
typedef struct _Edje_Lua_Map Edje_Lua_Map
Edje_Lua_Obj
typedef struct _Edje_Lua_Obj Edje_Lua_Obj
Edje_Lua_Timer
typedef struct _Edje_Lua_Timer Edje_Lua_Timer
Edje_Lua_Transition
typedef struct _Edje_Lua_Transition Edje_Lua_Transition
Function Documentation
_edje_lua2_error_full()
void _edje_lua2_error_full (const char * file, const char * fnc, int line, lua_State * L, int err_code)
References _edje_default_log_dom.
_edje_lua2_script_func_hide()
void _edje_lua2_script_func_hide (Edje * ed)
References _edje_lua2_error, and _Edje::L.
Referenced by _edje_lua_script_only_hide().
_edje_lua2_script_func_message()
void _edje_lua2_script_func_message (Edje * ed, Edje_Message * em)
References _edje_lua2_error, EDJE_MESSAGE_FLOAT, EDJE_MESSAGE_FLOAT_SET, EDJE_MESSAGE_INT, EDJE_MESSAGE_INT_SET, EDJE_MESSAGE_NONE, EDJE_MESSAGE_SIGNAL, EDJE_MESSAGE_STRING, EDJE_MESSAGE_STRING_FLOAT, EDJE_MESSAGE_STRING_FLOAT_SET, EDJE_MESSAGE_STRING_INT, EDJE_MESSAGE_STRING_INT_SET, EDJE_MESSAGE_STRING_SET, _Edje_Message::id, _Edje::L, _Edje_Message::msg, and _Edje_Message::type.
Referenced by _edje_lua_script_only_message().
_edje_lua2_script_func_move()
void _edje_lua2_script_func_move (Edje * ed)
References _edje_lua2_error, _Edje::L, _Edje::x, and _Edje::y.
Referenced by _edje_lua_script_only_move().
_edje_lua2_script_func_resize()
void _edje_lua2_script_func_resize (Edje * ed)
References _edje_lua2_error, _Edje::h, _Edje::L, and _Edje::w.
Referenced by _edje_lua_script_only_resize().
_edje_lua2_script_func_show()
void _edje_lua2_script_func_show (Edje * ed)
References _edje_lua2_error, and _Edje::L.
Referenced by _edje_lua_script_only_show().
_edje_lua2_script_func_shutdown()
void _edje_lua2_script_func_shutdown (Edje * ed)
References _edje_lua2_error, _edje_lua2_script_shutdown(), and _Edje::L.
Referenced by _edje_lua_script_only_shutdown().
_edje_lua2_script_func_signal()
void _edje_lua2_script_func_signal (Edje * ed, const char * sig, const char * src)
References _edje_lua2_error, and _Edje::L.
Referenced by _edje_emit_handle().
_edje_lua2_script_init()
void _edje_lua2_script_init (Edje * ed)
References _Edje::L, and MAX_LUA_MEM.
Referenced by _edje_lua_script_only_init().
_edje_lua2_script_load()
void _edje_lua2_script_load (Edje_Part_Collection *edc __UNUSED__, void *data __UNUSED__, int size __UNUSED__)
_edje_lua2_script_shutdown()
void _edje_lua2_script_shutdown (Edje * ed)
References ERR, _Edje_Lua_Obj::free_func, _Edje::L, and _Edje::lua_objs.
Referenced by _edje_file_del(), and _edje_lua2_script_func_shutdown().
_edje_lua2_script_unload()
void _edje_lua2_script_unload (Edje_Part_Collection *edc __UNUSED__)
Referenced by _edje_collection_free().
Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59