Tiler
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Eina Documentation at Tue Nov 5 2013
Files
Modules
Related Pages
Main Page
Tiler
Data Types
Data Structures
struct Eina_Tile_Grid_Info
Grid type of a tiler.
Typedefs
typedef struct _Eina_Tiler Eina_Tiler
Tiler type.
typedef struct Eina_Tile_Grid_Info Eina_Tile_Grid_Info
Grid type of a tiler.
typedef struct _Eina_Tile_Grid_Slicer Eina_Tile_Grid_Slicer
Functions
Eina_Tiler * eina_tiler_new (int w, int h)
Creates a new tiler with w width and h height.
void eina_tiler_free (Eina_Tiler *t)
Frees a tiler.
void eina_tiler_tile_size_set (Eina_Tiler *t, int w, int h)
Sets the size of tiles for a tiler.
Eina_Bool eina_tiler_rect_add (Eina_Tiler *t, const Eina_Rectangle *r)
Adds a rectangle to a tiler.
void eina_tiler_rect_del (Eina_Tiler *t, const Eina_Rectangle *r)
Removes a rectangle from a tiler.
void eina_tiler_clear (Eina_Tiler *t)
Removes all rectangles from tiles.
Eina_Iterator * eina_tiler_iterator_new (const Eina_Tiler *t)
Create a iterator to access the tilers calculated rectangles.
Eina_Iterator * eina_tile_grid_slicer_iterator_new (int x, int y, int w, int h, int tile_w, int tile_h)
Creates a new Eina_Iterator that iterates over a list of tiles.
static Eina_Bool eina_tile_grid_slicer_next (Eina_Tile_Grid_Slicer *slc, const Eina_Tile_Grid_Info **rect)
Iterates over the tiles set by eina_tile_grid_slicer_setup().
static Eina_Bool eina_tile_grid_slicer_setup (Eina_Tile_Grid_Slicer *slc, int x, int y, int w, int h, int tile_w, int tile_h)
Setup an Eina_Tile_Grid_Slicer struct.
Detailed Description
Warning
This is a very low level tool, in most situations(for example if you're using evas) you won't need this.
Basic usage
Eina_Tiler is a tool to facilitate calculations of which areas are damaged and thus need to be re-rendered. The basic usage of Eina_Tiler is to give it the size of your canvas and a set of rectangular areas that need re-rendering, from that and using heuristics it'll tell you an efficient way to re-render in the form of a set of non-overlapping rectangles that covers the whole area that needs re-rendering.
The following is pseudo-code showing some simple use of Eina_Tiler:
tiler = eina_tiler_new(MY_CANVAS_WIDTH, MY_CANVAS_HEIGHT);
EINA_LIST_FOREACH(list_of_areas_that_need_re_rendering, l, rect)
  eina_tiler_add(tiler, rect);
itr = eina_tiler_iterator_new(tiler);
EINA_ITERATOR_FOREACH(itr, rect)
  my_function_that_repaints_areas_of_the_canvas(rect);
See also
eina_tiler_new()
eina_tiler_rect_add()
eina_tiler_iterator_new()
Warning
There are no guarantees that this will be the most efficient way to re-render for any particular case.
Grid Slicer
Grid slicer and Eina_Tiler are usually used together, that is however not necessary, they can be used independently. Grid slicer provides an easy API to divide an area in tiles which is useful in certain applications to divide the area that will be rendered into tiles. It's customary to, then create one Eina_Tiler for each tile.
The following is pseudo-code showing a very simplified use of grid slicer together with Eina_Tiler:
itr = eina_tile_grid_slicer_iterator_new(0, 0, MY_CANVAS_WIDTH, MY_CANVAS_HEIGHT, TILE_WIDTH, TILE_HEIGHT);
EINA_ITERATOR_FOREACH(itr, grid_info)
  {
     tiler = eina_tiler_new(grid_info->rect.w, grid_info->rect.w);
     EINA_LIST_FOREACH(list_of_areas_that_need_re_rendering_in_this_tile, l, rect)
       eina_tiler_add(tiler, rect);
     itr = eina_tiler_iterator_new(tiler);
     EINA_ITERATOR_FOREACH(itr, rect)
     my_function_that_repaints_areas_of_the_canvas(rect);
  }
See also
eina_tiler_new()
eina_tiler_rect_add()
eina_tile_grid_slicer_setup()
eina_tile_grid_slicer_next()
eina_tile_grid_slicer_iterator_new()
Function Documentation
eina_tiler_new()
Eina_Tiler* eina_tiler_new (int w, int h)
Creates a new tiler with w width and h height.
Parameters
w Width of the tiler
h Height of the tiler
Returns
The newly created tiler
See also
eina_tiler_free()
Examples
eina_tiler_01.c.
References EINA_MAGIC_SET, and EINA_TRUE.
eina_tiler_free()
void eina_tiler_free (Eina_Tiler * t)
Frees a tiler.
Parameters
t The tiler to free.
This function frees t. It does not free the memory allocated for the elements of t.
Examples
eina_tiler_01.c.
eina_tiler_tile_size_set()
void eina_tiler_tile_size_set (Eina_Tiler * t, int w, int h)
Sets the size of tiles for a tiler.
Parameters
t The tiler whose tile size will be set.
w Width of the tiles.
h Height of the tiles.
Warning
w and h must be greater than zero, otherwise tile size won't be changed.
Tile size is not used!
References EINA_FALSE.
eina_tiler_rect_add()
Eina_Bool eina_tiler_rect_add (Eina_Tiler * t, const Eina_Rectangle * r)
Adds a rectangle to a tiler.
Parameters
t The tiler in which to add a container.
r The rectangle to be added.
Returns
EINA_TRUE on success, EINA_FALSE on failure.
See also
eina_tiler_rect_del()
Examples
eina_tiler_01.c.
References EINA_FALSE.
eina_tiler_rect_del()
void eina_tiler_rect_del (Eina_Tiler * t, const Eina_Rectangle * r)
Removes a rectangle from a tiler.
Parameters
t The tiler in which to add a container.
r The rectangle to be removed.
See also
eina_tiler_rect_add()
eina_tiler_clear()
eina_tiler_clear()
void eina_tiler_clear (Eina_Tiler * t)
Removes all rectangles from tiles.
Parameters
t The tiler to clear.
See also
eina_tiler_rect_del()
eina_tiler_iterator_new()
Eina_Iterator* eina_tiler_iterator_new (const Eina_Tiler * t)
Create a iterator to access the tilers calculated rectangles.
Parameters
t The tiler to iterate over.
Returns
A iterator containing Eina_Rectangle.
Examples
eina_tiler_01.c.
References EINA_MAGIC_SET, EINA_TRUE, FUNC_ITERATOR_FREE, FUNC_ITERATOR_GET_CONTAINER, and FUNC_ITERATOR_NEXT.
eina_tile_grid_slicer_iterator_new()
Eina_Iterator* eina_tile_grid_slicer_iterator_new (int x, int y, int w, int h, int tile_w, int tile_h)
Creates a new Eina_Iterator that iterates over a list of tiles.
Parameters
x X axis coordinate.
y Y axis coordinate.
w width.
h height.
tile_w tile width.
tile_h tile height.
Returns
A pointer to the Eina_Iterator. NULL on failure.
The region defined by x, y, w, h will be divided in to a grid of tiles of width tile_w and height tile_h, the returned iterator will iterate over every tile in the grid having as its data a Eina_Tile_Grid_Info.
Note
This is a convenience function, iterating over the returned iterator is equivalent to calling eina_tile_grid_slicer_setup() and calling eina_tile_grid_slicer_next() untill it returns EINA_FALSE.
References EINA_ERROR_OUT_OF_MEMORY, eina_error_set(), EINA_MAGIC_SET, eina_tile_grid_slicer_setup(), FUNC_ITERATOR_FREE, and FUNC_ITERATOR_NEXT.
eina_tile_grid_slicer_next()
static Eina_Bool eina_tile_grid_slicer_next (Eina_Tile_Grid_Slicer * slc, const Eina_Tile_Grid_Info ** rect) inline static
Iterates over the tiles set by eina_tile_grid_slicer_setup().
Parameters
slc Pointer to an Eina_Tile_Grid_Slicer struct.
rect Pointer to a struct Eina_Tile_Grid_Info *.
Returns
EINA_TRUE if the current rect is valid. EINA_FALSE if there is no more rects to iterate over (and thus the current one isn't valid).
This functions iterates over each Eina_Tile_Grid_Info *rect of the grid. eina_tile_grid_slicer_setup() must be called first, and *rect is only valid if this function returns EINA_TRUE. Its content shouldn't be modified.
Note
Consider using eina_tile_grid_slicer_iterator_new() instead.
eina_tile_grid_slicer_setup()
static Eina_Bool eina_tile_grid_slicer_setup (Eina_Tile_Grid_Slicer * slc, int x, int y, int w, int h, int tile_w, int tile_h) inline static
Setup an Eina_Tile_Grid_Slicer struct.
Parameters
slc Pointer to an Eina_Tile_Grid_Slicer struct.
x X axis coordinate.
y Y axis coordinate.
w width.
h height.
tile_w tile width.
tile_h tile height.
Returns
A pointer to the Eina_Iterator. NULL on failure.
The region defined by x, y, w, h will be divided in to a grid of tiles of width tile_w and height tile_h, slc can then be used with eina_tile_grid_slicer_next() to access each tile.
Note
Consider using eina_tile_grid_slicer_iterator_new() instead.
Referenced by eina_tile_grid_slicer_iterator_new().
Samsung Electronics is supporting the EFL Documentation Project Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59