Magic
Enlightenment
Beauty at your fingertips
Home News About Download Support Contribute Contact Tracker Docs
Eina Documentation at Tue Nov 5 2013
Files
Modules
Related Pages
Main Page
Magic
Tools
Eina_Magic provides run-time type-checking.
Macros
#define EINA_MAGIC_NONE 0x1234fedc
Random value for specifying that a structure using the magic feature has already been freed.
#define EINA_MAGIC Eina_Magic __magic;
Declaration of a variable of type Eina_Magic.
#define EINA_MAGIC_SET(d, m) (d)->__magic = (m)
Set the magic number of d to m.
#define EINA_MAGIC_CHECK(d, m) ((d) && ((d)->__magic == (m)))
Test if d is NULL or not, and if not NULL, if d->__eina_magic is equal to m.
#define EINA_MAGIC_FAIL(d, m)
Call eina_magic_fail() with the parameters d, d->__magic, m, FILE, FUNCTION and LINE.
Typedefs
typedef unsigned int Eina_Magic
An abstract type for a magic number.
Functions
const char * eina_magic_string_get (Eina_Magic magic)
Return the string associated to the given magic identifier.
Eina_Bool eina_magic_string_set (Eina_Magic magic, const char *magic_name)
Set the string associated to the given magic identifier.
Eina_Bool eina_magic_string_static_set (Eina_Magic magic, const char *magic_name)
Set the string associated to the given magic identifier.
void eina_magic_fail (void *d, Eina_Magic m, Eina_Magic req_m, const char *file, const char *fnc, int line)
Display a message or abort if a magic check failed.
Variables
Eina_Error EINA_ERROR_MAGIC_FAILED
Error identifier corresponding to magic check failure.
Detailed Description
Eina_Magic provides run-time type-checking.
C is a weak statically typed language, in other words, it will just check for types during compile time and any cast will make the compiler believe the type is correct.
In real world code we often need to deal with casts, either explicit or implicit by means of void*. We also need to resort to casts when doing inheritance in C.
Eina_Magic give us a way to do casts and still be certain of the type we are opearting on.
Note
It should be noted that it is considered good practice to disable Eina_Magic for production code. The reasoning is that any Eina_Magic errors should have been caught during testing and therefore there is no reason to incur the performance downside of Eina_Magic.
An example should elucidate matters.
Macro Definition Documentation
EINA_MAGIC_NONE
#define EINA_MAGIC_NONE 0x1234fedc
Random value for specifying that a structure using the magic feature has already been freed.
It is used by eina_magic_fail().
If the magic feature of Eina is disabled, EINA_MAGIC_NONE is just 0.
Examples
eina_magic_01.c.
EINA_MAGIC
#define EINA_MAGIC Eina_Magic __magic;
Declaration of a variable of type Eina_Magic.
To put in a structure when one wants to use the magic feature of Eina with the functions of that structure, like that:
struct Foo
{
   int i;
   EINA_MAGIC
};
If the magic feature of Eina is disabled, EINA_MAGIC does nothing.
Examples
eina_magic_01.c.
EINA_MAGIC_SET
#define EINA_MAGIC_SET (d, m) (d)->__magic = (m)
Set the magic number of d to m.
d must be a valid pointer to a structure holding an Eina magic number declaration. Use EINA_MAGIC to add such declaration.
If the magic feature of Eina is disabled, EINA_MAGIC_CHECK is just the value 0.
Examples
eina_magic_01.c.
EINA_MAGIC_CHECK
#define EINA_MAGIC_CHECK (d, m) ((d) && ((d)->__magic == (m)))
Test if d is NULL or not, and if not NULL, if d->__eina_magic is equal to m.
d must be a structure that holds an Eina magic number declaration. Use EINA_MAGIC to add such declaration.
If the magic feature of Eina is disabled, EINA_MAGIC_CHECK is just the value 1.
Examples
eina_magic_01.c.
EINA_MAGIC_FAIL
#define EINA_MAGIC_FAIL (d, m)
Value:
  eina_magic_fail((void *)(d),            \
                  (d) ? (d)->__magic : 0, \
                  (m),                    \
                  __FILE__,               \
                  __FUNCTION__,           \
                  __LINE__);
Call eina_magic_fail() with the parameters d, d->__magic, m, FILE, FUNCTION and LINE.
d must be a structure that holds an Eina magic number declaration. Use EINA_MAGIC to add such declaration.
If the magic feature of Eina is disabled, EINA_MAGIC_FAIL does nothing.
Examples
eina_magic_01.c.
Function Documentation
eina_magic_string_get()
const char* eina_magic_string_get (Eina_Magic magic)
Return the string associated to the given magic identifier.
Parameters
magic The magic identifier.
Returns
The string associated to the identifier.
This function returns the string associated to magic. Even if none are found this function still returns non NULL, in this case an identifier such as "(none)", "(undefined)" or "(unknown)".
The following identifiers may be returned whenever magic is invalid, with their meanings:
(none): no magic was registered exists at all.
(undefined): magic was registered and found, but no string associated.
(unknown): magic was not found in the registry.
Warning
The returned value must not be freed.
Referenced by eina_magic_fail().
eina_magic_string_set()
Eina_Bool eina_magic_string_set (Eina_Magic magic, const char * magic_name)
Set the string associated to the given magic identifier.
Parameters
magic The magic identifier.
magic_name The string associated to the identifier, must not be NULL.
Returns
EINA_TRUE on success, EINA_FALSE on failure.
This function sets the string magic_name to magic. It is not checked if number or string are already set, in which case you will end with duplicates. Internally, eina will make a copy of magic_name.
See also
eina_magic_string_static_set()
Examples
eina_magic_01.c.
eina_magic_string_static_set()
Eina_Bool eina_magic_string_static_set (Eina_Magic magic, const char * magic_name)
Set the string associated to the given magic identifier.
Parameters
magic The magic identifier.
magic_name The string associated to the identifier, must not be NULL.
Returns
EINA_TRUE on success, EINA_FALSE on failure.
This function sets the string magic_name to magic. It is not checked if number or string are already set, in which case you might end with duplicates. Eina will not make a copy of magic_name, this means that magic_name has to be a valid pointer for as long as magic is used.
See also
eina_magic_string_set()
Examples
eina_magic_01.c.
eina_magic_fail()
void eina_magic_fail (void * d, Eina_Magic m, Eina_Magic req_m, const char * file, const char * fnc, int line)
Display a message or abort if a magic check failed.
Parameters
d The checked data pointer.
m The magic identifer to check.
req_m The requested magic identifier to check.
file The file in which the magic check failed.
fnc The function in which the magic check failed.
line The line at which the magic check failed.
Warning
You should strongly consider using EINA_MAGIC_FAIL(d, m) instead.
This function displays an error message if a magic check has failed, using the following logic in the following order:
If d is NULL, a message warns about a NULL pointer.
Otherwise, if m is equal to EINA_MAGIC_NONE, a message warns about a handle that was already freed.
Otherwise, if m is equal to req_m, a message warns about a handle that is of wrong type.
Otherwise, a message warns you about ab-using that function...
If the environment variable EINA_LOG_ABORT is set, abort() is called and the program stops. It is useful for debugging programs with gdb.
References EINA_ERROR_MAGIC_FAILED, eina_error_set(), EINA_LOG_DOMAIN_GLOBAL, EINA_LOG_LEVEL_CRITICAL, eina_log_print(), EINA_MAGIC_NONE, and eina_magic_string_get().
Samsung Electronics is supporting the EFL Documentation Project Copyright ©2013 Enlightenment Docs generated Tue Nov 5 2013 19:12:59